### ISSUE TITLE
请问管理一个问题，很重要！

### ISSUE THREAD

**Issue by thumia** [getlantern/forum#1000]
专业版可以授权三台设备，但如果要更换已授权的设备要如何办？比如原来这台设备不用了，在不损失授权次数的情况下授权另一台新设备。我是马上就要遇到这个问题：手机面临固件升级，而我目前为第三方固件，是那种连手机型号都改变了的固件，过久要刷回官方版新固件，手机型号肯定会变。如果以后又打算刷个第三方呢，还有直接换手机的情况，会不会影响授权数量？电脑端同理。以上疑惑请指点一二，谢谢！

**Comment by p3rcya** [comment]
可以取消授权的
