### ISSUE TITLE
为什么不可以修改注册的邮箱？

### ISSUE THREAD

**Issue by joingreat** [getlantern/forum#10028]
想问一下：账号管理里面为什么不可以修改注册的邮箱——反过来要告诉所有人，A&B两个邮箱都是一起的么？

**Comment by Ghostwithout** [comment]
你好，如果需要修改邮箱，请提供购买凭证和备用邮箱，核实后可手工更改。谢谢！ @joingreat

**Comment by BTC1688** [comment]
你好，我也需要修改邮箱，麻烦与我联系，谢谢！ @Ghostwithout

**Comment by joingreat** [comment]
@Ghostwithout ，有管理员邮箱么？

**Comment by Ghostwithout** [comment]
请发送到support@getlantern.org，标题为更改邮箱。谢谢！ @BTC1688 @joingreat
