### ISSUE TITLE
全新来的不要买了，太坑了

### ISSUE THREAD

**Issue by lkd3063601** [getlantern/forum#1006]
哎，说多都是泪啊，刚开始免费的用着还行，后来付费就买了个专业版，真TM坑，更新到最新版本还是总登不上，时好时坏，大部分都是连不上的，还不如我后来找的免费的软件。钱白打了

**Comment by j782070772** [comment]
同，国内网站都上不了了。

**Comment by zhaqu** [comment]
所以说LZ你找到的什么免费的软件居然干过了收费的，一分钱一分货啊

**Comment by YOYOsheep** [comment]
我还是选择耐心等待作者出正式版。（可能是因为我有XX-NET先用着，所以不太急）

**Comment by xfhy1822** [comment]
蓝灯已经违背了最初的开发推广理念了~~~！！

自己搬起石头砸自己的脚，搞个捐赠多好，非搞强制收费的！（别说什么还在免费，免费流量实在感人，宁愿不用，免费翻墙工具比蓝灯大方‘；好用的多了去了）
这么玩所谓的P2P模式优势将变得毫无意义，代价就是失去之前积攒下的大量的免费客户群体，速度只会越变越慢！！跟普通VPN还有何区别？？

试问蓝灯最初的存在意义还有什么？一个最初的P2P模式翻墙工具还未普及，就将迎来终结，走向末路，变回传统的VPN模式吗？？

**Comment by Danie1s** [comment]
我觉得蓝灯的原作者已经卖给现在这个团队了,你们没有发现之前的页面都没有显示更新吗?你们没有发现之前的页面都是英文的,而现在变成全中文吗?蓝灯这个软件被原作者开发得比较成熟,然后现在这个团队看中了蓝灯,所以买下来,先进行免费和付费的策略,慢慢的就会变成全付费.但问题是现在这个团队根本没有实力去继续维护开发这个软件,所以也导致这么多问题出现.现在的蓝灯跟以前的已经不是同一个软件,有需要的话还有很多收费的,比蓝灯稳定的软件,没有入坑

**Comment by Danie1s** [comment]
我觉得蓝灯的原作者已经卖给现在这个团队了,你们没有发现之前的页面都没有显示更新吗?你们没有发现之前的页面都是英文的,而现在变成全中文吗?蓝灯这个软件被原作者开发得比较成熟,然后现在这个团队看中了蓝灯,所以买下来,先进行免费和付费的策略,慢慢的就会变成全付费.但问题是现在这个团队根本没有实力去继续维护开发这个软件,所以也导致这么多问题出现.现在的蓝灯跟以前的已经不是同一个软件,有需要的话还有很多收费的,比蓝灯稳定的软件,没必要入坑

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
