### ISSUE TITLE
关于退款

### ISSUE THREAD

**Issue by 130lin** [getlantern/forum#1007]
因为你们的无账号登陆方式
我给他们邮件他们怎么知道退给谁

**Comment by j782070772** [comment]
给退么？我发了邮件要求退款，没回应

**Comment by 130lin** [comment]
@j782070772 我也没用有回应

**Comment by j782070772** [comment]
@130lin 我已经发帖骂人了，我认为蓝灯现在这种毫无解释，毫无歉意的做法和骗子没什么两样。钱在谁手里谁就是大爷。就知道拿钱不知道做好服务，呵呵了。

**Comment by joefei** [comment]
我严重怀疑是不是有GFW的人混到蓝灯开发组去了，→_→。

**Comment by 47crusader** [comment]
我也希望能退款。。。专业版一直显示“”正在等待代理隧道响应”，什么都登不上

**Comment by rocknrollfly** [comment]
@joefei 
蓝灯有安全审计人员，请放心使用

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
