### ISSUE TITLE
诚信出售剩余17个月坑位，真心想买的加我QQ954455850，价格8元/月，点进来看图片。还有一个坑位，刚刚出了一个，来长期稳定优质占坑人员

### ISSUE THREAD

**Issue by 954455850** [getlantern/forum#10087]
![tim 20180618161917](https://user-images.githubusercontent.com/31529293/41525410-7956c66c-7313-11e8-9d9e-e81cfc4bd05c.png)

**Comment by 954455850** [comment]
![tim 20180618183429](https://user-images.githubusercontent.com/31529293/41531555-3efd2340-7326-11e8-9bef-1f218a09a6eb.png)

**Comment by xqzr** [comment]
加你没反应？
