### ISSUE TITLE
管理员好，修改登录邮箱，谢谢！

### ISSUE THREAD

**Issue by longer56789** [getlantern/forum#10093]
收到，谢谢。贴上购买记录就可以修改登录邮箱。

**Comment by longer56789** [comment]
@Ghostwithout ,管理员大大，帮忙处理一下，谢谢！

**Comment by Ghostwithout** [comment]
你好，麻烦提供下购买凭证，核实后可更改。谢谢！@longer56789

**Comment by longer56789** [comment]
![img_2130](https://user-images.githubusercontent.com/40330363/41691757-f6de0cfe-752e-11e8-9632-4e044483ded8.JPG)
@Ghostwithout

**Comment by longer56789** [comment]
![Uploading 支付记录.JPG…]()
@Ghostwithout ,这个是支付记录，请核实一下。

**Comment by longer56789** [comment]
![gmpz](https://user-images.githubusercontent.com/40330363/41696396-77d9f1d0-7546-11e8-871e-880f37fc0dd4.JPG)

@Ghostwithout 购买凭证，请核实，谢谢！

**Comment by Ghostwithout** [comment]
你好，已更改，谢谢！@longer56789

**Comment by longer56789** [comment]
购买记录验证过了，我撤掉了。
