### ISSUE TITLE
写上尊敬的管理员，帮修改下邮箱

### ISSUE THREAD

**Issue by 234704066** [getlantern/forum#10100]
当时注册时，邮箱填写错了，到现在都无法激活，麻烦您将lifeng@jarvisibim.com改为lifeng@jarvisbim.com，好让我们激活，谢谢！

**Comment by Ghostwithout** [comment]
你好，麻烦提供购买凭证，核实后可更改，谢谢！ @234704066

**Comment by 234704066** [comment]
![default](https://user-images.githubusercontent.com/17721279/41704340-9049007c-7568-11e8-9840-cb3665929789.jpg)
请尽处理，多谢！

**Comment by Ghostwithout** [comment]
你好，

请问你是在哪里购买的Lantern？应该是买到假的Lantern了。
首先，这是一家叫成都优博特的公司开发的假Lantern，而真正的Lantern是由国外的Brave New Software开发的；
其次，付款界面完全不同，请参考论坛其他要求更改邮箱的凭证；
再次，无法查询到邮箱信息；
再次提醒，国内搜索网站很多信息都是假的，请勿轻信https://github.com/getlantern/forum/issues/9670 https://github.com/getlantern/forum/issues/8423
最后，建议尝试联系该公司退款或相关部门进行投诉。
 谢谢！
@234704066
