### ISSUE TITLE
生气

### ISSUE THREAD

**Issue by j782070772** [getlantern/forum#1011]
花了十来块钱买了一个月云墙，快得和访问本国“局域网”一样。然后换蓝灯，经常连国内网站都访问不了。买了一年的蓝灯，此刻我想骂人。

**Comment by j782070772** [comment]
看看会不会被删帖

**Comment by j782070772** [comment]
真是，人家有实力，敢按月收费。蓝灯这种玩法，服务做好没问题，服务做的跟屎一样，这他妈和骗钱有啥区别？买了商品不能用，想骂人

**Comment by j782070772** [comment]
拿人钱不给人把事情做好，想问问蓝灯开发者，该不该被骂？

**Comment by j782070772** [comment]
说本帖是给云墙打广告的看清楚了。本人给蓝灯花了将近200块，给云墙花了不到20块。

**Comment by Junpr** [comment]
老司机带带我

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
