### ISSUE TITLE
请管理员给更改下邮箱，谢谢

### ISSUE THREAD

**Issue by xemhcn** [getlantern/forum#10122]
请管理员修改下邮箱
激活码：9MBK9-CWMHC-F3C9B-HW3T3-XMJKG
激活邮箱：lifeng@jarvisibim.com
正确邮箱：lifeng@jarvisbim.com

原因是激活时填错邮箱了， 请改下

**Comment by Ghostwithout** [comment]
@xemhcn 你好，根据后台查询，这个激活码属于另一个用户，请提供你的购买凭证，谢谢！

**Comment by xemhcn** [comment]
这个用户让帮他提交的 @234704066

**Comment by xemhcn** [comment]
请管理员给下他激活的正确邮箱

**Comment by Ghostwithout** [comment]
你好，请参考https://github.com/getlantern/forum/issues/10100
这个是用户@234704066关闭的case。
这个激活码：9MBK9-CWMHC-F3C9B-HW3T3-XMJKG是成都优博特提供的吗？能告知具体过程吗？
这个激活码属于另一个用户，所以怀疑这个假的公司将已经被使用的激活码再次卖给其他用户。
谢谢！@xemhcn

**Comment by fxintai** [comment]
@234704066 的同事QQ"四分卫"购买的激活码,转交给 @234704066 这个人用,这个人说邮箱错了,让其到论坛修改,具体填的什么邮箱不清楚  @Ghostwithout  
![jhm](https://user-images.githubusercontent.com/31147776/41828986-d18453ca-786a-11e8-9790-b7d0d010f56e.png)

**Comment by fxintai** [comment]
![1](https://user-images.githubusercontent.com/31147776/41829234-23c79826-786c-11e8-8a76-cd3dc4fa537a.png)
![img_20180623_180331](https://user-images.githubusercontent.com/31147776/41829237-268e95dc-786c-11e8-8fe4-a4863028f443.png)

**Comment by xemhcn** [comment]
![1](https://user-images.githubusercontent.com/40482531/41829417-38761f94-786d-11e8-9c9c-cd1fb1d96801.png)
![img_20180623_180331](https://user-images.githubusercontent.com/40482531/41829428-41584ad8-786d-11e8-9f94-4732ee2fc36c.png)


用户 234704066 的同事购买的, 交给用户  234704066  ,然后中间邮箱又出错, 至于他们是否给过第三个人无法证实, 也无法证实他们是否发出过激活码到其他地方, 实在搞不清楚, 具体此激活码激话那个个邮箱也不清楚,只知道是被用掉了
