### ISSUE TITLE
拿人钱做不好服务是不是相当于骗子？

### ISSUE THREAD

**Issue by j782070772** [getlantern/forum#1012]
更何况现在不仅是做不好，是做的跟屎一样。连他妈国内网站都上不了了！做不到和骗子有什么区别？别谈什么原因，知道有这些原因就应该做好了再收费！当然了，免费的你们不发布也没人说啥。但是收费的做不好就去死吧！气死了，花钱受罪。

**Comment by j782070772** [comment]
拿人钱就要给人把事情做好，因为一些原因没有做好要及时站出来向人解释并道歉，这是作为一个成年人应有的最基本的素质。可惜，在你球(特别的，不仅指你国人)，太差劲了。

**Comment by j782070772** [comment]
有人可能会说你他妈都骂人了还讲素质？呵呵呵，你面对着骗子还会以平常心来教他 “不要骗人啊” 吗？

**Comment by mxujm1** [comment]
额，发生什么了?我这里还是用的好好的， 没问题啊

**Comment by AgainWang** [comment]
推荐用金钥匙VPN,稳定不限速

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
