### ISSUE TITLE
付款前注意辨别真假Lantern

### ISSUE THREAD

**Issue by Ghostwithout** [getlantern/forum#10133]
请各位童鞋付款前注意辨别真假Lantern

![image](https://user-images.githubusercontent.com/33254750/41807572-24f82a72-7703-11e8-8b91-53c485d07ef5.png)
这是一家叫成都优博特的公司开发的假Lantern，而真正的Lantern是由国外的Brave New Software开发的；
其次，付款界面完全不同，请参考论坛其他要求更改邮箱的凭证；购买前请注意辨别真假；
如果已经购买，建议尝试联系该公司退款或相关部门进行投诉。
再次提醒，国内搜索网站很多信息都是假的，请勿轻信。#9670 #8423

谢谢！

**Comment by Ouksnack** [comment]
那就是有内鬼

**Comment by xemhcn** [comment]
https://reseller.lantern.io/signup  请问管理员，这个是真的不

**Comment by 00bb** [comment]
支持！

```diff
+ 输入我的邀请码 YJHBMVV 来获得三个月的蓝灯专业版！
- 输入我的邀请码 YJHBMVV 来获得三个月的蓝灯专业版！
```

**Comment by SJTUboy** [comment]
https://github.com/getlantern/forum/issues/9670

**Comment by SJTUboy** [comment]
#9670 

Lantern唯一官网 https://getlantern.org

输入我的邀请码 JHMRSV 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
Use my code JHMRSV and get 3 months free when you sign up!

**Comment by shanligang1017** [comment]
很多是代理买过去的激活码，你们官网本身不就支持批量买激活码吗，人家买去当然要卖

**Comment by Pazuo** [comment]
遇到假的，退款基本没戏，但是国内有很多卖激活码的，是真的，我朋友就是买的激活码。
**输入我的邀请码 JTCU99 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum**
