### ISSUE TITLE
安卓手机客户端如何“授权其他设备使用专业版”？

### ISSUE THREAD

**Issue by zzzcqna** [getlantern/forum#1013]
在安卓上安装并购买了专业版蓝灯，在电脑上下载了PC客户端，登录时要求在已有专业版的设备，打开菜单，点击“授权其他设备使用专业版”，但手机上找不到这个选项。
请问怎么处理？

**Comment by infinitebook** [comment]
我也是。。这不是坑爹吗！

**Comment by GD-HBX** [comment]
两个终端的客户端都是最新版的吗？

**Comment by GD-HBX** [comment]
我怎么就有？->__->

**Comment by huchiwen** [comment]
我手机上安装好lantern 没有登陆的按钮吗？叫我怎么登陆啊 呢吗的？这烂软件~~~

**Comment by huchiwen** [comment]
我是付费用户 没有登陆按钮 叫我怎么用啊 一大推问题 这个软件 从购买到现在 不断的新问题出现 都不知道你们是干嘛的 解决速度慢的要死 退款吧~浪费时间~

**Comment by huchiwen** [comment]
我已经忍了很久了~

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
