### ISSUE TITLE
付费之后不能用,重装系统之后说要我授权,怎么办?

### ISSUE THREAD

**Issue by jasonstyle2015** [getlantern/forum#1015]
付费买了专业版之后不能用,所以决定重装电脑系统, 重新安装lantern之后，提示我需要授权其他设备，怎么办？我电脑是同一台，只是系统重装了，lantern就当我是不同的设备了，怎么才能使用？？？？？？
[lantern.txt](https://github.com/getlantern/forum/files/417359/lantern.txt)

**Comment by jasonstyle2015** [comment]
lantern技术帮忙处理一下，到底能不能用？

**Comment by jasonstyle2015** [comment]
有没有人解决问题的？？？？

**Comment by RussellChen** [comment]
是不是给了你一个什么授权码，然后要在其他设备上确认？我也遇到这种状况了，但是安卓客户端根本没有地方来填写这个。
![qq 20160815211430](https://cloud.githubusercontent.com/assets/21038518/17665701/1ed3b7fe-632f-11e6-97ab-b011de39e04d.png)

**Comment by jasonstyle2015** [comment]
对，我系统都已经重装了，不可能回到原来的系统再给现在的系统授权，这钱都付了，就没人来解决问题的吗？

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
