### ISSUE TITLE
请管理员帮忙修改邮箱

### ISSUE THREAD

**Issue by bimver** [getlantern/forum#10167]
管理员你好，我原本的专业版邮箱是qq邮箱，但是好像收不到任何蓝灯的邮件，我想改邮箱，购买凭证我这里也没收到，不知道有没有影响
原邮箱：542050417@qq.com
修改为：13988869597@163.com

**Comment by bimver** [comment]
@Ghostwithout 感谢

**Comment by bimver** [comment]
我想知道购买凭证当时是发送到邮箱还是怎么的，我这里怎么没有

**Comment by Ghostwithout** [comment]
你好，购买凭证可以通过支付宝查询。考虑到信息安全，麻烦发送邮件到support@getlantern.org，邮件名“请更改邮箱”，内容包含原注册邮箱，备用邮箱和购买凭证，核实后可更改。谢谢！ @bimver
