### ISSUE TITLE
卸载apk后再重装，无法使用专业版了

### ISSUE THREAD

**Issue by lianddao** [getlantern/forum#1018]
为什么刚刚购买的专业版，我卸载apk以后再重装，就无法使用专业版了，发了问题，就给我邮箱发一个日志文件，尼玛，搞毛啊。我的支付邮箱是lianddao@163.com
尼玛，看了多个反馈。总结出来，就是被坑了，验证是否为专业用户的机会一生只有一次，死心吧。
你们普通用的流量，就是我们付费后不能再用的给你们填的。。。

**Comment by lianddao** [comment]
尼玛，今天内我总得开骂才能对得住我所付的钱吧，给了钱没服务，我在这里喷两句总行了吧，尼玛！！尼玛！！

**Comment by seancy** [comment]
致蓝灯团队：我的蓝灯手机版卸载后无法再登入专业版了，因为昨天我试了好久都登不上去，相信大家一定能解决的，加油，你们现在做的是一项伟大的事业！

**Comment by abelfu6** [comment]
我也出现了这样的情况，PC端购买的专业版，Mac上需要其他设备认证登录；而在PC的Webapp上没有授权其他设备的菜单；折腾了好久，最后发现PC端的版本是2.2.5，没办法只能下载最新版，好不容易下了最新版安装了吧，他妈的PC版也需要其他设备协助授权了。你说你们的产品逻辑得有多奇葩？现在是彻底无法登录专业版了，开发玩嗨了，有效控制了版权滥用，哈哈哈哈。第一批购买你们专业版的多少都是些情怀用户，你们这么对待他们？

**Comment by lemonskkyt** [comment]
蓝灯确实挺奇葩的，之前免费搞了这么久，也就偶尔抽风，换成收费后，刚上来就不行，一大堆买了的一样限速，明知道有问题也不知道先放开限速，非要买了专业版的用户等3 4天（结果也只解决一部分，我是属于等3 4天后就可以正常使用的那部分），现在又看到一堆卸载后重装就不行的，卧槽，你明知道有问题就不能先放开限速让花钱的正常使用吗？这都快两个月了，搞的好像放开限速让没花钱的用户用了就没人买了一样.......你这整体坑收费用户才真是没人敢买了

**Comment by ghostsunon** [comment]
换了手机重装一个，竟然发现我没法证明我是专业版用户。坑

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
