### ISSUE TITLE
蓝灯团队有没有回应？

### ISSUE THREAD

**Issue by j782070772** [getlantern/forum#1022]
面对这么多问题为什么连个回应都没有？？？我看像墙内人做事习惯。

**Comment by lianddao** [comment]
是的，是黑金

**Comment by unever** [comment]
看了你发的几个帖子，如果我是管理员我也不会回复。

**Comment by j782070772** [comment]
@unever 气的，我第一条帖子可没这样。花钱受罪

**Comment by abelfu6** [comment]
我也出现了这样的情况，PC端购买的专业版，Mac上需要其他设备认证登录；而在PC的Webapp上没有授权其他设备的菜单；折腾了好久，最后发现PC端的版本是2.2.5，没办法只能下载最新版，好不容易下了最新版安装了吧，他妈的PC版也需要其他设备协助授权了。你说你们的产品逻辑得有多奇葩？现在是彻底无法登录专业版了，开发玩嗨了，有效控制了版权滥用，哈哈哈哈。第一批购买你们专业版的多少都是些情怀用户，你们这么对待他们？

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
