### ISSUE TITLE
重装了系统，找不到登录的地方了

### ISSUE THREAD

**Issue by RussellChen** [getlantern/forum#1023]
_
[lantern.txt](https://github.com/getlantern/forum/files/418131/lantern.txt)
_
WIN10，打开页面
![qq 20160815211421](https://cloud.githubusercontent.com/assets/21038518/17666173/91267b1e-6331-11e6-84ae-36f0c6573734.png)
然后点登录
![qq 20160815211430](https://cloud.githubusercontent.com/assets/21038518/17666182/97a62494-6331-11e6-9521-d8435095359d.png)
请告诉我这个咋整

**Comment by zhcaa** [comment]
我的也是  真是苍老天啦

**Comment by code4impl** [comment]
同样的问题，你们解决了吗？

**Comment by abelfu6** [comment]
我也出现了这样的情况，PC端购买的专业版，Mac上需要其他设备认证登录；而在PC的Webapp上没有授权其他设备的菜单；折腾了好久，最后发现PC端的版本是2.2.5，没办法只能下载最新版，好不容易下了最新版安装了吧，他妈的PC版也需要其他设备协助授权了。你说你们的产品逻辑得有多奇葩？现在是彻底无法登录专业版了，开发玩嗨了，有效控制了版权滥用，哈哈哈哈。第一批购买你们专业版的多少都是些情怀用户，你们这么对待他们？

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
