### ISSUE TITLE
强烈要求退款

### ISSUE THREAD

**Issue by lufei008** [getlantern/forum#1024]
之前免费的一直不好用，今天早上319.99购买了蓝灯两年专业版，合计试试专业版应该好用了吧，但是专业版也无法使用。强烈要求退款！！！！
支付宝支付，支付宝账户：ywj1987315@126.com

**Comment by huchiwen** [comment]
我都想退款！妈的

**Comment by rocknrollfly** [comment]
蓝灯现在在我这里很好用，不知道为什么，我使用的还是普通版，无法使用的网友请检查自己的手机或电脑系统的纯净性，另外建议使用墙外邮箱
专业版用户送有额外使用时间，暂时不要给蓝灯开发组太大的压力了，相信他们已经在很努力了

**Comment by koaqiu** [comment]
支持楼主！

@rocknrollfly  收了钱就的办事，办不了事情 收什么钱？！
另外 你怎么知道他们“很努力”了？？？？？

**Comment by j782070772** [comment]
已经放弃了，就当拿钱给他们那啥了吧。。。。我是个文明人。

**Comment by abelfu6** [comment]
我也出现了这样的情况，PC端购买的专业版，Mac上需要其他设备认证登录；而在PC的Webapp上没有授权其他设备的菜单；折腾了好久，最后发现PC端的版本是2.2.5，没办法只能下载最新版，好不容易下了最新版安装了吧，他妈的PC版也需要其他设备协助授权了。你说你们的产品逻辑得有多奇葩？现在是彻底无法登录专业版了，开发玩嗨了，有效控制了版权滥用，哈哈哈哈。第一批购买你们专业版的多少都是些情怀用户，你们这么对待他们？

**Comment by ghostsunon** [comment]
我发现中国的蓝灯团队才是一群发国难财的人

**Comment by huchiwen** [comment]
起诉他们吧

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
