### ISSUE TITLE
只有一台笔记本在用专业版，，，，重装系统了，现在怎么办

### ISSUE THREAD

**Issue by zhcaa** [getlantern/forum#1026]
#

**Comment by zhcaa** [comment]
# **# 在线急等**

**Comment by zhcaa** [comment]
# 有人吗

**Comment by Hwatu** [comment]
没办法,等解决吧

**Comment by zhcaa** [comment]
要等多久呀

**Comment by seancy** [comment]
我也遇到了同样问题

**Comment by xyjzj2001** [comment]
等吧~~我的手机那天被淘宝给坑的发热，重置之后就在等更新~

**Comment by abelfu6** [comment]
我也出现了这样的情况，PC端购买的专业版，Mac上需要其他设备认证登录；而在PC的Webapp上没有授权其他设备的菜单；折腾了好久，最后发现PC端的版本是2.2.5，没办法只能下载最新版，好不容易下了最新版安装了吧，他妈的PC版也需要其他设备协助授权了。你说你们的产品逻辑得有多奇葩？现在是彻底无法登录专业版了，开发玩嗨了，有效控制了版权滥用，哈哈哈哈。第一批购买你们专业版的多少都是些情怀用户，你们这么对待他们？

**Comment by wizardmly** [comment]
我就想问，pc端为什么没有授权设备使用专业版功能，我在pc端买的pro版本，你让我怎么授权给移动端

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
