### ISSUE TITLE
【警告所有无知用户】Lantern从未发布过高于2.2.5的国际版本！

### ISSUE THREAD

**Issue by CaliloNio** [getlantern/forum#1029]
【最新版截图】

https://s25.postimg.io/qduj9wzn3/8_16_2016_9_56_20_PM.png

https://s25.postimg.io/7k8qcx1f3/8_16_2016_9_56_15_PM.png

请问lantern什么时候发布3.x版本啦？我真是服了这些无耻的国人了，拿着Google赞助、背弃bittorrent创建者最初的乃至一直根本都没变的设计意图，在背地里竟然利用beta中文版来坑国人赚钱。且注意，目前只有那个所谓的中文版针对中国用户的IP采取收费而已（完全不是lantern国际的策略）！

v2.2.5，这是lantern发布于Lantern 2.2.5 (20160627.192617) 的最新版。

这也可以在[AppNee](http://appnee.com/lantern/)看到的最新版的了（目前只有它提供最直接的也是最新的官网的完整镜像）。大家可以看到截图的吧，什么时候收费了？什么时候限速了？什么时候速度慢了？我住处100mb的光线，用internet download manager 下载是10mb/s左右。latnern我设定的是开机自动启动（默认的），从没有遇到过你们所谓的各种奇葩问题。

我实在是看不下去了，竟然有人愿意花钱购买中文版lantern，还要无辜受折磨！！就没有好奇为什么一个在全世界都有用户的lantern却在其论坛中只有中文提问和极少数的英文提问？你以为全世界只有中国才有GFW (Great Fire Wall) 吗？其实几乎每个国家都有自己的GFW (Government FireWall)，中国的比较厉害而已，但完全不是最严重的那些个之一。

请大家稍微动动脑子，就不能用个英文、法文、波斯文，什么文都行，反正你又没有必要认识不是吗？就偏偏要看lantern上的几个中文菜单而强迫收费吗？

如果你连[AppNee](http://appnee.com/lantern/)这个都无法下载，那就给我留言，我会上传到免费空间给大家提供下载地址，像github中文论坛所谓的“其他地方下载都是被植入病毒或广告的”，我只说一句——自己用杀毒软件去扫描，一个不够就用世界知名的[VirusTotal](https://www.virustotal.com/)或国人的[VirSCAN](http://www.virscan.org/)这种多引擎（数十款杀毒软件）同时扫描一下不就什么都清楚了。

最后请大家记住一点——凡是因为语言方便而倾向于使用汉化软件的人们，一定要多个心眼（大多是真的植入了病毒或者广告等malware的，就是篡改了内容而获利），何不多去软件的官网看些最新信息。不要别人用你熟悉的语言跟你乱说些什么你就信什么。

**Comment by EdwardAutumn** [comment]
呵呵。

**Comment by GD-HBX** [comment]
吃鲸🐋😲

**Comment by p3rcya** [comment]
官网没更新是因为没有正式发布，这个说过很多次了。
