### ISSUE TITLE
本周会修复专业版无法登陆的问题

### ISSUE THREAD

**Issue by p3rcya** [getlantern/forum#1031]
有部分用户在购买专业版后重新安装了系统，导致专业版没法被识别。这个问题我们本周会修复。只要使用的同一台电脑／手机，硬件没有改变，都可以找回专业版帐号。

**Comment by EvilNumber** [comment]
安卓版的專業版，每次選擇開啟選項，都會自動變回關閉，怎麼回事？

**Comment by EdwardAutumn** [comment]
@EvilNumber 可能是系统清理工具造成的，最新版才有这个问题

**Comment by 7pitter** [comment]
早上重装了系统，然后下了最新版，点击登陆弹出授权页面，没有登陆入口啊。。。@p3rcya

**Comment by zly1989222** [comment]
我要控告你们欺骗消费，购买了两年，结果重装下蓝灯就没了

**Comment by abelfu6** [comment]
我也出现了这样的情况，PC端购买的专业版，Mac上需要其他设备认证登录；而在PC的Webapp上没有授权其他设备的菜单；折腾了好久，最后发现PC端的版本是2.2.5，没办法只能下载最新版，好不容易下了最新版安装了吧，他妈的PC版也需要其他设备协助授权了。你说你们的产品逻辑得有多奇葩？现在是彻底无法登录专业版了，开发玩嗨了，有效控制了版权滥用，哈哈哈哈。第一批购买你们专业版的多少都是些情怀用户，你们这么对待他们？

**Comment by abelfu6** [comment]
还有就是，如果我的PC卖了，那我的专业版账户也就消失了吗？

**Comment by hcmyleo** [comment]
期待解决。坐等ing         千万别跳票了……

**Comment by EvilNumber** [comment]
@EdwardAutumn 那請問怎麼解決？而且我的手機是新刷的魅族系統，一加手機。@全體希望大家可以給點支持，耐心給Lantern，說一句公道話，我用它都一年多了，大家可以試試別的VPN，會不會有這性價比。

**Comment by EvilNumber** [comment]
@EdwardAutumn 然後，桌面版有時候上一些網站，只看到“read tcp 192.168.1.133:51710->159.203.198.222:443: i/o timeout”這句話，什麼意思？就是訪問不了網站

**Comment by abelfu6** [comment]
@全体，我用多态一年多，比这个好用稳定不知道多少，也就240一年，性价比不比这个差。

**Comment by abelfu6** [comment]
500一年的pro版，可以youtube1080p，流畅。怪自己脑抽，情怀了这个专业版

**Comment by zly1989222** [comment]
周五了，到底能不能修复好专业版重装之后没法识别登陆

**Comment by pucku** [comment]
到底能不能修复好专业版重装之后没法识别登陆的问题

**Comment by jasonstyle2015** [comment]
重装系统之后，没法授权，也登陆不了，期待解决！！！！

**Comment by hcmyleo** [comment]
你好，，您所说的硬件不改变，是类似于微软重装系统的那种不改变（可以换个硬盘，加个内存什么的）？还是绝对的不改变？我这台电脑需要换硬盘……可以吗？

**Comment by p3rcya** [comment]
如果你帐号已经在登陆情况就没有影响。只会影响需要找回帐号的用户

**Comment by stefantong** [comment]
用回3.0.6就好了啊 我也遇到了“abelfu6”这位用户所说的情况 装回3.0.6 可以用电子邮件登录 手机上的蓝灯也装回了3.0.6

**Comment by jasonstyle2015** [comment]
今天都周六了，怎么还不解决不能登陆的问题

**Comment by LonelyFaith** [comment]
怎么回事儿？？你们开发lantern应该能想到我门会重新装系统的问题把？？你们难道不应该有一个lantern的账号管理服务器？？

**Comment by fbuluo1987** [comment]
为什么专业版登录输入代码后，会提示无效的验证码？

**Comment by fbuluo1987** [comment]
为什么专业版登录输入代码后，会提示无效的验证码？版本3.0.12

**Comment by abelfu6** [comment]
蓝灯中国团队重新定义了“本周”这个概念

**Comment by EvilNumber** [comment]
@EdwardAutumn 怎麼還沒更新？

**Comment by EdwardAutumn** [comment]
@EvilNumber 我不是官方人员。

**Comment by nasavvan** [comment]
我今天才发现这个问题，怪我手贱，清理了一下系统，自己的电脑还要授权登陆，我一直用这台啊，我找谁授权，才买了几天的专业版就登不上了

**Comment by EvilNumber** [comment]
@p3rcya 老闆，你這樣不行哦，我的最新版手機版還是不可以上

**Comment by lzw2009** [comment]
完美，明天是第七天了，不知道会不会再改到这个月内呢。

**Comment by huchiwen** [comment]
一大堆问题！！！！你们还敢收费？

**Comment by imvicchen** [comment]
求解决啊，买完了就登录不了了，要授权，即便是授权我两台设备都是pc，一台在公司，一台在家，我咋授权！！！

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
