### ISSUE TITLE
没有账号登陆简直是在开玩笑

### ISSUE THREAD

**Issue by dujianchi** [getlantern/forum#1032]
假如我在一台电脑上/手机上购买了两年，那么两年之内我手机坏掉了/电脑硬盘坏了，换了一个新手机/新硬盘，那么我的专业版就这样随风而去了？这个机制本身就是很有问题，很不可靠的，另外，我已经不知道第几次想要购买专业版不成功了……

**Comment by dujianchi** [comment]
现在重新下载了最新版的可以购买了

**Comment by dujianchi** [comment]
其实无非就是担心别人购买一个账号被多人分享使用，解决这种问题还是有办法的啊，至少给个限制，比如：3个月内可以有2次使用邮件登陆，并解绑客户端的机会，诸如这样的限制

**Comment by 7pitter** [comment]
最新版的怎么登陆？点击登陆后弹出来个授权该设备。。。怎么授权？没有入口啊

**Comment by LitleCarl** [comment]
这里不是公告了么？不看么https://github.com/getlantern/forum/issues/1031

**Comment by abelfu6** [comment]
我也出现了这样的情况，PC端购买的专业版，Mac上需要其他设备认证登录；而在PC的Webapp上没有授权其他设备的菜单；折腾了好久，最后发现PC端的版本是2.2.5，没办法只能下载最新版，好不容易下了最新版安装了吧，他妈的PC版也需要其他设备协助授权了。你说你们的产品逻辑得有多奇葩？现在是彻底无法登录专业版了，开发玩嗨了，有效控制了版权滥用，哈哈哈哈。第一批购买你们专业版的多少都是些情怀用户，你们这么对待他们？

**Comment by lemonskkyt** [comment]
不如一周或两周解绑一次，正常的用户也不会整天设备换来换去

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
