### ISSUE TITLE
无法登陆专业版

### ISSUE THREAD

**Issue by code4impl** [getlantern/forum#1039]
今天重装了系统，下载最新版后发现需要使用以前的专业版进行授权才能登陆专业版，以前的版本是直接帐号密码登陆。由于重装了系统，已经无法登陆到以前的专业版进行授权，这个问题何解呀。

**Comment by abelfu6** [comment]
我也出现了这样的情况，PC端购买的专业版，Mac上需要其他设备认证登录；而在PC的Webapp上没有授权其他设备的菜单；折腾了好久，最后发现PC端的版本是2.2.5，没办法只能下载最新版，好不容易下了最新版安装了吧，他妈的PC版也需要其他设备协助授权了。你说你们的产品逻辑得有多奇葩？现在是彻底无法登录专业版了，开发玩嗨了，有效控制了版权滥用，哈哈哈哈。第一批购买你们专业版的多少都是些情怀用户，你们这么对待他们？

**Comment by rocknrollfly** [comment]
@abelfu6 能简单看懂英文请参考这个帖子的三楼：
#1083

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
