### ISSUE TITLE
Google Play上出现假冒蓝灯的VPN，请大家小心

### ISSUE THREAD

**Issue by p3rcya** [getlantern/forum#1050]
最近有人在论坛上广告“金钥匙VPN”，此应用在Google Play上以Lantern的名义，出售假冒的VPN。请大家不要购买，并对其广告贴积极举报，谢谢！
请认准蓝灯官方下载地址 https://github.com/getlantern/forum

**Comment by cunzai2016** [comment]
发个截图，这样大家看起来就更加方便了，最好建一个官方的QQ群，里面能有一个官方的代言人，这样有什么问题沟通起来也方便

**Comment by cunzai2016** [comment]
另外，正式版本什么时侯能出？有时间点吗？还有线路的优化，现在很慢，而且基本连不上，尤其是手机版本的，希望蓝灯别让大家失望!

**Comment by zly1989222** [comment]
大哥，说好这周解决重装后无法登陆的问题，到底有没有办法，我TM白白了快一个星期了

**Comment by Afteright** [comment]
感谢你们推荐！否则我还不知道有金钥匙这么好的VPN！又快又稳定！谢谢！人家假冒你们Lantern？没发现！人家不会收了我200块啥事不干！人家不会说秒杀VPN，人家速度就是比你们快！垃圾蓝灯，整天不知道解决问题，就知道瞎逼逼！你们啥时候能解决问题？！

**Comment by p3rcya** [comment]
楼上是假冒蓝灯的水军，已经封号。

**Comment by yukuai0011** [comment]
但是我的官方lantern确实最近上不了，金钥匙可以用（没钱拿的破解版），不过金钥匙连接的是辣鸡香港服务器，gplay一大堆东西都没有
