### ISSUE TITLE
个人解决重装后无法授权的经验

### ISSUE THREAD

**Issue by hcmyleo** [getlantern/forum#1055]
1.      把原来的蓝灯卸载了。
2.      到    http://www.freefq.com/sj/2016/07/09/Lantern306.html       下载3.0.6 （我不保证是否安全，我自己找了个网上3.0.6的资源，不放心的可以自己去找。我因为工作需要，要给笔记本换硬盘，等不了官方更新了，所以尝试了一下，确实成功了）
3.     用3.0.6的邮件登录，就能登录成功了
4.     下载官方最新的版本，，千万不要卸载老版本，，直接退出蓝灯后覆盖安装新版本。
5.     没有啦，，我就成功啦~~

**Comment by hcmyleo** [comment]
用这方法成功的，请回来说一声，，方便大家。

**Comment by zly1989222** [comment]
超赞！！！！大爱！！！！我也成功了，什么鬼官方垃圾，自古高手在民间！感谢楼主

**Comment by GD-HBX** [comment]
这个之前就有人讲过啦...

**Comment by jasonstyle2015** [comment]
![qq 20160820161010](https://cloud.githubusercontent.com/assets/21028516/17829972/d516e994-66f1-11e6-8d62-1038659b68e0.png)

**Comment by jasonstyle2015** [comment]
下载了3.0.6，为什么还是登陆不上去啊？？

**Comment by jasonstyle2015** [comment]
为什么我登陆不上去啊？我的邮箱也没写错！

**Comment by GD-HBX** [comment]
@jasonstyle2015 那可能只对那些3.1.0之前购买的人有效，因为那时候是用邮箱的验证码认证的，为什么会这样只有开发组知道...

**Comment by cacaca222** [comment]
好像真好使--。谢谢啊。。。之前是笔记本购买的。。现在买了个台式后没法登陆了--。用哥们你这个确实登陆上去了  。。哇哈哈哈哈

**Comment by abelfu6** [comment]
很好用的方法，已解决专业版不能登录问题

**Comment by nasavvan** [comment]
已经用这个方法解决，谢谢啦

**Comment by hcmyleo** [comment]
好久没人回帖了，，看来大家都解决了，，那我的问题来了，，，这帖子该怎么删除……

**Comment by jasonstyle2015** [comment]
解决什么啊解决，又不是所有的都能解决，我是3.1.1的时候买的，还是不行

**Comment by hcmyleo** [comment]
我没有义务给所有人解决问题@jasonstyle2015 我也只是个和你一样的买家而已。 我所解决的是和我同一版本购买并重装的人的问题。至于你3.11买的，现在不能用，与我无关。有多少条回复就有多少邮件到我邮箱，感觉很不好，所以我想删帖。哪位大兄弟知道怎么删帖吗？

**Comment by imvicchen** [comment]
不想关注 右边的小喇叭 可以点击一下

**Comment by imvicchen** [comment]
我是3.1.1买的，看来只能坐等官方了，郁闷！

**Comment by hcmyleo** [comment]
@imvicchen 谢谢

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
