### ISSUE TITLE
重装系统后无法授权使用专业版

### ISSUE THREAD

**Issue by joefom** [getlantern/forum#1058]
买了两年的lantern专业版。当初买的时候系统装的是win8.1 64位企业版，蓝灯版本为(Lantern3.1.1(20160811.054934))，并授权了两台android设备。
现在换用win10 64位企业版(正版激活)，仍旧安装的是(Lantern3.1.1(20160811.054934))。现用android授权PC设备，无法成功授权lantern专业版。
浏览器用的是firefoxESR 45.3

**Comment by joefom** [comment]
这个问题已得到解决。
先得在android设备的lantern专业版上点击"专业版账户管理"解绑原来的设备(我应该解绑win8.1),然后才可以继续授权其他设备。

**Comment by lysu** [comment]
。。。。。那没andorid设备咋办- -

我遇到相同问题。。。不过只在mac用了没其他设备没andorid手机。。然后mac重装了下。。

现在如何找回专业版？？- -

**Comment by p3rcya** [comment]
一些用户因为重装登录不了的问题官方正在解决中，只要硬件不改变都能找回来

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
