### ISSUE TITLE
Lantern的3.1.0和3.1.1搞的什么认证方式？！

### ISSUE THREAD

**Issue by TalentSales** [getlantern/forum#1059]
害得我今天下午弄了一整下午都没有登录上去！

谁想出来的这种狗屁的认证方式！把脑袋弄下来！

**Comment by rocknrollfly** [comment]
一些用户因为重装登录不了的问题官方正在解决中，只要硬件不改变都能找回来

**Comment by p3rcya** [comment]
楼上说的对，请等新版

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)

**Comment by TalentSales** [comment]
您好，確實能上去了，謝謝。

 

发件人: p3rcya [mailto:notifications@github.com] 
发送时间: 2016年8月26日 11:09
收件人: getlantern/forum <forum@noreply.github.com>
抄送: TalentSales <talentsales@outlook.com>; Author <author@noreply.github.com>
主题: Re: [getlantern/forum] Lantern的3.1.0和3.1.1搞的什么认证方式？！ (#1059)

 

 <https://github.com/getlantern/forum/issues/1107> 蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里
