### ISSUE TITLE
换手机后发现我竟然没有通道证明我是专业版用户

### ISSUE THREAD

**Issue by ghostsunon** [getlantern/forum#1064]
无语了，早知道这样我打死也不会买这个，换手机竟然没有任何保障

**Comment by p3rcya** [comment]
会支持email找回的，请等新版

**Comment by 7pitter** [comment]
我也遇到了这情况

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
