### ISSUE TITLE
专业版，MacOS，貌似所有问题都被我碰上了么？

### ISSUE THREAD

**Issue by DengZhengyuan** [getlantern/forum#1065]
额，最近貌似有点忙，当时买了专业版用不了，也没太在意。

我用的Hotmail的邮箱 (dengzhengyuan2240@hotmail.com) 注册的，据说有个邮件会发来？印象里好像没有收到额

另外电脑是MBA，好吧，升级了MacOS系统，貌似这个问题我看还没解决。所以至今还没有再打开lantern使用过，也没登陆过专业版。暂时买了一个月VPN用着。

不是很急着催你们的啦，等一两个月什么的也没问题的。不过啥时候修好了，还是希望你们能够通知我一声。

版主说有问题记得发log，我记得，哈哈。

Log: https://www.dropbox.com/s/9vplafudr6lfayt/lantern_log_from_dengzhengyuan.zip?dl=0

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
