### ISSUE TITLE
求助官方，授权登录的问题？

### ISSUE THREAD

**Issue by imvicchen** [getlantern/forum#1079]
rt，目前官方有进展吗？什么时候可以解决这个问题，因为买了之后无法登录，我暂时还花了钱暂时用其它的，对蓝灯很自信，所以请求尽快解决～关于这么长时间造成的损失，我都可以忽略～只求快些搞定！

**Comment by qingjulee** [comment]
我也是同样的问题，我也已经购买了专业版的，但是怎么也用不了啊！！！

**Comment by qingjulee** [comment]
谁能够帮忙啊？

**Comment by rocknrollfly** [comment]
@qingjulee 能简单看懂英文请参考这个帖子的三楼：
#1083

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
