### ISSUE TITLE
已有LANTERN专业版帐号，但没专业版登录入口

### ISSUE THREAD

**Issue by terrry210** [getlantern/forum#1082]
已有LANTERN专业版帐号，但没专业版登录入口，只能继续购买？咋回事

**Comment by bzq360** [comment]
我8月23号晚上购买的专业版然后退出蓝灯。24号早晨居然没有办法证明这台电脑有专业版账号！

**Comment by bzq360** [comment]
好心痛，专门注册个github号表示不满，这可是180人民币啊 :(

**Comment by bzq360** [comment]
我是WIN10，还有一个问题，firefox和chrome的蓝灯是通用的吗？昨天我的火狐蓝灯chrome也能用

**Comment by GD-HBX** [comment]
@bzq360 ？咩叫Firefox和chrome的蓝灯？蓝灯装在你电脑上，后台开了一个网页服务罢了，唔理你系用咩浏览器都可以浏览嗰个页面

**Comment by rocknrollfly** [comment]
能简单看懂英文请参考这个帖子的三楼：
#1083 
@bzq360

**Comment by Remyres** [comment]
他是说安装一个3.0.6的版本，登陆，再更新到最新版 @bzq360

**Comment by terrry210** [comment]
装了最新版3.1.1，只能关联设备，不能登录专业版，难道要再买一次

**Comment by bzq360** [comment]
我们两兄弟好惨啊

**Comment by Remyres** [comment]
@terrry210  PC端的3.1.1，我自己无法授权，不知道为什么，但另一位蓝友却可以帮我授权，好郁闷。。

**Comment by bzq360** [comment]
@Remyres 现在只有3.1.1有下载啊，根本找不到3.0.6了

**Comment by Remyres** [comment]
https://github.com/getlantern/lantern-binaries  @bzq360

**Comment by Remyres** [comment]
我自己也没试过，成功了说下哈

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
