### ISSUE TITLE
2.2.5 PC cant use, Phone is OK

### ISSUE THREAD

**Issue by decemer** [getlantern/forum#1085]
i have test 2 PC,2.2.5 cant use
Guangdong,Guangzhou,china telecom

**Comment by YOYOsheep** [comment]
me too

**Comment by hmm1316440706** [comment]
you should use 3.1.1

**Comment by pram22** [comment]
Why we must use v3.1.1?

I choose use v.2 because no limit usage

**Comment by myleshorton** [comment]
Closing for now guys.
