### ISSUE TITLE
2.2.5版本仍然可以用的话，付费用户的权益是如何保证的？

### ISSUE THREAD

**Issue by ArvinLiuV** [getlantern/forum#1087]
翻了下Close的Issue，看到这个帖子https://github.com/getlantern/forum/issues/1029，然后到帖子提到的链接http://appnee.com/lantern/下载了安装包。
安装使用发现是2.2.5版本，并没有**限制免费800M和限速**的提示。另外获取到的安卓版APK文件的MD5值和这里的也不一样。
![image](https://cloud.githubusercontent.com/assets/19185818/17916803/2d434bb8-69e9-11e6-9bb0-ce289e8d8ba0.png)

看帖子里的解释说目前是Beta版，没正式发布。但是既然已经有付费用户了，2.2.5版本为什么不强制停用升级呢？另外2.2.5版本的会有800M限制吗，没有的话对付费用户是不是太不公平了？

**Comment by rocknrollfly** [comment]
蓝灯不会学某朝的德性，把人分三六九等，人为的制造不公平，所以旧版不会人为作限制，也无权强制别人升级不准别人用旧的。之所以要推出专业版，是为了创立付费墙防止某朝收集服务器IP和积累服务资金提高服务质量，并不是为了赚钱，目前收费不贵，因为有大洋彼岸的资助。
既然买了专业版，就安心用自己的就行了，专业版会提供更好的服务，以后会增加功能。至于旧版，随着GFW的升级，旧版自然会失效，当然不是蓝灯官方人为的

**Comment by ArvinLiuV** [comment]
@rocknrollfly 在可以使用免费帐户的情况下，是怎么创立出付费墙的？难道付费用户和免费用户用的服务器是不同的？这是不可能的。
至于Lantern的价格，我觉得并不便宜。之前我是使用其他付费VPN服务的，不过因为代理方式不同，导致我访问公司内网时需要频繁添加路由表，所以更换了Lantern。两者价格没有什么差距，甚至后者在做活动时比Lantern还要便宜许多。
而Lantern在手机端的服务质量要比对方差了许多，频繁断线**也许**可以忍受，但是断线后不会自己停掉代理，导致手机断网就真的让人很无奈了。我在手机上只有需要翻墙时才会打开，根本不敢和PC一样一直打开着。
另外对于一个免费软件来说，为什么无权禁止免费用户使用？如果这么圣母的话，Beta版怎么可以向用户收费的？

**Comment by EdwardAutumn** [comment]
兄弟你这么说就不对了。你可以不买，但是还要让别人不能用免费的？我也买了，但是你这心态有点低劣

**Comment by rocknrollfly** [comment]
专业版的服务器地址当然比普通版多得多，普通版的服务器运营成本又部分来自专业版销售收入
蓝灯因为不只是要维护服务器，而且要研发，不断更新技术，所以这个价格不算昂贵
普通VPN从技术理论上来说比蓝灯易被封锁得多，之所以表面上不被封锁是故意放水，关键时刻又大面积封杀，而蓝灯有技术优势，成为封锁重点目标是因为其用途有明显政治性，不是那些拿来简简单单玩游戏和流量色情站点的工具
放平心态，等待稳定强大和增加功能的正式专业版

**Comment by ArvinLiuV** [comment]
@rocknrollfly 专业版与普通版服务器数量有明显差别的话，那就可以接受了。只是不知道2.2.5版本是否有流量限制，毕竟就算普通版的服务器被封的话，因为【政治性用途】，也会开新的吧。
我也明白，因为【用途有明显政治性】，估计普通版Lantern服务器被封的几率估计不低。希望可以平衡好普通和专业服务器的比例吧。继续加油，手机端早日稳定。

@EdwardAutumn 如果开始给你两个选择：2.2.5版本完全免费，不限流量；3.+版本免费800M，需要付费才能和前者一样不限流量。你会选哪一个？
重点不在可不可以有免费用户，在于付费不能享受到更好的服务。如果没有区分的话，就应该采用捐款的方式了。我也为TechZero捐过一杯咖啡钱，在上面的镜像都挂掉时也没发过牢骚。和Lantern相比，一个是无盈利服务大家，一个是带有目的性并准备开始商业化。不可能一样宽容的。

**Comment by EdwardAutumn** [comment]
@ArvinLiuV 我就这么说吧，收费版有专门的服务器和特殊协议，这是免费版和2.25都没有的，你满意了不
