### ISSUE TITLE
getlantern 蓝灯专业版的共享安全问题

### ISSUE THREAD

**Issue by lixiaoguai** [getlantern/forum#1090]
遇到个怪事。
我从[这个地址](https://github.com/getlantern/lantern-binaries)下载蓝灯，运行后显示另一个人的付费账号，我联系了邮箱的主人，他是一个普通用户，并不清楚为什么会出现这种情况，请问蓝灯付费版可以用这种方式共享的吗？

 

![cqmnx7jumaatnq7](https://cloud.githubusercontent.com/assets/3614860/17918986/48ced038-69fc-11e6-9b6c-b5752ecc48db.jpg)

**Comment by p3rcya** [comment]
已经修复了这个问题，其他用户不会遇见这个问题了

**Comment by lixiaoguai** [comment]
我用另一台电脑下载，已经没这个问题，但第一次下载的电脑上还可以用这个用户的专业版。
