### ISSUE TITLE
无法授权PC端

### ISSUE THREAD

**Issue by Remyres** [getlantern/forum#1091]
购买了专业版，在3.0.6的时候授权了另一台手机，现在升级到3.1.3，无法授权我的PC，显示无效的验证码。动态授权码更新还要167个小时，怎么解决？693605

**Comment by orbancanon** [comment]
@Remyres 确认你的验证码是有效的，而且在PC版里面可以授权。是不是输入的时候多了空格什么的？

**Comment by Remyres** [comment]
输入的时候没错呀，但是，。。你帮我授权了？ @orbancanon

**Comment by Remyres** [comment]
就6位数字，我手机上3.0.6的时候没有显示授权，升级到3.1.1后菜单上才有授权其他设备使用专业版，但是，输入了6位数字验证码，一直提示我无效

**Comment by Remyres** [comment]
我解绑，自己再试试看~    @orbancanon

**Comment by Remyres** [comment]
我是不是做错什么了。。。 我把WIN10的解绑了，但是，为什么我还一直连着。。额。。

**Comment by orbancanon** [comment]
真是快手~ 我只是试了试，然后立马就从后台删了，还是被你绑上了……

2016-08-24 16:22 GMT+08:00 Remyres <notifications@github.com>:

**Comment by Remyres** [comment]
55555555我没做除了解绑外的任何操作呀~~~

**Comment by orbancanon** [comment]
惟今之计，只有手工删除C:\Users\<用户名>\AppData\Roaming\Lantern\settings.yaml这个文件，然后重新绑定。

2016-08-24 16:25 GMT+08:00 Remyres <notifications@github.com>:

**Comment by Remyres** [comment]
OK  我试试

**Comment by Remyres** [comment]
删了 解绑了  但我自己手机端还是提示  验证错误   无效的验证码：未授权

**Comment by Remyres** [comment]
难道就不能登陆的么~~  郁闷。。

**Comment by Remyres** [comment]
不是说一个账户可以授权另外两台设备的么，我就一共2台手机，再加个PC就不行了？

**Comment by orbancanon** [comment]
帐户肯定是可以授权的。具体怎么回事得查一查。

2016-08-24 16:36 GMT+08:00 Remyres <notifications@github.com>:

**Comment by orbancanon** [comment]
你购买时的邮箱是什么？私给我orbancanon@gmail.com，我手工给你加吧

在 2016年8月24日 下午4:40，Orban St. <orbancanon@gmail.com>写道：

**Comment by Remyres** [comment]
发你了~~  拜托啦~~

**Comment by p3rcya** [comment]
@orbancanon 这个解决了么？

**Comment by Remyres** [comment]
已经解决啦~  @p3rcya

**Comment by BlueSoraSky** [comment]
@p3rcya 我是手机授权电脑，但输入授权码后一直没有反应。。

**Comment by Remyres** [comment]
@BlueSoraSky 我前面也是你这种情况，后来让管理员帮忙处理的，你可以找下他们  可以@下 orbancanon
