### ISSUE TITLE
专业坑爹

### ISSUE THREAD

**Issue by ZTFtrue** [getlantern/forum#1093]
我购买了专业版，但是那台Linux设备已经不使用了，现在怎么给其它设备授权？

**Comment by Remyres** [comment]
取消授权，再授权给其他呗

**Comment by qingxin6174** [comment]
@Remyres 以下设备绑定了您的专业版帐户：
Windows 10
Windows 10
Windows 10
我该怎么区分解绑哪一台？

**Comment by Remyres** [comment]
0 0  回忆下你的绑定时间吧   越是下面的越近   @qingxin6174

**Comment by Remyres** [comment]
而且，你全是win10么    要么全部解绑了    重新登陆过  把你需要的一台一台加上去

**Comment by qingxin6174** [comment]
@Remyres 全部解绑，重新绑定，第一台设备如何绑定？
https://github.com/getlantern/forum/issues/973
基本功能都做不好，我没有勇气解绑

**Comment by qingxin6174** [comment]
@Remyres 绑定时间这个可以，不过我想最好还是能有个区分，或者可以让用户编辑一下设备名称也好。希望能改进

**Comment by Remyres** [comment]
我也希望他们能有这个改进， 我两个手机型号一样，结果就显示一样   0 0
第一台设备可以通过登陆的方式进行，会有验证码发你邮箱的

**Comment by ZTFtrue** [comment]
@Remyres 我说的是之前那台已经不用了，并且蓝灯已经删除了，这样就没法授权了。
知道邮箱也没法登录。

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
