### ISSUE TITLE
20160825我用mac客户端在网页上购买了专业版，根本用不了。

### ISSUE THREAD

**Issue by tulate** [getlantern/forum#1097]
1. mac版的网页上找不到授权其他设备的链接；
   也就是说，如果在MAC上购买的专业版，只能在这一台机器上用。
2. 自从购买了专业版，连facebook都打不开了；
   也就是说，之前免费版是可以打开的，付款之后就打不开了。
请开发者回复以上问题。
如果得不到回复，
我是否可以推导出以下结论:
这是一个诱骗注册的翻墙骗局。

**Comment by tulate** [comment]
我的邮箱是tulate#qq.com，请开发者回复问题。

**Comment by p3rcya** [comment]
我们正在购买更好的网络线路，来解决部分用户无法访问的问题。
公测时间内购买专业版有两个月额外时间赠送(正式版推出后，后台会自动加入)，所以请稍安勿躁。

**Comment by p3rcya** [comment]
请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 ，方便我们调查，谢谢

**Comment by tulate** [comment]
线路问题，无法上网的问题，我可以等您的进展；
但是“mac版的网页上找不到授权其他设备的链接”的问题，怎么解决啊？
[lantern.txt](https://github.com/getlantern/forum/files/436395/lantern.txt)

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)

**Comment by tulate** [comment]
mac版的网页上找不到授权其他设备的链接

**Comment by p3rcya** [comment]
请确认使用最新版3.1.1 论坛主页下载 https://github.com/getlantern/forum
