### ISSUE TITLE
半个小时前还能用，现在一直在转圈

### ISSUE THREAD

**Issue by 772077730** [getlantern/forum#1099]
请GM排查问题，谢谢~
[lantern.TXT](https://github.com/getlantern/forum/files/436291/lantern.TXT)

**Comment by p3rcya** [comment]
请问现在问题还存在么？

**Comment by 772077730** [comment]
现在没有了，多谢~

**Comment by 772077730** [comment]
不行呢，之前以为可以了，但是现在又转圈了
