### ISSUE TITLE
今天终于恢复正常了

### ISSUE THREAD

**Issue by orivil** [getlantern/forum#110]
还以为不恢复了，正准备搭 VPN 呢

**Comment by HBXSZ** [comment]
我这里怎么还是上不了谷歌= =囧，lantern倒是能正常连接，蓝灯首页新闻加载异常缓慢

**Comment by orivil** [comment]
@HBXSZ 再等等吧，应该快了

**Comment by HBXSZ** [comment]
@orivil 嗯嗯，这GFW也是醉人，突然没了谷歌好不适应233

**Comment by velly** [comment]
可以了吗？ 我昨天就是翻过去~~ 结果装个Eclipse插件都装不了。蛋疼

**Comment by BingCool852** [comment]
好难受，突然不能翻墙了，希望快一点修复
