### ISSUE TITLE
手机清除数据后无法授权了

### ISSUE THREAD

**Issue by atoper** [getlantern/forum#1103]
我购买后，授权mac和Android设备

目前mac还能用，Android设备清除过一次数据，需要重新授权
但mac上没有找到给Android手机授权的办法？

补充说明下，我试着解绑了，以为解绑后可以重新绑定，但是还是不行

请问怎么解决？

**Comment by atoper** [comment]
好了，我在Android手机上安装了个3.0.0版本，可以让邮件发授权码，自己搞定了

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
