### ISSUE TITLE
蓝灯专业版无法登陆的问题已经解决，无法登陆的请进入

### ISSUE THREAD

**Issue by p3rcya** [getlantern/forum#1107]
桌面版解决步骤
**以下操作必须在绑定了蓝灯的电脑上进行，原始购买设备是默认绑定的**
1 退出蓝灯后，删除旧的yaml配置文件，目录见以下(目录可能是系统隐藏目录，需手动输入)
Windows XP C:\Documents and Settings\<用户名>\Application Data\Lantern\settings.yaml
Windows 7 - Windows 10 C:\Users\<用户名>\AppData\Roaming\Lantern\settings.yaml
Mac /Users/<用户名>/Library/Application Support/Lantern/settings.yaml
2 [点击这里下载蓝灯最新版本](https://github.com/getlantern/forum/issues/833)，安装。
3 打开蓝灯后，稍等几分钟，蓝灯就会自动变成专业版

安卓版解决步骤
**以下操作必须在绑定了蓝灯的安卓上进行，原始购买设备是默认绑定的**
1 在安卓上卸载蓝灯。
2 [点击这里下载蓝灯最新版本](https://github.com/getlantern/forum/issues/833)，安装。
3 打开蓝灯后，稍等几分钟，蓝灯就会自动变成专业版

如果已经成功登陆了专业版，想授权其他设备使用，[请看这个教程](https://github.com/getlantern/forum/issues/973)

**Comment by imvicchen** [comment]
@p3rcya 电脑重做系统了~ 识别不出来专业版咋搞

**Comment by p3rcya** [comment]
@imvicchen 硬件不变都可以恢复

**Comment by lifeforfun** [comment]
@p3rcya 我也重做了系统，我打开页面等了半天也没升级成专业版呢，刚刚才买了两年时长，重做了系统之后安装的也是最新版，我的系统是ubuntu 12 电脑是戴尔n4030

**Comment by p3rcya** [comment]
@lifeforfun 请问帐号是什么？

**Comment by orbancanon** [comment]
@lifeforfun 另外也请把日志发一下。

**Comment by wangpansheng** [comment]
我的刚买的,然后电脑重装系统了,按照上边的教程不管用呀,现在只有手机有授权,但是手机上没有找到可以授权电脑的功能! 手机现在的版本是3.0.7,怎么才能解决呀,花了钱,却用不了专业版,求快点解决,可以直接账号密码登录!!

**Comment by orbancanon** [comment]
@wangpansheng 手机版升个级就有那一项了。记得升级前不要卸载当前版本

**Comment by lifeforfun** [comment]
@orbancanon 蓝灯有账号这一说？如果问付款账号的话，支付宝：a791446794@163.com 
另外日志从哪里看？我这是ubuntu 32bit 版的

**Comment by jinxiaoze** [comment]
重装系统以后也是不知道怎么登陆，按照指示删掉setting重装也是不行

**Comment by GeekerAndyLove** [comment]
Hi,😀
电脑端和android端都是最新版本，电脑端授权android设备，电脑端显示授权成功（但是设备里并没有添加上）但是手机端一直没有任何反应 :(

**Comment by p3rcya** [comment]
@GeekerAndyLove 请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 并请提供帐号名。请及时提供，否则我们无法调查。

**Comment by GeekerAndyLove** [comment]
@p3rcya 您好，刚刚解决掉了，，，抱歉。是因为账号已达到三台，但是我的电脑双系统就相当于占用了两个设备，不是很合理，希望您能够反馈一下，谢谢。支持Lantern。

**Comment by HeDaZhi** [comment]
@p3rcya  按照教程方法依旧无法变为专业版，请问这种情况应该怎么解决？

**Comment by p3rcya** [comment]
@HeDaZhi 请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 并请提供帐号名。请及时提供，否则我们无法调查。

**Comment by allensun87** [comment]
蓝灯登录正常但翻不了墙

**Comment by Alvin9999** [comment]
@p3rcya  个人经验供您参考。新加坡ip对电信和移动网络的速度都不错。最近在网上有看到锐速可以提速，我不太懂，你有兴趣的话可以了解一下，如果可行，相信对lantern的速度会进一步提升。

**Comment by foxkathy** [comment]
我也是重装系统后就不行了，把我识别为不同设备，需要原始购买设备授权，可是我用的就是原始设备没办法再授权，请问有解决办法吗

**Comment by p3rcya** [comment]
@Alvin9999 谢谢，我们会调查
@foxkathy 新版会增加邮箱登录，本月会发布。公测时间内购买专业版有两个月额外时间赠送(正式版推出后，后台会自动加入)，所以请稍安勿躁。

**Comment by EvilNumber** [comment]
@p3rcya 我的魅族系統，但是安卓版的lantern每次打開后，總是自動會選擇off選項，根本翻不了墻

**Comment by alon007** [comment]
@p3rcya 我重装的也是原始的设备，也没有授权过，现在也没有办法登录了

**Comment by p3rcya** [comment]
新版蓝灯3.2已经支持邮箱登陆，请大家去论坛主页 https://github.com/getlantern/forum 下载。感谢给位的耐心等待！

**Comment by Engrtao** [comment]
很痛心啊，买了专业版，转了很久登录上了专业版，可是速度非常慢，更本没法用

**Comment by ollosonia** [comment]
购买了蓝灯专业版1年，我只用了5个月，这几天突然不能用了，提示：很抱歉，蓝灯似乎未在运行。请重启蓝灯并重试。 WINXP ，360浏览器，当时没开360安全卫士。 麻烦帮我看下怎么回事。  547696370@qq.com 是注册邮箱。

**Comment by p3rcya** [comment]
请报告网络环境，访问时段。
**请在本帖提供email**, 并使用应用内发送日志功能报告问题。若无法自动提交，请手动上传，方法见https://github.com/getlantern/forum/issues/1840#issuecomment-260143243 。请及时提供，否则无法调查，谢谢！

**Comment by nabu888** [comment]
手机没法用，nabu888@gmail.com

**Comment by nabu888** [comment]
日志文件已经上传

**Comment by MrWangLi** [comment]
Mac上一直无法登录专业版，提示账号找不到。是什么情况？
