### ISSUE TITLE
最新解决专业版无法登陆的办法，无用

### ISSUE THREAD

**Issue by 7pitter** [getlantern/forum#1108]
我在手机上购买的蓝灯，后来换了两个手机。。。
我的电脑在购买蓝灯后，硬盘挂掉了也换了电脑。。。

请问如何这样的情况能解决吗？按照公告里的方法试了，等了几分钟，还是无法登陆，包括手机。。。

**Comment by p3rcya** [comment]
**操作必须在原始购买蓝灯的电脑上进行**

你这样所有的硬件都换掉了的话，只能等以后版本支持邮箱回复。

**Comment by 7pitter** [comment]
怪我咯？能给个大概时间不？工作要翻墙很多

**Comment by p3rcya** [comment]
因为一般用户不太可能所有硬件都刚好同时换掉。你刚好这样，只能等新版。具体时间我还不知道

**Comment by EdwardAutumn** [comment]
楼主你这一次换三个设备也不能全怪软件吧。如果只是单纯看网页可以下个freebrowser代替用用

**Comment by 7pitter** [comment]
@EdwardAutumn 哈 不要误会，我没有怪蓝灯。。只是太巧了而已
