### ISSUE TITLE
用支付宝支付lantern1年的专业版，结果什么也登陆不上！！！

### ISSUE THREAD

**Issue by qingjulee** [getlantern/forum#1115]
结果登陆不上，还是免费版的，该找谁啊？蓝灯官方也没有个说法,郁闷的不得了，到底什么情况啊？

**Comment by EdwardAutumn** [comment]
官方人员已经在帮你看了。耐心点。

**Comment by qingjulee** [comment]
@EdwardAutumn 有你这句话就OK了。需要提供什么信息你告诉我。

**Comment by EdwardAutumn** [comment]
我不是官方人员…我就安慰你一下

**Comment by qingjulee** [comment]
你这是在玩我啊！

**Comment by qingjulee** [comment]
你不是是官方的人得瑟个毛啊？我这边着急着你还寻人开心啊？

**Comment by mengpeiwei** [comment]
me too

**Comment by mengpeiwei** [comment]
兄弟，解决了，去这个网站下载https://getlantern.org/ 然后把你电脑的原版删了重装就好了，记得语言选中文

**Comment by mengpeiwei** [comment]
语言选中文，记得，反正我重装就好了

**Comment by p3rcya** [comment]
@qingjulee  我是官方人员，我们正在帮你看了

**Comment by qingjulee** [comment]
@p3rcya 谢了，可以用的时候联系我。

**Comment by qingjulee** [comment]
@p3rcya 我可能购买了的时候没有网络出现问题了，没等绑定就退出页面了。

**Comment by qingjulee** [comment]
我马上就没有流量，咋整啊？是否可以再领取一次免费版的？ @p3rcya 
![image](https://cloud.githubusercontent.com/assets/21211238/18025473/64a2bb86-6c5d-11e6-975d-200b40985ea2.png)

![image](https://cloud.githubusercontent.com/assets/21211238/18025474/774b51bc-6c5d-11e6-8f78-5899b9ecd0d9.png)

**Comment by p3rcya** [comment]
已经回复到了 https://github.com/getlantern/forum/issues/1089 请不要重复发贴
