### ISSUE TITLE
关于专业版的登录建议

### ISSUE THREAD

**Issue by lxp0gb** [getlantern/forum#1129]
在已退出所有授权设备时，要登录已购专业版，现行的解决方法都要求是原购买设备。
这解决方案既步骤复杂又对于原购买设备不在身边或不可用的用户不可行，而且也隐含了安全问题。
试想，用户要退出授权设备，就是确定不在那个设备使用，如果真要再用他会再进行授权。
而现行的解决方法是允许非授权设备再次获得之前的授权，尽管它是原购买设备。
而且因为这个机制还产生了另外一个技术问题，被取消授权的设备还能继续以购买专业版的身份使用，尽管好像对用户有利，可以通过这个漏洞使用多于3台设备，最多多少台没试过。
建议还是允许通过注册的电邮地址登录加密码登录。
之前一直不采用这种方法，我相信开发团队一定考虑过，最后估计想避免某些安全或管理漏洞，才没采用这种传统的登录方式。
能知道原因吗？

**Comment by p3rcya** [comment]
没有使用电子邮件是因为被国内邮件商过滤了。但我们以后会加入邮件找回帐号的功能的。

关于安全问题，其实不是原始购买设备，只要是已绑定的专业版设备都可以找回。原始购买设备，如果被解绑，还是无法登陆的

**Comment by lxp0gb** [comment]
新版已解决，关issue！
