### ISSUE TITLE
连不上的原因我觉得是网络服务商搞的鬼

### ISSUE THREAD

**Issue by shendongdebing** [getlantern/forum#113]
Jun 06 03:40:20.794 - 1m27s ERROR balancer: balancer.go:79 Unable to dial via (trusted) chained proxy at 159.203.202.11:443 [] to connect://logs-01.loggly.com:443: Unable to dial server (trusted) chained proxy at 159.203.202.11:443 []: dial tcp 159.203.202.11:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. on pass 2...continuing

错误LOG是这么写的，我在江西上不了，可我朋友在广东却可以用。

**Comment by wesavetheworld** [comment]
You are right, Jiang Xi Dian Xin and Jiang Xi  Lian Tong have big problems.

**Comment by p3rcya** [comment]
请上传log。log进入Lantern应用安装目录下后点击logs文件夹。 在发帖时将文件拖拽到到发帖的地方就可以上传了。

**Comment by shendongdebing** [comment]
@p3rcya 已经可以用了，应该不是蓝灯的问题

**Comment by shendongdebing** [comment]
@p3rcya 在公司可以用，回家又不能了。。。
[lantern.txt](https://github.com/getlantern/forum/files/304775/lantern.txt)
