### ISSUE TITLE
想要退款的进来下。

### ISSUE THREAD

**Issue by imvicchen** [getlantern/forum#1131]
已经等了n久了，耽误工作和学习，我已经不想再等了，求退款！
也许等你修复了以后，我会在来支持，但是目前我觉得你退款给我是最好的处理方式，谢谢你。
misterxuan@foxmail.com支付账号
misterxuan@qq.com登录账号
支付时间 2016-08-14 00:26

**Comment by p3rcya** [comment]
请问具体是什么情况？ 请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 ，方便我们调查，谢谢

**Comment by imvicchen** [comment]
@p3rcya 我发帖子不是一天两天了，也不是一贴两贴了，从专业版无法登录，到无法识别，太耽误事儿了，而且用了之后不打开 还不能上网。。。我现在凭白无故 就花了180买个bug回来，你要说你是骗子，我就认栽了，如果可以，我协商退款到事儿吧，我不太想用了！

**Comment by Linausername** [comment]
@p3rcya  我也实在不能容忍蓝灯了，非常不稳定，我花钱不是来帮你们测试的。看下如何退款

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)

**Comment by imvicchen** [comment]
@p3rcya 你还发这个有什么用，要是好用就不会要求退款了，请你直视问题，别拿无用公帖敷衍！！！

**Comment by philipslu** [comment]
@p3rcya 你的那些方法一点用都没有，完全无效，我按你的写法重做了不止3次了。买个专业版就是个最大的失败。

**Comment by philipslu** [comment]
而且退款无门！一直陪着试用新版本，但是新版本也没毛用。一直无法解决真正的问题。

**Comment by tulate** [comment]
退款这个罪恶的想法。。。在我脑海中也闪现了好几回了

**Comment by imvicchen** [comment]
说让我上传日志，我电脑刚重新做了系统，这日志能反映出啥呢，我现在只是想退款！

**Comment by Linausername** [comment]
我们被骗了。认栽吧！

**Comment by imvicchen** [comment]
我看他们应该是把钱花了 没钱退款😂

**Comment by p3rcya** [comment]
请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 并请提供帐号名。请及时提供，否则我们无法调查。

**Comment by Alvin9999** [comment]
站在蓝灯开发组的角度看，退款的确是一个很敏感的问题，有点“牵一发而动全身”的意思，如果开了先例，只给你退，不给别人退，也不好。看的出来，他们其实也很努力的在解决此问题，可能需要更多的时间和包容。

站在用户的角度，花了钱不能翻墙，那不是白花了吗？心情十分理解。所以，我建议楼主可以先用这款永久免费的一键翻墙浏览器（pac版）以解燃眉之急，等到蓝灯开发者开发出了更好的软件，换成蓝灯即可。百度网盘下载地址：http://pan.baidu.com/s/1mhEac6O  

我自己用下来，白天看视频720p很顺畅，晚上高峰期480p没有问题。因为不同地区，封锁强度和网络环境不同，所以速度不可能一样。pac版集成了5个不同的pac地址，可以切换着使用，如果你那里一个都不能用的话，可以在下面的更新地址里下载goagent版，goagent使用的高质量谷歌ip且ip源充足，也是不错的选择，同样永久免费。

软件更新地址：https://github.com/Alvin9999/new-pac/wiki

**Comment by lemonskkyt** [comment]
我的倒是没问题了，就是刚买的三四天不能用.......
但我觉得蓝灯处理问题的方式实在太糟糕了，特别是对于账号问题，搞不定你可以全部开了免费用啊，等搞定了再弄账号授权什么的，你都免费了这么久了，就差这一两个月？？？就算你要测试改进后的账号系统有没用，你也可以给免费的限制个200-500KB/S什么的，收费的不限速就好了，现在这样当初积累的口碑全毁了........

**Comment by imvicchen** [comment]
@Alvin9999 首先，无论是你官方派的公关号，还是个人粉丝，都先说声谢谢，我觉得从我以往发帖的状态和话术来看，我都想要解决问题，并不希望退款，但是官方那个账号一直回避问题，不正视问题的存在，官方的技术贴也并不能解决问题，得不到问题解决，也没有官方的理解，受到委屈当然很伤感，从支持蓝灯，到现在被伤到，我觉得这并不是我一厢情愿的事儿，钱退和不退还得看他们给不给，我有留邮箱，这并不一定要在这里公开退款！免费vpn，花钱的好用都可以，我不想浪费时间所以消费，钱花的冤枉了都不爽，我也不是冲动消费的人，考虑过后才会选择购入，毕竟人家都有一个一个月的，这上来就年费！

我购买完第一天就不能用！都多长时间了！

我的做法希望官方得到重视，这并不是恶意的，我和我们都只想得到问题的解决以及合理的回复。

1 我最希望的还是退款
邮箱：misterxuan@qq.com

2 程序给力的话，给一个修复bug的确定时间

3 我认栽。

**Comment by tulate** [comment]
既然做了收费政策，就一定要做退款政策。
顺顺利利退了款，等技术问题解决了，用户还会顺顺利利回来的，
只有收费政策没有退款政策，就意味着。。。。。。
说到底，翻墙市场，一定是信誉市场，一定是口碑传播，
否则技术再好也不会长久。

**Comment by Alvin9999** [comment]
@imvicchen   十分理解

**Comment by tulate** [comment]
1 我最希望的还是退款
邮箱：tulate#qq.com

2 程序给力的话，给一个修复bug的确定时间

3 我认栽

**Comment by imvicchen** [comment]
@tulate 要走队形的节奏

**Comment by tulate** [comment]
都走了队形了，官方还没有回复，看来是认栽的节奏了。
呼吁@p3rcya回复一下吧。

**Comment by qq425729** [comment]
刚要买 来这里看了一眼  额....

**Comment by AaronSum** [comment]
哇，打算买呢，这一看，还咋买啊。。

**Comment by tulate** [comment]
大家都看到了，官方就是装作没看到

**Comment by xanaduo** [comment]
1 我最希望的还是退款
登录邮箱：980086933@qq.com
支付宝：18672935910
2 程序给力的话，给一个修复bug的确定时间
3 我认栽

**Comment by huchiwen** [comment]
支持退款！！！

**Comment by gagazx** [comment]
呵呵提到退款官方人员只会说：请问具体是什么情况？ 请按照此帖上传日志 #358 ，方便我们调查，谢谢

然后就没下文了。

**Comment by p3rcya** [comment]
LZ的问题应该已经解决了。请看 https://github.com/getlantern/forum/issues/1123#issuecomment-246311729
