### ISSUE TITLE
购买失败

### ISSUE THREAD

**Issue by nerdDan** [getlantern/forum#1141]
在 Android 客户端上购买，填了邮箱卡号。信用卡有效期最晚能选择 2020 年，我的卡是 2021 到期。我选择了错误的有效期 2020，点购买，提示卡号错误。

再到桌面 Chrome 版上购买，相同的邮箱和卡号，有效期填了正确的 2021，提示邮箱已被占用。银行反馈扣款成功。

现在似乎钱花出去了，没买到专业版 lantern。

**Comment by imvicchen** [comment]
@nerdDan 可以考虑暂时不要购买，因为bug问题特别多，买了以后也不能正常使用，等待官方修复这些致命问题后在考虑！

**Comment by p3rcya** [comment]
请报告邮箱并请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 ，方便我们调查，谢谢 

@orbancanon 请看看

**Comment by nerdDan** [comment]
@p3rcya file is too large to upload
![Uploading image.png…]()
