### ISSUE TITLE
那个P管理员，请你正视问题，给我们肯定的答复！

### ISSUE THREAD

**Issue by shitlantern** [getlantern/forum#1147]
第一：速度什么时候可以好，每天都是正在购买正在购买，到底要买到什么时候？早知道我就买私人搭建的Shadowsocks服务，一个月才几块钱，速度比Lantenr所谓专业版快多了。我想问你，到底什么时候可以把速度稳定下来，一个星期？一个月？一年？
第二：到底能不能退款？如果第一个问题无法肯定回复，那回答我第二个问题，到底能不能退款？每次遇到问题，都是“请上传Log””我们正在调查“，然后你看了Log之后有没有查明问题？查明问题了有没有告知大家那个Log的问题？没有吧？你们可能没有财务管理后台吧？收了钱就收了钱，根本不知道钱是谁的吧？
第三：管理员你是不是Lantern开发团队的？如果不是，请你从这个所谓的论坛消失，不需要你这种什么卵用都没的人。如果最后发现这是一个骗局，我祝你全家安康！

**Comment by shitlantern** [comment]
我猜你也仅仅是一个“管理员”，什么都不知道的，那你还算赶紧滚蛋吧，别在这里丢人现眼了！

**Comment by p3rcya** [comment]
人身攻击的帖子一律不予回复。
