### ISSUE TITLE
如何知道好友使用了我的邀请码

### ISSUE THREAD

**Issue by lwhsteven** [getlantern/forum#1158]
如题，如何知道好友使用我的邀请码了，我何时开始免费了，使用的时间如何查询。

**Comment by p3rcya** [comment]
专业版帐号管理界面可以查询

**Comment by lwhsteven** [comment]
我登录的网页没有账号管理，我都没购买怎么有账户管理界面。我是说别人买了，用了我的邀请码，我如何知道？然后如何让自己成为专业版本。

**Comment by p3rcya** [comment]
别人使用后，你就会自动成为专业版。然后就有这个专业版帐号管理界面了
