### ISSUE TITLE
蓝灯公测用户不是说要多送2个月吗

### ISSUE THREAD

**Issue by 1604563715** [getlantern/forum#1189]
我的怎么没送呢，我也是公测用户。
[lantern.txt](https://github.com/getlantern/forum/files/453281/lantern.txt)

**Comment by 1604563715** [comment]
![1](https://cloud.githubusercontent.com/assets/20652180/18224099/6137ee58-71fd-11e6-8c77-9fbded9a5e89.JPG)

**Comment by YOYOsheep** [comment]
是出了正式版后送吧，现在速度还是很慢，还是测试期。

**Comment by p3rcya** [comment]
楼上说的对
