### ISSUE TITLE
最近网速都好慢

### ISSUE THREAD

**Issue by yummy222** [getlantern/forum#1192]
我是Pro用户，但是最近网速好慢啊，上youtu看视频都看不了，希望给个答复，毕竟花了钱就是觉得你们之前没收费钱很好有，支持一下，现在这样让我很难过啊，
13631277700@163.com

**Comment by p3rcya** [comment]
你关闭了这个问题是因为速度回复了吗？

**Comment by SSRspeed** [comment]
欢迎使用SSR加速，www.ssrcheap.com
