### ISSUE TITLE
帮蓝灯宣传一下——蓝灯官方宣传片

### ISSUE THREAD

**Issue by rocknrollfly** [getlantern/forum#1202]
蓝灯官方宣传片，2年前发布的，制作得不错，现在看依然让人感动、激动
这么久以来个人使用蓝灯都基本流畅正常，客服也很专业耐心，为了表示感谢，在这里帮蓝灯宣传一下，希望蓝灯永远不忘记梦想、一直努力、越来越强大

https://youtu.be/9IrfAPo4ASw  更新：（youtu.be是youtube官方现在使用的短网址域名，请放心访问）

不放心的这里有长网址： https://www.youtube.com/watch?v=9IrfAPo4ASw

**Comment by EdwardAutumn** [comment]
@p3rcya 看链接名字应该是钓鱼网站，请速度清理。

**Comment by rocknrollfly** [comment]
@EdwardAutumn 老兄，youtu.be是youtube官方的短网址域名，好吗？不信去查查

**Comment by EdwardAutumn** [comment]
http://listofscams.blogspot.sg/2011/07/youtube-links-hackvirus-alert.html
我个人不是很喜欢这种东西。见谅。

**Comment by rocknrollfly** [comment]
@EdwardAutumn 好吧，有长网址仍然不放心那就算了，只作资料保存，这帖子我关了就当没发过吧

**Comment by EdwardAutumn** [comment]
我只是说我个人不喜欢。用短域名钓鱼的例子是很多的，本人对你并没有恶意，请不要误会。

**Comment by p3rcya** [comment]
@rocknrollfly @EdwardAutumn 这个确实是官方帐号发的宣传片。
