### ISSUE TITLE
mac系统无法翻墙这两天？

### ISSUE THREAD

**Issue by kkguodong** [getlantern/forum#1205]
你们有这样问题吗？无论是新版本还是旧版本。。MAC系统无效果。有这样问题的说一下。pc版本可以用吗？

**Comment by kkguodong** [comment]
这个文本是我PC电脑的日志文件。。麻烦技术人员看一下。。之前用一年了，最近上不去了

**Comment by SSRspeed** [comment]
欢迎使用SSR加速，www.ssrcheap.com
