### ISSUE TITLE
本月会支持邮箱登陆

### ISSUE THREAD

**Issue by p3rcya** [getlantern/forum#1217]
鉴于有部分用户无法使用动态授权码授权其他设备使用专业版，本月我们会加入邮箱登陆的功能，请大家等待新版。新版发布后，用户可以使用动态授权码授权其他设备，也可以使用邮箱登陆。

**Comment by li5551** [comment]
很棒

**Comment by junecwf** [comment]
这个可以有

**Comment by li5551** [comment]
iOS版本什么时候发布呢？

发自我的 iPhone

**Comment by SmallJimmy-Ha** [comment]
本月什么时候啊。

**Comment by chjng89** [comment]
我买了专业版，但重启计算机后，登陆信息就小时了，又没有邮箱登陆，所以不能用专业版，也烦不了墙？在邮箱登陆的版本发布前，能不能先帮我解决一下这个问题。我的账号是258053532@qq.com

**Comment by chjng89** [comment]
能在新版本发布之前这段时间，能先解决购买专业版的用户的使用问题吗？

**Comment by p3rcya** [comment]
新版蓝灯3.2已经支持邮箱登陆和MacOS Sierra，请大家去论坛主页 https://github.com/getlantern/forum 下载。感谢给位的耐心等待！

**Comment by SmallJimmy-Ha** [comment]
@p3rcya 我有台windows 10电脑被取消授权了， 但是依然还是显示pro。 还能显示我其他的已授权设备。 怎么彻底取消那台windows 10电脑的电脑？
