### ISSUE TITLE
打开Lantern之后，QQ掉线，Safari打不开网页

### ISSUE THREAD

**Issue by 356285883** [getlantern/forum#1225]
RT，系统版本是Mac OS 10.11.6
Lantern版本是3.1.4

**Comment by lianddao** [comment]
是挺垃圾的，我买了我后悔，连谷歌硬盘都连接不上，尼玛，还怎么自称FQ

**Comment by p3rcya** [comment]
@356285883 @lianddao 请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 请及时提供，否则我们无法调查。
