### ISSUE TITLE
真心，买了两年速度100K上下想退款

### ISSUE THREAD

**Issue by wrzasd** [getlantern/forum#1234]
真心，买了两年速度100K上下想退款，退一半也是好的。对这个软件无语了

**Comment by p3rcya** [comment]
我们正在内测更好的线路， 请去 https://github.com/getlantern/forum/issues/1152 申请。
公测时间内购买专业版有两个月

**Comment by wrzasd** [comment]
再信你们一次，我今天把grennvpn续费了，2M/s，速度快的飞起好么！！！！！！！！！！！！！！！！

**Comment by wrzasd** [comment]
@p3rcya  再信你们一次，我今天把grennvpn续费了（之前想着买了你们的就不续green了），2M/s，速度快的飞起好么！！！！！！！！！！！！！！！！

**Comment by imvicchen** [comment]
@wrzasd 是greenvpn？什么价格，有官网吗？我看看

**Comment by wrzasd** [comment]
@imvicchen http://gjsq.me/760120 优惠码是10off2016

**Comment by imvicchen** [comment]
@wrzasd 说实话，我也想退款，特别想退款！！！

**Comment by wrzasd** [comment]
@imvicchen 差不多价钱_(:з」∠)_，我现在已经无力吐槽了，就当打水漂或者送人算了_(:з」∠)_

**Comment by wrzasd** [comment]
@imvicchen  不过green缺点也蛮明显的，要挑对线路，否则慢的想自杀，，，，没用过先买一个月试试_(:з」∠)_而且官网经常换，只能通过软件找到官网地址，外面假网站太多

**Comment by imvicchen** [comment]
@wrzasd 我记得真的是国外的，国内的不敢说，现在vpn市场太乱，但是像蓝灯这种花了钱干脆用不了的也是第一个

**Comment by wrzasd** [comment]
@imvicchen  云墙不错，不过是流量制的，像我这种看视频下软件的伤不起

**Comment by imvicchen** [comment]
@wrzasd 我有用，只是公司内网需要来回切，要不内网一些软件用不来

**Comment by rocknrollfly** [comment]
@imvicchen 官方正在测试新线路，蓝灯3还处于测试阶段有问题请各位网友谅解官方，蓝灯是由墙外力量开发的新系统，要适应墙内环境和使用习惯需要时间，相信他们已经在很努力了。专业版用户赠送得有补偿时间。VPN只是方便，适合用于娱乐用途为主，但安全可靠性。。。。蓝灯和VPN区别请看这里 #361

**Comment by rocknrollfly** [comment]
@imvicchen 补充：我这里使用蓝灯大多数时间都流畅、快捷稳定，只出现过很短暂的连接后打不开被封禁站点的问题，更说明是不同用户的网络环境线路有区别。

**Comment by cablsbs** [comment]
手机一直无法正常上网，电脑还好

**Comment by Gdname** [comment]
表示免费蓝灯伤不起了，看个视频，最低画质都要生要死了

**Comment by p3rcya** [comment]
@wrzasd 新数据中心应该会快起来了，你再看看。

@Gdname 看视频的话，推荐购买专业版。因为免费服务器资源限制，不好意思。

**Comment by gaotong2055** [comment]
改用小双加速了，还是SS系列的比较稳定

**Comment by p3rcya** [comment]
不要挖坟
