### ISSUE TITLE
无论是在windows上还是在mac上 最新版的chrome都是无法翻墙的

### ISSUE THREAD

**Issue by mishengqiang** [getlantern/forum#13]
在windows上chrome刚刚开始无法翻墙的时候，卸载迅雷即可，但是后来chrome升级后，卸载迅雷也是无法翻墙的，其它浏览器都可以翻墙。
在mac上chrome一直无法翻墙，Safari和Firefox都是可以的。
这真是一件神奇的事情，Google支持的翻墙软件chrome竟然无法翻墙。

**Comment by percyalpha** [comment]
请上传log，说明系统和浏览器版本。 log进入Lantern应用安装目录下后点击logs文件夹。 在发帖时将文件拖拽到到发帖的地方就可以上传了

**Comment by mishengqiang** [comment]
我已经知道了为啥了，因为被另一个软件代理了。
