### ISSUE TITLE
要点脸，行吗？

### ISSUE THREAD

**Issue by l941005** [getlantern/forum#1306]
收费的 不如 免费的。
你们都说房价高，可房价越高质量越好。
你们倒好，一个尚未完善的软件收费也就算了。
出了问题就只会弄一些无用的帖子来敷衍。
好比你问我，你要100万，我回答你说，那你努力啊。
这不是废话吗？

**Comment by whybux** [comment]
是的。只从收费了后，就不好用了。

**Comment by zsqp447** [comment]
什么不好比去和房子比，全世界比蓝灯更坑爹的我第一个想到的就是天朝的房子，楼主一定是土豪不愁钱买房，或是运气好没买到坑爹的天价烂房

**Comment by CaliloNio** [comment]
发的帖子几个小时就给关闭了～～

**Comment by syjml** [comment]
@p3rcya 退钱！！！退钱！！！退钱！！！退钱！！！退钱！！！退钱！！！退钱！！！@p3rcya 退钱！！！退钱！！！退钱！！！退钱！！！退钱！！！退钱！！！退钱！！！@p3rcya 退钱！！！退钱！！！退钱！！！退钱！！！退钱！！！退钱！！！退钱！！！@p3rcya 退钱！！！退钱！！！退钱！！！退钱！！！退钱！！！退钱！！！退钱！！！@p3rcya 退钱！！！退钱！！！退钱！！！退钱！！！退钱！！！退钱！！！退钱！！！

**Comment by ShangXinbo** [comment]
就是不退就是不退，你怎么着

**Comment by kerecsenchen** [comment]
这是不是骗子？？

**Comment by ShangXinbo** [comment]
不是骗子，只是长的有点象骗子

**Comment by sun1a2b3c** [comment]
各位等这个月更新完再看看

**Comment by whybux** [comment]
已放弃蓝灯。已入别的ss

**Comment by ShangXinbo** [comment]
已放弃蓝灯，已入别的ss

**Comment by p3rcya** [comment]
新版蓝灯3.2已经支持邮箱登陆和MacOS Sierra，请大家去论坛主页 https://github.com/getlantern/forum 下载。感谢给位的耐心等待！
