### ISSUE TITLE
总是提示错误！

### ISSUE THREAD

**Issue by KelaKing** [getlantern/forum#131]
我已经卸载迅雷，为什么提示还要卸载迅雷？
![2016-06-08 11 08 27](https://cloud.githubusercontent.com/assets/13584044/15881584/ad471b12-2d69-11e6-868a-2c480702deef.png)

**Comment by p3rcya** [comment]
请上传log。log进入Lantern应用安装目录下后点击logs文件夹。 在发帖时将文件拖拽到到发帖的地方就可以上传了。

迅雷和蓝灯冲突

**Comment by KelaKing** [comment]
> 请上传log。log进入Lantern应用安装目录下后点击logs文件夹。 在发帖时将文件拖拽到到发帖的地方就可以上传了。
> 
> 迅雷和蓝灯冲突


[lantern.log.zip](https://github.com/getlantern/forum/files/304199/lantern.log.zip)
我已经卸载迅雷了，OS X的log在~/Library/Logs/Lantern对吧？
