### ISSUE TITLE
大家推荐下，有那些，翻强软件(免费+收费)

### ISSUE THREAD

**Issue by Boss198** [getlantern/forum#1315]
大家推荐下，有那些，翻强软件(免费+收费)

**Comment by YOYOsheep** [comment]
PC的，我觉得XX-NET速度不错。 Lantern抽风我就靠这个了。 手机我就只能用Lantern

**Comment by jindongwang** [comment]
我现在用ezcat,h t t p : // e z c a t . x y z

**Comment by pjomvndy** [comment]
我现在用goagent版（免费），很稳定，电信20M https://github.com/Alvin9999/new-pac/wiki
![2](https://cloud.githubusercontent.com/assets/22160550/18619738/e0bcede6-7e36-11e6-81b8-24775632b12e.PNG)
![3](https://cloud.githubusercontent.com/assets/22160550/18619740/f1689ce4-7e36-11e6-8d24-cffd959a7061.PNG)

**Comment by Gdname** [comment]
楼上的，这个东西= =是浏览器吗？？我去下载了一个，发现那个管家提示有病毒= =

**Comment by p3rcya** [comment]
因为有病毒疑问，我暂时关闭此贴，以防万一

**Comment by Gdname** [comment]
这个。。。因为我一句话就。。。

**Comment by p3rcya** [comment]
关闭并不是删帖啊。还是可以看到的
