### ISSUE TITLE
你好，我的专业版账户已经过期，请及时调查一下

### ISSUE THREAD

**Issue by xisuly123** [getlantern/forum#1325]
[lantern.txt](https://github.com/getlantern/forum/files/479092/lantern.txt)

帐号 314708576@qq.com

2016.7.16购买了一年的专业版，今天已经过期。这怎么回事？？

**Comment by xisuly123** [comment]
@p3rcya 我的专业版已经过期了，你们说是给调查也没有结果啊？现在只能用免费版了。明明买了一年的，怎么刚用2个月就过期？？？

**Comment by p3rcya** [comment]
我把此帖合并到 https://github.com/getlantern/forum/issues/1298
