### ISSUE TITLE
烂事真的烂

### ISSUE THREAD

**Issue by kerecsenchen** [getlantern/forum#1328]
免费版畅通无阻 后来就不行了 升级了专业版 也还是不行  youtube都上不去 不管电脑还是手机    
541448862chen@gmail.com

**Comment by kerecsenchen** [comment]
@p3rcya

**Comment by slqcug** [comment]
我也是，强烈要求退钱啊

**Comment by cnmlantern** [comment]
想要退款的，找这3个人退款，@EdwardAutumn @paperbag @kxkxkx

**Comment by p3rcya** [comment]
我们正在内测更好的线路， 请去 https://github.com/getlantern/forum/issues/1152 申请。
公测时间内购买专业版有两个月额外时间赠送(正式版推出后，后台会自动加入)，所以请稍安勿躁。

**Comment by SSRspeed** [comment]
欢迎使用SSR加速，www.ssrcheap.com

**Comment by p3rcya** [comment]
新的线路已经发放到LZ这里了。
