### ISSUE TITLE
自己搭建的openvpn服务器找人共号

### ISSUE THREAD

**Issue by Ralphci** [getlantern/forum#133]
加q1550451341. 自己的服务器10m宽带速度没问题。翻墙随便翻，YouTube基本秒放

**Comment by Ralphci** [comment]
希望找个人共号，一个月最少出24，觉得可以加q详聊

**Comment by cnfan** [comment]
如果能凑够5个人，我加入。

**Comment by Ralphci** [comment]
两个了

**Comment by p3rcya** [comment]
OpenVPN不是按照协议特征封了么？ L2TP什么可能还好点吧

**Comment by Ralphci** [comment]
至少我还稳定

**Comment by metayx** [comment]
你香港服务器吧，哪个提供商的，你要是搞搭建ppp的VPN劝你还是别搞了，流量大的话分分钟封你主机。自用还是可以的。

**Comment by Ralphci** [comment]
又不是商用，两三个人有关系么？
