### ISSUE TITLE
怎么才能退钱？我昨天买了个一年的账号，结果发现专业版竟然体验比免费的还差

### ISSUE THREAD

**Issue by slqcug** [getlantern/forum#1331]
赶紧退钱给我吧

**Comment by slqcug** [comment]
用了一天而已，请联系我的账号slq307@gmail.com。给我退钱吧

**Comment by medz** [comment]
我也买了～说实话，给了钱，体验也非常差，甚至造成国内的一些网站访问都出现了问题，不过，官方是不会退钱的，这点我很肯定，因为我也是最早推出商业版本就买了的。其次，说好的一个月后稳定送一个月额补偿，目前并没有收到补偿，我看了下官方开发团队的提交代码的人，只剩下一个人，我能确定的就是，蓝灯不会再好了。

**Comment by zhouzyiOS** [comment]
一般软件从免费到收费只有两个原因：1扩招，加了许多高级功能 2.要黄了，在黄之前争取捞一笔

**Comment by xanaduo** [comment]
我们是不是要见一个维权群，维权？谁牵个头！
QQ：980086933

**Comment by cnmlantern** [comment]
想要退款的，找这3个人解决，@EdwardAutumn @paperbag @kxkxkx

**Comment by xanaduo** [comment]
果然是骗子，刚才有个人说他举报后被封了，还是花钱买教训吧

**Comment by ishize** [comment]
哎。这钱花的。挺冤的

**Comment by SSRspeed** [comment]
欢迎使用SSR加速，www.ssrcheap.com

**Comment by youe360** [comment]
没搞错吧，前几天还看到管理现在人都不见了！我是没法上了上来看看，花钱打水漂的节奏？

**Comment by p3rcya** [comment]
@xanaduo 除了广告贴，没有封过其他帖子。
@youe360 我不在么？

**Comment by p3rcya** [comment]
正在给专业版用户发放更好的线路。因为是分批次发放，你可能还要等等。

**Comment by p3rcya** [comment]
已经发放完毕

**Comment by connieyeli** [comment]
能不能退钱？？？更新到3.2.1都不能翻墙！而且开了蓝灯连普通网站也很难上！确实和其他网友所说并没有稳后加1个月的使用限期！

**Comment by p3rcya** [comment]
@connieyeli 请问你用的是什么线路？ 请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 请及时提供，否则我们无法调查。 

正式版发布后，会赠送两个月。现在还没发布呢
