### ISSUE TITLE
两年专业版，Mac，不稳定，有时候刷新n遍也无法翻，截止此刻。

### ISSUE THREAD

**Issue by jyufeng** [getlantern/forum#1342]
两年专业版，Mac，不稳定，有时候刷新n遍也无法翻，截止此刻。

**Comment by jyufeng** [comment]
所谓内测专业线路我如何了解并给予内测评价呢

**Comment by jyufeng** [comment]
lantern web界面动不动提示‘您的免费流量已用完，。。。等等‘，画圈.......，画好了web显示pro了也没用，真的不如n周，n月前免费时代呢。

**Comment by jyufeng** [comment]
貌似现在又回到老早前的nl，sg，jp的线路，jp目前最好。

**Comment by jyufeng** [comment]
又转圈，看多久‘正常’

**Comment by jyufeng** [comment]
YouTube视频直接
<img width="956" alt="default" src="https://cloud.githubusercontent.com/assets/8719855/18668546/a934828e-7f68-11e6-9cf9-2994ec618705.png">

**Comment by jyufeng** [comment]
YouTube视频直接
![Uploading 未命名.png…]()

**Comment by p3rcya** [comment]
新版会增加邮箱登录，本月会发布。公测时间内购买专业版有两个月额外时间赠送(正式版推出后，后台会自动加入)，所以请稍安勿躁。

**Comment by SSRspeed** [comment]
欢迎使用SSR加速，www.ssrcheap.com

**Comment by SSRspeed** [comment]
欢迎使用SSR加速，www.ssrcheap.com
