### ISSUE TITLE
[已解决]刚买了一年的，结果我开Google首页开了5、6分钟！求退款。

### ISSUE THREAD

**Issue by pkl6612** [getlantern/forum#1352]
刚买了有一个小时，开Google首页都得5、6分钟都打不开。
如果不能解决的话请退款，扣我1一个月的钱也行。
我看了很多帖子，你们有困难可以理解，但是我们花了钱却得不到相应的服务，退款也是讲道理的吧。
![lantern](https://cloud.githubusercontent.com/assets/19401744/18701993/44133616-8012-11e6-8af4-9f64339d2393.png)
日志我也上传了，改了一下后缀名，因为log和zip都总是上传失败。

**Comment by gagazx** [comment]
还想退款？想多了

**Comment by houser0323** [comment]
我也是，太坑了，万恶的资本主义

**Comment by SSRspeed** [comment]
欢迎使用SSR加速，www.ssrcheap.com

**Comment by ThinWonton** [comment]
自己搭建吧

**Comment by pkl6612** [comment]
@p3rcya 是不是给我换了服务器了？现在虽然速度不快，但已经能打开谷歌和youtuobe了。凑合能用就不要求退款了。感谢！

**Comment by p3rcya** [comment]
@pkl6612 对。线路我们会一直改进的。有时候封的厉害，要时常换

**Comment by p3rcya** [comment]
已经解决我关闭了
