### ISSUE TITLE
我要退款！！！！！！

### ISSUE THREAD

**Issue by houser0323** [getlantern/forum#1354]
houser.0323@gmail.com
付费专业版安卓手机，一个网页也没打开过，卸载后重新安装，然后登录入口都没有，exm?
这叫做软件？这叫做付费软件？
做不了滚蛋好么！！！还老子钱

**Comment by rocknrollfly** [comment]
蓝灯目前遭到重点封锁，官方正努力解决，另外请检查你的网络环境和设置
官方将推出新版，赠送有专业版用户使用时间，请耐心冷静，稍安毋躁

**Comment by rocknrollfly** [comment]
蓝灯在技术和背景上是强大的，只是被GFW盯死了。

**Comment by maxxsun** [comment]
楼主别急，我是电信线路的，专业版速度也很慢。相信蓝灯肯定会解决的。

**Comment by SSRspeed** [comment]
使用SS，速度快，线路多。www.ssrcheap.com

**Comment by p3rcya** [comment]
新版会增加邮箱登录，本月会发布。公测时间内购买专业版有两个月额外时间赠送(正式版推出后，后台会自动加入)，所以请稍安勿躁。

**Comment by chjng89** [comment]
@p3rcya 我找不到登陆的入口，所以无法登入，也无法发送log.等于我买了账号根本用不上。因为没有地方可登陆。请解决！！！！

**Comment by chjng89** [comment]
@p3rcya 我的账号是258053532@qq.com

**Comment by raymondlee5918** [comment]
我觉得是这样，不管你有啥问题。好歹你在多台授权的时候，能不能搞的用个邮箱验证码或者手机验证码来搞定？使用临时的激活码，我白天在公司上班选择了，晚上回家才能打开电脑输入，难道让我的公司电脑一天都不关机吗？请在多台授权这方面再人性化一点，谢谢了！

**Comment by p3rcya** [comment]
新版蓝灯3.2已经支持邮箱登陆和MacOS Sierra，请大家去论坛主页 https://github.com/getlantern/forum 下载。感谢给位的耐心等待！
