### ISSUE TITLE
手机和pc都重装了，请问还有什么办法登陆购买的专业版

### ISSUE THREAD

**Issue by lxp0gb** [getlantern/forum#1360]
手机和pc都重装了，请问还有什么办法登陆购买的专业版

**Comment by p3rcya** [comment]
新版会增加邮箱登录，本月会发布。公测时间内购买专业版有两个月额外时间赠送(正式版推出后，后台会自动加入)，所以请稍安勿躁。

**Comment by lxp0gb** [comment]
在新版发布前，能否先让我登录呢？我需要提供什么资料，提供到哪呢？直接把我电邮发到这里，其实不安全。我昨晚已经通过app里反馈问题反馈过，但好像除了邮箱收到自己的日志和下载链接，没对登录没帮助。

**Comment by p3rcya** [comment]
本月就会发布了，所以请稍微等下，不好意思

**Comment by lxp0gb** [comment]
谢谢回答，我自己已经找到解决方法了。这个issue可以关了。
