### ISSUE TITLE
蓝灯会发布新版支持MacOS Sierra

### ISSUE THREAD

**Issue by p3rcya** [getlantern/forum#1364]
现在的版本还不支持MacOS Sierra，本月会发布新版支持MacOS Sierra。大家可以等几天再升级系统。

**Comment by leweihe** [comment]
说真的,别把这种东西放github.我还想好好用github呢.....

**Comment by p3rcya** [comment]
我们就是用Github开发蓝灯的。不放Github放哪里？

**Comment by Hwatu** [comment]
希望进度可以快一点...已经忍了很久了

**Comment by lsiuhen** [comment]
手残升级了系统 咋弄 要等多久呢大神？

**Comment by code4impl** [comment]
一样的手残重装了新系统，哎。

**Comment by yspic** [comment]
手残升级了。。。谢谢更新。我是专业版的，上不去看不到很着急哦。

**Comment by p3rcya** [comment]
本月就能发布了，不好意思。

**Comment by jessezhao** [comment]
耐心等待啊，还好我是来研究代码的

**Comment by clayzhu** [comment]
虽然是发现用不了再看到这个的，不过还是点个赞！

**Comment by AesirTitan** [comment]
加油👏

**Comment by p3rcya** [comment]
新版3.2已经发布，支持MacOS Sierra。请大家去论坛首页 https://github.com/getlantern/forum 下载
