### ISSUE TITLE
专业用户，新加坡的服务器速度还是比较慢

### ISSUE THREAD

**Issue by EdwardAutumn** [getlantern/forum#1370]
平均速度只能在200到300kb之间，希望更换此服务器。

**Comment by p3rcya** [comment]
正在寻找更好的服务器中心。你说的是kB，不是kb对吧？

**Comment by EdwardAutumn** [comment]
@p3rcya 是的。是字节，不是比特。

**Comment by p3rcya** [comment]
那还好，至少可以暂时忍受下吧？ 其他线路我们正在寻找

**Comment by p3rcya** [comment]
@EdwardAutumn 你现在试试？

**Comment by EdwardAutumn** [comment]
@p3rcya 我现在没连家里的网，回去试试，谢谢。

**Comment by EdwardAutumn** [comment]
@p3rcya 刚才又测试了一下，下载速度还是太慢，只能拿来看网页，看视频和在Google play上下载游戏都不行。
