### ISSUE TITLE
我把我的蓝灯重装了，但是发现登陆不上了，我需要蓝灯官方的解释，要么就退款给我。根本没有办法登陆，只有授权码，现在让我怎么办

### ISSUE THREAD

**Issue by masterzheng13** [getlantern/forum#1375]
我把我的蓝灯重装了，但是发现登陆不上了，我需要蓝灯官方的解释，要么就退款给我。根本没有办法登陆，只有授权码，现在让我怎么办

**Comment by masterzheng13** [comment]
我把我的蓝灯重装了，但是发现登陆不上了，我需要蓝灯官方的解释，要么就退款给我。根本没有办法登陆，只有授权码，现在让我怎么办

**Comment by potato9527** [comment]
尴尬   我之前只用电脑登过  然后下午刚重装  以为能邮箱登陆  GG

**Comment by potato9527** [comment]
下面的帖子好像说这个月会有email登录

**Comment by masterzheng13** [comment]
没办法啊，有没有注册，只是用支付宝付了款

**Comment by masterzheng13** [comment]
谁知道他们的电话啊

**Comment by qwe603696111** [comment]
可以在网上找一个安卓的旧版本的蓝灯   旧版本的可以用购买的时候填写的邮箱收验证码登录

**Comment by masterzheng13** [comment]
真的吗，我试试

**Comment by TalentSales** [comment]
在我的WINDOWS7上發生過類似的現象，後來發現是WINDOWS7系統的問題，升級（安裝微軟發布的系統升級，KB什麼什麼的）了一下系統就沒有問題。不升級真的是上不去的，我也不知道是哪個補丁在影響LANTERN。不妨試一下……。

**Comment by Alexanderlim810** [comment]
我是mac，今天更新了系统之后，就彻底不能用了

**Comment by cntomy** [comment]
同样的问题...为啥不开放email登陆？？？

**Comment by zsqp447** [comment]
据说这个月要出新版本增加邮箱登录

**Comment by p3rcya** [comment]
新版会增加邮箱登录，本月会发布。公测时间内购买专业版有两个月额外时间赠送(正式版推出后，后台会自动加入)，所以请稍安勿躁。

**Comment by p3rcya** [comment]
新版蓝灯3.2已经支持邮箱登陆和MacOS Sierra，请大家去论坛主页 https://github.com/getlantern/forum 下载。感谢给位的耐心等待！

**Comment by TalentSales** [comment]
看来MAC和WINDOWS还真不一样，我从来没有用过MAC。
