### ISSUE TITLE
蓝灯3.2.0发布，支持邮箱登陆，支持MacOS Sierra

### ISSUE THREAD

**Issue by p3rcya** [getlantern/forum#1382]
最新版本下载地址(更新版本会使用同样的下载地址)。 请大家收藏本页，方便以后更新。

[Windows 版本(要求XP SP3以上)] (https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-beta.exe)      [备用地址] (https://s3.amazonaws.com/lantern/lantern-installer-beta.exe)  

[安卓版(要求4.1以上)] (https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-beta.apk)               [备用地址] (https://s3.amazonaws.com/lantern/lantern-installer-beta.apk) **请勿使用UC浏览器下载，会被替换成假的有广告的版本**  [Google Play下载](https://play.google.com/store/apps/details?id=org.getlantern.lantern)

[macOS (10.7及以上)] (https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-beta.dmg)              [备用地址] (https://s3.amazonaws.com/lantern/lantern-installer-beta.dmg) 

[Ubuntu 14.04 32位](https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-beta-32-bit.deb)
[Ubuntu 14.04 64位](https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-beta-64-bit.deb)

**Comment by EdwardAutumn** [comment]
马上就发现一个bug，安卓手机上覆盖安装会要求重新授权，脸一黑

**Comment by p3rcya** [comment]
我们调查下。但是现在已经支持邮箱登陆，所以应该没有关系吧。

**Comment by EdwardAutumn** [comment]
是没关系。但是也是个BUG。

**Comment by p3rcya** [comment]
@EdwardAutumn 确实是bug。正在调查

**Comment by merlinfong** [comment]
我的用 google play 直接覆盖升级 没有你的那个问题@EdwardAutumn

**Comment by merlinfong** [comment]
@p3rcya 可以预告一下什么时候结束付费用户的内测呢？说过赠送的2个月一定要实现哦！

**Comment by merlinfong** [comment]
@p3rcya 蓝灯未来能支持自选线路吗？

**Comment by jyufeng** [comment]
MacOS Sierra，lantern 3.2.0，一直转圈无法连接服务器？急，3.1.4那里可以下载？
![default](https://cloud.githubusercontent.com/assets/8719855/18805263/d7e03626-823a-11e6-9f4e-86100b550724.jpeg)

**Comment by jpsdwang** [comment]
上个版本还能连上，3.2电脑版连谷歌都上不去了。没测试好就发出来了么？

**Comment by qcind** [comment]
windows 10 RS2 14931
lantern 3.2.0
也是出现该情况（无法连接蓝灯服务器），待跟进；谢谢！

**Comment by jyufeng** [comment]
@p3rcya 请把mac版3.1.4的安装文件链接再发出来应急。

**Comment by jyufeng** [comment]
@p3rcya 看来https://github.com/getlantern/forum/issues/1343的问题还是没有解决。版本授权控制不能为控制而控制导致付费用户的权益受损。

**Comment by qingyinji** [comment]
@p3rcya 新版本被卡巴斯基检测为病毒删除了

**Comment by jyufeng** [comment]
@p3rcya  一整天了，有没有解决Mac版3.2.0的方案呀？

**Comment by suixudongi8** [comment]
android客户端已经不能用，断断续续。换成3.1.4也是。

**Comment by unever** [comment]
windows版本暂无法使用，望尽快修复。

**Comment by phlaoi** [comment]
@p3rcya 还是不能更改为正确邮箱地址吗

**Comment by p3rcya** [comment]
@unever 现在应该还是8787么？

**Comment by xyuanmu** [comment]
@unever 现在新端口是 49586

**Comment by unever** [comment]
@xyuanmu 测试49586，无效。
同时也求教这位朋友，如何查看Lantern的新端口？如果以后又变了也好能及时自行更换。

@p3rcya 告知一下如何查看新端口号吧，谢谢。

**Comment by xyuanmu** [comment]
@unever 看来端口不是固定的，每台电脑都不一样，早上是看蓝灯的日志，刚才看了下原来可以修改的。

Windows 路径：
日志：%appdata%\Lantern\logs\Lantern.log
设置文件，addr后面就是：%appdata%\Lantern\settings.yaml

**Comment by unever** [comment]
@xyuanmu 测试有效，感谢。

**Comment by xieyingli** [comment]
1个月没在sierra上打开google了，终于打开了，希望稳定。。。

**Comment by yamsoil** [comment]
mac新系统，更新了新蓝灯以后第一天可以正常访问被墙网站，第二天就无法访问被墙网站，今天是第三天。

**Comment by cnvipstar** [comment]
最新版的macOS Sierra 10.12,使用蓝灯时chrome浏览器下方状态栏一直显示  “正在等待代理隧道的响应 ……”
升级之前是没有问题的。

**Comment by li5551** [comment]
用邮箱登陆，会受到一个账号恢复码，输入以后显示The limit of devices that can be linked has been reached，就不能用了，楼主看下怎么解决

**Comment by orbancanon** [comment]
@li5551 你有其它设备在用专业版吗？有的话请在“帐户管理”里把不用的设备删掉。没有的话，可以把详情发邮件给我orbancanon@gmail.com，我在后台帮你清理。

**Comment by li5551** [comment]
有其他设备在用专业版，那回来我把那个删掉，还有一个疑问是，现在3.2版本，我怎么进去谷歌都进不去了，怎么会这么慢，什么原因导致的？亲

发自我的 iPhone

**Comment by orbancanon** [comment]
@li5551 速度慢的原因太多。请按照https://github.com/getlantern/forum/issues/358的说明收集并发日志给我们。

**Comment by li5551** [comment]
好的👌🏻

发自我的 iPhone

**Comment by li5551** [comment]
IOS版本什么时候可以用上呢？

发自我的 iPhone

**Comment by youthzzf** [comment]
我是蓝灯专业版用户，一个星期前重装系统，再次安装蓝灯通过邮箱验证时显示The limit of devices that can be linked has been reached
我的账户是youthzzf@163.com，请您还帮我在后台清理一下。

**Comment by p3rcya** [comment]
@youthzzf 会人为清理，请等72小时

**Comment by youthzzf** [comment]
麻烦您了@p3rcya

**Comment by Allenchenchen** [comment]
上youtube,144p的视频都看不了，这很让我惆怅啊。。。。。

**Comment by Allenchenchen** [comment]
好慢啊，谷歌和Youtube一直缓冲，这让我很忧伤@p3rcya

**Comment by p3rcya** [comment]
@Allenchenchen 是专业版还是免费版？

**Comment by p3rcya** [comment]
@youthzzf 已经人为清理，请重新登录

**Comment by p3rcya** [comment]
@Allenchenchen  请上传运营商(比如上海电信100M)，并请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 并请提供邀请码。请及时提供，否则我们无法调查。

**Comment by Allenchenchen** [comment]
12天过去了，我又来了。。还是好慢，问题没有得到解决，求调查

**Comment by sunnyleeIcm** [comment]
仍然没有看到mac上有相关界面授权其他设备
Windows界面中也没有邮箱登录界面 @p3rcya

**Comment by p3rcya** [comment]
@suixudongi8 请下载最新版3.2。登陆界面可以用email

**Comment by Allenchenchen** [comment]
专业版，还比不上免费vpn的速度，这才忧伤（网络本身没问题，没装迅雷极速，360，谷歌浏览器都用，谷歌和youtube的打开时间相当慢。。。）@p3rcya 补充下：安卓使用还是挺快的，至少看视频不卡
广州电信20M, 邀请码 XQ82GN ,之前有上传了zip
