### ISSUE TITLE
3.2版本Http代理端口用8787连接不上

### ISSUE THREAD

**Issue by RedTea** [getlantern/forum#1384]
以前一直是8787，升级到3.2后就不能用了，查了一下pac发现端口变成56661了。这么重大的变更居然没有看到有提示。我可是付了钱的。

**Comment by thezzycom** [comment]
我就一句话，你真奇葩

**Comment by qcind** [comment]
windows 10 RS2 14931
lantern 3.2.0
也是出现该情况，待跟进；谢谢！

**Comment by junecwf** [comment]
哎，现在变得打开网页好慢啊，亲，升级怎么变越来越差了

**Comment by xyuanmu** [comment]
#1394 
端口 49586

**Comment by YOYOsheep** [comment]
127.0.0.1:14402

**Comment by xyuanmu** [comment]
奇怪，难道现在端口不是固定的？

**Comment by lililalahaha** [comment]
升了3.2，无法FQ。按楼上把SETTINGS.YAML里的端口改成8787就可以了

**Comment by orbancanon** [comment]
随机端口和其它一些手段合用，是为了解决一个重大的安全隐患，防止在网页中检测Lantern是否正在运行。一旦选好，会一直使用那个端口。

**Comment by hexiyou** [comment]
安装好以后在CMD里边输个命令查看一下端口就行。
`type %appdata%\Lantern\settings.yaml`
![tp](https://cloud.githubusercontent.com/assets/1593944/18852824/d4c2d930-8474-11e6-89b3-5b97e3fcf5f7.png)

**Comment by EdwardAutumn** [comment]
@orbancanon 这就尴尬了，socks5的代理端口我怎么找

**Comment by orbancanon** [comment]
@EdwardAutumn 还是在settings.yaml里，有一个socksAddr

**Comment by RichardKuroshio** [comment]
那么最新版还能通过代理设置只让Firefox使用lantern吗？

**Comment by orbancanon** [comment]
@RichardKuroshio 以前怎么设，现在还怎么设，只是端口没有固定在8787，要到settings.yaml里去查了

**Comment by lililalahaha** [comment]
我用的CHROME、switchyomega，把lanter翻墙模式里的8787端口改成settings.yaml的端口即可

**Comment by RichardKuroshio** [comment]
@orbancanon 我显示的端口是6091，但是在火狐的HTTP代理用这个端口连不上。使用PAC的话每次开机之后nocache和token后的字符串都不一样，都需要手工修改，何解？

**Comment by EdwardAutumn** [comment]
@orbancanon 找到了谢谢

**Comment by p3rcya** [comment]
蓝灯3.3.4版本在设置界面显示了端口，欢迎更新 https://github.com/getlantern/forum/issues/1737
