### ISSUE TITLE
没办法授权Android手机使用蓝灯

### ISSUE THREAD

**Issue by dyguests** [getlantern/forum#1396]
我试过重装蓝灯，windows,mac,android都试过，就是没办法授权给Android手机。

一般把动态验证码提交给电脑上的lantern没有反应。有时有反应也只是提示失败。

**Comment by p3rcya** [comment]
用最新的3.2邮箱登陆试试 https://github.com/getlantern/forum

**Comment by dyguests** [comment]
这是授权花了比较长的时间，不过 windows上显示授权成功了。说“请等待XXXXX”，不过andorid端还是没反应。
需要等很久吗？


另外我重新安装android版后，动态授权码就一直固定着没有变动了。一直是一个码。

**Comment by p3rcya** [comment]
用邮箱登陆试试

**Comment by qingyinji** [comment]
安卓用邮箱登录提示恢复码错误，试多少次都是这样。我就手机上安装了lantern，PC上卡巴斯基老是把它当成病毒杀了，所以没安装，不能给手机授权。希望可以早点解决安卓版登录的，不然掏了钱还在用着免费的T^T

**Comment by dyguests** [comment]
@p3rcya 我试了,还是不行的.PC端说"授权成功,请等待....",
但是android端就是没反应

**Comment by dyguests** [comment]
@p3rcya 现在综报 ,已达到3个设备上限...

话说我是在 公司PC,个人Mac,个人PC,个人手机上用.只能绑定3个设备吗?

**Comment by p3rcya** [comment]
对。最多三个设备

**Comment by dyguests** [comment]
好吧.只好把个人PC给解绑了.
