### ISSUE TITLE
还是不能 Google

### ISSUE THREAD

**Issue by orivil** [getlantern/forum#140]
我只是一个小小的程序员，每天都需要用 Google，我关心中国的未来，但我从来不发布反动信息，甚至对很多不客观的反动消息，也给予强力的批评。

现在因为封网的影响，我不能正常工作了，我该找点什么事来做呢？

**Comment by DPABeginner** [comment]
我是Unity、UE4游戏程序员，遇到技术问题必须是用Google搜索啊。Lantern 2.2.4目前可以上Google，不行的话github搜XX-net，这个也很强大，不过需要一些配置，对程序员来说应该没什么问题

**Comment by p3rcya** [comment]
@orivil 现在还是不能访问么？ 还是不行的话，请上传log。log进入Lantern应用安装目录下后点击logs文件夹。上传到Github需改后缀为txt，然后在发帖时将文件拖拽到到发帖的地方就可以上传了。

**Comment by orivil** [comment]
@p3rcya 试了很多次，传不上来，一直显示正在上传文件，你们好像正在恢复 p2p 版本？什么时候出来呀？
