### ISSUE TITLE
无法登陆专业版蓝灯

### ISSUE THREAD

**Issue by p8h9** [getlantern/forum#1409]
手机上的蓝灯重新安装发现没有登陆专业版的选项，如何解决。。。。。。。。。。。。。。。

**Comment by p3rcya** [comment]
下载最新的3.2版本 https://github.com/getlantern/forum 用邮箱登陆

**Comment by foxkathy** [comment]
安装了新版 选择找回专业版账号 但是输入恢复码之后还是提示 The limit of devices that can be linked has been reached 求解决~

**Comment by p3rcya** [comment]
@foxkathy 这个说明你已经达到3个设备登陆上限。你是不是重新安装多次，没有取消对以前设备的授权？如果是的话，请提供下email，我们人为帮你把原来的设备解绑。

**Comment by p8h9** [comment]
以前蓝灯第一个项目是登陆专业版，现在是购买专业版，所以不知道如何登陆，没有在其他设备上使用，又无法授权

**Comment by foxkathy** [comment]
账号email：foxevil317@gmail.com
有劳了！

2016-10-01 0:26 GMT+08:00 p8h9 <notifications@github.com>:

**Comment by p3rcya** [comment]
@foxkathy 请自己下载新版用邮箱登陆，谢谢。下载地址 https://github.com/getlantern/forum

**Comment by foxkathy** [comment]
重新安装了新版 获取了账号恢复码 仍然提示【The limit of devices that can be linked has been
reached】
是不是解绑还未生效……？

2016-10-02 16:55 GMT+08:00 p3rcya <notifications@github.com>:

**Comment by p3rcya** [comment]
@foxkathy 已经清理了，你再试试
