### ISSUE TITLE
关于账号授权问题

### ISSUE THREAD

**Issue by mourirveix** [getlantern/forum#1439]
由于电脑被盗在宿舍被盗，接连俩次手机刷机(完全没注意过)，导致授权用户超过三个！而且手机版不能解绑其他用户！从购买到现今，而且个人gs评价也只有一星！wtfts！

**Comment by mourirveix** [comment]
lantern太矫情了，我从开始的耐心到无奈也是忍无可忍了，现在只是希望得到解决。

**Comment by p3rcya** [comment]
请提供邀请码，我们后台人工给你解绑下

**Comment by mourirveix** [comment]
XQXN85

**Comment by mourirveix** [comment]
@p3rcya XQXN85

**Comment by p3rcya** [comment]
72小时内会解决

**Comment by p3rcya** [comment]
@mourirveix 请提供账号email

**Comment by p3rcya** [comment]
重复帖
