### ISSUE TITLE
专业版网速太慢了!

### ISSUE THREAD

**Issue by LJZ1993** [getlantern/forum#1443]
我是专业版,用google浏览器打开网页太慢了,足够我抽半支烟了!看视频更是卡!请工作人员赶紧解决啊

**Comment by p3rcya** [comment]
请上传运营商(比如上海电信100M)，并请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 并请提供邀请码。请及时提供，否则我们无法调查。

**Comment by LJZ1993** [comment]
- 信息

[Uploading 信息.txt…]()

[Uploading lantern.txt…]()


- 







- 

[Uploading lantern.txt…]()

**Comment by p3rcya** [comment]
没有上传完毕，请重新上传
