### ISSUE TITLE
电脑系统重装后，重新安装蓝灯，提示授权的设备数量已经满了

### ISSUE THREAD

**Issue by Immortalt** [getlantern/forum#1449]
我在两台电脑和一台手机上授权了专业版，一台电脑系统重装后，重新安装蓝灯，有英文提示授权的设备数量已经满了。那我怎么在这台电脑上重新登陆蓝灯专业版？！我现在实际能用蓝灯的设备只有两台了。。。

**Comment by p3rcya** [comment]
在登录的设备中，去账号管理界面解绑不需要的设备
