### ISSUE TITLE
吉林长春联通 电信 铁通貌似都不能用呢

### ISSUE THREAD

**Issue by yxd7909** [getlantern/forum#145]
如题。谢谢技术员！

**Comment by p3rcya** [comment]
请上传log。log进入Lantern应用安装目录下后点击logs文件夹。上传到Github需改后缀为txt，然后在发帖时将文件拖拽到到发帖的地方就可以上传了。

**Comment by yxd7909** [comment]
[Uploading lantern.txt…]()
[Uploading lantern.txt…]()
