### ISSUE TITLE
重装系统导致绑定设备上线，请求解绑

### ISSUE THREAD

**Issue by thezzycom** [getlantern/forum#1451]
因本人重装一次系统，在别的设备上绑定就显示了绑定设备上线，请求解绑。
授权码LBGHNX
邮箱zzyjjw17@163.com

谢谢，辛苦了

**Comment by p3rcya** [comment]
请问现在有已经登录的设备么？ 如果有的话，可以去账号管理界面解绑。如果没有的话，我会人工处理

**Comment by thezzycom** [comment]
@p3rcya 谢谢 已经找到了，以前没发信

**Comment by AsiaDeveloper** [comment]
我在windows上绑定了，然后解绑，将软件删除，然后切换到MAC上，提示找不到设备，，我现在的MAC授权码是073349。请帮我处理下，谢谢。

**Comment by p3rcya** [comment]
@AsiaDeveloper 用邮箱登陆就可以了

**Comment by AsiaDeveloper** [comment]
输入邮箱:返回Cannot recover user from provided information

**Comment by garveylee** [comment]
@p3rcya 现在登录设备上限已满 但是我试过所有的设备登录 依然是设备已满 请帮我清空 账号为：423668877@qq.com 谢谢

**Comment by garveylee** [comment]
@p3rcya 我在所有的设备都上尝试过登录 却依然显示设备已满 请帮我解决此问题 账号为：423668877@qq.com 谢谢

**Comment by p3rcya** [comment]
已经清除了所有已授权的设备，请重新安装最新版 https://github.com/getlantern/forum 后登录。

**Comment by jiangkun123** [comment]
我在win7设备安装的蓝灯，同事也帮了我的Android手机，但是我在我手机管理为什么看不到我的win7设备也无法解绑

**Comment by gyviva** [comment]
管理员，急救！！我的手机重置过两次，授权了两次，win7授权过一次，先在专业版无法授权了！gyviva@live.com,请帮我手动全部重置一下，验证码497151、102493！！！！！

**Comment by gyviva** [comment]
管理员，急救！！我的手机重置过两次，授权了两次，win7授权过一次，先在专业版无法授权了！gyviva@live.com,请帮我手动全部重置一下，验证码497151、102493！！！！！

**Comment by gyviva** [comment]
管理员，急救！！我的手机重置过两次，授权了两次，win7授权过一次(现在无故也无法登陆专业版了)，先在专业版无法授权了！gyviva@live.com,请帮我手动全部重置一下，验证码497151、102493！！！！！
