### ISSUE TITLE
proxy_on.pac 内容为空

### ISSUE THREAD

**Issue by kencloud** [getlantern/forum#1454]
在Windows 10安装`Lantern 3.2.0 (20160922.022149)` 启动后，这个pac为空:
`http://127.0.0.1:16823/proxy_on.pac`

请问有办法解决吗？

这个应该是proxy的自动配置文件，里面配置了的proxy端口。
`16823`不是proxy的端口，只是管理界面
没有这个文件，proxy是不工作的

**Comment by kencloud** [comment]
https://github.com/getlantern/lantern/blob/e0a57ed1299edc893c6caff2e7ad22453907732f/src/github.com/getlantern/flashlight/app/pac.go

This shows that default `pacUrl` is `proxy_on.pac`
somehow `genPACFile` return empty content.

need someone to look into this.

**Comment by joesis** [comment]
Hey @kencloud sorry for the delay. You set `http://127.0.0.1:16823/proxy_on.pac` manually right? In 3.2.0 a dynamically generated token is appended to the URL, to prevent malicious programs from detecting the existence of Lantern instance. 

Lantern sets the correct PAC URL when it starts up. In which circumstance you need to set it manually?

cc @p3rcya

**Comment by zjhzsz** [comment]
如何解决手工输入的地址后面的数字

**Comment by hyan23** [comment]
@joesis Hi, I'm on chrome linux, I have to set proxy_on.pac manually via switchyomega extension or I will not be able to access Internet, so please keep the static url in next version.

**Comment by joesis** [comment]
@hyan23 It's intentionally changed for security reason. Can you use proxy address instead? You can see it from the `addr` attribute of `~/.lantern/settings.yaml`.

**Comment by kencloud** [comment]
@joesis, I am using Windows, Chrome browser + SwitchyOmega. 
I want to set the PAC url in the SwitchyOmega. 

Where can I find the right URL for the PAC?
I could not find it in the lantern startup page.

**Comment by joesis** [comment]
@kencloud as aforementioned, it changes each time Lantern is started. Can you set proxy address in SwitchyOmega instead? It can be found from the `addr` attribute of `settings.yaml`.  The file should be under `c:/users/<your-user-name>/AppData/Roaming/lantern`

**Comment by kencloud** [comment]
@joesis thank you.
I figure out the proxy port by check the port listened by lantern process, same as the in the `settings.yaml`.

Maybe in future, the port and pac file url can be shown on the lastern startup page, in the setting.

Thank you for your patient help.

**Comment by joesis** [comment]
Yeah, it's on the plan and already has UI design ready. Thanks @kencloud
