### ISSUE TITLE
无法使用SwitchyOmega

### ISSUE THREAD

**Issue by a1991937511** [getlantern/forum#1457]
装了最新的3.2后 无法使用SwitchyOmega的切换 只能用lantern自带的系统代理 换了38813端口也不行

**Comment by a1991937511** [comment]
已经好了 端口错了 奇怪的是我从ie里看到的代理端口是38813 在配置文件看到的是38815 用38815就好了 这是什么原因啊？

**Comment by Alvin9999** [comment]
能用就好

**Comment by stelectronic** [comment]
@a1991937511 你是不是从老版本升级为新版本的, 重新安装一个蓝灯后端口号会变, 我重复安装几次发现的

**Comment by p3rcya** [comment]
蓝灯3.3.4版本在设置界面显示了端口，欢迎更新 https://github.com/getlantern/forum/issues/1737
