### ISSUE TITLE
免费版和专业版都无法连外网，可以登录成功

### ISSUE THREAD

**Issue by pandolia** [getlantern/forum#1462]
[lantern.txt](https://github.com/getlantern/forum/files/512740/lantern.txt)

**Comment by orbancanon** [comment]
@pandolia 虽然你发的日志只有一分多钟，但从里面看到不少来自Chrome的访问记录，也并没有出错。能否详细描述一下现象，并多尝试一会儿再收集日志？

**Comment by pandolia** [comment]
@orbancanon 感谢您的回复，下面是运行了1个小时的 log 。

[lantern.txt](https://github.com/getlantern/forum/files/513347/lantern.txt)

内网都可以上，但是外网 google 、 youtube 都上不去，chrome 的错误信息是：

```
无法访问此网站

www.google.com 的响应时间过长。
请试试以下办法：
检查网络连接
检查代理服务器和防火墙
运行 Windows 网络诊断
ERR_CONNECTION_TIMED_OUT
```

**Comment by orbancanon** [comment]
@pandolia `ERR_CONNECTION_TIMED_OUT`这个错误看起来像是没有把Lantern当作代理服务器。能否在Chrome地址栏打开 chrome://net-internals/#proxy，截个图？另外你有什么浏览器插件没？换个浏览器试试？日志看起来仍然很正常。

**Comment by pandolia** [comment]
谢谢！这个是 Chrome （没有浏览器插件）的截图：

![image](https://cloud.githubusercontent.com/assets/13767061/19154314/a097a20e-8c0c-11e6-9853-33f360fddb0c.png)

我用64位的 ie 也打不开，不过用32位的 ie 可以打开 google 了，其他网站也可以打开，但提示“浏览器已不支持”。

**Comment by pandolia** [comment]
下面这些是 netstat 命令列出的在本地监听的端口，没有看到 8787 端口：
  
  TCP    127.0.0.1:4300         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:4301         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:5037         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:5939         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:8911         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:9088         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:9990         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:15485        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:48303        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:62869        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:62872        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:62875        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:65000        0.0.0.0:0              LISTENING

**Comment by pandolia** [comment]
可能是和迅雷冲突引起的，我把迅雷卸载了，可以用 Chrome 连外网了。不知道具体是什么原因。
非常感谢啊！

**Comment by p3rcya** [comment]
和迅雷极速版有冲突，这个是已知问题

**Comment by pandolia** [comment]
哦，我的是迅雷普通版，而且前面一直都是都是可以上外网的，就这两天突然不能用了，不知道怎么回事。

**Comment by orbancanon** [comment]
@pandolia 呀，迅雷是个老问题，竟然没有想到。解决就好。
