### ISSUE TITLE
能添加登出按钮吗？ 之前蓝灯卸载了，然后重新安装之后显示的是别人的账号，重装一次换一次。

### ISSUE THREAD

**Issue by rinho1239104** [getlantern/forum#1481]
能添加登出按钮吗？ 之前蓝灯卸载了，然后重新安装之后显示的是别人的账号，重装一次换一次。

**Comment by p3rcya** [comment]
“重新安装之后显示的是别人的账号，重装一次换一次。” 这个能在账号管理界面截图给我们看看么？

**Comment by p3rcya** [comment]
@rinho1239104 我后台查看了下，这个情况不可能啊。你现在还有这个情况么？能截图给我看看么

**Comment by rinho1239104** [comment]
@p3rcya 抱歉，无法截图了。系统已经重装。我依稀记得帐号是y8一串数字@126.com

**Comment by p3rcya** [comment]
现在还有问题么？

**Comment by rinho1239104** [comment]
@p3rcya 这几天在不停重装系统,,并且导致
![image](https://cloud.githubusercontent.com/assets/22650662/19410649/fbbd3a36-9323-11e6-85bf-4dcc702881ad.png)希望能帮忙在后台清除掉 谢谢. 帐号是1239104@gmail.com

**Comment by p3rcya** [comment]
@rinho1239104 已经清除了所有已授权的设备，请重新安装最新版 https://github.com/getlantern/forum 后登录。
