### ISSUE TITLE
能不能把3.2.0以前的版本下载链接给放出来呢，3.2.0以前的版本很好用的

### ISSUE THREAD

**Issue by niewenfeng** [getlantern/forum#1487]
能不能把3.2.0以前的版本下载链接给放出来呢，3.2.0以前的版本很好用的

**Comment by junecwf** [comment]
[lantern_3.1.1.txt](https://github.com/getlantern/forum/files/518690/lantern_3.1.1.txt)

官方3.1.1版本，请将lantern_3.1.1.txt改为lantern_3.1.1.zip后解压

**Comment by p3rcya** [comment]
以前的版本可能有bug，请不要使用

**Comment by niewenfeng** [comment]
@p3rcya 可是3.2.0也不好用啊，整个十一假期都不能用直到现在为止

**Comment by p3rcya** [comment]
请问具体什么不好用？我们会修复

**Comment by niewenfeng** [comment]
@p3rcya lantern的页面能打开，但不能打开google和其它被屏蔽的页面，

**Comment by p3rcya** [comment]
用其他浏览器试试，火狐

**Comment by niewenfeng** [comment]
火狐、edge、chrome我都试过了，不行

**Comment by p3rcya** [comment]
可能是免费版服务器被墙了，请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 并请提供邀请码。请及时提供，否则我们无法调查。

**Comment by niewenfeng** [comment]
我的不是免费版，付了两年的费用的，邀请码是Y7H3YX
附件是日志
[lantern.zip](https://github.com/getlantern/forum/files/518821/lantern.zip)

**Comment by p3rcya** [comment]
我们后台会调查，72小时给你回复
