### ISSUE TITLE
专业版账号同时登陆3个设备的上限

### ISSUE THREAD

**Issue by 30stand** [getlantern/forum#1495]
手机之前授权了2台电脑使用专业版账户，连手机共3台设备。最近手机刷了系统，再用蓝灯的时候，通过邮件获取验证码，但提交之后提示专业版账号同时登陆3个设备的上限。问题已解决。原来在另外的设备可以进行解绑操作。

**Comment by Griffin1** [comment]
菜单栏的账号管理可以解绑设备
