### ISSUE TITLE
蓝灯无法支付

### ISSUE THREAD

**Issue by interpen** [getlantern/forum#1501]
RT。用的支付宝支付。 系统提示支付宝拒绝支付。
原文如下：
Alipay declined this payment. The most likely reasons are that the account does not have sufficient funds or Alipay deemed the payment to be potentially fraudulent.

**Comment by szj888** [comment]
是不是蓝灯已经被盯上了，封堵支付渠道。

**Comment by p3rcya** [comment]
应该是余额不足导致的。你先去支付宝充值下，在支付试试

**Comment by interpen** [comment]
按三楼的说法，进行了尝试。可以付款了。因为我设置了支付宝余额自动转到余额宝，所以中间还有点小插曲。
建议后来的同学们要是有遇到类似的问题，先关闭支付宝自动转余额宝功能，同时手动从银行先转账到支付宝。

**Comment by interpen** [comment]
谢谢！@p3rcya
