### ISSUE TITLE
无法翻墙，已上传log

### ISSUE THREAD

**Issue by EdwardAutumn** [getlantern/forum#1503]
[lantern.zip](https://github.com/getlantern/forum/files/521374/lantern.zip)

**Comment by p3rcya** [comment]
正在调查 @orbancanon

**Comment by orbancanon** [comment]
@EdwardAutumn 就是蓝灯服务器不通。刚刚测试了，服务器在内地可以访问。可能是你本地网络暂时的原因

**Comment by EdwardAutumn** [comment]
@p3rcya @orbancanon  问题已解决。
