### ISSUE TITLE
请问我这算是购买成功了吗？

### ISSUE THREAD

**Issue by arong-pm** [getlantern/forum#1504]
[lantern.log.zip](https://github.com/getlantern/forum/files/522367/lantern.log.zip)

<img width="679" alt="2016-10-12 12 18 53" src="https://cloud.githubusercontent.com/assets/17631681/19278846/8004b596-9011-11e6-9c94-48adf73f34f8.png">

**Comment by p3rcya** [comment]
对啊。18年到期

**Comment by arong-pm** [comment]
我更新系统了，我要取消绑定“Mac OS X 10.11.5”,重新登入，这个用户体验的设计太差了

**Comment by p3rcya** [comment]
你登陆后就可以取消绑定了。是更新了系统后被退出登陆了？
