### ISSUE TITLE
进国内网站被代理

### ISSUE THREAD

**Issue by EdwardAutumn** [getlantern/forum#1506]
![qq 20161012095803](https://cloud.githubusercontent.com/assets/19833520/19294804/6d96a4cc-9062-11e6-9a51-cc7d432df605.png)

如图所示

**Comment by p3rcya** [comment]
设置里不要选择代理全部流量

**Comment by EdwardAutumn** [comment]
@p3rcya 配置的地方我没动过，一直是默认没有勾选代理全部流量

**Comment by p3rcya** [comment]
这个奇怪。你其他国内网站会被代理么？ @orbancanon 你看看怎么回事

**Comment by EdwardAutumn** [comment]
@p3rcya 没有，就这一个网站，这以前也发生过，现在又没有了。暂时关闭这个issue。
