### ISSUE TITLE
分享一个蓝灯邀请码输入我的邀请码 992YGB ，额外获得三个月的蓝灯专业版！

### ISSUE THREAD

**Issue by looking1960** [getlantern/forum#1523]
分享一个蓝灯邀请码输入我的邀请码 992YGB ，额外获得三个月的蓝灯专业版！

**Comment by stephen666** [comment]
# 蓝灯lantern最新邀请码 Y2947HH 永久有效！获取三个月免费！

## 请输入我的蓝灯lantern邀请码 Y2947HH 来获得三个月免费的蓝灯专业版！使用后请留下你的邀请码，我也会使用你的邀请码续费的！

![lantern referall code](https://user-images.githubusercontent.com/11013738/28992843-0117abea-79da-11e7-913a-009de33ae2c1.png)
