### ISSUE TITLE
除了浏览器，mac终端和其他软件支持fq吗

### ISSUE THREAD

**Issue by NearEven** [getlantern/forum#1528]
浏览器代理不错，想问下终端和sourcetree等软件支持fq吗

**Comment by douniwan5788** [comment]
lantern本质是一个http代理，其他软件设置http代理即可，如终端export http_proxy=http://127.0.0.1:8787

**Comment by kenny67nju** [comment]
@douniwan5788  端口号怎么设置？我直接敲命令不对。

**Comment by NearEven** [comment]
@douniwan5788 多谢小哥,可以了, @kenny67nju , **http://jingyan.baidu.com/article/a378c960849144b3282830dc.html**,你参照这个就可以了

**Comment by spiritedRunning** [comment]
为啥设置了export还是不行呢。。。。急

**Comment by NearEven** [comment]
@spiritedRunning  用这种方法设置吧：http://www.jianshu.com/p/411a60f415a5
把lantern和cow的地址都换成lantern的代理地址（ 首先找到lantern的代理地址， 
``/Users/用户名/Library/Application Support/Lantern/settings.yaml``文件，其中``addr:``后为代理地址）

注意： cow：的地址不要用自带文本编辑器修改，``符号必须是' '``
