### ISSUE TITLE
电脑重装系统,忘记取消授权,希望请清除所有已授权的设备,1239104@gmail.com

### ISSUE THREAD

**Issue by rinho1239104** [getlantern/forum#1541]
电脑重装系统,忘记取消授权,希望请清除所有已授权的设备,1239104@gmail.com

**Comment by thezzycom** [comment]
最新版邮箱登录，自己可以解除已绑定设备

**Comment by rinho1239104** [comment]
@thezzycom 
![default](https://cloud.githubusercontent.com/assets/22650662/19410616/3ac691b0-9323-11e6-9d53-5ff23aa8521f.PNG)
能自己操作就不会来这提出来了

**Comment by p3rcya** [comment]
已经清除了所有已授权的设备，请重新安装最新版 https://github.com/getlantern/forum 后登录。
