### ISSUE TITLE
输入我的邀请码 XVJR7Y ，额外获得三个月的蓝灯专业版！

### ISSUE THREAD

**Issue by LouisMing** [getlantern/forum#1542]
最新的  欢迎输入

**Comment by LouisMing** [comment]
输入我的邀请码 XVJR7Y ，额外获得三个月的蓝灯专业版！

**Comment by thezzycom** [comment]
https://github.com/getlantern/forum/issues/313
这里有汇总贴，不要再乱开了，别给管理添加麻烦，等下被删帖也别怪别人，自己不仔细看
