### ISSUE TITLE
蓝灯正在解决电信用户部分时段访问慢的问题

### ISSUE THREAD

**Issue by p3rcya** [getlantern/forum#1545]
根据各位论坛用户的报告，我们发现中国电信用户在繁忙时段出现网络慢的情况。中国联通，中国移动在同时段没有这个现象，电信非繁忙时段也没有这个现象。
根据我们的调查，这个由于电信国际出口带宽拥堵造成的，联通移动的国际出口没有这个现象，电信非繁忙时段也没有这个现象。

我们将会使用对电信的蓝灯专业版用户优化服务器中心。当然这个优化会被电信物理的国际带宽所限制。我们会在物理带宽的限制内，保证电信用户在繁忙时段流畅播放高清视频。(根据用户报告，非繁忙时段电信用户已经可以流畅播放高清视频)。 

整个优化过程大概要一个月，优化的服务器会以购买蓝灯专业版的次序在直接后台发放。到时候会在论坛通知大家，谢谢！

**Comment by niewenfeng** [comment]
win10最新版不能用蓝灯的问题什么时候解决？

**Comment by YOYOsheep** [comment]
的确中国电信繁忙时段国际出口是有问题的，晚上一些没有屏蔽的境外网站打开也非常慢。

**Comment by gentlemanweso** [comment]
没错虽然是付费版但在学校和单位的电信网络下确实都不是特别理想，虽然油管看1080p基本可以但是实时网速一般也就400-500k/s，然而家里联通下轻松7m/s以上……

**Comment by j782070772** [comment]
我电信基本上就上不去

**Comment by nanmaolike** [comment]
大哥能帮我办理一下退款吗，我卡爆了，根本没法用

**Comment by ray1919** [comment]
有人关注就好，电信确实慢，速度时有时无。

**Comment by sxliang** [comment]
我的可不是分时段，几乎就死全时段的慢。坐标：杭州，电信

**Comment by YOYOsheep** [comment]
@sxliang  广州半夜（猜测）和早上7点起床是很快的（这个时候去GooglePlay更新应用最爽）。其他时段都慢

**Comment by p3rcya** [comment]
已经发放完毕，请专业版用户升级到3.3.1 https://github.com/getlantern/forum/issues/1675

**Comment by j782070772** [comment]
@p3rcya  手机客户端北京电信还是不行

**Comment by sxliang** [comment]
手机开户端杭州电信依然不行。没办法正常用。 在2016年10月31日 09:31 ，cgj写道： @p3rcya 手机客户端北京电信还是不行 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.
