### ISSUE TITLE
我的邀请码 Y48GU5U

### ISSUE THREAD

**Issue by szj888** [getlantern/forum#1550]
欢迎分享，Y48GU5U

**Comment by he22lei** [comment]
楼主你好，能给个专业版授权嘛？谢谢！

**Comment by szj888** [comment]
你好，由于蓝灯专业版授权只能三台设备，我这里已经满员，不好意思，欢迎你使用我的邀请码，谢谢！
----- 原始邮件 -----
发件人：he22lei <notifications@github.com>
收件人：getlantern/forum <forum@noreply.github.com>
抄送人：szj888 <songzejia@sina.com>,  Author <author@noreply.github.com>
主题：Re:_[getlantern/forum]_我的邀请码_Y48GU5U_(#1550)
日期：2016年10月16日 20点47分

楼主你好，能给个专业版授权嘛？谢谢！

&mdash;

**Comment by he22lei** [comment]
哦，满员就算了。谢谢！
