### ISSUE TITLE
3.2版本不能使用8787端口了？pac端口也变成随时变化不能指定使用了？ 

### ISSUE THREAD

**Issue by bdironbox** [getlantern/forum#1552]
这样的lantern对于专业人员根本没法用了啊，只是为了解决不冲突问题？还是胃口越来越大了，强制监听所有用户的所有流量了？

**Comment by szj888** [comment]
那端口是多少啊？

**Comment by szj888** [comment]
那端口是多少啊？

**Comment by szj888** [comment]
那端口是多少啊？

**Comment by szj888** [comment]
那端口是多少啊？

**Comment by szj888** [comment]
那端口是多少啊？

**Comment by szj888** [comment]
那端口是多少啊？

**Comment by szj888** [comment]
那端口是多少啊？

**Comment by szj888** [comment]
那端口是多少啊？

**Comment by p3rcya** [comment]
下个版本会在用户界面显示端口。随机端口是为了防止GFW

**Comment by bdironbox** [comment]
不能保留8787的同时增加随机端口吗？

**Comment by p3rcya** [comment]
保留了8787就不是随机端口了啊。端口下个版本会显示，这样用户就可以按照界面显示的设置了

**Comment by bdironbox** [comment]
但是我一大堆应用都是指定8787的，难道要我每次开机每个应用都要看一下端口号再重新设置一下？那我300块是打水漂了

**Comment by p3rcya** [comment]
端口每一个用户选择后就是固定的。

**Comment by bdironbox** [comment]
那期盼尽快更新版本，以前的安装包都没留着，别的地方下载的不放心

**Comment by p3rcya** [comment]
本月会更新

**Comment by p3rcya** [comment]
蓝灯3.3.4版本在设置界面显示了端口，欢迎更新 https://github.com/getlantern/forum/issues/1737
