### ISSUE TITLE
蓝灯专业版的端口是多少？

### ISSUE THREAD

**Issue by szj888** [getlantern/forum#1567]
不是8787吗？

**Comment by bdironbox** [comment]
强烈建议保留8787等固定端口，否则不能自己控制

**Comment by GD-HBX** [comment]
这个之前的issues有描述，你们翻翻看

**Comment by p3rcya** [comment]
蓝灯3.3.4版本在设置界面显示了端口，欢迎更新 https://github.com/getlantern/forum/issues/1737
