### ISSUE TITLE
IOS版本有确定什么时间发布吗？

### ISSUE THREAD

**Issue by ihaolin** [getlantern/forum#1568]
你好，
请问下，IOS版本什么时候发布呢，很想购买专业版，然而没有IOS版本，这个很头疼。

**Comment by p3rcya** [comment]
年底。你可以先在桌面版使用，到时候装iOS版本

**Comment by ihaolin** [comment]
我主要想用移动端，PC需求其实不那么高。

**Comment by ssy341** [comment]
@p3rcya ios移动版 需要越狱使用么？
