### ISSUE TITLE
User link not configured 

### ISSUE THREAD

**Issue by darksheng** [getlantern/forum#1578]
用qq邮箱登录，显示这个东西，有解决的办法吗，有工作人员在线吗

**Comment by darksheng** [comment]
User link not configured

**Comment by p3rcya** [comment]
请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 并请提供email。请及时提供，否则我们无法调查。

**Comment by p3rcya** [comment]
支付记录也提供下

**Comment by p3rcya** [comment]
不要重复发帖
