### ISSUE TITLE
开蓝灯与不开蓝灯下载速度一样都是几k

### ISSUE THREAD

**Issue by BTNC** [getlantern/forum#1589]
使用[conda](http://conda.pydata.org/docs/)下载软件在不开蓝灯下速度只有几k，在开蓝灯下速度仍然只有几k。蓝灯已经设置成代理全部流量，管理系统代理，确认蓝灯已成功翻墙，油管速度尚可。conda超时错误日志显示正从亚马逊云下载s3.amazonaws.com。请问这种开蓝灯却仍然下载慢是什么原因？

**Comment by p3rcya** [comment]
> 开蓝灯与不开蓝灯下载速度一样

说明是网站或者运营商问题，不是蓝灯问题

**Comment by BTNC** [comment]
谢谢解答，请问一些直连某ip的程序会受到蓝灯影响吗？
