### ISSUE TITLE
Lantern还是挺好的，真的

### ISSUE THREAD

**Issue by ArvinLiuV** [getlantern/forum#1590]
虽然安卓端连YouTube480P都卡得要死，但是它可以让你用50K的速度从GooglePlay下个免费不限流量的Turbo VPN, 然后用Turbo看720P啦。

呵呵，还说运营商限制海外访问的带宽。那么大概Turbo走的不是网线，是用的量子传输吧。

买了Lantern一年的付费，现在感觉真跟吃翔一样。

**Comment by p3rcya** [comment]
禁止广告
