### ISSUE TITLE
建议管理员写一个置顶公告

### ISSUE THREAD

**Issue by EdwardAutumn** [getlantern/forum#1628]
首先，说明蓝灯现在是测试版，可能会遇到网络不稳定的情况，省得不断有人来问。就我最近使用来看，比789月份的时候好多了，那时候手机端经常连不上，pc端网速也一般，现在PC端网速很快了，就手机端速度不稳定。再一个说明现在没有退款制度，暂时不支持退款，购买前请注意。其他的问题说明比如发帖问问题时请附带log可以都添加上去，完全没必要在这种冗余问题上浪费时间。

**Comment by gagazx** [comment]
测试版不稳定连不上你还跪舔？既然开始收费，发测试版来逗我们玩？而且还不给退款？收费的测试版不好用不该被喷吗？

**Comment by EdwardAutumn** [comment]
你用不了不代表别人用不了，懂？

**Comment by p3rcya** [comment]
@EdwardAutumn 谢谢！我也想这样，问题是Github没有办法置顶帖子。。。

**Comment by EdwardAutumn** [comment]
@p3rcya 那就放在Google+上，github毕竟是个技术交流社区。建个QQ群也可以。这有些人素质低智商也感人，看着也是烦。

**Comment by gagazx** [comment]
@EdwardAutumn 是是是，我用不了不代表别人用不了，交流那里的几百条退款帖子和不能用的帖子都是可以正常使用的人过来逗大家玩的。呵呵。

**Comment by thezzycom** [comment]
哈哈 能用的都不来这了

**Comment by thezzycom** [comment]
全球多少人就那几个人来
