### ISSUE TITLE
Lantern 3.2.5 (20161024.183159)的本地代理端口是多少

### ISSUE THREAD

**Issue by niget** [getlantern/forum#1643]
因为我不想代理全局,以前一直 Proxy SwitchyOmega 这个插件使用的,让蓝灯只代理指定网站,但是现在好像端口变了?以前是8787

**Comment by Hwatu** [comment]
最新版不是3.2.4嘛..你的手机版吗?

**Comment by niget** [comment]
@Hwatu window版啊,我刚刚下载的,他显示这个版本

**Comment by EdwardAutumn** [comment]
刚刚又下了一次，是升级了

**Comment by ssdfe** [comment]
我现在上外网很正常，但是国内的网很不正常（国内的有时显示正常，有时就是白页，有时 404 ，有时Not Found on Accelerator，不知道是怎么回事，软件怎么设置都不管用 啊

**Comment by p3rcya** [comment]
@ssdfe  截图和log上传下

**Comment by p3rcya** [comment]
蓝灯3.3.4版本在设置界面显示了端口，欢迎更新 https://github.com/getlantern/forum/issues/1737

**Comment by Sanisy** [comment]
我的3.35版本的专业版很慢啊，为什么？为什么我更新到3.35端口还是原来的，我真的是无语了。买了专业版比免费版还慢，是不是可以修改ssh代理的端口号的

**Comment by Sanisy** [comment]
我才用半个月，能不能把钱退了，我退订服务
