### ISSUE TITLE
河北唐山 联通 无法打开Lantern设置主页

### ISSUE THREAD

**Issue by diauweb** [getlantern/forum#166]
昨天把全局流量打开了，今天发现无法打开[Lantern主页](ui.lantern.io) 显示联通DNS的广告页，而且改DNS也没有用，现在好尴尬，Lantern基本上是没法打开的状态。。。 重装也不行 请问以前的设置页端口是什么来着。。 用ui.lantern.io好尴尬。。

**Comment by Honwhy** [comment]
POST http://ui.lantern.io:1233/user-create net::ERR_NAME_NOT_RESOLVED
