### ISSUE TITLE
Can I use Latern Pro in windows PC and Android phone at the same time?

### ISSUE THREAD

**Issue by LandyRo** [getlantern/forum#1660]
Can I use Lantern Pro in windows PC and Android phone at the same time? Does Lantern support multi devices? Because I use Lantern Pro in my Windows PC, but I also want to use on my Android phone and use the same account, is it possible?

**Comment by atavism** [comment]
@LandyRo Yes, you may link up to three devices. After you install the app on Android, if you click on the "Authorize Device for Pro" menu item, you can either enter the e-mail address you signed up for Pro with OR submit the device linking code (after you click on the "Link This Device" button) on your PC (under the "Add Device" menu item). Then your Android device will be automatically linked to your Pro account.

**Comment by atavism** [comment]
Please re-open if you have any additional questions/issues!

**Comment by LandyRo** [comment]
Thank you. But the problem is reverse. I bought Lantern Pro on Windows PC and can't link to my Android device, on PC Lantern Pro doesn't has "Add device"? How can I add?

[cid:d6e470fe-9ca1-4316-8a89-a4bf2da609a7]


Best,

Landy Lee

Mobile: 008613202368576
Email: lfl3050621214@gmail.com
Skype: lfl3050621214


________________________________
发件人: atavism <notifications@github.com>
发送时间: 2016年10月27日 23:24
收件人: getlantern/forum
抄送: LandyRo; Mention
主题: Re: [getlantern/forum] Can I use Latern Pro in windows PC and Android phone at the same time? (#1660)


@LandyRo<https://github.com/LandyRo> Yes, you may link up to three devices. After you install the app on Android, if you click on the "Authorize Device for Pro" menu item, you can either enter the e-mail address you signed up for Pro with OR submit the device linking code (after you click on the "Link This Device" button) on your PC (under the "Add Device" menu item). Then your Android device will be automatically linked to your Pro account.

―

**Comment by LandyRo** [comment]
Thank you.Thank you. But the problem is reverse. I bought and installed Lantern Pro on Windows PC and can't link to my Android device, on PC Lantern Pro there is NO "Add Device" NO "Link This Device" How can I add my Android device to Windows PC? 
![11](https://cloud.githubusercontent.com/assets/20776432/19774080/763d8396-9c9e-11e6-96ec-12d25ca87640.JPG)

**Comment by atavism** [comment]
@LandyRo It doesn't look like you're using the latest version on desktop. You can download it from [here](https://getlantern.org/lantern-installer-beta.exe). Once you upgrade you should see the "Add Device" menu item.

**Comment by LandyRo** [comment]
Thank you so much!!!! I succeed!!!! Yes, I thought before even you told me, but when I went to the Lantern website I saw the new version just share the same file name as previous version (show as the picture, different modified date but same file name), so I think there is no upgrade version and I didn't download. But when you told me the same thing and gave me the link, I just tried even the same file name as my old version, but it is new version, and it works!!!. Thank you so much, if you can give  different file name will be less confuse, for ex. beta 1, beta 2.... just an advice. :-)
![12](https://cloud.githubusercontent.com/assets/20776432/19774944/57598440-9ca1-11e6-9a5c-a1201b8becc2.JPG)
