### ISSUE TITLE
以前的本地应用使用连接为 127.0.0.1:8787 现在连接不上了。

### ISSUE THREAD

**Issue by aiai982** [getlantern/forum#1671]
用的是新版本3.2.5

**Comment by p3rcya** [comment]
新版端口每个用户都不一样，我们下个版本会显示使用的端口

**Comment by NAVrasZ** [comment]
现在有查看的方式吗，最近网络突然不行（话说什么原因），只要是连国外的都得走lantern才有速度，但有些貌似不支持全局代理只能手动填写

**Comment by p3rcya** [comment]
安装好以后在CMD里边输个命令查看一下端口就行。
type %appdata%\Lantern\settings.yaml

**Comment by aiai982** [comment]
~/.lantern$ cat settings.yaml 
addr: 127.0.0.1:40180
autoLaunch: true
autoReport: true
language: en-US
localHTTPToken: f03d902868axe15bdb4d996102164a1e
proxyAll: false
socksAddr: 127.0.0.1:45041
systemProxy: true
uiAddr: 127.0.0.1:42489

是socksAddr ?  @p3rcya

**Comment by p3rcya** [comment]
addr: 127.0.0.1:40180 这个

**Comment by p3rcya** [comment]
蓝灯3.3.4版本在设置界面显示了端口，欢迎更新 https://github.com/getlantern/forum/issues/1737
