### ISSUE TITLE
蓝灯端口的说明

### ISSUE THREAD

**Issue by p3rcya** [getlantern/forum#1674]
以前的本地应用使用连接为 127.0.0.1:8787 现在每个用户的端口都不同，防止GFW。
下个版本我们会在用户界面显示使用的端口。

如果现在各位急的使用请在CMD里边输个命令查看一下端口就行。
type %appdata%\Lantern\settings.yaml

**Comment by shendanpuff** [comment]
请问mac下怎么查看端口？

**Comment by EdwardAutumn** [comment]
@shendanpuff 你可以去找这个配置文件

**Comment by Jerry-goodboy** [comment]
@p3rcya @shendanpuff @EdwardAutumn @xiam @myleshorton 
Mac 下没有 settings.yaml，只在 lantern.app包内容里 有 lantern.yaml，但是里面的内容是空的，本地代理的端口怎么配置，应该写成什么样的格式？

**Comment by bdironbox** [comment]
Mac 下没有 settings.yaml，只在 lantern.app包内容里 有 lantern.yaml，但是里面的内容是空的，本地代理的端口怎么配置，应该写成什么样的格式？

**Comment by p3rcya** [comment]
蓝灯3.3.4版本在设置界面显示了端口，欢迎更新 https://github.com/getlantern/forum/issues/1737
