### ISSUE TITLE
关于新版两个问题

### ISSUE THREAD

**Issue by EdwardAutumn** [getlantern/forum#1678]
@p3rcya 
1.用最新的手机端的3.3.1版出现了连接一段时间后断线的情况，已经在手机端提交过日志
2.什么时候可以推出更换绑定账户的邮箱的功能

**Comment by SWDADWD** [comment]
你说的这两个问题，貌似一直存在。你可以等下下下下下下个版本解决！

**Comment by p3rcya** [comment]
1.正在调查
2.这个我们正在想怎么解决。因为一般需要更换邮箱是因为邮箱输入错误，所以没有办法认证后再更换。而直接更换又可能导致盗号。各位可以帮我们想想办法

**Comment by EdwardAutumn** [comment]
@p3rcya 其实我就单纯的是想换个邮箱，以前那个邮箱以后可能不用了。有没有考虑过短信验证？

**Comment by SWDADWD** [comment]
@p3rcya 简单，查后台交易记录。一个个筛查就出来了。

**Comment by EdwardAutumn** [comment]
@p3rcya 从昨天开始手机端网络基本没连上去过。

**Comment by p3rcya** [comment]
@EdwardAutumn 现在应该已经修复了，你重新打开试试

**Comment by p3rcya** [comment]
@EdwardAutumn 请问你安卓上登录了专业版么？

**Comment by EdwardAutumn** [comment]
@p3rcya 目前确实可以连上去了，但是速度依然不是很快。暂时关闭这个issue。

**Comment by SWDADWD** [comment]
@EdwardAutumn lantern用的代理服务器都很垃圾，所以很慢！
