### ISSUE TITLE
蓝灯时好时坏，不知道是不是网络波动的影响，免费版专业版都存在问题，附log文件

### ISSUE THREAD

**Issue by dustin48** [getlantern/forum#1687]
今天购买的付费lantern，之前用免费版也有问题，一直以为是免费的限制问题，结果购买专业版也是有同样问题。
附件为log文件。启动时就有log，打开网页页面提示错误时并没有生成新log
[lantern.txt](https://github.com/getlantern/forum/files/560302/lantern.txt)

**Comment by dustin48** [comment]
由于是跟别人合租，自己又从网口接了路由器，不知道是否有影响。本身网络状况也不太稳定。

**Comment by dustin48** [comment]
第二次尝试使用，log文件一直持续变大，error log相同。
不知道为何zip文件提示不支持，拓展名小写的原因？所以附件重命名txt文件，notepad中格式正常。
由于不能压缩文件，所以删除了部分log以免过大上传失败，仍然保留源文件，后续可提供。
[lantern.txt](https://github.com/getlantern/forum/files/560320/lantern.txt)

**Comment by SWDADWD** [comment]
你连接：45.32.21.116 ，lantern代理服务器出现多次超时现象！
证明代理服务器和您本地ISP链接网络环境并不好，不稳定！
你可以利用tcping 45.32.21.116，看看延迟以及丢包

**Comment by dustin48** [comment]
@SWDADWD 网络不稳定这个是知道的。但是墙内的网站只是顿卡一下，过大概十几秒就好了。但是蓝灯就一直没法使用，今天是有成功过，但是卡一次之后就再也连不上了。
铁通的网络，顿卡我没法解决来着OTZ

**Comment by SWDADWD** [comment]
@dustin48 你可以重启光猫换个IP，然后ping路由器网关。有时候可能暂时封锁，如果ping路由器和光猫网管地址也出现丢包和延迟高，那就证明本地局域网环境有问题。

**Comment by dustin48** [comment]
@SWDADWD 之前尝试过重启，的确能连。。。但是顿卡之后，就得重启。想要继续使用的话，就只能无限重启么

**Comment by SWDADWD** [comment]
@dustin48 我看是你本地网络不好吧？你有试过电脑直连光猫，不通过路由器吗？

**Comment by dustin48** [comment]
@SWDADWD 刚刚重启，目前能使用。我去掉路由器试试还会不会出现问题。不知道路由里哪个设置会影响这个。
多谢帮助！
