### ISSUE TITLE
今天上午网络不太稳定啊

### ISSUE THREAD

**Issue by EdwardAutumn** [getlantern/forum#1698]
网络断了几次，速度有时候也特别慢，麻烦看看是怎么回事。请将附件后缀名改为zip
![logs zip](https://cloud.githubusercontent.com/assets/19833520/19843358/a5731dcc-9f5c-11e6-8320-bbc09b2a4301.jpg)

**Comment by SWDADWD** [comment]
瞄了一眼，日志出现大量连接：“45.32.8.167”代理服务器出现大量"Timed out"，从30日12点开始，尤其是31日凌晨1~3点，简直就是每分钟超时好几下。
