### ISSUE TITLE
今天一直连不上去啊

### ISSUE THREAD

**Issue by EdwardAutumn** [getlantern/forum#1704]
@p3rcya 麻烦看看，把文件后缀改成zip

[logs.zip.txt](https://github.com/getlantern/forum/files/563364/logs.zip.txt)

**Comment by EdwardAutumn** [comment]
重新启动蓝灯后恢复了

**Comment by SWDADWD** [comment]
LZ请注意一下隐私，毕竟日志里面可以找到你浏览器 操作系统等信息，以及浏览网站（部分报错）
