### ISSUE TITLE
唉，付费后实在太难用了

### ISSUE THREAD

**Issue by Kellyfeb** [getlantern/forum#1710]
只有第一天下载了3.3.1版后运行快速，以后就时断时续，这两天尤其晚上半夜根本所有墙外网页都打不开，卸载后重装就打开1~2分钟而已，烦。日志怎么也传不上来，都改了.txt 了也不行

**Comment by p3rcya** [comment]
3.3.2已经修正了这个问题

**Comment by Kellyfeb** [comment]
下载安装了，还是不行

**Comment by Kellyfeb** [comment]
端口重装一次变一次

**Comment by lemonskkyt** [comment]
是不是卡的一般都电信啊，我用的450 3年的移动10MB宽带，除了刚开始收费的前3天专业版被当成免费版限速，后来95%以上的情况都可以流畅播放1080P，只不过偶尔抽风卡顿，但是去亲戚家连WiFi的话，50MB的电信宽带，手机经常很模糊的画面还卡顿（手机上看不到是什么分辨率，估计是不到360P的）
