### ISSUE TITLE
有些网站无法访问

### ISSUE THREAD

**Issue by EdwardAutumn** [getlantern/forum#1717]
@p3rcya 
http://forums.bethsoft.com/forum/184-the-creation-kit/
这个网站有时候会无法访问，就算能访问也会每次让我输验证码，能优化一下吗

**Comment by p3rcya** [comment]
哈哈，我也玩。 3.3.2应该修复了

**Comment by EdwardAutumn** [comment]
@p3rcya 并没有啊，一直让我输验证码，要不就是提示禁止访问。我平时不看这个网站的，但是在最近出的天际特别版还没出对应的creation kit，一直在等这个。
另外我刚才又遇到了几次网络中断，国内网站可以正常访问，国外的上不去
[lantern.zip.txt](https://github.com/getlantern/forum/files/565725/lantern.zip.txt)

**Comment by SWDADWD** [comment]
@EdwardAutumn 因为触发了人机验证机制。这种现象多出于，公共代理服务器，或者该IP访问流量过大！
这种问题需要解决，只能让lantern多分配一点代理服务器，或者增加附加IP服务。
@EdwardAutumn 至于lantern经常断，很明显的，你log里面出现大量超时，证明连接代理服务器非常不稳定。

**Comment by EdwardAutumn** [comment]
@SWDADWD 这位兄弟你很热心啊，我每个帖子里都有你

**Comment by SWDADWD** [comment]
@EdwardAutumn 那是当然，我只是把我知道的，告诉你们罢了~

**Comment by EdwardAutumn** [comment]
你不说，我还以为你是暗恋我呢

**Comment by p3rcya** [comment]
感谢报告，内部正在处理。请等待新版

**Comment by paperbag** [comment]
@EdwardAutumn 
这个是 Cloudflare 的 CAPTCHA，是由域名的控制者在 Cloudflare 上设置的。
很显然这个问题并不能解决。
percy 不是也用 Cloudflare 吗，想必不应该不知道吧。
