### ISSUE TITLE
说好的800M免费流量呢。

### ISSUE THREAD

**Issue by unvchan** [getlantern/forum#1728]
我今天头一次使用就告诉我本月流量为0 ，第一次下载，第一次使用，怎么就没了。况且今天才3号啊！

**Comment by binsee** [comment]
你可以查看一下是否能正常翻墙，以及端口占用情况。
我一直指定的使用8787端口，前两天出现本月流量为0时，查看监听端口，发现我指定的8787端口有其他程序占用，导致lantern工作异常，本月流量为0（或者压根不显示）。将占用的程序关闭，并重新启动lantern后发现流量显示正常了。

建议作者加入错误提醒机制，在不正常工作时，在页面上显示提示。

**Comment by p3rcya** [comment]
新版随机端应该不会有这个问题。请用最新的3.3.5
