### ISSUE TITLE
lantern的设备管理问题

### ISSUE THREAD

**Issue by crazystudy** [getlantern/forum#1746]
有个疑问:
一个专业账号最多只能绑定三台设备
还是说可以绑定多台设备,但最多只支持三台设备同时在线

**Comment by p3rcya** [comment]
最多绑定3台。但是你可以在管理界面解绑

**Comment by kaiyu2012** [comment]
都不能登录了，怎么进管理界面

**Comment by kaiyu2012** [comment]
设备已满
其他绑定的设备都已经删除程序。
这个情况，请问如何处理

**Comment by p3rcya** [comment]
不要重复发帖。请在 https://github.com/getlantern/forum/issues/1749 留email， 我人为处理

**Comment by lx98821** [comment]
帮忙清除 lx98821@163.com 这个帐号绑定的 huawei honor 6 这个设备，因为绑定满了，ＡＰＰ被删除了，所以麻烦你了，另外，如果把它绑定上到ＰＣ上。谢谢

**Comment by lx98821** [comment]
我无法管理已经授权的设备。在哪里可以管理
