### ISSUE TITLE
我怎么还是什么网站都上不去？

### ISSUE THREAD

**Issue by sunnytnt** [getlantern/forum#1755]
我安装了专业版lantern3.3.5。但使用火狐，chrome, IE浏览器都打不开google, youtube等任何一个需要翻墙的网站。均显示连接超时。以下是log和上不去网和浏览器设置的截图：
[lantern log.zip](https://github.com/getlantern/forum/files/573776/lantern.log.zip)
[截屏.xlsx](https://github.com/getlantern/forum/files/573779/default.xlsx)

**Comment by orbancanon** [comment]
@sunnytnt Lantern没有设置成系统代理。你打开Lantern界面里的“设置”菜单，高级里面的“设置系统代理”选项，开关一下再看浏览器设置里“使用自动配置代理”有没有变化。

**Comment by sunnytnt** [comment]
问题都已解决，谢谢。
