### ISSUE TITLE
发现一个关于授权设备的bug

### ISSUE THREAD

**Issue by G1enY0ung** [getlantern/forum#1762]
起因是这样的，我的lantern上面目前有三台设备， 然后我想解绑一台然后绑定我另外一台机器。

然后我在已经解绑的设备上继续运行lantern的时候，发现还是专业版，并没有退出

然后我又在重新绑定的设备上运行的时候，发现刚刚绑定的新的设备也是专业版

发生了无限绑定的情况，可以绑定无数台机器，不知道是不是bug？

只有删除了根目录下的.lantern dir，才可以真正的退出

我绑定的机器都是linux，三台Ubuntu16.04 desktop， 一台manjaro16.06.1 desktop

还望解决一下这个问题。

**Comment by p3rcya** [comment]
用下最新的3.3.5，应该没有这个问题

**Comment by G1enY0ung** [comment]
@p3rcya 试过了，升级到最新版本依旧可以登录， 只要不删除.lantern/目录，还是可以直接使用

**Comment by G1enY0ung** [comment]
早几个版本已经好了，感谢🙏，希望lantern越做越棒，关闭此issue
