### ISSUE TITLE
请及时在google play上发布最新版

### ISSUE THREAD

**Issue by lxp0gb** [getlantern/forum#1767]
3.3.5版已发布多日，但google play上还是3.3.4，请在google play上及时发布最新版。

**Comment by qcind** [comment]
请问在Google Play发布，是否需要时间审核的？

**Comment by lxp0gb** [comment]
是否发布到google play上遇上什么困难呢？

**Comment by lxp0gb** [comment]
3.4.1在googleplay发布，关贴
