### ISSUE TITLE
太难用

### ISSUE THREAD

**Issue by Kellyfeb** [getlantern/forum#1772]
这几天基本没有流畅的时候，不停卸载重装只能打开几分钟，也不知道什么原因我就是各种姿势都上传不了日志，是长城宽带的问题吗，只有3.3.5刚更新那两天好用

**Comment by p3rcya** [comment]
那你上传到google drive或者什么网盘上。没有日志没办法调查

**Comment by Kellyfeb** [comment]
@p3rcya https://drive.google.com/file/d/0Bz10ZhE6hCeAZUozTDBJeWJacUU/view?usp=sharing

**Comment by Kellyfeb** [comment]
@p3rcya https://drive.google.com/file/d/0Bz10ZhE6hCeAZmdhNUxEQktKb1k/view?usp=sharing

**Comment by Kellyfeb** [comment]
@p3rcya 请问查出原因了吗
