### ISSUE TITLE
支付页面出不来

### ISSUE THREAD

**Issue by gfreewind** [getlantern/forum#1791]
Win10系统，最新版本的Lantern3.3.5，无论是Edge还是chrome都弹不出支付页面，无法完成购买

**Comment by gfreewind** [comment]
更新一下。刚才试了，之前是3.2.5版本，Edge和chrome都没有支付页面。
升到3.3.5后，edge还是不行，alipay可以了。

**Comment by gfreewind** [comment]
最后使用alipay付款的时候，一切信息填写正确，最后显示付款过程中有一个错误。

**Comment by gfreewind** [comment]
错误信息为“There was an error in the payment process”

**Comment by orbancanon** [comment]
@gfreewind 这个错误偶尔会发生，是支付服务商内部发生了错误。重试一下能行吗？

**Comment by gfreewind** [comment]
今天支付成功了。

提个问题，收费版本的VPN通道都是依赖于哪些技术？怎样保证不被墙？

**Comment by p3rcya** [comment]
@gfreewind 请看看这贴 https://github.com/getlantern/forum/issues/378
