### ISSUE TITLE
蓝灯开启转完圈圈还是不能翻墙

### ISSUE THREAD

**Issue by Caroys** [getlantern/forum#1813]
蓝灯开启后，圈圈倒是转完了，右上角的流量条却没显示出来，显示蓝灯已连接，却仍然不能翻墙，安卓端也是相同的问题，都是在三天前出现的。
重装蓝灯也试过，但重装完后除了右上角出线流量条以外其他并无差别，还是不能翻墙，安卓端同样。
迅雷极速版已关闭。
![lantern](https://cloud.githubusercontent.com/assets/23382103/20180656/557856ba-a796-11e6-86ee-960888ebb6b2.png)
[lantern.txt](https://github.com/getlantern/forum/files/583612/lantern.txt)

**Comment by wueiro** [comment]
表示遇到了同样的问题。。。尝试了各种办法，均失败。

**Comment by texaskid** [comment]
+1

**Comment by Caroys** [comment]
更新到最新的3.3.9就可以用了！

**Comment by p3rcya** [comment]
蓝灯3.4.1发布，解决崩溃问题 https://github.com/getlantern/forum/issues/1892
