### ISSUE TITLE
重装软件后获取恢复码填写后提示已经绑定多个设备

### ISSUE THREAD

**Issue by xtootoo** [getlantern/forum#1845]
帮忙清除授权的三个设备 我的邮箱 psygoh@vip.qq.com

**Comment by p3rcya** [comment]
没有找到这个email，你是不是输错了

**Comment by xtootoo** [comment]
绝对没有错， 恢复码我都收到了

**Comment by p3rcya** [comment]
已经清除了所有已授权的设备，请重新安装最新版 https://github.com/getlantern/forum 后登录。
