### ISSUE TITLE
我想知道最近论坛集中反馈的安卓APP和联通大规模瘫痪，上传了那么多日志，大概要分析多久？

### ISSUE THREAD

**Issue by gaoliup** [getlantern/forum#1851]
尽快解决吧

**Comment by EdwardAutumn** [comment]
安卓速度慢貌似和网络有关系。反正我这联通的无线网速度基本就200多kb，七月份到现在没有任何改善。

**Comment by gagazx** [comment]
@EdwardAutumn 那你为何还要跪舔蓝灯呢？

**Comment by EdwardAutumn** [comment]
@gagazx 请问我跪舔谁管你屁事？

**Comment by Trikoles** [comment]
管理员基本不会公布Log分析的结果的

**Comment by p3rcya** [comment]
日志分析后，一般都会直接在后台解决。因为时间有限，不能逐一回复。回复的时间还不如用来处理更多的日志

**Comment by gaoliup** [comment]
@p3rcya  不是，安卓这都半个月不行了，。总得解决下吧

**Comment by gaoliup** [comment]
@Trikoles  我只是希望有人管一下安卓，这都半个月了

**Comment by p3rcya** [comment]
@gaoliup 我们正在解决。提交日志对我们解决问题是有帮助的

**Comment by p3rcya** [comment]
蓝灯3.4.1发布，解决崩溃问题 https://github.com/getlantern/forum/issues/1892
