### ISSUE TITLE
这几天老自动退出

### ISSUE THREAD

**Issue by cnfeigo** [getlantern/forum#1854]
运行一小会就自动退出了，不知道什么问题
[lantern.log.txt](https://github.com/getlantern/forum/files/587868/lantern.log.txt)

**Comment by orbancanon** [comment]
@cnfeigo 日志的时间只有49秒看不太出来之前发生过什么，但最后没有看到程序退出啊

**Comment by cnfeigo** [comment]
@orbancanon 那是我特意删掉以前的，只上传了一个，从启动到自动退出的日志。这个多一些，请
[lantern.log.txt](https://github.com/getlantern/forum/files/588637/lantern.log.txt)
看看

**Comment by cnfeigo** [comment]
@orbancanon 我可能找到原因了。astrill， 装了这个以后出现的问题（虽然没启动），刚刚卸载以后就正常了。应该是它在背后kill掉lantern

**Comment by orbancanon** [comment]
呃，居然有这样的事…… @cnfeigo 谢谢！我们会试试

**Comment by orbancanon** [comment]
@cnfeigo 请问你的Windows版本和Astrill版本是多少？我们想看看怎么能重现

**Comment by cnfeigo** [comment]
都是最新的， Astrill已经删掉，前几天下的最新版。win10 家庭版一直有更新
