### ISSUE TITLE
下载的lantern-installer-beta.exe 文件老是被杀毒软件删除

### ISSUE THREAD

**Issue by gbmeco** [getlantern/forum#1855]
我用的是Norton Security 
被迫每次都要手动关掉杀毒软件再下载更新再重新打开。

**Comment by zsqp447** [comment]
现在的杀软，除了根据特征码，主要还是通过监控软件的行为进行判断，所以凡是有修改系统行为的一般都报毒，有些有名的软件没误报可能是被加了白名单。

**Comment by EdwardAutumn** [comment]
我用的卡巴斯基没有问题。

**Comment by p3rcya** [comment]
是最新的3.3.7么？

**Comment by gbmeco** [comment]
是的。
![norton lantern](https://cloud.githubusercontent.com/assets/23441375/20288549/26c2f092-ab0f-11e6-9a8d-c4cca3e6d78b.JPG)

**Comment by Trikoles** [comment]
卡巴斯基、NOD32、小红伞、AVAST都报毒！！！！！最新版！！！

**Comment by p3rcya** [comment]
@Trikoles 最新版应该解决了这个问题，请下载3.3.9 https://github.com/getlantern/forum

**Comment by p3rcya** [comment]
蓝灯3.4.1发布，解决崩溃问题 https://github.com/getlantern/forum/issues/1892

**Comment by p3rcya** [comment]
最新的已经解决了
