### ISSUE TITLE
安卓专业版不停的闪退

### ISSUE THREAD

**Issue by LotusDeaken** [getlantern/forum#1856]
好不容易以授权了安卓的专业版，
结果刚用了一会，就开始不停的闪退。
心累啊。
已经上传报告，dudingkun945@qq.com

**Comment by EdwardAutumn** [comment]
一样

**Comment by p3rcya** [comment]
蓝灯3.4.1发布，解决崩溃问题 https://github.com/getlantern/forum/issues/1892
