### ISSUE TITLE
频繁崩溃，能退款不？

### ISSUE THREAD

**Issue by gfreewind** [getlantern/forum#1861]
几乎没有办法用。大概十几分钟就要崩溃一次吧。

最新的蓝灯版本，最新的Win10。

早知道先试用一下，再买专业版本了。

**Comment by EdwardAutumn** [comment]
你不使用的预览版吧

**Comment by gfreewind** [comment]
肯定不是预览版啊。

正版Win10，系统自带的。

**Comment by cnfeigo** [comment]
我也是win10， 现在用3.3.7正常，之前的版本会报病毒

**Comment by gfreewind** [comment]
报毒我也遇到过。

但现在根本没法用，一会儿就崩溃。


管理员，专业版刚买几天，能退不？

**Comment by p3rcya** [comment]
@gfreewind 
请报告网络环境，访问时段。
请提供email并使用应用内发送日志功能报告问题。请及时提供，否则无法调查，谢谢！

**Comment by gfreewind** [comment]
已经在另外一个issue中回复了。

专业版本至少在我的环境中体验非常不好，只要求退款。

**Comment by p3rcya** [comment]
蓝灯3.4.1发布，解决崩溃问题 https://github.com/getlantern/forum/issues/1892
