### ISSUE TITLE
管理员，专业版崩溃，能退款不

### ISSUE THREAD

**Issue by gfreewind** [getlantern/forum#1864]
As title，崩溃得太频繁了，根本没法用

**Comment by p3rcya** [comment]
请报告系统浏览器版本
请提供email并使用应用内发送日志功能报告问题。请及时提供，否则无法调查，谢谢！

**Comment by gfreewind** [comment]
跟浏览器无关。
用Edge（38.14393.0.0）和Chrome都崩溃。

买了还不到7天，还不能退款吗？现在连网上买东西都可以7天无理由退款。

**Comment by p3rcya** [comment]
@gfreewind 请提供email并使用应用内发送日志功能报告问题。请及时提供，否则无法调查，谢谢！

**Comment by gfreewind** [comment]
@p3rcya 今天又重新使用了一次，暂时没有崩溃，但上网速度非常慢。
注意，是专业版本，gmail会卡很长时间。用其他工具（也是收费的），没有问题。

现在我不需要调查，只希望退款。重现崩溃不是用户的义务。

**Comment by p3rcya** [comment]
蓝灯3.4.1发布，解决崩溃问题 https://github.com/getlantern/forum/issues/1892
