### ISSUE TITLE
安卓版被攻击了

### ISSUE THREAD

**Issue by mitanikanae** [getlantern/forum#1873]
安卓版，从GooglePlay上下的版本，是会员，今天早上发现手机连接Wifi的时候只要打开Lantern把开关打到On的状态很快就会报错退出，前几天还没有这个问题呢，估计是GFW开始攻击安卓版Lantern了，现在暂时用赛风顶着，烦请开发人员找出问题所在并解决之，或者是直接更新软件版本。

**Comment by p3rcya** [comment]
请报告网络环境，访问时段。
请提供email并使用应用内发送日志功能报告问题。请及时提供，否则无法调查，谢谢！

**Comment by cjqq354139968** [comment]
我的手机也闪退
，也是VIP版。

**Comment by gaoliup** [comment]
每天来论坛看看安卓情况，看来还是没解决

**Comment by jinskanna** [comment]
我也是，唉，好痛苦啊

**Comment by p3rcya** [comment]
请报告网络环境，访问时段。
请提供email并使用应用内发送日志功能报告问题。请及时提供，否则无法调查，谢谢！

**Comment by Quattroporte** [comment]
原来如此，我以为是我手机系统的问题😳还刷了机

**Comment by heaven502** [comment]
刚开始 发送日志失败，刚才发送成功了

**Comment by wangqianyuus** [comment]
怎么现在还无法解决呢!

**Comment by oakmikeoak** [comment]
同样情况，原来好好的，现在一按启动就直接崩溃 版本3.4.0

**Comment by p3rcya** [comment]
蓝灯3.4.1发布，解决崩溃问题 https://github.com/getlantern/forum/issues/1892
