### ISSUE TITLE
这VIP买得爽

### ISSUE THREAD

**Issue by Jannister** [getlantern/forum#1875]
免费版的时候从来没出过问题，大不了速度慢点偶尔连不上，毕竟免费版嘛，无所谓。

然后觉得用得挺好，想直接VIP省事了，
真是彻底好了。。前天晚上买了两年VIP，然后昨晚就一晚上连不上，提交日志以后貌似很快解决了。今天再连，应用直接崩溃。。重装也崩溃。。我。。。。

说真的这是继育碧之后我又一次感觉到自己是“正版软件”的受害者，不管是不是外部客观原因，我个人的使用感受真的非常差，一种上当受骗的感觉。

——————————————
Windows端没问题，出事的全是安卓版，但是手机不能上我用VPN干嘛。。。
今天的已提交日志，管理员不用提醒我。

**Comment by Jannister** [comment]
顺便，希望给安卓版添加退出账户功能，我专业版上不了用免费版还不行吗

**Comment by Quattroporte** [comment]
同样，我也是发现了这个问题，从免费版一直用到现在，也是前天买的两年的专业版，PC端没问题，Android端原来用免费版賊溜，现在上了Pro了反而总是闪退直接没法用了。。。希望管理员给个解释

**Comment by Jannister** [comment]
@Quattroporte 昨晚回光返照了一下，今天又不行了。。。

觉得自己的信任被辜负了那种感觉。。

**Comment by Quattroporte** [comment]
你可以去GitHub上下载一下最新版的3.4.1版本的，这个应该可以

2016年11月16日 下午1:21，"Jann I." <notifications@github.com>写道：

**Comment by Jannister** [comment]
@Quattroporte OK
看到各种帖子了，感谢提醒。

**Comment by Jannister** [comment]
对了，当然还要感谢下蓝灯团队的努力！

**Comment by p3rcya** [comment]
蓝灯3.4.1发布，解决崩溃问题 https://github.com/getlantern/forum/issues/1892

**Comment by p3rcya** [comment]
感谢各位的耐心等待
