### ISSUE TITLE
关于提交Log之后没有反馈结果的问题

### ISSUE THREAD

**Issue by Trikoles** [getlantern/forum#1876]
您在每一个帖子都让使用者提交Log，让你们调查。可是从未见你反馈过调查结果？？？我买了2年，目前在电信也是时而快时而慢。

**Comment by Trikoles** [comment]
我也不说什么，我是一个付费用户，希望您能够真视一些问题，不要老是Block一些问题。

**Comment by p3rcya** [comment]
结果： 蓝灯3.4.1发布，解决崩溃问题 https://github.com/getlantern/forum/issues/1892
