### ISSUE TITLE
付费老用户真心求问：为何不完善退款制度？

### ISSUE THREAD

**Issue by Trikoles** [getlantern/forum#1877]
RT，希望中文论坛管理员能够正视问题，我也不求退款。我是从P2P时代用到现在的，看到目前这个软件的现状，不忍，就注册账号上来，专程问几个问题。

**Comment by EdwardAutumn** [comment]
蓝灯目前是每个用户只知道部分服务器的ip，如果可以退费，那有恶意人员可以通过不断购买然后退费穷举出大量或者全部服务器的ip然后全部封锁。这种模式下注定是没有退费的。

**Comment by zsqp447** [comment]
不谈技术就说说退款本身吧，出了问题有两个选择，一个是解决问题，另一个是不解决直接退款，当然还有第三种一边退款一边解决问题，呵呵那当然不可能，不少用户觉得我不想管那么多还是直接退款比较好，但用的不爽就退款这种消费理念并不是全地球的普遍规则，蓝灯来到中国有些水土不服，你觉得用的不好就该退款天经地义，他们可能觉得这根本是消费者耍流氓

**Comment by EdwardAutumn** [comment]
很多干程序猿的，这点钱讲实话一天工资不到，他们是不会去纠结这个钱的，至少我就没有。反正我现在用的很好，PC速度很快，但是安卓版真的就稀烂的。

**Comment by SWDADWD** [comment]
@EdwardAutumn @zsqp447 国内外众多VPN品牌，或者其他代理。都可以提供免费试用，一个月购买，甚至全额退款，为什么lantern不行？而且lantern出现过好几次重大问题，一大堆反应忽快忽慢，甚至大面积无法使用，或者崩溃等等，他们也是付费用户！
为什么其他国外VPN可以针对中国大陆网络进行优化，而lantern不可以？我看主要没技术/没钱！

一个商业化公司，就应该要有个样子，既然转型了，就需要满足这个市场需求，要不然只能成为历史！

**Comment by p3rcya** [comment]
@SWDADWD 蓝灯现在不能免费使用么？

**Comment by p3rcya** [comment]
> 国内外众多VPN品牌，或者其他代理。都可以提供免费试用

而蓝灯永远会提供免费版，难道不如免费试用好？ 难不成你想要蓝灯只提供免费版限时是用？

**Comment by SWDADWD** [comment]
@p3rcya 没说不可以啊。一次性一年，用户是需要足够信任你们的才会这样，日后如果出现各种的问题，只会造成信任危机。
而且楼上所说的月付防止“滥用”，这点根本站不住脚，一年180元，这点钱对于政府是小事？GFW这项工程花费好几十亿，甚至几百亿都有可能，在乎180元？
lantern多花点钱买好点服务器吧，或者推出独立IP。赛风都可以随便更换线路，何况付费？
至于被封锁IP，国外知名的VPN一般都买了AS段，好几十万个IP，属于自己的IP，服务器都是自己的，全世界几百个节点，针对大陆网络特别优化线路。。。不过价格也是10刀一个月起步。

**Comment by SWDADWD** [comment]
@p3rcya 这点，基本上大部分商业化VPN都提供免费的。一个月给2GB。

**Comment by SWDADWD** [comment]
@p3rcya lantern这个团队，如果不能适应市场需求，那么真的没人去买的。

**Comment by p3rcya** [comment]
@SWDADWD  这个精华帖里面已经说了。请看，

> 近期GFW工作人员搞很多个IP来检测蓝灯的IP，进行封锁。专业版需要付费，GFW就没办法一下子注册很多帐号，来批量封锁IP。所以付费能有效抵御GFW的封锁。这也是我们只提供年付的原因。如果提供月付，GFW可以购买月付帐号收集IP。现在GFW只能购买年付版，有效限制GFW的渗透率。

**Comment by p3rcya** [comment]
@SWDADWD 如果GFW愿意付费购买，我们可以使用GFW的钱，购买更多的服务器

**Comment by SWDADWD** [comment]
@p3rcya 这个理论根本站不住脚的。你们能拿出1亿嘛？？？

**Comment by p3rcya** [comment]
每个账号能访问的IP都是有限的，GFW要一直购买新的专业版账号，才能收集所有的IP。而购买账号的钱，我们可以购买更多的IP

**Comment by p3rcya** [comment]
@SWDADWD 如果他们能花1亿购买专业版账号，收集IP，那我们就能查得出一亿，购买新的IP

**Comment by SWDADWD** [comment]
@p3rcya 你们使用的数据中心 以及技术我都看过，很好破的。

**Comment by p3rcya** [comment]
除非封杀所有数据中心的IP。那还不如直接断网算了

**Comment by SWDADWD** [comment]
@p3rcya 这个不需要太过于辩论。。。谈结果就行了，你看用户反应的问题来吧。

**Comment by p3rcya** [comment]
目前3.4.1可以稳定运行。如果用户有问题，我们都会解决的。

**Comment by SWDADWD** [comment]
@p3rcya 首先一点就是速度 以及 稳定性问题，如果你们的技术能够做到不被干扰以及屏蔽，那么为什么有人抱怨我使用其他VPN是正常的，速度快的？ 第二点，手机上出现莫名其妙的闪退，以及掉线，这个问题一直存在，现在也没用解决。这点@EdwardAutumn 也遇到的。第三点 IOS设备没有得到支持，之前github 说过会在秋季发布，现在都冬季了。第四点，线路切换，没有实现。

**Comment by SWDADWD** [comment]
简单来说，从推出3.X到现在，貌似一直在解决产品本身的BUG，一些功能，甚至很有必要的东西。根本不像是一个商业化产品该有的。

**Comment by p3rcya** [comment]
闪退，以及掉线目前3.4.1已经解决了，请下载测试后在评论 https://github.com/getlantern/forum/issues/1892

iOS版本软件开发是需要时间的。 线路切换专业版以后会加入

**Comment by SWDADWD** [comment]
@p3rcya 闪退这个问题，play上面依旧会有人这样，而且日期是11月16日，但是他们之前版本不存在这种现象，只能说新版本存在BUG，后续解决了。很久之前@EdwardAutumn 是用着用着退出，这种是打开闪退，而且之前是很小范围出现。
或许下一次又会出什么问题。这种几率，恐怕要么一堆人是这样，要么小范围，你们只能反复测试。

**Comment by SWDADWD** [comment]
@p3rcya 无非我就是想说：既然是商业化公司，就做好产品，要不然只会成历史。谈情怀，漫长等待，只会失去信任。  产品线都没完善，而且前提BUG一大堆，已经失去一部分老用户信赖，后期新用户只可能更加不信任。  恐怕你们本身产品都没有别人商业化产品做的优秀，无意是毫无竞争力。

**Comment by SWDADWD** [comment]
@p3rcya 不过你们肯花大量人力技术 资源投入，最后或许也换不来客户。因为。。。你们前期做过市场调查，大部分人根本承受不住这个价格的。而且切入点本来就不适合，毕竟是为免费而来~想让他们付费，有点难，再加上前期这么多问题，无疑就是雪上加霜。

**Comment by p3rcya** [comment]
我们本来就不是商业公司，蓝灯专业版付费可以防止GFW收集所有IP，前面已经说了，而且可以保证免费版可以长期使用。本来就不是盈利的。

**Comment by SWDADWD** [comment]
@p3rcya 你们已经是属于商业化公司了。
第一：3.X版本并没有开源
第二：推出PRO版本，介绍功能 速度 等等比免费版有什么差异
第三：免费版本限制

你们lantern背后团队之前也是做P2P软件的，后来也推出付费模式的。如果不盈利，PRO版本应该和赛风一样没任何区别，赛风PRO就是一个捐赠途径，免费版和高级版赛风没有区别。

**Comment by SWDADWD** [comment]
谈结果就行了，你们希望通过这种模式来维持发展，那么就给客户想要的，要不然最后。。。成为历史。

**Comment by SWDADWD** [comment]
@p3rcya 说准确一点，现在这种运作模式完全属于商业化性质。至于lantern这个项目上面的组织，现在还是不是非商业性的，我不清楚，
也就是现在常见的产品本来开源 ，或者由开源社区共同维护，受到一些人捐赠。不过服务是收费的。

这就是好像是redhat。不过你们现在本身产品不开源，只能说，模式非常彻底。

**Comment by gfreewind** [comment]
同感。

虽然真的不差这点钱，但是作为收费软件，不支持退费，这是规则上的不合理。

我用了不到一周，PC版本一直不断崩溃，这样的软件，也好意思收费？

**Comment by p3rcya** [comment]
是Astrill的问题，已经解决了

**Comment by SWDADWD** [comment]
@EdwardAutumn 程序BUG一大堆，我猜项目经理会天天找你麻烦！当然最后是服务消费者，产品做的烂，没有买的。
