### ISSUE TITLE
新版安装手机后，点击开启，确认链接VPN，上方消息栏显示后，几秒就直接闪退

### ISSUE THREAD

**Issue by BubbleSwan** [getlantern/forum#1882]
你好Lantern专家们，

新版本安装手机后，点击开启，确认链接VPN，之后手机消息栏上方出现钥匙显示连接，几秒后立刻闪退。
每次点击开启就会出现这种情况，手机查看没有限制什么就是找不到问题。
手机：小米Note Pro；MIUI8 开发版

谢谢
BubbleSwan

**Comment by p3rcya** [comment]
蓝灯3.4.1发布，解决崩溃问题 https://github.com/getlantern/forum/issues/1892
