### ISSUE TITLE
安卓专业版3.4.0闪退

### ISSUE THREAD

**Issue by WithdrawnObserver** [getlantern/forum#1886]
日志已提交
点击开按钮后直接闪退。
测试发现仅安卓版存在此问题，PC版正常。
网络环境：中国移动
上网时间：今日整个上午直到现在
机型：MI 5,MIUI 8稳定版

**Comment by NAVrasZ** [comment]
3.4.4同

**Comment by p3rcya** [comment]
蓝灯3.4.1发布，解决崩溃问题 https://github.com/getlantern/forum/issues/1892
