### ISSUE TITLE
安卓3.4.0专业版闪退 sony xa ultra android6.0 

### ISSUE THREAD

**Issue by oakmikeoak** [getlantern/forum#1887]
和大家一样，之前都没问题，今天一点启动就崩溃 重启改设置均无效。

**Comment by BubbleSwan** [comment]
同样状况，安卓下，PRO点击开启后，上方出现了钥匙，一会就退了。重开，重复多次也是一样。偶尔的机会，出现正常结果，网络却上不去，根本没连接上。
手机：小米Note Pro MIUI8 开发版

**Comment by p3rcya** [comment]
蓝灯3.4.1发布，解决崩溃问题 https://github.com/getlantern/forum/issues/1892
