### ISSUE TITLE
最新3.4.1依然崩溃

### ISSUE THREAD

**Issue by gfreewind** [getlantern/forum#1894]
买了专业版本一周左右，几乎没用过，因为崩溃的太频繁了。
官方又不肯退款，看到出了最新的3.4.1，刚才试用了不到5分钟，又崩溃了。。。

@p3rcya 管理员，如何导出日志啊？
你们不肯退款，我就把日志交给你们分析，看看你们到底能不能解决？

**Comment by p3rcya** [comment]
@gfreewind 请问是什么系统？请提供email并使用应用内发送日志功能报告问题，也可以手动上传，方法见https://github.com/getlantern/forum/issues/1840#issuecomment-260143243。请及时提供，否则无法调查，谢谢！

**Comment by gfreewind** [comment]
@p3rcya Win10系统，重现的非常快。
下面是日志，看看你们什么时候可以解决

[lantern.zip](https://github.com/getlantern/forum/files/596320/lantern.zip)

**Comment by orbancanon** [comment]
@gfreewind 日志里没看到崩溃的记录，我们在Windows 10上也没能重现。有没有可能是其它软件把它杀掉了？有位朋友在https://github.com/getlantern/forum/issues/1854#issuecomment-260286100 提到Astrill会干这事儿。

**Comment by gfreewind** [comment]
@orbancanon 还有这等事情。。。。。 那这个Astrill也太龌龊了。。。

之前测试的时候，我都是把astrill关掉的。这次连后台进程也杀掉，我再试试。

**Comment by orbancanon** [comment]
@gfreewind 卸载Astrill能解决吗？请问你的Windows版本和Astrill版本是多少？我们想看看怎么能重现

**Comment by gfreewind** [comment]
astrill的进程全杀掉了，还是crash。
[lantern.zip](https://github.com/getlantern/forum/files/596481/lantern.zip)

**Comment by orbancanon** [comment]
ASOVPNHelper这个服务在不在？或者按https://github.com/getlantern/forum/issues/1854#issuecomment-260286100 所说，卸载整个软件呢？

这个比较难定位，因为我们装了Astrill也没能重现。程序被其它进程杀掉的话，日志里体现不出来（你新发的日志确实也没有异常）。

**Comment by gfreewind** [comment]
凡是Astrill的服务全杀了。

如果你们装了astrill不能复现，我认为不是astrill的问题。

能不能改进一下程序啊？把谁杀的它的进程id打印出来啊。我不是搞Windows的。至少Linux有手段知道什么信号杀的，谁杀的。

2016-11-17 13:03 GMT+08:00 Orban Canon <notifications@github.com>:

**Comment by p3rcya** [comment]
卸载了Astrill试试？
