### ISSUE TITLE
访问谷歌启用了ipv6,经常需要输入验证码，验证是人为操作，有碰到这个问题的吗？

### ISSUE THREAD

**Issue by chayangge** [getlantern/forum#191]

**Comment by zhangzhibin** [comment]
经常遇到

**Comment by atomsyoung** [comment]
同遇到这个问题，以前没有的的，近几个版本总是这样
ps：校园网

**Comment by AaronWharton** [comment]
我前几天遇到这样的情况，现在直接不能用了，我也是校园网。

**Comment by lucifinilsu** [comment]
你们现在还能翻？

**Comment by bj-wei** [comment]
每次查google都有，很烦的，可以解决掉么？

**Comment by iliangxiao** [comment]
我也是最近两周这样的，挺麻烦的

**Comment by Sherlock3003** [comment]
同，google和youtube经常输入验证码。同校园网。不过现在lantern每次打开都闪退，翻不了了，但每次开机后，卸载lantern再重新安装可以翻，关机之后再开就再次闪退了。

**Comment by ptzhuf** [comment]
这一周才开始的, 一直要验证码.. 真的是IPV6的原因吗...

**Comment by junjunn** [comment]
不是ipv6的原因吧

**Comment by april4513** [comment]
Latern可以用ipv6？
怎么弄啊？？？

**Comment by bj-wei** [comment]
诶？ 今天没验证码了？？
