### ISSUE TITLE
刚刚从GitHub下载的3.4.2版本的最新版发现有广告

### ISSUE THREAD

**Issue by Quattroporte** [getlantern/forum#1937]
刚安装完之后自动升级成为Pro版本了，最上面出现了广告。。。Pro版本竟然带广告

**Comment by p3rcya** [comment]
你确认是官方版本么？给个截图？

**Comment by Quattroporte** [comment]
实在不好意思，重启了一下之后就没了，这个话题可以删么，谢谢！

**Comment by Quattroporte** [comment]
又出来了，截图了怎么上传

**Comment by Quattroporte** [comment]
2016年11月22日 下午12:15，"p3rcya" <notifications@github.com>写道：

**Comment by AllenBrook** [comment]
我也发现有广告
