### ISSUE TITLE
我提了个信用卡的安全问题，你给我删了？？？

### ISSUE THREAD

**Issue by liuyuhang** [getlantern/forum#1939]
用户安全问题影响到你的收入了，你就把我的问题删了？？？
WTF

**Comment by liuyuhang** [comment]
输入的信息怎么保障安全，我是写代码的，随随便便记录用户信用卡数据啊，以后随便用啊

**Comment by p3rcya** [comment]
你自己发在这里，哪里删了？https://github.com/getlantern/lantern/issues/5463
信用卡这种问题早就解释过了。你是程序员，就应该能读明白
https://github.com/getlantern/forum/issues/335#issuecomment-231140551
