### ISSUE TITLE
新装的win10系统开启蓝灯，翻墙无效

### ISSUE THREAD

**Issue by nan1227** [getlantern/forum#1942]
换了个新固态硬盘，装了蓝灯，蓝灯页面也能自动打开，但是上facebook，youtube无效。

[lantern.log.zip](https://github.com/getlantern/forum/files/606356/lantern.log.zip)

**Comment by yym0924** [comment]
你可以手动把代理设置成蓝灯设置里那两个

**Comment by nan1227** [comment]
代理设置装上蓝灯就设置好了

**Comment by nan1227** [comment]
我看局域网设置里面有使用自动配置脚本的

**Comment by nan1227** [comment]
自己弄好了
