### ISSUE TITLE
怎么联系管理员，为什么不成立专门的群来解决这个问题呢

### ISSUE THREAD

**Issue by kkf07111125** [getlantern/forum#1968]
怎么联系管理员，为什么不成立专门的群来解决这个问题呢

**Comment by kkf07111125** [comment]
在FaceBook上面为什么不回复呢？

**Comment by kkf07111125** [comment]
@p3rcya

**Comment by p3rcya** [comment]
就是这个论坛来解决问题。

**Comment by kkf07111125** [comment]
嗯，那我填写了专门的邀请码，也购买了两年的套餐，为什么没有到账呢@ p3rcya小编叫我联系你，帮我解决下，谢谢了

**Comment by kkf07111125** [comment]
temnia 这个管理员聊过的

**Comment by temnia** [comment]
我不是管理员，我只是用户

**Comment by kkf07111125** [comment]
嗯嗯，不好意思，谢谢你的回复

**Comment by p3rcya** [comment]
我去原贴回复，这个关了 https://github.com/getlantern/forum/issues/1908
