### ISSUE TITLE
发现Lantern与Uplay冲突

### ISSUE THREAD

**Issue by jkeyvv** [getlantern/forum#1980]
之前的版本，开着蓝灯的话无法登陆Uplay，关闭就可以登陆。
现在关闭蓝灯也无法登陆了，试了几次，发现禁用蓝灯开机启动，就可以登录Uplay，但是如果开机期间开过蓝灯，就再次无法登陆了。

**Comment by saszr** [comment]
是的，uplay登不上去设置里面变更浏览器代理设置
