### ISSUE TITLE
劝大家别买专业版，我的180块钱就当送人了，买个教训。

### ISSUE THREAD

**Issue by jihaixiao8** [getlantern/forum#1994]
蓝灯专业版会一直在跑流量，上传东西，而且量很大，会影响别人上网，问开发团队没人理。。。

所谓的上传日志开发团队帮忙解决，根本没有的事，我提交了很多次日志，半个月来从没给我回复，非常安静。

北京联通开了蓝灯，github的代码 pull不了，电脑只能重启，退出蓝灯也连不上。。。

实在受不了了，卸载了，就当没买过吧。。。。太折腾

**Comment by ivanbirth851230** [comment]
这位兄弟 何以这么决绝的说话呢 你这样意气用事也不起作用啊 遇到问题 我们冷静解决就好了呗。。。有问题大家一起分担 对于你说的蓝灯专业版一直跑流量的问题 确实是有的 但是我觉得在可控范围之内啊 我买的是两年版 觉得还可以啊

**Comment by Quattroporte** [comment]
同问，我也发现会有流量上传，但是就翻墙效果来说，还是很棒的，两年的Pro

**Comment by jihaixiao8** [comment]
@ivanbirth851230 我也很无奈啊。。。毕竟买了个单机版，没人管啊。。。。  我看这个issue里面有很多人都问开发团队，为何不停的在上传流量，但是开发团队1个字都没提过，有什么猫腻？？

**Comment by p3rcya** [comment]
电脑智能重启，上传流量都应该是你电脑的问题。估计是其他软件偷偷上传，被蓝灯代理了而已。

**Comment by tigeeo** [comment]
额，本来想买的，这下子好了，等等看吧

**Comment by Wang-chao** [comment]
我这边还挺好用的

**Comment by p3rcya** [comment]
应该是你电脑上的应用跑流量，被蓝灯代理了而已。请自查

**Comment by zhange98** [comment]
没用过专业版不清楚，现在没有支付宝支付了，不会用银行卡购买，不懂不会。

**Comment by kelix** [comment]
我320就当丢掉了。。。
