### ISSUE TITLE
每次使用蓝灯一段时间以后，百度就会提示我极有可能被劫持

### ISSUE THREAD

**Issue by sddshao** [getlantern/forum#2008]
每次使用蓝灯一段时间以后，百度就会提示我极有可能被劫持，卸载蓝等以后，再次搜索就没有提示了，屡试不爽。是不是蓝灯自己的问题？卸载了蓝灯以后杀毒显示没有搜到病毒。难道以后要在隔离沙箱里面运行？

**Comment by sddshao** [comment]
最主要的是，现在每个礼拜都会接到骚扰、推销的电话，黑名单已经加了好几页。。运营商维护人员过来看，说是电脑中毒了。但是使用的软件很少，最近也只安装使用过蓝灯，卸载以后，360急救箱、windos defender全盘扫描都没有发现问题。

**Comment by EdwardAutumn** [comment]
电脑上装的卡巴斯基，没有一点问题。

**Comment by thezzycom** [comment]
表示一直用没问题

**Comment by p3rcya** [comment]
和蓝灯没关系。是你自己电脑上可能有病毒
