### ISSUE TITLE
已购买的1年期PRO，怎么登陆不了

### ISSUE THREAD

**Issue by sealwan** [getlantern/forum#2034]
昨天才购买的才购买的1年期PRO，登陆时提示：Cannot recover user from provided information
购买email：wjwanbo@163.com，支付宝交易，交易ID：w103313145
不能用就退钱啊！！

**Comment by sealwan** [comment]
别人都是付款完成之后，直接就变成专业版了，我付款后还是试用版，找回email，又提示Cannot recover user from provided information，有没有搞错啊！

**Comment by sealwan** [comment]
请尽快解决啊！

**Comment by p3rcya** [comment]
这种是付款没有成功导致的。应该会收到银行的退款。

**Comment by sealwan** [comment]
没有收到退款啊，我是支付宝付款的，不是信用卡啊，你能查Paymentwall交易ID吗？
ID：w103313145

**Comment by p3rcya** [comment]
正在调查

**Comment by p3rcya** [comment]
@sealwan 请问你蓝灯哪里下载的？具体下载地址是什么？

**Comment by sealwan** [comment]
https://s3.amazonaws.com/lantern/lantern-installer-beta.apk

**Comment by sealwan** [comment]
就是这个网上下的啊

**Comment by p3rcya** [comment]
请问是什么时候下载的？

**Comment by sealwan** [comment]
昨天12月2日

**Comment by sealwan** [comment]
啊，已经可以用专业版了。
但是频繁闪退是怎么回事啊，一点开关就闪退啊！

**Comment by sealwan** [comment]
我的手机是华为mate9，蓝灯频繁闪退，根本没法用

**Comment by p3rcya** [comment]
请问是什么版本的系统？什么版本的蓝灯？
