### ISSUE TITLE
蓝灯安卓版在偷跑流量？？

### ISSUE THREAD

**Issue by jayofstella** [getlantern/forum#2062]
12月1日，光一天蓝灯跑了100m，可是我所有app使用加起来也不到100m，蓝灯单独跑了至少50m以上！
吓得我出门只能关掉蜂窝网络了！这到底是版本bug还是。。。。？？？

**Comment by p3rcya** [comment]
还有系统的流量吧，50M差不多吧

**Comment by jayofstella** [comment]
@p3rcya  在智能管理器看的，s7e 手机，除去各种软件的流量，一天蓝灯跑50m正常吗？30天就要1500M啊！！电信套餐只包含1000m而已！我发现问题以后立刻关闭了蓝灯并且禁止自启动，终于正常了，但是牵扯到的问题就是不方便使用。唉，我买了2年的，没想到用起来这么不顺畅，不知道可否退掉拿一部分refund？

**Comment by jayofstella** [comment]
之所以发现这个问题 也是最近发现流量跑得太快，有点不正常了，11月20号就已经流量殆尽，所以专门查看了使用情况。

事实上因为发现即使开着蓝灯，港版系统下的S7依旧因为不停链接Google服务器导致耗电异常，在刷了国行系统以后，蓝灯几乎不怎么使用了，即使这样，蓝灯依然在11月跑了300多M流量（几乎没有打开软件的情况下），所以希望，至少给出一个解决方案吧。。。 @p3rcya

**Comment by p3rcya** [comment]
近期的版本引入了一个bug... 请去论坛主页下载最新的3.5.12版 https://github.com/getlantern/forum ，已经修复此问题。但之前很多用户报告的原因确实是其它应用的流量导致的。
