### ISSUE TITLE
安卓版试用后感觉不错，直接付费购买专业版，但专业版购买成功后开始闪退，请解决

### ISSUE THREAD

**Issue by rockychentri** [getlantern/forum#2090]
您好，免费版试用很不错，所以买了1年付费版。付费成功自动转为专业版后开始闪退，根本无法使用。卸载重新安装后无解。
另外，我购买时填写用户名邮箱为546653224@qq.com，购买成功后变成546653224@gmail.com了，这个邮箱不是我的，麻烦帮忙调整。
闪退问题我用软件上报后，都会发给我一个自动回复邮件让我填写detail，但我在安卓机上找不到相关信息。
请尽快解决或退款

**Comment by NAHSUH** [comment]
不是吧。我准备买专业版。问题多，好纠结。

**Comment by temnia** [comment]
这是最新版本的bug导致，开发组已在修复，等待更新

**Comment by rockychentri** [comment]
好的，那我等等看。

**Comment by temnia** [comment]
你可以先下载旧版本的稳定版使用

2016-12-11 22:47 GMT+08:00 rockychentri <notifications@github.com>:

**Comment by p3rcya** [comment]
邮箱已经调整。闪退请报告蓝灯版本，系统版本和手机型号

**Comment by rockychentri** [comment]
蓝灯3.5.5，手机型号华为荣耀8，安卓型号 6.0，emui 4.1

**Comment by rockychentri** [comment]
你好，安卓旧版本在哪儿下载？精华帖的3.4下下来还是3.5.5

**Comment by temnia** [comment]
新版本3.5.7已发布

**Comment by p3rcya** [comment]
蓝灯3.5.7发布，解决闪退问题 https://github.com/getlantern/forum/issues/2133
