### ISSUE TITLE
我的授权设备满了，请帮忙清除一下，谢谢

### ISSUE THREAD

**Issue by maxh1983** [getlantern/forum#2095]
我的账号是kaidi.huang@qq.com
非常感谢！

**Comment by p3rcya** [comment]
已经清除了所有已授权的设备，请重新安装最新版 https://github.com/getlantern/forum 后登录。

**Comment by maxh1983** [comment]
非常感谢，可用了

**Comment by maxh1983** [comment]
非常感谢，可用了
