### ISSUE TITLE
如何获取动态授权码？

### ISSUE THREAD

**Issue by sialchina** [getlantern/forum#2098]
专业版可以允许3台设备使用，当我授权其他设备使用专业版时，需要输入授权码，如何获得？请答复

**Comment by p3rcya** [comment]
请看教程 https://github.com/getlantern/forum/issues/973

**Comment by duruiok** [comment]
真是要了卿命！安卓蓝灯授权设备使用专业版，根本就不出现动态授权码！请问如何解决？版本3.6.3

**Comment by Frozensunshine** [comment]
是的，我也是跟楼上一样的问题。怎么办？

**Comment by p3rcya** [comment]
请报告网络环境，访问时段。
**请在本帖提供email**, 并使用应用内发送日志功能报告问题。若无法自动提交，请手动上传，方法见
https://github.com/getlantern/forum/issues/1840#issuecomment-260143243
。请及时提供，否则无法调查，谢谢！

**Comment by Taka9903** [comment]
同样的问题，不显示动态授权码，邮箱找回账号一直在加载没反应。

**Comment by JennieYan** [comment]
如何获取动态授权码？这个问题我也没解决？求助！
因为忘记了动态授权码，现在要如何生成？
