### ISSUE TITLE
安卓手机 授权动态码不显示

### ISSUE THREAD

**Issue by cocosUnity** [getlantern/forum#2102]
安卓手机 授权动态码不显示 怎么才能授权
![screenshot_2013-01-01-03-53-03 1](https://cloud.githubusercontent.com/assets/24518108/21090278/9efc2cac-c079-11e6-98e5-b9d6f5ffac6c.png)

**Comment by p3rcya** [comment]
用邮箱登陆试试

**Comment by cocosUnity** [comment]
问题解决，用邮箱登上了。
