### ISSUE TITLE
s7edge  3.5.6版本闪退

### ISSUE THREAD

**Issue by xxl594482971** [getlantern/forum#2119]
手机为安卓7.0系统，昨天更新了下系统，今天下载了最新的蓝灯，然后就闪退。不知道是蓝灯的原因还是系统的原因。

**Comment by xxl594482971** [comment]
我试过了，3.4.X的没问题。

**Comment by gaoliup** [comment]
我也是，继续用3.4.2

**Comment by KamilleK** [comment]
安卓7.1.1，今天升3.5.6，闪崩

**Comment by gaoliup** [comment]
@KamilleK 我6.0也闪退。先用旧版本吧

**Comment by KamilleK** [comment]
@gaoliup 能不能给我发一个？heero_kyou@hotmail.com。谢谢！

**Comment by gaoliup** [comment]
@KamilleK 已发

**Comment by sankatorres** [comment]
@gaoliup 发一个给我吧，谢谢。sanka.wk@gmail.com

**Comment by gaoliup** [comment]
@sankatorres 已发

**Comment by sankatorres** [comment]
@gaoliup 已收到，十分感谢

**Comment by p3rcya** [comment]
蓝灯3.5.7发布，解决闪退问题 https://github.com/getlantern/forum/issues/2133
