### ISSUE TITLE
oneplus 3 安卓蓝灯3.5.6闪退

### ISSUE THREAD

**Issue by gaoliup** [getlantern/forum#2120]
从谷歌和论坛安装的3.5.6都闪退，日志已提交，尽快修复，还好我有3.4.2的存档，旧版本一切正常。

**Comment by gaoliup** [comment]
安卓6.0，闪退

**Comment by Jannister** [comment]
楼主如果可以的话求个3.4.2的apk，论坛里已经找不到了。吃一堑长一智我以后一定先来论坛看看大家怎么说的再决定升级与否

邮箱graindia@sina.com

**Comment by gaoliup** [comment]
@Jannister 已发

**Comment by Jannister** [comment]
@gaoliup 感谢。已收到！

**Comment by sankatorres** [comment]
我的华为mate 9今天更新后也崩溃闪退，求3.4.2的apk文件，邮箱sanka.wk@gmail.com

**Comment by sankatorres** [comment]
现在3.5.6版本之前的版本是3.4.2吗？之前的用的好好的，一更新崩溃了，下次慎重更新了

**Comment by gaoliup** [comment]
@sankatorres 具体版本号不知道，反正3.4.2是没问题的

**Comment by p3rcya** [comment]
蓝灯3.5.7发布，解决闪退问题 https://github.com/getlantern/forum/issues/2133
