### ISSUE TITLE
请帮忙清除授权，三个名额满了无法授权了

### ISSUE THREAD

**Issue by wall-l** [getlantern/forum#2123]
请帮忙清除授权，三个名额满了无法授权了

**Comment by wall-l** [comment]
邮箱 feng200660@163.com

**Comment by wall-l** [comment]
这个软件，根本没人管啊！售后问题这么多。

**Comment by p3rcya** [comment]
已经清除了所有已授权的设备，请重新安装最新版 https://github.com/getlantern/forum 后登录。
