### ISSUE TITLE
刚下载了蓝灯, 没有看到800M免费流量?

### ISSUE THREAD

**Issue by fenivana** [getlantern/forum#2136]
我想测试一下不限速模式下的速度再决定是否购买, 但下载安装后显示 "每月免费高速流量剩余0MB. " ?
Android客户端

**Comment by Quattroporte** [comment]
我可以用我的号授权你试试

**Comment by fenivana** [comment]
论坛里一堆要求退款的, 吓怕了, 还是再观望一下吧...

**Comment by NAHSUH** [comment]
我觉得这跟自己的网络有问题。
