### ISSUE TITLE
搞毛搞毛搞毛啊

### ISSUE THREAD

**Issue by ArvinLiuV** [getlantern/forum#2197]
安卓新版本开启链接就开始狂跑流量，然后Google打不开，开百度都卡的要死。
不要和我说别的软件跑的，我有另一款收费VPN（奇怪为什么买两个？还不因为是破安卓版烂的跟翔一样），翻墙后既不狂跑流量也不会翻不了墙。
所以我再再再再再来问一次，你们在搞毛？

**Comment by rockychentri** [comment]
求分享另一款。。

**Comment by ArvinLiuV** [comment]
@rockychentri 在这里不能说其他VPN的名字，说了就会以打广告的名义把帖子给你关掉。我之前有过一贴提到了另一款完全免费（连收费版本都没有）的VPN，就被【不准打广告】给封掉了。

**Comment by ssy341** [comment]
免费的都不分享，重新开一贴在这里分享：[FQ看这里，输入我的邀请码 LKWP6W 额外获得三个月的蓝灯专业版](https://github.com/ssy341/datatables-cn/issues/5)

**Comment by p3rcya** [comment]
近期的版本引入了一个bug... 请去论坛主页下载最新的3.5.12版 https://github.com/getlantern/forum ，已经修复此问题。但之前很多用户报告的原因确实是其它应用的流量导致的。
