### ISSUE TITLE
能不退款能不能退款

### ISSUE THREAD

**Issue by aunret** [getlantern/forum#2200]
真是收完钱就不管用户体验了，看个视频480都卡顿半天。还有这是什么情况，啥都不动这软件就把所有上传速度都占用了，到底传什么呢！
![2016-12-20 20 09 31](https://cloud.githubusercontent.com/assets/18435440/21350195/ffb2c196-c6f0-11e6-97c4-cd17186aace9.png)
![Uploading 屏幕快照 2016-12-20 20.09.31.png…]()

**Comment by gbmeco** [comment]
这个测流量的是什么软件？

**Comment by aunret** [comment]
iStat

**Comment by hao505** [comment]
iStat是windows上的软件吗？

**Comment by jayofstella** [comment]
同问 如何退款，哪怕只退一半

**Comment by miscellaneous20** [comment]
同问

**Comment by p3rcya** [comment]
近期的版本引入了一个bug... 请去论坛主页下载最新的3.5.12版 https://github.com/getlantern/forum ，已经修复此问题。但之前很多用户报告的原因确实是其它应用的流量导致的。
