### ISSUE TITLE
lantern3.5.9安卓后台吃移动流量厉害，昨天突然发现它吃了700多m

### ISSUE THREAD

**Issue by zhrxx444** [getlantern/forum#2205]

**Comment by qcind** [comment]
能消耗这么多流量，那请问：速度快吗？

**Comment by zhrxx444** [comment]
我基本没有用移动4G连过lantern，都是WiFi，昨天打开手机的数据使用，看到蓝灯后台消耗700多M。最近极难打开YouTube，不过连上了速度还是快的

**Comment by jayofstella** [comment]
我早就报告过这个问题 发过帖子 不过被回复说 是因为开lantern所有流量都过lantern
实际上
我这个月没怎么用过lantern，就这 吃了我1,4g
我已经卸载了安卓版的lantern了

**Comment by jayofstella** [comment]
另外 速度并不快。。。感觉lantern团队现在不好好做软件 着急赚钱，新的web页面正在招代理呢。。。
我觉得lantern2.X的时候很好用，因为那时候的体验我才充值的 没成想！
唉！！

**Comment by qcind** [comment]
3.5.11 
ing ?

**Comment by jayofstella** [comment]
@qcind 我已经把安卓版删了，实在不能忍受每个月前10天就把我2个多G流量跑完。。
现在好多问题，团队解决的都不好好后悔充值！
我感觉这个项目用不了2年就会完蛋。。。
唉，要知道黑五astrll一年也才不到50usd，早知道就不该贪便宜

**Comment by thezzycom** [comment]
厉害了，吓的寡人赶紧看了一下流量

**Comment by dodowin** [comment]
要圈一波跑路的感觉

**Comment by merlinfong** [comment]
安装蓝灯最新版，就没有这个问题了

**Comment by p3rcya** [comment]
近期的版本引入了一个bug... 请去论坛主页下载最新的3.5.12版 https://github.com/getlantern/forum ，已经修复此问题。但之前很多用户报告的原因确实是其它应用的流量导致的。
