### ISSUE TITLE
Kaspersky 发现病毒 PDM:Trojan.Win32.Bazon.a

### ISSUE THREAD

**Issue by ningfc** [getlantern/forum#2209]
下载下来直接就被卡巴删掉了

**Comment by p3rcya** [comment]
正在解决

**Comment by bangyangyao** [comment]
电脑管家报毒。

**Comment by gcfkhy** [comment]
windows 自带也一样

**Comment by bleedingmouse** [comment]
我笔记本上的Microsoft Security Essentials 不报毒，台式机上的卡巴斯基目前报了两种，一个多月前是“Trojan-Banker.Win32.Banbra.vbiw”，我有点儿疑心就换了GoAgent用，但实在不顺，又换回，刚刚卡巴报的则是“Trojan-Banker.Win32.Banbra.vhgb”。

**Comment by bangyangyao** [comment]
管理员能答复一下吗！？

**Comment by bleedingmouse** [comment]
昨天我的微软也杀lantern了。

**Comment by oncidiumluridum** [comment]
這些軟件都不老實，申請了太多敏感權限就不應該后臺下載更新包，這是大忌。跟國內 BAT 一樣的流氓。

**Comment by duhast123** [comment]
特别手机版，后台偷跑数据太严重，就光打开lantern，其它程序不运行，一天下来也会消耗几十M流量，电脑版倒没发现太大问题，就是会在注册表添加自动运行项，管理截面设置不管用，每次运行都会在注册表添加那个键

**Comment by p3rcya** [comment]
解决了，卡巴斯基已经不误报了 https://www.virustotal.com/en/file/426bf3ee177a8249e530931941c00745533fdf38d903599e019708407eb5760f/analysis/
