### ISSUE TITLE
蓝灯骗局？蓝灯官方请回话

### ISSUE THREAD

**Issue by masterzheng13** [getlantern/forum#2229]
我已授权了三台设备，但三台设备都丢失了，现在我想在一台新的设备上登录，可是发现账号找不回来，显示“已近授权了三台设备”，这就意味着我用不了。无论之前账号找不回的问题，还是现在的无法新授权设备问题，我都被困扰，造成我长期不能正常使用蓝灯，我请求蓝灯官方给我赔偿或延期。
 
如果可以的话，请把蓝灯官网设置成中文，看起来累，也看不懂，谢谢

**Comment by masterzheng13** [comment]
请求清理所有授权设备，谢谢，邮箱 970716304@qq.com,并要求延期

**Comment by p3rcya** [comment]
已经清除了所有已授权的设备，请重新安装最新版 https://github.com/getlantern/forum 后登录。
