### ISSUE TITLE
输入邀请码后出现错误

### ISSUE THREAD

**Issue by shellj** [getlantern/forum#2234]
输入邀请码后出现错误，不填邀请码就可以，
这个就尴尬了 😉
<img width="1399" alt="error" src="https://cloud.githubusercontent.com/assets/1058220/21537313/b339e296-cdca-11e6-8c08-c00759022826.png">

**Comment by orbancanon** [comment]
@shellj 这是之前版本的一个bug。麻烦你[下载最新版](https://github.com/getlantern/forum#蓝灯lantern最新版本下载)

**Comment by shellj** [comment]
@orbancanon 好难过😭，已经支付了，没有拿到邀请奖励
