### ISSUE TITLE
context deadline exceeded

### ISSUE THREAD

**Issue by KnightSch** [getlantern/forum#2235]
系统,ubuntu 14.04,蓝灯版本:Lantern 3.5.11 (20161223.201228)
可以番强,但是偶尔打开有些网站报context deadline exceeded,重新刷新又会好,这是什么问题?

**Comment by Jannister** [comment]
win10系统，也这样。

**Comment by RichardKuroshio** [comment]
Win7遇到了同样的情况，需要多次刷新，刚才是要翻墙的网站突然全都打不开了

**Comment by peak0632** [comment]
我也是这样

**Comment by xfq** [comment]
试试最新版本（参见 getlantern/lantern#5526 ）。

**Comment by p3rcya** [comment]
最新的3.5.12 解决了这个问题，请去论坛主页下载最新的3.5.12版 https://github.com/getlantern/forum
