### ISSUE TITLE
蓝灯一直显示context deadline exceeded

### ISSUE THREAD

**Issue by niyifei-ss** [getlantern/forum#2244]

**Comment by LollingChris** [comment]
是的。我昨晚也是。

**Comment by peak0632** [comment]
我这几天都遇到这个问题，需要刷新两三次页面才能正常加载，这几天经常遇到

**Comment by jiannan20052005** [comment]
我也是如此，必须多刷新几次才行。以前没这事是更新到3.5.11版本就这样了。希望管理员能解决一下。

**Comment by p3rcya** [comment]
最新的3.5.12 解决了这个问题，请去论坛主页下载最新的3.5.12版 https://github.com/getlantern/forum
