### ISSUE TITLE
安卓新版到底为什么跑流量

### ISSUE THREAD

**Issue by ArvinLiuV** [getlantern/forum#2248]
不要再说不是Lantern跑的这种没节操的话了，只要打开，不管翻不翻墙，一直跑流量。清理掉Lantern的进程立马变0。给个解释。
旧版没问题而新版有，只能是你们加了隐秘数据收集上传。如果要否认请说出来到底为什么跑流量。

**Comment by merlinfong** [comment]
背后肯定大有问题，请管理员解释！！！

**Comment by shuiyingwuhen** [comment]
希望管理員解釋下，吃流量特別厲害

**Comment by orbancanon** [comment]
近期的版本引入了一个bug... 请下载最新的3.5.12版，已经修复此问题 （参见https://github.com/getlantern/forum/issues/2268#issuecomment-271124619 ）。但之前很多用户报告的原因确实是其它应用的流量导致的。

**Comment by p3rcya** [comment]
近期的版本引入了一个bug... 请去论坛主页下载最新的3.5.12版 https://github.com/getlantern/forum ，已经修复此问题。但之前很多用户报告的原因确实是其它应用的流量导致的。
