### ISSUE TITLE
蓝灯访问网页提示503错误

### ISSUE THREAD

**Issue by luiqn2007** [getlantern/forum#2271]
错误信息：

HTTP/0.0 503 Service Unavailable
Date: Wednesday, 04-Jan-17 14:15:54 CST
Keep-Alive: timeout: 38

context deadline exceeded

一开始免费版有无限速流量的时候正常，后来流量用完了就偶尔出现这个问题，然后买了专业版还有这个问题。。。
好多网站都有出现过这种问题，刷新一下一般能解决，但是有时候，比注册，或者申请什么的时候，刷新就不太合适了。希望能解决这个问题。
而且总觉得专业版速度还不如用免费无限速流量时候快？

**Comment by p3rcya** [comment]
最新的蓝灯解决了这个问题，请重新安装最新版 https://github.com/getlantern/forum 后登录。

**Comment by luiqn2007** [comment]
好吧，，，现在没有503了，开始验证机器人了。。。
