### ISSUE TITLE
context deadline exceeded错误

### ISSUE THREAD

**Issue by luiqn2007** [getlantern/forum#2272]
打开网页显示 context deadline exceeded 错误。刷新几次有时候能显示。
尤其是百度的，贴吧等，还有别的国内网站也会出现。
开着全局代理，因为经常要去github等，不开太慢，不想频繁切换了。
怎么回事？

**Comment by stipethom** [comment]
我也有这个问题，而且不停地闪退……

**Comment by p3rcya** [comment]
最新的3.5.12 解决了这个问题，请去论坛主页下载最新的3.5.12版 https://github.com/getlantern/forum

**Comment by kkew3** [comment]
同问，但版本是3.7.4

**Comment by CdricZhang** [comment]
访问朝中社网站http://www.kcna.kp/的时候, 又出现了这个问题
