### ISSUE TITLE
证书过期

### ISSUE THREAD

**Issue by cronaldook7** [getlantern/forum#2274]
电脑3.5.12版，数字证书过期或尚未生效，怎么回事？我是在论坛上更新的。

**Comment by thezzycom** [comment]
ssl 过期是网扎你的事，跟lantern没关系

**Comment by thezzycom** [comment]
你访问网站的锅

**Comment by gsaves** [comment]
![image](https://cloud.githubusercontent.com/assets/3612024/21762046/94d1707e-d691-11e6-9319-8eaab5122edf.png)
这个和网站有关系？

**Comment by p3rcya** [comment]
3.6.0 应该解决了这个问题，请下载新版
