### ISSUE TITLE
Refund

### ISSUE THREAD

**Issue by myz1912** [getlantern/forum#2288]
跑流量不解决，现在connected仍然无法访问Google。 
买了不到一周，给我退款!
也希望大家要买pro的看看，蓝灯现在问题多严重而且管理员鸟都不鸟你。购买请三思

**Comment by zsqp447** [comment]
还梦想退款，快醒醒吧，趁用的时间短赶紧打个对折卖掉，WINDOWS端还是挺快挺稳的，也许能卖掉

**Comment by p3rcya** [comment]
近期的版本引入了一个bug... 请去论坛主页下载最新的3.5.12版 https://github.com/getlantern/forum ，已经修复此问题。但之前很多用户报告的原因确实是其它应用的流量导致的。
