### ISSUE TITLE
输入我的邀请码 YJB7J3P 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

### ISSUE THREAD

**Issue by lb814641551** [getlantern/forum#2290]
输入我的邀请码 YJB7J3P 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by lb814641551** [comment]
输入我的邀请码 YJB7J3P 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by zhoujianmin** [comment]
输入我的邀请码 WMHZRD 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by hohodasheng** [comment]
输入我的邀请码 2QL2QP 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
