### ISSUE TITLE
One-year lantern Pro plan on sale ONLY HALF PRICE! 一年期蓝灯专业版出售 半价！

### ISSUE THREAD

**Issue by myz1912** [getlantern/forum#2292]
I just subscribed to my one-year plan 3 days ago. Basically, I am not satisfied with their service so I decide to resell my account. You can get a full year pro lantern for only **HALF** price, say $15 or ￥100. Also, the promotion code is intact. 

If you are interested about that, don't hesitate to contact me: zym1994815@gmail.com

我三天之前刚买了一年期的蓝灯专业版。可是我不满意蓝灯的服务，现在决定转卖它。有兴趣的朋友只需要半价，15刀或者100人民币，即可享受一年的蓝队pro  并且激活码是未使用的

有兴趣的朋友请联系我！ 邮箱地址zym1994815@gmail.com

**Comment by ireland2011** [comment]
问你一下, 购买后多久收到激活码?

**Comment by myz1912** [comment]
@ireland2011 你是说买我的？如果有兴趣给我发封邮件吧 细说

**Comment by p3rcya** [comment]
零售版没有激活码，请大家小心

**Comment by myz1912** [comment]
I don't provide an activation code. Instead, I activate your device then you can remove my last authorized device. That's the thing. Any concern contact me via email: zym1994815@gmail.com

**Comment by myz1912** [comment]
@p3rcya I mean the promotion code not the activation code. Promotion code can prolong your subscription.
