### ISSUE TITLE
蓝灯专业版，信用卡&支付宝均支付失败

### ISSUE THREAD

**Issue by LJerO** [getlantern/forum#2310]
如题，信用卡换过三张，mastercard、JCB、银联，全部显示√，扣款1or0美元，之后又消费冲正，支付宝显示不可用，请帮忙解决，非常感谢
[lantern.zip](https://github.com/getlantern/forum/files/693303/lantern.zip)

**Comment by p3rcya** [comment]
你使用的是什么版本？ 请使用最新版本

**Comment by LJerO** [comment]
感谢！问题已解决

**Comment by p3rcya** [comment]
如何解决的？

**Comment by LJerO** [comment]
更换最新版本之后解决，非常感谢！
