### ISSUE TITLE
最近有点儿被磨得没脾气了....日志和截图打包了

### ISSUE THREAD

**Issue by aold619** [getlantern/forum#2311]
1、动不动就timeout了，见截图，浏览网页已经很烦了，下载几乎无法进行，手机端速度尚可，但PC端速度还是有点儿....
2、设备解绑依旧没有效果，出现这么些个问题和设备的解绑什么的有没有关系也不知道
3、是否全局代理必须通过网页上调整，很麻烦，那这个客户端是为了做什么的....不能理解

[logs.zip](https://github.com/getlantern/forum/files/693660/logs.zip)

**Comment by aold619** [comment]
看到了别人的贴子，已经更新了最新版，我先用用试试吧，更新了不说给个提示吧，我们自己看也行，各个下载地址上都没有版本号提示....无语了...
唉，就盼着早点能稳定啊大哥....速度都不要求了，慢慢提，先能稳定，包括自定义代理的域名等等该有的功能有了，完了速度慢慢提啊可以.....

**Comment by HelloThisWorld** [comment]
却是总是timeout，多刷新几次就好了，怀疑是连接池释放有问题

**Comment by GD-HBX** [comment]
貌似现在lantern自动更新的，是我眼花了吗？

**Comment by aold619** [comment]
更新了最新版之后用了几天，感觉很不错，这次更新的确给力。希望后续可以方便一点切换是否全局代理。
