### ISSUE TITLE
老蓝灯用户现出售手头一款用于苹果手机的闲置VPN，希望别删贴

### ISSUE THREAD

**Issue by rocknrollfly** [getlantern/forum#2320]
我是一名老蓝灯用户，现在看着很多网友急于在iphone上翻墙，正好我前两天心急花18元在苹果商店买了一个月的VPN，只用了两天，速度稳定性都很好，现现在主要用蓝灯PC端所以不想要了，半价出售。不用越狱就能用！

要的请直接回复此帖留下你的联系方式，交个朋友以后买蓝灯都可以分享邀请码

**Comment by huiyu998** [comment]
朋友rocknrollfly你好，18元在苹果商店买了一个月的VPN？可以告诉大家名字吗？等蓝灯出IOS估计够呛了。我准备给原来购买蓝灯的朋友，因为他们买蓝灯冲着蓝灯2016年底出蓝灯出IOS版才购买的，当时我推荐他们购买的。现在不知道怎么面对朋友。

**Comment by rocknrollfly** [comment]
@huiyu998 告诉我你的联系方式我直接联系你吧，在这里说有广告嫌疑

**Comment by rocknrollfly** [comment]
@huiyu998 如果你要买我购买了的这一个月的我就联系你

**Comment by huiyu998** [comment]
您好谢谢494968081@qq.com邮箱联系
