### ISSUE TITLE
lantern 3.6.1 专业版，无法连接到蓝灯的服务器

### ISSUE THREAD

**Issue by Eccolala** [getlantern/forum#2327]
@p3rcya **Ubuntu 14.0.4**  Lantern 3.6.1(20170110.002026)
![ScreenShot](https://cloud.githubusercontent.com/assets/8536168/21871683/c0ae0afe-d89e-11e6-98e6-31a8dd29e421.png)
**Log**
 ##

[lantern.txt](https://github.com/getlantern/forum/files/700407/lantern.txt)

**Comment by spiderraven** [comment]
请问是怎么解决的，我今天更新之后也无法连接服务器

**Comment by Eccolala** [comment]
自己就好了
