### ISSUE TITLE
3.6.1专业版用户，一直无法连接蓝灯服务器

### ISSUE THREAD

**Issue by spiderraven** [getlantern/forum#2342]
专业版用户，今天中午开始一直无法连接蓝灯服务器。蓝灯版本是3.6.1.
路由器重启、卸载重装之后依然如此，求解

**Comment by spiderraven** [comment]
每次连接都提示无法连接到蓝灯服务器，是怎么回事？

**Comment by spiderraven** [comment]
[lantern.txt](https://github.com/getlantern/forum/files/706426/lantern.txt)

**Comment by Tjlastnumber** [comment]
我也是同样的问题，显示无法连接服务器

**Comment by huiyu998** [comment]
电脑版的圈圈转了好久显示“很抱歉，我们无法连接到蓝灯的服务器。请检查您的网络连接并重试。”

**Comment by p3rcya** [comment]
请问你的log为什么显示的是1月1日？ 不是现在的log？ @spiderraven

**Comment by spiderraven** [comment]
这个是我今天早上重装后，根据版内的方法导出的LOG，系统时间是1月15号没问题，LOG显示1月1号不知道为什么。。。但可以肯定的是是今天上午11点左右导出的

**Comment by p3rcya** [comment]
现在解决了吗？你重启下试试

**Comment by spiderraven** [comment]
可以使用了，谢谢
