### ISSUE TITLE
输入我的邀请码 2QL2QP 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

### ISSUE THREAD

**Issue by hohodasheng** [getlantern/forum#2345]
输入我的邀请码 2QL2QP 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by raobing496** [comment]
＃三年or三个月＃邀请码，输入我的邀请码 LY5SN6 来获得三个月的蓝灯专业版！复制。一次就可以哦，不管你有没有购买专业版，只要绑定您的邮箱就完成邀请动作的，您邮箱以后只要购买了，就能获得额外的3个月的免费试用时长，不信你试试哦：LY5SN6！冷艳少女5555555566666666666么么哒～
