### ISSUE TITLE
如何通过蓝灯在终端翻墙

### ISSUE THREAD

**Issue by zzhanga** [getlantern/forum#2352]
RT，我需要从ubuntu系统的终端命令中访问谷歌去获取源代码，如何让终端也可以通过蓝灯翻墙？请大神指点

**Comment by ssy341** [comment]
![20170116125928](https://cloud.githubusercontent.com/assets/1725705/21971443/a4d835de-dbeb-11e6-8f76-36ae054627e4.jpg)
在命令行设置代理为上述的即可

**Comment by blackredscarf** [comment]
@ssy341 我在终端设置了我的端口
export http_proxy=http://127.0.0.1:XXXX
export https_proxy=http://127.0.0.1:XXXX
还有socks的端口也设置了
但ping google.com 仍然不通，请教怎么解决！

**Comment by zzhanga** [comment]
@blackredscarf 你需要使用proxychains或者proxychains-ng进行代理

**Comment by blackredscarf** [comment]
@zzhanga 我在/etc/proxychains.conf
设置socks5 127.0.0.1 XXXX
然后proxychains4 ping google.com
仍然不通。。。

**Comment by zzhanga** [comment]
@blackredscarf 大概你也尝试了www.google.hk 或者 www.google.jp 或者 www.facebook.com 等同类型网站吧，如果你的浏览器能正常访问但是终端不可以的话，我建议查看一下你的DNS或者proxychains的DNS默认设置，还望解决

**Comment by blackredscarf** [comment]
@zzhanga 
昨天还好好的，今天变成这样了：【已经是最新版本了】
HTTP/0.0 503 Service Unavailable
Date: Sunday, 19-Feb-17 21:00:38 PST
Keep-Alive: timeout=38

Still unable to dial persistent://www.google.com:80 after 3 attempts

**Comment by TaylorSwiftRed** [comment]
楼主，你是怎么解决的，最近好头疼这个问题哦。。

**Comment by zzhanga** [comment]
我的解决办法是使用使用proxychains或者proxychains-ng进行终端代理，获取代码的话，是给git设置了代理

**Comment by yzthr** [comment]
输入我的邀请码 YMYW9CT 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by Abson** [comment]
因为 ping 并不是走 http/https 协议

**Comment by Abson** [comment]
ping 走 ICMP 协议呀兄弟

**Comment by Abson** [comment]
你可以使用 curl https://www.google.com
