### ISSUE TITLE
需要在window的终端console也访问屏蔽网站，如何设置lantern

### ISSUE THREAD

**Issue by wuxilistl** [getlantern/forum#2365]
比如在windows终端，用wget命令访问GOOGLE，

**Comment by shendanpuff** [comment]
你需要Proxifier，自行google一下，有很多教程的

**Comment by wuxilistl** [comment]
嗯，找到了。建立系统变量https_proxy;值为lantern的http(s)代理服务器（lantern-》设置-》高级设置）。
或者在congsole中set https_proxy=代理服务器
