### ISSUE TITLE
刚买了一年的，我这么授权我的其他设备啊

### ISSUE THREAD

**Issue by diyxiaoshitou** [getlantern/forum#2372]
刚买了一年的，我这么授权我的其他设备啊

**Comment by diyxiaoshitou** [comment]
还有上面写着180元，我付费的时候这么是216元啊

**Comment by temnia** [comment]
用你“已授权的设备”输入你的其他“未授权设备”的激活码
金额应该交易的是美元，汇率一下就。。。。

**Comment by diyxiaoshitou** [comment]
哦,“未授权设备”的激活码,这么得到啊？ 还有就是什么时候支持iso

**Comment by shizongger** [comment]
金额交易的是美元？是人民币啊，我都是用支付宝支付的，确实是一年216元人民币，如果换算成美元，那1500元人民币一年的蓝灯，谁买谁SB!

**Comment by temnia** [comment]
我支付宝付出去的是美元，当时折合人名币是180

“为授权设备”打开授权那里有个激活码
