### ISSUE TITLE
显示账户1970年1月1号到期

### ISSUE THREAD

**Issue by solidusw** [getlantern/forum#2383]
求解决，13435537798@163.com

**Comment by solidusw** [comment]
另外在安卓端也无法使用

**Comment by p3rcya** [comment]
这个是没有购买成功导致的。银行应该会有退款，请重新购买

**Comment by p3rcya** [comment]
请上传一下购买截图

**Comment by hxy8278932** [comment]
我也是同样的问题！ 
![image](https://cloud.githubusercontent.com/assets/25238243/22134618/5bdb989c-df03-11e6-9087-caa3e40f12ea.png)

**Comment by hxy8278932** [comment]
电脑版本 无法授权 但可以使用专业版  每次使用 都要输入邮箱。
![image](https://cloud.githubusercontent.com/assets/25238243/22134631/85fa3dae-df03-11e6-8e31-a502888b8810.png)

**Comment by majiehui** [comment]
同样的问题 1648820920@qq.com 求解决

**Comment by solidusw** [comment]
[](url)
