### ISSUE TITLE
已经购买了专业版，但是怎么总是显示的是免费版的界面呢？

### ISSUE THREAD

**Issue by babikiu** [getlantern/forum#2384]
购买了专业版后，每次都需要在“授权设备使用专业版”输入一次邮箱，然后显示正常了，但是随后又会自己变成免费版的样子，速度也降下来了，vcbear11@163.com
![screenshot_2017-01-20-03-20-50-910_org getlantern lantern](https://cloud.githubusercontent.com/assets/25231293/22121626/c6f141fc-debf-11e6-9c7f-7471c8378135.png)
![screenshot_2017-01-20-03-20-37-980_org getlantern lantern](https://cloud.githubusercontent.com/assets/25231293/22121707/0296a12a-dec0-11e6-981d-4fd114a58c57.png)

**Comment by p3rcya** [comment]
后台查看了，你并没有成功购买专业版。请看看支付宝账单并且重新购买

**Comment by babikiu** [comment]
但是支付宝显示已经扣费了，怎么算？！！！
![screenshot_2017-01-20-04-07-39-975_com eg android alipaygphone](https://cloud.githubusercontent.com/assets/25231293/22123348/424a6ac6-dec6-11e6-9608-69dd399ed5b6.png)

**Comment by p3rcya** [comment]
正在调查

**Comment by p3rcya** [comment]
请使用应用内发送日志功能报告问题。若无法自动提交，请手动上传，方法见https://github.com/getlantern/forum/issues/1840#issuecomment-260143243 。请及时提供，否则无法调查，谢谢！

**Comment by babikiu** [comment]
已经通过“报告问题”提交日志

**Comment by p3rcya** [comment]
刷新下试试

**Comment by babikiu** [comment]
好了，谢谢

**Comment by babikiu** [comment]
还想问一下，这个3个设备限制是说3个设备同时登陆？那我想第4个设备使用，退出前面其中一个就可以吗？

**Comment by p3rcya** [comment]
对。请去账号管理界面推出

**Comment by hxy8278932** [comment]
我的手机版 也是这样的问题，麻烦看一下。287742934@qq.com  
![image](https://cloud.githubusercontent.com/assets/25238243/22134654/ac9d4492-df03-11e6-95cd-ce7963beafcb.png)
