### ISSUE TITLE
昨天买的专业版，今天显示1970年1月1日到期

### ISSUE THREAD

**Issue by zifang00** [getlantern/forum#2390]
求解决呀   zifang00@sina.com

**Comment by zifang00** [comment]
![2uwhffcj l1 2f33tciw5s9](https://cloud.githubusercontent.com/assets/25245259/22148472/40ce9446-df49-11e6-937c-69e276f52730.png)

**Comment by zifang00** [comment]
![td o53vnpy1fvv7 ld wvx](https://cloud.githubusercontent.com/assets/25245259/22148511/7b8160fa-df49-11e6-8050-7faad14542fb.png)

**Comment by qizi297** [comment]
Me too.
呵呵，我也无语了，之前我也买的lantern专业版，刚买完，打开lantern一看：未购买状态，我找回专业版账号后，就和你一样了

**Comment by p3rcya** [comment]
请不要挖坟。已经在你的帖子里面回复了
