### ISSUE TITLE
今天刚购买的专业版，但无法使用，显示账户1970年1月1号到期

### ISSUE THREAD

**Issue by rzybz** [getlantern/forum#2392]
68737877@qq.com，下面是账号和支付成功的截图
<img width="672" alt="qq20170120-0 2x" src="https://cloud.githubusercontent.com/assets/25248706/22153362/fde51704-df61-11e6-89ec-6495a1569c1d.png">
![wechatimg1](https://cloud.githubusercontent.com/assets/25248706/22153369/0654de74-df62-11e6-83de-0773f53b4b69.jpeg)
![wechatimg2](https://cloud.githubusercontent.com/assets/25248706/22153863/0c9a0dca-df64-11e6-9fca-54863e1d1931.jpeg)

**Comment by p3rcya** [comment]
请刷新
