### ISSUE TITLE
刚通过安卓手机客服端买的两年专业版，为什么每次登录电脑都要提示登录账号呢

### ISSUE THREAD

**Issue by tom324** [getlantern/forum#2393]
登录蓝灯账号以后不能解绑我的手机，也不能授权别的设备，提示错误，手机登录也不提示专业版，和电脑一样得通过邮件才能找回账号登录

**Comment by tom324** [comment]
关键不只是显示，我现在看youtube都不能使用流量了，速度才几十kb

**Comment by tom324** [comment]
我的邮箱是
1993128430@qq.com

**Comment by p3rcya** [comment]
请刷新
