### ISSUE TITLE
lantern专业版邀请码输入我的邀请码 Y4Y5NRM 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

### ISSUE THREAD

**Issue by tuburn** [getlantern/forum#2427]
lantern专业版邀请码输入我的邀请码 Y4Y5NRM 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by stephen666** [comment]
# 蓝灯lantern最新邀请码 Y2947HH 永久有效！获取三个月免费！

## 请输入我的蓝灯lantern邀请码 Y2947HH 来获得三个月免费的蓝灯专业版！使用后请留下你的邀请码，我也会使用你的邀请码续费的！
![lantern-referral-code](https://user-images.githubusercontent.com/11013738/28974582-69c1a87e-7969-11e7-8c4a-1178f2953bbd.png)

**Comment by cindy888** [comment]
For a free month of Lantern Pro, use this referral code: 4U6F55 ; You can download it from here: https://bit.ly/1M8x04u
