### ISSUE TITLE
手机刷机后无法绑定，请帮忙重设

### ISSUE THREAD

**Issue by beastrobin** [getlantern/forum#2429]
安装lantern授权显示:已经达到专业版账号同时登陆3个设备的上线。请帮忙重设一下，谢谢
账号: qiaojie288@sina.com
付费日期:2016.7.11 10:22

**Comment by p3rcya** [comment]
已经清除了所有已授权的设备，请重新安装最新版 https://github.com/getlantern/forum 后登录。
