### ISSUE TITLE
专业版蓝灯，ThinkPad win0已经无力吐槽了

### ISSUE THREAD

**Issue by newnu** [getlantern/forum#2441]
已经趁着再次重启时候的几分钟赶紧发去了问题的报告，北京的台式机win7完美运行，笔记本ThinkPad win0基本上是几分钟就死，需要重启才行，甚至重启也不行，要重装，有时候重装也不行，要把所有残余删的干干净净才行几分钟。我已经要被他整死了！我的邮箱ylmil@163.com。

**Comment by p3rcya** [comment]
请手动上传，方法见https://github.com/getlantern/forum/issues/1840#issuecomment-260143243 。请及时提供，否则无法调查，谢谢！

**Comment by newnu** [comment]
自动上传过了，现在再手动来一次

**Comment by newnu** [comment]
怎么压缩包也不能上传了？

**Comment by newnu** [comment]
试试PDF格式
[lantern.pdf](https://github.com/getlantern/forum/files/740818/lantern.pdf)

**Comment by newnu** [comment]
现在可以上，不知道还能用多久
