### ISSUE TITLE
怎么没法支付宝付款了？

### ISSUE THREAD

**Issue by atlaski** [getlantern/forum#2459]
手机版倒是有支付宝支付的选项，但点击后页面就从没出来过；电脑版的直接就没支付宝选项了。是不是只能信用卡支付了？

**Comment by p3rcya** [comment]
电脑版的直接就没支付宝选项了？ 给个截图看看。

请在本帖提供email, 并使用应用内发送日志功能报告问题。若无法自动提交，请手动上传，方法见https://github.com/getlantern/forum/issues/1840#issuecomment-260143243 。请及时提供，否则无法调查，谢谢！
