### ISSUE TITLE
为什么开了lantern能上推特youtube，但是上不去汤不热？tumblr？

### ISSUE THREAD

**Issue by boomrabbit** [getlantern/forum#248]
为什么开了lantern能上推特youtube，但是上不去汤不热？tumblr？
求让上汤不热tumblr。。。。

**Comment by p3rcya** [comment]
@fffw I thought our blacklist includes Tumblr?

**Comment by fffw** [comment]
Yes, it's included. Even if it's not, auto detection should work. tumblr can be open from our test VPS.

**Comment by boomrabbit** [comment]
〉_〈..。。。难道是我的问题？。。。

**Comment by boomrabbit** [comment]
@p3rcya @fffw 更新225以后，今天第一次打开可以上汤不热了。tumblr

**Comment by fffw** [comment]
Cool @boomrabbit . Though 2.2.5 did nothing relates to this issue. Closing for now.
