### ISSUE TITLE
转让lantern专业版

### ISSUE THREAD

**Issue by jinxiaohui0731** [getlantern/forum#2480]
一直是lantern的忠实粉丝用了好几年，可是最近苦于没有ios的版本改用其他工具了，刚买一两个月的lantern专业版想转让，不知道有没有触犯什么吧规。欢迎感兴趣的童鞋联系我吧

**Comment by jinxiaohui0731** [comment]
907581340@qq.com

**Comment by qiaotoubao** [comment]
我想知道 你现在用的什么软件 能分享下吧

**Comment by 130lin** [comment]
我也想换
vpn最好就是包月
用的不好就不续

**Comment by jinxiaohui0731** [comment]
谢谢各位支持，已经出了
