### ISSUE TITLE
这几天一直速度非常慢，网页加载困难，youtube只能144p。

### ISSUE THREAD

**Issue by zhenyangleo** [getlantern/forum#2514]
自从差不多2月6日开始，速度就非常的慢。软件内报告了几次，没有得到解决，也没有收到邮件回复，所以这里issue一下。

专业版
苏州移动
20M带宽
原来直接邮箱登陆的电脑不在身边没有测试，用的是被授权专业版的第二台电脑。
除了凌晨没测试，其他时段都是如此速度。
邮箱：zhenyangleo#hotmail.com
软件内的报告我记得发了三次了。
希望得到回复说明原因，毕竟是花了钱的，然而速度和免费版一样。

**Comment by atlantishulin** [comment]
类似的问题。

**Comment by qiaotoubao** [comment]
我现在也是一样 能上外网，速度有些慢。 @p3rcya @orbancanon 。管理员大大能帮忙看看吧

**Comment by youyuchi** [comment]
我也是如此，直接上不了了

**Comment by youyuchi** [comment]
@qiaotoubao @zhenyangleo @atlantishulin 你们好，我的问题解决了，我是通过下载最新版蓝灯弄好的，希望可以帮到你们

**Comment by p3rcya** [comment]
请LZ提交一下今天的日志，方便调查！谢谢

**Comment by youyuchi** [comment]
@p3rcya 大神问下上面时候有ios版。。。

**Comment by zhenyangleo** [comment]
@youyuchi 原来我也以为是版本问题，升级了3.6.3，依然很慢。

**Comment by youyuchi** [comment]
@zhenyangleo 那你把日志发给大神吧，他有办法解决的

**Comment by zhenyangleo** [comment]
有两个日志文件啊，不知道哪个是，我吧logs文件夹打了个包。 @p3rcya 
[logs文件夹.zip](https://github.com/getlantern/forum/files/762675/logs.zip)

**Comment by orbancanon** [comment]
@zhenyangleo 你的宽带到服务器之间不通，所以切换到香港去了。怀疑是运营商路由配置有问题。你尝试打开命令行（开始->运行->cmd），ping一下这几个地址看能不能通？

```
ping 218.188.104.9 -l 1000
ping 223.119.2.185 -l 1000
ping 223.118.3.125 -l 1000
ping 221.176.23.85 -l 1000
ping 211.136.1.106 -l 1000
ping 221.183.21.13 -l 1000
ping 221.183.21.17 -l 1000
ping 221.183.21.9 -l 1000
ping 211.136.1.102 -l 1000
ping 211.136.1.110 -l 1000
```

**Comment by zhenyangleo** [comment]
@p3rcya 我现在登录youtube是显示的.jp，应该是链接到日本的吧。之前用现在的移动网络，连接香港过，倒是挺快的；在家里电信网络连接日本，也是比较快的。

正在 Ping 223.119.2.185 具有 1000 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

223.119.2.185 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

C:\Users\ZhenDesk>ping 223.118.3.125 -l 1000

正在 Ping 223.118.3.125 具有 1000 字节的数据:
来自 223.118.3.125 的回复: 字节=1000 时间=41ms TTL=248
来自 223.118.3.125 的回复: 字节=1000 时间=45ms TTL=248
来自 223.118.3.125 的回复: 字节=1000 时间=42ms TTL=248
来自 223.118.3.125 的回复: 字节=1000 时间=43ms TTL=248

223.118.3.125 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 41ms，最长 = 45ms，平均 = 42ms

C:\Users\ZhenDesk>ping 221.176.23.85 -l 1000

正在 Ping 221.176.23.85 具有 1000 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

221.176.23.85 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

C:\Users\ZhenDesk>ping 211.136.1.106 -l 1000

正在 Ping 211.136.1.106 具有 1000 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

211.136.1.106 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

C:\Users\ZhenDesk>ping 221.183.21.13 -l 1000

正在 Ping 221.183.21.13 具有 1000 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

221.183.21.13 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

C:\Users\ZhenDesk>ping 221.183.21.17 -l 1000

正在 Ping 221.183.21.17 具有 1000 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

221.183.21.17 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

C:\Users\ZhenDesk>ping 221.183.21.9 -l 1000

正在 Ping 221.183.21.9 具有 1000 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

221.183.21.9 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

C:\Users\ZhenDesk>ping 211.136.1.102 -l 1000

正在 Ping 211.136.1.102 具有 1000 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

211.136.1.102 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

C:\Users\ZhenDesk>ping 211.136.1.110 -l 1000

正在 Ping 211.136.1.110 具有 1000 字节的数据:
请求超时。
请求超时。
请求超时。
请求超时。

211.136.1.110 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 0，丢失 = 4 (100% 丢失)，

**Comment by youyuchi** [comment]
@zhenyangleo 我刚刚出现蓝灯.维基连不上，你是怎么看自己网络日志和分析的？

**Comment by zhenyangleo** [comment]
@youyuchi 日志我也看不懂，我就上传了下。参考 #1840

**Comment by youyuchi** [comment]
@zhenyangleo 谢谢你

**Comment by orbancanon** [comment]
@zhenyangleo 我给你的这些都是香港移动/广东移动的IP地址，从服务器ping可以通，而且是去你本地宽带的中间节点。所以基本判断应该是宽带网络的问题。可能是哪里的路由做错了，这个可以跟移动反映一下。

@130lin @atlantishulin 你们是移动宽带，也可以ping上面的那些地址判断一下。

**Comment by zhenyangleo** [comment]
@orbancanon 你说的路由是指移动运营商的路由？还是我自己家里的路由器啊？如果是移动网络的问题，这个应该如何反映啊，会不是是移动故意这么做的呢。。。。。

**Comment by orbancanon** [comment]
@zhenyangleo 移动运营商的。故意倒不会。反映就打客服呗，说广东和香港移动的XXX地址，从我这里都不通啊，让转技术部门处理。

**Comment by zhenyangleo** [comment]
@orbancanon 一会儿客服试试看吧。但是客观也体现了现在lantern服务器少吧。不能说移动就一个节点问题就没办法高速了，希望还是能够改进。

**Comment by rainmaker86010** [comment]
我也是同样的问题，刚在Windows客户端提交了问题报告，两年的Pro用户，求解决，谢谢。

**Comment by orbancanon** [comment]
@rainmaker86010 你的邮箱 或者 邀请码是多少？好定位你的报告。

**Comment by rainmaker86010** [comment]
@orbancanon rainmaker86010@gmail.com

**Comment by rainmaker86010** [comment]
@orbancanon Pro账号的注册邮箱是is5151@sina.com，谢谢

**Comment by zhenyangleo** [comment]
@orbancanon  同样的网络，我用另一台电脑安装免费版的lantern，却有1500kbps的速度，同一个网络的专业版却只有200kbps不到。这就让我有点不懂了。。。。 这不是收费的线路没有免费的好嘛？同样是连接的日本服务器，算是彻底蒙圈了，求解啊！

**Comment by gaotong2055** [comment]
蓝灯坑人不浅啊，已改用小双加速了，速度66的

**Comment by zhenyangleo** [comment]
@orbancanon 今天测试了下，速度有所恢复，虽然没有达到之前的高速，但是基本可用了。说明官方还是有动作的。如果反映能够再速度些就更好了！谢谢！

**Comment by cheney789** [comment]
https://github.com/zhenyangleo
