### ISSUE TITLE
成功开通，欢迎使用我的邀请码

### ISSUE THREAD

**Issue by ed3rss** [getlantern/forum#2538]
输入我的邀请码 Y4W2SPX 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by linbenyi** [comment]
唉，老是卡在付款页面

**Comment by p3rcya** [comment]
@linbenyi 请给个截图。

请报告网络环境，访问时段。
**请在本帖提供email**, 并使用应用内发送日志功能报告问题。若无法自动提交，请手动上传，方法见https://github.com/getlantern/forum/issues/1840#issuecomment-260143243 。请及时提供，否则无法调查，谢谢！

**Comment by hiatuslee** [comment]
我的优惠码 # N2YPBN  获得三个月的蓝灯专业版！
