### ISSUE TITLE
win10 安装蓝灯后运后打不开受限的网站

### ISSUE THREAD

**Issue by tofindme** [getlantern/forum#254]
![image](https://cloud.githubusercontent.com/assets/5988375/16484174/7703f916-3eea-11e6-86cc-a8d82c7ca6bf.png)

任务栏里面是有蓝灯运行的

**Comment by xiaooo520** [comment]
昨天下午开始我的也不行了，昨天早上还用得好好的

**Comment by tofindme** [comment]
现在已经又可以了，好像不是太稳定哦
