### ISSUE TITLE
我的Mac和Win10两台电脑都在昨天翻不出墙了，Lantern正常运行却无法翻墙。

### ISSUE THREAD

**Issue by yueweijia** [getlantern/forum#2567]
好奇怪啊，前天还好好的。Lantern正常运行，也能正常显示主页。可是打不开任何境外网页，和没翻墙一样。

**Comment by p3rcya** [comment]
请问是专业版么？ 

请报告网络环境，访问时段。
**请在本帖提供email**, 并使用应用内发送日志功能报告问题。若无法自动提交，请手动上传，方法见https://github.com/getlantern/forum/issues/1840#issuecomment-260143243 。请及时提供，否则无法调查，谢谢！

**Comment by Wows233** [comment]
你设置了 管理系统代理 吗？勾上

**Comment by yueweijia** [comment]
免费版，不知为何用不了了。重装也不行，管理系统代理勾上了。是免费版的不能用了吗？

**Comment by Wows233** [comment]
我的能用啊，移动 江西

**Comment by yueweijia** [comment]
Wows233 你的是免费版还是专业版呢？

**Comment by Wows233** [comment]
免费版。。没钱买

**Comment by yueweijia** [comment]
Wows233 好吧，我已经上不去了。。。
