### ISSUE TITLE
更换了网络环境后，专业版速度很慢

### ISSUE THREAD

**Issue by mkdirmushroom** [getlantern/forum#2574]
- pc端可以访问墙外网站，但速度很慢
- 安卓端youtube直接无法加载，推特，脸书，ins访问不了，google可访问，但速度很慢
- 网络：江苏连云港移动
- 账号： 374841238@qq.com

**Comment by mkdirmushroom** [comment]
pc、安卓均已上传日志

**Comment by orbancanon** [comment]
@mkdirmushroom 从PC的日志看到你那里连我们最快的香港服务器经常断，于是连到比较拥堵的日本线路去了。国际网络出口一直很紧张，而且每个地方的情况不一样。我们会在新的地区增加服务器来减轻这个问题，但这往往也取于你本地网络到国际出口的质量。

安卓的日志没能传上来，但从现象看，我想问题是一样的。
