### ISSUE TITLE
备用地址下载失败

### ISSUE THREAD

**Issue by zzhhbyt1** [getlantern/forum#258]
https://s3.amazonaws.com/lantern/lantern-installer.exe

浏览器：Edge
返回页面：默认无法访问页面：
Hmm, we can't reach this page.

Try this
•Make sure you’ve got the right web address: https://s3.amazonaws.com
•Refresh the page
•Search for what you want

ISP：中国电信-河北

**Comment by orbancanon** [comment]
国内访问S3确实经常有问题

**Comment by zzhhbyt1** [comment]
唉。。。只能说今天凌晨下载安卓版的时候又好了。就是非常慢，还不如raw.githubcontent.com
。我还是把issue关了吧，既然链接本身OK的。

**Comment by p3rcya** [comment]
请使用主力地址下载
