### ISSUE TITLE
输入我的邀请码 X4VTP4 来获得三个月的蓝灯专业版！

### ISSUE THREAD

**Issue by Andy-GM-lau** [getlantern/forum#2580]
输入我的邀请码 X4VTP4 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by gtb-togerther** [comment]
搭个便车，楼主不介意吧？
输入我的邀请码 YHCZBU 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
