### ISSUE TITLE
升级3.6.3后, 免费版无法访问被屏蔽网站, 部分使用https的国内网站也有问题

### ISSUE THREAD

**Issue by echo1937** [getlantern/forum#2588]
环境: 中国移动
3.6.1 mac 专业版  OK
3.6.3 mac 专业版 OK
3.6.1 Windows台式机 专业版 OK
3.6.3 Windows笔记本 免费版 异常, 无法访问被屏蔽网站, 部分使用https的国内网站也有问题

已经发送日志，邮箱echo1937#foxmail.com

**Comment by p3rcya** [comment]
应该是免费服务器被墙导致的。 国内部分无法访问可能是因为误判被墙，所以自动代理了。

**Comment by chuweitao** [comment]
工作人员请正面回复我的问题#2575
