### ISSUE TITLE
使用lantern的时候网页版网易云音乐无法播放

### ISSUE THREAD

**Issue by KnightSch** [getlantern/forum#2596]
RT，退出lantern后可以正常播放，不然提示所在地区因为版权无法播放，网易云音乐不应该走代理的吧。
【上海 联通】

**Comment by itgoyo** [comment]
网易云网页版是http://而lantern启动之后会自动切换https://   我带我博客里边的网易云也出现了这个问题https://itgoyo.github.io

**Comment by p3rcya** [comment]
用firefox打开，不走代理就可以

**Comment by KnightSch** [comment]
@p3rcya 用chrome如何设置?目前我要用都是通过SwitchyOmega设置代理规则

**Comment by Gu2uMo** [comment]
试一试 ，不要选  “代理全部流量“”

**Comment by KnightSch** [comment]
目前使用终端版网易云音乐--musicbox, :)

**Comment by LongruiDong** [comment]
我没有选择“代理全部流量”，但win10网易云音乐客户端在lantern连接时还是无法联网。。 @Gu2uMo
