### ISSUE TITLE
未解决2，请删除安卓版本节点IP 47.91.143.76

### ISSUE THREAD

**Issue by chuweitao** [getlantern/forum#2606]
#2575

**Comment by chuweitao** [comment]
工作人员给我回复

**Comment by uqiu** [comment]
你那个帖子是18小时之前的,我看到官方人员10小时前还回复了别的帖子,但是没有回复你的.
是没看到还是故意的?
这种工作态度不行吧?
我的同样是这个问题,希望有人出来解释一下.

**Comment by chuweitao** [comment]
@uqiu 他们就这样的态度，反正付钱了就拉倒了

**Comment by uqiu** [comment]
@chuweitao  我是前天刚购买的一年服务,看这个样子,我今天已经邮件联系蓝灯的收款平台paymentwall处理退款事宜了

**Comment by uqiu** [comment]
@chuweitao 

`Hello, We've raised your concern to the appropriate department. Our specialists will be working with the website to process your refund request. We'll send you an update once we receive feedback. Thank you! Paymentwall Team `


这个是我收到的回信,等结果

**Comment by chuweitao** [comment]
@uqiu 我也去申请退款，互勉
