### ISSUE TITLE
突然蓝灯打不开了

### ISSUE THREAD

**Issue by Faynman** [getlantern/forum#2626]
[lantern.txt](https://github.com/getlantern/forum/files/812875/lantern.txt)
zip文件上传不了，我修改了后缀为txt就可以了

安装新版后还一样，弹出的蓝灯首页什么都不显示，一直打圈圈

**Comment by p3rcya** [comment]
**请在本帖提供email**, 并使用应用内发送日志功能报告问题。若无法自动提交，请手动上传，方法见https://github.com/getlantern/forum/issues/1840#issuecomment-260143243 。请及时提供，否则无法调查，谢谢！

**Comment by Faynman** [comment]
@p3rcya

**Comment by Faynman** [comment]
忘记放email了2721297306@qq.com， @p3rcya 麻烦帮忙解决下，好几天了。
[lantern.log.txt](https://github.com/getlantern/forum/files/815538/lantern.log.txt)
