### ISSUE TITLE
Lantern 收费了？github 上的lantern 是不是假的啊

### ISSUE THREAD

**Issue by Drakefrog** [getlantern/forum#263]
今天在 Github 上下载到了 lantern-installer-3.0.2，然后打开后弹出了升级专业版不限流量的字样。
然后到 lantern.org 上下到的版本是免费的。

请问这是为什么，是否 github 上的并非官方的，而是第三方开发者伪造的呢

**//版主编辑：各位请看[关于蓝灯3的说明](https://github.com/getlantern/forum/issues/352)**

**Comment by Drakefrog** [comment]
老实说付费我是原意的，但是希望官方给个更新文档能说明一下，要不然看到了并不敢付钱

**Comment by Shensven** [comment]
今天给新电脑装Lantern，在Github上下的3.0.2也出现了收费的字眼，而lantern.org上的版本依旧是老版本，难道github被盗号了？

**Comment by ylwszb** [comment]
蓝灯要收费了？？？
如果这样会失去很多用户。

**Comment by p3rcya** [comment]
是真的。

**Comment by p3rcya** [comment]
@Shensven 请问是什么杀毒软件？我们解决下

**Comment by p3rcya** [comment]
@ylwszb 免费版还是会有的

**Comment by Drakefrog** [comment]
说起来，lantern 的团队是隶属于谷歌的吗？

**Comment by p3rcya** [comment]
@Drakefrog 现在版本是3.0.0 https://github.com/getlantern/forum 你为什么是3.0.2的？ 最好有Chrome或者火狐下载

**Comment by Drakefrog** [comment]
我用 chrome 从 github 上 lantern 的首页下载的。
https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-3.0.2.dmg

**Comment by p3rcya** [comment]
@Drakefrog 对 这个版本是真正的

**Comment by p3rcya** [comment]
@Drakefrog 文档正在更新

**Comment by Shensven** [comment]
@p3rcya 我的桌面环境是这样的，win10 10586.420 家庭中文版 64bit，只装了一个腾讯电脑管家，一个猎豹安全浏览器，是猎豹安全浏览器自带的杀毒模块报的毒

**Comment by woodenwatcher** [comment]
3.0.2安装后会显示本月剩余的流量，这是否说明免费版会限制流量?

**Comment by xyuanmu** [comment]
为什么专业版用支付宝支付不成功？网页显示打勾，但账单里没有转账记录。

**Comment by p3rcya** [comment]
@xyuanmu 请报告手机和系统。并发送log

**Comment by orbancanon** [comment]
@xyuanmu 从后台没有查到失败的支付记录。网页显示打勾只是完成了初步的验证，并没有开始实际扣款的操作。打勾的界面消失之后，你有没有留意到什么提示信息（网页下方出现黑色提示框）？

**Comment by xyuanmu** [comment]
@p3rcya vivo x6d Android 5.1
@orbancanon 打勾界面消失后一片空白

**Comment by orbancanon** [comment]
@xyuanmu 买成功后会有一个醒目的提示界面。看起来像是支付的页面没有完成。重试一下应该就可以了。

@p3rcya @Rice321 也许可以录一个从下载到购买成功的视频，再配个音？回头各视频网站一转，岗岗的。

**Comment by Rice321** [comment]
@orbancanon  谢谢你的建议！我们会尽快推出文档供用户学习使用蓝灯！

**Comment by p3rcya** [comment]
这个建议好。我先做个图文教程

On Saturday, July 2, 2016, orbancanon <notifications@github.com> wrote:

> @xyuanmu <https://github.com/xyuanmu>
> 买成功后会有一个醒目的提示界面。看起来像是支付的页面没有完成。重试一下应该就可以了。
>
> @p3rcya <https://github.com/p3rcya> @Rice321 <https://github.com/Rice321>
> 也许可以录一个从下载到购买成功的视频，再配个音？回头各视频网站一转，岗岗的。
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/getlantern/forum/issues/263#issuecomment-230129092>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHjwqcTfmcnX57ZVGHblhHJKBABAYu9fks5qRwZKgaJpZM4JDmG->
> .
>


-- 
Percy Alpha(PGP
<https://pgp.mit.edu/pks/lookup?op=vindex&search=0xF30D100F7FE124AE>)

**Comment by xyuanmu** [comment]
成功了，要关闭蓝灯才可以

**Comment by lemonskkyt** [comment]
为什么买了专业版，只是页面变了，还是一样限速没法看YouTube

**Comment by Ageds** [comment]
免费版会限速。。。专业版就不会 但是2.2.3的版本还是可以用

**Comment by zhange98** [comment]
希望以后继续有免费版，每天有1G流量就够了看看图片和资料就够了，看视频的去买专业版。

**Comment by xyuanmu** [comment]
表示购买了专业版速度没上去啊，地区限制的视频依然看不了，能退不？

**Comment by SunXu231** [comment]
今天下载的3.0.3，在安卓手机上面使用，提示我本月还有547M流量，难道是以后要限制流量数量了吗

**Comment by p3rcya** [comment]
@xyuanmu 速度限制的问题现在已经解决了，你再试试

**Comment by chkjc10** [comment]
请问这个3.0版的是官方开发的吗，为什么我在官网没下到这个版本

**Comment by xyuanmu** [comment]
@p3rcya 是的，速度上来了，开发者辛苦了

**Comment by kangear** [comment]
@p3rcya 请问如何在chrome之外使用lantern，我已经购买了pro版本。我主要想在git中也能使用lantern。

**Comment by xyuanmu** [comment]
@kangear 端口是8787不是16823

**Comment by kangear** [comment]
@xyuanmu 
```
git config --global https.proxy http://127.0.0.1:8787
```

ok了，3q.

**Comment by kangear** [comment]
@p3rcya 你好，我前两天开Pro套餐后使用git下载了Android源码(30GiB左右)，现在几乎是不能正常使用了，Google也打不开了，很不稳定？我是不是使用的流量太大，触发了Lantern后台的什么机制导致不能再正常使用了呢？你能帮我解决一下吧？邮件地址：kangear@163.com

**Comment by p3rcya** [comment]
@kangear  现在还是不能使用么？

**Comment by p3rcya** [comment]
我整理了大家的问题一并回答。大家请看 https://github.com/getlantern/forum/issues/362

**Comment by chenzww** [comment]
不再打算用Lantern了。刚用Lantern才2个月作为辅助使用，第一个月时还行。之后就走下坡路，可用性和稳定性相当差。大概是收费版的出现让免费版臭哄哄的。免费版都这么让人寒心，连试用收费版的想法的灭了。再见！

**Comment by VRdeveloperA** [comment]
@all lantern 用于都是免费，任何收费用途的所谓lantern版本都是非lantern社区行为，而且个人行为，所有lantern版本只有在官方网站www.getlantern.org/上发布。
见过VPN收费的，但没见过通过lantern的名义来收费，太不要脸了@p3rcya.

**Comment by panzer1313208** [comment]
免费的时候不知道感恩，收费了就开始嘲讽？

**Comment by xyuanmu** [comment]
在付费工具中，一年180无限流量真心很不错了，6月份的试用版里貌似27元就可以购买专业版，但我不会共享出来，我自己也是第一时间180购买的一年。
用蓝灯快一年，不过之前主要流量都是用gae类翻墙工具，没怎么用，因为蓝灯免费不想增加服务器负担而且在电信网络下速度不理想。gae类工具IP是个令人头疼的问题，花很多时间去找，筛选，还写了一些小工具找IP，为了能更流畅访问互联网，看视频，也累了，想买个VPN一直没相中好的。之后移动光纤覆盖了，更换后gae类速度确实上来，但IP段依然不稳定，要时常更换，而蓝灯速度却很好，就开始蓝灯作为主力，后来发现有测试版推出付费服务，不过速度不是很理想就用回2.2.4，直到6月底速度开始出现问题2.2.5、3.0.2版都没速度，只有0621版本速度非常好觉得应该是限速就购买了专业版，速度到现在一直都很理想，希望能继续保持，也会一直支持蓝灯！

**Comment by p3rcya** [comment]
@VRdeveloperA 请看精华帖，蓝灯3是官方发布的。我不会删帖，但是你下次再发这种帖子我就ban你帐号了

**Comment by p3rcya** [comment]
@xyuanmu 感谢支持！

**Comment by panzer1313208** [comment]
@p3rcya 这个论坛里有几个喷子，希望你别被他们误导啊。

**Comment by jamesbankkkk** [comment]
我还是喜欢免费的

**Comment by imengchaoemcc** [comment]
翻墙重度患者表示看到lantern收费立马就付费了，不过，并没有感觉速度上去，还有很烦人的是，google总让我输入验证码

**Comment by imyellow** [comment]
更新一下官网下面的最新版本号这么难？

**Comment by 00317** [comment]
卡巴斯基会报危险，然后自动处理，就不能用了，请关注一下。

**Comment by qizi297** [comment]
我也喜欢免费的，毕竟用的是海外用户的电脑当翻墙节点的，大家可以下个旧版的lantern试试：https://yunpan.cn/c6ypKQ4dMNInN  访问密码 1fe1

**Comment by circking** [comment]
# **使用最新邀请码 Y74KBB  ，可额外增加一至三月的蓝灯专业版会员时间！**

**Comment by EvilNumber** [comment]
可以詳細講下專業版使用的技術嗎？例如有多少個國家服務器，多少條線，但可以確定確實很具性價比，相比雲梯VPN，搬瓦工VPN

**Comment by Huang-Libo** [comment]
lantern估计被几个国人买了。然后变成收费模式开始敛财。

**Comment by p3rcya** [comment]
@Huang-Libo 蓝灯是美国公司。你去这里看看 https://github.com/getlantern/lantern/issues 英文的issue多还是中文issue多就知道了

**Comment by HBqizi297** [comment]
#1287

**Comment by HBqizi297** [comment]
#1287

**Comment by TeWuJia** [comment]
什么时候推出iOS端lantern的app啊,等了好久了,现在已付费专业版

**Comment by p3rcya** [comment]
年内出。

**Comment by mrguo2012** [comment]
付费版支持 BT 客户端的代理吗？

**Comment by etins** [comment]
付费之后的网速如何?

**Comment by jihaixiao8** [comment]
我就想知道付费后网速如何，可以的话我立刻买

**Comment by mancafe** [comment]
之前不是说一直都是免费的吗？为了对抗政府的封锁的呀？什么情况啊？！！！！！
