### ISSUE TITLE
安卓版上动态授权码看不到，找回专业版账号也一直正在请求

### ISSUE THREAD

**Issue by Mactarvish** [getlantern/forum#2641]
我在pc买的pro想要授权给安卓，等了两个小时了，两种方法都不行

**Comment by Mactarvish** [comment]
另外手机上蓝灯是最新版3.6.3

**Comment by benny27521** [comment]
我也遇到了同样的问题，重新安装后只能使用免费版了

**Comment by Mactarvish** [comment]
坑爹呢

**Comment by benny27521** [comment]
昨天发生的，到今天依然如此

**Comment by benny27521** [comment]
@Mactarvish 解决了吗？

**Comment by qizi297** [comment]
对对，我也是

**Comment by p3rcya** [comment]
请报告网络环境，访问时段。
**请在本帖提供email**, 并使用应用内发送日志功能报告问题。若无法自动提交，请手动上传，方法见
https://github.com/getlantern/forum/issues/1840#issuecomment-260143243
。请及时提供，否则无法调查，谢谢！

**Comment by Mactarvish** [comment]
@pyrcya 451143003@qq.com

**Comment by Mactarvish** [comment]
@p3rcya 451143003@qq.com

**Comment by benny27521** [comment]
@p3rcya d.min@163.com，未root安卓手机，无法提供日志信息

**Comment by benny27521** [comment]
是不是验证服务down了？

**Comment by jevons-du** [comment]
@p3rcya 
同上

**Comment by youyuan2046** [comment]
1017301253@qq.com 同上

**Comment by benny27521** [comment]
已经解决了，谢谢@p3rcya
