### ISSUE TITLE
最近lantern 邀请码 

### ISSUE THREAD

**Issue by ouyanglee** [getlantern/forum#2652]
输入我的邀请码 YJ2SBBN 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by stephen666** [comment]
# 蓝灯lantern最新邀请码 Y2947HH 永久有效！获取三个月免费！

## 请输入我的蓝灯lantern邀请码 Y2947HH 来获得三个月免费的蓝灯专业版！使用后请留下你的邀请码，我也会使用你的邀请码续费的！

![lantern referall code](https://user-images.githubusercontent.com/11013738/28992867-903ae68e-79da-11e7-8eed-5fa48b8bf7f1.png)
