### ISSUE TITLE
请解除禁言专业版用户chuweitao@126.com

### ISSUE THREAD

**Issue by chuweitao2** [getlantern/forum#2658]
之前刷帖是我不对，但是也恳请你们不要随便禁言一个2年专业版用户chuweitao@126.com，我们付费，反馈问题，蓝灯才能做的更好，不是吗？
另外，你们说好的上周内解决，出新版，给个答复
#2575 
#2657

**Comment by p3rcya** [comment]
现在已经解除了禁言。你报告的问题我们早就在调查修复了，请等待新版发布。

**Comment by p3rcya** [comment]
请不要用小号刷版。否则的话，两个账号都会禁言
