### ISSUE TITLE
如何让我的命令行工具翻墙

### ISSUE THREAD

**Issue by johnhi2015** [getlantern/forum#2661]
用MAC的同学经常会通过git、brew安装程序。 这类通过命令行的工具怎么能使用翻墙呢？试了全局， 也没用。

**Comment by paperbag** [comment]
For example
```
git config --global http.proxy 127.0.0.1:1080 
```
```
git config --global --unset http.proxy
```

**Comment by chuweitao** [comment]
别想了，没戏

**Comment by paperbag** [comment]
@chuweitao 如果你不清楚就请不要秀你的无知，issue tracker 不是百度贴吧，谢谢。

**Comment by xy2401** [comment]
还真可以啊？更新maven 更新github 需要挂vpn，如何用蓝灯还真不知道。
http://localhost:52581 我一开始还以为是这个地址的http代理

**Comment by xy2401** [comment]
@paperbag  两个端口试了一下都不行啊
': Received HTTP code 404 from proxy after CONNECT

**Comment by johnhi2015** [comment]
@paperbag Thanks

找到更好的方法了。
将以下代码添加到~/.bash_profile里面
`alias proxy_http='http_proxy=http://127.0.0.1:49576 https_proxy=http://127.0.0.1:49576'`
然后
`source ~/.bash_profile`

在想翻墙的命令前，敲上
`proxy_http` 
就可以了。 希望能帮到大家。

**Comment by luxi78** [comment]
蓝灯配合[proxychains](https://github.com/rofl0r/proxychains-ng)使用，基本上做到终端下透明翻墙。
