### ISSUE TITLE
为什么我的使用日期少了两个月？

### ISSUE THREAD

**Issue by 852kop** [getlantern/forum#2664]
购买当天显示到期时间是:2019年四月七号，然后使用邀请码增加了一个月，为什么现在变成了2019年3月十号到期？ 我的邮箱是:852479011@qq.com

**Comment by 852kop** [comment]
还有手机端为什么总是用着用着就不能翻墙了，只能手机重启才能恢复正常

**Comment by joesis** [comment]
@852kop 后台显示你是10月3号到期，不是3月10号。界面显示错乱了？能否截个图看看？

手机用着用着不能翻墙的问题正在解决。
