### ISSUE TITLE
lantern导致Uplay无法连接

### ISSUE THREAD

**Issue by EdwardAutumn** [getlantern/forum#2670]
@p3rcya 
今天发现的这个问题，比较烦，求解决

**Comment by orbancanon** [comment]
@EdwardAutumn 所以Uplay连的都是国内还是国外？如果全是国内的话，即将发布的一个更新可能会对此有帮助。

**Comment by EdwardAutumn** [comment]
@orbancanon 都是国外的，美国，日本，加拿大。

**Comment by orbancanon** [comment]
@EdwardAutumn 这个可能要发一下日志来看才知道怎么回事。另外什么情况下能够连接？不开Lantern也不开其它翻墙软件，或者把Lantern的“设置系统代理”选项勾掉，这两种情况下都能连么？

**Comment by EdwardAutumn** [comment]
@orbancanon 把设置系统代理关掉才行。

[lantern.txt](https://github.com/getlantern/forum/files/829717/lantern.txt)

**Comment by orbancanon** [comment]
@EdwardAutumn 你最后一次启动之后没有试过连uplay吧？从日志里看不到相关的访问记录。

**Comment by EdwardAutumn** [comment]
@orbancanon 
我每次为了方便你们看日志会先删除以前的日志再重现问题。我先关掉蓝灯删了以前的日志，再打开蓝灯，开启Upaly客户端，然后上传的日志。然后客户端显示的问题是和断线了一样,如果日志里没有会不会是端口冲突了，反正我也没时间去看，虽然其实影响不大，因为我是买了网易UU玩上面的游戏的，只是蓝灯关来关去麻烦。
![qq 20170310223114](https://cloud.githubusercontent.com/assets/19833520/23798852/55de0092-05e1-11e7-87c4-c9e5352bfa90.png)

[lantern.txt](https://github.com/getlantern/forum/files/834174/lantern.txt)

**Comment by orbancanon** [comment]
我看到有连接https://public-ubiservices.ubi.com和https://lb-upc-dmx.ubisoft.com这些相关网站的记录，还都挺正常的，不过也有客户端强制把连接关闭的情况。具体为何关闭跟这个应用本身有关，从Lantern这边就看不出来了。
