### ISSUE TITLE
安卓版本不稳定的问题正在解决

### ISSUE THREAD

**Issue by p3rcya** [getlantern/forum#2671]
有部分用户反馈安卓版本不如PC版本稳定。我们正在解决这个问题，预计本月出新版解决这个问题。

**Comment by jevons-du** [comment]
支持！

**Comment by chuweitao** [comment]
我看到了希望的曙光

**Comment by benny27521** [comment]
哇……太棒了

**Comment by sodabluesff** [comment]
什么时候可以手动选择节点？ 香港的阿里云节点慢的像老水牛都快挂掉了。 试用免费版默认连接日本的vultr节点， 掏钱升级立刻就换阿里云的垃圾节点！ 这是欺骗用户购买吗？ 我要退款！

**Comment by gbmeco** [comment]
能加快IOS版的开发吗？

**Comment by mkdirmushroom** [comment]
哈哈，终于要解决安卓端的问题啦，蓝灯团队幸苦了！

**Comment by Griffin1** [comment]
我是支持的！

**Comment by benny27521** [comment]
经测试，问题得到了解决，谢谢蓝灯团队！

**Comment by p3rcya** [comment]
已经修复 https://github.com/getlantern/forum/issues/2699
