### ISSUE TITLE
支付宝购买蓝灯专业版邮箱无法找回的问题

### ISSUE THREAD

**Issue by MrErHu** [getlantern/forum#2672]
购买了一年的蓝灯专业版会员，使用支付宝支付的，默认使用的是支付宝ID的邮箱，但该邮箱已经无法找回，这种情况怎么办？

**Comment by chuweitao** [comment]
努力找回邮箱，不然，凉拌

**Comment by MrErHu** [comment]
看来官方没有回复了，以后不使用蓝灯了，转SS

**Comment by bluesodi** [comment]
购买成功后，会有邮件提醒吗？我支付完怎么还是免费版本的。求告知
