### ISSUE TITLE
请问如何退款？

### ISSUE THREAD

**Issue by sodabluesff** [getlantern/forum#2675]
试用免费版的时候给分配日本Vultr高速节点， 等你付了钱， 立刻切换到其它垃圾节点，花钱买了个不能用的玩意，还不如自己买vps。  lantern就是这么欺骗用户花钱购买的。

**Comment by sodabluesff** [comment]
奉劝那些准备花钱的新人们，不要觉得免费版速度快你就买专业版，那是故意给你分配高速节点诱骗你花钱呢！ 等你一付费，你会发现还不如免费版的。

**Comment by p3rcya** [comment]
请报告网络环境，访问时段。
**请在本帖提供email**, 并使用应用内发送日志功能报告问题。若无法自动提交，请手动上传，方法见https://github.com/getlantern/forum/issues/1840#issuecomment-260143243 。请及时提供，否则无法调查，谢谢！    

你的问题是服务器选择算法的问题。请按照上面报告环境帮助我们调整算法。

**Comment by p3rcya** [comment]
@sodabluesff 请不要刷版谩骂，否则禁言。

**Comment by power2262** [comment]
蓝灯的速度绝对比购买的VPN要强多少倍。

**Comment by chuweitao** [comment]
@sodabluesff 请不要刷版谩骂，否则禁言。

**Comment by Runing2015** [comment]
我的也是，每天晚上9点以后就好卡，使用了反馈功能后，速度很快变好了，大概十多分钟又变差了！可气

**Comment by Runing2015** [comment]
我的也是，每天晚上9点以后就好卡，使用了反馈功能后，速度很快变好了，大概十多分钟又变差了！可气

**Comment by sodabluesff** [comment]
@p3rcya     安卓，没有root。   

网络环境： 中国移动光纤宽带（河南移动）

还有我发现Lantern根本不是随机分配节点；而是固定分配香港阿里云47.90.60.97这个垃圾节点， 导致google、youtube打不开或者缓慢。  而且不管我断开重连多少次，永远是固定的阿里云节点， 这就是你所说的算法？ 我网页都打不开了你还给我分配这个节点？   

还有， 当我切换回免费版的时候，同样的网络环境， 给我分配的却是日本Vultr节点，速度很快。 你怎么解释这个现象？？ 这是算法还是故意为之？

**Comment by sodabluesff** [comment]
@p3rcya  请就所谓的“算法”问题给出合理的解释， 如不能还望办理退款， 谢谢！

**Comment by p3rcya** [comment]
@sodabluesff 请在本帖提供email, 并使用应用内发送日志功能报告问题。

**Comment by sodabluesff** [comment]
@p3rcya 请提供手动选择节点的功能， 自动分配的节点根本不能用！

**Comment by p3rcya** [comment]
这个是算法问题，请提供日志。如果你不提供，我们没发给你解决。

**Comment by sodabluesff** [comment]
@p3rcya    三星s7 edge， 安卓7.0系统。 没有root，   网络环境中国移动宽带。   


请告诉我手机没Root如何上传日志。

**Comment by p3rcya** [comment]
请仔细阅读我3楼的回复

**Comment by sodabluesff** [comment]
你3楼的回复是没Root不能上传日志。

**Comment by sodabluesff** [comment]
算了， 果断卸载Lantern。 问题无人解决，退款更无望。

**Comment by p3rcya** [comment]
"并使用应用内发送日志功能报告问题"。 没有日志没有办法处理
