### ISSUE TITLE
麻烦管理员们更改账户邮箱绑定，谢谢你们

### ISSUE THREAD

**Issue by 852kop** [getlantern/forum#2678]
请将852479011@qq.com更改为shuaihuasong@gmail.com， 是这样子的，这号我打算转卖给别人，然后我想请问下，将绑定的邮箱修改成买方的邮箱后，接下来买方该怎么做可以使他的设备变成专业版？感谢回答！

**Comment by 852kop** [comment]
比我晚提问的问题都得到了回答，为什么就不回答我的问题？

**Comment by 852kop** [comment]
对方在催我啦

**Comment by chuweitao** [comment]
官方禁止买卖，不把你禁言算好的了。
建议 你把你的邮箱卖给他呗

**Comment by 852kop** [comment]
管理员大哥我知道你在线的，为什么不回答我的问题啊，
