### ISSUE TITLE
【置顶】蓝灯现在是正式版了吧！早期小白鼠用户承诺赠送2月时长何时落实！？

### ISSUE THREAD

**Issue by merlinfong** [getlantern/forum#2682]
关于这个问题，这是我第二次提出来，官方一直没有个说法。话说蓝灯现在也该是正式版了，官方承诺的2月时长补偿什么时候落实！！？？

**Comment by merlinfong** [comment]
[https://github.com/getlantern/forum/issues/2460](url) 这个帖子之前发过了！

**Comment by merlinfong** [comment]
https://github.com/getlantern/forum/issues/2460

这是我之前发过的了。

**Comment by p3rcya** [comment]
在账号过期前会赠送的。

**Comment by merlinfong** [comment]
@p3rcya 你意思是账号过期前 系统自动续期两个月？？

**Comment by merlinfong** [comment]
其实你们很多措施在这个论坛里说说就行，你们除了技术大牛的身份外，对运营简直是菜鸟。你们很多所谓官方措施的措辞中，措辞不严谨，远没有你们自己写代码严谨。留各种Bug的空间让你们在后期自圆其说！你说什么时候送，都是你说的！你之前的说法就是，蓝灯推出正式版之后，就赠送两个月！现在又另外一种说辞，账号过期前赠送！你看看之前的记录，你本人是不是这样说！包括你们现在推出的代理，背后隐藏各种售后的BUG，我们当代理，如果我们自己的用户提出各种技术问题，你们有人来管吗？真心拜托你们提升运营能力！别再当菜鸟好不好？！@p3rcya

**Comment by merlinfong** [comment]
补充一下，当代理绝不会像在你提供的网站注册一下就这么简单。背后还有法律问题，应该做成合同形式，如果产生法律责任，后果怎么办，你是知道的！

**Comment by chuweitao** [comment]
2个月，你就这么热爱蓝灯吗？我到期直接卸载

**Comment by p3rcya** [comment]
过期前后台会自动延期的

**Comment by merlinfong** [comment]
@p3rcya 为什么关闭！！！！

**Comment by p3rcya** [comment]
因为你的问题已经解决了，告诉你过期前后台会自动延期的。
