### ISSUE TITLE
【问题根本没解决】今天如果蓝灯就是正式版，就得补偿所有用户！

### ISSUE THREAD

**Issue by merlinfong** [getlantern/forum#2684]
先回答我这个问题！蓝灯今天是不是正式版！？

**Comment by merlinfong** [comment]
merlinfong commented 33 minutes ago
关于这个问题，这是我第二次提出来，官方一直没有个说法。话说蓝灯现在也该是正式版了，官方承诺的2月时长补偿什么时候落实！！？？
@merlinfong

merlinfong commented 30 minutes ago
#2460

这是我之前发过的了。
@p3rcya
Contributor
p3rcya commented 29 minutes ago • edited
在账号过期前会赠送的。
@merlinfong

merlinfong commented 27 minutes ago
@p3rcya 你意思是账号过期前 系统自动续期两个月？？
@merlinfong

merlinfong commented 21 minutes ago
其实你们很多措施在这个论坛里说说就行，你们除了技术大牛的身份外，对运营简直是菜鸟。你们很多所谓官方措施的措辞中，措辞不严谨，远没有你们自己写代码严谨。留各种Bug的空间让你们在后期自圆其说！你说什么时候送，都是你说的！你之前的说法就是，蓝灯推出正式版之后，就赠送两个月！现在又另外一种说辞，账号过期前赠送！你看看之前的记录，你本人是不是这样说！包括你们现在推出的代理，背后隐藏各种售后的BUG，我们当代理，如果我们自己的用户提出各种技术问题，你们有人来管吗？真心拜托你们提升运营能力！别再当菜鸟好不好？！@p3rcya
@merlinfong

merlinfong commented 18 minutes ago
补充一下，当代理绝不会像在你提供的网站注册一下就这么简单。背后还有法律问题，应该做成合同形式，如果产生法律责任，后果怎么办，你是知道的！
@chuweitao

chuweitao commented 7 minutes ago
2个月，你就这么热爱蓝灯吗？我到期直接卸载
@p3rcya
Contributor
p3rcya commented 2 minutes ago
过期前后台会自动延期的
@p3rcya p3rcya closed this 2 minutes ago
@merlinfong

merlinfong commented just now
@p3rcya 为什么关闭！！！！
 @p3rcya
 Contributor
p3rcya commented 4 minutes ago
请不要刷版
 @p3rcya p3rcya closed this 4 minutes ago
@merlinfong
     
merlinfong commented 4 minutes ago
我没有刷版！你得解释！
 @merlinfong
     
merlinfong commented a minute ago
@p3rcya p3rcya 问题根本没有解决！你说过蓝灯成为正式版之后就得补偿！现在为什么选择自动延期？！因为你今天说了，也只是把问题延长 直至用户忘记而已！

**Comment by p3rcya** [comment]
最后警告一次。 我已经说过了，测试用户的时间会自动延长。
