### ISSUE TITLE
烦请管理员们更改账户邮箱绑定，谢谢你们

### ISSUE THREAD

**Issue by 852kop** [getlantern/forum#2686]
请将852479011@qq.com更改为shuaihuasong@gmail.com， 是这样子的，这号我打算转卖给别人，然后我想请问下，将绑定的邮箱修改成买方的邮箱后，接下来买方该怎么做可以使他的设备变成专业版？感谢回答！

**Comment by chuweitao** [comment]
禁止线下交易

**Comment by 852kop** [comment]
@chuweitao 
为什么啊？不给退款就算了，为什么还不准转卖给别人。

**Comment by 852kop** [comment]
@p3rcya
