### ISSUE TITLE
两个星期了，专业版蓝灯弹出的页面还是上不了

### ISSUE THREAD

**Issue by Faynman** [getlantern/forum#2688]
[lantern.txt](https://github.com/getlantern/forum/files/832851/lantern.txt)
我在家里可以用，手机可以用公司电脑不能用。出问题前一直好好的，前两个星期突然打不开了。打开蓝灯都会弹出页面，然后自动登录专业版，弹出的页面一直空白，估计连不上服务器。难道是我的电脑问题吗？给点建议吧。PS:网上改hosts可以用

**Comment by orbancanon** [comment]
@Faynman 能否删一下C:\Users\Faynman\AppData\Roaming\Lantern\settings.yaml 这个文件再试？同时也请把删之前的这个文件发到orbancanon@gmail.com 我看一下。

**Comment by Faynman** [comment]
@orbancanon 删除了还是不行，你研究出什么方法没？

**Comment by orbancanon** [comment]
@Faynman 看起来你在公司用的虚拟机对吧？你的帐号是多少告诉我一下？

**Comment by stevenchengcn** [comment]
我家里的台式机都不能用，手机和笔记本都可以用

**Comment by fancier1005** [comment]
你好！我的电脑拿到公司可以翻墙使用，但是回家了不能连接。我买的两年收费版！提示信息如下：
 “无法访问此网站

localhost 拒绝了我们的连接请求。
请试试以下办法：
检查网络连接
检查代理服务器和防火墙
ERR_CONNECTION_REFUSED”

**Comment by fancier1005** [comment]
忘记说了我是MAC系统

**Comment by p3rcya** [comment]
@fancier1005 那就说明是你家庭网络设置的问题

**Comment by Faynman** [comment]
@orbancanon 在公司的电脑win10系统，装了虚拟机ubuntu 14.05, 虚拟机里面可以使用。但是win10系统就不可以。最近还改host和使用星源浏览器勉强折腾着用。

**Comment by Faynman** [comment]
@p3rcya
