### ISSUE TITLE
烦请管理员们更改账户邮箱绑定，谢谢你们

### ISSUE THREAD

**Issue by 852kop** [getlantern/forum#2691]
请将852479011@qq.com更改为shuaihuasong@gmail.com， 是这样子的，这号我打算转卖给别人，然后我想请问下，将绑定的邮箱修改成买方的邮箱后，接下来买方该怎么做可以使他的设备变成专业版？感谢回答！
@p3rcya
我哪儿做错了？你倒是说啊，为什么就是不肯回答我的问题，这是闹哪样啊？

**Comment by 852kop** [comment]
@p3rcya   大哥拜托了，请帮帮忙

**Comment by p3rcya** [comment]
这个是公司的TOS，我个人也没办法。请不要重复开贴，谢谢

**Comment by 852kop** [comment]
@p3rcya  你骗人，我在历史记录里发现你替别人修改过邮箱了
![1](https://cloud.githubusercontent.com/assets/26253416/23787296/04d728a4-0537-11e7-865a-f6fa733aa497.png)
![2](https://cloud.githubusercontent.com/assets/26253416/23787340/3633c3ee-0537-11e7-868d-0b1d407d3d7d.png)
![3](https://cloud.githubusercontent.com/assets/26253416/23787398/74292dba-0537-11e7-8508-1ac19e30e563.png)

**Comment by p3rcya** [comment]
我说禁止贩卖零售账号是公司政策。用户无法登录当然是要解决的。

**Comment by nolongerhesitate** [comment]
lantern ，有没有智能分流的功能啊？ 还是全局代理呢？
