### ISSUE TITLE
[紧急]求助求助求助！！！

### ISSUE THREAD

**Issue by matt586** [getlantern/forum#2695]
我绑定蓝灯的邮箱被盗，因为邮箱被盗所以我无法找回账号，所以请求将绑定的852479011@qq.com替换成601485316@qq.com

**Comment by matt586** [comment]
我的购买记录
![s70311-072859](https://cloud.githubusercontent.com/assets/26323099/23819271/9285b14c-05c9-11e7-8f17-58c43b88ed5c.jpg)

**Comment by p3rcya** [comment]
邮箱是唯一购买凭证。请问腾讯找回邮箱

**Comment by matt586** [comment]
@p3rcya
我一没设置密保，二没绑定手机，你叫我怎么找回邮箱？
