### ISSUE TITLE
@p3rcya 我一没设置密保，二没绑定手机，三账号里没有好友，你叫我怎么找回邮箱

### ISSUE THREAD

**Issue by matt586** [getlantern/forum#2696]
这是我购买当天截图
![s70311-094732](https://cloud.githubusercontent.com/assets/26323099/23819421/adb39d10-05cb-11e7-9002-df25b70d3a77.jpg)

**Comment by matt586** [comment]
替换邮箱对你说来只是举手之劳，却能提高用户的的印象，何乐而不为呢？

**Comment by matt586** [comment]
用户有困难，官方应该给予帮助，而不是让用户自行解决

**Comment by p3rcya** [comment]
邮箱是唯一登陆凭证。直接修改邮箱，万一你是盗了这个图片，怎么说？ 为了用户安全，不能这样修改。
