### ISSUE TITLE
make lantern error 

### ISSUE THREAD

**Issue by wangzhenhui1991** [getlantern/forum#27]
sequin@0.1.0 node_modules/faye/node_modules/csprng/node_modules/sequin -> node_modules/sequin
typedarray@0.0.6 node_modules/faye/node_modules/concat-stream/node_modules/typedarray -> node_modules/typedarray
npm WARN lantern-ui@0.0.10-0 license should be a valid SPDX license expression
[08:24:02] Using gulpfile /home/wzh/git/lantern/lantern-ui/gulpfile.js
[08:24:02] Starting 'clean'...
[08:24:02] Starting 'usemin'...
[08:24:02] Starting 'copy'...
[08:24:02] Finished 'copy' after 11 ms
[08:24:02] Finished 'clean' after 131 ms
[08:24:03] Finished 'usemin' after 1.48 s
[08:24:03] Starting 'build'...
[08:24:03] Finished 'build' after 10 μs
/home/wzh/git/lantern
Building development lantern
*\* VERSION was not set, using default version. This is OK while in development.
Build tags: 
Extra ldflags: 
# github.com/getlantern/systray

/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64/libgdk-3.so: undefined reference to `cairo_surface_set_device_scale'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64/libgtk-3.so: undefined reference to`cairo_surface_get_device_scale'
collect2: error: ld returned 1 exit status
Makefile:356: recipe for target 'lantern' failed
make: **\* [lantern] Error 2

**Comment by bnb7xi** [comment]
after install cairo -> zypper install cairo-devel

occured other problem!
# make lantern
typedarray@0.0.6 node_modules/typedarray -> node_modules/faye/node_modules/concat-stream/node_modules/typedarray
sequin@0.1.0 node_modules/sequin -> node_modules/faye/node_modules/csprng/node_modules/sequin
npm WARN lantern-ui@0.0.10-0 license should be a valid SPDX license expression
[10:44:50] Using gulpfile /home/wzh/git/lantern/lantern-ui/gulpfile.js
[10:44:50] Starting 'clean'...
[10:44:50] Starting 'usemin'...
[10:44:50] Starting 'copy'...
[10:44:50] Finished 'copy' after 9.54 ms
[10:44:50] Finished 'clean' after 132 ms
[10:44:52] Finished 'usemin' after 1.48 s
[10:44:52] Starting 'build'...
[10:44:52] Finished 'build' after 8.58 μs
/home/wzh/git/lantern
Building development lantern
** VERSION was not set, using default version. This is OK while in development.
Build tags: 
Extra ldflags: 
# github.com/getlantern/flashlight/main
usage: 6l [options] main.6
  -1    use alternate profiling code
  -8    assume 64-bit addresses
  -B info
        define ELF NT_GNU_BUILD_ID note
  -C    check Go calls to C code
  -D addr
        data address
  -E sym
        entry symbol
  -I interp
        set ELF interp
  -L dir
        add dir to library path
  -H head
        header type
  -K    add stack underflow checks
  -O    print pc-line tables
  -Q    debug byte-register code gen
  -R rnd
        address rounding
  -S    check type signatures
  -T addr
        text address
  -V    print version and exit
  -W    disassemble input
  -X name value
        define string data
  -Z    clear stack frame on entry
  -a    disassemble output
  -c    dump call graph
  -d    disable dynamic executable
  -extld ld
        linker to run in external mode
  -extldflags ldflags
        flags for external linker
  -f    ignore version mismatch
  -g    disable go package data checks
  -installsuffix suffix
        pkg directory suffix
  -k sym
        set field tracking symbol
  -linkmode mode
        set link mode (internal, external, auto)
  -n    dump symbol table
  -o outfile
        set output file
  -r dir1:dir2:...
        set ELF dynamic linker search path
  -race
        enable race detector
  -s    disable symbol table
  -shared
        generate shared object (implies -linkmode external)
  -tmpdir dir
        leave temporary files in this directory
  -u    reject unsafe packages
  -v    print link trace
  -w    disable DWARF generation
Makefile:356: recipe for target 'lantern' failed
make: *** [lantern] Error 2
