### ISSUE TITLE
【伸张正义】蓝灯权益受害用户的请看这里！

### ISSUE THREAD

**Issue by LMAO2** [getlantern/forum#2717]
各位被蓝灯售后服务害惨的亲们，让我们联合起来一起向其维权！退款问题、公测补偿等等问题悬而未决的，大家请在这里畅所欲言，维护自己合法权益！！﻿请加入Google+ Community：https://plus.google.com/communities/117160121257336662530

**Comment by wangzhenhui1991** [comment]
hahaha.

**Comment by wangzhenhui1991** [comment]
怎么都这么逗.
