### ISSUE TITLE
专业版授权问题

### ISSUE THREAD

**Issue by chenluwei** [getlantern/forum#2722]
无法授权给其他设备了，动态码输入后另外一台没办法升级到专业版

**Comment by stevenchengcn** [comment]
同问，还有，出了问题，找不到客服，这就是客服吗？有没有人专门回答问题？

**Comment by chenluwei** [comment]
这么多天了，一个回复都没有，太失望了

**Comment by p3rcya** [comment]
**请在本帖提供email**, 并使用应用内发送日志功能报告问题。若无法自动提交，请手动上传，方法见https://github.com/getlantern/forum/issues/1840#issuecomment-260143243 。请及时提供，否则无法调查，谢谢！

**Comment by chenluwei** [comment]
[Uploading lantern.txt…]()
[Uploading lantern.txt…]()
