### ISSUE TITLE
使用蓝灯同时使用其他VPN会冲突吗？

### ISSUE THREAD

**Issue by danperor** [getlantern/forum#2733]
公司办公，使用了自己的VPN，发现安装上lantern，貌似VPN拨号不成功，是lantern修改vpn设置导致的吗？有没官方的一个解答？

**Comment by chuweitao** [comment]
蓝灯不会修改vpn设置

**Comment by myvipbackup2** [comment]
先开影梭再开蓝灯，蓝灯会把影梭挤掉的，vpn只能同时用一个吧
输入我的邀请码 Y4KQ358 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
