### ISSUE TITLE
购买专业版无法使用 1970年到期

### ISSUE THREAD

**Issue by qqcruise** [getlantern/forum#2774]
登陆lanter 不显示专业版，通过找回账号后，显示1970年到期，无法使用，email   qqcruise@163.com

![Uploading QQ截图20170323120415.jpg…

**Comment by p3rcya** [comment]
并没有购买成功的记录。请上传交易凭证

**Comment by Selladore** [comment]
我也有同样的问题，我的帐号是：ywarlock@gmail.com
今天（刚刚）通过支付宝购买两年，但是无法登录，或者登录之后，几分钟内重新退回到免费版。也无法授权其他的设备。登陆后，账户管理内显示到期时间1970年。

**Comment by LeinLiu** [comment]
我尚未购买成功 在支付宝支付时一直在载入 退出后通过找回账号 也变成1970年到期

**Comment by Selladore** [comment]
我的购买后途径和 @LeinLiu  。在 localhost 的支付宝页面一直转圈。我没有等到它刷新完成，直接重新启动，使用找回帐号登录，到期时间是1970年。刷新蓝灯的网页界面后，又会退回到免费版。

**Comment by Selladore** [comment]
我的邮箱刚刚收到一份paymentwall付款收据，收据提到是蓝灯的付款凭证。所以我重新试着登录蓝灯，登录成功了。
我的问题已经解决。
