### ISSUE TITLE
Lantern在mac上购买了pro后受限速

### ISSUE THREAD

**Issue by helloworldhj** [getlantern/forum#278]
Lantern在mac上购买了pro后受限速，换了台Windows添加专业版后不受限速，在mac上尝试重启，删除lantern相关的配置文件后重新安装配置都无法解决。

**Comment by jyufeng** [comment]
偶的也是这个问题，怎么不见开发人员的回复？

**Comment by woaixiangbao** [comment]
我的也是很慢，怎么办

**Comment by p3rcya** [comment]
我们正在解决，也请大家上传下log，谢谢

**Comment by helloworldhj** [comment]
[lantern.txt](https://github.com/getlantern/forum/files/345192/lantern.txt)
这是我的log文件

**Comment by helloworldhj** [comment]
提一点 我第一次使用Lantern是在mac上，购买pro也是在mac上 问题也是出在mac上 之后我在windows和android上安装使用都没有限速的问题，而且每次在mac上开启lantern会提示免费流量用完，可我明明已经是pro用户。

**Comment by p3rcya** [comment]
@helloworldhj Mac上的蓝灯界面截图给我看下

**Comment by helloworldhj** [comment]
![screen shot 2016-07-04 at 01 34 07](https://cloud.githubusercontent.com/assets/578987/16546802/04bc1afe-4189-11e6-8ae6-5b0ef171c2b7.png)
是这个吗？

**Comment by p3rcya** [comment]
@helloworldhj 对，那你已经是Pro版本啦

**Comment by ineondog** [comment]
@p3rcya 对的，我也是已购买的pro版，3.03版，依旧限速，会弹出流量用光的提示。mac10.11.5
<img width="1280" alt="screen shot 2016-07-04 at 04 02 04" src="https://cloud.githubusercontent.com/assets/19625167/16547330/78843562-419c-11e6-8030-5e8cc4480a8e.png">
<img width="1280" alt="screen shot 2016-07-04 at 04 03 33" src="https://cloud.githubusercontent.com/assets/19625167/16547332/8826d088-419c-11e6-9fa1-423813a2c73b.png">
另外mac版的log在哪里，为啥找不到
<img width="772" alt="screen shot 2016-07-04 at 04 13 28" src="https://cloud.githubusercontent.com/assets/19625167/16547367/bfcb2b0a-419d-11e6-9977-c60c6e5b0676.png">

**Comment by helloworldhj** [comment]
@p3rcya 对的 依然受限 然后我换了台mac使用，直接使用pro登录使用，一开始很快，但是后来又提醒我免费流量用完了，然后网速又受限了。

**Comment by helloworldhj** [comment]
@ineondog 日志文件在以下目录：/Users/你的用户名/Library/Logs（里面会有一个lantern文件夹）可以直接打开Finder后点击左上角菜单栏中的Go，然后按住Option键可以跳出Library选项
![screen shot 2016-07-04 at 06 09 55](https://cloud.githubusercontent.com/assets/578987/16547871/002efb62-41ae-11e6-800c-7db421d610c0.png)

**Comment by ineondog** [comment]
@p3rcya 谢谢 @helloworldhj 
[lantern.txt](https://github.com/getlantern/forum/files/345338/lantern.txt)

**Comment by p3rcya** [comment]
@ineondog 已收到，正在调查

**Comment by orbancanon** [comment]
@helloworldhj @ineondog @jyufeng @lemonskkyt @woaixiangbao 见谅并谢谢各位。几个小时前修复了后台的一个重要BUG，从@helloworldhj 的日志看，在上传日志前的10分钟，已经恢复。而@ineondog 最近几个小时应该都是没问题的。请问你们的速度还很慢吗？打开Lantern时免费流量用完的提示只是显示问题，正在查找原因，并不影响Pro的使用。

**Comment by ineondog** [comment]
@orbancanon 可我最近几个小时都没用，因为太慢了，刚打开依旧是20kb左右，youtube几乎无法打开，附截图和log
[lantern.txt](https://github.com/getlantern/forum/files/345435/lantern.txt)

<img width="1280" alt="screen shot 2016-07-04 at 04 03 33" src="https://cloud.githubusercontent.com/assets/19625167/16549202/dc57deb8-41ce-11e6-88d4-f94dfa4f662c.png">

**Comment by lemonskkyt** [comment]
@ineondog   我刚看了，还是一样限速 20KB/S

**Comment by ineondog** [comment]
@helloworldhj 是吧。。非常有趣==

**Comment by orbancanon** [comment]
呃，谢谢反馈。查看中。

**Comment by helloworldhj** [comment]
@ineondog @orbancanon 确实还是龟速 亟待解决 而且总是被谷歌要求做人机识别
![screen shot 2016-07-04 at 10 50 05](https://cloud.githubusercontent.com/assets/578987/16549798/6c3bf1bc-41d5-11e6-8a59-d6074270dbb6.png)

**Comment by lemonskkyt** [comment]
好神奇，Mac上购买的，windows和andriod都可以，但是Mac，即使换另一台都不行......
然后windows购买的，windows上就用不了，但android就可以正常使用....
这是一购买就不下诅咒了吗？？？要大家换着账号用？

**Comment by lemonskkyt** [comment]
楼主，咱们换着用试试吧，反正可以解绑，我的是windows上购买的，我把我的账号给你，你看看可以不...
lemonskkyt@163.com ,看到了回复下我给你发验证码

**Comment by ineondog** [comment]
我刚开win10虚拟机试了一下，依旧不行，免费流量速度好2m/s，一会儿用完就不行了==

**Comment by lemonskkyt** [comment]
@ineondog  不是账号，我在同一个WiFi下，购买pro的PC不行，andriod手机就没问题，楼主Mac买的，windows和andriod可以，Mac即使换一台也不行(>﹏<~)

**Comment by ineondog** [comment]
@lemonskkyt 会不会只是免费流量没用完==我身边没有安卓手机没法测试，只是我可以确定不是本地网络的问题了因为免费通道可以高速上网

**Comment by helloworldhj** [comment]
@ineondog @lemonskkyt 刚刚好像服务器后台更新了 我重新登录后网速已经上来了 看youtube HD没问题 你们看下

**Comment by lemonskkyt** [comment]
@helloworldhj   确实可以了，谢谢

**Comment by p3rcya** [comment]
都解决了这个帖子我关闭了
