### ISSUE TITLE
关于蓝灯的几个问题

### ISSUE THREAD

**Issue by nehcnoel** [getlantern/forum#2780]
你好，蓝灯support，
因工作需要经常翻墙，最近浏览网页发现蓝灯这款软件，使用后总体感觉良好，但还是有几个问题想咨询，如下
1、我本人使用较多的是ios 以及 Mac OS设备，蓝灯目前没有ios版本，希望尽快提供，这也是影响我购买pro版本最主要的因素。能否告知目前iOS版本的开发进度，预计何时发布？
2、我看到你们的软件支持3个终端，能否具体解释一下3个终端是怎么定义的？

如果可以的话，还请释疑，多谢。

**Comment by p3rcya** [comment]
1.因为软件开发，所以具体很难估计。
2.能授权3个设备（比如电脑，电脑，手机）

**Comment by nehcnoel** [comment]
了解，多谢。
