### ISSUE TITLE
系统托盘图标里显示不了蓝灯？？

### ISSUE THREAD

**Issue by GeraltG** [getlantern/forum#2782]
之前重装了下系统，重装系统后重新安装蓝灯，却发现打开蓝灯后系统托盘图标里没有蓝灯（但还是可以翻墙）？？请问是什么情况？

**Comment by p3rcya** [comment]
**请在本帖提供email**, 并使用应用内发送日志功能报告问题。若无法自动提交，请手动上传，方法见https://github.com/getlantern/forum/issues/1840#issuecomment-260143243 。请及时提供，否则无法调查，谢谢！

**Comment by GeraltG** [comment]
今天重装了蓝灯，问题已经解决，谢谢了。
