### ISSUE TITLE
Win32.Troj.Undef.(kcloud)

### ISSUE THREAD

**Issue by tiansu** [getlantern/forum#2793]
消毒软件报有病毒，怎么回事？

**Comment by p3rcya** [comment]
请问是什么杀毒软件？ 蓝灯哪里下载的？

**Comment by tiansu** [comment]
https://bit.ly/lantern-cn <https://bit.ly/lantern-cn> 这里，点击 Windows 版本(要求XP SP3以上) <https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-beta.exe>。

用的是金山毒霸。

**Comment by p3rcya** [comment]
是杀毒软件误报。请白名单，或者使用国外的杀毒软件
