### ISSUE TITLE
一年专业版180元，两年专业版300元~

### ISSUE THREAD

**Issue by chencuocuo** [getlantern/forum#2800]
很无奈在这里卖蓝灯专业版激活码，真的很抱歉。。。
本来在淘宝卖的，结果被关店了。。。
还有20个库存，低价出了回血。。。

一年专业版180元，两年专业版300元。。。

蓝灯代理商是公开透明的，价格大家都知道。
加我微信购买即可：ID：danyunlou
加好友请备注下蓝灯

**Comment by p3rcya** [comment]
请不要在这里广告，这里是技术支持。可以去其他论坛。
