### ISSUE TITLE
专业版使用问题

### ISSUE THREAD

**Issue by autumn0932** [getlantern/forum#2805]
购买了1年的蓝灯，每次登陆都要通过找回账号来登陆Lantern Pro。
登陆之后，在账号管理那里【电子邮件地址：】是空白的，到期时间显示：您的专业版账户将在 -17254 天后，即 1970/1/1 过期
而且登陆之后跟使用免费版蓝灯完全没区别，按图标的显示蓝灯，新弹开的也是之前未登陆的蓝灯页面。
邮箱：autumn0932@vip.qq.com

**Comment by p3rcya** [comment]
这个是没有付款成功导致的。请查看你支付宝的付款记录。

**Comment by autumn0932** [comment]
是在蓝灯代理商购买的1年的激活码，但在填完25位激活码后出现【在支付过程中出现错误】，试了几次也是这样。
代理商说账号已经是被激活的了。用找回账号的方式登录也显示【感谢您购买蓝灯专业版！】

**Comment by p3rcya** [comment]
请把激活码发送到 percy#getlantern.org

**Comment by autumn0932** [comment]
请问如何发送，是通过邮件发送么？

**Comment by p3rcya** [comment]
对，请发送给我。我们调查下

**Comment by autumn0932** [comment]
已经把码发到了这个邮箱notifications@github.com，不知是否收到。还是说要发到其他邮箱

**Comment by p3rcya** [comment]
已经收到。正在调查

**Comment by p3rcya** [comment]
@autumn0932 请问你当初使用激活码的那天电脑的邀请码是什么？

**Comment by autumn0932** [comment]
没使用过别人的邀请码，如果我的邀请码是不变的话，登陆后页面显示的是：NZH3GS。
如果是指第一次用邮箱登陆，收到的那份邮件验证码是：394227

**Comment by p3rcya** [comment]
已经邮件联系
