### ISSUE TITLE
急！在代理商网站上购买了批量激活码，但是没有购买记录

### ISSUE THREAD

**Issue by liuzhenhai** [getlantern/forum#2818]
求助，不知道该怎么办了。

**Comment by p3rcya** [comment]
请问你邮箱是什么？

**Comment by liuzhenhai** [comment]
@p3rcya 1989lzhh@sina.com 
需要order number吗？

**Comment by liuzhenhai** [comment]
1989lzhh@sina.com
订单号是Order w114341180

2017-03-31 10:14 GMT+08:00 p3rcya <notifications@github.com>:

**Comment by p3rcya** [comment]
找到了购买记录，是后台的延迟问题。过几个小时再看以下。

**Comment by liuzhenhai** [comment]
还是你这边反馈快啊，我之前正在联系reseller@getlantern.org。只有再等等了

**Comment by p3rcya** [comment]
你现在刷新试试

**Comment by liuzhenhai** [comment]
👌

**Comment by liuzhenhai** [comment]
🙏
