### ISSUE TITLE
Mac 版买了两年Pro，无法记住账号，Expire Date：1970-01-01，无法使用

### ISSUE THREAD

**Issue by lilpillow** [getlantern/forum#2844]
刚买了两年的Pro，账户信息显示Expire Date 是1970-01-01，然后直接用不了。一刷新就变回normal版…… 购买成功扣钱了，也没给我发邮件啥都没有。Report 了无数次没反应是什么鬼？真的累心了…… 重启无数次也没用……
<img width="1044" alt="screen shot 2017-04-08 at 06 29 48" src="https://cloud.githubusercontent.com/assets/27032548/24822046/d38ae6dc-1c24-11e7-9e3b-c0ff64fb7d63.png">

**Comment by lilpillow** [comment]
求助……

**Comment by p3rcya** [comment]
**请在本帖提供email**, 并使用应用内发送日志功能报告问题。若无法自动提交，请手动上传，方法见https://github.com/getlantern/forum/issues/1840#issuecomment-260143243 。请及时提供，否则无法调查，谢谢！

**Comment by lilpillow** [comment]
lanternk@icloud.com。 我已经在发了无数次 send an report……

**Comment by lilpillow** [comment]
[Uploading lantern.zip…]()

**Comment by lilpillow** [comment]
看不懂你那个怎么上传日志。。 我找到了log，已经回你邮件。请尽快解决。。。
我昨天都尝试卸载再安装，还不行。。。。

**Comment by lilpillow** [comment]
怎么没人理我啊，也没人处理啊！

**Comment by p3rcya** [comment]
我们正在处理，请不要开新帖。

**Comment by p3rcya** [comment]
这个是付款不成功导致的。如果你确认付款成功，请上传付款证明，我们可以后台调查。

**Comment by lilpillow** [comment]
付款成功了！都已经从我账户扣款了！证明要上传到哪里去？请给我个邮箱
