### ISSUE TITLE
出现蓝灯无法运行的情况却始终得不到技术回复能否申请退款

### ISSUE THREAD

**Issue by limsaya** [getlantern/forum#2846]
我发了至少4-5封邮件 ,论坛上也发帖了 不一定立马给个解决方案 起码告诉我你们在关注这个问题啊

**Comment by p3rcya** [comment]
**请在本帖提供email**, 并使用应用内发送日志功能报告问题。若无法自动提交，请手动上传，方法见https://github.com/getlantern/forum/issues/1840#issuecomment-260143243 。请及时提供，否则无法调查，谢谢！

**Comment by demonlims** [comment]
2842  那就看下  ,log  都在里面 ,至今都没人回复

**Comment by demonlims** [comment]
那请看下#2842的问题

**Comment by liuweifendou** [comment]
Mac端的总是显示连接上，可以无法访问任何被屏蔽的国外网站，使用过自动上传几次，但是没人回复解决，在此手动上传望解决。邮箱：liuweivvip@126.com
[Lantern.zip](https://github.com/getlantern/forum/files/907598/Lantern.zip)

**Comment by limsaya** [comment]
@p3rcya   想确认orbancanon  是否是你们的员工

**Comment by lilpillow** [comment]
我也有同样问题！也想退款！请教我可以怎么弄！老子不用了！太气人了！

**Comment by lilpillow** [comment]
#2857  #2844  两个帖子都是我的！都没人管

**Comment by p3rcya** [comment]
@limsaya 是的。他已经正在调查了，所以不要开新帖
