### ISSUE TITLE
付费版是否比免费版更稳定？

### ISSUE THREAD

**Issue by youngwind** [getlantern/forum#286]
RT
用了一下lantern，觉得还是很方便的。唯一的问题就是不稳定，在刚刚的几个小时内，掉线了好几次。我试用的是免费版。想问如果换成付费版能否保证稳定性？

**Comment by p3rcya** [comment]
@youngwind 是，付费版稳定性和速度都更好。

**Comment by lemonskkyt** [comment]
刚好几分钟前解决问题，现在可以了，这个是我的邀请码   5KL5K4

**Comment by lsh1215225** [comment]
付费版在哪下载？

**Comment by p3rcya** [comment]
https://github.com/getlantern/forum 这里下载

**Comment by youngwind** [comment]
@p3rcya 已购买专业版，但是为何通过google搜索的时候会提示这样的内容？ 
<img width="661" alt="2016-07-04 3 57 10" src="https://cloud.githubusercontent.com/assets/8401872/16554260/301c8d6a-4200-11e6-8419-7f08bab2048d.png">

**Comment by youngwind** [comment]
@p3rcya 还是不时出现掉线的情况，访问不了google，控制面板也一直loading。。。如下图。是我什么地方用得不对吗？
<img width="1439" alt="2016-07-04 4 24 48" src="https://cloud.githubusercontent.com/assets/8401872/16554898/5bda4e34-4204-11e6-8892-65eabb83f6f9.png">

**Comment by caofengzi** [comment]
@youngwind 這是更換ip地址引起的，你用tor試試能夠煩死你。

**Comment by youngwind** [comment]
@caofengzi  那有什么解决方案吗？现在是完全翻不了了。。。。之前免费的还只是偶尔掉线。。现在付费了居然用不了！！请问有退款渠道吗。。。

**Comment by p3rcya** [comment]
@youngwind 请上传log，我们调查下。

**Comment by caofengzi** [comment]
log就是你启动蓝灯以后在点击一下任务栏的蓝灯图标弹出的那个界面。

via CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.5.49&pv=4.4.4&source=email_footer_2] On Tue, Jul 05, 2016 at 12:10 PM, 梁少峰 < notifications@github.com [notifications@github.com] > wrote:
@p3rcya [https://github.com/p3rcya] 如何查看log?

**Comment by youngwind** [comment]
@caofengzi @p3rcya 依然没有找到路径，能直接给出默认mac os EI Capitian的安装地址吗？我试过如下地址找不到。
<img width="651" alt="2016-07-05 12 20 09" src="https://cloud.githubusercontent.com/assets/8401872/16573967/58aaf418-42ac-11e6-8328-6fb73c4da0f7.png">

**Comment by p3rcya** [comment]
@youngwind 

日志文件在以下目录：/Users/你的用户名/Library/Logs（里面会有一个lantern文件夹）可以直接打开Finder后点击左上角菜单栏中的Go，然后按住Option键可以跳出Library选项

**Comment by youngwind** [comment]
@p3rcya  这个Lantern太难折腾了，请问能退款吗？ 我买了一年的，刚刚用了两天不到。。。部分退款也可以。（PS：为什么没有月付类型呢，这样也好让人尝试好坏啊）

**Comment by btsg** [comment]
@p3rcya 请问退款渠道。

我买了两年的，就在几个小时之前。

当时不知道有邀请码，我能不能退款之后，重新购买，这次填加邀请码。

**Comment by csitaylor** [comment]
付费版今天一样上不了3.0.5

**Comment by p3rcya** [comment]
@csitaylor 请上传下log，方便我们调查

**Comment by guoduren** [comment]
付费版稳定性和速度都更好，不错。我的邀请码是 YLYFQG

**Comment by qzwl** [comment]
为什么多收了三分钱。。支付宝支付

**Comment by p3rcya** [comment]
@qzwl 汇率转换问题吧。

**Comment by huiyu998** [comment]
输入我的邀请码 Y745HS 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by zhuyudong** [comment]
输入邀请码YHVPMSF 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by zz89419318** [comment]
蓝灯合租扣扣裙：597065668，70一年哦

**Comment by jijkbird** [comment]
我就想问  为何我免费版用的那么流畅  一付费  马上链接不上了？
