### ISSUE TITLE
专业版为什么还是会被限速？

### ISSUE THREAD

**Issue by zhyy2008z** [getlantern/forum#2873]
已经购买了两年的专业版，蓝灯也已经提示了现在是专业版状态。但是我在两台电脑登了专业版，500兆流量用完后还是被限速了，请问这是什么情况，求解释？昨天通过软件内置的报告问题反馈，到现在还没有回复，只好把问题发到这里

**Comment by lemonskkyt** [comment]
上午还好的，现在我也被限速了.....

**Comment by p3rcya** [comment]
请报告网络环境，访问时段。
**请在本帖提供email**, 并使用应用内发送日志功能报告问题。若无法自动提交，请手动上传，方法见https://github.com/getlantern/forum/issues/1840#issuecomment-260143243 。请及时提供，否则无法调查，谢谢！

**Comment by zhyy2008z** [comment]
zhyy2008z@gmail.com，从昨天北京时间早上九点左右，购买完之后一直到现在都被限速。已经通过应用内报告功能成功提交三次。

**Comment by zhyy2008z** [comment]
网络环境是公司联通网络，家里中国移动网络。
有一点还要补充一下，免费的500兆流量用完之前非常快，基本上可以维持每秒一两兆，我专门在干净的虚拟机（win10）里做过实验，免费流量用完之前就绑定了专业版，虚拟机里免费的500兆用完之后还是被限速了。因此，我确定我客户端跟服务器之前网络是良好的，应该是程序哪里出了问题，麻烦调查，谢谢了！

**Comment by zhyy2008z** [comment]
从昨天晚上我使用蓝灯开始直到现在，我的蓝灯已经正常了，不再被限速，可以达到令人满意的速度，非常感谢！

**Comment by JasonMao0623** [comment]
昨天买的两年的专业版，为什么还是限速啊，而且很不稳定。一会网速很快，一会打开个Google都要半天，我想问这是怎么回事。买了专业版之后打开youtube看144p的居然要缓冲几分钟，真是醉了。好歹也三百多大洋呢，连个客服都没找到。这怎么解决啊！！！！

**Comment by p3rcya** [comment]
已经修复，请大家重启下电脑。

**Comment by zhyy2008z** [comment]
@p3rcya 账户又被限速了，貌似就在你说重启电脑之后。。。我已经在应用内报告问题了，仍然在干净虚拟机下进行了测试，免费版流量未用完的情况下很快，实体机下专业版仍被限速为10kb/s。。。网络环境：中国移动、联通宽带。 账户：zhyy2008z@gmail.com

**Comment by lemonskkyt** [comment]
@p3rcya 压根就没修复，从前天开始，天天被限速

**Comment by orbancanon** [comment]
@zhyy2008z 很抱歉，有几台服务器的后台数据不一致，导致你仍然被限速，刚刚批量修复了。请你再试试，现在应该已经自动恢复了。

**Comment by zhyy2008z** [comment]
@p3rcya  ok，现在确实已经不限速了，谢谢~
