### ISSUE TITLE
VPN推荐

### ISSUE THREAD

**Issue by xiaoweihuang** [getlantern/forum#2874]
推荐一款便宜实用的VPN http://ss.f2ecoder.com

**Comment by diaodada** [comment]
2018年国内最好的5个VPN推荐 快速稳定不掉线国外VPN
https://vpnbay.com/
知乎推荐的免费/付费VPN（安卓/iOS翻墙软件）官网
VPN已经被全网封杀，整理了一批可以用的，方便大家使用，需要的朋友记得收藏分享网址
https://vpnbay.com/the-5-best-vpn-services-for-2018.html

**Comment by hallochina** [comment]
在中国，最好用的付费VPN推荐 https://vpnchina.zdhweb.com/p/vpn-china.html
你可以根据自己的偏好选择注册所有推荐的vpn，然后根据使用效果，哪个好用就付款哪个。

**Comment by chinahallo** [comment]
在china，测试并推荐好用的付费v.pn
https://vpnchina.zdhweb.com
