### ISSUE TITLE
买了以后看油管超爽，一兴奋朋友圈都发说说让他们都买专业版了，但是就爽了那么半个小时就卡了，尴尬~~

### ISSUE THREAD

**Issue by MetalMaxPlus** [getlantern/forum#2875]
账号412161745@qq.com,昨晚购买的专业版
[lantern.txt](https://github.com/getlantern/forum/files/923409/lantern.txt)
![qq 20170415150950](https://cloud.githubusercontent.com/assets/14823690/25061830/708a7926-21f1-11e7-8c2a-3ff7e2b77d7d.png)

**Comment by MetalMaxPlus** [comment]
貌似网速已恢复，2017.4.16 21:00 至 2017.4.17 10:00 全程youtube测试流畅

**Comment by p3rcya** [comment]
已经修复，请大家重启下电脑。
