### ISSUE TITLE
专业版限速问题

### ISSUE THREAD

**Issue by JasonMao0623** [getlantern/forum#2882]
昨天买的两年的专业版，卖完之后看了一下youtube很快，可是过了一段时间怎么又限速了啊，而且很不稳定。一会网速很快，一会打开个Google都要半天。我测试了一下不用蓝灯的情况下网速很好，可以买了专业版之后打开youtube看144p的居然要缓冲几分钟，还不如之前用每个月800兆的快，真是醉了。好歹也三百多大洋呢，连个客服都没找到。是不是3.6.3的版本不稳定啊？这怎么解决啊！！！！

**Comment by sutando** [comment]
我的今天开始也速度奇慢。。不知道是怎么了。。

**Comment by p3rcya** [comment]
已经修复，请大家重启下电脑。
