### ISSUE TITLE
今天早上用蓝灯速度变得非常慢。 youtube都打不开。

### ISSUE THREAD

**Issue by sutando** [getlantern/forum#2883]
是服务器问题吗。还是什么情况。

**Comment by power2262** [comment]
前两天是美国的IP，今天只有荷兰和日本的IP，其中荷兰IP太慢，你断开蓝灯后重新连接，运气好时，能连接到日本的IP。但是电脑记不住！再次连接时，又跑到荷兰IP了。

**Comment by sutando** [comment]
@power2262   还真是。。竟然连得荷兰。。 我之前都是连得香港。

**Comment by JasonMao0623** [comment]
请问一下，怎么看是连的哪里的

**Comment by sutando** [comment]
@JasonMao0623   之前是香港。  今天连上就是荷兰。 还有印度。。

**Comment by p3rcya** [comment]
已经修复，请大家重启下电脑。
