### ISSUE TITLE
为什么购买了专业版速度比限速的试用版还慢？

### ISSUE THREAD

**Issue by 396822365** [getlantern/forum#2885]
今天刚买的专业版，试了下家里广东移动12M的网络，平时下载速度在1.2M/s左右，用蓝灯最高100kb/s，长时间维持在20kb/s。别说看youtube的视频了，网页都打不开。已经报告问题很多次了，邮箱396822365@qq.com

**Comment by JasonMao0623** [comment]
我也是，昨天买的，贼慢！！！

**Comment by 396822365** [comment]
@p3rcya 可以帮忙解决下吗？

**Comment by nijia909** [comment]
我用挺快- 0-要不你试试看你改改DNS？（蠢萌的萌新的废话-0-）

**Comment by 396822365** [comment]
改成什么样的？我也是萌新哈哈哈哈哈哈

**Comment by lxn348567248** [comment]
我是昨天晚上买的，我的也很慢，我下点东西都下不了。

**Comment by nijia909** [comment]
改DNS的话-0-
一般都不用本地的运营商 电信联通移动的-= -坑爹DNS吧0-
一般都用阿里，谷歌- 0
再不然亚马逊，微软- -那些DNS- -

**Comment by p3rcya** [comment]
已经修复，请大家重启下电脑。

**Comment by nijia909** [comment]
简单翻译下- -那些大公司的DNS服务 劝告用户用自己DNS原因就是：
<1.我家DNS速度快。| 特别是保证秒杀反应快       
<2.域名解析到我这里靠谱。| 特别国外网站       
<3.我的数据更新快。       
<4.根据我的GeoDNS能够知道你到底是从哪里访问的，给你一个最快的服务器服务。      
<5.我的DNS特别稳定。       
<6.有些无良的DNS提供商会给你乱装软件，乱弹窗口，卖假药什么的。

**Comment by nijia909** [comment]
@p3rcya 楼上工作的帅哥，美女- -麻烦教个热点共享翻墙呗--#2886

**Comment by 396822365** [comment]
@p3rcya 我依旧没有解决啊，还是没法用，20kb/s
