### ISSUE TITLE
专业版为什么又被限速了..............

### ISSUE THREAD

**Issue by lemonskkyt** [getlantern/forum#2889]
昨天下午就莫名其妙的被限速，后来晚上用就自己好了，现在又是被限速，什么情况...........只能看144P的(」゜ロ゜)」

**Comment by MetalMaxPlus** [comment]
同上，老抽风

**Comment by lemonskkyt** [comment]
卧槽，还是被限速

**Comment by lemonskkyt** [comment]
什么鬼，记得刚开始收费的时候就是 买了专业版，然后会被当成 免费版限速，搞了3 4天才搞好，当时就觉得很奇葩，这不能区分是 专业版还是 免费版，你可以先全部不限速啊，之前就一直免费，多免费3 4天会死啊，非要搞的 付费用户没法使用........这收费都差不多一年了，怎么还会有这样的问题

**Comment by sutando** [comment]
@lemonskkyt  昨天有问题今天好了。。不知道你那好没好。

**Comment by lemonskkyt** [comment]
@sutando 昨天有问题的时候，我也不行，后来晚上用就好了，但是今天下午又被限速，到现在都还不行

**Comment by lemonskkyt** [comment]
现在没限速了.......................................
