### ISSUE TITLE
昨晚购买的专业版，结果还限速。。。。

### ISSUE THREAD

**Issue by sxswisdom** [getlantern/forum#2892]
帐号shixueshu@outlook.com，昨晚购买的专业版，到现在也无法保证高速，甚至有些时候速度比之前还慢。

**Comment by xiaoweihuang** [comment]
建议使用ss.f2ecoder.com

**Comment by sxswisdom** [comment]
![image](https://cloud.githubusercontent.com/assets/15007572/25112786/116491f2-2426-11e7-95b9-0b313e065f57.png)
这youtube视频看着一卡一卡的，还不是720p高清的

**Comment by lemonskkyt** [comment]
用了差不多一年了，除了刚开始的三四天 专业版被当成免费版被限速，其它偶尔抽风下，都正常，然后从前天开始，又开始被当成免费版限速

**Comment by orbancanon** [comment]
@lemonskkyt  很抱歉，有几台服务器的后台数据不一致，导致你仍然被限速，刚刚批量修复了。请你再试试，现在应该已经自动恢复了。

**Comment by sxswisdom** [comment]
总算恢复了。。。
