### ISSUE TITLE
已经赠送专业版的测试用户两个月使用期

### ISSUE THREAD

**Issue by p3rcya** [getlantern/forum#2898]
为了感谢蓝灯专业版刚推出时帮忙测试的用户，我们已经在后台赠送了两个月使用期。请测试期间购买蓝灯专业版的用户查看用户管理界面的过期时间，谢谢！

**Comment by EdwardAutumn** [comment]
我现在更在乎什么时候能解决验证码的问题。。。

**Comment by chengziqing** [comment]
并没增加，前几天，我是2017年12月份到期，现在还是，没有增加。

**Comment by Griffin1** [comment]
什么时间之前算专业版的测试期？我16年31/7买的专业版过期时间没变化。。

**Comment by shangzhou** [comment]
已验证bravo👏

**Comment by Wang-chao** [comment]
我的只加了1个月，并没有额外加2个月，帐户为wangchao07028@gmail.com

**Comment by laoqi260** [comment]
我的也并没有增加两个月，还是之前买的的日期。账户：528321894@qq.com

**Comment by temnia** [comment]
帐户yxc0011992@gmail.com，只增加了1个月@p3rcya
貌似推荐过好友的计算时间就出错了

**Comment by Hwatu** [comment]
我也没有赠送 账户hwatu.du@gmail.com

**Comment by geliorgl** [comment]
我也没有赠送  账户geliorgl@gmail.com

**Comment by junecwf** [comment]
我的也没有啊 ，账户junecwf@tom.com

**Comment by hckdk** [comment]
没有。mask2000@qq.com

**Comment by qingyinji** [comment]
并没有。1360725096@qq.com

**Comment by Roseyang2017** [comment]
能不能给我赠送两个月专业版

**Comment by 1604563715** [comment]
我的并没有赠送两个月专业版as19910703@gmail.com

**Comment by p3rcya** [comment]
现在已经赠送了

**Comment by temnia** [comment]
已查收，验明有效
