### ISSUE TITLE
请问怎么在mac终端使用lantern翻墙？

### ISSUE THREAD

**Issue by HeyDaniel** [getlantern/forum#29]
要使用cocoapods下载第三方库，挺急的，求大神指教。

**Comment by yeahwu** [comment]
export http_proxy=http://127.0.0.1:8787

**Comment by HeyDaniel** [comment]
export http_proxy=http://127.0.0.1:8787 我试了 没有用啊 
ping google.com还是丢包

**Comment by DanielGzx** [comment]
我用的就是Mac，什么设置都不用的。安装-打开-使用

**Comment by HeyDaniel** [comment]
我知道，在浏览器使用是不用设置的，但是在终端下没办法使用。你可以开启lantern后分别ping google.com/baidu.com

**Comment by HeyDaniel** [comment]
问题已经解决
在控制台输入
export http_proxy=http://127.0.0.1:8787
export https_proxy=http://127.0.0.1:8787
然后在终端就可以翻墙了

**Comment by F-12** [comment]
浏览器打开`http://127.0.0.1:8787`,右下角设置里勾上管理系统代理不就行了
如果问题解决了请close

**Comment by F-12** [comment]
close #29

**Comment by spiritedRunning** [comment]
@HeyDaniel 为啥我试了还是不行，不过我改了默认端口，应该没影响吧

**Comment by wy-z** [comment]
@spiritedRunning 127.0.0.1:60562

**Comment by ahangchen** [comment]
有没有试过翻墙在终端里跑pip的？ssl错误应该是要导入证书才能解决的，终端的证书要在哪里导入呢？

**Comment by wy-z** [comment]
@ahangchen http://mirrors.aliyun.com/help/pypi

**Comment by ahangchen** [comment]
@wy-z 有些whl阿里云镜像没有啊。。

**Comment by wy-z** [comment]
@ahangchen 比如?

**Comment by wy-z** [comment]
@ahangchen 最好贴下 log

**Comment by ahangchen** [comment]
@wy-z 比如tensorflow最新版本的whl，所以希望不换源，关注不换源情况下的证书问题，这种情况的log是这样的：

```
cwh@chenweiangdeMBP ~$ pip3 install Django
Collecting Django
  Could not fetch URL https://pypi.python.org/simple/django/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645) - skipping
  Could not find a version that satisfies the requirement Django (from versions: )
No matching distribution found for Django
```

**Comment by wy-z** [comment]
感觉不像是证书问题 `No matching distribution found for Django`

**Comment by ahangchen** [comment]
@wy-z 看出错的第一行，长度显示不够，no matching的原因是上面的[SSL: CERTIFICATE_VERIFY_FAILED]

**Comment by spiritedRunning** [comment]
@wy-z 还是不行，我打开latern页面显示的是http://127.0.0.1:16823/， 但是这个端口我试了也不行。ping google.com仍然没反应

**Comment by wy-z** [comment]
@spiritedRunning 
```
export http_proxy=127.0.0.1:60562
export https_proxy=127.0.0.1:60562
```

**Comment by spiritedRunning** [comment]
@wy-z Lantern 版本 2.2.5 (20160627.192617)
看来我是一个比较老的版本，我按我的端口配置后，curl有反应了，
`<!DOCTYPE html><html ng-app=app><head><meta charset=utf-8><title>{{ 'LANTERN' | translate }}</title><meta name=viewport content="width=device-width, initial-scale=1.0"><meta name=description content=Lantern><meta name=author content="Team Lantern"><link rel=stylesheet href=style/app.css><script src=js/lib-8390a0f47b.js></script><script src=js/app-e34bf0ca6e.js></script><link rel="shortcut icon" href=img/favicon.ico><link rel=icon type=image/png href=img/favicon.png></head><body ng-controller=RootCtrl ng-cloak lang="{{ lang }}" dir="{{ langDirection }}"><div id=fb-root></div><div id=waiting ng-show=!wsConnected><div ng-show=!backendIsGone><div>{{ 'WAITING_FOR_LANTERN' | translate }}</div><img src=img/spinner.gif></div><div ng-show=backendIsGone><div class=backend-gone>{{ 'LANTERN_GONE' | translate }}</div></div></div><div class=message><a href=https://getlantern.org target=_blank><img id=logo src=/img/ui-header-logo.svg></a><br><span ng-hide="(backendIsGone && !wsConnected) || showError">{{ 'WELCOME_TO_LANTERN_BLOCKED_SITES' | translate }}</span></div><div id=feedLink ng-class="{subtle: showNews}"><div><a ng-click=showNewsfeed() ng-show="!showNews && !showError">{{ 'SHOW_NEWSFEED' | translate }}</a> <a ng-click=hideNewsfeed() ng-show="showNews || showError">{{ 'HIDE_NEWSFEED' | translate }}</a></div></div><div ng-include src="'partials/modals.html'"></div><div ng-include src="'partials/get-mobile.html'"></div><div ng-include src="'partials/bookmarks.html'"></div><div ng-include src="'partials/news.html'"></div><div ng-include src="'partials/footer.html'"></div><div ng-include src="'partials/developer.html'"></div><div ng-include src="'partials/error.html'"></div></body></html>% `

其实我是想git clone一个代码 ， 似乎还是不行

**Comment by ahangchen** [comment]
@spiritedRunning git clone 就是要走https的啊，关键就是要搞定证书问题，我也在纠结证书怎么搞

**Comment by Insofan** [comment]
@ahangchen 你解决了终端翻墙了么 试了ss和lantern export 代理都不行

**Comment by mikiXuan** [comment]
@HeyDaniel   @ahangchen   请问搞定了么 我今天搞了一天  realm 也没更新成功。终端和lantern的代理都设置好了也不行

**Comment by Insofan** [comment]
@mikiXuan 我搞定了 用ss ng 加上
    `git config --global http.proxy socks5://+你监听端口`

**Comment by qha0731** [comment]
尝试了半天，找到解决方法。
在蓝灯网页设置中：
可以看到
HTTP(S)代理服务器：127.0.0.1:56256
在终端中输入，端口号要一致：
export http_proxy=127.0.0.1:56256
export https_proxy=127.0.0.1:56256

**Comment by RecherJ** [comment]
@ahangchen 你用lantern代理，ssl证书问题搞定了吗？我git push时报证书问题
