### ISSUE TITLE
Lantern Pro 仍然遇到流量提醒

### ISSUE THREAD

**Issue by ayasaki-hayate** [getlantern/forum#290]
版本3.0.3

![qq 20160704133933](https://cloud.githubusercontent.com/assets/16934954/16551616/ea8052b8-41ec-11e6-8ae3-37400098f34a.png)

**Comment by p3rcya** [comment]
这个不会影响正常使用。但请上传log方便我们调查

**Comment by partial-s** [comment]
https://gist.github.com/partial-s/c6f9cb93063af85cd2ca45f851072291

**Comment by ayasaki-hayate** [comment]
在3.0.4中修复了,感谢帮助
