### ISSUE TITLE
蓝灯邀请码 V4LV48 在购买后将免费获得额外3个月的权限。

### ISSUE THREAD

**Issue by I-most-handsome** [getlantern/forum#292]
使用我的代码 V4LV48 在购买后将免费获得额外3个月的权限。下载 Lantern https://bit.ly/lanternapk

**Comment by 562503117** [comment]
使用我的代码 V4LV48 在购买后将免费获得额外3个月的权限。

**Comment by 562503117** [comment]
免费使用,请使用推荐代码 V4LV48

**Comment by p3rcya** [comment]
这里都是蓝灯用户。因为版面问题，请将邀请码发到其他论坛，谢谢！

**Comment by p3rcya** [comment]
请发到汇总贴中 #313

**Comment by GPX-NSlog** [comment]
输入我的邀请码 99WK5V 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by haotianhong** [comment]
输入我的邀请码 MCFPBX 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
