### ISSUE TITLE
蓝灯邀请码

### ISSUE THREAD

**Issue by Husky1992** [getlantern/forum#2929]
输入我的邀请码 J9GX8W 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by stephen666** [comment]
# 蓝灯lantern最新邀请码 Y2947HH 永久有效！获取三个月免费！

## 请输入我的蓝灯lantern邀请码 Y2947HH 来获得三个月免费的蓝灯专业版！使用后请留下你的邀请码，我也会使用你的邀请码续费的！
![lantern-referral-code](https://user-images.githubusercontent.com/11013738/28964892-6181e6ec-7941-11e7-8333-4ec26545980b.png)

**Comment by meibujun** [comment]
输入我的邀请码 YJJ9W4F 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
