### ISSUE TITLE
我的邀请码，VQLVQ5，输入后我们都会赠3个月

### ISSUE THREAD

**Issue by Portan** [getlantern/forum#293]
我很老实，麻烦新买的朋友输这个邀请码，互利互惠~

**Comment by p3rcya** [comment]
这里都是蓝灯用户。因为版面问题，请将邀请码发到其他论坛，谢谢！

**Comment by p3rcya** [comment]
请发到汇总贴中 #313

**Comment by yc1621898712** [comment]
输入我的邀请码 WQQQ5D ，额外获得三个月的蓝灯专业版！

**Comment by yc1621898712** [comment]
请问一下，蓝灯并没有需要我填邀请码的地方？ 只有我自己的邀请码，是没有要我填的地方还是我没找到？

**Comment by p3rcya** [comment]
邀请码是邀请朋友用的。

**Comment by peterpjn** [comment]
输入我的邀请码 YHW2MD 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by aousqqdu** [comment]
输入我的邀请码 X4VGJ6 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by zheng19970330** [comment]
输入我的邀请码 Y2PPGX3 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by ttkl360** [comment]
最新邀请码 2017/11/07  输入我的邀请码 62FT4M 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by linysgithub** [comment]
2018/06/23最新邀请码  WS3VWU
