### ISSUE TITLE
lantern已经不行了

### ISSUE THREAD

**Issue by virskor** [getlantern/forum#2935]
推荐这个吧  免费的，超级快可以看youtube4K的也没谁了
https://www.pojiesuo.com/aff.php?aff=1

**Comment by chhzhangs** [comment]
没法下载啊

**Comment by duhast123** [comment]
这个网站咋看起来这么山寨，LOGO也是山寨GreenVPN，本身自己的网站就很慢，我看也没戏

**Comment by virskor** [comment]
不会，真的是我用过最快的最稳定的ss4K不卡，官网是卡，但是你可以用免费版试试，绝对牛

**Comment by wuxw719** [comment]
垃圾。

**Comment by thezzycom** [comment]
这么厉害 aff=1 自己来推荐自己的吧
