### ISSUE TITLE
我年前买的一年的专业版，用了没多久，就变成到1970年到期！！！why！！！！

### ISSUE THREAD

**Issue by 563273538** [getlantern/forum#2953]
563273538@qq.com #
![hzw18o 2v xur u tb ed](https://cloud.githubusercontent.com/assets/28344763/25656242/aa3cf346-302a-11e7-91d9-e2c964458e35.png)

**Comment by p3rcya** [comment]
后台查看，并没有你付款成功的记录。如果你确认付款成功，请上传支付宝记录。

**Comment by 563273538** [comment]
![image](https://cloud.githubusercontent.com/assets/28344763/25733573/f20232fa-318c-11e7-9e5a-a473618cab26.png)
我用了一个月之后才没用的。不管怎样，你们要给我给说法.........

**Comment by lee134134134** [comment]
你的问题解决了吗 我都不敢支付了

**Comment by p3rcya** [comment]
这个账单是假的，后台查询不到
拜托LZ你骗人也要专业点吧。。。 说了年前买的，图片上显示购买日期是2017-03-02 呵呵呵

**Comment by 563273538** [comment]
我记错时间了，但你这个态度让我很不爽。我这个帐单绝对真实。现在我很怀疑你的真实性!!!!

**Comment by 563273538** [comment]
你关闭我的帖子是什么意思

**Comment by 563273538** [comment]
敢不敢加我联系方式!!QQ563273538。
