### ISSUE TITLE
本来也不是什么大事，就200多钱。但你说我骗子！我现在要弄明白到底谁的问题！！关我帖子说明你心虚!!!!

### ISSUE THREAD

**Issue by 563273538** [getlantern/forum#2958]
![img_1190](https://cloud.githubusercontent.com/assets/28344763/25734237/8603091a-3193-11e7-999d-367b7efb1c1c.PNG)
![m2cvw 4l9k8fe ehde 5fc](https://cloud.githubusercontent.com/assets/28344763/25734239/8e2097fc-3193-11e7-85e4-ef9c431a1548.png

之前我发的帖子，记错购买时间了，误说错为年前买的，真实购买时间为上截图时间。就在刚才那个不知道是不是官方的人关闭我的帖子，还说我是骗子，查不到我的付款信息，我就纳闷，我没付款我凭什么一开始能用，你怀疑我账单有问题，你可以直接支付宝官方确认。不要拿你那么弱智的推理来判断这件事！！！！

**Comment by 563273538** [comment]
我的问题并没有解决，各位看官，可以去支付宝官方查我的订单号，绝对真实............

**Comment by duhast123** [comment]
蓝灯现在的服务是VPN里面最烂的，实质问题从来不解决也不回答，现在也非常不稳定，经常会自动切换地址，在国外网盘下载东西，一会又断开一会又断开，现在换免费的代理看油管720p电影，挺流畅的，根本不值得花钱用蓝灯

**Comment by p3rcya** [comment]
@563273538 再去后台查看了，没有看到你的用户ID，付款记录。如果你确认支付，请联系支付宝退款。因为我们没有收到这笔交易的任何内容。

**Comment by 563273538** [comment]
我的支付宝账号是18721166952.不是我注册的这个ID。还有我之前有使用过一段时间，请问你们没有收到付款，我怎么能用！！！。请仔细核实清楚。别把问题推到我这里。我也留下我的QQ：563273538.想解决问题请主动联系我。
上面那张专业版使用时间的截图是什么意思！我的专业版使用时间怎么就变成1970年！！！

**Comment by p3rcya** [comment]
蓝灯有免费版，不付钱当然能用。1970年就是没有付款成功的意思。 如果你确实有问题，请点击你账单上的“对此账单有疑问”这个选项解决。

**Comment by 563273538** [comment]
我付完款后，还特地查看了下使用时间，那时是正确的使用时间！！！就200块钱我都懒得退，但你们的问题推给我，我就不爽了！！我付了钱，用了一段时间后，不能用了，你们说没收到钱，叫我去退款。这什么道理！！这事没完！

**Comment by p3rcya** [comment]
我们会在QQ上联系你。但是我们目前位置都没有原来使用时间正确，后来错误的例子

**Comment by orbancanon** [comment]
@563273538 你之前提的那个QQ邮箱确实没有成为专业版，因为你最后购买时填的是563273538@163.com …… 我们逐一查找了那段时间的所有交易记录，才发现。

请你使用163邮箱登录。

**Comment by 563273538** [comment]
我也说声抱歉，时间太久自己记错了。
