### ISSUE TITLE
我的lantern邀请码 26W6JM

### ISSUE THREAD

**Issue by ztxzhang518** [getlantern/forum#2998]
输入我的邀请码 26W6JM 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by youngjy** [comment]
输入我的邀请码 YYXRFHS 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by stephen666** [comment]
# 蓝灯lantern最新邀请码 Y2947HH 永久有效！获取三个月免费！

## 请输入我的蓝灯lantern邀请码 Y2947HH 来获得三个月免费的蓝灯专业版！使用后请留下你的邀请码，我也会使用你的邀请码续费的！
![lantern-referral-code](https://user-images.githubusercontent.com/11013738/28974613-84f0bd60-7969-11e7-8a86-7a3f8f5b9588.png)
