### ISSUE TITLE
蓝灯专业版能用来玩游戏吗？

### ISSUE THREAD

**Issue by PangpangKong** [getlantern/forum#3007]
我回国带来回一套Oculusrift，国内用必须要翻墙，不知道蓝灯专业版够不够稳定。还有一个问题就是，我试用过免费版一段时间了，我发现蓝灯只能作用于浏览器翻墙，Windows商店里的App（twitter，Facebook等）还是用不了，不知道是我的设置问题还是免费版的限制，专业版可以全局突破限制吗？如果蓝灯只能用来浏览网页那么我也就没有购买专业版的必要了。
谢谢解答

**Comment by EdwardAutumn** [comment]
如果想用全局系统代理很多软件都可以实现，问题在于蓝灯虽然带宽不错，但是玩游戏延迟太高，目前测试拿来玩上古卷轴ol是玩不下去的。

**Comment by Jannister** [comment]
蓝灯设置里代理全部流量没试试看？

**Comment by PangpangKong** [comment]
非常感谢楼上两位的帮助，一直没注意蓝灯主页左上角还有个设置选项，勾选了全局设置之后都可以用了。
