### ISSUE TITLE
lantern专业版不可用20170526

### ISSUE THREAD

**Issue by xuwenping123** [getlantern/forum#3039]

**Comment by xuwenping123** [comment]
你好，lantern专业版不可用。具体情况如下：
系统环境　win7 sp1, lantern3.7.0
在家里的台式机上专业版可用，在公司的台式机上安装lantern后chrome弹开蓝灯页面一直转圈，一段时间后显示无法连接服务器。
按照给出的方式查看注册表，发现安装lantern后Internet Setting下将出现注册项：
ProxyOverride	<local>
ProxyServer		127.0.0.1:49891
ProxyEnable		1     此项则一直存在
麻烦查看下，谢谢

**Comment by itgoyo** [comment]
@xuwenping123 我也经常遇到Chrome转圈圈的情况，后面登录的时候我都是从Chrome复制地址到Firefox上面登录成功先再返回使用Chrome的。

**Comment by orbancanon** [comment]
@xuwenping123 看起来你公司的台式机连不上蓝灯的服务器啊。是不是公司有防火墙限制只能访问某些地址？

注册表项是蓝灯写入的，是正常的。退出蓝灯时就会把它清掉。

**Comment by xuwenping123** [comment]
@itgoyo 刚刚尝试了安装火狐客户端，设置其为默认浏览器，一样还是在转圈啊。。。
@orbancanon 公司的网络不妨碍lantern网络，有同事使用免费版的lantern都可以的
不造为毛抽风，我这日志都无法上传，这就比较尴尬了啊

刚刚查看了chrome的代理服务器，打开后在Internet属性页面局域网配置代理页面
勾选了选项  为LAN使用代理服务器
地址：127.0.0.1   端口：49891
勾选了选项 跳过本地地址的代理服务器

传图失败，只能用文字描述了。。。

**Comment by orbancanon** [comment]
@xuwenping123 是的，代理服务器的设置都是正常的。惟一的原因就是无法访问蓝灯的服务器。能否按https://github.com/getlantern/forum/issues/1840#issuecomment-260143243 这里所说手工上传日志呢？

**Comment by itgoyo** [comment]
@xuwenping123 一般传图可以尝试优先传到图床，然后再markdown格式复制过来，个人推荐一个免费实用的图床，叫极简图床。Chrome拓展里有插件。图片直接复制粘贴，不用上传，直接自动生成Markdown代码

**Comment by itgoyo** [comment]
[lantern.zip](https://github.com/getlantern/forum/files/1031218/lantern.zip)
@p3rcya  @xuwenping123 的log已由我代替上传，他那边网络原因不方便上传。

**Comment by orbancanon** [comment]
@xuwenping123 不好意思现在才回。所有Lantern服务器的https证书都被篡改了，Lantern为了安全起见，不允许连接。

你同事在同一网络能用的话，那应该是你自己电脑上装的什么软件做了手脚。如果方便的话，重装干净的系统应该可以解决。

**Comment by qcind** [comment]
lantern pro. version?
how does it feel like?

**Comment by xuwenping123** [comment]
@orbancanon 你好，我这是台式机，因为lantern重装的话不太现实。是这样，可以使用什么来检测下是什么软件对Lantern服务器的https证书进行了篡改么？

**Comment by orbancanon** [comment]
@xuwenping123 你想想最近装过什么吧？但这种卸也有可能卸不干净。

或者这样，你把C:\Users\Administrator\AppData\Roaming\Lantern 这个目录删掉，再重装3.7.0试试。这样会使用内置的服务器把Lantern启动起来，然后去获得新的配置。

**Comment by xuwenping123** [comment]
@orbancanon 哎，最终还是选择了重装电脑，还好重装后解决了问题。。。
