### ISSUE TITLE
很抱歉，我们无法连接到蓝灯的服务器。请检查您的网络连接并重试。

### ISSUE THREAD

**Issue by smileyusd** [getlantern/forum#3058]
打不开？什么毛病？已经是最新版的了，昨天用的还是正常的

**Comment by chengziqing** [comment]
64,快到了，每年都这样。其他VPN估计也是

**Comment by kk-hua** [comment]
大概什么时候能用

**Comment by gloria1992** [comment]
我今天也是这样，前两天还正常，今天一打开就不信，我买了专业版，明年才到期啊

**Comment by gloria1992** [comment]
64快到了是啥意思？？

**Comment by ben474178556** [comment]
今天一打开就不行，昨天还可以的，以为网络问题呢

**Comment by gloria1992** [comment]
我也是，还以为突然就不支持校园网了呢

**Comment by smileyusd** [comment]
我也是才买不久的，要不要这么坑哟，
刚才去问了另一个人，他用的还是免费版的，居然可以正常使用。
什么鬼？

**Comment by gloria1992** [comment]
最开始我也用的免费版，但是网速限制我就买了一年的专业版，而且我之前已经用了好几个月了，一直没啥毛病的。今天电脑手机都用不了，简直了。。。

**Comment by smileyusd** [comment]
估计是他们那边出问题了

**Comment by TimYi** [comment]
我也是专业版遇到了这个问题，希望能尽快修复。不过貌似还可以上google.

**Comment by gloria1992** [comment]
哎呀，我试了下，果然能用，谢谢你，能用谷歌就够了，科研狗伤不起，查资料都要翻墙。

**Comment by yyhyplxyz** [comment]
为什么6.4快到了，就不能翻墙了……

**Comment by mengyuxingchen** [comment]
我这边虽然显示不能连接，但是google，油管都可以正常上

**Comment by Griffin1** [comment]
我的显示无法连接，但却能正常使用hhh

**Comment by orbancanon** [comment]
是的，有个服务故障，导致界面显示不能连接，但Lantern能正常使用。正在抢修中

**Comment by NoKeqi** [comment]
...我以为是我的电脑问题，我浏览器重装了不行，原来大家都有这个问题

**Comment by JiaweiGitHub** [comment]
什么时候可以修好？

**Comment by zzn130** [comment]
我也一样，显示无法连接但实际上是能用的

**Comment by Jannister** [comment]
![tim 20170602105645](https://cloud.githubusercontent.com/assets/21797573/26709032/57554f92-4782-11e7-811d-33cfabdf1a0d.png)

**Comment by acaesar17** [comment]
我的也不能用，什么时候可以恢复使用？

**Comment by huanghe666** [comment]
什么时候能用，给个回复。昨天刚买的专业版

**Comment by Jannister** [comment]
估计要到下周一，哈哈。毕竟后天是全国禁网日，开发团队也无能为力吧。

**Comment by tianya6666** [comment]
早上起来还正常，上班之后用电脑尝试连接，开始出现无法连接到lantern服务器，还以为是公司的网站限制了lantern，后来发现手机用无线网也一样连不上，手机APP一打开就闪退， 电脑倒是可以上网，但是手机咋办。而且付费才一个多月，还有一年时间，这么坑爹。现在好在电脑访问网页还能行，这要再过几天，访问不了网站，岂不是彻底没地方投诉去了？

**Comment by TerrrnceTam** [comment]
同樣問題，懷疑是專業版的服務器出了問題。手機上的卸載重裝之後用免費版就不會閃退和斷線。平板上沒有重裝就會不斷閃退。重裝之後選重設賬戶的話會一直停在處理請求的頁面。望儘快修復

**Comment by orbancanon** [comment]
楼上各位，现在已经完全恢复了。
