### ISSUE TITLE
同样的问题，联网也无法连接到服务器

### ISSUE THREAD

**Issue by yyhyplxyz** [getlantern/forum#3059]
zip文件上传失败，复制粘贴log文件字数超过限制了……可以给个邮箱让我传过去吗，本人邮箱：xxw9808@163.com

**Comment by yyhyplxyz** [comment]
后来尝试用word文档，上传成功了，希望能尽快解决
[Jun 02 01.docx](https://github.com/getlantern/forum/files/1046495/Jun.02.01.docx)

**Comment by Griffin1** [comment]
我的显示无法连接但却能正常使用hhh

**Comment by orbancanon** [comment]
是的，有个服务故障，导致界面显示不能连接，但Lantern能正常使用。正在抢修中

**Comment by orbancanon** [comment]
各位，现在已经完全恢复了。
