### ISSUE TITLE
lantern最新版3.0.4，请使用电信专用邀請碼 R4LR4H 

### ISSUE THREAD

**Issue by Boss198** [getlantern/forum#307]
lantern最新版3.0.4正常连接，请使用电信专用邀請碼 R4LR4H 
下载地址：https://github.com/getlantern/forum

![888](https://cloud.githubusercontent.com/assets/19481181/16576763/d23409ac-42c3-11e6-866b-b65c8de6d1de.jpg)

**Comment by p3rcya** [comment]
这里都是蓝灯用户。因为版面问题，请将邀请码发到其他论坛，谢谢！

**Comment by p3rcya** [comment]
请发到汇总贴中 https://github.com/getlantern/forum/issues/313

**Comment by CAOXP** [comment]
这难道还有 电信 与 非电信  的区别 ？

**Comment by p3rcya** [comment]
没有

**Comment by grchen** [comment]
输入我的邀请码 LFJ626 ，额外获得三个月的蓝灯专业版！

**Comment by antyiwei** [comment]
输入我的邀请码 YM3S368 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
![image](https://user-images.githubusercontent.com/26668105/29485103-cc121068-84fe-11e7-89bb-a61e3fa5081c.png)

**Comment by xumu** [comment]
输入我的邀请码 YGF8YJ7 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by KingToBest** [comment]
输入我的邀请码 9PS7XV 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
