### ISSUE TITLE
本来是专业版，忽然提醒我您的免费流量已用完

### ISSUE THREAD

**Issue by onlyatryyouknow** [getlantern/forum#3074]
本来是专业版，忽然提醒我您的免费流量已用完，懵逼，然后又重新授权了一遍，

手机上显示授权成功，但是电脑没反应

倒是变成了剩下原先免费版每个月的流量，就是变成了刚用的免费版一样？

**Comment by mengyuxingchen** [comment]
你试试用邮箱验证码方式授权喽

**Comment by onlyatryyouknow** [comment]
……已解决，蓝灯没有自动更新，我还不知道不是最新版……
