### ISSUE TITLE
今天一天都没连上google play

### ISSUE THREAD

**Issue by mengyuxingchen** [getlantern/forum#3075]
我是安卓专业版。今天一天都没连上google play，开完全代理也不行。什么情况？

[lantern.txt](https://github.com/getlantern/forum/files/1049564/lantern.txt)

**Comment by mengyuxingchen** [comment]
第二天依旧没连上，开发人员是过周末去了么？

**Comment by mengyuxingchen** [comment]
好吧，找到了问题所在。原因是我把蓝灯放到文件夹内就上不去google play。这应该算是bug？

**Comment by vitas1983** [comment]
@mengyuxingchen   蓝灯放到文件夹上？ 什么意思？ 我也是登不上google play

**Comment by GD-HBX** [comment]
同问防盗文件夹内是什么意思
