### ISSUE TITLE
[3.7.0安卓版Bug]代理全部流量 设置选项自动取消勾选

### ISSUE THREAD

**Issue by tianzry** [getlantern/forum#3078]
3.7.0版本的安卓蓝灯，设置-代理全部流量 这个选项返回之后会自动取消选择，请修复。

**Comment by mengyuxingchen** [comment]
对，有这个bug。而且一旦被清理后台进程，google play就上不去了

**Comment by p3rcya** [comment]
**请在本帖提供email**, 并使用应用内发送日志功能报告问题。若无法自动提交，请手动上传，方法见https://github.com/getlantern/forum/issues/1840#issuecomment-260143243 。请及时提供，否则无法调查，谢谢！

**Comment by tianzry** [comment]
@p3rcya  这只是一个应用程序bug，你们都可以再现，要啥日志……
