### ISSUE TITLE
win8.1升级到win10，专业账户不认设备了，支付宝找回账号失败

### ISSUE THREAD

**Issue by wskeith** [getlantern/forum#3099]
17年二三月买了一年的账号，一直到5月都用得很顺，最近两周升级到win10，打开蓝灯后居然提示让我升级到专业版？？？
输入支付宝账户点找回专业版账户，提示“无法根据以上信息找回账号”？？？
邮件反馈情况一周了也没见个回复？？？
@p3rcya 联系邮箱是ws_keith@126.com（非支付宝账号）
还需要我提供什么信息？除了支付宝我还可以提供payment reference ID。

**Comment by p3rcya** [comment]
请上传 payment reference ID

**Comment by temnia** [comment]
找回账号不应该用你买的时候所填的邮箱嘛，用支付宝账户干嘛

**Comment by wskeith** [comment]
@p3rcya payment reference ID: b110675730

**Comment by wskeith** [comment]
@temnia  登录提示用邮箱或者购买的支付宝账号，邮箱不记得了，用支付宝账号也不行

**Comment by wskeith** [comment]
@p3rcya  找到邮箱了，不用麻烦了，多谢：）
