### ISSUE TITLE
Google人机验证问题的原因是什么？Lantern团队有在解决吗？

### ISSUE THREAD

**Issue by ArvinLiuV** [getlantern/forum#3112]
频繁验证，甚至出现无法使用的情况。目前给的答复是尽力降低出现概率？能不能彻底解决？
![qq 20170612152924](https://user-images.githubusercontent.com/19185818/27023259-57770e66-4f84-11e7-84b1-ea4f5b9d0763.png)

**Comment by saronic** [comment]
太频繁出现了，严重影响使用。

**Comment by qcind** [comment]
lantern 代理服务机器IP，被Google防'DOS'攻击策略拦截；从而触发人机验证机制。

**Comment by mengyuxingchen** [comment]
他们说了，还有没办法解决，只能降低几率。

**Comment by ArvinLiuV** [comment]
n o
