### ISSUE TITLE
上京东也会出现EOF，不是说国内网站不代理的吗？

### ISSUE THREAD

**Issue by ArvinLiuV** [getlantern/forum#3114]
国内网站也走代理，严重影响网速啊。京东经常提示是否切换到海外版、淘宝直接就是台湾版。不是说国内网站不走代理吗？
![qq 20170613112021](https://user-images.githubusercontent.com/19185818/27064532-70bed0e2-502a-11e7-98ac-bb856b0394c1.png)

**Comment by orbancanon** [comment]
@ArvinLiuV 请确保你Lantern设置里的“代理所有流量”选项没有勾上。另外，请在论坛下载最新的3.7.2 版，所有国内的地址都直连。

**Comment by ArvinLiuV** [comment]
o
