### ISSUE TITLE
激活码激活成功但一刷新就掉线

### ISSUE THREAD

**Issue by uuandur** [getlantern/forum#3123]
1245423506@qq.com  @客户端已经上传了好几次的日志，麻烦管理员解决下。

**Comment by p3rcya** [comment]
请提供payment id，当时付款时收到的email

**Comment by uuandur** [comment]
id 1245423506@qq.com 我没有收到邮件

p3rcya <notifications@github.com>編寫：

**Comment by uuandur** [comment]
日期也不对

**Comment by p3rcya** [comment]
这个是付款不成功导致的，请提供当时的付款信息

**Comment by uuandur** [comment]
是激活码吗

p3rcya <notifications@github.com>編寫：

**Comment by uuandur** [comment]
9R97Q-WDJRD-Q2DVJ-64VKH-3VR8F -- [1y-usd, 未激活]  这是我通过代理买的

p3rcya <notifications@github.com>編寫：

**Comment by uuandur** [comment]
我又用激活码激活了一遍，已经搞好了

p3rcya <notifications@github.com>編寫：
