### ISSUE TITLE
关于Youtube视频无法正常播放的问题

### ISSUE THREAD

**Issue by p3rcya** [getlantern/forum#3134]
目前部分用户遇到Youtube视频无法播放的问题。这个是 googlevideo.com 域名403 造成的。而这个域名是通过HTTPS加密加载的，说明是YouTube方面的问题，禁止了访问。我们正在与YouTube方面联系解决这个问题。

外媒也报道了Youtube出现问题 http://nordic.businessinsider.com/youtube-is-down-friday-northeast-us-2017-6

为什么YouTube在这个节骨眼出现问题呢？大家众所周知。

### 大家可以在无法播放视频页面最下方点击“发送反馈”，直接向YouTube反馈，估计可以加速问题的解决。

![image](https://user-images.githubusercontent.com/20512438/27213383-4eca57ac-521b-11e7-9e02-ba22c1197e2b.png)

**Comment by KevinWangWLF** [comment]
感謝管理員的快速反應, 希望盡快解決, 辛苦了!

**Comment by p3rcya** [comment]
我们的服务器都是正常的，是YouTube服务器的问题，所以我们也只能等他们解决。我们只能向YouTube报告。

**Comment by lemonskkyt** [comment]
一起去trump twitter留言吧

**Comment by p3rcya** [comment]
无法播放视频页面最下方点击“发送反馈”，直接向YouTube反馈，估计可以加速问题的解决。

**Comment by ivoryue** [comment]
可不可以给个反馈的模板？应该反馈什么内容给油管？直接跟youtube反馈说明使用蓝灯vpn无法观看youtube视频吗？

**Comment by gawain-id** [comment]
大家重置一下IE试试

**Comment by shangzhou** [comment]
![image](https://user-images.githubusercontent.com/6767742/27213933-4a90d5e0-529c-11e7-9ee6-26cc7719db06.png)
还有一个问题，从昨天开始chrome 浏览器的这个九宫格点击后不再弹出Google的那些应用了。

**Comment by ivoryue** [comment]
我试了一下，我这边chrome 浏览器的这个九宫格点击后可以弹出Google的应用，是正常的

**Comment by hl614907630** [comment]
好了

**Comment by hl614907630** [comment]
哥們的好了，

**Comment by DezineLeo** [comment]
已经可以看了

**Comment by letaibai** [comment]
我说怎么播放不了了,原来是youtube的问题呀

**Comment by hl614907630** [comment]
又壞了

**Comment by RocStone** [comment]
同样的问题

**Comment by zzyb** [comment]
目前还没有恢复，已经向youtube发了反馈

**Comment by zzyb** [comment]
只能看直播内容

**Comment by wrbking** [comment]
感觉好了……

**Comment by wrbking** [comment]
时好时坏 实在是找不到规律。。。

**Comment by TalentSales** [comment]
感覺YOUTUBE在封鎖通過LANTERN過來的請求。

**Comment by KevinWangWLF** [comment]
是lantern被Google限制了, 一個很明顯的現象, 就是我用psiphon3(賽風)看youtube所有視頻都是正常的, 這說明youtube本身並沒有問題, 只是針對某種特殊的網絡環境進行了限制!

**Comment by RocStone** [comment]
那lantern就比较蛋疼了，我都付费了，结果。。

**Comment by chengziqing** [comment]
@KevinWangWLF 我想主要原因，是新版的蓝灯为了解决谷歌机器人验证问题，屏蔽了大量谷歌广告网址，才导致YOUTUBE把蓝灯屏蔽。屏蔽广告，不是正确i解决估计机器人验证的方法，因为那样会被访问的资源部待见。

**Comment by lemonbook** [comment]
今天开始的，上午时好时坏，现在完全不行了

**Comment by RocStone** [comment]
@chengziqing 没有屏蔽广告吧，我这边不打开Adblock，广告还是有的

**Comment by mengyuxingchen** [comment]
@chengziqing 哪屏蔽广告了，不懂别瞎扯。

**Comment by Junjiu** [comment]
不只youtube 啊，还有很多别的网站也看不了

**Comment by hl614907630** [comment]
蓝灯是谷歌投资这也封，还没好，时好时坏的

**Comment by KevinWangWLF** [comment]
@chengziqing 对于lantern是否为了解决人机验证问题而屏蔽了Google广告, 这个我并不了解, 不做多言, 而且我想, youtube视频无法观看应该也和这个无关吧, 我个人认为, 这里面的原因应该是有太多人都用lantern这一特定的网络环境去浏览Google, 进行搜索, 上youtube, 造成了Google有太多的数据异常, 而且人机验证问题应该也和这个有关, 不过这仅仅是我个人的观点, 仅供参考!

**Comment by rocknrollfly** [comment]
向 @p3rcya 反馈一个问题： 刚刚用蓝灯（专业版）打开youtube时，直接没有显示主页，而是显示了谷歌的验证界面，而且验证界面也显示不完整，无法验证，观察状态是无法连接www.gstatic.com ,无法与www.gstatic.com进行tls握手，貌似前两天不存在这个问题，赛风也不存在这个问题，请调查一下

**Comment by wrbking** [comment]
为什么总是看了两个视频之后就又看不了……隔段时间 好像又能看两个视频……

**Comment by rocknrollfly** [comment]
现在能打开能看了，但页面上还是不能加载www.gstatic.com

**Comment by GreatBigWhiteWorld** [comment]
影梭也不能看utube，很像是utube问题，但我的问题是，难道全世界看utube都出问题了吗？今天坏的时间非常诡异。

**Comment by lzhefuren** [comment]
唉，什么原因还不清楚吗？今天是谁宣布要干什么事的日子？！只有两个原因：1、有新技术屏蔽了所有相关IP的视频；2、谷歌向某些势力妥协了，答应在某些日子里屏蔽大陆IP的视频播放。

**Comment by GreatBigWhiteWorld** [comment]
@lzhefuren 是所有视频打不开，这个你还不能验证么，不是某些视频。

**Comment by hl614907630** [comment]
可以把赛风和蓝灯一块打开，就可以看

**Comment by lzhefuren** [comment]
@GreatBigWhiteWorld，你都没看明白我说的。1、大陆研发了某些技术，屏蔽了象Youtube这种网站的视频，其他内容不屏蔽，仅针对视频，因为今天实在太敏感了；2、Youtube（谷歌）向某些势力妥协了，在这个特定的日子里对来自大陆的IP屏蔽了所有视频。仅仅屏蔽某些视频有难度，也太露骨！

**Comment by wrbking** [comment]
@lzhefuren   其他VPN都能用，今天敏感啥。。。

**Comment by GreatBigWhiteWorld** [comment]
其实稍微想想就明白了，根本不是youtube那边出了问题

**Comment by bizos** [comment]
今天的确敏感，人家预告的是晚上9:00开始直播，看来墙又有新技术了。

**Comment by whatucamefor** [comment]
什么日子，我的一直能用啊，看的很流畅，不过一直用的是3.6.3，不知道有没有关系

**Comment by bizos** [comment]
靠，我vps的管理页面都打不开了，这次封的真是彻底。

**Comment by KevinWangWLF** [comment]
是的, Psiphon3 赛风就可以正常观看YouTube视频, 只是lantern不能看, 明显是lantern受到限制, 再者, 同样不太明白, 今天有什么敏感事件, 至少我对这方面"敏感事件"不太关注.
再说了, 国内IP本来都是在GFW内的, 外面的网站根本上不去, 本来就是屏蔽的, 想上外网都会给你redirect, 在这种情况下, Google还需要用技术手段屏蔽吗?

**Comment by bizos** [comment]
guo w g , 不敢说了，怕被喝茶。

**Comment by wrbking** [comment]
gwg不是天天直播吗。。。

**Comment by cyumeng** [comment]
确实，大杀器可以，但蓝灯不行。

**Comment by bizos** [comment]
今天可不一样哦，“核弹级爆料”

**Comment by piaocn** [comment]
这所谓的GWG爆料关我屁事，我上有土鳖就是为了学语言还有OpenCourse的，我管他爆什么东西出来

**Comment by TalentSales** [comment]
告訴大家一個不成熟的臨時解決方案~~~在打開LANTERN的基礎上，再打開Psiphon3~~~然后就一切正常了！！！雖然速度不是很快，但是可以正常觀看YOUTUBE~~~此時的速度基本上不影響心情~~~我這里試著還不錯！希望大家也試試看看~~~

**Comment by lemonskkyt** [comment]
好了

**Comment by alexjunkerchao** [comment]
希望能尽快解决，我的专业版可是付了钱的

**Comment by lemonskkyt** [comment]
.....看完一个视频又不行了

**Comment by zzyb** [comment]
试用楼上不成熟的建议成功！
蓝灯（LANTERN）加上赛风（Psiphon3）可以观看youtube视频网速不慢。

**Comment by zzyb** [comment]
等不及的可以试一试

**Comment by rocknrollfly** [comment]
貌似是最近两天加载不了谷歌的一些页面，慢慢调查解决吧

**Comment by KevinWangWLF** [comment]
Lantern+Psiphon3同时开, 的确可行, 不过此时(win10系统)貌似走的是Psiphon3的代理, 根本就没有走Lantern, 速度貌似和单独开Psiphon3的速度是一样的, 这样还不如单独开Psiphon3.

**Comment by wrbking** [comment]
@whatucamefor  特意下了3.6.3 依旧不能看。。  另外 500 Internal Server Error 是什么鬼，youtube主页都登不上去了

**Comment by TalentSales** [comment]
在我這里無論單獨開哪個都不靈，無法打開YOUTUBE，但是雙開就能打開YOUTUBE，還比較流暢。

**Comment by KevinWangWLF** [comment]
这就是个人网络情况不同, 以及电脑系统环境不同造成的差异了, 我的网络就是, 单独开Psiphon3是可以连上的, 而且速度还好, 至少youtube 480P是可以流畅观看的, 单独开Lantern, 打开网页的速度很快, 这一点是Psiphon3没得比的, 但不能看youtube视频, 两者同时开的话, 可以看youtube, 但速度和单独开Psiphon3的效果差不多, 而且貌似根本就没有走Lantern代理, 只是走的Psiphon3.(我的是win10系统)

**Comment by ArvinLiuV** [comment]
为什么手机端可以看呢？

**Comment by wrbking** [comment]
@ArvinLiuV  我手机也看不了，安卓端。

**Comment by INKRAINZZP** [comment]
你们和谷歌不是自家吗，怎么会出这种问题hhhh

**Comment by bearlittle** [comment]
这应该是谷歌屏蔽了使用蓝灯代网络环境下的YouTube视频内容，前段时间开始经常出现请求异常需要进行人机确认的情况，今天开始使用蓝灯代理上YouTube则无法播放视频，而使用其他代理软件则没有问题！

**Comment by whatucamefor** [comment]
@wrbking 那就不知道了，我用3.6.3是因为新版的开着不能上应用商店，不过我也试用了最新版，看youtube一点问题都没有，还有google人机验证，最近也没出现，我是win10 1703

**Comment by mengyuxingchen** [comment]
楼上那些说敏感的，请问为啥其他VPN就啥事没有？想多了吧你们

**Comment by p3rcya** [comment]
@mengyuxingchen 因为Youtube并不是一台服务器，某些服务器被DDOS下线，某些还是可以。所以这个只是具体线路的问题。

**Comment by p3rcya** [comment]
见 https://github.com/getlantern/forum/issues/3134

**Comment by EdwardAutumn** [comment]
但今天为止还没有恢复

**Comment by letaibai** [comment]
还是不能看啊

**Comment by zybrucewayne** [comment]
@p3rcya  你能别胡扯吗 为什么其他的vpn能看 就你们不能看 解决不了问题别推卸责任 我们付费是要你解决问题的 什么问题都要我们反应 那我还用蓝灯干什么

**Comment by piaocn** [comment]
楼上那个，人家还真不是胡扯，我一个交了3年费用的我都不急，你着什么急

**Comment by wrbking** [comment]
楼上那个，交3年费和交1年费的恐怕没什么差别吧，问题摆在那，就是没解决啊。

**Comment by mengyuxingchen** [comment]
@p3rcya 用了专业版从来就没顺心过，安卓版google play经常上不去，每次都要重装才行。还有完全代理退出就自动取消的bug，上报问题你也没个回应。3.7.2pc版自己奔溃差点把电脑网络搞废，现在youtube也看不了，还有个卵用？

**Comment by zybrucewayne** [comment]
@piaocn 因为我要看郭文贵爆料

**Comment by zybrucewayne** [comment]
蓝灯 @p3rcya  你们牛逼了 我在google play随便下了一个免费的vpn 竟然能看youtube

**Comment by INKRAINZZP** [comment]
你们这样不回复，不发你们与谷歌的沟通进展，难以服众。只会流失用户而已，我想很多人买VPN很大一部分是为了YouTube吧。这样搞让我们很难接受啊！

**Comment by Rich-dad** [comment]
付费用户很着急啊，看论坛评论已炸，我以为是VPN的事，看来的确是Google 问题，去Chrome看其他网站视频完全无影响，只有看YouTube是视频是卡到一半，而且还跳帧这个肯定不是蓝灯所能造成的，也没有那么大功力

**Comment by alei9195** [comment]
根本 不是youtube 的问题，这个是蓝灯自身问题。

**Comment by KevinWangWLF** [comment]
@Rich-dad, 这个已经确定, 别的VPN可以正常看youtube视频, 只有lantern不行, 很明显凡是通过lantern代理访问youtube的, 都被Google阻止了.

**Comment by snlo** [comment]
youtube被攻击信吗？

**Comment by moonrhino** [comment]
应该这麽说，蓝灯被攻击了

**Comment by LreeLenn** [comment]
结果：用Lantern这边不能看，有赔偿？

**Comment by moonrhino** [comment]
我还是觉得蓝灯好的，蓝灯的速度是我用过的vpn里最快的。希望Landen尽快恢复服务。肯定是被有针对的视频屏蔽了

**Comment by Rich-dad** [comment]
大家可以去看 推特，已经有人在反应youtube遭攻击了，蓝灯在这里肯定也无能为力，这是国家性的骇客攻击

**Comment by RochaC** [comment]
躺着中枪啊。。我想呢，怎么今天一天不能上lantern

**Comment by alei9195** [comment]
@Rich-dad 能给外链接吗

**Comment by ChA1eY** [comment]
确实是Lantern的问题，其他的渠道可以播放的，希望Lantern解决。

**Comment by alei9195** [comment]
可以播放了，哈哈

**Comment by mengyuxingchen** [comment]
现在youtube恢复正常了，不知道还会不会再崩溃

**Comment by alei9195** [comment]
已经又崩了

**Comment by mengyuxingchen** [comment]
是的，刚关掉再开，直接崩。我已经真心怀疑这是蓝灯自己的问题。youtube那边被攻击不假，然而这和蓝灯看不了youtube没半毛钱关系。

**Comment by mengyuxingchen** [comment]
我真心觉得蓝灯看不了youtube跟youtube被攻击没有直接关系。很可能是谷歌方面屏蔽了蓝灯，否则没法解释为什么其他vpn都可以正常的观看。其次，用蓝灯的经常会碰到google的人机验证，这是应该是通过蓝灯访问造成谷歌那边数据混乱，我一直上不去google play应该就是这个原因。现在波及到了youtube。
呵呵，我就看你们怎么解决这事。

**Comment by p3rcya** [comment]
各位能访问YouTube网页就代表蓝灯服务器没有问题，否则你国内给我上个YouTube网页试试。按照 @Rich-dad 说的，其他视频网站是可以播放的。这个是YouTube部分服务器的问题。其他VPN使用的数据中心不同，所以可能可以访问。但这个只是碰线路运气，最终只能由Youtube解决

**Comment by mengyuxingchen** [comment]
@p3rcya 哦，然后你蓝灯就这么倒霉的看不了？你难道不应该去具体了解一下为什么？什么原因造成的？还有google play各种连接错误，你也告诉我是谷歌的问题？你服务器是没有问题，到如果是谷歌把你屏蔽了呢？

**Comment by mengyuxingchen** [comment]
@p3rcya 刚才的话，有些强词夺理了，抱歉。不过蓝灯的问题真心不少，有时候也挺烦的。

**Comment by alei9195** [comment]
@p3rcya 之前没用蓝灯前是通过修改HOSTS主机域名，可以进入YOUTUBE但跟现在这情况一样不能播放视频，后来使用蓝灯就可以播放了。现在蓝灯的现象跟以前用HOSTS现象一样

**Comment by mengyuxingchen** [comment]
@alei9195 我记得那种现象应该是端口被封导致的吧。

**Comment by mengyuxingchen** [comment]
@p3rcya 刚刚好了一下，然而又不行了。好的时候我google play也能上去了，然而现在又都不行了。

**Comment by shuishengmu** [comment]
Mac 一点问题也没有。

**Comment by alei9195** [comment]
刚刚安卓版3.7.0版可以正常播放了，而且速度不错。但桌面版还是不行

**Comment by alei9195** [comment]
@shuishengmu 蓝灯有MAC版？

**Comment by shuishengmu** [comment]
@alei9195 有啊  刚才行 现在又不行了

**Comment by alei9195** [comment]
操，又不行了

**Comment by shuishengmu** [comment]
xx-net   Mac和Windows都没问题

**Comment by kilorocky** [comment]
反正我这两天都看不了视频，只能看直播，搞得我看了两天的south park和family guy

**Comment by Knuprebyc001** [comment]
也不亏啊 ( ͡° ͜ʖ ͡°)

**Comment by KevinWangWLF** [comment]
Win10系统, 还有Android手机, 现在的情况是:
使用Lantern Pro: Youtube网站可以进入, 但无法看视频, 而其他视频网站可正常进入正常观看;
使用其它代理或者VPN软件:   Youtube网站可以进入并正常观看视频, 而其他视频网站则是一切正常.
这样就有两种可能,
1st: 此次事件和youtube被攻击有关, 而Lantern所走的线路, 碰到了youtube那一部分有问题的服务器线路, 因此就遭遇上了;
2nd: 这个事与youtube被攻击无关, 是Lantern遭遇了Google的限制, 凡透过Lantern代理访问Youtube, 视频就无法载入.
无论是哪种情况, 都只是表面现象, 要真正找到问题的根本原因并解决问题, 光靠说是不行的, 而作为客户的我们, 调查能力有限, 最多是在youtube页面发个异常报告, 此时Lantern官方应该站出来, 与Google沟通, 参与调查, 找出根本原因, 再去解决, 而整个过程要透明化, 实时update, 我们希望看到的就是这个解决过程.

**Comment by flyever** [comment]
我自己的vps都无法看油土鳖视频，所以确实是今天某人爆料造成的。

**Comment by alei9195** [comment]
@shuishengmu 你确定windows能用？

**Comment by flyever** [comment]
大家洗洗睡吧，连美国人自己看着都有问题，散了散了。

**Comment by alei9195** [comment]
@flyever啥爆料？

**Comment by mathada** [comment]
油管大规模瘫痪
http://www.dailymail.co.uk/sciencetech/article-4611366/YouTube-thousands-users-world.html

**Comment by mengyuxingchen** [comment]
@KevinWangWLF 说的没错，这么拖下去无论对用户还是蓝灯官方都是损失。

**Comment by piaocn** [comment]
这个关Lantern鸟事，自己去twitter搜索youtubedown，看看多少人受影响，显然的蓝灯的服务器受到了波及而已

**Comment by hansanning** [comment]
希望能尽快回复啊

**Comment by hansanning** [comment]
希望能尽快恢复啊

**Comment by lemonskkyt** [comment]
本来压根不知道什么GWG，真是好样的

**Comment by lemonskkyt** [comment]
好像节点是 日本 没问题，美国就没法看

**Comment by harry0060** [comment]
油管现在已经好了 但为何还是不行呢
免费版用其他电脑反而可以看 怎么回事

**Comment by alei9195** [comment]
@harry0060 不能吧，刚试了

**Comment by Carol1992** [comment]
视频播放请求报403

**Comment by alei9195** [comment]
刚把桌面版装 回3.7.0版居然可以用，但重启电脑会不会自动升级啊，这样看来应该是蓝灯的问题了

**Comment by alei9195** [comment]
测试了几次，确实是蓝灯最新版的问题了，降回以前的版本OK

**Comment by harry0060** [comment]
我试了两台电脑 同一个网络下新装免费版 飞一样快

**Comment by alei9195** [comment]
好像可以了？最新版

**Comment by harry0060** [comment]
没有 都是不行

**Comment by christdaisy** [comment]
3.7.2和3.6.3 都看不到youtube的视频，等吧。。

**Comment by letaibai** [comment]
我想问下有没有具体的恢复时间?

**Comment by rocknrollfly** [comment]
都是蓝灯使用了因youtube遭攻击而被谷歌拒绝的中国ISP通道造成的，无法加载谷歌的一些网址页面，前两天还好好的，使用其他国家线路好像就行了，麻烦蓝灯官方快点解决

**Comment by wrbking** [comment]
怀念我的lantern，何时能够修复。

**Comment by EdwardAutumn** [comment]
貌似回复了，给我切换成了日本接点就好了，虽然导致了twitch不太稳定

**Comment by qimilan** [comment]
我也是不行啊

**Comment by p3rcya** [comment]
主要看政府是不是因为郭文贵爆料继续攻击Youtube 

油管大规模瘫痪
http://www.dailymail.co.uk/sciencetech/article-4611366/YouTube-thousands-users-world.html

**Comment by bangyangyao** [comment]
这样甩锅有意义~？！给个解决方案啊。买lantern就是为了看youtube，现在看不了，请退钱。

**Comment by leiqin** [comment]
请不要甩锅，我换了个vpn就能看youtube了，蓝灯还是不能看。再说瘫痪的时间段早过了，现在早恢复了，只有蓝灯还没恢复。

**Comment by p3rcya** [comment]
和你说了，是Youtube具体线路的问题。

**Comment by LunarisDream** [comment]
我的目前好使了

**Comment by GreatBigWhiteWorld** [comment]
http://downdetector.com/status/youtube

**Comment by letaibai** [comment]
现在可以看了

**Comment by lemonskkyt** [comment]
反正日本节点能看，但是基本都是美国节点很蛋疼，运气好分到日本节点一切正常

**Comment by piaocn** [comment]
今早上试了一下，可以看了，用的是一个日本的IP，不知道能正常多久

**Comment by zzyb** [comment]
我的已经可以正常使用了。

**Comment by zzyb** [comment]
恢复了

**Comment by sxswisdom** [comment]
可以看啦

**Comment by KevinWangWLF** [comment]
youtube breakdown的事, 确实有这个新闻, 也确实有某某人爆料的新闻, 
不过仅凭这些因素, 根本无法确定问题的本源, 也不能因为这样就安然无事了, 这样处理问题会引起争议.
之前经过多次测试, 只有Lantern代理受到了影响, 其它大多数VPN或代理软件都正常.
发生这种情况, 有可能是Google有意识的屏蔽Lantern, 如果不存在屏蔽, 确实是Lantern遭遇了youtube那一部分有问题的线路, 而其它大多数代理都没有遇到.
这样就要思考一下, 有没有可能是Lantern本身使用的通道, 或者是切换节点的问题?
这些技术方面的问题需要官方去研究和解决, 特别是针对切换节点的问题, 我在Lantern内部利用提交功能是提交过的, 但却没有回复, 话说回来, 我提交了几个问题了, 都一个月了, 还是没有回复, 请管理员看看, 这到底是什么情况? 谢谢!

**Comment by p3rcya** [comment]
现在Youtube已经恢复正常了。对于其他问题，请问能否在这里重复下

**Comment by Aboutchi** [comment]
厉害。。。youtube也给摆定了。。。。

**Comment by mengyuxingchen** [comment]
@p3rcya 安卓版有些节点上不去google play。完全代理那里退出到上一界面就会自动取消（我甚至都不知道那功能起作用了没有）。还有就是3.7.2有点不稳定，可能会导致网络无法连接。

**Comment by mengyuxingchen** [comment]
@Aboutchi 那是youtube自己解决的。

**Comment by alei9195** [comment]
我觉得蓝灯一点服务意识都没有，为啥别人的VPN可用蓝灯不可用。这就是问题，不管是不是线路问题，作为商家蓝灯你就应该为用户去解决问题。OK?

**Comment by alei9195** [comment]
还好只买了一年的，一年后再看情况吧。

**Comment by KevinWangWLF** [comment]
@p3rcya 我之前提交了几个问题, 比如android客户端闪退问题, 软件不稳定问题, 要求开启节点选择功能, 等等, 有的已经提交将近一个月都没回复,  现在有些问题已经解决, 眼下最重要的就是节点选择功能, 这次的事件, 应该和节点选择也有关联, 请尽快反馈给官方, 尽快处理, 谢谢!

**Comment by shuishengmu** [comment]
一直对lantern比较满意，安装就能用，不像别的软件用户名啊，密码啊什么的，特别繁琐。虽然有时候莫名的出现问题，但是经过折腾就能解决，速度不也不错。现在就差ios的了，希望尽快开发。
另外最讨厌一些人，掏了钱买了软件，就 大爷一样，这个不对那个不行，是花了钱，都想正常用，那也稍微容忍一下别人可不可以。
一年就那点钱，省了多少事情，那么辛苦找免费的，你时间不值钱啊~
我不是lantern什么托，估计人家也不需要，心平气和的去考虑问题，做事情，不要那么浮躁。

**Comment by harry0060** [comment]
@shuishengmu 终于有人出来讲些公道话了 支持一个

**Comment by Jayhello** [comment]
还是不行啊，我这里一直不能看
![image](https://user-images.githubusercontent.com/16144935/27258444-198a3800-542d-11e7-9efe-36026c36cc89.png)

**Comment by KevinWangWLF** [comment]
@Jayhello 现在整体上基本恢复了, 如果还是不行, 就换个版本试试看

**Comment by mengyuxingchen** [comment]
的确这件事主要原因是因为youtube，但蓝灯也不是一点问题没有。一直以来的各种问题，虽说不大，但也没到可以忽视的地步。其次蓝灯在这件事上并不是没有任何处理能力，因为到事件中后期蓝灯的某些节点是可以正常连接的，蓝灯不应该趁这个机会赶紧将用户使用这些有效节点来临时解决事件么？然而蓝灯什么都没有做，就这么把用户晾着。再加上大部分vpn都没有受到影响，自然会造成用户强烈不满。有时候只发一个公告是不够的。

**Comment by mengyuxingchen** [comment]
希望蓝灯能在此事吸取经验教训

**Comment by LunarisDream** [comment]
我个人认为软件开发没有大家想象的那么简单，出问题也不是那么容易就能解决的，尤其是这种不止一方面出的问题（蓝灯和YT都是）。谷歌有可能是测试针对了蓝灯的服务器，也有可能是因为有人在用蓝灯来做一些spam或DDoS来导致所有人都必须答captcha。事情没那么简单就不要要求简单的解决方案，随便甩锅。毕竟蓝灯的devs也不想让自己的服务这样瘫痪。

**Comment by KevinWangWLF** [comment]
@mengyuxingchen, 不错, 从商家的角度来讲, 帮助客户解决困难和实际问题永远是最关键的, 只发一个通告, 过分强调外界原因, 弱化甚至是规避自身的问题, 难以服众, 这是工作原则和态度问题, 对于客户来讲, 并不是钱多钱少的问题, 这关系到商业态度和商业信用, 如果客户服务做得不好, 肯定会招来非议.

**Comment by s081222** [comment]
我啟動了藍燈，但是上牆外網頁依然是“無法訪問此網站”  這是什麼問題，如何解決！謝謝

**Comment by mengyuxingchen** [comment]
@s081222 单独开贴详细描述你的问题。你说的太笼统了。

**Comment by BooleLean** [comment]
我重新安装了下，可以用了

**Comment by rocknrollfly** [comment]
现在可以看了，谢谢蓝灯团队。但谷歌页面上还是加载不了一些连接例如www.gstatic.com

**Comment by rocknrollfly** [comment]
一些网站的页面赛风能显示完整的蓝灯都显示不完整

**Comment by LINDA0207** [comment]
@p3rcya 还是不可以播放啊，欢乐chrome还是不行！！！如果是这样还是帮我退了好了，一下子买了3年。。。。

**Comment by wglantern** [comment]
还是看不了，一直在缓冲

**Comment by ChaoCheung** [comment]
正确姿势请看，https://www.v2ex.com/t/368608

**Comment by ChaoCheung** [comment]
![image](https://user-images.githubusercontent.com/17491666/27293364-c4b1dec4-5548-11e7-8349-1d49e3efa449.png)
 直播看不了，但是视频可以，所以还有点缺陷

**Comment by zhangjunwen** [comment]
我的一样， 一台电脑能看， 另外一台看不了， 手机网页也看不了， APP也看不了， 忒奇怪了， YOUTUBE网页打开流畅  一直加载。。。

**Comment by mengyuxingchen** [comment]
@zhangjunwen youtube应该还没有完全好，蓝灯也就只能有部分节点能看，比如日本。不过蓝灯没有选节点的功能，所以只能看脸。

**Comment by ever391** [comment]
看不了，整了半天，大半夜，依然看不了，我的是香港服务器，依然不能有作何用。。。。

**Comment by snoopykei** [comment]
确实, 现在是只能看live不能看普通的视频... 真的不知道为什么.

**Comment by harry0060** [comment]
现在美国节点都能用啊 怎么不能呢

**Comment by marxpayne** [comment]
我们的系统检测到您的计算机网络中存在异常流量。此网页用于确认这些请求是由您而不是自动程序发出的。为什么会这样？


IP 地址：47.52.58.9
时间：2017-08-08T17:17:25Z
网址：https://www.youtube.com/watch?v=ubuWLe7fO0o&spfreload=10

**Comment by hansanning** [comment]
您好，这两天确实打开YouTube视频，谷歌都说我流量有异常，要做人机验证。这个问题6月份出现过我之前和很多网友反应过；更新新版本后没有问题了，但是最近两天又出现了……

2017年8月9日 01:20，"marxpayne" <notifications@github.com>写道：

我们的系统检测到您的计算机网络中存在异常流量。此网页用于确认这些请求是由您而不是自动程序发出的。为什么会这样？

IP 地址：47.52.58.9
时间：2017-08-08T17:17:25Z
网址：https://www.youtube.com/watch?v=ubuWLe7fO0o&spfreload=10

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/getlantern/forum/issues/3134#issuecomment-321023457>,
or mute the thread

**Comment by zhengdahanlei** [comment]
为什么我用谷歌浏览器打开YouTube，可以显示网址，但是却不能显示视频
[打开不显示.docx](https://github.com/getlantern/forum/files/1566575/default.docx)
