### ISSUE TITLE
youtube已经修复了吗？我好像可以正常看了。

### ISSUE THREAD

**Issue by wrbking** [getlantern/forum#3150]
再更新：换地区还是有用的……使劲换，重点关注土耳其……我又能看视频了////

更新，当我什么都没说过吧。。。就爽了十几分钟。/////

原帖：
刚刚在前面几个帖子看到可以修改地区来正常看视频，于是我从美国改到日本，再改台湾，都不能正常看。
然后我又改到土耳其，能正常看了，我再改回美国，还是能正常看，日本，台湾都正常。。。。。

你们可以试试这个方法，本人mac端，3.7.2的lantern
改地区的方法，旧版网页，在底部；新版网页界面，在右上角个人设置里面。

我不知道是不是因为已经修复了所以可以正常看视频，还是因为改了地区，所以可以正常看视频……

**Comment by harry0060** [comment]
察~ 就半个小时又不行了 土耳其都不行

**Comment by wrbking** [comment]
@harry0060 我已经行了两次了…… 地区换来换去，开关一下lantern，感觉还是可行的。

**Comment by GFWfuck** [comment]
手机版蓝灯可以正常观看......应该不是蓝灯的锅
