### ISSUE TITLE
充值了两年，然后发现专业版功能有问题

### ISSUE THREAD

**Issue by eukire** [getlantern/forum#3177]
1.系统是macos 10.12.5，谷歌版本 59，购买两年的专业版，一直提示流量不足
2.点击显示蓝灯，进去每次都是非专业版，点击登录不需要验证码直接登录成功
3.下次再点击显示蓝灯，进去还是非专业版。
4.显示专业版到期时间“您的专业版账户将在 -17339 天后，即 1970/1/1 过期”
5.问题已持续三个多月，只有刚买的时候是好的，一直觉得是bug，会修复的，但是升级到3.7还是坏的。最近终于忍无可忍前来发帖。

希望问题得到解决或退款。多谢。

**Comment by 1409521116** [comment]
我还有半年多，现在完全不能用，反应问题又不理我，同要求退款，这种服务就不配收钱

**Comment by tuzhao** [comment]
我的lantern今天突然也不能用了,不知道什么情况.昨天还可以用.

**Comment by p3rcya** [comment]
请提供当时付款邮件里面的payment id

**Comment by eukire** [comment]
@p3rcya 不一定能找得到 我绑定的邮箱是imyyan@163.com

**Comment by p3rcya** [comment]
你绑定的邮箱是 eukire@163.com

**Comment by BenjaminXi** [comment]
我的今天也用不了

**Comment by turnerpoh** [comment]
我今天刚购买了两年的专业版，希望不要遇到以上问题~
