### ISSUE TITLE
蓝灯手机版已经很久不能用了！WHY!I!

### ISSUE THREAD

**Issue by GODDAMN-IT** [getlantern/forum#3179]
我试用了几个月高速稳定，然后一下买了2年！结果就用了个把月就完全无法访问了！找了很久才找到这里来！希望帮忙解决下！谢谢！

**Comment by GODDAMN-IT** [comment]
希望负责人能留个邮箱把日志信息发给你！

**Comment by p3rcya** [comment]
请报告网络环境，访问时段。
**请在本帖提供email**, 并使用应用内发送日志功能报告问题。若无法自动提交，请手动上传，方法见https://github.com/getlantern/forum/issues/1840#issuecomment-260143243 。请及时提供，否则无法调查，谢谢！

**Comment by GODDAMN-IT** [comment]
我的是电信200M光纤！一般是晚上！

**Comment by GODDAMN-IT** [comment]
附件我怎么提供？？？

**Comment by GODDAMN-IT** [comment]
mrzhangwanyu@outlook.com邮件是这个！日志我已经提交了！
