### ISSUE TITLE
Green说要停后，来这看了看后，居然公告说啥，再看后吓得我不敢买了

### ISSUE THREAD

**Issue by lanmingle** [getlantern/forum#3186]
首先我就是看下蓝灯的权威问题，能不能在国内用，但是看了那公告后，暂时保持呵呵！

之后浏览其它的，说蓝灯的服务质量什么的，马上吓得我来发个 issues 大声告诉你们，还是去买香港服务器自己搭建吧，额！还是不这样折腾了，到时候看看是否还有别的用，吃瓜群众保持围观。

**Comment by androidNdk** [comment]
我买了green 2年。妈蛋，才用1个月，真日了狗了。

**Comment by zR-Zr** [comment]
green 我都是 三个月一买......

**Comment by reaper12** [comment]
可以退款的啊
