### ISSUE TITLE
不开蓝灯就没网

### ISSUE THREAD

**Issue by Michael-Wallace** [getlantern/forum#3246]
我现在是不开蓝灯的情况下正常浏览网页都打不开，开了才能看见网页（没有打开全部流量代理）。请问该怎么解决这个问题

**Comment by Alvin9999** [comment]
依次打开IE浏览器—工具—internet选项—连接—局域网设置，把“为LAN使用代理服务器”前面的勾去掉即可：
 
![11](https://user-images.githubusercontent.com/12132898/27756281-cc2f2f24-5e28-11e7-85c6-83b6d501d1eb.png)

**Comment by little321tony** [comment]
你用360断网急救箱就搞定啦！

**Comment by Jannister** [comment]
3.7.2版本就已经解决这个问题了，建议你升级到最新的3.7.3

**Comment by Michael-Wallace** [comment]
谢谢各位
