### ISSUE TITLE
我是lantern付费用户，我的一台电脑上的lantern突然无法翻墙

### ISSUE THREAD

**Issue by Immortalt** [getlantern/forum#3263]
我的其他电脑上的lantern都是正常的，只有一台电脑突然出问题，可以正常上网，但是无法翻墙，重装lantern也没有用，请问怎么办，有没有修复的办法或者彻底卸载lantern的方法。总不能逼我重装系统吧？

**Comment by temnia** [comment]
什么系统什么版本的lantern，问题要写清楚才好处理

**Comment by mikedchavez1010** [comment]
用的什么浏览器？

**Comment by Immortalt** [comment]
我最终自己解决了这个问题。必须彻底卸载蓝灯然后重新安装——蓝灯的卸载程序卸载不彻底，在通过卸载程序卸载后需要定位到软件安装目录，删除目录下所有文件才算彻底卸载。
