### ISSUE TITLE
lantern怎么设置全局代理

### ISSUE THREAD

**Issue by andylee1890** [getlantern/forum#3293]
有没有功能可实现类似于VPN的全局代理或者智能代理

**Comment by itgoyo** [comment]
有的，用软件就可以了，lantern设置里边的全局代理其实不是真正的全局，这个要用软件来设置https代理或者socket代理

**Comment by andylee1890** [comment]
什么软件可以设置, 具体怎么做

**Comment by mikedchavez1010** [comment]
用代理者Proxifier
