### ISSUE TITLE
电信网络打开lantern一直在转圈，连接不上

### ISSUE THREAD

**Issue by jormin** [getlantern/forum#3299]
电信网络打开lantern一直在转圈，连接不上

**Comment by little321tony** [comment]
你先用360断网急救箱检查一下本地网络是不是正常

**Comment by p3rcya** [comment]
请先按照此贴 https://github.com/getlantern/forum/issues/1902 自查所有步骤。大部分问题都可以按照此贴解决。

如果还是无法解决，请报告网络环境，访问时段。
**请在本帖提供email**, 并使用应用内发送日志功能报告问题。若无法自动提交，请手动上传，方法见https://github.com/getlantern/forum/issues/1840#issuecomment-260143243 。请及时提供，否则无法调查，谢谢！

**Comment by jormin** [comment]
是这几天突然出现的问题，在公司也正常，在家里就不行，`Windows`和`Mac`下都连接不上，一直转圈，家里是电信网络，不使用`Lantern`时也能正常上网，打游戏看电影都很正常，就是`Lantern`连接不上。

**Comment by ouyanglee** [comment]
[lantern.txt](https://github.com/getlantern/forum/files/1251001/lantern.txt)

**Comment by ouyanglee** [comment]
[lantern.txt](https://github.com/getlantern/forum/files/1251002/lantern.txt)
941027155@qq.com

**Comment by p3rcya** [comment]
请给在发帖前先按照[蓝灯无法使用的解决办法](https://github.com/getlantern/forum/issues/1902)自行解决。自行解决问题通常只需要几十分钟。管理员调查解决问题需要几天至几周。

若无法按照[蓝灯无法使用的解决办法](https://github.com/getlantern/forum/issues/1902)自行解决，愿意等待管理员人为调查的，请按照如下格式发帖。https://github.com/getlantern/forum/issues/3536 不按照格式发帖无法调查，谢谢。
