### ISSUE TITLE
设备授权绑定后，能解除设备绑定重新绑定新的设备吗？

### ISSUE THREAD

**Issue by sincycai** [getlantern/forum#3333]
为了更加的方便生活、工作，日常用的设备比较多，个人PC MAC 安卓手机  苹果手机都会想翻墙，只能绑定3个设备会不会太少了？还有就是如果设备坏了怎么办？最后蓝灯有售后或者客服吗？

**Comment by cdyberlin** [comment]
我也想问这个问题

**Comment by mengyuxingchen** [comment]
在账号管理中可以把不需要的设备移除，什么平台都可以直接操作。

**Comment by sincycai** [comment]
嗯嗯，已经买了，确实可以解绑、退出登录
