### ISSUE TITLE
输入我的邀请码 YJJTW25 你懂的~~！

### ISSUE THREAD

**Issue by sincycai** [getlantern/forum#3334]
输入我的邀请码 YJJTW25 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by lumotuwe** [comment]
输入我的邀请码 MYG74Z 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by lumotuwe** [comment]
输入我的邀请码 MYG74Z 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
输入我的邀请码 MYG74Z 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
输入我的邀请码 MYG74Z 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
重要的事情说三次********
