### ISSUE TITLE
使用了一下感觉速度非常快。买了专业版后，网速极慢。

### ISSUE THREAD

**Issue by zhuxianzhiniko** [getlantern/forum#3347]
RT..同一网络环境，之前翻墙下载大约在2M-4M每秒。现在连下载都下载不了。

youtube,免费高速流量时候1080P，都能正常观看。现在直接卡住。网络比免费的低速还慢。什么鬼！刚买2年的。

**Comment by little321tony** [comment]
开玩笑

**Comment by yaodongb** [comment]
1080无卡顿

**Comment by zhuxianzhiniko** [comment]
..隔天后，又恢复正常了。。刚买的时候异常慢。。
