### ISSUE TITLE
lantern 蓝灯最新邀请码JGRGW9 免费获取三个月专业版本使用权

### ISSUE THREAD

**Issue by zhouoyu** [getlantern/forum#3370]
使用此邀请码：JGRGW9，免费获取三个月专业版本使用权。

**Comment by youngjy** [comment]
输入我的邀请码 YYXRFHS 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by stephen666** [comment]
# 蓝灯lantern最新邀请码 Y2947HH 永久有效！获取三个月免费！

## 请输入我的蓝灯lantern邀请码 Y2947HH 来获得三个月免费的蓝灯专业版！使用后请留下你的邀请码，我也会使用你的邀请码续费的！

![lantern-referral-code](https://user-images.githubusercontent.com/11013738/28974650-a4aaf03a-7969-11e7-8670-954811202ff0.png)
