### ISSUE TITLE
买了专业版还是翻不了墙?

### ISSUE THREAD

**Issue by dcdb723** [getlantern/forum#3371]
白天开着蓝灯下国服暴雪的游戏,不知道为什么会走蓝灯的流量,然后再开google之类的网站就开不了了,之前用的免费版,我刚刚以为流量用完了,就买了付费的Pro,结果还是不能翻墙???

**Comment by dcdb723** [comment]
我可以肯定的告诉你们,我没开全局代理.

**Comment by mengyuxingchen** [comment]
专业版没有流量限制，你是不是没登录啊

**Comment by little321tony** [comment]
卸载了重新再安装试试吧！

**Comment by dcdb723** [comment]
@mengyuxingchen @little321tony 谢谢回复,好像是因为我chrome装了SwitchyOmega的问题,我把这个插件关了就好了,但是我mac刚装上去什么别的插件都没装为啥用不了呢=.=看了置顶的帖子,只教了windows的IE浏览器怎么设置,不知道有没有人会.

**Comment by dcdb723** [comment]
已经解决了
