### ISSUE TITLE
部分安卓用户无法观看YouTube视频的解决方案

### ISSUE THREAD

**Issue by p3rcya** [getlantern/forum#3384]
这和上次一样，是因为某人YouTube的视频，YouTube服务器被攻击，而导致的。遇到问题的安卓用户，可以使用浏览器访问YouTube观看。电脑不受影响。

**Comment by little321tony** [comment]
蓝灯no.1

**Comment by zybrucewayne** [comment]
我想知道你是如何舔着脸胡扯的 正大光明说假话 和上次一样 只要换了其他的vpn 就能看 但是就你们lantern不能看  现在更夸张 用电脑看个网页卡半天 一直要验证 还刷不出来  意思就是我看不了了 反正明年到期我100%不用你们的垃圾产品

**Comment by xiyangzk** [comment]
好几个人都提到，如果pro版可以按月、按季度购买的话，都愿意尝试一下。
