### ISSUE TITLE
蓝灯邀请码

### ISSUE THREAD

**Issue by Pengfei-Gao** [getlantern/forum#3399]
输入我的邀请码 5SUT6R 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by stephen666** [comment]
# 蓝灯lantern最新邀请码 Y2947HH 永久有效！获取三个月免费！

## 请输入我的蓝灯lantern邀请码 Y2947HH 来获得三个月免费的蓝灯专业版！使用后请留下你的邀请码，我也会使用你的邀请码续费的！
![lantern-referral-code](https://user-images.githubusercontent.com/11013738/28964811-031b404e-7941-11e7-8b84-3849ebd50b95.png)

**Comment by YIinGitHub** [comment]
# **蓝灯lantern最新邀请码 Y2947HH 永久有效！获取三个月免费！**

**Comment by YIinGitHub** [comment]
# **蓝灯lantern最新邀请码 YMDF4CX 永久有效！获取三个月免费！**
![yqm](https://user-images.githubusercontent.com/30485071/29010870-0f55a08a-7b61-11e7-9d5a-ab5dee18a45c.PNG)

**Comment by meibujun** [comment]
输入我的邀请码 YJJ9W4F 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by feigu** [comment]
输入我的邀请码 6RVUDT 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by CQKang** [comment]
# 输入我的邀请码 _JVVCU2_ 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum****

**Comment by cjbs10086** [comment]
输入我的邀请码 95CM4S 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by cindy888** [comment]
For a free month of Lantern Pro, use this referral code: 4U6F55 ; You can download it from here: https://bit.ly/1M8x04u

**Comment by lorunsky** [comment]
输入我的邀请码 **K429UH** 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
