### ISSUE TITLE
这是怎么回事？我的账号无法登陆。我的手机是nextbit robin，购买了专业版后刷了LineageOS。然后就登陆不聊了，第一次登陆专业版是购买后自动登陆的。（下图附带支付宝购买记录，和免费版访问谷歌的图片，网络是通的叉叉是系统的图标显示问题。）

### ISSUE THREAD

**Issue by sltruman** [getlantern/forum#3420]
![3cf5eebf0fb9e1ed9f5e31f91eb36b20](https://user-images.githubusercontent.com/12881971/28398110-380def00-6d38-11e7-9ceb-c20c20daf322.png)

两个账号都无法登陆。
xfskyl@sina.com sliu.truman@gmail.com

![10c29a406619da0821ca973cedc375ca](https://user-images.githubusercontent.com/12881971/28398115-3d8c5502-6d38-11e7-8e09-a037bd181285.jpg)
![5452df12b62d09e063530ac04d23f70c](https://user-images.githubusercontent.com/12881971/28398534-305f38b6-6d3a-11e7-9a66-8a079ff28d73.jpg)

![605eaa39d65f08698cf45c54726791bf](https://user-images.githubusercontent.com/12881971/28398140-639d47e2-6d38-11e7-8d91-8f6cf2dfdcd9.jpg)

![11cdfb3879cdd478d85823a1a2f793f2](https://user-images.githubusercontent.com/12881971/28398144-66ba59b0-6d38-11e7-8ea6-3115f37d8d04.jpg)

![c36489b8be89748d7d9e8733671f338e](https://user-images.githubusercontent.com/12881971/28398123-4ce9de8e-6d38-11e7-833d-a7cb461aa7cc.jpg)

**Comment by sltruman** [comment]
如果有验证码的话，我并没有收到，无论是支付宝账号邮箱，还是谷歌邮箱，但我的谷歌邮箱停止过服务一次。
![6564f24bead7e6e900f17a58e2302658](https://user-images.githubusercontent.com/12881971/28398280-0db7e61a-6d39-11e7-8917-6268a74fcbe7.jpg)

**Comment by sltruman** [comment]
![a5ba540f633b817739fc457939c12bd1](https://user-images.githubusercontent.com/12881971/28398336-5dc7411e-6d39-11e7-972a-2981bf7964e6.jpg)

**Comment by p3rcya** [comment]
你的账号是 sliu.trumam gmail.com 请使用这个邮箱登陆

**Comment by sltruman** [comment]
这个邮箱不存在，我需要更改邮箱。不然我没有激活码。
