### ISSUE TITLE
无法续费，提示被另一用户使用

### ISSUE THREAD

**Issue by AllenBrook** [getlantern/forum#3430]
![image](https://user-images.githubusercontent.com/17419861/28420822-f8d4a294-6d95-11e7-9bec-2182ced42448.png)

**Comment by AllenBrook** [comment]
求解决！

**Comment by wyrainer** [comment]
汗，我刚刚专门注册了帐号准备提这个问题的。。。。

**Comment by AllenBrook** [comment]
为什么没有管理员反馈？？？

**Comment by myvipbackup2** [comment]
@p3rcya  同样遇到这个问题怎么解决？

**Comment by AllenBrook** [comment]
目前已经解决 成功续费 各位小伙伴 要续费的可以抓紧拉
