### ISSUE TITLE
＊＊付費版用戶＊＊無法翻墙

### ISSUE THREAD

**Issue by linthree** [getlantern/forum#3432]
您好，

我的電子郵件 linthree＠gmail.com

我是購買2年的付費版用戶，從昨日(2017年7月19日)晚上開始到今天, 我的桌上型電腦,出現網站被屏蔽的問題.

但用手機的lantern是正常的.

已按照 "蓝灯无法使用的解决办法" https://github.com/getlantern/forum/issues/1902,進行操作,仍出現網站被屏蔽的現象.

我上傳了日誌，麻煩您幫忙看看是什麼原因,謝謝.

**Comment by p3rcya** [comment]
已经通过邮件回复
