### ISSUE TITLE
免费获得蓝灯专业版额外使用时间，请使用邀请码 YYQDTXK 。

### ISSUE THREAD

**Issue by yangxiaojun1** [getlantern/forum#3488]
免费获得蓝灯专业版额外使用时间，请使用邀请码 YYQDTXK 。您可以在此处下载：https://bit.ly/1M8x04u

**Comment by meibujun** [comment]
输入我的邀请码 YJJ9W4F 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
