### ISSUE TITLE
登录youtube总要人机检验，醉了

### ISSUE THREAD

**Issue by muse458** [getlantern/forum#3492]

**Comment by little321tony** [comment]
装个谷歌浏览器，这样人机验证次数也不多，而且顶多也就是打个勾而已，省事

**Comment by huanghe2015** [comment]
使用的人太多，自然就会出现要填验证码的情况，所有VPN都这样。 @little321tony 谷歌浏览器只需要打勾是因为NoCaptcha的功劳，它会记录在打勾之前浏览器窗口里的光标轨迹，人所画出来的光标轨迹是不完美的，自然就能将机器人与人区分开来。

**Comment by Banana1130** [comment]
即使是谷歌浏览器，只要每次重启蓝灯，8-9成几率会人机测试（油管），不过打钩还算方便，无力的安慰

**Comment by sqken** [comment]
我也遇到了

**Comment by tsaosung** [comment]
我也是啊，每次搜索视频都要人机验证

**Comment by buranguo** [comment]
我的youtube就直接打不开了

**Comment by muse458** [comment]
只是直接打钩吗？不要选择相应的图片吗？

**Comment by little321tony** [comment]
装谷歌浏览器中，真心就打个勾，可以试试喔！

**Comment by buranguo** [comment]
不能访问youtube莫名其妙好了不到两天，又挂了，更甚的是这会连谷歌邮箱也不能登陆了。。。

**Comment by leewhitefly** [comment]
打钩还好，那个选图片的直接选到吐啊，比订车票的验证码都恶心

**Comment by wannihilation** [comment]
没遇到过，我金丝雀浏览器  输入我的邀请码 YM3FGUV 来获得三个月的蓝灯专业版！

**Comment by hhzhaoheng** [comment]
我的facebook被禁用好多次了，好像因为地址变的原因，我特么传了身份证和自己照片才解。

**Comment by tbirder** [comment]
@hhzhaoheng  你填好手机号，找回不就容易么？

**Comment by hhzhaoheng** [comment]
现在没事了，原先就是用手机注册的，禁用时候要求传照片和证件。
