### ISSUE TITLE
大家好，从最近vpn被查封这么多，我也加入lantern大家族啦。邀请码5KSJGV。

### ISSUE THREAD

**Issue by kinseigou** [getlantern/forum#3506]
购买pro版的lantern时，记得使用这个（邀请码5KSJGV） 哦。如果你购买一年就能获赠一个月的pro版lantern使用时间。如果你购买2年的那就能获赠3个月的Pro版lantern使用时间哦。

重点说3遍。      邀请码5KSJGV。                   邀请码5KSJGV。                  邀请码5KSJGV。

欢迎各位踊跃使用       I:-D I 笑

**Comment by mqygme** [comment]
用这个邀请码 6R3RWD，送蓝灯专业版高速不限流量三个月哦！
Apply coupon code 6R3RWD to get FREE THREE MORE MONTHS Lantern PRO!
