### ISSUE TITLE
分享一个蓝灯邀请码

### ISSUE THREAD

**Issue by lanpinterest** [getlantern/forum#3514]
邀请码YJ7C6T4  今天刚买的两年，额外送了三个月。如果有朋友要购买，可以用这个邀请码，保证可以用。可惜不能在苹果设备使用。不过不限流量看视频还是非常爽的！

**Comment by zm3333** [comment]
输入我的邀请码 YGWX8BW 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by mqygme** [comment]
# **6R3RWD** # **免费送三个月哦**

**Comment by frankredtiger** [comment]
KY67ZF   分享蓝灯邀请码，免费送三个月喔，两年专业版!

**Comment by windtreeliu** [comment]
输入我的邀请码 YMNT4SK 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by frankredtiger** [comment]
最新蓝灯邀请码  KY67ZF

2017-08-14 21:06 GMT+08:00 windtreeliu <notifications@github.com>:

**Comment by meibujun** [comment]
输入我的邀请码 YJJ9W4F 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by frankredtiger** [comment]
最新邀请码 KY67ZF 永久有效！！！！！请输入我的邀请码 KY67ZF
​ 来获得三个月的蓝灯专业版！使用后请留下你的邀请码，我也会使用你的邀请码续费的！！！！！

2017-08-24 19:21 GMT+08:00 meibujun <notifications@github.com>:
