### ISSUE TITLE
我一直无法收到专业版的恢复码，账号：sliu.trumam@gmail.com

### ISSUE THREAD

**Issue by sltruman** [getlantern/forum#3516]
希望管理能够查看一下什么问题。
![2017-07-22](https://user-images.githubusercontent.com/12881971/28562568-61c20f22-7155-11e7-85a9-2a7edd5c00fd.png)

**Comment by mengyuxingchen** [comment]
貌似用谷歌邮箱的都有这个问题

**Comment by sltruman** [comment]
这可怎么办？

**Comment by sltruman** [comment]
@p3rcya 试过在蓝灯里的“无法收到恢复码”的选项，邮箱收到的回复是无法自动恢复。

**Comment by orbancanon** [comment]
@sltruman 发过去的邮件被拒了呀。
![image](https://user-images.githubusercontent.com/20250571/28601288-e77890ca-71e9-11e7-9e3a-efdee47b7b09.png)

最初的错误是这样的，Google说这个邮箱不存在。
![image](https://user-images.githubusercontent.com/20250571/28601397-95ae957c-71ea-11e7-980a-37276da92497.png)

**Comment by sltruman** [comment]
@orbancanon 是的，最初我的邮箱是写错了，导致无法登陆专业版，后来纠正了，google的设置里面开启了拒绝吗？

**Comment by orbancanon** [comment]
@sltruman 因为被拒绝太多次，所以进Lantern邮件服务商的黑名单了。我刚刚把它从黑名单移除，你现在应该可以收到邮件了。

**Comment by sltruman** [comment]
@orbancanon 我这边已经解决问题了，谢谢。
