### ISSUE TITLE
最近专业版闪退什么原因？

### ISSUE THREAD

**Issue by merlin1985** [getlantern/forum#3535]
我的专业版今天上网也闪退什么原因啊？两个星期前登录还是ok的，我下载的应该是最新版本；
网络是移动宽带，访问时间晚上10点，已经按照#1840的方法都试过了，没有用啊；系统是win7 64位
我的email地址是merlin_1985@163.com
[lantern.zip](https://github.com/getlantern/forum/files/1176945/lantern.zip)

**Comment by p3rcya** [comment]
正在调查

**Comment by buranguo** [comment]
我的专业版也存在同样问题，而且现在youtube打不开了，还有的内网页面出现eof。
email:buranguo@gmail.com
系统：win8.1 64位

**Comment by merlin1985** [comment]
问题解决
把c:\Users<用户名>\AppData\Roaming\Lantern整个目录删掉，然后重装Lantern。
 必须这种方式删除，通过程序卸载不行。

**Comment by buranguo** [comment]
谢谢你的指点。我这里打不开youtube了，知道怎么解决吗？谢谢！

2017-07-27 22:06 GMT+08:00 merlin1985 <notifications@github.com>:

**Comment by orbancanon** [comment]
@merlin1985 是的，因为你之前手工把settings.yaml里面的地址改成了192.168.1.105:8787，现在电脑的IP地址一变，这个就无效了。

**Comment by merlin1985** [comment]
确实之前手工改过IP地址，多谢
在2017年07月28日 12:40，Orban Canon 写道：

@merlin1985 是的，因为你之前手工把settings.yaml里面的地址改成了192.168.1.105:8787，现在电脑的IP地址一变，这个就无效了。
