### ISSUE TITLE
致购买了专业版使用中却遇到bug的用户

### ISSUE THREAD

**Issue by ghost** [getlantern/forum#357]
因为现在是公测版，可能不稳定有bug。为了感谢用户提交bug帮助我们改进。所有在正式发布前购买的专业版用户，在正式版发布后，会获赠一个月的额外专业版。我们现在正在全力以赴修复bug。 

如果大家遇到bug，请欢迎提交到论坛上。我除了广告和水帖以外，我从来没有，今后也不会删帖。 立帖为证。

**Comment by dave1221** [comment]
我表示对@p3rcya的敬业和负责表示赞赏！！也请那些态度比较激进的用户多理解……但是既然涉及到收费，我一定会和网上某宝已有的对比，刚刚问了年费一百五且做了好多年，评论对速度稳定性都比较认可的产品。。我们的优势在哪里？

**Comment by p3rcya** [comment]
1.蓝灯永远可以免费使用。 除非你看视频刷图片，或者希望连接质量高，完全可以免费使用。而VPN基本没有免费的。 
2.蓝灯并不是VPN。蓝灯采用多个服务器和多个混淆协议来保证服务器的快速与稳定。一般VPN协议特征明显，可以被GFW实时分析协议特征，故意劣化或者阻断连接。
3.蓝灯每个客户端不知道所有服务器的IP。而VPN的用户知道所有服务器的IP，GFW注册个帐号，可以全部封锁。


@dave1221

**Comment by hynum** [comment]
所以还得等一个月才能正常用啊

**Comment by p3rcya** [comment]
@hynum 赠送一个月不代表要等一个月才能正常使用。赠送的时间长是因为我们希望感谢公测的用户

**Comment by minion93** [comment]
为什么我无法购买啊，确认支付以后就白屏，信用卡和支付宝都试过了一样的

**Comment by p3rcya** [comment]
@minion93 请按照 https://github.com/getlantern/forum/issues/358 上传log，方便我们调查

**Comment by minion93** [comment]
@p3rcya

**Comment by minion93** [comment]
@p3rcya 发送日志无限转圈

**Comment by p3rcya** [comment]
@minion93 是安卓版么？

**Comment by minion93** [comment]
@p3rcya 是的

**Comment by minion93** [comment]
@p3rcya 上传成功了 有点慢

**Comment by Eccolala** [comment]
ubuntu 怎么获取日志 @p3rcya

**Comment by merkel12345678** [comment]
你好，专业版电脑已经可以正常翻墙，但是，安卓版3.0.6安装之后打开lantern就是直接闪退，无法上传log，请帮忙解决下，非常感谢@p3rcya

**Comment by p3rcya** [comment]
@merkel12345678 请问系统版本和手机型号？

**Comment by merkel12345678** [comment]
系统是Android4.2.2 手机型号是HUAWEI HN3-U01   @p3rcya

**Comment by minion93** [comment]
@p3rcya 
小米5 尊享版
Miui 8 6.6.30 
Android版本 6. 0.1MXB48T，应该不是我手机问题，我用电脑也无法购买，

**Comment by p3rcya** [comment]
@minion93 你用的是最新3.0.6么？ 具体问题是什么？ 无法加载购买界面？

**Comment by Giorgiowj** [comment]
@p3rcya 你好，想问下lantern的收费方式以后能支持其他的吗?比如paypal...支付宝不放心。另外我支持收费！免得部分人滥用。感谢你们为我们自由获取信息所做的辛勤工作。

**Comment by p3rcya** [comment]
@Giorgiowj 如果你有Paypal的话，你应该有信用卡吧？ 我们现在就支持信用卡付款了。 谢谢你的关心！

**Comment by Giorgiowj** [comment]
谢谢了

**Comment by 33cyy** [comment]
我只想問一下，是不是換了服務器，現在用專業版上一下for大陸ip站，還要經過你們的服務器讀取？讀取延遲很慢嗎？能否修復，還有經常登錄- -有時會自動斷開鏈接？還有用你提供的 https://speedof.me/ 測試？上傳下載速度只有Download Speed: 80 kbps  Upload Speed: 130 kbps ？以前免費的時候不會出現的問題現在都冒出來了，更何況指望想指望你們進步優化可以看到tw網站的？

**Comment by ldc1024** [comment]
前来支持 望早日修复bug

**Comment by p3rcya** [comment]
@33cyy 不好意思，速度慢的问题正在解决。访问大陆网站，如果没有开启全局代理会直连。

**Comment by jyufeng** [comment]
@p3rcya 3.0.6版本还是有问题，看视频是不是的中断。有时候自动回复，有时候必须手动刷新，等待一段时间才能恢复。

**Comment by wkpeng** [comment]
我输入了邀请码，购买了两年，为什么我帐号显示只是两年的时间并没有赠送三个月？

**Comment by p3rcya** [comment]
@wkpeng 请按照此帖上传log https://github.com/getlantern/forum/issues/358 ，方便我们调查，谢谢

**Comment by DK29c** [comment]
我买了1年的PRO，可是我的手机（android）、平板电脑（android）都无法正常使用，PC（win10）十分十分缓慢。求解。

**Comment by summerjones** [comment]
买的时候说可以关联三台电脑，但是另外一台Mac下载了最新版的lantern却到处都找不到登录的地方，怎么关联呢？

**Comment by summerjones** [comment]
而且付款的时候我记得有一个页面，写着”lantern支持什么什么版本，iOS版本正在研发中“，再搜索就找不到了，那个不是官网么？而且现在能搜索到的官网也找不到支付按钮，是我遇到钓鱼网站了么？

**Comment by p3rcya** [comment]
这个页面下载 https://github.com/getlantern/forum 有支付按钮

**Comment by 0zhuyuxuan0** [comment]
之前一直用的2.2.5版的，今天上不了网了，显示流量用完了，于是就升级到专业版，but还是上不了网
日志：
[lantern.txt](https://github.com/getlantern/forum/files/373069/lantern.txt)

**Comment by yangkedj** [comment]
@ghost
lantern 会推出iOS版本吗

**Comment by AgainWang** [comment]
推荐用金钥匙VPN,稳定不限速

**Comment by jasonstyle2015** [comment]
重装系统之后，怎么授权？什么时候解决这个问题？？？？？？？？？？

**Comment by hcmyleo** [comment]
@ghost  我很喜欢蓝灯，日常开机自启。完全没有打扰，如果不是我重装系统，发现没法授权……我差不多都要忘了它了，，哈哈。很好的使用体验，能在不打扰我的前提下，让我自由上网，这很赞。

**Comment by summerjones** [comment]
谁能告诉我怎么授权给别的电脑？未授权的电脑打开lantern，显示邀请码，说在菜单中找“授权其他设备使用专业版”，但是我在已授权的电脑上到处都找不到这行字啊？？？

**Comment by fbuluo1987** [comment]
为什么专业版登录输入代码，会提示无效的验证码？版本3.0.12

**Comment by summerjones** [comment]
之前无法授权的问题我自己解决了，是因为我更新了系统，授权的时候是Mac OS X 10.11.5，后来更新到了Mac OS X 10.11.6，打开lantern之后，“账号管理”下面就直接是“获取移动版本”，把lantern删了重装，就出先“给其他设备授权”了，是说每次更新系统都得重新装一次lantern么？

**Comment by luc11** [comment]
我的lantern也遇到相同问题。9天以前买的pro版本，已经绑定好了电脑，一切正常。3天前系统重装，再次下载登陆lantern专业账号时出现“授权设备使用专业版本”。另外，请问楼上@summerjones是怎么解决这个问题的？

**Comment by summerjones** [comment]
之前无法授权的问题我自己解决了，是因为我更新了系统，授权的时候是Mac OS X 10.11.5，后来更新到了Mac OS X 10.11.6，打开lantern之后，“账号管理”下面就直接是“获取移动版本”，把lantern删了重装，就出先“给其他设备授权”了，是说每次更新系统都得重新装一次lantern么？@luc11

**Comment by SUIRUI** [comment]
LANTERN PRO"一个专业版的账号可以同时在任意三部设备上使用，包括桌面端和移动设备。",——我想问下我可不可以与另一免费版用户共享我的专业版账号？如果可以，怎么弄呢？
![default](https://cloud.githubusercontent.com/assets/22320432/19142001/acdb79e0-8bcc-11e6-9f29-422b9de9d788.png)

**Comment by mrsolog** [comment]
Mac版，长时间（约5分钟）转圈圈后提示链接服务器失败。同时quit lantern没反应。已经持续了一两周了，自从付了钱没多久就便成这个样了，免费版本倒是用的还不错。

**Comment by p3rcya** [comment]
@mrsolog 正在调查。以后请开新帖，不要挖坟

**Comment by fangkun115** [comment]
买了两年，但上周开始就无法连接Pinterest等网站了，求助
