### ISSUE TITLE
蓝灯 ubuntu 14.04 64位Deb版本在笔记本上一直无法工作

### ISSUE THREAD

**Issue by thatdigua** [getlantern/forum#3571]
我使用Linux Mint，和ubuntu 14.04是兼容的，下载了14.04的64deb版本，安装正常，蓝灯也可以正常启动。
使用Chrome，选了switchOmega的系统代理，就是上不了google之类的网站，很是烦恼，也不知道问题出在哪里？？应该怎么诊断。特别受挫。
都说装了之后直接就用了，为啥我的总是不行呢

**Comment by QQ595332727** [comment]
在ubuntu 14.04里可以正常使用吗？

**Comment by JuniorZhangwei** [comment]
貌似封了吧，windows和android好像也不好使了

**Comment by thatdigua** [comment]
反正最后在chrome里面搞不定 一直没法使用 换了firefox浏览器 神奇地就好了 我也不知道什么原因
