### ISSUE TITLE
邀请码，欢迎大家使用

### ISSUE THREAD

**Issue by ljlong1982** [getlantern/forum#3584]
邀请码 YFP8N8G 来获得三个月的蓝灯专业版！

**Comment by YouZhengChuan** [comment]
分享您的邀请码
YFPU9H8

**Comment by xuezechao2012** [comment]
输入我的邀请码 YHVU6XU 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by mqygme** [comment]
<h1> 6R3RWD，送蓝灯专业版高速不限流量三个月哦！﻿</h1>﻿
