### ISSUE TITLE
邀请码YHZFFG，蓝灯专业版，问题反馈

### ISSUE THREAD

**Issue by temp4826** [getlantern/forum#3592]
最近经常遇到问题
1、手机打开专业版蓝灯，打开Google Play之后，却无法下载app，速度一直是0。
2、能打开Google Play却不能打开谷歌网页搜索。
3、关掉蓝灯之后，什么软件都显示无法连接，这个问题很严重。手机不像电脑，可以手动查看代理。

请问3个问题怎么解决！

**Comment by temp4826** [comment]
听说是3.7.4的问题？？？

**Comment by p3rcya** [comment]
请完全卸载后安装3.7.5测试版 https://github.com/getlantern/forum/issues/3595

**Comment by meibujun** [comment]
输入我的邀请码 YJJ9W4F 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
