### ISSUE TITLE
今天发现用不成了，然后下载新版本，就在界面一直转啊转 

### ISSUE THREAD

**Issue by yangzhiyao** [getlantern/forum#360]
用chrome查看网络连接情况：
<img width="584" alt="2016-07-07 2 29 10" src="https://cloud.githubusercontent.com/assets/6712485/16644396/47a5cafe-444f-11e6-9494-345d65086e32.png">
ws://127.0.0.1:16823/data 一直处于 101 Switching Protocols
不知道是什么情况

日志文件附上：
[lantern.log.zip](https://github.com/getlantern/forum/files/351505/lantern.log.zip)

**Comment by p3rcya** [comment]
正在调查

**Comment by chkjc10** [comment]
我也是，在电脑短和手机上都是一直转圈，用回2.25也连不上。为什么专业版一出，好多问题都来了，原来免费的是时候基本上都能连，难道这是上天捉弄人？

**Comment by dearlili** [comment]
我还以为是我自己的问题呢，看来是lantern出问题了。

**Comment by liypeng** [comment]
我下载新版本也是转呀转

**Comment by z1000zhihe** [comment]
是的 一直在转圈

**Comment by xulimessage** [comment]
是的，我的一直在转
