### ISSUE TITLE
无法为蓝灯续费，填写email地址的时候显示“该邮件地址已被另一用户使用”

### ISSUE THREAD

**Issue by maxxsun** [getlantern/forum#3614]
无法为蓝灯续费，填写email地址的时候显示“该邮件地址已被另一用户使用”    请教管理员如何解决？

**Comment by WengHeng** [comment]
我也是,好久都不能续费了...不知道怎么解决...可能是要让我们重新弄邮箱续费吧 
是不是?管理员 @p3rcya

**Comment by c2303191** [comment]
_别续费了，蓝灯不让你续费

**Comment by maxxsun** [comment]
额 眼看就要到期了 续个费还那么麻烦。

**Comment by c2303191** [comment]
lantern收费没多久把你咋就到期了呢。。。

**Comment by p3rcya** [comment]
正在修复。请等下一个版本

**Comment by p3rcya** [comment]
已经修复
