### ISSUE TITLE
终于下定决心买蓝灯了！速度超级牛逼！没买的赶紧买买买啊！我的邀请码:  YM3FGUV

### ISSUE THREAD

**Issue by wannihilation** [getlantern/forum#3618]
# 终于下定决心买蓝灯了！速度超级牛逼！没买的赶紧买买买啊！输入我的邀请码 YM3FGUV 来获得三个月的蓝灯专业版！

**Comment by mqygme** [comment]
用这个邀请码 <h1>6R3RWD</h1>﻿，送蓝灯专业版高速不限流量三个月哦！
Apply coupon code  <h1>6R3RWD</h1>﻿ to get FREE THREE MORE MONTHS Lantern PRO!﻿

**Comment by wannihilation** [comment]
# 输入我的邀请码来获得三个月的蓝灯专业版！   YM3FGUV
