### ISSUE TITLE
蓝灯lantern最新邀请码 Y2947HH 永久有效！获取三个月免费蓝灯专业版！

### ISSUE THREAD

**Issue by stephen666** [getlantern/forum#3630]
# 蓝灯lantern最新邀请码 Y2947HH 永久有效！获取三个月免费！

## 请输入我的蓝灯lantern专业版邀请码 Y2947HH 来获得三个月免费的蓝灯专业版！使用后请留下你的邀请码，我也会使用你的邀请码续费的！

![lantern-referral-code](https://user-images.githubusercontent.com/11013738/28955186-33486a64-7917-11e7-98df-2a29ef48aaad.png)

**Comment by stephen666** [comment]
也可以到 #313

**Comment by stephen666** [comment]
reference #313

**Comment by meibujun** [comment]
输入我的邀请码 YJJ9W4F 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by fuhuowcy** [comment]
**_蓝灯lantern最新邀请码 LK9XMP
![2017-09-06_085611](https://user-images.githubusercontent.com/31676624/30089856-04eca510-92e2-11e7-8295-a6b1c001fe6a.jpg)
， 永久有效！获取三个月免费！敬请使用_**

**Comment by Ropynn** [comment]
YP9SWD2  刚才填了你的邀请码  这是我的邀请码

**Comment by ourmv** [comment]
输入我的邀请码 L9N4HH 来获得三个月的蓝灯专业版！

**Comment by CQKang** [comment]
输入我的邀请码 JVVCU2 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by cindy888** [comment]
For a free month of Lantern Pro, use this referral code: 4U6F55 ; You can download it from here: https://bit.ly/1M8x04u

**Comment by guodj** [comment]
输入我的邀请码 MJZX77 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
