### ISSUE TITLE
discovermagazine的文章无法阅读

### ISSUE THREAD

**Issue by tbirder** [getlantern/forum#3668]
![20170806125523](https://user-images.githubusercontent.com/30400128/29000717-c789f9f0-7aa6-11e7-8a4a-c07dc8140d19.png)

**Comment by p3rcya** [comment]
是说有文章链接都出现问题还是部分链接？请贴出具体链接，谢谢

**Comment by tbirder** [comment]
@p3rcya  你可以打开 https://blogs.discovermagazine.com/  试试，所有的的文章都这样，日本IP就是这个问题。

**Comment by paperbag** [comment]
Chrome 已经清楚的写着重定向过多，请尝试清除你的 Cookies。

**Comment by tbirder** [comment]
@paperbag 你是在给我翻译这句话么？

**Comment by paperbag** [comment]
你还不懂吗？这和你说的“被禁止访问”有什么关系？

On August 7, 2017 8:43:45 PM GMT+08:00, tbirder <notifications@github.com> wrote:
>@paperbag 你是在给我翻译这句话么？

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by paperbag** [comment]
什么“discovermagazine的文章被代理ip拉取的次数太多就被禁止访问了”只是你的臆想。

On August 7, 2017 8:43:45 PM GMT+08:00, tbirder <notifications@github.com> wrote:
>@paperbag 你是在给我翻译这句话么？

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tbirder** [comment]
我只要退出蓝灯，反复再试，只要试到别的ip就正常，一试到这个日本ip就打不开。

我玩cookies的时候，你可能还没学会上网，不要自以为是。

**Comment by paperbag** [comment]
> 我玩cookies的时候，你可能还没学会上网，不要自以为是。

我说的重点是这与被禁止访问无关，你非要咬着 cookies 不放。

~那就当我没学会上网，而你到现在连一个 repo 都没有~

刚才试了一下，使用蓝灯时访问
http://blogs.discovermagazine.com/lovesick-cyborg/2017/08/07/the-ice-tank-shaping-future-coast-guard-icebreakers/
确实存在循环重定向的问题。

猜测与 https://github.com/getlantern/httpseverywhere 有关。

**Comment by orbancanon** [comment]
是的，确实和httpseverywhere有关。谢谢@paperbag。Lantern依照的规则在[这里](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Discover.com.xml)。这个网站首页支持https，访问里面的文章时却一直重定向回http。@tbirder 它使用的是302 Moved Temporarily，_理论上_可以理解为临时故障，修复了就会改回来。

我们想想怎么在Lantern里规避这种情况。

**Comment by tbirder** [comment]
@p3rcya @orbancanon   这个网站没有被墙，可以直接访问，反而打开蓝灯后却不能访问了（可能就如同楼上说的httpseverywhere重定向http而非https有关），不知在非全局代理模式下，蓝灯为何将其加入被墙的行列？

**Comment by paperbag** [comment]
> Lantern依照的规则在[这里](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Discover.com.xml)。

应该是这个 https://www.eff.org/https-everywhere/atlas/domains/discovermagazine.com.html

看了一下，这个在 HTTPSE 里是实验性规则。@orbancanon

**Comment by orbancanon** [comment]
哦对对@paperbag，对应到github是https://github.com/EFForg/https-everywhere/blob/release/src/chrome/content/rules/DiscoverMagazine.com.xml。这条规则EFF那边已经修复了，Lantern下一版里更新一下规则库就可以解决了。

**Comment by tbirder** [comment]
看了下规则，仅解决blogs.discovermagazine.com这一个网站的这类问题么？莫非是一个网站得写一个规则？不解。@orbancanon @paperbag 

`<ruleset name="Discover Magazine.com (partial)" platform="mixedcontent">
	<target host="blogs.discovermagazine.com" />

	<rule from="^http:" to="https:" />
</ruleset>`

**Comment by orbancanon** [comment]
@tbirder 它确实是这样工作的，EFF的贡献者在积极地维护这个规则库。不过下版的Lantern会加一个功能来防止出现too many redirects，即使规则会导致这种情况。

**Comment by tbirder** [comment]
@orbancanon  这一块儿我还不太熟悉，能解决就OK了。锁帖。
