### ISSUE TITLE
我想问下在第一次付费时卡住（提示付费成功），然后刷新进行第二次付费...

### ISSUE THREAD

**Issue by GD-HBX** [getlantern/forum#371]
我想问下在第一次付费时卡住（提示付费成功），然后刷新进行第二次付费也显示成功，两次都有收到短信“【宝宝宝】输入校验码******，确认您 lantern 向Stripe, Inc.支付320.01元“（点解多1分钱？-_-，手续费？），上述两次操作后只有第二个操作在浏览器上提示付款成功并转到pro版的页面，并且收到“【宝宝宝】贵账户lantern于13月32日25时61分通过（宝宝宝）消费320.01元。详询99999“，那么问题来了，第一次付款浏览器提示成功（同时手机接到输入验证码短信），并且卡在着转圈，然后我等得唔耐烦就刷新再进行第二次付款，那么第一次的付款会不会被扣费！目前只提示扣了一次费。

**Comment by orbancanon** [comment]
@GD-HBX 除非你刷新后是专业版的界面，否则都没有付款成功的哈。
