### ISSUE TITLE
我想知道为什么封锁我的蓝灯账号？我里面有7年多的时长

### ISSUE THREAD

**Issue by ethan1107** [getlantern/forum#3710]
连个通知都没有就封了，谁能给个说法？

**Comment by c2303191** [comment]
还能这样？？？

**Comment by baiyibaiyi** [comment]
樓主你可能刷的分享碼太多了，大家只要足夠1年或兩年贈送時間，已經很了不起了。分享碼給人太多（公共敏感地區），不僅不會給藍燈帶來太多好處，還會帶來不小的害處。問問自身，在這期間究竟做了什麼，不要去怪藍燈對你如何。

**Comment by lemonskkyt** [comment]
@baiyibaiyi ......分享太多会被封，那不扯淡，我还剩7年半，难道我还要担心被封

**Comment by tbirder** [comment]
其实这样的问题，蓝灯应该出来解释一下比较好。

如果不是楼主猜测的原因，以讹传讹不太好。

**Comment by p3rcya** [comment]
请不要发只有邀请码没有其他内容的帖子，见 https://github.com/getlantern/forum/issues/3773 ，屡教不改者将封号处理。
