### ISSUE TITLE
pro用户，网速限制，log已上传

### ISSUE THREAD

**Issue by GD-HBX** [getlantern/forum#372]
![ma](https://cloud.githubusercontent.com/assets/3373783/16653988/47c050e0-4486-11e6-9621-ca014ae454a4.png)

win_log:
[lantern.txt](https://github.com/getlantern/forum/files/352180/lantern.txt)

Android_log:
[a_lantern.log.txt](https://github.com/getlantern/forum/files/352357/a_lantern.log.txt)

**Comment by orbancanon** [comment]
@GD-HBX Android的问题是服务器被墙了，刚刚把那个服务器下架，很快就能用了。你好像没有把专业版帐号用到Android上，所以只能用那一台服务器。

从Windows上看到也有一台被墙的服务器，但有多台，似乎不至于影响使用。

**Comment by GD-HBX** [comment]
@orbancanon 但系速度上还是没变化，跟免费的没区别...

**Comment by GD-HBX** [comment]
貌似坑爹的狗信限速，移不动速度杠杠的，其他pro用户是这样的吗？

**Comment by GD-HBX** [comment]
狗信真的限@*+-速的话能在log中看到吗？能解决吗？比如换掉你们v=p“s的i#p，速度在20k-100多k之间跳动，受不了，移不动就没这个问题！
