### ISSUE TITLE
蓝灯和知乎

### ISSUE THREAD

**Issue by little321tony** [getlantern/forum#3729]
我现在习惯一直开着蓝灯在手机上上网，但是我发现蓝灯安卓版好像不太支持知乎，打开知乎网站相关的内容很费劲，pc电脑上却没有出现这种问题。

**Comment by little321tony** [comment]
退一步说，知乎的安卓客户端在使用蓝灯的情况下可以正常使用

**Comment by ethan112323** [comment]
蓝灯在安卓上是全局的vpn，可能知乎对于国外的ip不太支持

输入我的邀请码 # JFTW7F 来获得三个月的蓝灯专业版！

**Comment by ethan112323** [comment]
蓝灯在安卓上是全局的vpn，可能知乎对于国外的ip不太支持

输入我的邀请码 # **JFTW7F** 来获得三个月的蓝灯专业版！

**Comment by little321tony** [comment]
不会吧，我没开“代理全部流量”这一项啊！？
