### ISSUE TITLE
手机版登录专业版之后翻不了墙啊……Why……

### ISSUE THREAD

**Issue by Rieal** [getlantern/forum#373]
手机版登录专业版之后翻不了墙啊……Why……

**Comment by p3rcya** [comment]
请按照本帖 https://github.com/getlantern/forum/issues/358 上传log，方便我们调查

**Comment by Rieal** [comment]
这个问题在3.0.7这个版本的时候被修复

**Comment by huiyu998** [comment]
期待苹果手机版早日开通

**Comment by 1053393611** [comment]
手机无线练不了网，流量可以连，什么原因

[lantern.zip](https://github.com/getlantern/forum/files/573796/lantern.zip)
