### ISSUE TITLE
已经购买了专业版，重装系统想登陆登陆不了

### ISSUE THREAD

**Issue by apple2303** [getlantern/forum#3730]
没有输密码的文本框啊，我输入支付宝账号或者邮箱号都是显示：无法根据以上信息找回账号。怎么办？
![_20170810234448](https://user-images.githubusercontent.com/30904660/29179175-4eebefd4-7e26-11e7-8e66-056212448c90.png)

**Comment by tbirder** [comment]
尽管已经打码，但目测你输入的仅仅是手机号，而不是邮箱。

**Comment by apple2303** [comment]
。。。只是这个截图是手机号，它显示输入支付宝账号或邮箱。我试了手机号和邮箱，都是显示这个鬼。

**Comment by little321tony** [comment]
这个问题我也遇到过，一般来说手机版的蓝灯即使你卸载重装它也会有记忆你是专业版用户，因此如果你要授权电脑还是得通过手机来操作，直接在电脑输入邮箱或其他是不可行的。

**Comment by pky920216344** [comment]
输入我的邀请码 YPNZNS8 来获得三个月的蓝灯专业版！

**Comment by apple2303** [comment]
@little321tony 但我手机是苹果的，没法用啊。。。所以现在是无解了嘛~~~~(>_<)~~~~

**Comment by pky920216344** [comment]
祈祷出iOS版

发自我的 iPhone

在 2017年8月11日，10:23，apple2303 <notifications@github.com<mailto:notifications@github.com>> 写道：


@little321tony<https://github.com/little321tony> 但我手机是苹果的，没法用啊。。。所以现在是无解了嘛~~~~(>_<)~~~~

**Comment by little321tony** [comment]
你这个问题我不太会哎@p3rcya

**Comment by one360** [comment]
搬瓦工vps，kvm一年才120元，比蓝灯划算多了，每月500G流量
还能建个网站，随便折腾
内存：512MB
硬盘：10GB SSD
月流量：500GB
机房：8个机房
价格：年付19.99美元
地址 https://bwh1.net/aff.php?aff=3412&pid=43
（可一键安装ss）

**Comment by p3rcya** [comment]
@apple2303 

你并没有成功购买专业版。
若觉得成功购买，请提供如图的支付凭证
Order w110286123
交易号 20170220210010033302548151123
商户订单号 w110286123
