### ISSUE TITLE
mac os 频繁闪退

### ISSUE THREAD

**Issue by chentao7v** [getlantern/forum#3733]
电脑环境:mac os sierra 10.12.6
五分钟后就自动停止.
装了最新版本(Lantern 3.7.4 (20170705.190647))也不行.

之前一直没有出现过这个问题,今天突然出现的.

遇到的问题：频繁闪退
蓝灯专业版账号Email: chentao7v@163.com
应用内报告问题的时间: 2017.8.11 下午3点

日志:
[lantern.log.zip](https://github.com/getlantern/forum/files/1216823/lantern.log.zip)

@p3rcya

**Comment by chentao7v** [comment]
这个问题非常严重,我目前所有的ide都需要lantern,包括 命令行

**Comment by Syzq** [comment]
我的也是不到五分钟就会自动退出。奇怪，我还以为是我的win7出了问题。看来是lantern的问题啊

**Comment by chentao7v** [comment]
@Syzq 
我的之前一直是好好的,今天就开始出毛病,坑啊

**Comment by ICMYS** [comment]
同样的问题。win10

**Comment by chentao7v** [comment]
@ICMYS 
又挂了

**Comment by chentao7v** [comment]
@p3rcya 
更换到了 Lantern 3.7.6 (20170731.121940) 还是不行

**Comment by Griffin1** [comment]
我 win 10 ,安卓也是用着用着自动关闭！
已在应用内报告问题提交日志。

**Comment by chentao7v** [comment]
@Griffin1 
安卓的我也有这个问题,不过手机上我用的时间不多

**Comment by romantiskt** [comment]
我今天也是出现了此问题。希望官方尽快解决

**Comment by jiaoyixuan** [comment]
一样的问题
Ubuntu 16.04 LTS

**Comment by ICMYS** [comment]
http://s3.amazonaws.com/urtuz53txrmk9/index.html
把3.7.4的删除干净了，使用这个地址下载的3.6.3倒是没有自动退出

**Comment by chentao7v** [comment]
@ICMYS 
知道mac 上怎么删干净么?

**Comment by ICMYS** [comment]
@chentao7v  没用过，不知道。

**Comment by phihh** [comment]
蓝灯是我用过最差的vpn。我绝对不会再把它推荐给任何人。垃圾蓝灯。

**Comment by jimoe06** [comment]
@ICMYS  还是会自动退出。。。。

**Comment by jimoe06** [comment]
@ICMYS win10删干净怎么删，控制面板卸载就可以吗？

**Comment by tsaosung** [comment]
一样的问题

**Comment by Syzq** [comment]
@phihh  我感觉蓝灯还是挺好挺方便的  现在ZF管控的严   偶尔不稳定也是正常的。其他VPN问题也很大

**Comment by phihh** [comment]
@Syzq ZF是government 吗

**Comment by Syzq** [comment]
@phihh   对  这阵子查的挺严的  好多VPN都被查封了  要怪只能怪我天朝太强大  （手动滑稽）

**Comment by ICMYS** [comment]
@jimoe06  
C:\Users\这里是你的用户名\AppData\Roaming\Lantern
把这个目录下的文件全部删除

**Comment by jimoe06** [comment]
@ICMYS 感谢，好像确实可以了。。我还是会断，不过时间长了不少，半小时左右才断了一次 emmm。。

**Comment by jimoe06** [comment]
@ICMYS 有点无语。。。装好第一次打开确实是3.6.3，关掉第二次再开就自动升级了。。。变成3.7.4了

**Comment by chentao7v** [comment]
#3736 
#3737 
@p3rcya 
官方的同学

**Comment by Jiayupeng** [comment]
上来之后发现不是自己一个人出现这样的问题，希望官方尽快解决。。

**Comment by lq08025107** [comment]
的确是有这个问题，不会蓝灯也要悲剧了吧

**Comment by dikblo** [comment]
总三的人我操你妈逼。你们这么干断子绝孙。真的一点活路也不给留。

**Comment by orbancanon** [comment]
受影响的后台服务已经修复。现在各平台客户端应该已经恢复正常。

**Comment by p3rcya** [comment]
已经修复 https://github.com/getlantern/forum/issues/3741
