### ISSUE TITLE
今天蓝灯不正常，几分钟就崩溃了

### ISSUE THREAD

**Issue by ck8918** [getlantern/forum#3737]
有多少人出现问题了，官方或者技术高手能解决吗

**Comment by chentao7v** [comment]
#3733

**Comment by qijiannet** [comment]
我的也是 win10系统 打开用一会 就自动关了 又要重新开 很烦~！

**Comment by tsaosung** [comment]
我的手机也一样啊，一会就崩溃了，关都关不掉

**Comment by songokudeen** [comment]
我也是一样，我还以为我是我整其他软件设置什么的把lantern搞坏了。知道不是我的毛病就好 xD

**Comment by tsaosung** [comment]
好像专业版有问题，我用免费版试了下居然是好用的

**Comment by CoderLJY** [comment]
看来可能是这个版本的问题，我也是这样的

**Comment by orbancanon** [comment]
受影响的后台服务已经修复。现在各平台客户端应该已经恢复正常。

**Comment by p3rcya** [comment]
已经修复 https://github.com/getlantern/forum/issues/3741
