### ISSUE TITLE
蓝灯频繁闪退，有人出来解决吗

### ISSUE THREAD

**Issue by ck8918** [getlantern/forum#3740]
用上一下就退出来了，很不稳定。

**Comment by jingtai5** [comment]
我的也是，难道要被封了？

**Comment by chentao7v** [comment]
@p3rcya 
只知道他是官方的,也联系不上啊

**Comment by CoderLJY** [comment]
我按照那个处理的帖子，重装，管理员权限登陆也不行，注册表根本就没有其他的代理

**Comment by WarlockLOL** [comment]
我的也是这样 今天大概整个服务器都是这样

**Comment by aleckon1987** [comment]
从今天上午10点左右开始的，一直在闪退。

**Comment by onebee** [comment]
是的  我的也是这样 mac  10.12.6 系统

**Comment by p3rcya** [comment]
请给在发帖前先按照[蓝灯无法使用的解决办法](https://github.com/getlantern/forum/issues/1902)自行解决。自行解决问题通常只需要几十分钟。管理员调查解决问题需要几天至几周。

若无法按照[蓝灯无法使用的解决办法](https://github.com/getlantern/forum/issues/1902)自行解决，愿意等待管理员人为调查的，请按照如下格式发帖。https://github.com/getlantern/forum/issues/3536 不按照格式发帖无法调查，谢谢。

**Comment by chentao7v** [comment]
@p3rcya 
这是大面积的闪退,之前都没有出现

**Comment by Banana1130** [comment]
这是大面积问题，和个人系统无关吧，不是我们检查自行解决，而是官方给个明确答复出何问题了！@p3rcya

**Comment by wcmolin** [comment]
我的也是，mac 10.12.6 频繁闪退。

**Comment by wyybbyy** [comment]
搞得我都不想买了

**Comment by chentao7v** [comment]
@wyybbyy 
先别买了,官方也在和稀泥

**Comment by wyybbyy** [comment]
好先看看再说

**Comment by orbancanon** [comment]
受影响的后台服务已经修复。现在各平台客户端应该已经恢复正常。

**Comment by p3rcya** [comment]
已经修复 https://github.com/getlantern/forum/issues/3741
