### ISSUE TITLE
闪退问题已经修复

### ISSUE THREAD

**Issue by p3rcya** [getlantern/forum#3741]
今天出现的闪退问题我们已经修复。请大家重启软件

**Comment by orbancanon** [comment]
受影响的后台服务已经修复。现在各平台客户端应该已经恢复正常。

**Comment by YIinGitHub** [comment]
之前用免费版是能上 google.com 的，
现在我买了专业版，反而打开 google.com 时直接跳转 google.com.hk， 一直上不了 google.com，
为什么会这样？怎么解决这个问题？

**Comment by ICMYS** [comment]
@YIinGitHub  打开一次https://www.google.com/ncr 试试

**Comment by lililalahaha** [comment]
现在好像正常了

**Comment by zhrxx444** [comment]
还是不行，看一会YouTube就挂掉

**Comment by realwhs** [comment]
依旧不行，区别是原来几分钟退，现在可能坚持十几分钟退，刚又退了

**Comment by PKingHot** [comment]
我重装了软件就好了

**Comment by sunnyy524** [comment]
我还是闪退啊，打开5分钟内可以用，5分钟后就显示红灯：蓝灯已关闭。您无法访问已屏蔽的网站
