### ISSUE TITLE
我的邀请码！52WWSX

### ISSUE THREAD

**Issue by wuyuhan2015** [getlantern/forum#3745]
输入我的邀请码 52WWSX 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by wuyuhan2015** [comment]
输入我的邀请码 52WWSX 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by wyybbyy** [comment]
才购买吗？感觉这个专业版怎么样

**Comment by wuyuhan2015** [comment]
感觉特别快，而且性价比高，次什么红杏的强多了

**Comment by wuyuhan2015** [comment]
这个码可以用，反正特别快吧
