### ISSUE TITLE
买了蓝灯之后反而用不了！一个字，“服”！

### ISSUE THREAD

**Issue by Char-CN** [getlantern/forum#3754]
自动买了2年蓝灯专业版后。
打开蓝灯一直提示：很抱歉，我们无法连接到蓝灯的服务器。请检查您的网络连接并重试。
一个字，“服”！
呵呵哒！

**Comment by p3rcya** [comment]
请给在发帖前先按照[蓝灯无法使用的解决办法](https://github.com/getlantern/forum/issues/1902)自行解决。自行解决问题通常只需要几十分钟。管理员调查解决问题需要几天至几周。

若无法按照[蓝灯无法使用的解决办法](https://github.com/getlantern/forum/issues/1902)自行解决，愿意等待管理员人为调查的，请按照如下格式发帖。https://github.com/getlantern/forum/issues/3536 不按照格式发帖无法调查，谢谢。

**Comment by hhzhaoheng** [comment]
不会吧，我一直会，凡是支持的设备我都装的有，没有遇到楼主的问题。

**Comment by ilivid** [comment]
我购买后也短暂的遇到了这个问题，不过路由器重启后就OK了

**Comment by Char-CN** [comment]
哎~~~过几天就好了，实在是。。。。。。。。无语
