### ISSUE TITLE
windows版，Ubuntu版无法用邮箱登陆成专业版

### ISSUE THREAD

**Issue by i18ni18n** [getlantern/forum#3757]
遇到的问题：
	电脑版无法登陆成专业版，填完登陆邮箱，进入输验证码的页面输入验证码后，点登陆后界面不动，无法登陆，用手机版能登陆进去变成专业版，可是给电脑授权登陆的时候总提示 not authorized，已按照“蓝灯无法使用的解决办法”的步骤尝试，依然无法解决问题
购买凭证：
Order w124753686
交易号 2017081121001003960217006713
商户订单号 w124753686

蓝灯专业版账号Email: 42859060@qq.com
应用内报告问题的时间: 应用内报告时间2017-08-10 11:21

**Comment by p3rcya** [comment]
请勿重复发帖 https://github.com/getlantern/forum/issues/3756#issuecomment-321956369
