### ISSUE TITLE
输入我的邀请码 L9HKW3 来获得三个月的蓝灯专业版！

### ISSUE THREAD

**Issue by williamwine** [getlantern/forum#3763]
输入我的邀请码 L9HKW3 来获得三个月的蓝灯专业版！

**Comment by feng5045782** [comment]
动态授权码
615145

**Comment by one360** [comment]
搬瓦工vps，kvm一年才120元，比蓝灯划算多了，每月500G流量
还能建个网站，随便折腾
内存：512MB
硬盘：10GB SSD
月流量：500GB
机房：8个机房
价格：年付19.99美元
地址 https://bwh1.net/aff.php?aff=3412&pid=43
（可一键安装ss）
