### ISSUE TITLE
分享下我的邀请码，可获得赠送时长

### ISSUE THREAD

**Issue by Lsy-kg** [getlantern/forum#3767]
输入我的邀请码 KGMYFH 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by Lsy-kg** [comment]
目前测试看，大部分速度还是比较稳定的，给还未找到合适vpn的网友做个参考吧；期待ios端发布

**Comment by mqygme** [comment]
用这个邀请码，送3个月专业版哦
<h1>6R3RWD</h1>

**Comment by ethan112323** [comment]
输入我的邀请码#  JFTW7F 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by ethan112323** [comment]
输入我的邀请码
#  JFTW7F
