### ISSUE TITLE
要输入哪个邀请码呀？？？？

### ISSUE THREAD

**Issue by charliesy123** [getlantern/forum#3768]
要输入哪个邀请码呀？？？？那么多不一样的。你们是搞业务的吗？

**Comment by Lsy-kg** [comment]
输我的吧KGMYFH，咱俩都能获得赠送时长

**Comment by charliesy123** [comment]
这个邀请码是互相赠送的嘛？

**Comment by Lsy-kg** [comment]
是的

**Comment by Lsy-kg** [comment]
目前测试网速还可以

**Comment by charliesy123** [comment]
专业版怎么样还可以吗不常出毛病吧

**Comment by Lsy-kg** [comment]
可以的，速度还不错；目前没什么毛病。关闭蓝灯后不影响正常访问国内网站，不像别人说的还要手动关闭pc系统的代理。

**Comment by ethan112323** [comment]
输入我的邀请码 # JFTW7F 来获得三个月的蓝灯专业版！

**Comment by ethan112323** [comment]
输入我的邀请码 **# JFTW7F** 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by ethan112323** [comment]
输入我的邀请码 **JFTW7F** 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by mqygme** [comment]
还是用这个吧，免费送3个月哦
<h1>6R3RWD</h1>
