### ISSUE TITLE
好几天无法登陆蓝灯

### ISSUE THREAD

**Issue by hujijjj123** [getlantern/forum#3769]
电脑从8月11日起就无法登陆蓝灯，启动软件就一直卡在圆圈处，过会就提示：很抱歉，蓝灯似乎未在运行，请重试。然后就自动退出了，重装了软件，修复了HOTS文件还是不行，另外软件自动退出后，普通的上网也上不了了，要在设置中勾掉代理才行。在手机端发了报告，回复的邮件也没具体解决的方法，所以在这里发了，请尽快解决，谢谢！

**Comment by Lsy-kg** [comment]
我没遇到你说的这些问题。。win10

**Comment by hujijjj123** [comment]
补充下问题，我的是XP系统，是不是最近XP系统都上不了了啊

**Comment by 35169323** [comment]
我的Mac OS没这问题。

我的邀请码：5KYMZ7
输入邀请码可以赠送三个使用时间。

**Comment by jamicc** [comment]
我也遇到同样的问题，工作电脑是xp，不过今天才发现这个问题，也没有提示，只有蓝灯页面在一直加载，一个小圈圈一直转啊转。

**Comment by zhrxx444** [comment]
我也是这样，准确描述，打开蓝灯画圈，但是可以看YouTube，过会儿自动退出，墙内外网站都登陆不上，只能用腾讯工具箱修复，才可以登陆

**Comment by tbirder** [comment]
我也遇到过这个现象，把蓝灯完全卸载掉，重启，全部删除安装目录下文件，重新下载新版本安装。我就是这样解决的。

新朋友输入我的邀请码： YFMSDN9 （最新有效）获赠3个月专业版时长。

**Comment by jamicc** [comment]
楼上卸载重装的方法亲测有效

**Comment by hujijjj123** [comment]
问题已解决，谢谢！
我的邀请码：2CUNV7
输入邀请码可以赠送三个使用时间
