### ISSUE TITLE
请问专业版如何购买？

### ISSUE THREAD

**Issue by MambaWong** [getlantern/forum#3776]
通过lantern网页界面的“立即获取专业版”进去之后，输入了邮箱，以及信用卡付费之后，收到预授权 6.69 元的消息，过大概五分钟由收到消息预授权调整为 0.00 元，这是啥个意思呢？

**Comment by tbirder** [comment]
我也不知道啥意思，估计是购买失败了吧。
建议你选择支付宝付款。

新朋友输入我的邀请码： YFMSDN9 （最新有效）获赠3个月专业版时长。

**Comment by MambaWong** [comment]
关键是没有看到支付宝付款或微信付款的链接，请问在哪里？

**Comment by tbirder** [comment]
@MambaWong  直接在蓝灯app的界面上选择套餐，然后输入邀请码，然后就有选择支付方式，有支付宝选项。确认你的app是3.7.4或相近的版本。

输入我的邀请码： YFMSDN9 （最新有效）获赠3个月专业版的使用时长。

**Comment by ethan112323** [comment]
下载软件，支持支付宝，微信付款  输入我的邀请码 
# JFTW7F

**Comment by zhuhengyu** [comment]
输入我的邀请码 67HS6W 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by jsvr** [comment]
我也是到最后一步 没有支付的按钮

**Comment by jsvr** [comment]
支付宝没法付款

**Comment by tbirder** [comment]
@jsvr  至少你应该把你的操作截几张图上来，看看你的现象是如何发生的。

**Comment by MambaWong** [comment]
@jsvr 最开始没有出现支付宝付款链接，估计是因为我的lantern的版本不是最新的，后来升级到3.7(安卓手机版)之后就可以看得到了，也能够看到后面的支付按钮，但就是不能够支付成功。突发奇想会不会是因为用的国内的邮箱的问题，因为我这个时候用的是126的邮箱，尼玛果断换了个Gmail的，然后就一路顺畅直到支付成功。用美金支付转换人民币还可以便宜十几块钱，购买请输入我的邀请码 J4796F ，谢谢。希望能够帮到你。

**Comment by mqygme** [comment]
付款时用这个邀请码<h1> 6R3RWD ﻿</h1>﻿送蓝灯专业版高速不限流量三个月哦！

**Comment by p3rcya** [comment]
@mqygme 
本论坛不要发只有邀请码没有其他内容的帖子，请发到其他论坛，见 https://github.com/getlantern/forum/issues/3773 ，屡教不改者将封号处理。
