### ISSUE TITLE
你好，可以退款的吗，感觉不如预期

### ISSUE THREAD

**Issue by zhaoweihaoChina** [getlantern/forum#3782]
刚刚买的

**Comment by zhaoweihaoChina** [comment]
之前免费版好快的，还是日本的ip，现在专业版好慢，ip还是香港的

**Comment by tbirder** [comment]
日本ip还是香港ip，都是随机的，速度快慢都是一样的，感觉上的差异只与你的本地网速相关。参看：https://github.com/getlantern/forum/issues/3651

**Comment by alei9195** [comment]
我觉得速度挺快的
