### ISSUE TITLE
连续一周多了.电信网络突然不能使用.

### ISSUE THREAD

**Issue by houyujiangjun** [getlantern/forum#3790]
我买了两年的pro版,但是最近突然无法使用了,不管是在公司还是在家里, 常见的问题都排查了,应该是服务器被墙了,求帮助.≡(▔﹏▔)≡   不能自由上网, 没法工作了...
账号是:
houyujiangjun@126.com
错误日志信息如下:

aip=1&cd1=3.7.4&cd2=3.7.4-f198d4ddd8648abe20954d1ce2d8b533e1c2d533c76c2f4152eee4366d7899d0&cid=mIOJHdpI&dp=localhost&sc=start&t=pageview&tid=UA-21815217-12&uip=14.104.82.218&v=1
Aug 15 09:19:22.043 - 0m4s DEBUG flashlight.client: client.go:351 Use shortcut (dial directly) for ssl.google-analytics.com:443(203.208.40.158) [local_proxy_type=http op=proxied_dialer origin=ssl.google-analytics.com:443 origin_host=ssl.google-analytics.com origin_port=443 root_op=proxy user_agent=Go-http-client/1.1]
Aug 15 09:19:22.095 - 0m4s DEBUG chained: ratetracking.go:51 Finished xfer [client_bps_recv_avg=[2.5140846595922485e+08 10378] client_bps_recv_max=24225.136438545465 client_bps_recv_min=24225.136438545465 client_bps_sent_avg=[1.1334382969224795e+06 696] client_bps_sent_max=1628.5033001759764 client_bps_sent_min=1628.5033001759764 client_bytes_recv=10378 client_bytes_sent=696 op=xfer origin=globalconfig.flashlightproxy.com:443 origin_host=globalconfig.flashlightproxy.com origin_port=443 proxy_host=47.52.17.234 proxy_network=tcp proxy_port=443 proxy_protocol=https proxy_type=chained root_op=xfer]
Aug 15 09:19:22.095 - 0m4s DEBUG chained: ratetracking.go:52 Total Received: 10 kB [client_bps_recv_avg=[2.5140846595922485e+08 10378] client_bps_recv_max=24225.136438545465 client_bps_recv_min=24225.136438545465 client_bps_sent_avg=[1.1334382969224795e+06 696] client_bps_sent_max=1628.5033001759764 client_bps_sent_min=1628.5033001759764 client_bytes_recv=10378 client_bytes_sent=696 op=xfer origin=globalconfig.flashlightproxy.com:443 origin_host=globalconfig.flashlightproxy.com origin_port=443 proxy_host=47.52.17.234 proxy_network=tcp proxy_port=443 proxy_protocol=https proxy_type=chained root_op=xfer]
Aug 15 09:19:22.095 - 0m4s ERROR flashlight.client: handler.go:53 Error piping data to downstream: write tcp 127.0.0.1:56234->127.0.0.1:62662: wsasend: An existing connection was forcibly closed by the remote host. [error=Error piping data to downstream: %v error_location=github.com/getlantern/flashlight/vendor/github.com/getlantern/proxy.(*connectInterceptor).copy (proxy_connect.go:147) error_op=write error_text=Error piping data to downstream: write tcp 127.0.0.1:56234->127.0.0.1:62662: wsasend: An existing connection was forcibly closed by the remote host. error_type=errors.Error local_addr=127.0.0.1:62662 network=tcp op=proxy origin=globalconfig.flashlightproxy.com:443 origin_host=globalconfig.flashlightproxy.com origin_port=443 remote_addr=127.0.0.1:56234 root_op=proxy user_agent=Go-http-client/1.1]
ERROR flashlight.client: handler.go:53   at github.com/getlantern/flashlight/vendor/github.com/getlantern/proxy.(*connectInterceptor).copy (proxy_connect.go:147)
ERROR flashlight.client: handler.go:53   at github.com/getlantern/flashlight/vendor/github.com/getlantern/proxy.(*connectInterceptor).connect (proxy_connect.go:132)
ERROR flashlight.client: handler.go:53   at github.com/getlantern/flashlight/vendor/github.com/getlantern/proxy.(*connectInterceptor).(github.com/getlantern/flashlight/vendor/github.com/getlantern/proxy.connect)-fm (proxy_connect.go:53)
ERROR flashlight.client: handler.go:53   at github.com/getlantern/flashlight/client.(*Client).ServeHTTP (handler.go:51)
ERROR flashlight.client: handler.go:53   at net/http.serverHandler.ServeHTTP (server.go:2202)
ERROR flashlight.client: handler.go:53   at net/http.(*conn).serve (server.go:1579)
ERROR flashlight.client: handler.go:53   at runtime.goexit (asm_386.s:1612)
ERROR flashlight.client: handler.go:53 Caused by: wsasend: An existing connection was forcibly closed by the remote host.
Aug 15 09:19:22.361 - 0m5s DEBUG flashlight.proxied: proxied.go:242 Got successful HTTP call! [http_method=GET http_proto=HTTP/1.1 http_status_code=200 op=dualfetcher origin=geo.getiantem.org origin_host=geo.getiantem.org origin_port=80 proxy_type=chained root_op=geolookup]
Aug 15 09:19:22.361 - 0m5s DEBUG flashlight.proxied: proxied.go:294 Chained request succeeded in 1.8114225s [http_method=GET http_proto=HTTP/1.1 http_status_code=200 op=dualfetcher origin=geo.getiantem.org origin_host=geo.getiantem.org origin_port=80 proxy_type=chained root_op=geolookup]
Aug 15 09:19:22.361 - 0m5s DEBUG flashlight.proxied: proxied.go:262 Switching to chained fetcher for future requests since it is within 3 times of fronted response time [http_method=GET http_proto=HTTP/1.1 http_status_code=200 op=dualfetcher origin=geo.getiantem.org origin_host=geo.getiantem.org origin_port=80 proxy_type=chained root_op=geolookup]
Aug 15 09:19:22.361 - 0m5s DEBUG flashlight.proxied: proxied.go:427 Closing second response body [http_method=GET http_proto=HTTP/1.1 http_status_code=200 op=dualfetcher origin=geo.getiantem.org origin_host=geo.getiantem.org origin_port=80 proxy_type=chained root_op=geolookup]
Aug 15 09:19:22.362 - 0m5s ERROR flashlight.client: handler.go:73 Unable to write response to downstream: write tcp 127.0.0.1:56234->127.0.0.1:62665: wsasend: An existing connection was forcibly closed by the remote host. [error=Unable to write response to downstream: %v error_location=github.com/getlantern/flashlight/vendor/github.com/getlantern/proxy.(*httpInterceptor).processRequests (proxy_http.go:141) error_op=write error_text=Unable to write response to downstream: write tcp 127.0.0.1:56234->127.0.0.1:62665: wsasend: An existing connection was forcibly closed by the remote host. error_type=errors.Error local_addr=127.0.0.1:62665 network=tcp op=proxy origin=geo.getiantem.org origin_host=geo.getiantem.org origin_port=80 remote_addr=127.0.0.1:56234 root_op=proxy user_agent=Lantern/3.7.4 (windows/386)]
ERROR flashlight.client: handler.go:73   at github.com/getlantern/flashlight/vendor/github.com/getlantern/proxy.(*httpInterceptor).processRequests (proxy_http.go:141)
ERROR flashlight.client: handler.go:73   at github.com/getlantern/flashlight/vendor/github.com/getlantern/proxy.(*httpInterceptor).intercept (proxy_http.go:113)
ERROR flashlight.client: handler.go:73   at github.com/getlantern/flashlight/vendor/github.com/getlantern/proxy.(*httpInterceptor).(github.com/getlantern/flashlight/vendor/github.com/getlantern/proxy.intercept)-fm (proxy_http.go:68)
ERROR flashlight.client: handler.go:73   at github.com/getlantern/flashlight/client.(*Client).ServeHTTP (handler.go:71)
ERROR flashlight.client: handler.go:73   at net/http.serverHandler.ServeHTTP (server.go:2202)
ERROR flashlight.client: handler.go:73   at net/http.(*conn).serve (server.go:1579)
ERROR flashlight.client: handler.go:73   at runtime.goexit (asm_386.s:1612)
ERROR flashlight.client: handler.go:73 Caused by: wsasend: An existing connection was forcibly closed by the remote host.
Aug 15 09:19:22.483 - 0m5s DEBUG httpse: httpse.go:162 Average running time: 0ms
Aug 15 09:19:22.483 - 0m5s DEBUG httpse: httpse.go:163 Max running time: 0ms for host: 
Aug 15 09:19:22.497 - 0m5s DEBUG flashlight.client: client.go:351 Use shortcut (dial directly) for qurl.f.360.cn:80(101.199.109.150) [local_proxy_type=http op=proxied_dialer origin=qurl.f.360.cn:80 origin_host=qurl.f.360.cn origin_port=80 root_op=proxied_dialer]
Aug 15 09:19:22.528 - 0m5s DEBUG flashlight.analytics: analytics.go:165 Successfully sent request to GA: 200 OK
Aug 15 09:19:22.529 - 0m5s DEBUG easylist: easylist.go:97 Loaded new ruleset, added: 27176   skipped: 2552
Aug 15 09:19:22.717 - 0m5s DEBUG flashlight.proxied: proxied.go:242 Got successful HTTP call! [http_method=GET http_proto=HTTP/1.1 http_status_code=200 op=dualfetcher origin=d2n32kma9hyo9f.cloudfront.net origin_host=d2n32kma9hyo9f.cloudfront.net origin_port=80 proxy_type=chained root_op=chainedandfronted]

**Comment by tbirder** [comment]
你帐号是不是被封了？

**Comment by little321tony** [comment]
哈哈你发的还挺多的喔🤔@tbirder

**Comment by tbirder** [comment]
@little321tony  彼此彼此嘛，能帮就帮点  :)

**Comment by p3rcya** [comment]
请给在发帖前先按照[蓝灯无法使用的解决办法](https://github.com/getlantern/forum/issues/1902)自行解决。自行解决问题通常只需要几十分钟。管理员调查解决问题需要几天至几周。

若无法按照[蓝灯无法使用的解决办法](https://github.com/getlantern/forum/issues/1902)自行解决，愿意等待管理员人为调查的，请按照如下格式发帖。https://github.com/getlantern/forum/issues/3536 不按照格式发帖无法调查，谢谢。

**Comment by little321tony** [comment]
@tbirder 我从来没也从没想过去分享😌
