### ISSUE TITLE
通过蓝灯访问网页, http://www.ip.cn/

### ISSUE THREAD

**Issue by xwj1003** [getlantern/forum#3814]
谷歌是可以访问了,
问题是为什么 ip 显示的是真实IP. 这样不好吧.
 http://www.ip.cn/ 查看自己的 ip

--------------------
找到原因了, 可能是蓝灯只对GFWLIST 里的网站走代理.
如果想全部走代理, 需要在设置里面选中  "代理全部流量" 即可.

**Comment by tbirder** [comment]
原因就在于，你没有选择全局代理。这个网站并没有经过蓝灯的代理通道。你选择全局代理就是显示这个：

![20170817134642](https://user-images.githubusercontent.com/30400128/29397690-ac4c38ec-8352-11e7-893e-9fb0b41be424.png)

**Comment by temp4826** [comment]
蓝灯在日本用的是 阿里的服务器
这样合适么？
