### ISSUE TITLE
# 我的邀请码 H295ZB

### ISSUE THREAD

**Issue by yefbAndroid** [getlantern/forum#3830]
# 我的邀请码 H295ZB
## 立即下载  _https://github.com/getlantern/forum_
<p></p>
<p>谢谢大家的支持！</p>
<p></p>
若购买两年版双方都获赠3个月，若购买一年版双方都获赠1个月。

**Comment by p3rcya** [comment]
本论坛不要发只有邀请码没有其他内容的帖子，请发到其他论坛，见 https://github.com/getlantern/forum/issues/3773 ，屡教不改者将封号处理。

**Comment by yefbAndroid** [comment]
发错了
