### ISSUE TITLE
硬盘坏了, 换了后无法收到恢复码

### ISSUE THREAD

**Issue by fxintai** [getlantern/forum#3836]
lz2014@126.com  请问收不到恢复码怎么处理, 只绑定过一个电脑

**Comment by tbirder** [comment]
所以说还是授权，一个手机一个电脑比较合适，任何一个出了问题重装时都可以互相授权。

我不知道注册邮箱能不能够解除绑定（如果绑定的三台设备全部丢失，就需要这个功能），也不知道注册的邮箱，能不能收到，恢复码，如果没有，这些功能，的确非常有必要。

**Comment by fxintai** [comment]
垃圾邮件中找到了, 已经好了 谢谢大家
