### ISSUE TITLE
输入我的邀请码 4MTYMB 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

### ISSUE THREAD

**Issue by ddwomenhao** [getlantern/forum#3843]
输入我的邀请码 4MTYMB 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by p3rcya** [comment]
本论坛不要发只有邀请码没有其他内容的帖子，请发到其他论坛，见 https://github.com/getlantern/forum/issues/3773 ，屡教不改者将封号处理。
