### ISSUE TITLE
 Copy your invitation code

### ISSUE THREAD

**Issue by fmhpml** [getlantern/forum#3844]
**Invitation Code** ： **6ZRZZ4**
Valid period ： 2018/9/19
Both sides will get a month of use time for free.
Thank you. Could you leave your nickname?

**Comment by p3rcya** [comment]
本论坛不要发只有邀请码没有其他内容的帖子，请发到其他论坛，见 https://github.com/getlantern/forum/issues/3773 ，屡教不改者将封号处理。
