### ISSUE TITLE
p3rcya是谁?

### ISSUE THREAD

**Issue by b-z** [getlantern/forum#386]
在你出现之前，蓝灯里面几乎是没有汉语的，也没有这个什么论坛。
那时候大家讨论还是在lantern仓库的issues里面发英语。
我稳定地用了从前几天开始，我的旧版本的蓝灯就完全无法使用了，
今天来github更新了所谓新版本，也是时断时续。

所以真的像另一个朋友@tidatida 在 #315 中说的那样，先免费用着爽，等有一堆用户之后再收费咯，而且是针对中国用户的
180块一年，要是有IOS版本还好，迟迟不出我还不如买个VPS去了

真希望能回到2.x版本的时代

**Comment by b-z** [comment]
大家散了吧
现在还有800MB流量，过不了多久应该是免费的都不给用了
这话我就放在这

**Comment by lanten** [comment]
官方说会用久提供免费版，还有什么想不开的？
真搞不懂啊，你走吧没人拦你，少个人占流量岂不快哉？

**Comment by b-z** [comment]
你用过以前的版本么?

**Comment by hynum** [comment]
你应该去看看精华帖，800M是不限速流量，用完之后就限速20k/s了，还是能上，但是现在在修复bug，上不了。PS：我已经买了，也在等，摊手。

**Comment by GD-HBX** [comment]
买了的路过，一堆bug，等解决

**Comment by lanten** [comment]
好吧，我错了

**Comment by b-z** [comment]
20kb/s几乎就等于没有速度了，
比如当前的这个issue页面就有700KB，等待加载基本上是不能忍的。

花180买个专家版真的还不如自己搭建一个VPS+SS好用咧

**Comment by lanten** [comment]
之前没仔细看，这个800M流量限制似乎有点坑。。。

**Comment by Shensven** [comment]
@b-z 上github不需要走代理

**Comment by Eccolala** [comment]
@b-z 你用哪家的VPS,感觉搬瓦工的挺贵的

**Comment by b-z** [comment]
@Eccolala github有好像是有100刀的学生优惠

**Comment by b-z** [comment]
@Shensven 打个比方而已啦，一般网页都是这么大

**Comment by b-z** [comment]
另一个issue里面有开发者回复了

> So the repository has not been sold to anyone, and @p3rcya works with our team. In any scenario, however, I and the Lantern team are fully committed to building the best possible software we can for you to keep the internet free.

**Comment by AndySSi** [comment]
其实我不懂为什么会有Bug？至少2.X.X版本应该是可以用的啊？难道为了收费在调整后台架构？

**Comment by lkptantan** [comment]
反正我是一点翻不了。之前家里电脑还可以用，昨晚回去手贱。。。

**Comment by lkptantan** [comment]
估计是后台完蛋了
