### ISSUE TITLE
只有 Chrome 无法使用 lantern 科学上网，卸载重装之后依旧不能使用(不是插件的原因)

### ISSUE THREAD

**Issue by Yves0** [getlantern/forum#3862]
根据以前的 issue，说是 Chrome 插件的原因。但是我把 Chrome 卸载了，并且把配置文件也删除了，重新安装之后没有任何插件依然无法使用，而 firefox 正常使用。

Chrome 版本 60.0.3112.101-1_amd64
系统版本 Ubuntu 16.04

**Comment by Yves0** [comment]
安装了旧版本的 Chrome 之后就好了，希望尽快修复

**Comment by 1317099058** [comment]
我的Chrome也是这个版本的，可以用，无任何问题的
