### ISSUE TITLE
蓝灯专业版购买流程！小心支付宝汇率陷阱~

### ISSUE THREAD

**Issue by JDDCN** [getlantern/forum#3863]
# 蓝灯专业版购买流程
友情提示，**支付宝**存在**汇率问题**，购买时建议查看好价格
### 购买页面，选择两年套餐：
![default](https://user-images.githubusercontent.com/22112689/29544898-bffa2bd2-871d-11e7-9179-c5b36b8a47c3.png)
### 填入你的邮箱地址，并填入正确的邀请码：YHQCBUM
![default](https://user-images.githubusercontent.com/22112689/29545563-aa7b3cb6-8721-11e7-983c-69310503b864.png)
### 确认赠送，继续支付：
![default](https://user-images.githubusercontent.com/22112689/29545125-195400c6-871f-11e7-988c-9ee518e5e181.png)
### 选择合适的支付方式（可以支付宝、微信支付哦，建议查看价格后支付）：
![default](https://user-images.githubusercontent.com/22112689/29545171-75d97394-871f-11e7-800c-fa50e633cf76.png)
### 微信支付，￥336原价
![default](https://user-images.githubusercontent.com/22112689/29545363-718bdad8-8720-11e7-848f-8a87f08c91e7.png)
### 支付宝支付，￥338.20（应该是汇率问题，贵一点）
![default](https://user-images.githubusercontent.com/22112689/29545413-c9b438ea-8720-11e7-89dd-b09a4767872e.png)

## 永久有效   两年送3个月！欢迎进入全新世界！
 最新**3个月**赠送邀请码
# `YHQCBUM`
立即下载 https://github.com/getlantern/forum
一起享用三个月的专业版赠送。购买时点击两年套餐后填入。

**Comment by anmac** [comment]
购买蓝灯的时候填写邀请码双方可以获赠三个月,一般是自己准备一个小号来推荐,这样获赠的三个月就可以给自己的小号了,送人很合适

**Comment by JDDCN** [comment]
@anmac 哦，还可以这样操作呀~那要求码是注册了就有吗？

**Comment by ethan112323** [comment]
输入我的邀请码 # JFTW7F 来获得三个月的蓝灯专业版！

**Comment by p3rcya** [comment]
本论坛不要发只有邀请码没有其他内容的帖子，请发到其他论坛，见 https://github.com/getlantern/forum/issues/3773 ，屡教不改者将封号处理。

**Comment by lucyddd** [comment]
国内的基本都被封杀了，就是存活的，也存在跑路风险，你还是直接买国外的吧，替代蓝灯，天行，Green，豆荚等
http://zhizhi.npage.de/
