### ISSUE TITLE
mac系统,能正常登陆,不能访问所有屏蔽网站

### ISSUE THREAD

**Issue by anmac** [getlantern/forum#3871]
遇到的问题：mac系统,能正常登陆,不能访问所有屏蔽网站
蓝灯专业版账号 Email: mhk466@163.com
应用内报告问题的时间: 2017/08/23 09:06:40

**Comment by anmac** [comment]
然后别特么提供那个 window 系统的解决方案了,看清楚是 mac 系统

**Comment by anmac** [comment]
@p3rcya

**Comment by anmac** [comment]
@p3rcya 按照你们规定的格式发帖了, 什么时候可以给解决方案

**Comment by orbancanon** [comment]
@anmac 请到Lantern界面的设置里面把“设置系统代理”一项打上勾。它默认是勾上的，你可能是无意中去掉了。

**Comment by anmac** [comment]
@orbancanon 谢谢,能上网了
