### ISSUE TITLE
刚刚买的蓝灯，有人要邀请码吗？

### ISSUE THREAD

**Issue by zyukyunman** [getlantern/forum#3879]
输入我的邀请码 YFMFH3M 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by c2303191** [comment]
汗

**Comment by ethan112323** [comment]
输入我的邀请码 **JFTW7F** 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by p3rcya** [comment]
本论坛不要发只有邀请码没有其他内容的帖子，请发到其他论坛，见 https://github.com/getlantern/forum/issues/3773 ，屡教不改者将封号处理。
