### ISSUE TITLE
用蓝灯支付东西安全不？

### ISSUE THREAD

**Issue by chrimiway** [getlantern/forum#3880]
比如play store， 或者amazon的东西，还有填信用卡什么的

**Comment by tbirder** [comment]
蓝灯仅仅是给你增加了一个绕过GFW的中转服务器而已。现在已经是越来越多的网站支持https，也就是SSL的加密传输协议，像play store， amazon就更不用说了，无论数据怎么中转，都是相对安全的。

如果你的电脑被劫持而导致的不安全，这就和用不用蓝灯没啥关系了。
