### ISSUE TITLE
最新的蓝灯邀请码

### ISSUE THREAD

**Issue by zhujunpengguizhou** [getlantern/forum#3881]
输入我的邀请码 56UQP7 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by p3rcya** [comment]
本论坛不要发只有邀请码没有其他内容的帖子，请发到其他论坛，见 https://github.com/getlantern/forum/issues/3773 ，屡教不改者将封号处理。

**Comment by 709724811** [comment]
蓝灯邀请码：JT8RBX

**Comment by HxXhY** [comment]
输入我的邀请码 HRFWM3 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
