### ISSUE TITLE
刚才无意在论坛看到有人分享破解版，然后好奇下下来居然能用，我就想问问能退款吗？😳

### ISSUE THREAD

**Issue by rsx9981** [getlantern/forum#3902]
无语了，居然有破解版，白花了我三百大钞

**Comment by rsx9981** [comment]
这里是链接，不信可以自己试试看，我就看管理员怎么看待这个问题：https://drive.google.com/file/d/0B-Dg-ynZaJFPbDhEWDJOZm1DeU0/view?usp=drivesdk

**Comment by c2303191** [comment]
你买个windows正版，然后你发现了windows盗版，然后你因为有盗版找微软要求退款，请问你是不是这个逻辑？

**Comment by rsx9981** [comment]
楼上的，我只是开个玩笑的说了下，顺便把盗版给管理员看看，到底怎么回事，你小子就这么爱喷？

**Comment by tbirder** [comment]
只要是软件，就无法避免被破解。
微软、abobe、autodesk这些奇贵无比的软件用用盗版就算了。一个两年多只要300多块的小工具，况且通过分享还能赠送时长，真心没必要这样。在购买之前，我就知道有破解版，我并没有用，担心安全，谁知道内置了什么恶意代码，没多少钱犯不着。

**Comment by c2303191** [comment]
我转述了你的想法就叫喷？那你算不算喷？

**Comment by chengziqing** [comment]
这个盗版假的，明显就是2.2.5包装的，并且很不安全，额外开启了定位权限和设备读取权限。放了2个广告。只能忽悠小白。

**Comment by sakura-lemon** [comment]
支持官方正版，使用起来安全、放心。很多破解版都会添加广告，而且大多数破解版并未成功破解，而是标榜，吸引用户去下载，骗取访问量而已。

**Comment by p3rcya** [comment]
这些都只是破解界面自欺欺人的。很多都有病毒，请小心
