### ISSUE TITLE
Play Store已更新3.7.6正式版？

### ISSUE THREAD

**Issue by tbirder** [getlantern/forum#3904]
今天的谷歌商店，推送了更新。这次是比论坛快？

![img_20170827_073116](https://user-images.githubusercontent.com/30400128/29745889-10b6007e-8a8d-11e7-9003-a85849fc67da.png)

**Comment by KnightSch** [comment]
我怎么看到还是3.7.2版本？

**Comment by tbirder** [comment]
@KnightSch  google play store 上的应用据说都是分批推送的。

**Comment by Jannister** [comment]
但是论坛已经出了谜之4.0.0测试版。。。

**Comment by tbirder** [comment]
@Jannister  4.0.0这个还是测试版，大版本更新，一般更新幅度较大，先期测试，测试周期偏长，很多软件都是这么做的。我说的是正式版。

**Comment by Jannister** [comment]
@tbirder 我的意思是，论坛还没出来3.7.6正式版就先出来了4.0.0测试版

**Comment by tbirder** [comment]
@Jannister 这很正常，大版本迭代，先期测试
