### ISSUE TITLE
绑定规则

### ISSUE THREAD

**Issue by GD-HBX** [getlantern/forum#392]
根据某些国人的无节操尿性，如果解绑和再绑定是可以立即进行的话（毕竟你的卖点是pro用户不限速和不限流量，滥用的话就...），可能会出现被玩坏的情况，有人会进行二次售卖；建议开发团队在绑定机制上做些限制，比如3个账户解绑再绑定是有时间限制的，或者2个设备解绑再绑定是有时间限制的，剩下的一个无限制（这剩下的一个解绑再绑定无限制可以发给朋友试用）。最好考虑一下，不然到时候买了的多了你不好修改这个限制。

**Comment by p3rcya** [comment]
对这个可以考虑，每次可以这样，每次绑定和解除都需要7时间

**Comment by p3rcya** [comment]
但是我觉得现在没有限制，也很难二次售卖啊。 毕竟是要用用户email登陆的。

**Comment by GD-HBX** [comment]
@p3rcya 那也是，因为一旦登录每个设备都可以在软件设置里解绑其余两个，估计也不会有人在这样的机制下二次贩卖吧😁

**Comment by p3rcya** [comment]
对应该不会。如何倒是发觉有人进行这样贩卖我们再解决吧
