### ISSUE TITLE
为什么我买的两年蓝灯专业版莫名其妙的少了一年？

### ISSUE THREAD

**Issue by DFVSQY** [getlantern/forum#3924]
前几天刚买的蓝灯专业版两年，另加额外7个月免费时长，昨天看时还是到2020年3月份到期，今天就突然变成了2019年3月份到期，时间上明显少了一年，这是怎么回事？
相关账号信息：邀请码Y28VTPQ
截图：
![qq 20170829131320](https://user-images.githubusercontent.com/8075421/29805411-496d9158-8cbc-11e7-9326-b091ec532bb1.png)

**Comment by c2303191** [comment]
还能这样。。。

**Comment by c2303191** [comment]
打土豪，分时长

**Comment by DFVSQY** [comment]
这个问题很严重啊 为什么没有客服出来处理一下？刚买的就少了一年啊！

**Comment by tbirder** [comment]
猜想你可能违规受到了处罚，扣一年可能是轻的，还有封号的。

**Comment by DFVSQY** [comment]
在未收到任何警告或者提示的情况下莫名其妙的就被随意减少了一年？
这也太随意了吧？请客服人员出来解释一下？刚买了几天就少了一年太严重了！

**Comment by DFVSQY** [comment]
在未收到任何通知或者说明的情况下突然就少了一年的时间究竟是刻意还是意外？
客服出来说明一下啊？纠结。。。
