### ISSUE TITLE
自己租个vps搭建vpn吧，我以前的账号已经被封，无任何不良行为，连个答复都没有

### ISSUE THREAD

**Issue by ethan112323** [getlantern/forum#3938]

**Comment by ethan112323** [comment]
过去个把月了，连个正式的回答都没有，果然没有政府监管的地方就是黑吃黑。

**Comment by DFVSQY** [comment]
蓝灯在用户付费后随意修改购买内容是相当不诚信的行为，十分的可耻！
希望想要购买的用户注意一下，另外请相关管理者重视一下这个问题，这样问题的性质十分严重，非常有违基本契约精神，具有诈骗的性质！
