### ISSUE TITLE
十分恶劣，蓝灯在购买后悄无声息的在背后修改时长！

### ISSUE THREAD

**Issue by DFVSQY** [getlantern/forum#3939]
在未收到任何通知或者说明的情况下，购买之后被蓝灯在后台恶意删除时长，一年二百多块钱突然就白交了，对此蓝灯不给任何回复，行为十分恶劣！

**Comment by c2303191** [comment]
我推荐周围5个同事拿到的一年多时长说扣掉就扣掉。我只有一个服。一个商业软件这么乱搞，不知道能走多远

**Comment by DFVSQY** [comment]
我的在完全不知情的情况下连自己花钱购买的时长都被悄无声息的删除了，一年二百多的费用就这样在毫不知情的情况下白交了，蓝灯这种行为有违基本契约精神和商业诚信，十分可耻！
不知道这是蓝灯高层的意思还是蓝灯下面操作员的意思，总之对蓝灯的诚信程度十分怀疑。

**Comment by c2303191** [comment]
我在蓝灯之前也购买过无数其他付费软件，在一个论坛偶犯一个版规（关键这个版规一般人还真不好找），连个警告都没，就能直接随意删除时长甚至封停你的使用权，我只能说这种霸王条款和随意性我真的是头一次见到，不过谁让咱在中国呢，啥事都可能遇到。只能认栽

**Comment by DFVSQY** [comment]
**希望这个帖子能引起相关购买者的注意和相关管理者的重视，花了好几百之后随意随意修改购买内容这种具有诈骗性质的行为十分可耻，望改正！**

**Comment by SendLessLove** [comment]
刚想购买的，看到这个issues，希望出来解释一下

**Comment by lemonskkyt** [comment]
https://github.com/getlantern/forum/issues/3773

**Comment by ward233** [comment]
1年1买就差不多了，毕竟人家是”美国人“的软件嘛。

**Comment by ssy341** [comment]
看标题还以为lantern偷偷给我们增加了时长，窃喜了一下:)

**Comment by p3rcya** [comment]
论坛主页清楚的写了版规 https://github.com/getlantern/forum
