### ISSUE TITLE
8月31日买的专业版一年，为什么今天显示还有38天到期

### ISSUE THREAD

**Issue by xxrshanshan** [getlantern/forum#3953]
8月31日买的一年，昨天显示是还有一年零一个月到期（用了推荐码），为什么今天变成还有38天到期。

**Comment by xxrshanshan** [comment]
昨天因为初次使用论坛，发了一个邀请码，可是为什么直接扣除了一年的时间。

**Comment by Yavash** [comment]
这样严重的问题，官方竟然没有人回答……

**Comment by orange520** [comment]
官方要跑路了看來，大家想買的請三思了。

**Comment by p3rcya** [comment]
你的过期时间是2018-09-09 38天是哪里看出来的？
