### ISSUE TITLE
嗯？没购买专业版就无限流量了？？

### ISSUE THREAD

**Issue by 1638513336** [getlantern/forum#3963]
![default](https://user-images.githubusercontent.com/31557955/29992603-8bef023c-8fd2-11e7-9baf-5a50834e4465.png)

这是哈情况？？？从蓝灯官网下载正版软件（貌似是4.0.0版本）但没购买专业版就无限流量咯？？看YouTube 1080P都不卡？？BUG吗？？

**Comment by p3rcya** [comment]
这个应该只是界面没有刷新出来而已，刷新几次就会显示。流量到了速度还是会限制的

**Comment by psychopassor** [comment]
免費是日本服務器😢付費的想用日本服務器而不能😂
