### ISSUE TITLE
4.0.0版PC端小概率crash同样存在

### ISSUE THREAD

**Issue by tbirder** [getlantern/forum#3965]
同一台电脑，win10系统，之前的版本如3.7.2，3.7.4都正常，卸载并删除根目录安装4.0.0版后，出现了一定概率的crash，找另一台win7系统的电脑测试，依然存在，PC端内部已提交报告。日志附后：

[lantern.zip](https://github.com/getlantern/forum/files/1271927/lantern.zip)

**Comment by p3rcya** [comment]
正在调查

**Comment by frezeman** [comment]
反应速度岗岗的，期待为ios版而付费

**Comment by tbirder** [comment]
@p3rcya 说来也奇怪，早上安装后，两个小时内抽了三次风。然后整个下午和晚上又是好好的，一次风都没抽过...

**Comment by tbirder** [comment]
@p3rcya   简直经不起夸奖，20: 05 （Beijing Time）又crash了，日志附后：
[lantern.zip](https://github.com/getlantern/forum/files/1272148/lantern.zip)

**Comment by orbancanon** [comment]
@tbirder 谢谢反馈！确实是一个bug，会很快修复。在这期间，请你打开Lantern之后把显示的界面关掉，应该会避免这个问题发生。

**Comment by tbirder** [comment]
@orbancanon   今天上午又crash了，如果你已经确认了问题所在，我就不再上传新的日志了。

**Comment by orbancanon** [comment]
@tbirder 你当时Lantern的页面开着的吗？如果是，那应该是同样的原因。如果没有的话，那就麻烦再点一次报告问题。我从后台可以看到你的日志。

**Comment by tbirder** [comment]
@orbancanon  开着呢，应该是同样的问题。

**Comment by orbancanon** [comment]
@tbirder 嗯，那就是了。在新版本出来之前，关掉Lantern页面就可以规避这一问题。

**Comment by tbirder** [comment]
@orbancanon  这个问题在 4.0.1 version 中同样存在，貌似没有的到修复。日志附后：
[lantern.zip](https://github.com/getlantern/forum/files/1283617/lantern.zip)

**Comment by tbirder** [comment]
@orbancanon 这个问题在4.1.0测试版中同样存在，并为彻底解决，日志附后：
[lantern.zip](https://github.com/getlantern/forum/files/1327005/lantern.zip)
