### ISSUE TITLE
没购买专业版都能无限流量？怀疑是BUG

### ISSUE THREAD

**Issue by 1638513336** [getlantern/forum#3975]
从蓝灯官网上下载的最新版，也从未购买过专业版，不知怎么回事流量也没有被限制（如图）？
![default](https://user-images.githubusercontent.com/31557955/30000561-c044d760-90a3-11e7-9137-bdad03000636.png)

虽然没有显示本月已用的流量，但我相信本月我使用的流量已超过 500Mb ，但现在看1080P视频都不卡

重装了两遍操作系统和N遍蓝灯，但问题依旧如此，我不知道这是怎么回事。

**Comment by tbirder** [comment]
https://github.com/getlantern/forum/issues/3963
