### ISSUE TITLE
蓝灯4.0.1正式版发布，提高稳定性

### ISSUE THREAD

**Issue by ghost** [getlantern/forum#4014]
若无法使用，请看[蓝灯无法使用的解决办法](https://github.com/getlantern/forum/issues/1902)

[Windows 版本(要求XP SP3以上)](https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer.exe)      [备用地址](https://s3.amazonaws.com/lantern/lantern-installer.exe)  
[安卓版(要求4.1以上)](https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer.apk)               [备用地址](https://s3.amazonaws.com/lantern/lantern-installer.apk) [Google Play下载](https://play.google.com/store/apps/details?id=org.getlantern.lantern) **请勿使用UC浏览器下载，会被替换成假的有广告的版本**  

**蓝灯iOS版本将在2018年发布，现有App Store上的蓝灯均为假冒。**  iOS版本开发完毕会在论坛上通知

[macOS (10.7及以上)](https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer.dmg)              [备用地址](https://s3.amazonaws.com/lantern/lantern-installer.dmg) 

[Ubuntu 14.04 32位](https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-32-bit.deb)
[Ubuntu 14.04 64位](https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-64-bit.deb)

**Comment by chengziqing** [comment]
修改了哪些问题也不简短说明一下

**Comment by EdwardAutumn** [comment]
@p3rcya 
我也建议每次更新给出一些修复BUG日志之类的，加强和用户的互动，不是每次更新都是空洞的版本数字。

**Comment by z00368452** [comment]
为什么这个点连谷歌都上不去？ 代理服务器显示的是阿姆斯特丹

**Comment by p3rcya** [comment]
@z00368452 请给在发帖前先按照[蓝灯无法使用的解决办法](https://github.com/getlantern/forum/issues/1902)自行解决。自行解决问题通常只需要几十分钟。管理员调查解决问题需要几天至几周。

若无法按照[蓝灯无法使用的解决办法](https://github.com/getlantern/forum/issues/1902)自行解决，愿意等待管理员人为调查的，请按照如下格式发帖。https://github.com/getlantern/forum/issues/3536 不按照格式发帖无法调查，谢谢。

**Comment by KnightSch** [comment]
@p3rcya 蓝灯iOS版本将在2018年发布，希望不要是18年年底，哈哈

**Comment by frezeman** [comment]
新鲜出炉，哈哈，更新了

**Comment by qcind** [comment]
labs.

**Comment by sodabluesff** [comment]
@p3rcya   为何play store 里更新总是不及时？

**Comment by shuiyingwuhen** [comment]
@p3rcya ，WIN8 频繁闪退

**Comment by rocknrollfly** [comment]
蓝灯要注意和杀毒软件厂商沟通，最新两个版本AVAST报毒

**Comment by BlueAubrey** [comment]
ipad 能安装吗

**Comment by ssy341** [comment]
@BlueAubrey 等2018年ios版出来了就可以在ipad上安装了

**Comment by sk28moon39** [comment]
购买了收不到邮件怎么办？

**Comment by zhruith** [comment]
能不能把切换【代理系统流量】和【代理全部流量】的check button 放在首页下角，别设计的那么隐蔽，因为经常要切换，要点好几下才能点到，这浪费很多时间。谢谢。

**Comment by Centaur** [comment]
已安装4.0.0，Lantern会自己升级到4.0.1吗？

**Comment by Yoefs** [comment]
更新后有什么改变呢？

**Comment by justinpp** [comment]
727956571@qq.com   我登录直接提示我错误的输入或缺少参数！！！哪里解决了，麻烦管理查明给个解释！！！！！

**Comment by evanoxu** [comment]
@KnightSch 我是希望能在我续费前见到iOS版（ps: 19年到期）

**Comment by kokoo1230** [comment]
更新之后代理显示日本，相比以前的版本无论是YOUTube还是上台湾网站都更慢了，之前YOUTUBE1080P不用缓冲，现在480都看不流畅，请问怎么更改代理区域？

**Comment by lucyddd** [comment]
国内的基本都被封杀了，就是存活的，也存在跑路风险，你还是直接买国外的吧，替代蓝灯，天行，Green，豆荚等
http://zhizhi.npage.de/
