### ISSUE TITLE
2017年9月6号购买的两年账号，出售两个位置

### ISSUE THREAD

**Issue by z00368452** [getlantern/forum#4021]
![image 1](https://user-images.githubusercontent.com/24273293/30172985-d4ce319e-9428-11e7-96cc-572ebac5397c.png)

**Comment by fyb521** [comment]
要一个。

**Comment by yantj1027** [comment]
怎么算。

**Comment by qdcoltking** [comment]
要一个，邮件联系我吧qdcoltking@live.com

**Comment by z00368452** [comment]
100一个，要的请联系WeChat：330845311
