### ISSUE TITLE
我的专业版账户使用时间突然由1300多天减少至300多天，请问原因，谢谢！

### ISSUE THREAD

**Issue by meibujun** [getlantern/forum#4034]
我的专业版账户使用时间突然由1300多天减少至300多天，请问原因，谢谢！

**Comment by p3rcya** [comment]
请提供邮箱。你违反版规发过邀请码么？ 见 https://github.com/getlantern/forum/issues/3773

**Comment by meibujun** [comment]
meibujun@163.com

**Comment by p3rcya** [comment]
根据记录，你多次违规在论坛发只有邀请码的帖子，见 #3773 扣除了因为违规而赠送的时间。付费购买的时间没有影响

**Comment by meibujun** [comment]
可是我今年才购买，而且记得买了二年服务期，不可能现在只剩300多天，谢谢


发自我的 iPhone

**Comment by psychopassor** [comment]
1300多天！天呐，这是赠送了多少时间！不过在邀请码汇总贴里发的邀请，根本就是石沉大海……

**Comment by p3rcya** [comment]
帮你加了一年

**Comment by meibujun** [comment]
谢谢帮助，谢谢！

发自我的 iPhone
