### ISSUE TITLE
邮箱收不到邮件没有管理人回答下吗

### ISSUE THREAD

**Issue by justinpp** [getlantern/forum#4035]
说几个小时这都24小时了，是不是被腾讯吞了感觉，还是没发啊，有什么解决办法，管理人员回答下好吗，申请也提交了还是没有回信，用不了真是急死人啊，来个人回答下这么难吗

**Comment by orange520** [comment]
我看好多人有這樣的問題，搞得我都不敢買了

**Comment by rocknrollfly** [comment]
建议用 hotmail 的邮箱

**Comment by p3rcya** [comment]
部分邮箱无法收到邮箱登陆码的问题已经解决 
https://github.com/getlantern/forum/issues/4067
