### ISSUE TITLE
授权专业版收不到邮件啊，已经两天了都收不到

### ISSUE THREAD

**Issue by yeonss** [getlantern/forum#4036]
怎么办啊啊啊啊？

**Comment by yupuxilong** [comment]
收了钱就撒手不管了？

**Comment by orange520** [comment]
被坑了

**Comment by rocknrollfly** [comment]
建议各位使用hotmail的邮箱 @yupuxilong @orange520

**Comment by p3rcya** [comment]
部分邮箱无法收到邮箱登陆码的问题已经解决 
https://github.com/getlantern/forum/issues/4067
