### ISSUE TITLE
Lantern最近用不了，转战XX-Net，goagent大神的力作。

### ISSUE THREAD

**Issue by lkptantan** [getlantern/forum#404]
用这种商业化见鬼去吧

**Comment by zhouzhiwen2000** [comment]
换VPN吧
Lantern注意力不在free用户上
买linodevps最近有优惠，自己搭一个SS，用IPV6代理（如果你是教育网的话），十分稳定
bandwagonhost ipv4不稳定，但是ipv6很好，价格很便宜，100+元包年
ipv6能分到5个IP左右，可以写个脚本自动切换IP.

**Comment by zhouzhiwen2000** [comment]
XX-Net，goagent不稳定

**Comment by zhouzhiwen2000** [comment]
如果不会设置可回复问我

**Comment by zhouzhiwen2000** [comment]
如果你有现成vps更好了

**Comment by panzer1313208** [comment]
@lkptantan 呵呵，逗逼，XX-Net，goagent用的是谷歌GAE服务，而且前段时间xxnet彻底瘫痪因为GFW直接封了xxnet的内置IP。没有IP你还怎么翻墙？

**Comment by panzer1313208** [comment]
XXNET免费的前提是因为谷歌的GAE服务器是免费的。

**Comment by panzer1313208** [comment]
而且，我是xxnet的作者之一，知道xxnet的检查IP功能么？我弄的

**Comment by panzer1313208** [comment]
xxnet终究是在弄appid这个部分太麻烦而且内置IP段被封也就没什么卵用了。上海电信至今无法使用xxnet。

**Comment by hynum** [comment]
不明觉厉

**Comment by maozaiba** [comment]
这是蓝灯反馈论坛，为毛会有XXNET的人，居然还有自称作者之一的人。。。

**Comment by CherryMill** [comment]
在Linux上可以用啊。。用WIndows本来就会有诸多限制的啊

**Comment by panzer1313208** [comment]
@maozaiba 蓝灯反馈论坛，你知道我解答了多少蓝灯问题= =

**Comment by panzer1313208** [comment]
感觉还是蓝灯好，简单

**Comment by Garden-Q** [comment]
实测xxnet也翻不了

**Comment by panzer1313208** [comment]
@Garden-Q 不可能，肯定是你没弄对，或者你是上海电信？

**Comment by yuwuyan** [comment]
稍微复杂的东西我都弄不来~
蓝灯好就好在简单

**Comment by NAVrasZ** [comment]
@panzer1313208 其实电信哪个地方的都坑，之前我电信用lantern上youtube测速就只有300k，还经常翻不动，某博主已经建议要翻就不能选电信。

**Comment by CherryMill** [comment]
电信ISP网络的问题?



发自我的小米Pad
在 NAVrasZ <notifications@github.com>，2016年7月12日 11:42写道：

@panzer1313208<https://github.com/panzer1313208> 其实电信哪个地方的都坑，之前我电信用lantern上youtube测速就只有300k，还经常翻不动，某博主已经建议要翻就不能选电信。

**Comment by ssy341** [comment]
@panzer1313208  你们说的ss是什么啊？全称是啥？

**Comment by lkptantan** [comment]
没想到变成一吹水贴了
