### ISSUE TITLE
邀请码 NRCFVJ

### ISSUE THREAD

**Issue by jay9527** [getlantern/forum#4041]
输入我的邀请码 NRCFVJ 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forumApply coupon code NRCFVJ to get FREE THREE MORE MONTHS Lantern PRO!﻿

**Comment by p3rcya** [comment]
本论坛不要发只有邀请码没有其他内容的帖子，请发到其他论坛，见 https://github.com/getlantern/forum/issues/3773 ，赠送的时间已经扣除，屡教不改者将封号处理。
