### ISSUE TITLE
专业版账号，恢复邮件始终收不到。。。能处理下么

### ISSUE THREAD

**Issue by yupuxilong** [getlantern/forum#4042]

**Comment by orange520** [comment]
好多這種貼都沒有個答復，我看懸！

**Comment by yeonss** [comment]
我的也收不到 气死

**Comment by yupuxilong** [comment]
苹果笔记本更新了软件就要求恢复专业版，然后一直收不到邮件，账号85806021@qq.com

**Comment by baiyibaiyi** [comment]
不要用qq，請用gmail。

**Comment by yeonss** [comment]
但是之前购买的时候用的QQ邮箱啊，再说gmail国内根本用不了，这算什么解决方法……

**Comment by rocknrollfly** [comment]
建议各位用 hotmail

**Comment by psychopassor** [comment]
126/163/outlook都行，很少用QQ邮箱了

**Comment by yupuxilong** [comment]
买的时候怎么不提醒要用什么邮箱，现在的处理方式不是应该主动联系收不到邮件的人，人为的帮他们处理，并且再购买时注明使用的邮箱种类，避免出现类似的问题，望严肃对待。

**Comment by steven129** [comment]
我的也收不到，重装蓝灯最新版就用不了。已尝尽各种办法。邮箱460483629@qq.com.望解决？

**Comment by nbhero007** [comment]
我的也是，买的时候就是QQ邮箱。58869224@qq.com。收不到验证码

**Comment by p3rcya** [comment]
部分邮箱无法收到邮箱登陆码的问题已经解决 
 https://www.microsoft.com/zh-cn/outlook-com/

**Comment by yupuxilong** [comment]
没收到邮件，但是已经恢复正常使用了。
