### ISSUE TITLE
我的邀请码

### ISSUE THREAD

**Issue by ottolhp** [getlantern/forum#4052]
因为版面有限，请大家不要开新帖发邀请码。请将邀请码汇总到此贴中，谢谢！ 也欢迎大家把邀请码发表到其他论坛或者微信群。

我的邀请码 GYB4W2

若购买两年版双方都获赠3个月，若购买一年版双方都获赠1个月。

**Comment by p3rcya** [comment]
本论坛不要发只有邀请码没有其他内容的帖子，请发到其他论坛，见 https://github.com/getlantern/forum/issues/3773 ，赠送的时间已经扣除，屡教不改者将封号处理。
