### ISSUE TITLE
我的邀请码 FXXDZ2 

### ISSUE THREAD

**Issue by steven2081** [getlantern/forum#4053]
输入我的邀请码 FXXDZ2 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by saohuw** [comment]
大家不要买千万，收不到验证码。白花钱

**Comment by p3rcya** [comment]
本论坛不要发只有邀请码没有其他内容的帖子，请发到其他论坛，见 https://github.com/getlantern/forum/issues/3773 ，赠送的时间已经扣除，屡教不改者将封号处理。
