### ISSUE TITLE
收不到邮箱验证码希望您老解决

### ISSUE THREAD

**Issue by saohuw** [getlantern/forum#4054]
我看到好多人发帖都收不到验证码，而且官方人员也没有回复。
这服务态度真是6666
我QQ：1026367232
谁能帮我解决，感激不尽！

**Comment by steven129** [comment]
卸载原来的，后面装上最新的蓝灯，现在不能登录为专业：已有专业设备使用或者邮箱登录。电脑都没变过。各种方法都用上了，也没有？

**Comment by p3rcya** [comment]
部分邮箱无法收到邮箱登陆码的问题已经解决 
 https://www.microsoft.com/zh-cn/outlook-com/
