### ISSUE TITLE
专业版，求帮助，邮箱460483629@qq.com.卸载重装最新版蓝灯就不再是专业版。电脑不变，系统没有重装，各种方法已用了。

### ISSUE THREAD

**Issue by steven129** [getlantern/forum#4058]
![aa](https://user-images.githubusercontent.com/31800743/30245818-39196e8e-9618-11e7-8d25-f65c8fec0637.jpg)
![2](https://user-images.githubusercontent.com/31800743/30245820-3a842f70-9618-11e7-91f1-09a454e577eb.jpg)

**Comment by justinpp** [comment]
同，等死ing。只要是有关邮箱收不到的问题都没有管理回复，害怕。。

**Comment by haook500** [comment]
是吗

**Comment by nwh91camille** [comment]
愁死了，我也是这个情况

**Comment by p3rcya** [comment]
部分邮箱无法收到邮箱登陆码的问题已经解决 
 https://www.microsoft.com/zh-cn/outlook-com/
