### ISSUE TITLE
蓝灯授权等死ing

### ISSUE THREAD

**Issue by charlesYMX** [getlantern/forum#4061]
买了专业版  登陆了一个，但是在另一台电脑授权动态，等了一天没有消息，有没有大侠遇到过，管理员能给个解释吗？

**Comment by nbhero007** [comment]
同问，我的是qq邮箱

**Comment by p3rcya** [comment]
部分邮箱无法收到邮箱登陆码的问题已经解决 
https://github.com/getlantern/forum/issues/4067
