### ISSUE TITLE
部分邮箱无法收到邮箱登陆码的问题已经解决

### ISSUE THREAD

**Issue by p3rcya** [getlantern/forum#4067]
如果你无法收到邮箱登陆码，请
1. 下载安装最新的4.0.1版本，下载地址 https://github.com/getlantern/forum/issues/4014
2. 点击邮箱登陆后，检查邮箱的垃圾邮件
3. 如果你有其他登陆专业版的设备，可以用这些设备授权登陆。

若还有问题，请在本帖回复报告，并上传邮箱地址。请勿开新贴。

新用户推荐使用微软的Outlook邮箱 https://www.microsoft.com/zh-cn/outlook-com/ 放置以后出现丢信的情况。

**Comment by pzs1911** [comment]
我的邮箱1227758750@qq.com  收不到登入码

**Comment by pzs1911** [comment]
我的邮箱1227758750@qq.com 收不到登入码

**Comment by nwh91camille** [comment]
邮箱895138170@qq.com

**Comment by s081222** [comment]
464977978@qq.com  收不到登入码

**Comment by justinpp** [comment]
邮箱727956571@qq.com

**Comment by 0475zgh** [comment]
我的邮箱0475zgh@163.com收不到登入码

**Comment by cntgkdd** [comment]
邮箱未收到授权码：836145930@qq.com

**Comment by 0475zgh** [comment]
![qq 20170912110740](https://user-images.githubusercontent.com/31855377/30306537-53f248f4-97ab-11e7-8744-a5c3418237e9.png)
我的交易ID:w126373004。用0475zgh@163.com一直没有收到授权登录码。现将邮箱改为：
zgh0475@outlook.com。
![qq 20170912110637](https://user-images.githubusercontent.com/31855377/30306528-4d0347be-97ab-11e7-823d-779f3b6e3ffa.png)

**Comment by 0475zgh** [comment]
朋友们：授权码困扰了多天，今天终于弄明白了。要把授权这台电脑动态授权码，复制下来，再上你最初注册的那电脑上操作，见图
![1](https://user-images.githubusercontent.com/31855377/30328750-dc7fad22-9802-11e7-9698-be78259c8bb8.png)
![2](https://user-images.githubusercontent.com/31855377/30328781-f35af862-9802-11e7-8372-7b4c645a165f.png)
![3](https://user-images.githubusercontent.com/31855377/30328798-fea227fe-9802-11e7-90ab-4faa429e19ae.png)
![4](https://user-images.githubusercontent.com/31855377/30328817-0c16d5ec-9803-11e7-82c1-08006a8f99d5.png)

**Comment by p3rcya** [comment]
没哟收到邮件的，请重新安装4.0.1后重新登陆

**Comment by 0475zgh** [comment]
你好，你们解答的不对，很多用户在论坛里向你们要授权码，其实授权码是用户自己在第一台注册设备注上向自己的另一台设备授权，首先要将要授权设备的动态码，复制后给自己第一台注册的设备来给别另一台设备上进行授权。不是重新安装4.0.1后重新登陆能解决的。我也是困扰了多天发了N遍邮件，最终解决的方法如所述。





在 2017-09-13 00:32:34，"p3rcya" <notifications@github.com> 写道：


没哟收到邮件的，请重新安装4.0.1后重新登陆

**Comment by 0475zgh** [comment]
p3rcya commented 8 hours ago：
你好，你们解答的不对，很多用户在论坛里向你们要授权码，其实授权码是用户自己在第一台注册设备注上向自己的另一台设备授权，首先要将要授权设备的动态码，复制后给自己第一台注册的设备来给别另一台设备上进行授权。不是重新安装4.0.1后重新登陆能解决的。我也是困扰了多天发了N遍邮件，最终解决的方法如所述。

**Comment by zhaoxu0609** [comment]
邮箱759397728@qq.com，收不到邮件，求解决

**Comment by Facebai** [comment]
135194145@qq.com，收不到登录码

**Comment by unsine** [comment]
未收到邮件 unsinegvo@yahoo.co.jp
