### ISSUE TITLE
9-12最新邀请码5S9CVW，还多出一个专业板授权

### ISSUE THREAD

**Issue by lukesun2017** [getlantern/forum#4096]
# 9-12最新邀请码5S9CVW，还多出一个专业板授权

有需要的朋友请及时联系，晚了可就没有了。

**Comment by codeInCat** [comment]
这个怎么用的?

**Comment by p3rcya** [comment]
本论坛不要发只有邀请码没有其他内容的帖子，请发到其他论坛，见 https://github.com/getlantern/forum/issues/3773 ，赠送的时间已经扣除，屡教不改者将封号处理。
