### ISSUE TITLE
邀请码YMC7YB7

### ISSUE THREAD

**Issue by YangShizhao** [getlantern/forum#4114]
小宝，你快输这个邀请码吧，我们在妇联网上相识，你需要骑行的爱啊
YMC7YB7

**Comment by p3rcya** [comment]
本论坛不要发只有邀请码没有其他内容的帖子，请发到其他论坛，见 https://github.com/getlantern/forum/issues/3773 ，赠送的时间已经扣除，屡教不改者将封号处理。

**Comment by YangShizhao** [comment]
哇，这就过分了啊，怎么就给我把时间扣了，整个页面就一个new issue看起来像是回帖的按钮，谁知道还要拉到最下面才能回复啊！






在 2017-09-14 12:59:27，"p3rcya" <notifications@github.com> 写道：


本论坛不要发只有邀请码没有其他内容的帖子，请发到其他论坛，见 #3773 ，赠送的时间已经扣除，屡教不改者将封号处理。
