### ISSUE TITLE
新出炉的邀请码 输入我的邀请码 LY4WK2 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

### ISSUE THREAD

**Issue by jipinqishi** [getlantern/forum#4117]
输入我的邀请码 LY4WK2 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by s1socks** [comment]
我用了，“系统将在结账后赠送您一个月云云”。

**Comment by s1socks** [comment]
J9RYWT 这是我的，楼下继续。

**Comment by p3rcya** [comment]
本论坛不要发只有邀请码没有其他内容的帖子，请发到其他论坛，见 https://github.com/getlantern/forum/issues/3773 ，赠送的时间已经扣除，屡教不改者将封号处理。
