### ISSUE TITLE
分享个2年的邀请码 4MMGXC

### ISSUE THREAD

**Issue by MaoRey** [getlantern/forum#4124]
输入我的邀请码 4MMGXC 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
购买前输入邀请码，2年的你和我都会额外获得三个月
都没有更新了，打个广告不会删我吧

**Comment by p3rcya** [comment]
本论坛不要发只有邀请码没有其他内容的帖子，请发到其他论坛，见 https://github.com/getlantern/forum/issues/3773 ，赠送的时间已经扣除，屡教不改者将封号处理。
