### ISSUE TITLE
lantern 3.0.5电脑版是正规发布的吗？

### ISSUE THREAD

**Issue by asustnt** [getlantern/forum#413]
我看到网上有下载3.0.5的版本，打开后流量是0

**Comment by EdwardAutumn** [comment]
你哪下的3.05？我记得3.05后来被开发者换回3.04了

**Comment by asustnt** [comment]
我在百度里收搜索出来的，今天下午找到的

**Comment by EdwardAutumn** [comment]
别百度啊，赶紧删了
https://s3.amazonaws.com/lantern/lantern-installer-3.0.6.exe
这是官方最新版本，下载要翻墙。安卓版本将末尾改成exe改为apk

**Comment by asustnt** [comment]
兄弟，非常感谢！！！

**Comment by EdwardAutumn** [comment]
问题解决了的话选择close issue.

**Comment by asustnt** [comment]
我选择了免费试用专业版，跳出“您的邀请码  CWLCWT”，然后再开一个比如 google.com，过了一会就跳出“Still unable to dial tcp://www.google.com:80 after 3 attempts”，这句话麻烦看看是什么意思，我哪里操作错了？谢谢了

**Comment by EdwardAutumn** [comment]
跳邀请码是正常的，后面那个错误你把tcp改成https看看?

**Comment by asustnt** [comment]
我输入了https://www.google.com，等了一会，显示”无法显示此页“。唉~~~而且右上角显示 您本月的免费流量还有0MB。这个是怎么回事情呀，谢谢~

**Comment by EdwardAutumn** [comment]
那我就母鸡了，等版主现身。

**Comment by asustnt** [comment]
其实我安装了3.0.4/5/6，都显示只有0MB。。。
