### ISSUE TITLE
输入我的邀请码 62RUPX

### ISSUE THREAD

**Issue by TangBean** [getlantern/forum#4159]
输入我的邀请码 62RUPX 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

自己买的VPS慢死了 :-(

希望Lantern好用 :-)

**Comment by VisionKwok** [comment]
请不要发只有邀请码没有其他内容的帖子,违反者将扣除所有赠送时间。具体见 #3773
