### ISSUE TITLE
所谓的蓝灯吧官方群  说是为了帮助人  其实是挂羊头卖狗肉

### ISSUE THREAD

**Issue by kxkxkx** [getlantern/forum#418]
蓝灯开发者论坛里现在有人发布蓝灯吧官方群  说是为了帮助人  其实是挂羊头卖狗肉 为了卖自己的ss

http://i4.piimg.com/1949/5fe821d0c2889229.png

http://chuantu.biz/t5/16/1467993127x2728309165.png

http://img.hoop8.com/1607A/yfbBF0Hi.png

**Comment by GD-HBX** [comment]
0.0

**Comment by panzer1313208** [comment]
@kxkxkx 别人要买，我当然卖啊。

**Comment by panzer1313208** [comment]
![_fzlx kf2m31x9 r1a ut1](https://cloud.githubusercontent.com/assets/13449426/16694332/3b0cf894-456c-11e6-8ac2-0fccc47551aa.png)
![h p epoq sk zojs 2vf8y](https://cloud.githubusercontent.com/assets/13449426/16694338/3f2f18f8-456c-11e6-8f49-3a782cd1d4a4.png)
![p5m74wy d73wjg 8 xj gzd](https://cloud.githubusercontent.com/assets/13449426/16694343/41af2690-456c-11e6-924c-fd8fe36ed25d.png)
![v 613 wvuwqun5 lh ts](https://cloud.githubusercontent.com/assets/13449426/16694349/4428e23a-456c-11e6-8e5a-31acbc3e779e.png)

**Comment by panzer1313208** [comment]
1级是刚刚进群的

**Comment by panzer1313208** [comment]
1级的人都觉得你在无理取闹。呵呵

**Comment by jsonwork** [comment]
不理哪些人。。共享没有错

**Comment by alivesong** [comment]
由于这几天蓝灯出问题，且我的pc版本长期没升级。 我今晚进了论坛，由此进了所谓的  蓝灯官方群。（现已退群） 现在说下我的亲身经历
      进群后 ，群公告告知此群不用了，加另外一个群。加了后，我在群里问，网速太卡，怎么购买 蓝灯pro。有管理员回答到暂时不要买。   不久   某管理员在群里刷屏说    该论坛有人骂他。以解散群为威胁，要群友一起进论坛对骂。 群友开始大量“讨论”。不到十分钟时间，有管理员先表示“买卖是自愿的”，后承认“蓝灯就是速度慢” “xxnet代理就是速度快”等言论。 风波平息后，群没有解散。而且群文件里有蓝灯3.0.6版本，不知真假。
       同时，我已经在pc端成功通过3.0。4 版本 付费并上网成功。我个人对网速是相当满意的。 于是，我在群里刷屏道蓝灯付费上网成功，网速可以，随后退群。 本不想参与此事。  退群后，威胁群友解散群的管理员立即加我好友，说蓝灯官方说不行，我怎么可以。还问道我是不是此帖贴主。  我告知后，立即被他拉黑。
       综上所述，在此声明：1，以上言论全部属实，半点虚假，立即阳痿。2我无意撕逼，只想把所见到的分享与大家。3我认为无论是lantern还是Google或者美国政府，一直在做着公益性质的事情，造福大家。不能因为收费而被否定，更不应该被怀有不轨之心的人给污染。4 那个所谓的官方群，对lantern没有半点贡献。有的管理员年仅18岁。翻墙已不容易，还要儿戏吗？！  
       最后，我正式提出要求，封广告贴与否在于lantern官方（管理员）的态度，我表示尊重，不多干涉。但官方有必要声明那不是官方群，这既是对lantern负责，也是对用户负责，更是对自己的劳动成果负责。希望lantern能仔细 考虑 @p3rcya

**Comment by panzer1313208** [comment]
楼上说的，“还问道我是不是此帖贴主。  我告知后，立即被他拉黑”对此我表示疑问，你已经退群了，觉得本群对你没什么帮助，我只是问一下你能不能翻墙了，你能翻了，退群了，那我删除你咋了？你能翻我祝贺你。但有更多的人无法翻墙，要不要我截图下发到这里？

**Comment by panzer1313208** [comment]
还有我只是删除，不是拉黑。

**Comment by panzer1313208** [comment]
而且群内这么多支持我的人，你怎么不说？

**Comment by panzer1313208** [comment]
几岁不重要，重要的是能不能帮群里人翻墙，我在群文件里不仅仅放了翻墙软件，还写了详细的教程。

**Comment by panzer1313208** [comment]
3.0.6版本？你确定？要不要你下载一个样本然后把数字签名截图出来？

**Comment by alivesong** [comment]
我只是表达我的个人观点。怎么看待我说的，每个人都有自己的想法。你当然可以坚持说你有做好事。如果你有做好事，帮助到大家，自然会有受到帮助的人来这挺你，不需要你自己再这一条条的刷。只是我的个人看法，仅此而已。不需要针对我刷了，我要说的只这么多。对事不对人。

**Comment by panzer1313208** [comment]
我也跟你一样，对事不对人，你发出了个人经历，我发出对此的回答。

**Comment by panzer1313208** [comment]
你对我群文件里的蓝灯和蓝灯pro有疑问对吧？不太清楚这是不是假的？所以我要发出来告诉大家，是不是假的。

**Comment by panzer1313208** [comment]
![dww37 57eb mil 7vh5l g](https://cloud.githubusercontent.com/assets/13449426/16694845/f29eafe6-456e-11e6-92d3-10c072ebe4de.png)

**Comment by panzer1313208** [comment]
你看到了这2个没错吧？

**Comment by panzer1313208** [comment]
![470 h d2o f w 3 ir3yvb](https://cloud.githubusercontent.com/assets/13449426/16695117/7778cda4-4570-11e6-8d2c-c32971fcfe07.png)
![9p d6c_3xx8 0z rh 36j1](https://cloud.githubusercontent.com/assets/13449426/16695120/800d3bf8-4570-11e6-9d9a-0dc1e322f9d2.png)
![b n0h4dt5f1q8167 2zyljf](https://cloud.githubusercontent.com/assets/13449426/16695125/84202566-4570-11e6-8919-c28a9b502d67.png)

**Comment by panzer1313208** [comment]
![j 42h3 rj0_1j xtucl 9](https://cloud.githubusercontent.com/assets/13449426/16695135/91919dec-4570-11e6-92bc-8b6651354845.png)
![juuzn u1e58r _c27cv tme](https://cloud.githubusercontent.com/assets/13449426/16695138/96ccfa72-4570-11e6-9c82-df9344cd3f40.png)
![ug43_ 3u xfccoqjgvw xs](https://cloud.githubusercontent.com/assets/13449426/16695142/9b5cb514-4570-11e6-857b-bf0bb0d67226.png)
![z j5 s2vdpnlbn6 q imjn](https://cloud.githubusercontent.com/assets/13449426/16695145/9daa327e-4570-11e6-8981-f43b2a1e1276.png)

**Comment by panzer1313208** [comment]
https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-3.0.5.exe，我是直接改后面的版本号然后下载的，现在出了3.0.6了，我要去下载了，各位拜拜。

**Comment by EdwardAutumn** [comment]
@kxkxkx 可以关了，管理员说以后他再发就直接关他的帖子。

**Comment by panzer1313208** [comment]
@EdwardAutumn 你们的目的达到了，高兴了吧？我想知道你们为什么故意黑我？
