### ISSUE TITLE
无法科学上网了，用不了了

### ISSUE THREAD

**Issue by h3idan** [getlantern/forum#42]
用不了了。看了下日志，46开头那个ip都没办法ping通呀

**Comment by xiong0109** [comment]
你改了配置文件？我这边正常使用

**Comment by dopeawn** [comment]
lantern默认设置iE代理，你看你浏览器使用ie代理没有，不行去官网试下 最新版本lantern

**Comment by h3idan** [comment]
@xiong0109  配置文件咋修改？

@dopeawn  已经是最新的了。我用 chrome 跟 ie 有啥关系？ chrome 的 SwitchyOmega 插件。之前版本都没问题。

**Comment by yulianwete** [comment]
被强了

**Comment by fangkejian** [comment]
呜呜，时好时坏，好的概率不高啊

**Comment by h3idan** [comment]
@all,
已经买了 vps 自己搭了shadowsocks ：）
