### ISSUE TITLE
3.0.6发布，解决转圈问题

### ISSUE THREAD

**Issue by ghost** [getlantern/forum#421]
请大家去论坛主页下载 https://github.com/getlantern/forum

直接下载地址
Windows https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-3.0.6.exe
安卓 https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-3.0.6.apk
Mac https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer-3.0.6.dmg

**Comment by EdwardAutumn** [comment]
误杀的问题什么时候能解决，换一个版本就要加一个白名单，我现在每次安装只能先把杀软关了

**Comment by panzer1313208** [comment]
误杀的问题什么时候能解决，有几个人怀疑我上传的是假软件。而且他们居然不会看数字证书。

**Comment by paperbag** [comment]
@EdwardAutumn
基本没有报毒啊，连360都没有。
https://www.virustotal.com/en/file/72c497947e1193e5d10983ef6f103f81a2059dd5ea590e272b7d7d0e444bc99f/analysis/1467999303/

**Comment by dfeng6911** [comment]
MAC上使用仍然是转圈的 OSX 10.10.5

**Comment by p3rcya** [comment]
@dfeng6911 上传log。 如何上传见 https://github.com/getlantern/forum/issues/358

**Comment by dfeng6911** [comment]
[lantern.log.txt](https://github.com/getlantern/forum/files/354900/lantern.log.txt)

**Comment by panzer1313208** [comment]
@paperbag 报毒基本是360和腾讯电脑管家

**Comment by TSfan** [comment]
win 10依旧转圈

**Comment by p3rcya** [comment]
@TSfan 请上传log

**Comment by TSfan** [comment]
[lantern.txt.txt](https://github.com/getlantern/forum/files/355066/lantern.txt.txt)
[lantern.log (2).txt](https://github.com/getlantern/forum/files/355067/lantern.log.2.txt)

[lantern.log (3).txt](https://github.com/getlantern/forum/files/355069/lantern.log.3.txt)
[lantern.log (4).txt](https://github.com/getlantern/forum/files/355070/lantern.log.4.txt)

@p3rcya

**Comment by TSfan** [comment]
我已经搞好了，重新卸载安装就好了

**Comment by fish1330** [comment]
win10依然转圈

**Comment by minion93** [comment]
还是无法购买专业版 用信用卡付款银行都提示预授权6.70元 但是到最后钱还是扣不掉

**Comment by p3rcya** [comment]
@minion93 请问错误提示是什么？给个截图，并按照此帖上传log https://github.com/getlantern/forum/issues/358

**Comment by mxujm1** [comment]
很抱歉，蓝灯似乎未在运行。请重启蓝灯并重试。
这是为什么？

**Comment by mlhmomo** [comment]
购买了蓝灯，但是，电脑却无法使用

**Comment by p3rcya** [comment]
@Linausername 具体什么情况，请截图加上传log

**Comment by yurivikyi** [comment]
win10上使用依然是轉圈

**Comment by p3rcya** [comment]
@yurivikyi 请看照此帖上传log https://github.com/getlantern/forum/issues/358 谢谢

**Comment by turnerguo** [comment]
MAC 上依然转圈。。。10.11.6

**Comment by p3rcya** [comment]
@turnerguo 现在已经到3.1.14了，请下载最新版 https://github.com/getlantern/forum
