### ISSUE TITLE
希望p3rcya能够加入我的群。

### ISSUE THREAD

**Issue by panzer1313208** [getlantern/forum#422]
@p3rcya 帮助我监督群内，并且允许我在这里发群号。

**Comment by panzer1313208** [comment]
可以吗？

**Comment by panzer1313208** [comment]
最主要的是，群内可以收集lantern需要的信息，比如什么地区，什么环境无法用蓝灯。

**Comment by panzer1313208** [comment]
我

**Comment by paperbag** [comment]
@panzer1313208
你这样做是不对滴
你是在怂恿@p3rcya 暴露自己的账号，太危险了

**Comment by p3rcya** [comment]
@panzer1313208 @paperbag 我会新注册一个QQ号，加入，请放心

**Comment by panzer1313208** [comment]
@p3rcya 我要给你管理员，如果你实在是不方便，可以用某种方法私密我。

**Comment by panzer1313208** [comment]
@paperbag 暴露QQ会怎么样？被抓吗？

**Comment by panzer1313208** [comment]
如果暴露QQ会被抓，那我该被抓多少次，毕竟我这个是大号= =7个群，几万人加过。

**Comment by panzer1313208** [comment]
至少有个传播非法软件，或者传播破坏信息安全软件罪？

**Comment by p3rcya** [comment]
@panzer1313208 请留个邮箱，我注册好后email给你

**Comment by panzer1313208** [comment]
@p3rcya qq569532421@gmail.com,或者569532421@qq.com，发完邮件告诉我一下。

**Comment by panzer1313208** [comment]
我几乎不看谷歌邮箱，所以麻烦你发完邮件之后告诉我一下。

**Comment by paperbag** [comment]
@panzer1313208
他@p3rcya 好像是某组织former co-founder。

**Comment by panzer1313208** [comment]
什么鬼

**Comment by p3rcya** [comment]
防止查水表，我这个帖删了

**Comment by panzer1313208** [comment]
@p3rcya 好的
