### ISSUE TITLE
出售一个坑，6元一月、月付或季度付都行。

### ISSUE THREAD

**Issue by wufeng87** [getlantern/forum#4221]
出售一个坑，6元一月、月付或季度付都行。
有兴趣的联系。

**Comment by zilanghuo** [comment]
联系方式贴出来

**Comment by DannDanny423** [comment]
联系方式？

**Comment by wufeng87** [comment]
还有一个坑 ，支付宝63528605@qq.com

**Comment by zilanghuo** [comment]
你好，我是直接打钱到这个支付宝？可以先月付试下吗？




发自网易邮箱大师


在2017年9月25日 09:05，wufeng87<notifications@github.com> 写道：

还有一个坑 ，支付宝63528605@qq.com

**Comment by wufeng87** [comment]
有了 谢谢大家，你们自己再去组队吧
