### ISSUE TITLE
win10把lantern休眠后edge被墙未唤醒的问题

### ISSUE THREAD

**Issue by NAVrasZ** [getlantern/forum#423]
![2](https://cloud.githubusercontent.com/assets/20354364/16696564/1fd2b9c2-4578-11e6-9960-bf8f453c0c38.PNG)

**Comment by NAVrasZ** [comment]
新版的lantern对Edge的兼容仍不是很好，如在win10默认设置内设edge默认，刚开始没问题，后来再开ui界面则会无法打开然后被运营商劫持到无法显示网页的界面，ie则不会
另一个问题则是如我使用默认ie，运行lantern后用edge上网，隔一段时间就要重开一次lantern的ui界面否则google都开不了，同样用ie上网也不会
反馈一个bug，反复运行退出lantern三四次最终lantern会一启动就自动退出，ui界面显示lantern未运行

**Comment by NAVrasZ** [comment]
[lantern.txt](https://github.com/getlantern/forum/files/354834/lantern.txt)

**Comment by NAVrasZ** [comment]
安卓设备测试相同，google和getlantern上不去，估计是服务器仍然被墙，我继续等下一个版本~
下拉vpn管理里有一个配置键，点了以后不会弹出lantern，shadowsocks可以

**Comment by p3rcya** [comment]
@NAVrasZ 
1.流量0MB，你是不是上次用完了？ 这个和硬件绑定的，升级后流量不会重新恢复的。
2.用Edge被劫持的截图请给个
3.用Edge打不开的截图请给我个。
4.一般用户不会这样吧。所以暂时不解决

**Comment by NAVrasZ** [comment]
@p3rcya 额，这个月基本没用过什么，应该没到800M
虽然显示是0但实际上还有，速度也未限速
![1](https://cloud.githubusercontent.com/assets/20354364/16705441/9e3604e2-45bc-11e6-89d3-a01a3779a62e.PNG)

**Comment by p3rcya** [comment]
@NAVrasZ 现在专业版还未正式发布，所以不想把免费的用户限速了

**Comment by NAVrasZ** [comment]
@p3rcya 噢原来如此.. 
![23](https://cloud.githubusercontent.com/assets/20354364/16705451/e9770794-45bc-11e6-8047-dd11f213b89f.PNG)
这种是蓝灯仍在运行，但浏览器开了一段时间后UI会打不开的情形，地址已被移动劫持，但因为在墙外全局所以劫持页面连不上

**Comment by p3rcya** [comment]
嗯，这个貌似是DNS戒指。 我们调查下

**Comment by p3rcya** [comment]
我估计你所有的问题都是DNS劫持造成的，你先换个DNS吧。

**Comment by NAVrasZ** [comment]
@p3rcya 我换了2个被墙的DNS，UI界面能正常打开，google打不开
换了2个未被墙的DNS，UI正常打开，google打开（但是不确定是lantern还是DNS，有方法鉴别吗？）

**Comment by NAVrasZ** [comment]
@p3rcya 发现今天开机lantern貌似显示我流量是满的，然而数字还是0
（流量槽昨天是空的）
![888](https://cloud.githubusercontent.com/assets/20354364/16705558/e699f132-45bf-11e6-8689-f14c6eecc887.PNG)

**Comment by p3rcya** [comment]
我估计是DNS流量没有被代理

**Comment by NAVrasZ** [comment]
@p3rcya OK，刚判断出是走的lantern 2233
![666](https://cloud.githubusercontent.com/assets/20354364/16705577/6824c3d0-45c0-11e6-96cd-981c8e88ee6d.PNG)
另外换了DNS这速度惊喜啊
![999](https://cloud.githubusercontent.com/assets/20354364/16705578/752db744-45c0-11e6-9457-30569f6dce46.PNG)
网速超一倍（传说中的vpn网速加成？）

**Comment by p3rcya** [comment]
那就是你DNS的问题

**Comment by p3rcya** [comment]
不过这个我们也会想办法解决

**Comment by NAVrasZ** [comment]
@p3rcya 多谢，话说默认用运营商DNS被坑的人估计蛮多...
另外看网上说用ss要清除CNNIC证书，lantern需要吗？

**Comment by p3rcya** [comment]
对于蓝灯无所谓。不过对于自己上网安全，有能力清除就清除吧

**Comment by NAVrasZ** [comment]
好的

**Comment by NAVrasZ** [comment]
@p3rcya 刚才使用发现edge+lantern的方式还是不稳定，隔一段时间没翻的需唤醒一次，不唤醒的话打开第一个要翻墙的网站加载很慢有时仍http500，ie则很快貌似开翻墙网站被检测block后就立即唤醒了（测试google、facebook、youtube）

**Comment by p3rcya** [comment]
@NAVrasZ 那你先用IE吧，用Edge的人不多，所以不优先处理，不好意思

**Comment by NAVrasZ** [comment]
好的

**Comment by NAVrasZ** [comment]
@p3rcya 我的锅，，刚才把DNS换成100.000.000.000和200（这两个应该没有吧？），谷歌和facebook能上。我想之前的问题可能是因为查DNS和换DNS没用到翻墙（所以lantern下线了？），第二次访问google能上是因为第一次的请求唤醒了lantern（？）
lantern休眠和block无法及时代理导致劫持估计是win10和edge的幺蛾子，我还是改回ie吧..

**Comment by NAVrasZ** [comment]
总结一下就是DNS被劫持的换DNS，访问谷歌不稳定的把edge换ie
edge不稳定表现在lantern被win10休眠时：网页开新标签有时不走lantern(谷歌搜索结果url跳转走了hk、开谷歌http500)，本标签的直接跳转能正常唤醒lantern
查了下win10的确会自动停用未在工作的应用（甚至在内存满了或时间过长会把最小化的edge都关了）但不会损失内容，且可随时唤醒
但是youtube网页我怎么花式打开都可以，感觉好混乱...也可能是我系统问题，所以把问题关了免得误导别人（系统镜像在msdn itellyou下载从预装win7升到10，edge一打开默认搜索就是百度，且想要切换谷歌总是超时失败，切bing可以）
