### ISSUE TITLE
mac客户端打开蓝灯后无法打开某些网站

### ISSUE THREAD

**Issue by chenzz** [getlantern/forum#4240]
另外mac客户端也有问题，连上lantern后打开部分网站无法打开，
如打开以下页面
`http://pingtcss.qq.com/pingd?dm=ip138.com&pvi=8186113024&si=s3146206208&url=/&arg=&ty=1&rdm=&rurl=&rarg=&adt=&r2=36241650&r3=-1&r4=1&fl=27.0&scr=1600x900&scl=24-bit&lg=en-us&jv=&tz=-8&ct=&ext=adid=&pf=&random=1506320100199`

![image](https://user-images.githubusercontent.com/5676311/30794729-7dcf366c-a18f-11e7-825e-73388c7d40dc.png)

@orbancanon

**Comment by orbancanon** [comment]
@chenzz 这个也请在Lantern界面点一下报告问题，以便我们查看日志。

**Comment by chenzz** [comment]
@orbancanon 
已报告，报告内容为 #4240

**Comment by orbancanon** [comment]
看到了，谢谢！

**Comment by orbancanon** [comment]
这个问题也跟你公网是香港IP地址有关。绕的圈儿太多了

**Comment by chenzz** [comment]
mac的问题我回家再『报告问题』一下好了……
不过按道理部分网络走香港代理也不应该出问题才是，毕竟我不开蓝灯网站能打开

**Comment by orbancanon** [comment]
是这样的。不开蓝灯，从你的电脑到香港，再到最终网站。开了蓝灯，因为你在香港，所以不会直连，自动检测又发现这个网站迟迟没有返回数据，疑似被墙，所以就通过蓝灯服务器走了。这样不仅多了一跳，而且不同海外线路访问国内的速度千差万别，累积下来最终超时。

**Comment by chenzz** [comment]
@orbancanon 
OK，mac的问题我找个不走代理的wifi连上再『报告问题』一下好了

**Comment by orbancanon** [comment]
好的

**Comment by chenzz** [comment]
mac 客户端升级到4.1.0-beta8后问题已消失
Close
