### ISSUE TITLE
每月的免费流量也太少了吧

### ISSUE THREAD

**Issue by drgf** [getlantern/forum#427]
才800MB，好歹凑个整到1G吧，而且用完后的限速是20KB/S，这个速度太低了，不看视频浏览网页也不够，最起码200KB/S以上吧，相当于2M以下的速度，要求不过分吧
另外问下我还没用过3.0.这个每月的流量是注册了帐号，从帐号里扣的，还是会记录电脑的MAC地址或是其他什么的，让一台电脑只能用一个帐号

**Comment by p3rcya** [comment]
账号加硬件。以后有一系列反作弊措施，所以最好不要作死， 呵呵。20KB看网页没有任何问题

**Comment by zhouzhiwen2000** [comment]
很简单，linux下改/dev/sda的输出（重编译内核，改驱动（只改输出函数，改为随机输出uuid）），每一次开机换一个uuid，网卡mac就更容易换了，内核驱动再改下，把对主板信息访问定向到initramfs的文件里，id每次开机一换。ip重新拨号就会更换。搞定！

**Comment by p3rcya** [comment]
@zhouzhiwen2000 请你自重。若开发这种版本，已经违反了我们的开源政策。下次在论坛上讨论这种问题，我就只能ban了

**Comment by hnjdy** [comment]
@p3rcya  tor的网速都没有那么慢，20KB/S比手机2G的网速都慢了，如果有很多图的话，可能加载都超时，会加载不出来了。

**Comment by p3rcya** [comment]
@hnjdy 20KB是没个链接的速度。浏览器加载图片很多情况下是并联的，所以多图没关系

**Comment by zhouzhiwen2000** [comment]
@p3rcya 我并没有改动任何lantern源代码，linux内核的GPL协议允许我自由更改linux内核。我改的是内核（linux内核),并且我不打算进行商业活动，并没有违反GPL协议。我也有权发布linux内核（我将开放源代码）。

**Comment by zhouzhiwen2000** [comment]
@p3rcya 我并没违反你们的开源政策（我连lantern源码都没粘到）

**Comment by zhouzhiwen2000** [comment]
@p3rcya so，bite me！

**Comment by zhouzhiwen2000** [comment]
@p3rcya 请仔细阅读GPL协议，谢谢

**Comment by zhouzhiwen2000** [comment]
@p3rcya  这同时也可以被认为是更保密，更安全的linux内核。

**Comment by zhouzhiwen2000** [comment]
我将在linux内核与achi间加入转接程序，可以保护计算机硬件免于恶意代码损害。

**Comment by zhouzhiwen2000** [comment]
@p3rcya 应该还可以做一个用户端，用户可手动更改各种id，甚至主板型号信息

**Comment by p3rcya** [comment]
@zhouzhiwen2000 我说的是“**若**开发这种版本，已经违反了我们的开源政策。” 使用软件欺骗使用蓝灯是违反软件使用协议的。你可以自己用我们的源码编译一个版本，自己提供服务器，供大家无限制的使用，我们没有意见。使用我们的服务器和和名称来发表是违反license的。请看

   6. Trademarks. This License does not grant permission to use the trade
      names, trademarks, service marks, or product names of the Licensor,
      except as required for reasonable and customary use in describing the
      origin of the Work and reproducing the content of the NOTICE file.
https://github.com/getlantern/lantern/blob/devel/LICENSE

**Comment by p3rcya** [comment]
如果你重新编译一个随机改变Mac的linux版本，我们没有任何意见。但是这个也没有用。 但若你将作弊系统和蓝灯捆绑在一起发布，是违反版权协议的。而且我们反作弊绝对会K了所有这种用户

**Comment by zhouzhiwen2000** [comment]
不仅仅是mac，还包括硬盘id（我没法真正更改，但我可以模拟假数据）。主板信息（同上）。我将用软件接管acpi，再传给linux内核。

**Comment by p3rcya** [comment]
你这样搞被GFW看到了，可能会导致所有免费用户都没的用。到时候所有用户都被你这要搞了逼着购买专业版，又认为是蓝灯官方故意的。

**Comment by p3rcya** [comment]
@zhouzhiwen2000 其实我很喜欢你这种钻空子的精神。我如果个人不是这样会开发蓝灯么？ 翻墙软件不就是钻空子的么？ 问题是你这样弄，可能会造成所有人都没的玩。所以说我们必须遏制。

**Comment by zhouzhiwen2000** [comment]
你们不能开发ipv6版本吗？ipv6 ip很多，gfw在此方面技术也不成熟。

**Comment by p3rcya** [comment]
@zhouzhiwen2000 IPV6的版本ISP不提供IPV4你不能直接连接啊。

**Comment by zhouzhiwen2000** [comment]
教育网有IPV6

**Comment by p3rcya** [comment]
大部分用户没有。所以暂时不考虑了。

On Sunday, July 10, 2016, zhouzhiwen2000 <notifications@github.com> wrote:

> 教育网有IPV6
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/getlantern/forum/issues/427#issuecomment-231577435>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHjwqd9IqYIw1i8HO4eGfuGS5Ol8hSAFks5qUK5mgaJpZM4JIffH>
> .
>


--

**Comment by zhouzhiwen2000** [comment]
好吧

**Comment by TorosFanny** [comment]
目测ArchLinux版本很特别，为什么我的版本号是2.2.5，完全没提示过帐号的问题，速度也很快？

**Comment by weakish** [comment]
@zhouzhiwen2000 为何你的发言都看不到。

另外免费版反作弊是如何实现的？

所谓的「账号加硬件」并没有什么用，因为客户端可以随便魔改，欺骗服务器。

服务器端的话，本来通过客户端的的IP限制是很好的手段，可惜的是现在大量ISP不提供IP，都是NAT转发。通过数据分析可以一定程度上识别作弊，毕竟作弊导致的流量增加和由于某某人在小范围内大量推广增加用户导致的流量增加是不一样的。但是一般作弊也是小规模作弊的，不会是挂lantern 24x7高速下载Youtube视频之类，所以仍然不容易识别。另外数据分析要求记录、分析大量的数据，编程、存储、计算成本可能远大反作弊节省的流量成本。

**Comment by p3rcya** [comment]
专业版使用的服务器和免费版是不同的。

**Comment by weakish** [comment]
@p3rcya 我说的是免费版反作弊，根本不涉及专业版。
