### ISSUE TITLE
蓝灯的管理员呢

### ISSUE THREAD

**Issue by ssralvin** [getlantern/forum#4304]
发邮件不回，论坛发贴也没人管
是在搞笑吗？我们买，你卖，这就是买卖
做不到宣扬的那么好的技术支持就别他妈吃这碗饭。
口口声声说别人骗钱跑路，在你这儿要求退钱也一样找不到人

**Comment by yyqxjwxy** [comment]
真的是

**Comment by KevinWangWLF** [comment]
lantern的服务团队简直一团糟! 出了问题只知道找理由, 把问题丢出去,  
从来都不曾自我检讨, 也不针对问题采取实质性的措施, 没一点服务意识! 
软件后台的报告问题功能, 发出去从来不见回复, 好像打了水漂.
在论坛提问题, 管理员基本不理会, 如果问题实在太严重, 搞得论坛都炸开了锅, 眼看压不住了, 就用一个理由来搪塞.
还有管理员发的帖子都是无休止的照着模板copy! 不管是软体更新, 还是回复客户的问题, 都是一样的!
客户提出的问题也不改善, 比如要求提供软体更新日志, 管理员看了当没看见! 态度简直糟透了!

**Comment by panhaku** [comment]
真的很气炸，这几天才买了一年！

lantern贬低同行的口号倒是喊得很大声，出了问题，嚣张的气焰瞬间自灭！

任何翻墙软件能否做好售后服务，真的只能靠「商家诚信」了，倒霉的永远是客户（投诉无门）！

**Comment by wasd8456** [comment]
最近两天突然慢了，油管只能看144P模式的视频，试问这种速度你们会损失多少客户，不管是哪方面的原因，你们发现问题解决问题的速度真不行，墙高一尺道高一长，我一直相信，除非没有互联网，否则翻墙软件不会消失，而会越来越好，竞争力大的情况下更要做好口碑，而你们的服务态度确实太差

**Comment by 123321JOJO** [comment]
是的，就是骗子，没什么好解释的，气死我了。
