### ISSUE TITLE
退钱！退钱！

### ISSUE THREAD

**Issue by yyqxjwxy** [getlantern/forum#4308]
请在发帖前先按照蓝灯无法使用的解决办法 https://github.com/getlantern/forum/issues/1902 自行解决。自行解决问题通常只需要几十分钟。管理员调查解决问题需要几天至几周。请立即访问https://github.com/getlantern/forum/issues/1902 瞬间解决98%的问题

为了能在最快的时间内解决大家使用蓝灯遇到的问题，请各位用户严格按照发帖格式提交问题。

## 发帖格式
遇到的问题：请详细描述遇到的问题。如果描述不仔细，将无法调查

蓝灯专业版账号Email:  请提供登陆蓝灯专业版的email，免费版不提供技术支持。

应用内报告问题的时间:  请根据 https://github.com/getlantern/forum/issues/1840 在应用内上报问题，请填写专业版的email。请在帖子里注明报告的时间。

截图: 请提供有关问题的截图。 请把图片拖拽到这里。

----
请不要发只有邀请码没有其他内容的帖子,违反者将扣除所有赠送时间。具体见 https://github.com/getlantern/forum/issues/3773

**Comment by yyqxjwxy** [comment]
不给解决就退钱！

**Comment by beboyss** [comment]
可惜他们不退

**Comment by yyqxjwxy** [comment]
妈的几天了，连个官方公告也没有

**Comment by Ieyasu1543** [comment]
@yyqxjwxy 他们不觉得自己服务器出了问题

**Comment by beboyss** [comment]
我认为不是身么封端口或者海底电缆的问题，就是墙升级了，蓝灯的流量可以被检查出来，被限制了。不过以前说好的收费后抗打击能力所谓的提高也没体现出来】

**Comment by Ieyasu1543** [comment]
不能解决就当Pro版费用喂狗了呗

**Comment by zcy110120** [comment]
赞同墙升级的说法，因为这几天纽约锅报尿的事情，不希望被看到

**Comment by anticpc** [comment]
这几天爆料什么了?

**Comment by yyqxjwxy** [comment]
不解决就退钱，把整个论坛页面刷屏

**Comment by chuweitao** [comment]
刷频你敢试试，无警告直接封号，你信不信
