### ISSUE TITLE
大家务必看下此贴，我们需要做一些准备了。

### ISSUE THREAD

**Issue by ssralvin** [getlantern/forum#4313]
我先说下我个人情况。我个人留有一套备用上网的就是SS，有流量限制，但无使用期限限制。购入蓝灯主要是用电脑看视频什么的，没流量限制。
蓝灯现在速度很慢，跟免费版有一拼，所以我刚才试了下自己的备选方案，打开油管1080P没任何问题。而且我特意用了稍远一些的新加坡。
所以关于一些客观原因导致蓝灯速度慢可能并不是主要的，问题根源可能还是蓝灯本身。
在购入时，蓝灯闪亮的宣传口号在事到临头时显得那么具有虚假宣传的味道。
未来可能只有4条路：
1、蓝灯恢复，这样大家皆大欢喜。
2、无论恢复与否，管理员出现了，此种情况我相信很多人依然会坚持要退钱，所以希望大家能够互帮互助，到时候通过@emai，互相通知一下。
3、不恢复、管理员跑路，这种情况比较糟糕，但如果还可以使用，就平常翻墙搜个东西，看个新闻啥的。凑合着用。
4、蓝灯未来忽然某一时刻彻底无法使用，大家就当花钱买个教训。因为他们用的服务器不知道是月租还是年租，人如果跑了，不续费了，那服务器到日子就OVER也正常

**Comment by YourMomHasATinyDick** [comment]
1. 有可能
2. 退钱可能性为零。
3、4. 某一天跑路是必然的，互联网企业倒闭太频繁。现在管理员也形同虚设

**Comment by anticpc** [comment]
你们仿佛用到了假[蓝灯](https://getlantern.org/)

**Comment by Ieyasu1543** [comment]
comment管理员肯定都会看到的，但是会做选择性忽略，如果知道问题地解决超出自己能力范围之外，你会做出任何承诺吗？所以想要有正面回应是不太现实的，只能祈祷某一天连接速度会恢复，当然也要做好“这钱拿去喂狗了”的心理准备

**Comment by yyqxjwxy** [comment]
就是ss没有任何问题

**Comment by zcy110120** [comment]
墙这几天修高了，而一个公司对付国家力量显然是没有这么快速的应对办法，前几天看Tube还说要开会了要加网络大控制力度，没想到就这么快，加上老锅一直在纽约发一些敏感的视频，所以估计这段时间是没法解决了

**Comment by yyqxjwxy** [comment]
@zcy110120 那为什么我的ss服务一点问题都没有

**Comment by zcy110120** [comment]
@yyqxjwxy  那就不知道了  也可能有疏漏吧  反正我是中招，可能还有电信 移动 联通之分，我3台电脑都是电信的网，那个应该是管理最强的，刚才换了下手机授权，貌似看下推的速度还可以，我还等着看报料呢

**Comment by gawain-id** [comment]
某人一报~料，蓝灯 不是打不开，就是卡的不行。前段时间还说封锁对蓝灯没有任何影响。摊手!

**Comment by beboyss** [comment]
建议还没入坑的人暂时不要买了

**Comment by balusite** [comment]
现在要买蓝的的还是算了吧。 ss一个月一买都比这个合适。而且还不怕跑路。速度还稳定。线路还能自己选。   蓝灯不做出改变 只能被淘汰。

**Comment by taolijiavip** [comment]
我就是前天买的2年专业版啊，我真的心碎了

**Comment by StevenZhangg** [comment]
刚刚买的一年，后悔没有早看到论坛
