### ISSUE TITLE
蓝灯专业版速度慢的问题正在解决

### ISSUE THREAD

**Issue by angelwithout** [getlantern/forum#4319]
因为众所周知的原因，部分蓝灯专业版用户遇到速度慢的问题。此问题下周内会解决，请大家稍安勿躁。

**Comment by beboyss** [comment]
支持，蓝灯第一时间发声很重要，大家不是不给蓝灯时间，而是不能接受被无视！！！

**Comment by kuseqingchun** [comment]
输入我的邀请码 LB47P4 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by kuseqingchun** [comment]
希望蓝灯越来越好~

**Comment by hadow** [comment]
依然支持lantern,希望尽快解决

**Comment by moonrhino** [comment]
蓝灯是最快的vpn，希望尽快解决问题

**Comment by zcy110120** [comment]
希望尽快啊  不然时间和金钱都在流逝

**Comment by takuya1232** [comment]
支持  希望尽早解决  只不过这几天的钱 算是感觉白花了

**Comment by wondrous02** [comment]
支持lantern团队,希望能尽快解决。

**Comment by tunnelode** [comment]
用"其他不只一种"翻墙工具都是高速，大约3800Kbps/s. 请蓝灯尽快解决。

**Comment by yyqxjwxy** [comment]
哎呦我的天官方终于发话了。

**Comment by adskyfly** [comment]
大家还是多留几条路吧

**Comment by zz89419318** [comment]
合租群597065668，有专业的售后不用跑路，走微店http://weidian.com/i/2162502484?ifr=itemdetail&wfr=c，可以加我qq1047757797咨询

**Comment by mcyou** [comment]
确实慢的不行了，几乎用不了了，希望赶快处理，谢谢

**Comment by wrbking** [comment]
今天早上看youtube恢复正常（4k流畅播放），现在又变成144p

**Comment by zhaimen1008** [comment]
还好不是我一个人出现这样的问题 我就安心了

**Comment by wgjbrian** [comment]
希望尽快解决吧

**Comment by chuweitao** [comment]
如果你早点出这个公告，我也不用浪费钱买了一个月别的VPN

**Comment by YourMomHasATinyDick** [comment]
终于出现了。。下周之内。。

**Comment by szwx1314** [comment]
最近网速慢的要死，刷推只有100KB/S，还不如以前用免费的，希望尽快解决吧

**Comment by qcind** [comment]
感恩：lantern support team.

**Comment by yizeliang** [comment]
特别慢,希望能增加节点选择,香港的特别快,日本的特别慢

**Comment by fandeus** [comment]
的确速度慢得不行，现在144，240都很卡。

**Comment by moonrhino** [comment]
感觉速度回来啦

**Comment by TomatosX** [comment]
香港的节点出问题了么，之前我这里自动选择HK，现在是JP了，速度相当慢。

**Comment by retsyo** [comment]
前几天还有800kps~1Mps速度，现在只有80kps。
希望尽快得到解决吧。
谢谢啊。

**Comment by rocknrollfly** [comment]
我这里一直很快很流畅，油管1080P毫无压力。请大家相信蓝灯不可能出现跑路等问题，蓝灯是有可靠实力和背景的公司，遇到问题耐心等待官方解决
另外请管理员在论坛帖子页面发布4.1.0正式版公告，此版本未像从前一样发布公告，请像以前那样每个新正式版都发布公告
——————————————————————————————
输入我的邀请码 MT8B94 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by taolijiavip** [comment]
我真的是日了狗，刚买专业版第二天就出现这种问题，各种慢的要死，还不如mac上面的免费FreeVPN速度快，真的是醉了，这个钱花的真心不值

**Comment by xebecy** [comment]
会继续支持蓝灯加油

**Comment by justinpp** [comment]
放心吧 我一个代理手里还有激活码呢你看我慌吗 蓝灯稳得一匹你们不知道 去年不就来了一波不立马解决了？ 需要专业版的联系我 1年只要85 有意加q 1262200959 可走咸鱼

**Comment by onlyatryyouknow** [comment]
好好好……原来不是我错觉，现在刷汤有些图片要好久才能加载出来……

**Comment by moonrhino** [comment]
现在速度恢复了 1080p

**Comment by moonrhino** [comment]
希望保持，

**Comment by moonrhino** [comment]
怎么又开始卡了，难道说刚才小墙去吃饭了？

**Comment by StevenZhangg** [comment]
我刚买的一年的，发现卡的不行，完全没有宣传的流畅感，还以为被骗了，希望早点解决。

**Comment by bloodywk** [comment]
<img width="895" alt="2017-10-01 01 21 52" src="https://user-images.githubusercontent.com/17928924/31047975-05a9c4d8-a647-11e7-91b6-687b91af523e.png">
终于可以看4k视频了，这样才对嘛。之前200k的带宽简直令人发指，希望hold住。

**Comment by bloodywk** [comment]
<img width="912" alt="2017-10-01 01 32 47" src="https://user-images.githubusercontent.com/17928924/31048075-85e961c0-a648-11e7-8198-f5ce4d7ae959.png">
原来是开了另一vpn才这么快。不过蓝灯速度已经比之前好了很多，希望尽快解决问题。

**Comment by bloodywk** [comment]
<img width="747" alt="2017-10-01 01 36 21" src="https://user-images.githubusercontent.com/17928924/31048095-f5c76276-a648-11e7-9e1d-4f073229dd51.png">
光速打脸，当我没说。

**Comment by xjb258** [comment]
2017年10月1日，最新3个月邀请码：**YXMTU6D**

**Comment by shisanlanlan** [comment]
今晚速度回复正常了，前几天真是卡的没话说了，没办法只好用了几天自由门。

**Comment by ssynhtn** [comment]
Android版不管怎么设置都是全局走蓝灯的bug也解决一下吧

**Comment by PKingHot** [comment]
我这里还是很慢啊，一直给我选择日本的服务器，既然日本的有问题，你们能不能定向到别的服务器啊

**Comment by ronger666** [comment]
今天入了专业版 速度只能看360p 还会卡， 还不如我以前的15块的VPN快，我只用了一天，我要退钱！！！

**Comment by youzhicheng** [comment]
支持蓝灯，刚充了两年的钱。加油啊～！
国内的腾讯视频JB能搞出一分钟的广告（还不能跳过，有的是2分钟），有思想的原创视频基本没有。新闻APP更别提了，我都把手机上的网易新闻和头条都删了，没法看了都，全特么是广告软文，没办法下了个人民日报app,凑合着看，每次看完人民日报的新闻都让我更加热爱自己的祖国了，感动得要哭，这让我想起了朝鲜人民。人民日报里的新闻还是那些新闻，起码没广告。指望着到youtube上学点东西呢，那里确实有干货能学到东西。

**Comment by angelwithout** [comment]
蓝灯专业版速度已经恢复 https://github.com/getlantern/forum/issues/4356

**Comment by ashuang001** [comment]
并没有恢复啊.我这里恰恰相反 , 前几天 都不卡,进天一开始就卡得不行.服务器是日本的.基本不能正常观看youtube视频,1段10分钟的vlog要缓存40分钟 .
请尽快解决 啊.

**Comment by ekko123** [comment]
速度慢了好多啊 只能看1080 看4K很卡..
一9大前可达到4W+Kbps， 现在只有4K+
