### ISSUE TITLE
0.蓝灯/自由门 ?lantern/轮子功? 九头蛇？神盾局？

### ISSUE THREAD

**Issue by nijia909** [getlantern/forum#4323]
# 1.管理员？发布者?轮子?
![](https://extraimage.net/images/2017/09/30/307ff193ce6125fc811ba8461d21fbf1.jpg)
![](https://extraimage.net/images/2017/09/30/6fe18bf079bb6612a306e0c4bfb3f276.jpg)
![](https://extraimage.net/images/2017/09/30/61a4e4d22c9d7c9fb2c7a4d4c8fe5721.jpg)
![](https://extraimage.net/images/2017/09/30/f3eedbfae997ff95ea486410fb6e6c17.jpg)

# 2.短信权限？
![](https://extraimage.net/images/2017/09/30/a90488261cb59abfd514ec89bfac4d08.png)
![](https://extraimage.net/images/2017/09/30/95410bb6ee7d44abe525661c50e35f95.png)
![](https://extraimage.net/images/2017/09/30/f5949249409af915f1cba8ee17a0e4c6.png)
![](https://extraimage.net/images/2017/09/30/cfdbd27298ea5545fa45aa2713c4e629.png)
![](https://extraimage.net/images/2017/09/30/f784e9ed7762094e48a79a02ebb2f789.png)

**Comment by nijia909** [comment]
# 猜想
![](https://extraimage.net/images/2017/09/30/93684b58906d187d7c7d3f594d91e778.png)
![](https://camo.githubusercontent.com/388e8891faaba5e9c2e22b54d7148fb5c1ce0b15/68747470733a2f2f6578747261696d6167652e6e65742f696d616765732f323031372f30392f32382f31366332356230633037623736376236343139656434313232373831613136652e6a7067)

**Comment by beboyss** [comment]
太高深，没看懂

**Comment by chuweitao** [comment]
没看懂，但是你这个帖子估计是保不住了

**Comment by beboyss** [comment]
你都没看懂怎么知道保不住，不要对自己不了解的事情发表评论

**Comment by sun1a2b3c** [comment]
LZ的版本太老了吧？

**Comment by beboyss** [comment]
lantern安卓的权限确实很多不应该有，但是手机还可以提示，还可以屏蔽，谁知道电脑的版本又获取了什么权限，干了什么事情呢

**Comment by chengziqing** [comment]
@nijia909 蓝点确实有点向邪恶发展的趋势

**Comment by tbirder** [comment]
楼主，你可能也不知道，github里面，删除账户后，所有的数据都会合并到ghost这个系统账户里作为数据保存下来。

换句话说，你把自己的账户删了，你的这个帖子也会变成ghost.

楼主，想象力太丰富了，很不好。。。

**Comment by rocknrollfly** [comment]
同意 @tbirder 
请楼主或管理员关闭这个帖子

**Comment by tbirder** [comment]
@rocknrollfly    我删了，我都懒得再回复这样的帖子了。

**Comment by YourMomHasATinyDick** [comment]
ghost是注销账号的所有名称，【已注销用户】当然啥都有啦，楼主阴谋论不要那么明显好吗@nijia909
烦请管理员关闭帖子@angelwithout

**Comment by sun1a2b3c** [comment]
LZ是十九大前来维稳的吗？
