### ISSUE TITLE
管理员，你关我2个帖子可以，你能不能顺手把你日本的服务器也先关了

### ISSUE THREAD

**Issue by ssralvin** [getlantern/forum#4348]
你认为我的帖子对你的生意有负能量，OK，你的想法自由。你在你的地盘关闭我的帖子，OK，你的权力。你发一个一周内的公告认为可以让我们闭嘴，OK，你的单纯。
现在看个youtube 144P，日本服务器慢得不要不要的，你为何不先关闭日本呢？
你肯定会说是某些原因致使日本服务器慢，而非服务器本身慢，你所谓的众所周知的原因恰恰是你在宣传中的制胜法宝，对吧。
你想解决问题，很好啊，100%支持，但是解决问题的方法有一种叫紧急避险，你不应该在我们付费后告诉我们你会解决，稍安勿躁。然后除了让我们忍受却没有任何的应急计划。
你在互联网上可以随心所欲的宣传，但是如果现实打交道千万别做现在这种行为，因为很容易丧失别人对你们的信任，遇到脾气爆的可能还会挨揍，算是个忠告吧。
回归到主题：1个星期内解决，我们不接受也要接受，但你现在能不能采取一种应急措施先缓和一下速度慢的问题？

**Comment by beboyss** [comment]
防火墙找到日本服务器ip，屏蔽掉，然后就换服务器了
