### ISSUE TITLE
蓝灯专业版速度已经恢复

### ISSUE THREAD

**Issue by angelwithout** [getlantern/forum#4356]
蓝灯专业版速度已经恢复，感谢大家的耐心等待！

若还是遇到蓝灯专业版速度慢的问题，请在先按照蓝灯无法使用的解决办法 https://github.com/getlantern/forum/issues/1902 自行解决。若还是无法解决，请开新帖按照发帖格式报告。

**Comment by justinpp** [comment]
蓝灯的售后保障向来让人满意，大家不要一有问题就担心跑路。蓝灯是目前最靠谱 最方便快速的软件！相信蓝灯选择蓝灯。我是蓝灯代理商，有需要专业版可以联系我，单设备专业版1年85。激活码1年190 2年300，已有50多位买家，可走咸鱼，信用评价可查。有意联系q：1262200959

**Comment by GreatRain** [comment]
还是非常慢，没有任何改善。谢谢

**Comment by lanyun1973** [comment]
已测，jp server依然很慢，无非就是youtube缓存十几秒后，发现连不了，就自动跳到新加坡的服务器，这就叫你们的所谓解决办法，忽悠小白还差不多！

**Comment by wrbking** [comment]
普遍情况是 晚上十点以后速度会好一些，到了早上youtube就是144p/240p之类的。

没有改善。谢谢。

**Comment by lanyun1973** [comment]
已测，jp server依然很慢，无非就是youtube缓存十几秒后，发现连不了，就自动跳到荷兰的服务器，这就叫你们的所谓解决办法，忽悠小白还差不多！

**Comment by lanyun1973** [comment]
已测，jp server依然很慢，无非就是youtube缓存十几秒后，发现连不了，就自动跳到荷兰的服务器，这就叫你们的所谓解决办法，现目前只有荷兰NL和美国US可以正常使用

![01](https://user-images.githubusercontent.com/32354497/31104997-54b994f4-a813-11e7-88da-b72b866989da.JPG)

**Comment by NeverVanish** [comment]
昨晚10点至12点这段时间使用的时候速度还是可以的，youtube上能看720P，但是今天早上再使用时又恢复到前两天只能看144p，240p的速度了。

**Comment by IAMZHY** [comment]
还是不稳定，尽快恢复到之前的状态吧，现在这时好时坏用起来真的…………

**Comment by GreatRain** [comment]
没有任何改善，
<img width="1680" alt="2017-10-03 8 53 40" src="https://user-images.githubusercontent.com/22108226/31105700-a2d6cd32-a818-11e7-80bf-91806cfb4d17.png">

**Comment by GreatRain** [comment]
应该是蓝灯关掉了一些服务器

**Comment by kuseqingchun** [comment]
**输入我的邀请码 LB47P4 来获得三个月的蓝灯专业版！**立即下载 https://github.com/getlantern/forum

**Comment by kuseqingchun** [comment]
速度是恢复了一些，但是不稳定。时好时坏的。以后肯定会解决的。

**Comment by leolupei** [comment]
https://github.com/getlantern/forum/issues/4355

请帮助解决一下什么问题，感觉被欺骗

**Comment by shisanlanlan** [comment]
同为日本服务器，速度很快。
![fireshot capture 009 - _ - http___localhost_59536_](https://user-images.githubusercontent.com/32420204/31108611-f660424e-a82c-11e7-94ff-f911d1050a7d.png)
![fireshot capture 010 - 4 zion national park autumn - 4k nature d_ - https___www youtube com_watch](https://user-images.githubusercontent.com/32420204/31108612-f6673e00-a82c-11e7-9349-9d7aae09be4c.png)

**Comment by ronger666** [comment]
![360 -48837437](https://user-images.githubusercontent.com/32460901/31108595-e00dceda-a82c-11e7-9d13-a6d08d9a5214.jpg)
赶快退钱吧，这速度跟我说恢复了，你们跟骗子有什么区别？

**Comment by lanyun1973** [comment]
@shisanlanlan  哈哈，你的缓冲都黄成那样了还显摆，而且还掉帧，让你看看什么叫正常

![01](https://user-images.githubusercontent.com/32354497/31109667-df2cc6d6-a833-11e7-9e9c-4181d330260b.jpg)
![02](https://user-images.githubusercontent.com/32354497/31109668-e3913018-a833-11e7-9adc-ad1f84d33345.jpg)

**Comment by whatucamefor** [comment]
我这里确实恢复了，1080p无压力

**Comment by lyskr** [comment]
上海100M电信  还是卡爆

**Comment by wasd8456** [comment]
暂时恢复了，希望能够保持稳定

**Comment by lyskr** [comment]
![image](https://user-images.githubusercontent.com/32426587/31110358-0fcd02f6-a839-11e7-9409-318c1e917830.png)

**Comment by panhaku** [comment]
恢复了！1080P无压力！

**Comment by GreatRain** [comment]
真的越来越慢了，无法忍受了！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by Banana1130** [comment]
没有回复，卡的一比

**Comment by ashuang001** [comment]
还是很卡.连到日本就无法使用了.
成都电信用户.

**Comment by Banana1130** [comment]
原本4.0.1的时候，即使是日本IP，速度也很快，今天手贱升级到4.1.0，一下子变卡！根本不能看视频，找到以前4.0.1正式版的帖子，下载的还是4.1.0  什么情况？！速度问题希望能赶紧解决！

**Comment by wasd8456** [comment]
现在还是不稳定

**Comment by wasd8456** [comment]
依然很慢，下载速度更是慢的可怜

**Comment by yihengsir** [comment]
youtube就是看不了 facebook 和twitter上的视频都能看

**Comment by Naturaltits** [comment]
能说说是因为什么出问题了吗? 你们到底都做了什么?
就靠几个没脑子的水军说不卡 就代表恢复了?

**Comment by IAMZHY** [comment]
从早上看到这帖子到现在，试遍了移动联通电信的wifi 流量，就没流畅的看完过一个1080p的youtube视频，花了几百块买的的专业版，还没有免费的vpn速度快，真不知道速度恢复是从哪出来的

**Comment by Banana1130** [comment]
@angelwithout 速度卡的问题一点都没有解决，请不要欺骗大家！

**Comment by yihengsir** [comment]
Youtube 根本就看不了 你们这就是骗钱

**Comment by GreatRain** [comment]
再次发个截图，早晨已发了一个，不管怎样，都不应该升级越升越慢，这个说不通呀？也不应该这样吧！
![2017-10-03 9 02 03](https://user-images.githubusercontent.com/22108226/31126590-d5bc6bf6-a87e-11e7-8ea7-81d578ec80fa.png)


![2017-10-03 9 01 58](https://user-images.githubusercontent.com/22108226/31126528-aa455140-a87e-11e7-9b34-63664b7bf190.png)

**Comment by netljfwork** [comment]
网络供应商问题。。我这边挺好的，至少比以前好多了。。。
当然了我推荐蓝灯出一个专业操作版。专业版才能用，黑白名单，定点服务器，这样体验好多了，我肯定再给你们续两年。

**Comment by IAMZHY** [comment]
能不能把日本那条线路关了，有跟没有一样，卡的要死，打开蓝灯还默认这条线路，又没法手动切换，完全就是个摆设，让人连个其他地区的线路也行啊，死磕日本这条线了？

**Comment by Banana1130** [comment]
@IAMZHY 同意！

**Comment by bloodywk** [comment]
我这恢复了，而且是jp的服务器
<img width="913" alt="2017-10-04 01 58 41" src="https://user-images.githubusercontent.com/17928924/31140691-bf704d12-a8a7-11e7-8dc2-bc0fc0ef1862.png">

<img width="838" alt="2017-10-04 01 58 58" src="https://user-images.githubusercontent.com/17928924/31140695-c406be88-a8a7-11e7-8695-dd69112f2c2b.png">
北京联通

**Comment by bloodywk** [comment]
我是4.1.0版本
<img width="231" alt="2017-10-04 02 03 21" src="https://user-images.githubusercontent.com/17928924/31140837-45ef1fe4-a8a8-11e7-9e0c-aa6773572d4b.png">

**Comment by Banana1130** [comment]
并不算真正的恢复，只是晚上服务器用的人少了才快吧，还得看白天的速度！

**Comment by angelwithout** [comment]
请大家升级4.1.1 https://github.com/getlantern/forum/issues/4370

**Comment by williamddd** [comment]
国内的基本都被封杀了，就是存活的，也存在跑路风险，你还是直接买国外的吧
zhihu.page.tl
http://williamddd.doodlekit.com
https://diigo.com/0anh1v
