### ISSUE TITLE
蓝灯专业版1年85 有意联系 正规代理 可走咸鱼

### ISSUE THREAD

**Issue by justinpp** [getlantern/forum#4357]
蓝灯的售后保障向来让人满意，大家不要一有问题就担心跑路。蓝灯是目前最靠谱 最方便快速的软件！相信蓝灯选择蓝灯。我是蓝灯代理商，有需要专业版可以联系我，单设备专业版1年85。激活码1年190 2年300，已有50多位买家，可走咸鱼，信用评价可查。有意联系q：1262200959

**Comment by leolupei** [comment]
https://github.com/getlantern/forum/issues/4355

请帮助看一下什么问题，感觉被欺骗！
