### ISSUE TITLE
蓝灯彻底废了吗？

### ISSUE THREAD

**Issue by atlaski** [getlantern/forum#4385]
一连上蓝灯，所有网络连接都打不开了，连Google都打不开了。4.1.0和4.1.1都不行。是不是彻底报废了？

**Comment by myyyhugo** [comment]
还不如免费的好用，怕是正版vpn的受害者

**Comment by NovusLio** [comment]
这真是讽刺, 我昨天才买了一年.

**Comment by NovusLio** [comment]
我也只能呵呵,然后继续找VPN

**Comment by ronger666** [comment]
刚刚突然断开就一直连不上了！ 我也是服.

**Comment by Declarcall** [comment]
同，所有网站无法打开！

**Comment by atlaski** [comment]
我是能连上 但任何网页都打不开了

**Comment by a57620887** [comment]
对刚刚恢复没几天又开始不行了。。。管理员出来解释下

**Comment by leixiayang** [comment]
一样的，无法打开网页

**Comment by yansuysu** [comment]
杭州电信，专业版用户，刚刚开始已无法使用。

**Comment by Hurambar** [comment]
10分钟前断开  下载本论坛提供的最新Windows版本之后Windows Defender报毒  软件本体连同安装包一同删除 求尽快修复  珠海联通

**Comment by huangwen18** [comment]
刚刚买了一年的就无法使用了，这不是坑我们吗

**Comment by lvboy1** [comment]
我还以为就我一个，没想到广大同胞都一样

**Comment by Declarcall** [comment]
刚刚升级了一下 Lantern 4.1.1 (20170929.190044) 连webUI右下角的“已连接”都不显示。只显示“连接中...”

**Comment by Declarcall** [comment]
@Hurambar 同十分钟前断开的

**Comment by JimmyFivy** [comment]
同，正版受害者 ：）

**Comment by Declarcall** [comment]
所以，这是GFW的问题，还是蓝灯官方的问题呢？

**Comment by lvboy1** [comment]
我国内网站是可以打开的，但是墙外的就打不开

**Comment by Bbprime** [comment]
买了一年，刚用一个月，这什么鬼嘛

**Comment by sy4514** [comment]
是因为GWG爆料

**Comment by vuron** [comment]
GWG是什么？

**Comment by lvboy1** [comment]
楼上估计想说GWF吧

**Comment by fontomas** [comment]
@vuron 你可暂时把为他当成个SB对待。反正我是没兴趣看他那些所谓的爆料的，就算是真的，我们看了又能怎样？！我打着灯翻墙，只是为了能照亮前面的路，而不是看路上突然蹦出来的牛鬼蛇神，以及跳梁小丑！
