### ISSUE TITLE
准备弃坑。蓝灯毕竟用了这么久。。有些不舍。。吐槽下，求轻喷

### ISSUE THREAD

**Issue by dave1221** [getlantern/forum#439]
之所以弃坑，不是因为收费，而是因为还存在大量bug的情况下就开始收费，这种东西还没做好就圈钱的作风像极了国人的风格，我只去过欧洲，并不像欧洲我用过任何软件的风格。也不相信这种拿半成品出来卖的态度会是一个负责任的团队的态度。

之所以收费，有一部分噱头是：“不只是出售服务器，还一直研发更加抗封锁的协议和方法，并推出新功能” 也是说现在并没有成熟的协议和方法，除了收费外的新功能并没有看到……

这个价格并不便宜，贵过大多数的vpn，而标榜的所有的东西都在研发。也就是说费用里用户要承担一部分研发费用？先做好啊亲…… 

其次谷歌和帝国的基金补充已经穷到支付不起研发费用需要我们用户出钱么？不说帝国人家忙，凭谷歌的技术还要收取这么高的费用，我不信。。。他们提供资金的初衷是什么？很单纯么？很单纯么？

人毕竟有惰性，习惯了一款软件就不愿意再找别的，市面上能免费翻墙体验和你差不多的何止一家。收取这个费用能满足用户需求的稳定保密性做了很久的又何止一家。我并不认为公然抗封锁有什么前途。

至于之前帖子蓝灯和vpn的区别，没有一条有理有据令人信服，我是咨询过付费vpn的，人家做了八年，上万好评，并不差。vpn可以稳定看视频，可以先测后买，稳定性据评论不差，客服长期针对个人服务，八年没跑路，便宜。

翻墙的初衷对我个人而言无非就是习惯了Google，翻翻论文，偶尔上上18+。想看我浏览网站记录就看吧，弄得神神秘秘的。朝廷要是每个人都能管到，我只能服了。

用了蓝灯不到一年，一路坎坷。到最近开始卖钱用户体验却差到了极点，如开始所说，现在就这么急着圈钱，以后信的过么。 一开始想着毕竟免费用了这么久，买个专业版不为过…… 然而背后有所谓的谷歌撑腰还是这么不严谨合规。还是算了。。。。

总觉得对不起蓝灯，可是也不能为这个专业版买单。。还是算了。以上均属个人非专业意见，轻喷

**Comment by dave1221** [comment]
ps： 忘了说还有另我很不开心的就是个人买个正版卡巴，最近每个版本都开始报毒。就算卡巴和朝廷合作，那也表明了朝廷的态度：此软件不能用。我并不喜欢反朝廷。如果不是合作，卡巴的报毒并不能让人放心。。。蓝灯刚开始多半年并没有报毒的……更想选择相信卡巴。。。pps：已投别的坑。ppps：此贴可删……

**Comment by Huamei-Du** [comment]
跟楼主一样，用了一年多还是选择支持蓝灯。感觉专业版速度能再快一点就好了。我的邀请码 # **YLYP9H**谢 谢

**Comment by maozaiba** [comment]
收不收费无所谓  这并不是重点   因为只要让人足够信任  自然会有人愿意成为付费用户    其实我还有一些疑问 但是感觉官方人员有点不耐烦这些问题  有个回复竟然说某个持怀疑态度的用户是脑残！

还是围观好了。

**Comment by wilon** [comment]
呵呵，又想翻墙，又想速度快，又想免费，这位大爷，你咋不上天呢？
商业化收费是必然之路，要不然卖广告啊？

输入我的邀请码 C4LC4Q ，额外获得三个月的蓝灯专业版！

**Comment by p3rcya** [comment]
@dave1221 "而是因为还存在大量bug的情况下就开始收费" 。现在还是公测版本，官网上版本还是2.2.5，都没有正式改版宣布发布呢。现在你完全可以用2.2.5稳定版，没人逼你用测试版啊。
另外应为卡巴斯基误杀而说蓝灯不可信，这就是你对现在杀毒软件误杀率的不理解了。

**Comment by p3rcya** [comment]
@dave1221 请等正式版蓝灯3推出后，再来吐槽吧，谢谢！

**Comment by p3rcya** [comment]
@maozaiba 请问你的什么问题我不耐烦回答？ 你的“没人怀疑在天朝一个境外翻墙工具居然能使用支付宝付款？”我进行了详细回答，并加入了精华。请问有什么不满意的，欢迎指正！

**Comment by maozaiba** [comment]
@p3rcya 算了  我编辑删掉了   好像不是在我的帖子回复  我也记不清哪个帖子      我还是围观好了！

**Comment by p3rcya** [comment]
@maozaiba 如果你觉得我态度不好的话，我在这里向你道歉！我询问下只是因为能帮助我自己改进。

**Comment by dave1221** [comment]
@wilon 我已经找到了，翻墙，速度快，免费的软件，已经上天，你喜欢随便认人做大爷么？孙子？

**Comment by dave1221** [comment]
@p3rcya 公测版本连累官网版本不能用也是头一次见，你家官方版本能用么？误杀率我都懒得查和你争辩了，你说什么就是什么吧。为毛我用卡巴五年到现在就你一家误报？我吐槽的重点在于正式版出来之前就收费这种不专业拿测试版圈钱的态度谢谢

**Comment by p3rcya** [comment]
@dave1221 官网2.2.5版本不能用是GFW封锁的问题，我们没有做任何限制。这也是我们要推专业版的原因之一。免费版既然大家都能用，那GFW也能用。这个没办法的事情。

**Comment by dave1221** [comment]
@p3rcya 首先我已经弃坑了，其次我除了吐槽也要感谢蓝灯的，我甚至已经买过一次了，只不过出现bug不成功，不得已才去找别家的，自认为对蓝灯算得上是有情怀的。我没有找便宜的，没有找免费的，先去半夜付费已经说明了我的态度。。现在找到一个免费的很好用，才来忍不住吐槽，已经说了有些不舍，求轻喷。。既然有google支持大众的理解是不是应该哪怕付费也能秒杀其他一切渣渣。。哎。。。总之。。感谢蓝灯吧。。有一句说一句 @p3rcya 还是很负责的！

**Comment by p3rcya** [comment]
@dave1221 😄 谢谢！ 感谢你半夜来购买。其实支付宝购买不成功这种bug正是我们公测的理由。因为和支付宝，Stripe并免翻墙付款这个不释放给用户测试，我们自己内测是发现不了这种bug的。我们如果开放给用户免费公测，这种支付的bug等正式发布还得暴露出来。

蓝灯也是会一直保持免费的。问题是现在免费的GFW封的太厉害，造成免费无法使用的错觉，我们正在修复，不好意思。已经弃坑了，我也不会想说服你，但是若下次那个失效了，再回蓝灯看看。 👋

**Comment by dave1221** [comment]
@p3rcya  释放给用户测试可以先用1块钱啊之类的。大致齐的消除了bug再正式付费。毕竟正确的思路是内测如果是普通用户一般没有门槛的，纯个人意见哈。像我这种习惯了Google的人看着百度就觉得蛋疼，等不及啊…… 
毕竟对蓝灯有情怀，我至少向十个以上的人推荐过蓝灯，以后如有需要还是会回来的，谢谢 @p3rcya

**Comment by p3rcya** [comment]
@dave1221 对哦，当时应该先1块钱测试一个月的。。。当时没有想到啊，不好意思😓  不过现在我们对所有公测用户都会赠送一个月，所以算点补偿吧。

**Comment by JulySaligia** [comment]
@p3rcya 真心感觉Lantern这次的策略有很大的问题，让消费者感觉不舒服：“什么？这软件免费的不能用了？收费的就能用？这不逼我们付费么？这样不就和天朝的某鹅游戏有什么区别？；什么？这软件付费了还要当小白鼠？我付费是为了干嘛？”——很多人会这样想，毕竟github上突然冒出这么多帖子就能证明。。。当然，说这么多并不是想喷什么（我并没有用针对Lantern的工作人员，如果您感到不适，我道歉），只是希望自己用的这么久的Lantern能够做到最好而已。

**Comment by Cat7373** [comment]
实际上 Issue 是不能被删的吧- -
最多编辑掉内容- -

**Comment by guotiande** [comment]
其实现在真的不应收费，等全部做好再收也不迟，不过可以先促销一下，如现在买有优惠什么，最好先做一个测试版，让我们知道速度有多少，是否稳定等

**Comment by Keyperfect** [comment]
完全赞同你的观点！这里边有不为人知的秘密！但是为了收费不至于这样玩弄消费者啊！而且原来蓝灯没推出专业版的时候，一直好好的啊，难道GFW没发现吗？现在突然用GFW以及其他原因来圆场，有点难圆其说！而且就算收费，但是你免费的时候的技术手段都在吧，不至于收费之后就出这么多bug吧！矛盾！

**Comment by Cat7373** [comment]
其实试用的话，那 800M 流量应该跟专业版效果相同了吧。。

**Comment by Keyperfect** [comment]
@cat7373一开始说800m用完限速，现在又突然在哪个帖子说不限速，这么出尔反尔，我就想知道这费用收的太突兀了吧

**Comment by Keyperfect** [comment]
#432

**Comment by wilon** [comment]
呵呵，叨逼叨个没完，不愿意交钱就别用，赶紧滚蛋

**Comment by Keyperfect** [comment]
@wilon你不仅暴露了你的素质，而且暴露了你的智商！像你这样的人翻墙了又能搞什么呢……

**Comment by panzer1313208** [comment]
@p3rcya 这里逗逼太多，比如包括昨天那3个喷我的。

**Comment by panzer1313208** [comment]
@Cat7373 哈喽

**Comment by panzer1313208** [comment]
@Keyperfect 哈哈，那3逗逼，有一个说买完之后速度很快的，有一个说我发广告，还有一个说我卖SS

**Comment by wosdsadsahjd** [comment]
@dave1221 能跟我说一下那个免费vpn的名称吗0.0

**Comment by corbinass** [comment]
@dave1221 我也想知道免费VPN

**Comment by yeahwu** [comment]
google资助过lantern吗？美国国务院国家种子资金的资助倒是真的！下面是维基链接，真没看到google资助字样！
维基链接：https://zh.wikipedia.org/wiki/%E8%93%9D%E7%81%AF
俺这边2.x版还是可以用的，所以大家为什么不试试2.x版

**Comment by p3rcya** [comment]
见 www.scmp.com/news/china-insider/article/1372661/use-lantern-software-means-view-banned-websites-grows-china 2.2.5封的多。蓝灯3能用的尽量用3， 不行在用2吧

**Comment by yeahwu** [comment]
@p3rcya 谢版主解惑。辛苦了

**Comment by panzer1313208** [comment]
@yeahwu 你也来了？加我群吧

**Comment by NeroRose** [comment]
工作人员的态度是不是得加强了，人家和你说问题你直接就把人家呛回去，你应该这么干嘛，再说别人说的也不是全无道理，你这样做只会增加对这个软件更多的吐槽而已！

**Comment by yeahwu** [comment]
@Cat7373 @panzer1313208 很高兴遇见你们
多说几句，建议
1:增加退款按钮
2:pro用户尽量选择日本，港澳台，周边线路，其实用户要求并不高，只要达到以前2.0时候的速度就可以了
3:增加售后，或者建立售后体系，不要小瞧天朝的用户量。
上面纯属瞎扯，不喜，毋喷

**Comment by DPABeginner** [comment]
@yeahwu 老实交代，叉叉是不是也想收费了？lantern收费后必然会流失众多用户，然后你们在免费界一家独大，再然后和lantern一样走向商业化

**Comment by yeahwu** [comment]
你见过gae有收费的？xx是开源软件，俺们开发不用对用户负责，用户也不用对俺们掏钱，情况就是这么个情况！
自由软件，所以用户不要对俺们撕逼，爱用不用！
DPABeginner <notifications@github.com>于2016年7月11日 周一10:27写道：

**Comment by DPABeginner** [comment]
@yeahwu 别激动，俺只是用开玩笑的口吻问问，毕竟一直用叉叉，担心以后没得用。希望你们保持逼格，不为利益所动，顶

**Comment by orbancanon** [comment]
非常感谢@yeahwu 。你做的很多事，包括集成Lantern，大家有目共睹。建议非常中肯，只是需要一点一点地啃。期待多聊。

**Comment by kxkxkx** [comment]
@panzer1313208   怎么就是给脸不要是吧  你的群号都叫作者k了  好好卖你的ss 别再打着蓝灯的幌子  

![qq 20160711114214](https://cloud.githubusercontent.com/assets/16475312/16719432/c6b31620-475c-11e6-83df-efb0ad5d4807.jpg)
![qq 20160711114205](https://cloud.githubusercontent.com/assets/16475312/16719431/c6978cc0-475c-11e6-930a-9fdc9870eb30.png)
![qq 20160711114210](https://cloud.githubusercontent.com/assets/16475312/16719430/c614231c-475c-11e6-8ad4-8513d3f7685f.png)

**Comment by panzer1313208** [comment]
@kxkxkx 你好像萌萌，我卖SS怎么了？蓝灯的幌子？我什么时候打蓝灯的幌子了？你给我说清楚不然我要去告你诬陷你知道吗？

**Comment by kxkxkx** [comment]
@panzer1313208 嘴真硬啊 谁在这发蓝灯吧官方群号了？又是谁把小白骗进去兜售ss了？？谁的广告帖子被作者删除了？你的贴吧被封了，并不是来这发你的广告贴的理由！！！利用蓝灯当幌子也赚了不少钱了，适可而止好吧，给自己留点脸。15一个月的ss，就给个二维码了事，真黑啊。

**Comment by panzer1313208** [comment]
@kxkxkx 你可以去看看支持几十个用户看4K的VPS一个月要多少钱，不谢。

**Comment by panzer1313208** [comment]
@kxkxkx 其次我是在这里发蓝灯吧官方群号了，但为什么一定是打着蓝灯的幌子呢？首先蓝灯吧是一个翻墙吧，他不是蓝灯的专业贴吧。其次你可以看看我群里有多少种免费的翻墙方法，

**Comment by panzer1313208** [comment]
@kxkxkx 要不要我发截图？

**Comment by panzer1313208** [comment]
![z gigw4 j j pn_ptoemga](https://cloud.githubusercontent.com/assets/13449426/16726428/b9c7f6b0-478e-11e6-945b-d1e2fdcb11cc.png)

**Comment by panzer1313208** [comment]
看到了吗？这些都是免费的翻墙方法，但群友们说速度不行，想买SS，天天在群里问有没有卖SS的，所以我才去卖的啊。是群里人让我卖的，你不服你可以去找他们。

**Comment by panzer1313208** [comment]
你放心你加完群我肯定不T你，你来问问群里人对我的评价怎么样？

**Comment by kxkxkx** [comment]
@panzer1313208   
请回答 谁在这发蓝灯吧官方群号了？又是谁把小白骗进去兜售ss了？？谁的广告帖子被作者删除了？

别拿4k说事  我用的ss 运行一年多了  一年五十   你能比？20条线路都能4k

**Comment by panzer1313208** [comment]
@kxkxkx 我在这里发蓝灯吧官方群号怎么了？我的是翻墙群，让不能翻墙的小白进去找翻墙方法，有错吗？群号贴子被作者删除不是因为你导致的吗？

**Comment by panzer1313208** [comment]
@kxkxkx 我卖的贵吗你告诉我？15元一个月能看4K不限制流量？

**Comment by panzer1313208** [comment]
@kxkxkx 群里人觉得免费翻墙速度慢，让我弄个收费的有错吗？嗯？你别跟我提蓝灯，你看看这个论坛里有多少人想退款，有多少人说蓝灯不能用？

**Comment by panzer1313208** [comment]
@kxkxkx 
![2 umj4sk2j43xp kkqum 2u](https://cloud.githubusercontent.com/assets/13449426/16726653/ee4471f6-478f-11e6-93f2-be477e984b3b.png)

**Comment by panzer1313208** [comment]
不应该卖里面只有3票，因为有一票是我头的，另外一个票是另外一个卖SS的人投的。

**Comment by panzer1313208** [comment]
等这个投票的最终结果出来了，我就去弄另外一个投票。本群是不是应该禁止卖收费翻墙软件。

**Comment by panzer1313208** [comment]
@kxkxkx 如果群里禁止卖收费翻墙软件，或者群里人同意并且支持群主卖SS，我看你还有什么话说。呵呵

**Comment by panzer1313208** [comment]
对了顺便告诉你，群里人基本全是这个论坛和蓝灯贴吧加进去的。

**Comment by panzer1313208** [comment]
一年五十美元？20条线路都能4k？就你一个人还是一堆人？

**Comment by kxkxkx** [comment]
@panzer1313208  请回答 谁在这发蓝灯吧官方群号了？又是谁把小白骗进去兜售ss了？？谁的广告帖子被作者删除了？

**Comment by kxkxkx** [comment]
@panzer1313208 我也不和你废话了  你再在这发什么群号我就继续举报你

**Comment by panzer1313208** [comment]
@kxkxkx 骗进去？请回答你对骗的定义是什么？

**Comment by panzer1313208** [comment]
@kxkxkx 谁的广告贴子被作者删除我不太清楚，但肯定跟我无关。

**Comment by kxkxkx** [comment]
@panzer1313208    你不清楚？？？？我可有截图

**Comment by panzer1313208** [comment]
@kxkxkx 那么问题来了，你给不给那些买了蓝灯发现用不了然后想要退钱的人退钱？如果你不给退。那你哪来的脸举报我？

**Comment by kxkxkx** [comment]
@panzer1313208    
![123](https://cloud.githubusercontent.com/assets/16475312/16728092/08d4f228-4797-11e6-93ad-48fd5821f461.png)

**Comment by panzer1313208** [comment]
@kxkxkx 哦，这个的确是被关了，但还有很多没被关掉的啊？

**Comment by panzer1313208** [comment]
以后他在发就直接关他的帖子，但之前发的没关啊。

**Comment by nicklv** [comment]
看俩逗比开撕好好玩

**Comment by shoujiao** [comment]
看到其他项目的大神都来这里参与讨论了，真是一石激起千层浪啊！

**Comment by ssy341** [comment]
脑洞大开

**Comment by ssy341** [comment]
@Cat7373 把仓库删掉，这些都没有，简单粗暴

**Comment by grchen** [comment]
输入我的邀请码 LFJ626 ，额外获得三个月的蓝灯专业版！

**Comment by taoyie126** [comment]
我都购买专业版了却也上不去啊，在论坛反映好久了，还没有解决

**Comment by youe360** [comment]
@wilon  一看就不是好好看issue，楼主是买了蓝灯服务，但是对蓝灯现在状况不满意，而不是人家要求免费，他还和另外的收费VPN比较，哪里表明是要求免费啦？？你这人评论跟国内新闻评论一棒子喷子一个调调～

**Comment by youe360** [comment]
@wilon 我帮你总结吧，按国内喷子标准，一句话就行了，爱用不用，不用滚，爽吧～

**Comment by orcleoqu** [comment]
@panzer1313208  能在i o s上用么 限制流量么 私信下

**Comment by p3rcya** [comment]
iOS 上的蓝灯都是假的

**Comment by theratlesnake** [comment]
支持蓝灯，只要是建梯子的，都支持一下

**Comment by mayrain** [comment]
输入我的邀请码 YHQY2P5 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by wallyhung** [comment]
就一个fq的事情，这样撕逼好吗，如果你用的好，就继续买，如果不好，就自己买一个vps，支持数十个用户访问也是ok的，（毕竟你身边的朋友总有一个会翻墙技术的），我觉得大家都是本着讨论技术的态度来的，对真心做技术分享的人，32个赞👍如果说了某些话触犯了某些人，在这里先道歉~（ps，我曾经也各种搜索免费fq的办法，lantern给了很大帮助，很有感情，现在已经搭了个人vps）

**Comment by theratlesnake** [comment]
藍燈適合那些不懂技術，也不喜歡折騰的新手，挺好的，支持，還有別撕逼。

**Comment by lendo** [comment]
我就是先用GoAgent，再用蓝灯，再VPN，再用SS，最后又回到蓝灯。在如今形式下，VPN，SS都是随时可以封掉的，另外，不晓得VPN和SS有啥高级的。

**Comment by theratlesnake** [comment]
1楼这种人翻墙都是浪费国家资源，好好呆在墙内看新闻联播意淫高潮一下不就得了。翻个屁墙啊

**Comment by hallochina** [comment]
能不折腾，还是别折腾了，走付费vpn吧
https://vpnchina.zdhweb.com/p/vpn-china.html
你可以根据自己的偏好选择注册所有推荐的vpn，然后根据使用效果，哪个好用就付款哪个。

**Comment by lucyddd** [comment]
国内的基本都被封杀了，就是存活的，也存在跑路风险，你还是直接买国外的吧，替代蓝灯，天行，Green，豆荚等
http://zhizhi.npage.de/
