### ISSUE TITLE
相信蓝灯选择蓝灯！专业版1年85 我是代理 有意联系 可走咸鱼 信誉可查

### ISSUE THREAD

**Issue by justinpp** [getlantern/forum#4408]
蓝灯是目前最靠谱 最方便快速的软件！专业版速度平均2-3m/s 相信蓝灯选择蓝灯。我是蓝灯代理商，有需要专业版可以联系我，单设备专业版1年85。激活码1年190 2年300，已有60多位买家，可走咸鱼，信用评价可查。有意联系q：1262200959

**Comment by Jasoncxs** [comment]
我现在已经可以macbook 上了windows 还不行

在 2017年10月5日 下午11:33，justinpp <notifications@github.com>写道：
