### ISSUE TITLE
请教latern怎么在Chrome上使用

### ISSUE THREAD

**Issue by farshidvahid** [getlantern/forum#4422]
XX-NET 歇菜。下载了latern最新版，安装后，可以使用IE翻墙，也按照教程，配合switchy omega建立了latern的场景和pac文件（http://127.0.0.1:8086/proxy.pac），但在chrome上无法翻墙。请教目前最新版的latern chrome教程，有人能给个链接吗？感谢了！

**Comment by beboyss** [comment]
不用什么switchy啊，装上lantern全浏览器支持

**Comment by farshidvahid** [comment]
@beboyss  我使用chrome直接连接，再打开latern，还是不能翻墙啊。但IE可以。请教这是怎么回事？

**Comment by Declarcall** [comment]
@farshidvahid 蓝灯在webUI的设置里给出了代理服务器的类型，以及端口号。自己配置一下

**Comment by farshidvahid** [comment]
＠Declarcall 　蓝灯的设置里，把“管理系统代理”　和“代理全部流量”都勾选上了，还是无法使用chrome翻。能否说的详细点？感谢！

**Comment by sky660099** [comment]
把swithy停用掉

**Comment by farshidvahid** [comment]
@sky660099  停用后可以了。感谢！
