### ISSUE TITLE
问下有没有人和我相同情况（win8/10）

### ISSUE THREAD

**Issue by NAVrasZ** [getlantern/forum#443]
在本机上折腾得我彻底晕掉了，所以还是直接来问问好了
不知道是我自己系统的问题还是...
win10，msdn itellyou下载镜像升级
默认搜索为百度（可换bing不能换google）
然后主题其实是这张图233
![777](https://cloud.githubusercontent.com/assets/20354364/16706492/996f4a84-45e1-11e6-8532-d12eca2179c4.PNG)
和我有相同问题的应该能一眼看明白我的意思~

**Comment by p3rcya** [comment]
如果楼下有相同的问题，请按照 https://github.com/getlantern/forum/issues/358 上传log

**Comment by NAVrasZ** [comment]
[lantern.txt](https://github.com/getlantern/forum/files/355443/lantern.txt)
今天折腾几下不知道log里有没有新内容，我传份今天的

**Comment by NAVrasZ** [comment]
没有，，好事
那我关了哈~
