### ISSUE TITLE
重装了一下lantern就无法登陆了，才用了两个月专业版

### ISSUE THREAD

**Issue by FeiLeMa** [getlantern/forum#4462]
请输入支付宝账号或者Email

无法根据以上信息找回账号

我输入了 我当时绑定的邮箱账号显示，无法根据以上信息找回账号。
又试了以下用当时付款的支付宝账号，一样显示，无法根据以上信息找回账号

**Comment by MartinCrewes** [comment]
**## 是重装系统了？重装之前应该得取消授权。**
使用我的代码 JFDDVM 在购买后将免费获得额外3个月的权限。下载 Lantern https://bit.ly/lanternapk
![screenshot_2017-10-08-13-15-31-261_org getlantern lantern](https://user-images.githubusercontent.com/31303829/31314134-39b5ed9e-ac2b-11e7-8b3b-c30abe085ddc.png)

**Comment by FeiLeMa** [comment]
都没客服来解决一下吗

**Comment by FeiLeMa** [comment]
哇，终于解决了，有问题的找这位orbancanon@gmail.com
