### ISSUE TITLE
蓝灯在pc上无法登陆专业版账号？？

### ISSUE THREAD

**Issue by SMALLKBLOG** [getlantern/forum#447]
我的pc上没办法发验证邮件。总是出错。。
#444
[lantern.txt](https://github.com/getlantern/forum/files/355452/lantern.txt)
![qq 20160709145005](https://cloud.githubusercontent.com/assets/13879039/16706606/774b89b4-45e5-11e6-86c8-190207cf785b.png)

**Comment by SMALLKBLOG** [comment]
？？没人这样子吗、。、

**Comment by p3rcya** [comment]
我们正在调查原帖的log， https://github.com/getlantern/forum/issues/444 

这个帖重复了，我关闭了
