### ISSUE TITLE
刚买了专业版一天，因为手机问题恢复了出厂设置，再登录蓝灯无法继续使用专业版了。

### ISSUE THREAD

**Issue by farmgirlLilian** [getlantern/forum#4486]
刚买了专业版一天，因为手机问题恢复了出厂设置，再登录蓝灯无法继续使用专业版了。

蓝灯专业版账号Email: 490769224@qq.com 

应用内报告问题的时间: 2017.10.8

截图: 支付凭证
![_20171009131018](https://user-images.githubusercontent.com/32628851/31325763-53986a52-acf3-11e7-9e4c-c875fb08308a.png)

**Comment by ningqivip** [comment]
是被封了，老哥，和你手机没关系，我买了两年。也不能上了。
