### ISSUE TITLE
我不是黑蓝灯啊

### ISSUE THREAD

**Issue by beboyss** [getlantern/forum#4494]
不过咱蓝灯的技术实力是不是有待提高啊，当初我还没买专业版的时候，我记得lantern的关键口号是蓝灯不是vpn，gfw能封vpn但是封不了lantern，因为lantern的服务器对客户端不可见（后来发现不是这么回事啊），而且一封就是整体封，还不是某个服务器封，加油啊，要对得起承诺，等你们做大做强呢

**Comment by chenliuzhi** [comment]
我也上不去了！现在用的时改host

**Comment by GD-HBX** [comment]
是不是蓝灯骑的马是阿里巴巴缘故啊？阿里巴巴吃大陆草？

**Comment by 349205055** [comment]
蓝灯用的阿里云服务器，你说呢

**Comment by bigsyw** [comment]
专业版一年200多，说爆炸就爆炸，让我们怎么相信你们了，速度是不错，服务器真的别用阿里云了，马云的公司和江派有勾结，郭文贵爆料的，你们不知道吗？香港服务器说封就封，你们抢救有个屁用。

前几天四川也发生了万人抗议的活动，加上郭文贵爆料，中共是真的怕了，这次共产党怕是要全国断网了，我们要跟朝鲜一样了，哈哈。
