### ISSUE TITLE
到底是GFW的问题，还是蓝灯挂着GFW的名头收费，大家拭目以待

### ISSUE THREAD

**Issue by Keyperfect** [getlantern/forum#456]
首先，我们不该做伸手党，天上没有免费的馅饼。所以我是支持收费的，因为这也算是开发者来之不易的成果！但我感觉如果蓝灯挂着GFW的名义就收这么多的费用，关键还没有过去免费的时候好使，就有点说不过去了。管理员说这是与谷歌开发的，大家可以想想，谷歌在全球那是多牛的，所以如果真是这样的话，蓝灯是有前景的。但是如果是打着谷歌的名义来欺骗消费这就呵呵了。话说谷歌差这点钱吗？一次收这么多。还有就是这么多贴子，管理员的回复你们难道没发现漏洞吗？其实，这背后还有许多不为人知的东东。以上再重复一次，我们确实喜欢蓝灯，也支持收费，但是希望蓝灯拿出应有的效果！我想这个问题会浮出水面的！
还有大家想发现这中间的管理员说话漏洞，请多看看他对几个问题贴的回复，再联系谷歌的背景，你就会发现有点上当的感觉。
不论如何，不管内幕怎样，蓝灯使得6就行，对得起消费者就行！

**Comment by Keyperfect** [comment]
！这里边有不为人知的秘密！但是为了收费不至于这样玩弄消费者啊！而且原来蓝灯没推出专业版的时候，一直好好的啊，难道GFW没发现吗？现在突然用GFW以及其他原因来圆场，有点难圆其说！而且就算收费，但是你免费的时候的技术手段都在吧，不至于收费之后就出这么多bug吧！矛盾！

**Comment by ineondog** [comment]
在哪里可以看到用GFW的原因来圆场了？

**Comment by Keyperfect** [comment]
蓝灯收费是为了提供更好的用户体验，而不是给用户一个烂摊子！管理员说官网没发布最新版，但我记得他哪个帖子说 官网虽然是2.25版本的，但下载的是最新版的！

**Comment by Keyperfect** [comment]
@ineondog 翻看旧的帖子，就懂了

**Comment by Keyperfect** [comment]
@ineondog  可以看看#449

**Comment by Keyperfect** [comment]
@ineondog #439

**Comment by Keyperfect** [comment]
#426

**Comment by Keyperfect** [comment]
我们不做喷子，只做理性的发现者

**Comment by Keyperfect** [comment]
总之，我想大家对蓝灯的态度，就是爱之深，责之切！愿蓝灯可以对得起大家

**Comment by ineondog** [comment]
大概明白了，我觉得这次突然收费没公关好，大半年前是有问卷调查的：“你愿意为lantern付费获取更高质量的服务吗？”，这个问题我记得我选了是，大概这就是唯一的预告了，前几天突然上线付费吃相难看。
但毕竟稳定的vpn不好找，我用过很多付费的免费的都出现各种各样的问题，所以宽容一点吧，毕竟免费了那么久，lantern也不是公益组织，也有成本压力的。（谷歌不也是卖广告办会员吗

**Comment by Keyperfect** [comment]
@ineondog  对啊！大家纠结在一个高质量的问题上！因为截至目前，翻墙软件数不胜数，高质量的就不多了！

**Comment by ineondog** [comment]
#362 这里讲得蛮清楚的（但不管问题怎么样都是源于我国令人作呕的行为，而不是开发者或者用户的错

**Comment by Keyperfect** [comment]
讲的确实挺清楚，关键是付费后速度不行了！而他说付费后流量速度无限……

**Comment by yixiaoqingyuz** [comment]
支持你

**Comment by lucyddd** [comment]
国内的基本都被封杀了，就是存活的，也存在跑路风险，你还是直接买国外的吧，替代蓝灯，天行，Green，豆荚等
http://zhizhi.npage.de/
