### ISSUE TITLE
请教，为啥某些人解释为物理断，而GitHub可以登陆？蓝灯是否是租用阿里服务器？

### ISSUE THREAD

**Issue by AllenBrook** [getlantern/forum#4597]
如题：请管理员给个官方的回复，谢谢，这些直接影响大家对蓝灯可靠性的信任程度，不要总是三天两头的出问题，然后出来某几个XX说物理断网

**Comment by AllenBrook** [comment]
@angelwithout

**Comment by ZimmerWu** [comment]
确实是租的阿里云，前几天看到过节点信息，忘了是在哪看的了。

**Comment by temnia** [comment]
github没有墙为什么不能登陆，服务器一直都有用阿里云

**Comment by AllenBrook** [comment]
那就是近期蓝灯频繁断网是因为蓝灯的阿里云服务器被GFW识别，并进行了封锁导致的？
属于服务故障，根本赖不到物理断网！

**Comment by wzh190015** [comment]
github没被墙

**Comment by anticpc** [comment]
香港阿里云ss表示没问题
