### ISSUE TITLE
蓝灯失效超过24h了 大家进来讨论一下

### ISSUE THREAD

**Issue by gfwwcnm** [getlantern/forum#4700]
1.已经失效超过24小时，昨天崩溃 晚上好用过一阵马上继续崩溃
2.新版蓝灯在安卓上存在卡死现象，老版本不会
3.服务器地址一会US一会JP然而并没有什么卵用
3.WIN10用最新桌面版依旧存在卡死问题
**4.蓝灯是否能解决？不能解决的话尽快开启退款通道**
5.GitHub能裸连，所以上这里暂时没有问题
6.用别人的自建SS也挂了
7.并非所有的梯子都不行了，我用借来的PLEXVPN好好的

**Comment by lijun500** [comment]
挺住呀   昨晚有一段时间不行  后来12点过后 可以了 再后来 又不行 今早彻底完蛋了

**Comment by gfwwcnm** [comment]
@lijun500 就是这样我要受不了了

**Comment by 80068** [comment]
希望英、美、法、德、日、意、西、加、澳、新。同时想想办法。

**Comment by gfwwcnm** [comment]
@80068 指望别人还不如自己想办法，我现在拿PLEX顶着，但是感觉不过多久肯定完蛋

**Comment by VCDVD** [comment]
没有24h，只有13h。

**Comment by gfwwcnm** [comment]
@VCDVD 中间那那几个小时抠了不算？昨天下午3点左右失效的

**Comment by bizos** [comment]
我也是移动端和windows端同时失效，而且都是闪退。

**Comment by atlantishulin** [comment]
其实刚才十点到十点半还是挺好用的 也可以看YouTube 720p。

**Comment by gfwwcnm** [comment]
@bizos 感觉版本迭代有问题，不知道什么问题造成的。墙肯定也是升级了
你先拿上面的顶一下子能用24小时。手机好像能用更久

**Comment by gfwwcnm** [comment]
@atlantishulin 我的一直不好用，关键是安卓端一直在崩溃让我很难受

**Comment by nodoubtLA** [comment]
真是一场fight

**Comment by BIRDSLIKE** [comment]
@atlantishulin  刚十到十点半能用？ 昨晚也是这个时间段短暂好了一会 然后崩到12点

**Comment by ningqivip** [comment]
刚买了2年会员，盗国賊们已经疯狂了。准备自己搭服务器。

**Comment by ningqivip** [comment]
不知道能不能退款，一个月都没用到，就挂了

**Comment by gfwwcnm** [comment]
@VCDVD 我真是服了 我也不招谁惹谁 也不支持那几个开直播的缺心眼玩意 就是想好好看点资料 看看朋友们怎么样了 ，至于这么对我么

**Comment by gfwwcnm** [comment]
@ningqivip 退款我是不指望的，因为不退款成本很低，你能拿他怎么样，先拿我上面给的的顶一顶吧

**Comment by ebnbin** [comment]
@gfwwcnm PLEXVPN 也得翻出去才能上官网？

**Comment by Voyager-One** [comment]
我只是翻墙来用google搜索bug、上stackoverflow、上udemy和cousera、偶尔看看youtube上的囧星人和部长（tuber），唉又不干什么危害gcd统治的事，又不违法犯罪，为什么要这样啊？

**Comment by gfwwcnm** [comment]
@ebnbin 没有啊 直接就能上

**Comment by VCDVD** [comment]
@gfwwcnm 这不是心平气和，就事论事吗？有任何攻击的意思？

**Comment by gfwwcnm** [comment]
@Voyager-One 就这样了你能怎么的吧 我反正现在听绝望的 是不是要和朋友们永远说再见了

**Comment by gfwwcnm** [comment]
@VCDVD 买灯笼就是图的他稳定 我生气的是 根本不稳定，当然原来一直挺好，现在大家都上不去这么久了 久没人出来说句话么？

**Comment by gfwwcnm** [comment]
@VCDVD买灯笼就是图的他稳定我生气的是本本不稳定，当然原来一直挺好，现在大家都上不去这么久了久没人出来说句话么？

**Comment by xhxktd** [comment]
2.新版蓝灯在安卓上存在卡死现象
今天刚下的新版本 每次打开都会卡死

**Comment by gfwwcnm** [comment]
@xhxktd 就是这样

**Comment by VCDVD** [comment]
最近的几个新版本在连不上的时候会假死，自动崩溃。

**Comment by gfwwcnm** [comment]
@VCDVD 上一个版本还行 这个版本就是坑 除了界面好看一点

**Comment by FoobarRogers** [comment]
@xhxktd  从失联开始崩溃，应该是软件容错率太低

**Comment by gfwwcnm** [comment]
@FoobarRogers 容错率这种事情不是放出来之前必须要考虑的事情之一么

**Comment by VCDVD** [comment]
我还是觉得年初的版本好，稳定，界面简洁，也不会出现假死的情况。

**Comment by gfwwcnm** [comment]
@VCDVD 现在看来，已经回不去了。

**Comment by VCDVD** [comment]
看看能不能起死回生吧。真的倒下的话确实太可惜了。

**Comment by VCDVD** [comment]
话说现在洛杉矶也8:45了，官方还没回应～

**Comment by duanj3** [comment]
green倒的时候，难过的一批，现在lantern也不知道能不能挺住了

**Comment by karlzhouzhi** [comment]
能不能解决啊

**Comment by ashuang001** [comment]
这回看样子即使恢复了,也不会维持很长时间.这种长时间的中断或许会成为常态.
这是大家都不原意见到的.但似乎又是不得不面对的.
目前只能寄希望于10月以后,看能不能得到好转.如果10月以后1,2个月都还维持这种抽风状态的话,
那么豪无疑问的说可以放弃lantern了.

**Comment by karlzhouzhi** [comment]
官方处理说句话啊，发邮件了，也没人理

**Comment by FoobarRogers** [comment]
@gfwwcnm 我现在非常庆幸我当时早早地把Gmail客户端换成outlook并把Gmail登录上去，至少工作生活的信息没什么延误

**Comment by karlzhouzhi** [comment]
已经交了两年的年费了，能退吗

**Comment by NAHNAH55** [comment]
大家可以试一下 
Psiphon3 (免费， win 和 Android 都还能用， 但有点慢） https://psiphon.ca/en/download.html
Plex VPN (我还在试一下。 他们VPN是一天免费， 每月大概2.x美金） 如果要试一下， 请用 Z6YBU9 （买一月送一月）https://iplexvpn.com./register?invite_code=Z6YBU9

**Comment by karlzhouzhi** [comment]
开来了蓝灯，guthub上不去，我现在是卸载了蓝灯的

**Comment by karlzhouzhi** [comment]
现在需要蓝灯官方出来说句话

**Comment by karlzhouzhi** [comment]
你们有没有找过他们

**Comment by gfwwcnm** [comment]
@karlzhouzhi 怎么找？发邮件么？有人理你么？

**Comment by VCDVD** [comment]
@gfwwcnm 蓝灯恢复了。

**Comment by FoobarRogers** [comment]
@gfwwcnm 几分钟前已经发送英文邮件，看看会不会回复

**Comment by gfwwcnm** [comment]
@VCDVD 难道又是半夜恢复 第二天早上10点掐掉？

**Comment by gfwwcnm** [comment]
@FoobarRogers 我早就发了 没人理我

**Comment by VCDVD** [comment]
@gfwwcnm GFW跟蓝灯玩打游击的战术吧。

**Comment by gfwwcnm** [comment]
@NAHNAH55 把你这几个去自救小组帖子发一下 吧现在的帖子删了 我一会把上面的链接也抹了 刚才问题被关了一次 怀疑灯笼官方不让做广告

**Comment by gfwwcnm** [comment]
@FoobarRogers 我是什么都是gmail 感觉要坑

**Comment by VCDVD** [comment]
@gfwwcnm 前面关闭帖子不是你自己关的吗？

**Comment by VCDVD** [comment]
@gfwwcnm 多准备几款翻墙软件，有备无患。

**Comment by gfwwcnm** [comment]
@VCDVD 依旧崩溃，依旧连不上，手机端电脑端都连不上。
多备几款是好的，但是就怕一封全完蛋

**Comment by gfwwcnm** [comment]
@VCDVD 不是，突然就关闭了 然后我自己打开的 玩GitHub有一阵了 我又不是新手

**Comment by FoobarRogers** [comment]
@gfwwcnm 建议趁这次赶紧用outlook之类国内能用的邮件客户端代接收一下，163貌似也可以，看你敢不敢

**Comment by gfwwcnm** [comment]
@gfwwcnmOutlook有人不是哪里都好用的

**Comment by zhangchi25806** [comment]
我个人使用的印象是，国庆节后第二天，下午突然断开，晚上好了一下下，然后又废了，夜里好，早上坏，真是x了狗了

**Comment by VCDVD** [comment]
😄共匪跟蓝灯玩打游击的战术呢，专挑人家下班和休假的时候下手。

**Comment by NovusLio** [comment]
I'm sorry ,I just give up , I use express VPN now ,maybe is hight pricing but is stable,I'm very tired to find out nice VPN service.

**Comment by gfwwcnm** [comment]
@zhangchi25806 不停的坏 不停的好

**Comment by zhangchi25806** [comment]
@gfwwcnm 唉，这监管我真是X了。老子在美国读了两年书干了三年，回到了家乡北京。不怕工资少不怕吸雾霾不怕挤地铁，倒有几个人不让老子上谷歌上维基，这不是逼着爱国青年出走他乡嘛。

**Comment by ningqivip** [comment]
有卡死现象的，可以用谷歌应用下载蓝灯试试。我在官网下载的，有卡死现象。用谷歌应用商店下载安装的，不会卡死

**Comment by ningqivip** [comment]
都是一个版本。

**Comment by ningqivip** [comment]
不过就是上不了

**Comment by c1x2g** [comment]
呵呵19大 我cnm 蓝灯挺住啊

**Comment by xhxktd** [comment]
@ningqivip 就是在PLAY下的 卡死

**Comment by laocaodc** [comment]
看来都是同一个毛病啊! 安卓上只要点一下卡死  电脑上还是不能用啊

**Comment by michaelzq** [comment]
电脑和安卓都不能用，怎么办怎么办

**Comment by zhmi1204** [comment]
gcd逼人造反

**Comment by luoxixi** [comment]
同同同刚续费的，就不能用了 赶紧退款吧

**Comment by laocaodc** [comment]
都不能用啊？ 我也凑个热闹吧

**Comment by dskjg** [comment]
真被办了，我看退款也没戏了...Green被办了后过来蓝灯的...虽说Green开了那啥退款通道不过我申请了自今没收到退款....

**Comment by ZHSD** [comment]
现在非常时期,只能过段时间看看了

**Comment by UnivexDont** [comment]
Wingy 这个能用啊 ，为啥没有给墙掉。

**Comment by xzgfzcnk** [comment]
Do not use Chinese Develope VPNs etc.. Do not belive everything on WiKipedia, you know everyone can edit it.Expressvpn trubovpn speedyvpn shadowsocks etc none of these was shutdown by GFW even they guys want to.

**Comment by sy4514** [comment]
我有个VPN能用，但是不敢说，说了怕很快用不了了。自私一次吧

**Comment by 2freeDollRida** [comment]
@ebnbin than try NordVPN it's cheaper but IMHO one of the best and also many reviews editors choice
