### ISSUE TITLE
plexplan邀请码，可以免费用24小时。

### ISSUE THREAD

**Issue by wycfg** [getlantern/forum#4718]
https://www.plexplan.com/register?invite_code=ZBHRUR
各位大大用我的邀请码注册哦

**Comment by IAMZHY** [comment]
速度怎么样，好用不

**Comment by VCDVD** [comment]
呵呵，不怕死的可以去用plexvpn，公司是北京的，网站是备案过的，竟然还用QQ群联系。

**Comment by ovoff** [comment]
跟帖发我的，特殊情况下的临时方案
https://www.plexplan.com/register?invite_code=ZGA5UZ

**Comment by VCDVD** [comment]
@ovoff 呵呵，不怕死的可以去用plexvpn，公司是北京的，网站是备案过的，竟然还用QQ群联系。

**Comment by ovoff** [comment]
@VCDVD 临时用个24小时，反正你做什么TG也都是知道的，想找茬早就找了吧

**Comment by courser81** [comment]
充值页面根本打不开，但是真能上

**Comment by ovoff** [comment]
@VCDVD 不过按照你提醒查了下，备案信息竟然找不到？

**Comment by VCDVD** [comment]
中文版网页底部有备案号，是 京ICP备13004197号-6。
![image](https://user-images.githubusercontent.com/32630138/31416242-710957e6-ae5a-11e7-99a2-0b2e5c7a697a.png)

**Comment by ovoff** [comment]
@VCDVD 刚备案信息查不到，现在查到了，原来这个号注册给了另一个域名。

**Comment by wycfg** [comment]
速度肯定比不上蓝灯了，临时顶一下用

**Comment by unever** [comment]
说句大实话，就算获取信息又怎么样？很多翻墙的朋友就是为了能方便的Google一下，能访问Github，能查看设计网站等等，如果不是为了搞事情，怕什么？访问国内的微博百度就不知道你干嘛了？只要能提供快速稳定的线路和服务器，他是不是国内公司根本不重要，钓鱼？想多了。

**Comment by wycfg** [comment]
这个好像也封了。YouTube已经连不上了
