### ISSUE TITLE
plexplan这个真的很好用啊，但是顶风作案真的好么

### ISSUE THREAD

**Issue by xiguataida** [getlantern/forum#4721]
https://www.plexplan.com/register?invite_code=ZGYWUB
注册地址

**Comment by ALT34555** [comment]
我怀疑是针对灯笼的恶意攻击。
1.推上在此之前就有以郭某人为首的，一个煽动分裂的一波傻X。
2.此次攻击后，先搭别的梯子再点灯是能上的。
3.刚刚好是在双十节/哥伦布日凑在一起的时候出问题。
4.半路杀出个plex。

有理由怀疑是奇怪的人发动的针对性攻击。

不敢用主要还是担心被钓鱼。如果是官老爷开的通道我还信用一些，毕竟我并不认为追蒙面超人有什么不可以的。
问题就在它是境内组织。
如果是海外的，它拿到了我的信息也没用，但是境内的话就说不好了……
