### ISSUE TITLE
该死的盗国狗贼们，封杀蓝灯，看你们嚣张到什么时候，一切都是刚刚开始！

### ISSUE THREAD

**Issue by xueshaopeng** [getlantern/forum#4727]
一个郭文贵就把你们吓死了，你们这帮盗国狗贼，不得好下场！

**Comment by manxiaoboo** [comment]
祖国生你养你，给你安全生活，给你进职机会，给你文化底蕴，义务教你读书。没有党，能有今天？你对社会又有什么贡献？就因为这么几天不让你翻墙，你就叫上了。所有国家都对中国另眼相看，反而有你这种人，跟不上发展的脚步，只知道故步自封，崇洋媚外。到底谁是狗贼？

**Comment by yyqxjwxy** [comment]
楼上五毛？

**Comment by manxiaoboo** [comment]
我倒给你们五毛，求别辱国了，看着丢人。

**Comment by xueshaopeng** [comment]
@manxiaoboo 你的任务已经完成，可以回去领你的狗粮了。

**Comment by yyqxjwxy** [comment]
@manxiaoboo 呵呵呵我倒不想讨论政治，不过有你这种货色真是悲哀

**Comment by Chinaguigui** [comment]
@yyqxjwxy 说得没错 其实我也不想讨论政治，还是别理他为好

**Comment by hadow** [comment]
@manxiaoboo 2B青年，国是国，党是党，党跟国都不分了，滚球

**Comment by yyqxjwxy** [comment]
@manxiaoboo 还说别人固步自封呢，笑死了

**Comment by FunkyPaladin** [comment]
Wood Head!

**Comment by luckyhiger** [comment]
搞掩耳盗铃的伎俩，不做亏心事不怕鬼敲门，上梁不正下梁歪，水能载舟亦能覆舟

**Comment by allenLew1991** [comment]
这个issue 把它close吧，楼主。 哈哈。 我们不讨论政治。 这个议题在天朝比较幼稚

**Comment by selfpoised** [comment]
傻逼，以为自己姓赵

**Comment by ZimmerWu** [comment]
小粉红已经渗透到gitgub了吗？

**Comment by manxiaoboo** [comment]
悲哀

**Comment by manchuriasun** [comment]
@manxiaoboo 我对健身教练不感冒 也不信他 不过你这种小粉红麻烦哪里来的滚哪里去

**Comment by shuozhoushi** [comment]
@manxiaoboo   五毛狗我操你妈全家

**Comment by yyqxjwxy** [comment]
@xueshaopeng 不要这么激动，淡定。

**Comment by Chinaguigui** [comment]
@manxiaoboo mdzz 五毛狗！！！有本事你去闭关锁国吧

**Comment by Chinaguigui** [comment]
@manxiaoboo 你说我们故步自封，崇洋媚外？？？狗屁！！！我告诉你，灯泡谁做的？电脑谁发明的？安卓手机谁提出来的？我告诉你，这是全球经济化的成果！有本事别用外国人做的东西！！五毛狗！！！

**Comment by yyqxjwxy** [comment]
@manxiaoboo 这货脸都被扇肿了不敢出来了

**Comment by Chinaguigui** [comment]
@yyqxjwxy 那个SB 估计被打脸了 不敢说话了

**Comment by manxiaoboo** [comment]
我说的话是有些过激，但是请你们先放下情绪，好好看看这帖子的标题，多看几遍，心里不难受么？

**Comment by yyqxjwxy** [comment]
@manxiaoboo 不难受，就觉得你很蠢

**Comment by allenLew1991** [comment]
标题是挺辣眼睛。 都比较非理性。都比较蠢

**Comment by AquaHacker** [comment]
在国外的亲戚都没回来 说生孩子给养到18 车子很便宜 加油也跟喝水一样不要钱。都是大排量 没有涡轮增压 没有限号 没有雾霾 哈哈 挺讽刺天朝的 弄了半天 还是工厂污染 跟车子没关系嘛。可是能怎么办呢。你买车子 2/3 是税。这就是你爱的天朝 每天还希望他变得更好 可是所谓的人大代表 又不是我们选的。提的意见都很奇葩。政治变的让人谈虎变色。这是一个帝国毫无疑问了啊

**Comment by manxiaoboo** [comment]
而且不是什么我被打脸我不敢出来了，我虽然不是极端的爱国爱党，但是作为一个普通人，我看见这种帖子出现在公开的平台上，就算顶着骂，我也要出来说一句。

**Comment by Chinaguigui** [comment]
国家就是国家 党就是党 中共是不是要我们中国人民乖乖去只听他们的话？说好的中国历史上的多党制？还有问题是 为什么我天天看国内新闻，却没有看到中共的丑闻，而国外的有中共的丑闻？很像不愿意让我们中国人民知道。

**Comment by Chinaguigui** [comment]
其实我是中国人 当然去爱中国，但是党呢？难道我们只能去相信党，一点不去怀疑党吗？

**Comment by AquaHacker** [comment]
这个鸡巴国家。操。安居乐业成为奢望，买不起房（SB政府也不管） 开不起车（购置税 排量税 收费的公路 ）经济早TM硬着陆了 也只有看看 新闻联播洗洗脑才会觉得能活着就是幸福，生活是什么 想都不敢想。

上网看点东西 还TM管！ 弄GFW 的那帮人 是不是 没有鸡巴！

言论 自由 民主 呵呵 真TM扯淡啊！

在国外的亲戚都没回来
说生孩子给养到18
车子很便宜
加油也跟喝水一样不要钱。
都是大排量 没有涡轮增压 没有限号 没有雾霾

哈哈 挺讽刺天朝的 弄了半天 还是工厂污染 跟车子和做饭没关系嘛。
可是能怎么办呢。你买车子 2/3 是税。

这就是你爱的天朝 每天还希望他变得更好 可是所谓的人大代表 又不是我们选的。提的意见都很奇葩。

政治变的让人谈虎变色。这是一个帝国毫无疑问了啊

让我爱国 汽车购置税、高速费先取消了吧！！

自己的历史都改的黑白颠倒的国家 没有正义可言；
胡适早都说过 蒋先生那里 民主问题 是 多少的问题；毛泽B的那里 民主问题 是有无的问题；

所以 这国家养你了？是你父母养你了！ 这国家爱你了？ 是你自己努力了！
真的爱你 干嘛让你如此艰难？ 干嘛惹得这么多人骂傻逼共匪？

我爱国 不爱党！有点脑子 别整天看新闻联播，都是报喜不报忧！等你真正亲临一些事的时候你就看到了什么是真的阴谋！不就是仗着面积大兵马多吗。但绝非正义。说别人帝国主义 资本主义 好过你国的愚民主义。

**Comment by manxiaoboo** [comment]
当然可以怀疑，但是党做的好事和成就远远大于我们所了解的那些污点，最起码的底线是我们不要在这种平台上去横加侮辱，我宁愿相信你们骂的是我，而不是国家和党。

**Comment by yyqxjwxy** [comment]
就是中国人太蠢了，像二楼那种货色占据了大多数，大概是中国人血液里就有一种奴性，但是还好，最起码老百姓还是能过上安稳日子，没有走到绝境，我们人民是有很大的忍耐力的，有一句话，穷则独善其身吧。

**Comment by xueshaopeng** [comment]
@manxiaoboo 傻逼五毛狗，看看有多少人骂你，我要是你早撞墙自尽了

**Comment by Chinaguigui** [comment]
@manxiaoboo 不，我骂的不是你这个中国人 而是党输给你的思想，只是变得麻木

**Comment by yyqxjwxy** [comment]
诸位言论不要过激，最近要开会，希望十九大后有更好的发展吧。

**Comment by xueshaopeng** [comment]
@manxiaoboo 国家，执政党，政府，这几个概念都搞不清楚，就出来咬人，脑袋秀逗了吧

**Comment by Chinaguigui** [comment]
@yyqxjwxy 额，好吧。。。但愿如此吧  其实我不想骂中国人，只是看不下去了

**Comment by xq1991** [comment]
github也被这些轮子与sb郭文贵占领了，看了你们资料，没一个搞技术的，真是cnm了。

**Comment by yyqxjwxy** [comment]
@Chinaguigui 我也想骂人，但是没办法

**Comment by Chinaguigui** [comment]
@yyqxjwxy 唉~~真担心中国的未来啊

**Comment by yyqxjwxy** [comment]
@xq1991 又出来一个五毛？，我还真不是轮子我也不是郭粉，倒是你这种货色很让人恶心，难道诸位所言不是事实？

**Comment by Chinaguigui** [comment]
又出来的是五毛？？？我看不下去了

**Comment by yyqxjwxy** [comment]
ss开发者说过，造成今天这样的局面，是中国人自己造成的。

**Comment by xq1991** [comment]
@yyqxjwxy 无毛nmb，这里是github，不是这些傻逼轮子郭文贵的地方，以前github也是被封，现在才被放出来，又想害被封》？

**Comment by qq850482461** [comment]
傻逼还有SSR,github连个仓库都没有请你滚出克,

**Comment by Chinaguigui** [comment]
够了，不要谈什么国家政治，先等蓝灯公布发出再说

**Comment by xq1991** [comment]
@Chinaguigui 中国怎么样，中共怎么样，很多人都有自己的想法，老子以前20岁左右的时候还不是以为发现个天大的秘密，震惊的要死，现在发现哪那么简单。

**Comment by Coindea** [comment]
像你们这么玩，整天瞎扯，以后github估计也得像Google那样走出去，还不如多关心关心自己的生活。

**Comment by yyqxjwxy** [comment]
@xq1991很可笑啊。github你家开的？我党开的？？意思是这里也要被管控啊，

**Comment by xq1991** [comment]
@Coindea 他们哪是什么技术人，就是一群傻逼轮子和一群郭文贵们，现在跑来github了。

**Comment by xq1991** [comment]
@yyqxjwxy 像你们这样搞只等又被封了，你们就是故意把污水引来github，还恬不知耻的天天自由民主，自由你麻痹呀。

**Comment by xq1991** [comment]
@yyqxjwxy 我也不想和你这样的多说，只想说github就做好它该做的事情，不要把污水引到这里来，去fb，youtube上引战撕逼多的是，人也多的是，别到这里来搞。

**Comment by ZimmerWu** [comment]
身边的人基本上没有翻墙的，一个个除了朋友圈就是农药，steam和youtube都很少人知道，我也曾经给别人普及过什么youtube啊，steam啊，pornhub啊，nobody cares,继续抱着自己的优酷土豆,TGP,sis不放手。漠不关心才是最大的问题，事不关己高高挂起已经是他们的行为准则了。

**Comment by allenLew1991** [comment]
@xueshaopeng 墙裂建议你 close this issue。

**Comment by Chinaguigui** [comment]
@xq1991 是的 你说没错 我们不应该在github污水引进来，只有它做好它应该的事，所以我们不应该在github谈什么国内政治

**Comment by Chinaguigui** [comment]
@ZimmerWu 我是steam游戏玩家，看着腾讯游戏我看不下去 因为腾讯认为中国人人傻钱多，例如CF 逆战 使命ol 要玩钱买武器 影响游戏玩家的体验，破坏游戏的公平性

**Comment by yyqxjwxy** [comment]
@xq1991 明确说明，这个帖子许多言论就是就事论事，没有造谣传谣，楼主标题确实过激，但是底下回帖的人没有涉及标题的事，还有你这种动不动给人扣帽子的很红卫兵有区别？我还就是搞技术的，就职一家外卖公司，国内不让说这里说说怎么了，谁都心知肚明，你说怕把github封了，意思是你也认同我党高压的言论管控了吧

**Comment by lemonskkyt** [comment]
@xq1991  郭你妹的文贵啊，我党要是不断网影响我工作学习，我压根就不知道这人，其实现在也不清楚，单单就知道这么个人，所谓君子坦荡荡，小人长戚戚，既然我党这么紧张，就算人七分假话，想必也有三分真，我是懒得听，就算知道了，分辨了真假，我一屁民也改变不了什么

**Comment by yyqxjwxy** [comment]
@xq1991 你敲你的代码去吧，你特么那句话看见我，发表反社会言论了，傻逼一个

**Comment by xq1991** [comment]
@yyqxjwxy 你一开始就扣个五毛的帽子给我，现在又扣红卫兵的帽子，很有意思？高压言论管控这个是事实，腾讯新闻的热评也是经过筛选的，共产党现在就是这么做的，你这一开始就给我扣个五毛和红卫兵的帽子和真正的红卫兵有什么区别？

**Comment by yyqxjwxy** [comment]
@xq1991 放你妈的屁，你一出来把所有人污蔑为轮子郭粉，你特么有脸说？？当婊子立牌坊？

**Comment by xq1991** [comment]
@yyqxjwxy  老子什么时候说过你反社会了？

**Comment by xq1991** [comment]
@yyqxjwxy 不是你们先污蔑人家五毛？

**Comment by FunkyPaladin** [comment]
我倒是感觉这TM就是二楼引起的，你俩就歇歇吧。反正话里话外，看着都明白是个怎么回事儿。较真就输了，不过，工作之余，骂两句缓解压力也成哈。

**Comment by yyqxjwxy** [comment]
@xq1991人家许多人是就事论事，你上来就批所有人是轮子郭粉，再者练法轮功的就不行？有喜欢郭的也不行？老子就是不批你是不是这里所有人都是轮子郭粉？？

**Comment by xq1991** [comment]
@yyqxjwxy 老子在这里不赞同你们这样的行为也不行，偏要老子骂中国，骂共产党，说中国多黑暗才能和你好好谈？

**Comment by FunkyPaladin** [comment]
当然，开这个帖子的是个什么想法就不清楚了，知道的不用看也知道，不知道的看看也不知道。所以别激动了。清楚就好，该吃饭还得吃饭，天也塌不下来。

**Comment by haoxiaofan** [comment]
这个github迟早被封

**Comment by xq1991** [comment]
@FunkyPaladin 这样的评论之前都是youtube和fb上，很多的，早已见怪不怪了，现在跑github来专门搞事情，看见心很烦。

**Comment by Chinaguigui** [comment]
都给我安静 不想github被封 就闭嘴！听说十九大开完会后，蓝灯有很可能恢复了

**Comment by yyqxjwxy** [comment]
那就关了这个issues

**Comment by xq1991** [comment]
@yyqxjwxy 轮子我是知道有自愿的，郭文贵还有粉丝我倒是不知道。

**Comment by yyqxjwxy** [comment]
我说了不想在这里谈政治，可是还有人污蔑我是轮子郭粉，真尼玛的烦

**Comment by xq1991** [comment]
总是有人想搞个大新闻，震惊！秘闻！黑暗！

**Comment by yyqxjwxy** [comment]
@xq1991再说一遍我不站立场，别你妈给人扣帽子，真是有当年红卫兵的风范。

**Comment by xq1991** [comment]
@yyqxjwxy 我没那么多帽子要扣，自己别来找帽子扣就行，红卫兵可是一群自由主义左派青年学生组成的，我想我算是偏右派的思想，所以你这个红卫兵的帽子我不戴。

**Comment by yyqxjwxy** [comment]
@qq850482461 傻逼 我就是用的ssr，有个仓库了不得了？尼玛坐我旁边的大神，连个github账号都没有，你叫唤啥，拿qq号当名称的弱智。

**Comment by yyqxjwxy** [comment]
@xq1991 行了别立牌坊了，是你说的所有人都是轮子郭粉吧。

**Comment by xq1991** [comment]
@yyqxjwxy 别急了，真的，你比较具备红卫兵的特质。

**Comment by yyqxjwxy** [comment]
@xq1991哎呦我没着急，你自己先给所人有扣帽子的，眼瞎了自己打的字看不见？，你倒是逼装的可以。

**Comment by yyqxjwxy** [comment]
@xq1991 快去撸你的代码去，别在这装逼，

**Comment by yyqxjwxy** [comment]
@xq1991 你快去首页看看，挨个儿批斗去，快去，他们都是轮子郭粉。

**Comment by ningqivip** [comment]
权力的傲慢啊，把14亿人民当猪狗啊！

**Comment by ningqivip** [comment]
5毛无处不在，

**Comment by niunaiyi** [comment]
中国这几十年的改革开放和发展，在人类历史上，你放眼去看看，有这样的存在么？中国现在发展出了一套有别于目前存在的政治体制。说独裁，但是一个国家主席，也只能执政十年，不象金家王朝。说民主，在政治上，至少是党内民主，再极端点，七大常委里是民主的，也是有制衡。简单来说就是：一党独裁，党内民主。这种政治体制，即是创新，也是最符合我们国情的。无论任何政治体制，能让老百姓安居乐业，这就是好的政治体制。是的，我承认共产党是比普通群众享受很多利益，可是你也可以入党呀，也可以加入体制，成为体制内人呀。这一点，我相信政府没有做任何针对性限制，是自由的。话说回来，我不认为共产党是个执政党，反而象一个国家的执行党，就象公司的管理层一样。只要员工生活好了，管理层享受点优待，也是无可厚非的。
我们走自己的路，为什么一定要走别人的路，才能说是正确的呢？民主、自由，我不认为这是我们当下需要解决的问题。就我个人判断，我觉得反正是一种工具。伊拉克、叙利亚、利比亚，在这些国家，民主、自由就是被别人拿来当枪使的实验场。
回到我们的出发点，翻墙。蓝灯翻不了墙，有时候并不一定是政府弄的，也有很大可能是技术问题。就算是政府弄的，那又怎么样呢？美国没有网络管制？俄罗斯没有网络管制？政府做了控制，而不是禁止。政府三峡都建成了，难道没有办法禁止翻墙？
邓小平说过，打开窗子，苍蝇蚊子都会进来。你们家打开了窗子，但是也要加个纱窗，道理是一样的。
