### ISSUE TITLE
百度什么时候封锁的plex vpn的？

### ISSUE THREAD

**Issue by wlj123456** [getlantern/forum#4729]
在百度上搜索*** vpn全部提示无内容；
https://www.plexplan.com/?invite_code=Z6ZPUG
plexplan也搜索不到了

**Comment by xiguataida** [comment]
https://www.plexplan.com/register?invite_code=ZGYWUB
跟帖发一波，使用我的邀请码免费试用24个小时

**Comment by wycfg** [comment]
就刚才吧，我的不能用了

**Comment by laozhuorun** [comment]
用不了啊

**Comment by wlj123456** [comment]
百度节奏跟的真紧，VPN被封怎么大的事情，网络上全部都搜索不到！最早的新闻居然是2015年的，也是醉了。
