### ISSUE TITLE
plex好像可以用，点我领取一天试用啊

### ISSUE THREAD

**Issue by hikajshd** [getlantern/forum#4730]
我抱着试试的心理，发现真的可以用。

https://www.plexplan.com/register?invite_code=ZGBCUK

**Comment by xiguataida** [comment]
https://www.plexplan.com/register?invite_code=ZGYWUB
跟帖走一波，用我的邀请码免费使用24小时

**Comment by laozhuorun** [comment]
用个毛 ，一群托

**Comment by hikajshd** [comment]
我真不是托，我开了一年的灯，一个月还没有用上，现在就出问题了。这个能将就用，我先用着喽。。等灯可以用了，就继续用喽

**Comment by laozhuorun** [comment]
截个图看看，为什么开了plex vpn，但是上不了google

**Comment by hikajshd** [comment]
![tim 20171011095339](https://user-images.githubusercontent.com/32691831/31418683-1a01bb90-ae6a-11e7-92e1-fbbf7bd12325.png)
可以用谷歌，好吧。。

**Comment by laozhuorun** [comment]
电信表示用不了

**Comment by hikajshd** [comment]
哈哈，这我就不是很了解了。。我也是抱着试试的心理。。先观望喽

**Comment by NewZean** [comment]
https://www.plexplan.com/register?invite_code=ZH2KUM
真的可以用啊，用我的邀请码免费使用24小时
