### ISSUE TITLE
PlexVpn亲测可用

### ISSUE THREAD

**Issue by laozhuorun** [getlantern/forum#4745]
https://www.plexplan.com/register?invite_code=ZGHJUI

![image](https://user-images.githubusercontent.com/5772553/31419095-56b84430-ae6c-11e7-9133-b20554b8ff07.png)

**Comment by kimomoki** [comment]
这个有没有人说明一下是不是钓鱼用的？

**Comment by 1123362286** [comment]
反正卡巴斯基查了有木马，有人说用eset 查了没有，自己注意吧

**Comment by laozhuorun** [comment]
反正能 熬过十九大就行，管他呢

**Comment by laozhuorun** [comment]
windows下就要，其他的不需要

**Comment by AngarajaKarna** [comment]
卡巴查有木马的
