### ISSUE TITLE
今天蓝灯已经出新版了，可以直接翻墙。不会被拦截。

### ISSUE THREAD

**Issue by XIONGJUNHAN** [getlantern/forum#4746]
今天蓝灯出新版了。可以直接翻墙。不会被拦截。速度很快。

**Comment by TongFangyuan** [comment]
是吗, mac 的?

**Comment by allenLew1991** [comment]
啊于乌细哦，耐米踹

**Comment by BDevonce** [comment]
哪里啊？ 你不会说的还是4.1.2（20171006）那版吧？

**Comment by dennyx** [comment]
windows10 Lantern 4.1.4 (20171010.172159) 连接不上，一直显示连接中

**Comment by Supergamefan** [comment]
说出来你们可能不信 我用了4.1.4 连这个论坛都打不开了。要关了才能打开

**Comment by allenLew1991** [comment]
然并卵

**Comment by BDevonce** [comment]
起码人家在尽力尝试

**Comment by libibin** [comment]
发标题的能不能走点心，你告诉我怎么可以用了。你发个截图出来让大家看看。无聊人真多

**Comment by buddyfly** [comment]
4.14也不能用

**Comment by ashuang001** [comment]
这个说得对.起码lantern团队是尽力在做.一家公司对抗一个国家也挺不容易的.呵呵 
加油吧.最近大家都知道是非常时期,多些宽容吧.

**Comment by XIONGJUNHAN** [comment]
今天更新了安卓版，新版为4.1.4 (20171010.155235)

**Comment by wzc1076** [comment]
还是卡，还是不能用，蓝灯4.1.4（20171010）的

**Comment by ningqivip** [comment]
卡成狗
