### ISSUE TITLE
用了很多翻墙觉得蓝灯还是方便，选择了购买，可是速度能再快一点吗？

### ISSUE THREAD

**Issue by Huamei-Du** [getlantern/forum#475]
第一时间就买了，结果速度跟免费版是一样的，油管不到300k。。有没有官方人员正面交代一下~谢谢

输入我的邀请码 # **YLYP9H** ，额外获得三个月的蓝灯专业版！

**Comment by p3rcya** [comment]
请上传log，谢谢。 我们会尽快修复

**Comment by hnjdy** [comment]
我不购买专业版，输你的邀请码也有3个月专业版送？

**Comment by p3rcya** [comment]
@hnjdy 不是。必须购买才能获得

**Comment by Huamei-Du** [comment]
@p3rcya 
论坛上传了几次失败 传360了 麻烦看一下https://yunpan.cn/OcBS6xEjsCd3u7  访问密码 425f

**Comment by p3rcya** [comment]
正在解决

**Comment by NAVrasZ** [comment]
电信的么2233，我以前也这样，封得比较严改移动了
另外换下DNS

**Comment by Huamei-Du** [comment]
@p3rcya 我邮箱dusw1205@qq.com 变成30k/s速了！！伤透了卧槽

**Comment by Huamei-Du** [comment]
[lantern.zip](https://github.com/getlantern/forum/files/357522/lantern.zip)

**Comment by p3rcya** [comment]
正在解决
