### ISSUE TITLE
【目前能用最快的】

### ISSUE THREAD

**Issue by justinpp** [getlantern/forum#4758]
ios 安卓 mac windows 都可以 windows 4k ios 1080p 原本是灯笼备选 知道的没几个 有意联系q 1262200959 有缘的给 无缘收费 不好用欢迎下面爆破。

**Comment by AquaHacker** [comment]
MacOS 来一发

**Comment by justinpp** [comment]
目前不在电脑旁 只有exe文件在手机里

**Comment by justinpp** [comment]
windows系统可以考虑联系

**Comment by justinpp** [comment]
算了 我还是独乐乐吧😂
