### ISSUE TITLE
请不要在这里讨论政治问题，保留技术论坛的纯洁性

### ISSUE THREAD

**Issue by treenewwindy** [getlantern/forum#4770]
政治问题大家都关心，但这里不是合适的地方，否则只会带来更多不便。

想要知道世界的真相，可以多看，多听，多思考。在觉得自己弄清楚了之后，更重要的是行动。

在这里打嘴炮屁用也没有，只能添乱。

**Comment by WoNangbang** [comment]
You're right, but  it can unite us.

**Comment by yyqxjwxy** [comment]
同意

**Comment by ApocalypseWolf** [comment]
然而大多是在这里讨论政治问题的人都并不会听这些话（

**Comment by xq1991** [comment]
@ApocalypseWolf 是的呀，只能呼吁而已。

**Comment by kimomoki** [comment]
你这话说的一点政治水平都没有，我就问你翻墙本生是不是政治？

**Comment by tinghaode123** [comment]
翻墙真不是为了政治，就是看看电影，包括大的和小的，在学习点知识，这个国内的网站广告时间太长了

**Comment by zhangbodhr** [comment]
既然在这里打嘴炮屁用没有，那你这个屁一样的贴子自己删了吧，别给大家添乱了。

**Comment by wankaiss** [comment]
@kimomoki 你要知道以前可是吧github都给墙了的。好好珍惜吧，关键时期就老老实实的吧

**Comment by ALT34555** [comment]
@kimomoki  首先，网络屏蔽是每个国家都存在的，有些网站甚至会主动拒绝来自某些区域的ip访问，只不过我们这边太高了，影响到了我们的学习和工作。
其次，翻墙、vpn出现的比gfw早得多。
那么，请你再说一遍，翻墙属于技术板块还是政治板块？

说实话，我觉得把这些政治神经病都打爆，说不定墙自然就倒了(ㅎ‸ㅎ)

**Comment by ApocalypseWolf** [comment]
@ALT34555 而且我记得GFW最初的目的是防止境外黑客吧

**Comment by zhangbodhr** [comment]
@ALT34555 一边用着翻墙软件一边给GFW洗地，你妈是不是螺旋升天爆炸了，导致你精神如此错乱？
能不能用时光机器回到过去，让你爹不要碰你妈，通过保持你妈的纯洁性，防止你这种傻逼的出生，来保证这个世界的纯洁性？

**Comment by wankaiss** [comment]
@zhangbodhr 没必要这样吧？这种言论是我在twitter（民猪人士）才能看见的。讨论技术上升层次后就真的危险了。

**Comment by zhangbodhr** [comment]
@wankaiss 你这种话都说不明白的语文水平，我只在蠢猪人士身上才看见过。你用翻墙软件，你国警察说不定已经在抓捕你的路上了，还关心网站危不危险，你是猪交配生出来的吧？

**Comment by ALT34555** [comment]
@ApocalypseWolf  
GFW全称Great Firewall of China，方滨兴本来搞这个一方面是防止境外黑客，一方面是防邪教，那个时候大家的文化水平不是很高，轮子挺猖狂的……相信很多人都有“下载个东西/点个链接就跳进轮子站”的经历。
方先生的初衷实现得不错的，好几次境外的大面积电脑病毒问题都没影响进来。
不过后来，方先生出于种种原因，把墙越搭越高……
再后来吧，方先生给人下了，然后这墙呢，也……

**Comment by zhangbodhr** [comment]
@ALT34555 当初搞GFW，就是为了屏蔽境外网站的，防你妈逼的黑客。傻逼五毛，你给GFW洗一次地，你亲妈过马路被压死一次。

**Comment by ALT34555** [comment]
@wankaiss  说真的，我这几天上推都觉得清静了很多，反正我现在在学校，有教育网专线用……
我关注的话题又是转基因这种国内比较敏感的，每次看评都有KY在人家学术新闻下面说胡话，无一例外繁体中文（笑）
当然我是不支持把GFW搭这么高的，毕竟我在家用不了学校的专线……

**Comment by wankaiss** [comment]
@zhangbodhr 你不就想证明你移民出去是正确的么？很可惜，中国会让你这种狗失望的。赶紧去领狗粮吧，而且你这种人一辈子都是这种德性的。

**Comment by kimomoki** [comment]
@ALT34555 哈哈哈，洗脑成功，恭喜你获得自干五的称号! 公公您吉祥!

**Comment by zhangbodhr** [comment]
@ALT34555 我还不支持党员轮奸你妈呢，有用吗？

**Comment by kimomoki** [comment]
@wankaiss github封了才好，你们这些抱有侥幸心理的人才知道情况有多严重，觉得有个github就在安全区了。早知道如果你还需要蓝灯，你和所有人都在一条船上

**Comment by zhangbodhr** [comment]
@wankaiss 这么爱你国就别翻墙，你翻一次，八千万党员轮奸你妈一次，不谢

**Comment by treenewwindy** [comment]
泛政治化令人厌恶。
来这里的人很多只是为了查资料，找文献，或者只是为了追剧，购物，或者为了方便与客户联络。
这里只是探讨技术问题的地方，反馈信息，解决技术问题。至于来这里的每个人要翻墙出去做什么，与这个论坛无关。

**Comment by ALT34555** [comment]
@zhangbodhr
真希望能把你物理断网了，好防止你出去丢人现眼。如果你认为你有道理，请分条举例，证明你的观点，而不是像文盲一样叫骂。

**Comment by wankaiss** [comment]
@ALT34555 实在想不到这种人脑子怎么想的，估计是台巴子觉得大限将至了吧。@zhangbodhr github不需要翻墙。也就是互联网你跳这么欢，真想见见你本人什么样，不想斗嘴。

**Comment by zhangbodhr** [comment]
@ALT34555 可惜你没法给我物理断网，你党倒是快给你物理断网了，你还得给他洗地，活活气死你个臭傻逼。

**Comment by zhangbodhr** [comment]
@wankaiss 快别翻墙了，你亲妈今天被轮奸几次了？

**Comment by ALT34555** [comment]
@zhangbodhr   不好意思，本高级知识分子有专线（笑）

**Comment by wankaiss** [comment]
@zhangbodhr 看了你的contribute， 你既然在中国为何还这么跳呢？你回日本不就好了么？你好，我已截图。@ALT34555 我看了他的contribute，他应该是台巴子或者日本拍过来的。一起举报吧

**Comment by zhangbodhr** [comment]
@ALT34555 你好好用专线，千万别用蓝灯这些翻墙软体，也别出现在这些软体的论坛上，不然你亲妈爆炸就不好了是不是？

**Comment by wankaiss** [comment]
@ALT34555 看到软体我就知道了， 原来是在大陆要饭的台巴子。搞不懂为何要用简体（台巴子口中的残体）。这种人真的是很贱，既然不愿意就滚回去咯？正在扒这个台巴子的背景，要是在大陆做生意微博得曝光。

**Comment by zhangbodhr** [comment]
@wankaiss 呵呵，老子确实在大陆做生意，你有本事来举报我呀？微博ID：带带大师兄

**Comment by zhangbodhr** [comment]
@wankaiss 不举报你是婊子养的

**Comment by wankaiss** [comment]
@zhangbodhr 你何必呢？你弄带带大师兄有意思？你把你真的微博id拿过来。你充其量一个打工的台巴子。台巴子一贯的嘴炮确实遗漏无疑。

**Comment by AquaHacker** [comment]
不谈政治的国家 是 怎么样的国家？都不关心自己国家的政治的人们 是怎样的人们？

**Comment by Iriasu** [comment]
@wankaiss https://public.lightpic.info/image/0D20_59DDAB650.jpg

**Comment by AquaHacker** [comment]
保留技术论坛的纯洁性 哈哈 你纯洁就不会被共匪干吗。。。。

**Comment by wankaiss** [comment]
@Iriasu got it!loool

**Comment by zhangbodhr** [comment]
楼主，我建议你爸保持你妈的纯洁性

**Comment by ALT34555** [comment]
@zhangbodhr
说来惭愧，我的五毛还是昨天才发下来的，自己去跟老板说才领到五毛呢，不然我只能等灯亮喽。

@AquaHacker
前有推特治国，后有gitHub治国，佩服佩服，祝您早日实现自己的政见。

**Comment by zhangbodhr** [comment]
@wankaiss @@ALT34555 看到你们这俩头傻逼的上窜下跳，我深深的觉得党的GFW是一个伟大的发明创造，在这一点上咱仨达成了共识。但分歧也有，就是你们觉得GFW太高，我觉得GFW还不够高，起码没有高到阻挡你们这种傻逼在墙外的世界放屁拉屎，这违背了方滨兴先生的初衷，不是么？

**Comment by zhangbodhr** [comment]
@ALT34555 我觉得你算是个聪明人了，起码拿了五毛，有的二逼不拿钱还要当五毛，这种傻逼是不是遗传的？

**Comment by yyqxjwxy** [comment]
哎说实话阻止翻墙和普通老百姓没啥关系，苦了我们这些做技术的了，和做外贸的，其实普通人翻个墙就是有关推特fb也没别的

**Comment by anticpc** [comment]
#4660

**Comment by anticpc** [comment]
@AquaHacker 我朝民众多数陷入基本生活满足中苟延残喘，此乃饥荒政治

**Comment by 6726** [comment]
世界上只有四个国家不能连接国际互联网，这四个国家是猪国、朝鲜、伊朗、古巴。

你愿意待在你的猪 圈里老老实实做一只猪没人说你，但是你翻出猪圈后还像圣母婊一样替主子辩护，要求大家安静的做猪，这样以后就没有猪圈——这种斯德哥尔摩综合症的弱智逻辑，是可忍孰不可忍！

**Comment by yyqxjwxy** [comment]
说的对

**Comment by yyqxjwxy** [comment]
@6726 许多人就是这样的

**Comment by xq1991** [comment]
@6726 老子住的才不是猪圈，老子也从不说自己的国家是猪圈，你有本事在这里大放阙词老子就有本事怼你。

**Comment by xq1991** [comment]
@yyqxjwxy 又是你，你自己是猪国不要带上我们。

**Comment by yyqxjwxy** [comment]
@xq1991 真的是疯狗哪都咬，你爹理你了么咬你爹。人家说诸国就是反讽一下，看你这高潮劲儿，红卫兵一个，不是喜欢敲代码吗去撸你的代码闲的你麻痹一样到处咬人

**Comment by xq1991** [comment]
@yyqxjwxy 你这种才是有病，上面哪个数字账号明显是个HK，或者湾湾，他这种完全不是具有建设性的评论，还一个劲的叫好，真是有病。

**Comment by 6726** [comment]
祖国和猪国是谐音，既然是谐音，就通用一下。而且又可以起到一个隐喻。

还有，我是中国人哦，绝不是HK和湾湾

**Comment by xq1991** [comment]
@6726 那你说点实用的么？说一些乱七八糟没建设性的东西有意义？中国有黑点，你要黑就得指出你想黑的点来，不要一开始就噼里啪啦的全部中国人怎么怎么样。
网络封锁这个事情，政府这方面做的太过分了，这你完全可以黑，tmd开个会封锁的这么严用力太狠了。

**Comment by beboyss** [comment]
@ALT34555 @zhangbodhr
gfw这东西就不该有，什么太低太高，真特么逗，多高算高？多低算低？给一个错误的东西定义数量级？不是很高就可以合理化了？
我打个比方，以后强奸的规则改了，插进去5厘米不算强奸，因为有些人认为这不算太长，因为可能还没碰到处女膜！！！
五毛自干五你看我说的这个可以洗一波gfw不？

**Comment by Guoyuh78** [comment]
明年二月 提灯上街

**Comment by zhangbodhr** [comment]
@xq1991 “自己的国家”？搞笑了，你哪来的国家？你也配姓赵？这是老赵家的国家，你只是这个国家里的一头等着为赵家做贡献的肉猪罢了，谁给你的自信和赵家平起平坐了？你是有选领导人的权力，还是有房子不被强拆的权力？你只是一头猪，OK？

**Comment by nittup** [comment]
政府权力没有边界就是这样，随意剥夺人获取咨询的权力，有些东西没得洗。

**Comment by yyqxjwxy** [comment]
@xq1991 看你的言论越来越觉得你是煞笔，敢问你多大，毕业了没，人家只不过反讽而已又给人家扣香港和台湾的帽子，香港台湾怎么了人家不认同大陆怎么了？弱智一样简直，一看就是民粹分子，小粉红一个。

**Comment by xq1991** [comment]
@zhangbodhr 噢，那你又是哪个国家的赵姓子民呢？你又在为哪个国家献祭你自己的猪肉呢？你是选了哪个领导人了？你是在哪里买房子了？

**Comment by xq1991** [comment]
@yyqxjwxy 在我看了你也是傻逼，反正咱俩互看不顺眼，你不累就继续。

**Comment by yyqxjwxy** [comment]
@xq1991 我还真的累不该惹你这条狗啊。还搞技术呢尼玛培训班出来的吧

**Comment by yyqxjwxy** [comment]
@xq1991 傻逼小粉红你继续

**Comment by xq1991** [comment]
@yyqxjwxy 什么培训班？哪个厉害你介绍我个？虽然培训班大部分都是无脑混子型，但也有厉害的。

**Comment by xq1991** [comment]
@yyqxjwxy 我在12年时还是比较震惊于所谓的什么大新闻，大内幕什么的，但也没到你这种程度。可怜你也是找不出什么论据来搞我，只会一口一个小粉红，虽然我没什么知识呀，但是去知乎上面逛一逛有千万种方法怼你这种人。

**Comment by wankaiss** [comment]
坐等github泛政治化，然后被墙掉。一大帮twitter的民猪人士正在到来，几乎被twitter化

**Comment by yyqxjwxy** [comment]
@xq1991 哈哈需要论据吗，行了别说话了，让我笑会

**Comment by yyqxjwxy** [comment]
@xq1991 价值观不认同就滚得远远的，非要和不同价值观的人杠，这不是疯狗小粉红本质？

**Comment by xq1991** [comment]
@wankaiss 被怼了好久呀，不明白为什么他们转战Github了，难道就因为GitHub解禁了吗？

**Comment by yyqxjwxy** [comment]
@xq1991 老子你妈在这里回复他早不和你杠了，你也要过来咬，这不是疯狗？

**Comment by xq1991** [comment]
@yyqxjwxy 蛤蛤蛤，不是你们这群人先惹起来？退党保平安类似的骚扰？

**Comment by zhangbodhr** [comment]
@xq1991 既然你知道自己不姓赵，只是一头肉猪，怎么还给赵家洗地？你是纯粹的傻逼吗？

**Comment by xq1991** [comment]
@zhangbodhr 老子才不替什么赵家洗地，要洗你去洗。

**Comment by yyqxjwxy** [comment]
@xq1991 弱智你要能找出来我说过退党的话我算你牛逼，真特么意淫的可以，别来丢人了，头脑简单的货色别人发表不同的价值观就是反党反动派，看来你自带红色基因。

**Comment by zhangbodhr** [comment]
@wankaiss 你党墙了那么多网站，你有没有放一个屁？没有！现在是小粉红和五毛狗发的这个洗地贴，我们正义人士看不惯被动来怼你们，小粉红把GitHub可能被墙的屎盆子往正义人士头上扣。那么请问，小粉红和五毛狗有母亲吗？没有！有也早死光了，这帮逼亲妈不爆炸，朝鲜六级地震哪来的？

**Comment by xq1991** [comment]
@yyqxjwxy 就像你说的一样只是类似的比喻手法，我也就是拿类似的比喻碰到陌生人就退党保平安这样的人来比喻你。

**Comment by zhangbodhr** [comment]
@xq1991 你没给赵家洗地，你妈是怎么爆炸的？这明晃晃的事实你能否认？事实你们都否认，你们小粉红五毛狗还有人性吗？

**Comment by xq1991** [comment]
@zhangbodhr 老子没入党，团员都不是（初中时被班主任踢了），自称正义人士的“正义人士”好厉害噢。

**Comment by xq1991** [comment]
@zhangbodhr 一个劲的攻击家人，真不愧是火力爆炸的“民主奋斗者”。

**Comment by yyqxjwxy** [comment]
@zhangbodhr 原来是混混一个别去理他，这种脑残太多，没啥思想，头脑很简单。

**Comment by zhangbodhr** [comment]
@xq1991 你亲妈爆炸也只是个比喻的手法，你妈实际只是高位截瘫

**Comment by xq1991** [comment]
@zhangbodhr 嗯，好厉害，可惜你也之是个嘴炮。

**Comment by xq1991** [comment]
@yyqxjwxy 日子过的太平庸，也算混子吧，毕竟不像各位“民主人士”的光辉人生。

**Comment by zhangbodhr** [comment]
@xq1991 我只是打一个比方，你可以打比方，我就不能打比方？你为什么只盯着那些细枝末节，对我其他的正义言论视而不见？

**Comment by xq1991** [comment]
@zhangbodhr wow，“正义言论”？？？？我们这没人这么厚脸皮的噢，自称正义。

**Comment by treenewwindy** [comment]
楼歪了，打嘴炮有意思吗？

**Comment by 6726** [comment]
@xq1991 你那个不是比喻，你那是污蔑、扣帽子。人家不满赵家封墙锁国，你就说人家是湾湾港灿轮子民逗

说朝鲜、祖国是猪国，这种才叫比喻。

什么叫纯洁性？美国人可以在twitter、facebook总统主页上辱骂总统，赵国人连在国外网站讨论问题都变成政治性？变成不纯洁？

深入骨髓的奴性啊，太监也不过如此！

**Comment by 6726** [comment]
什么叫纯洁性？美国人可以在twitter、facebook总统主页上辱骂总统，赵国人连在国外网站讨论问题都变成政治性？变成不纯洁？

深入骨髓的奴性啊，太监也不过如此！
