### ISSUE TITLE
建议有人创建一个论坛，提供我们讨论和吐槽，包括VPN，GW，==

### ISSUE THREAD

**Issue by yungs2017** [getlantern/forum#4771]

**Comment by ZimmerWu** [comment]
偷偷记下IP一锅端还不稳？哈哈

**Comment by HelloXiaoxi** [comment]
你tm想集体收快递查水表吗？

**Comment by yungs2017** [comment]
哈哈，肯定要海外服务器，连vpn，起码要比在这里好吧

**Comment by 6726** [comment]
不要讨论，在国内讨论vpn翻墙的就会被查水表，这几天发生好多这种事了，好多人被抓

**Comment by johnhackett34** [comment]
蓝灯坏了以后我就下载了这个PlexVPN，比Astrill, Lantern, 和 ExpressVPN 都好用。推荐

[https://www.plexplan.com/dashboard/register?invite_code=ZG62UW]

**Comment by tianyuanli** [comment]
建设在国内，被一锅端。
建设在国外，vpn都挂了，还怎么上
