### ISSUE TITLE
苦的还是我们这些做外贸的吧 要做谷歌搜索引擎推广， 社交平台视频推广等都没法做了 

### ISSUE THREAD

**Issue by lucasat7startent** [getlantern/forum#4800]
RT..  我们老老实实做出口为国家创收外币啊，  如果以后所有翻墙都封了 很多中小型国际贸易企业要死掉啦。。。

**Comment by fjsiineo** [comment]
兄弟还是用收费的express吧，免费的怕被钓鱼。虽然贵了点买一个月先扛一下，蓝灯19大后也许会好点儿。express是美国最大的vpn公司，一直表现都很很稳定；不是不支持蓝灯只是蓝灯最近太不靠谱了，作为三年的老用户这些天有些失望。express的下载地址：http://www.expressrefer.com/refer-friend?referrer_id=14202793&utm_campaign=referrals&utm_medium=copy_link&utm_source=referral_dashboard

**Comment by lhsshl** [comment]
这么干人多地广的国家在国家安全和科技人文发展上也权衡不出个万全之策

**Comment by lhsshl** [comment]
这么个人多地广的国家在国家安全和科技人文发展上也权衡不出个万全之策
