### ISSUE TITLE
定点黑蓝灯。活该！

### ISSUE THREAD

**Issue by noodlespan** [getlantern/forum#4801]
几天了，一直连不上去。至少你要确保商业用户能正常使用，不管用什么方法，那怕借别人VPN给我们用。
老子还有两年年费在里面，可惜了！

**Comment by temnia** [comment]
商业用户为什么不自建线路

**Comment by cweijan** [comment]
我买了两年才用了1个月,气死了

**Comment by wenruan999** [comment]
plexplan.com/register?invite_code=XQC7UH …此款vpn一直可以使用，注册可免费使用一天，看1080p视频无压力

**Comment by wenruan999** [comment]
https://www.plexplan.com/register?invite_code=XQC7UH此款vpn一直可以使用，注册可免费使用一天，看1080p视频无压力

**Comment by noodlespan** [comment]
@wenruan999 屌，能试用一个星期不？

**Comment by noodlespan** [comment]
蓝灯 @angelwithout  到PlexVPN去借个账号给我用.

**Comment by TongFangyuan** [comment]
我蓝灯续费了一年,国庆回来发现用不了,真尴尬,

推荐下这个,[稳定](https://www.plexplan.com/register?invite_code=ZHZHUK),可以免费试用
可以作为暂时替代方案,买了一个月,每天都得查资料

**Comment by noodlespan** [comment]
毛，你们都在广告，plexplan 试用都用不了。

**Comment by noodlespan** [comment]
plexvpn 技术也是水货.

**Comment by VCDVD** [comment]
@wenruan999 呵呵，不怕死的可以去用plexvpn，公司是北京的，网站是备案过的，竟然还用QQ群联系。
