### ISSUE TITLE
https://www.plexplan.com/register?invite_code=XQC7UH此款vpn一直可以使用，注册可免费使用一天，看1080p视频无压力

### ISSUE THREAD

**Issue by wenruan999** [getlantern/forum#4802]
https://www.plexplan.com/register?invite_code=XQC7UH此款vpn一直可以使用，注册可免费使用一天，看1080p视频无压力

**Comment by wenruan999** [comment]
说明一下，不是非要花钱买，可以免费使用一天 ，解决暂时翻墙问题，问题是一点不卡。蓝灯加油，快点好了，大家就不用买其他vpn了。关键这个临时注册的可以使用24小时不卡，还可以看720p以上视频不卡。免费一天。不一定要花钱买，不一定非要花钱买，不一定非要花钱买。

**Comment by zyq7374** [comment]
哪条线，要不连不上，要不卡得爆炸

**Comment by wenruan999** [comment]
新加坡节点问题不大，效果好

**Comment by VCDVD** [comment]
呵呵，不怕死的可以去用plexvpn，公司是北京的，网站是备案过的，竟然还用QQ群联系。

**Comment by noodlespan** [comment]
https://www.plexplan.com 没法用

**Comment by noodlespan** [comment]
我是android的

**Comment by mlican** [comment]
会盗号

**Comment by dcdb723** [comment]
别tm逗了,慢的一B,我已经试过了

**Comment by chen5502** [comment]
没人担心这是个陷阱？反正我是不敢用的。

**Comment by wenruan999** [comment]
速度还可以，用了第二天了！https://www.plexplan.com/register?invite_code=XQC7UH此款vpn一直可以使用，注册可免费使用一天，看1080p视频无压力
