### ISSUE TITLE
建议大家不要在Github讨论敏感话题了，至少这几天不要

### ISSUE THREAD

**Issue by dct328** [getlantern/forum#4818]
我不是五毛也不是美分，只是为Github在中国的前途表示担心。我们需要做一步想后面的三步，而不是做一步后获得暂时的满足，把后面的道路都堵死了。你们在Github讨论敏感话题，如果Github被永久的封了，那我们不彻底玩完了？之前Github不是没有被封过。

我对政治不感兴趣，只是希望上国外网站查找资料

**Comment by beboyss** [comment]
顶

**Comment by sschern** [comment]
同意。。顶！！！！！

**Comment by ovoff** [comment]
是这样的，绝大多数被墙网站也是指简单的开放言论被反动利用而已。
不谈政治。

**Comment by dct328** [comment]
我觉得能不能暂时的把Lantern的东西从Github删除，开完会再说？

**Comment by MosesXY** [comment]
支持。

**Comment by TieChi** [comment]
希望大家在任何地方，即使墙外（肉身翻墙除外）谈论相关话题遣词造句都留个心眼。老大哥在看着你~~~~~~

**Comment by zhangbodhr** [comment]
自我阉割，不赞同。什么算敏感话题，翻墙算不？上面已经有人建议把蓝灯移出GitHub了，脑子有病吧？墙肯定会越来越高，GitHub被封只是时间问题。不如多开启民智，如果老百姓都知道自由的好，而不是主动给xxx当狗腿子洗地，那墙被推倒不是顺理成章的事？东德的例子不远吧？

**Comment by zhangyang412** [comment]
可拉倒吧 东德能像老共这样把一个落后农业国带成世界第二？政府垃圾你当然可以推，你当领导做得比老共好你也可以推。  啥都没有你穷瘠薄叫唤啥

**Comment by Lather0519** [comment]
傻逼楼主，人家是推墙，你个傻逼倒好，还维护。你不要翻墙了，缩在你的五亩三分地自己当满奴的狗去

**Comment by AllenBrook** [comment]
楼主既然这样还上GitHub干嘛，直接百度360去就可以了，让删除蓝灯？
你这态度，就是在自由的美国也能被你培养出一个毒菜的CCP

**Comment by beboyss** [comment]
跑味儿了呢，干脆把发表政治言论的都埋了，然后zf就自己把墙推了？

**Comment by beboyss** [comment]
你自己吧这个话题关了吧，可能你本意是好的，但你实际在引战

**Comment by dct328** [comment]
我上Github的目的是下载代码，查看代码，不是其他目的。百度360做这个？
硬干是没有用的，我们这几天不要干了，以后重新开始

**Comment by zhangbodhr** [comment]
@zhangyang412 是老共把十三亿人带成了世界第二，还是老共拖累十三亿人只能当世界第二？
五毛狗先死个妈再来发言，操你妈了个逼。

**Comment by hudson6666** [comment]
这里有些言论真的让我学到很多 不仅开始让我觉得墙是有积极意义的 甚至让我开始觉得大学必修政治课是有积极意义的……唉

**Comment by hudson6666** [comment]
有的人真应该找个大学旁听下中国近现代史、唯物辩证法 然后回小学或者会自己父母那学学怎么说话再到墙外来丢人
>------------------
我看到你用汉字在 GitHub 上说那样的话都觉得丢人

**Comment by ZimmerWu** [comment]
讲道理，我感觉我从小到大的政治老师也好讲师也好教授也好，没有人信自己在课堂上讲的那套说辞的。

**Comment by hudson6666** [comment]
你学东德你能带领我们奔世界第一么 总算是见识了一把什么叫国外反华势力（不然就是被国外反华势力洗脑）也总算领会了越翻墙越觉得墙有必要 越觉得开发翻墙工具让人心寒 觉得翻墙门槛提高反而是好事

**Comment by hudson6666** [comment]
@ZimmerWu 那些编纂的夸辞不一定对 但辩证法是真理

**Comment by ningqivip** [comment]
盗国賊已经彻底疯狂了

**Comment by ningqivip** [comment]
自干五
