### ISSUE TITLE
关于近期这些事我的一些看法

### ISSUE THREAD

**Issue by Hanwen666** [getlantern/forum#4829]
九月初买了一年的，邀请码被别人使用了，现在还剩下15个月。

怎么说呢，毕竟得开这么大的会议了，出于安全角度考虑，这么做也不是什么坏事。
想想隔壁老金统治的国家，fq恐怕得被枪毙的，咱们虽然有GFW，但如果想要到国外网站找点资料什么的还是没有问题的。现在大家都懂的，敏感时期嘛，相关部门这么做也是怕出事，毕竟是自己的祖国，如果出了事对国家、对每一个人来说都没有好处。所以还是希望大家稍作理解，忍一忍吧，忍个俩周。

当然，我不希望看到大会结束之后依旧没有恢复正常（呵呵脸）

**Comment by waysd7** [comment]
我的天呢，你大学时递交过入党申请书吧？

**Comment by godera** [comment]
技术不行，因噎废食。虽然如此，但还是希望过了大事后恢复

**Comment by paraparapa** [comment]
斯德哥尔摩综合症

**Comment by bigsyw** [comment]
封网其实是惯例，2008年奥运会就有了，天涯的报道：
　　　　本报记者了解到封网是业内惯例，全国两会、党的代表大会等重要活动举行时，都会进行这样的操作。今年2月29日，一家IDC公司就曾给客户发出“封网” 通知：“接电信和网通机房通知，因我国人大和政协‘两会’将于2008年3月份召开，国家相关部门考虑到信息安全的问题，故规定电信行业必须对电信级机房进行封网。”“因3月份‘两会’召开和8月份第29届奥运会的举办，全国机房将可能会陆续进行封网，我司会在接到通知后第一时间通知您。”

**Comment by ashuang001** [comment]
这个期间这个状况其实可以预见的.
至于以后还能不能用就不好说了.就目前来看,技术上封堵lantern已经是豪无疑问的了,就看封堵的成本有多少了.如果封堵成本很高,那么估计会后会放宽 ,也就是说,lantern还有恢复的可能 .如果封堵得成本非常低,,那么lantern如果不自寻出路的话,估计就再没有点亮得那一天了.希望 不要出现最糟的情况.毕竟我也是两年的用户,才用了很短时间.

**Comment by abc159487** [comment]
这孩子是没救了。权利都是抗争来的，你都开水里的蛤蟆了还等着天上掉馅饼？还好意思和朝鲜比，到时候怎么死的都不知道

**Comment by Tsohg85** [comment]
嗯…等狼吃饱点，它就吃素了…
这孩子没救了…喂狼吧…

**Comment by huhuda** [comment]
开大会为什么要封网，感觉逻辑上不通啊，是我读书少啊！

**Comment by ZimmerWu** [comment]
防止舆论的产生，舆论是一个群体产生的标志。

**Comment by panrenjie366** [comment]
在封闭的环境里缺少独立思考能力

**Comment by e2889e** [comment]
> 当然，我不希望看到大会结束之后依旧没有恢复正常（呵呵脸）
恢复正常???
对建墙人来说,
- 不能访问一些国外网站是正常状态.
- 能用蓝灯翻墙是不正常状态

墙能阻止多少,就在于成本和技术.
现在技术貌似没问题了,如果成本可以接受,
那就继续吧...

**Comment by e2889e** [comment]
> 当然，我不希望看到大会结束之后依旧没有恢复正常（呵呵脸）
恢复正常???
对建墙人来说,
- 不能访问一些国外网站是正常状态.
- 能用蓝灯翻墙是不正常状态

墙能阻止多少,就在于成本和技术.
现在技术貌似没问题了,如果成本可以接受,
那就继续吧...
