### ISSUE TITLE
我只希望，Github回归成一个程序员的纯技术论坛。

### ISSUE THREAD

**Issue by dct328** [getlantern/forum#4830]

**Comment by LittleNewton** [comment]
# 技术也是也人类生活相关的

**不能因为技术而技术，Linus Torvalds早就说了，是finding fun引导我们的科技进步，而不是科技进步引导我们**

希望我们祖国越来越好。

**Comment by HUAMENGDIGUO** [comment]
请推墙吧

**Comment by hudson6666** [comment]
你应该到ss社区去讨论技术 在这感慨什么

**Comment by hudson6666** [comment]
顺便看了你的另一帖 稍稍理解了你这心情 但是 错的是墙 错的不是 GitHub 也不是我们这些反抗网络审查的人 我不担心 GitHub 被封 也不会因为担心 GitHub 被封就遏制言论自由的人妥协

我不否认中国在当前国际形势下存在进行思想控制的合理性 也不否认集权制度有它独有的优越性 但是它对民主法治和人民权利的伤害也是要承认的 希望祖国越来越好

**Comment by zhangbodhr** [comment]
你的希望有个屁用，我还希望GFW倒塌呢。有助纣为虐帮忙遏制言论自由的精力，为什么不用在对抗GFW上呢？
顺便你妈在平流层爆炸了，飘得可哪都是，快管管她吧。。

**Comment by HeatMint** [comment]
作者既然有个https://getlantern.org，为什么不开个论坛在这个域名下呢？

**Comment by bigsyw** [comment]
国内网站，贴吧，论坛，你有能力说真话吗？，都用手机实名认证了，说点“真话”，随时就能用所谓的造谣，把你抓起来，还有大多数你要说的关键字都被屏蔽了，你怎么说？

**Comment by AquaHacker** [comment]
每每看到举着政治与我无关大旗 看似明哲保身的猪和羊们 我都倍感惋惜。

**Comment by bodo005** [comment]
你TM当心有一天政治关心你，你就知道谈不谈政治有什么用了。

**Comment by vsfq** [comment]
https://www.plexplan.com./register?invite_code=XZ4MUE

替代方案，互利共赢
