### ISSUE TITLE
PlexVPN也有点慢了。

### ISSUE THREAD

**Issue by kokoofive** [getlantern/forum#4834]
应该是大量新IP涌入导致服务器满载，今天Lantern给的萤火虫刚开始连的时候速度还蛮快的，现在也慢成了一坨，应该是有不少人在看视频，至于看的是什么自己心里有数哈。

就在刚刚又掉了一次，唉。

**Comment by ashuang001** [comment]
萤火虫是免费的.当然慢了.
僧多粥少说的大概就是这个意思 .
总之还是希望lantern能够修复吧.

**Comment by kokoofive** [comment]
没有YouTube的日子，好无聊啊，国内视频网都是一些垃圾剧，广告还那么恶心。

**Comment by Lather0519** [comment]
服务器就那么多，你们去别的地方吧
