### ISSUE TITLE
蓝灯不管用了，我买的还没到期，代理不管用了，这么回事

### ISSUE THREAD

**Issue by diyxiaoshitou** [getlantern/forum#4835]
蓝灯不管用了，我买的还没到期，代理不管用了，这么回事，mac的

**Comment by Iriasu** [comment]
看这里 #4775
要是label真的有置顶的作用就好了……

**Comment by unever** [comment]
发帖之前不先看一下论坛里的其他帖子吗？哪怕不少帖子也都是在抱怨，总有说明情况的，自己都不先找找问题的答案，上来就开口问。

**Comment by 12138tony** [comment]
去要求退款就行，很多人都是刚开通了专业版就不能用了，他们官方说短时间内用不了

**Comment by wenruan999** [comment]
如果10月底还不行，估计就麻烦了！https://www.plexplan.com/register?invite_code=XQC7UH此款vpn一直可以使用，注册可免费使用一天，看1080p视频无压力

**Comment by 12138tony** [comment]
要求退款，要求退款

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: wenruan999<mailto:notifications@github.com>
发送时间: 2017年10月12日 12:10
收件人: getlantern/forum<mailto:forum@noreply.github.com>
抄送: 12138tony<mailto:TonyWater12138@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [getlantern/forum] 蓝灯不管用了，我买的还没到期，代理不管用了，这么回事 (#4835)


如果10月底还不行，估计就麻烦了！https://www.plexplan.com/register?invite_code=XQC7UH此款vpn一直可以使用，注册可免费使用一天，看1080p视频无压力<https://www.plexplan.com/register?invite_code=XQC7UH%E6%AD%A4%E6%AC%BEvpn%E4%B8%80%E7%9B%B4%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8%EF%BC%8C%E6%B3%A8%E5%86%8C%E5%8F%AF%E5%85%8D%E8%B4%B9%E4%BD%BF%E7%94%A8%E4%B8%80%E5%A4%A9%EF%BC%8C%E7%9C%8B1080p%E8%A7%86%E9%A2%91%E6%97%A0%E5%8E%8B%E5%8A%9B>

―

**Comment by vsfq** [comment]
https://www.plexplan.com./register?invite_code=XZ4MUE
替代方案，互利双赢

**Comment by huanghe2015** [comment]
https://www.letscorp.net/archives/124128

**Comment by binbinbinbinbinbin** [comment]
https://www.plexplan.com./register?invite_code=X97TUL
这个月是敏感时期，用这个先撑过这个月吧。速度跟蓝灯专业版一样~
