### ISSUE TITLE
Plexplan 可以先用24小时

### ISSUE THREAD

**Issue by jowaichuck** [getlantern/forum#4848]
https://www.plexplan.com/register?invite_code=ZHBXUV

注册就能用，免费。

大家帮我续命吧

**Comment by VCDVD** [comment]
使用前请三思。

**Comment by tanglei528** [comment]
等着号被盗吧！

**Comment by vsfq** [comment]
https://www.plexplan.com/register?invite_code=XZ4MUE
互惠双赢

**Comment by ClearLove10** [comment]
这东西下载之后根本用不了，显示连接了，查ip根本没有改。

**Comment by Guyiming** [comment]
https://www.plexplan.com./register?invite_code=XXEJUT
安卓试过可以用   windows版无法安装

**Comment by solo4514** [comment]
windscribe VPN 每月免费61GB 网址https://windscribe.com/?affid=wmfoxbcj
![qq 20171012121250](https://user-images.githubusercontent.com/32726204/31479231-5befa718-af48-11e7-82b3-a5dbc0d68cb3.png)
![qq 20171012121343](https://user-images.githubusercontent.com/32726204/31479235-5ef2a15e-af48-11e7-89a3-9aaa6fffee25.png)
