### ISSUE TITLE
Close

### ISSUE THREAD

**Issue by whcrow** [getlantern/forum#4849]

**Comment by LauraGuan** [comment]
有木有连接啥的

**Comment by whcrow** [comment]
@LauraGuan 
http://dongtaiwang.com/loc/software/fg/761/fg761p.zip

**Comment by TheSadFrog** [comment]
https://github.com/shadowSOCKS

**Comment by vsfq** [comment]
((((((((((((


https://www.plexplan.com/register?invite_code=XZ4MUE
互惠双赢
