### ISSUE TITLE
蓝灯笼不亮的时候，MAC电脑最好用什么？

### ISSUE THREAD

**Issue by vsfq** [getlantern/forum#4851]
伤不起，每天的生意影响很大，几乎停滞，损失太大了

补充：
谢谢各位，我找到方案了：

 https://www.plexplan.com/register?invite_code=XZ4MUE

**Comment by cheenwe** [comment]
使用 shadowsockX

**Comment by lilongcnc** [comment]
我用shadowsockX不行. 账号上显示网点都是正常的,但是手机和电脑连接后,出不去.

**Comment by Mogotrevo** [comment]
appstore 里面那个，担心被封的话，可以周付月付

**Comment by HelloXiaoxi** [comment]
[
![2017-10-12 10 13 28](https://user-images.githubusercontent.com/25526254/31475918-23455f72-aec9-11e7-9f91-24a78c03c8e0.png)
](url)

不知道你们用什么，反正我有的用。

**Comment by cheenwe** [comment]
自购服务器, 自行配置 😃

**Comment by xumeng** [comment]
生意都用上它了，还不配备点专业的工具。

**Comment by vsfq** [comment]
生意都用上它了，还不配备点专业的工具。

——————————
蓝灯算专业的工具吗？

**Comment by cheungchou** [comment]
这个现在还能免费用
https://www.plexplan.com/register?invite_code=ZTRBU4

**Comment by anticpc** [comment]
ss稳如狗

**Comment by lilongcnc** [comment]
ss买的哪家账号啊?

**Comment by Halezhang** [comment]
ss 用哪家的服务器 ？

**Comment by Char-CN** [comment]
蓝灯充费2年，使用2个月（人家都是充电2分钟使用2小时）
这个可以用的哥们，我也是买了蓝灯。自从9号就用不了了，憋了2天终于发现，一起翱翔吧。https://www.plexplan.com/register?invite_code=XDIQU3
