### ISSUE TITLE
支持lantern，若资金不够可以众筹

### ISSUE THREAD

**Issue by sience999** [getlantern/forum#4853]
支持lantern，网络自由是公民的基本权利。希望lantern团队能尽快修复lantern，如果资金不够可以发起众筹。

**Comment by jijkbird** [comment]
免费版流畅  特么刚买专业版不到1秒  就连不上了  简直666

**Comment by yDan** [comment]
技术问题啊，不是资金问题吧

**Comment by whcrow** [comment]
收那么多费，说资金不足？

**Comment by ningqivip** [comment]
买了2年，用了还不到一个月，能退费吗？
