### ISSUE TITLE
已经恢复

### ISSUE THREAD

**Issue by Vywh** [getlantern/forum#4855]
<img width="1128" alt="2017-10-12 11 43 17" src="https://user-images.githubusercontent.com/24809413/31478396-ae3aa7a2-aed5-11e7-84c7-ed7aad28d673.png">

**Comment by NewLewis** [comment]
真的假的？？？

**Comment by Vywh** [comment]
不太稳定

**Comment by yeonss** [comment]
安卓的还是不行

**Comment by Germxu** [comment]
不是说阿里云和360高的专利技术识别ss流量来源并进行封锁的吗? 
不知道以后还怎么活

**Comment by Vywh** [comment]
那个论文根本就是瞎写的，本身不靠谱，而且也没有直接证据说明GFW使用了随机决策树

**Comment by Tsohg85** [comment]
还是不行啊

**Comment by Leoleepz** [comment]
不行不行，挂了

**Comment by NewLewis** [comment]
试了一下，不行，反正我的ubuntu是不行的

**Comment by ashuang001** [comment]
我反正就直接看lantern的续费通道是否能打开 .  手动滑稽.

**Comment by Vywh** [comment]
至少不会像之前一样根本连不上，现在可以稳定一段时间了

**Comment by dancorpse** [comment]
不行

**Comment by ningqivip** [comment]
卡死
