### ISSUE TITLE
20号之前最好不要进行修复更新了

### ISSUE THREAD

**Issue by pobingwanghai** [getlantern/forum#4857]
20号之后就放开端口了

**Comment by Leoleepz** [comment]
可以具体说一下是什么情况吗，谢谢 :)

**Comment by ashuang001** [comment]
请问消息来源是什么啊??

**Comment by vsfq** [comment]
https://www.plexplan.com./register?invite_code=XZ4MUE
互利双赢

**Comment by Char-CN** [comment]
蓝灯充费2年，使用2个月（人家都是充电2分钟使用2小时）
这个可以用的哥们，我也是买了蓝灯。自从9号就用不了了，憋了2天终于发现，一起翱翔吧。https://www.plexplan.com/register?invite_code=XDIQU3

**Comment by jetty-guo** [comment]
我的也是 不能用啊 憋屈 两年用一月

**Comment by binbinbinbinbinbin** [comment]
https://www.plexplan.com./register?invite_code=X97TUL
这个月是敏感时期，用这个先撑过这个月吧。速度跟蓝灯专业版一样~
