### ISSUE TITLE
lang attribute for <html> elem on 127.0.0.1:16823 UI does not change with language setting

### ISSUE THREAD

**Issue by HyperHCl** [getlantern/forum#486]
This causes some poor fallback handling for Chinese, since Unified Han characters in Unicode are supposed to show up in different shapes in different locales. https://en.wikipedia.org/wiki/Pango shows another interesting example for such locale-dependent shapes.

**Comment by HyperHCl** [comment]
?! Why am I posting in the forum...

**Comment by p3rcya** [comment]
@HyperHCl I'll move to the issue section. In the future, please open technical issues there directly
