### ISSUE TITLE
坚决支持蓝灯，但是蓝灯不能用时你需要个备胎。备胎在这里呦！

### ISSUE THREAD

**Issue by solo4514** [getlantern/forum#4860]
windscribe VPN 每月免费61GB 网址https://windscribe.com/?affid=wmfoxbcj
免费境外VPN。 windscribe 每月流量60GB. 点击链接，注册账号，选免费使用。注册成功后，点索要凭证，输入SOS60GBS，索要。 之后每月60GB看高清无压力.
![qq 20171012121343](https://user-images.githubusercontent.com/32726204/31479330-04f2dd62-af49-11e7-90db-bd01ab582f8d.png)

![qq 20171012121250](https://user-images.githubusercontent.com/32726204/31479325-fc5b3942-af48-11e7-9947-532797910c58.png)

**Comment by vsfq** [comment]
https://www.plexplan.com./register?invite_code=XZ4MUE
互利双赢

**Comment by solo4514** [comment]
windscribe VPN 每月免费61GB 网址https://windscribe.com/?affid=wmfoxbcj
![qq 20171012124000](https://user-images.githubusercontent.com/32726204/31479561-97cca4a0-af4a-11e7-9802-4603cd95a95e.png)

![qq 20171012121343](https://user-images.githubusercontent.com/32726204/31479566-a0046ee6-af4a-11e7-9083-48f9e3c09ffa.png)

![qq 20171012121250](https://user-images.githubusercontent.com/32726204/31479568-a4c9d6a0-af4a-11e7-8199-a4b90a5cc721.png)

**Comment by beboyss** [comment]
好

**Comment by locogp** [comment]
https://www.plexplan.com../register?invite_code=XXFFU6 共赢

**Comment by Fujiwarz** [comment]
61G怎么拿到的？我只拿到10g？

**Comment by locogp** [comment]
你好，怎么样获得60GB呢？谢谢！现在只有10GB @solo4514

**Comment by solo4514** [comment]
我也忘记怎么拿到61G了，最开始只有5G。之后有个好像是邮箱验证吧，你们试试

**Comment by Char-CN** [comment]
蓝灯充费2年，使用2个月（人家都是充电2分钟使用2小时）
这个可以用的哥们，我也是买了蓝灯。自从9号就用不了了，憋了2天终于发现，一起翱翔吧。https://www.plexplan.com/register?invite_code=XDIQU3

**Comment by solo4514** [comment]
windscribe VPN 每月免费61GB 网址https://windscribe.com/?affid=wmfoxbcj
免费境外VPN。 windscribe 每月流量60GB. 点击链接，注册账号，选免费使用。注册成功后，点索要凭证，输入SOS60GBS，索要。 之后每月60GB看高清无压力.

**Comment by locogp** [comment]
这个sos凭证现在提示是无效的了，没办法了 @solo4514

**Comment by solo4514** [comment]
那就10G吧，现在可能只有10G了
