### ISSUE TITLE
关于这两天PlexVPN，其实是智障鉴定VPN

### ISSUE THREAD

**Issue by Lather0519** [getlantern/forum#4861]
智障言论①：网站备案，国家监管，个人隐私。
解剖智障：这种人要么是文化低被带节奏的，要么是真正的反动者。
1.先说备案，想知道有没有备案完全可以去工业和信息化部查询，查完之后是不是备案自己心里没点逼数？我想应该没有，因为智障连查都不肯动手查，宁愿被带节奏当枪使。
2.国家监管，这TM就更好笑了。这是什么时代？到处都是摄像头，实名制；你没坐过火车？没做过高铁？还是没读过书？就算自驾你也要去加油站吧？当然，还没到能查你一天拉了几泡屎。
3.个人隐私，excuse me?
总结：土共立墙防的就是上面这种弱智，没脑子，或者是文化低，自以为墙外就是绝对正确，做什么都跟国家反着来，已然就是一个反动者；奉劝那些在外国留下各种反动暴恐的普通屁民，土共想查你没有查不到的，问题是人家不可能去使用国际交际地位来查你一个小屁民；并且蓝灯某些节点用的是阿里云的服务器，你以为土共不知道你这群煞笔干了什么事？为什么你还能在这里装逼？因为你现在还只是个发牢骚的小屁民。如果不信，够胆你就自己加入几个反华组织试试。

智障言论②：PlexVPN是土共钓鱼VPN
解剖智障：这种人跟上面一样，脑子有缺陷，你不可能说服一个傻逼，因为傻逼会攻击你，把你拉到跟他同一个水平，然后用他的傻逼功力击败你。

总结：全球任何一个信息化的国家，所有的信息都是被搜集的，普通人没有谁是隐形人。但是并不是说搜集了就一定要看，你不搞事，人家就不会去翻你的资料，也不会去查你。如果你是老老实实的人，你的信息一辈子都不会有人看，直到你死了然后被销毁。至于那些连一点网络技术都不懂，自身也不是什么碉堡的黑客，拿个VPN就在网上大肆留下反动语言，呵呵，相信我，你一定会出事的。

**Comment by provxy** [comment]
部分支持。
我到现在不敢买plexplan的原因仅仅是我怕plexplan也会挂。

**Comment by zhongguowangjing** [comment]
终于有个理性的人。任何一个国家政府都是监视民众的行为的，是任何一个国家，你以为你在网络上的行为政府会不知道？查你与不查你，只是需不需要的问题而已。

**Comment by Char-CN** [comment]
蓝灯充费2年，使用2个月（人家都是充电2分钟使用2小时）
这个可以用的哥们，我也是买了蓝灯。自从9号就用不了了，憋了2天终于发现，一起翱翔吧。https://www.plexplan.com/register?invite_code=XDIQU3

**Comment by vsfq** [comment]
https://www.plexplan.com./register?invite_code=XZ4MUE

替代方案，互利共赢

**Comment by Eachenk** [comment]
表示，昨天好好的 今天PLEXVPN的客户端就下载不了了， 360还疯狂报查杀
