### ISSUE TITLE
这个帖子里面的公告精华 里面的赛风就可以用啊，我现在就在用，但是间隔几分钟会掉线，不知道是不是受到某墙的干扰。用蓝灯的时候发现发送字节多，接收字节少，这个时候通常翻不了墙，接收字节多余发送字节的时候就能正常使用，现在的赛风也一样。先用着再说吧，反正能上推，看看新闻，看视频有些卡。还有这个git不用翻墙就能上，所以不要在此讨论敏感问题。那些猜测墙加固了的 赛风能上你怎么解释？ 先用着再说吧

### ISSUE THREAD

**Issue by haoyukin** [getlantern/forum#4888]
请在发帖前先按照蓝灯无法使用的解决办法 https://github.com/getlantern/forum/issues/1902 自行解决。自行解决问题通常只需要几十分钟。管理员调查解决问题需要几天至几周。请立即访问https://github.com/getlantern/forum/issues/1902 瞬间解决98%的问题

为了能在最快的时间内解决大家使用蓝灯遇到的问题，请各位用户严格按照发帖格式提交问题。

## 发帖格式
遇到的问题：请详细描述遇到的问题。如果描述不仔细，将无法调查

蓝灯专业版账号Email:  请提供登陆蓝灯专业版的email，免费版不提供技术支持。

应用内报告问题的时间:  请根据 https://github.com/getlantern/forum/issues/1840 在应用内上报问题，请填写专业版的email。请在帖子里注明报告的时间。

截图: 请提供有关问题的截图。 请把图片拖拽到这里。

----
请不要发只有邀请码没有其他内容的帖子,违反者将扣除所有赠送时间。具体见 https://github.com/getlantern/forum/issues/3773

**Comment by samscott1989** [comment]
我觉得大家的确不要在Github讨论特敏感的话题。。因为随时可能会引起某人注意 到时候连Github上不去就麻烦

**Comment by 349205055** [comment]
可能封的端口不一样，赛风可能叼一掉

**Comment by binbinbinbinbinbin** [comment]
https://www.plexplan.com./register?invite_code=X97TUL
这个月是敏感时期，用这个先撑过这个月吧。速度跟蓝灯专业版一样~

**Comment by fjsiineo** [comment]
还是用收费的express吧，免费的怕被钓鱼。虽然贵了点买一个月先扛一下，蓝灯19大后也许会好点。express的下载地址：http://www.expressrefer.com/refer-friend?referrer_id=14202793&utm_campaign=referrals&utm_medium=copy_link&utm_source=referral_dashboard
