### ISSUE TITLE
推荐个临时替代方案,自己有试用,比官网推荐的稳定,速度快,稳定

### ISSUE THREAD

**Issue by TongFangyuan** [getlantern/forum#4905]
.

**Comment by tyc1981** [comment]
下载链接打不开，是不是因为我用360的缘故

**Comment by fjsiineo** [comment]
为啥一回家要普查ip 你觉得这个国家买菜刀都要实民，这个国家正常吗？？不要觉得民众对不起政府，而是这个政府把人不当人，当奴才，当奴隶在用！IT男不要以为你不关心政治，你就不会被政治干扰，恰恰是你这种想法的人导致了中国如今这个局面。网络本应该是自由的，而不是砌高墙把百姓们围住困住！

**Comment by fjsiineo** [comment]
为啥一个国家要普查ip 你觉得这个国家买菜刀都要实民，这个国家正常吗？？不要觉得民众对不起政府，而是这个政府把人不当人，当奴才，当奴隶在用！IT男不要以为你不关心政治，你就不会被政治干扰，恰恰是你这种想法的人导致了中国如今这个局面。网络本应该是自由的，而不是砌高墙把百姓们围住困住！

**Comment by bimver** [comment]
打不开网页啊

**Comment by aXiaoYu** [comment]
先打开"免费一天"的链接，再就可以打开"免费11G"的链接了

**Comment by guoying1030** [comment]
@fjsiineo    哥，该吃药了。。。我们用vpn只是来学习的。。

**Comment by elecCore** [comment]
登陆超时

**Comment by fjsiineo** [comment]
该吃药的是你吧，学学得头脑如此不清楚，你学习了也干不成什么事。

**Comment by lwtbn1** [comment]
嘿，怎么没找到免费11g的链接？

**Comment by Wait845** [comment]
安卓可以用吗

**Comment by buptchinaren** [comment]
plexVPN那个还是不能用……

**Comment by CaesarRuiLin** [comment]
显示登录超时的需要手动在高级设置里面进行设置, 服务器地址 , 里面手动设置 https://api.pandasocks.org

**Comment by elecCore** [comment]
@CaesarRuiLin 设置这个地址之后登陆还是请求超时，端口什么的需要配置么？

**Comment by CaesarRuiLin** [comment]
https://api.vpnplex.com
https://api.plexplan.com 
https://api.pandasocks.org 
https://api.pandavp.com
https://api.pandavvp.com
这几个都试一下吧看看行不行我开始用https://api.plexplan.com 这个不行, 换成https://api.pandasocks.org 这个就可以了
@elecCore

**Comment by CaesarRuiLin** [comment]
@TongFangyuan 我用了那个11G的Windscribe速度不行啊, 还是打不开

**Comment by elecCore** [comment]
@CaesarRuiLin 谢了兄弟！https://api.plexplan.com连上了

**Comment by relanda** [comment]
政治跟每个人都息息相关。。呵呵，以为不谈就跟自己没关系了吗？真是暴露智商。

**Comment by ys1989611** [comment]
这个可以连得上：https://www.plexplan.com/register?invite_code=X5TWU8

**Comment by ys1989611** [comment]
连接不上的点这个链接：https://www.plexplan.com/register?invite_code=X5TWU8
