### ISSUE TITLE
我用的MacOS，今天刚买的专业版，居然无法翻墙！【入坑？】

### ISSUE THREAD

**Issue by q258523454** [getlantern/forum#4916]
花了几百块钱买了专业版，升级之后发现还不如免费版，完全不能用！
跟党的19大有关系吗？但是为什么免费版的能用呢？

**Comment by cweijan** [comment]
前几天被封了,草他么的,老子300块就用了一个月

**Comment by hexawp** [comment]
免费版能用?  

还有一件怪事, 我一个朋友不知道从哪里给我找来一个2.4版本的蓝灯, 他说他一直能用,还是免费的...
反正我专业版10号开始就一直不行.

**Comment by HelloXiaoxi** [comment]
本身蓝灯开始一直就是免费的啊，后来被大陆的人买去了，做成了收费版。之前有人在本站说过，让大家小心使用蓝灯或者尽量不用，（一些技术的东西看不懂）因为确实是国人在控制。

**Comment by bigmother** [comment]
我还在想免费版怎么用不了了。索性买了专业版。。然而还是用不了。心痛

**Comment by onloner2012** [comment]
我也是啊
难道是开会有关，谁能说一下吗？

**Comment by HelloXiaoxi** [comment]
艹，，兄弟买的时候没看一下论坛吗?  找其他方法吧。

**Comment by onloner2012** [comment]
用了快一年了，都是好好的，这几天就不行了，以为是升级，过几天就好，结果，到现在，废了

**Comment by galaxyseeker** [comment]
也许就是因为开会，大家以后就有经验了，买的时候注意时间。

**Comment by Ricky-Tsang** [comment]
大坑是不 這是商業詐騙~

**Comment by truthandlove** [comment]
版主好！大家好！

凡是电脑里装有腾讯公司、360公司 和其它受到中国公安部认证的杀毒软件公司发布的产品（包括非杀毒产品），往往他们的电脑翻墙都受到监控和影响，这些电脑在十九大中国政府加强管控期间，要是能成功翻墙，往往是偶然，甚至连偶然的机会都没有。

翻墙前，我们一定要想清楚，遇到问题的时候，考虑是先向中国政府抗议剥夺公民自由上网的权力，还是肆意指责帮你翻墙的人无能而不是自己无能。我们力争做一个有人格，能信任其他善良的人的人。

**Comment by truthandlove** [comment]
版主好！大家好！
我是翻墙爱好者，代理多种翻墙产品。
对于最新的4.2.1版，很多大陆网友反映用不了，我们的一些用户起初也遇到这种情况，但是，按照下面的基本步骤做，所有相关用户都可以翻墙了。
1。利用蓝灯的uninstall删除，并检查相关文件夹是否确实删除。
2。删除C:\Users\yiwei\AppData\Roaming\byteexec\ 文件夹。
3。删除电脑里所有腾讯、360的相关软件，包括QQ、手机应用宝、杀毒软件。（在翻墙的电脑中，决不用中国大陆软件，可用小红伞、comodo等外国杀毒软件）
4。在任务管理器中观察还是否有 腾讯、 Tecent、360的软件，终止其运行，并彻底删除。
5。重新启动电脑，在用户管理中创建新的管理员帐号。
6。用该新的管理员帐号，进入windows，并用管理员身份安装最新版蓝灯。
7。进入youtube，播放美国高清视频。（我们的用户反映速度高于很多其它翻墙软件）
8。遇到问题的时候，考虑是先向中国政府抗议剥夺公民自由上网的权力，还是肆意指责帮你翻墙的人无能而不是自己无能。

**Comment by truthandlove** [comment]
版主好！大家好！
中国大陆最佳翻墙电脑环境推荐：
1。英文版windows7 ，可加中文语言包。
2。英文杀毒防火墙软件，可关闭微软自带defender和firewall。绝无中国大陆或外国与中国政府合作的软件商的软件。
3。新建管理员账户。
