### ISSUE TITLE
看了几篇文章，看了几个视频，就满口“五毛，五毛”，把共产党对国家的贡献选择性遗忘

### ISSUE THREAD

**Issue by CherryYING** [getlantern/forum#4922]
就算共产党开放了网络，把中国变成和美国一样自由民主的国家，这些人还是会出来喊“五毛，五毛”

**Comment by HUAMENGDIGUO** [comment]
@CherryYING 那请开放网络，看看民众的反应如何。

**Comment by LuckyTigerMan** [comment]
支持你

**Comment by marsbible** [comment]
那就放开，国内也放开，到时候我天天给党唱赞歌。

**Comment by chutianshu1981** [comment]
现阶段看一党专政没啥不好的，但请开放网络

**Comment by qmz2000** [comment]
脑残就别翻墙了，呆里面也挺好的，就是别遇到拆迁，吃饱了别路过洗头店，不然就是雷洋的下场

**Comment by beboyss** [comment]
国家给了我生命，给了我吃的，给了我喝的，给了我一切，所以拿走一切也无所谓，自此，我顶，我自带干粮

**Comment by rotencode** [comment]
对国家做出贡献的不是什么党派，而是勤劳的公民。你跪着跪习惯了别要求我们也跪着，谢谢。
不赞美的权利太重要了。20世纪的几大极为骇人听闻的悲剧都是因为煽动崇拜造成的。例如红色柬埔寨屠杀消灭柬埔寨总人口1/4，没人敢反对，看不顺眼都可能会冠以敌对势力枪杀。毛时代放卫星+天气问题，引发的三年饥荒造成目前都无定论的千万级别人口饿死，核心点就是没有人能批评毛的放卫星决策。光是河南的一个市就饿死超过百万人。毛放卫星有人反对，例如彭德怀，58年七千人大会全力批斗彭德怀，结局是文革时代被毛整死了。
没有共，就没有十年文革，没有前三十年大肆搞权力斗争，也没有台湾问题，中国必然早就像台湾一样进入发达国家阶段了。
凡是搞社会主义（变异版封建皇权体制的遮羞布）的，现在还有几个好东西？一个全国只有一个胖子的封建帝国朝鲜，一个人均收入不足一千元人民币的越南，一个时常偷渡美国的古巴。还有根据相关法律法规无法显示的其他国家。

**Comment by CherryYING** [comment]
@rotencode 
1.这只是我的观点没要求你们你做什么。
2.什么叫我跪着，你支持资本主义反对共产党就是站着了。
3.党派对国家没有贡献，那为什么每个国家都有党派。

**Comment by mythlegend** [comment]
只有畜类才会跪舔一个在和平时期造成大量平民非正常死亡，至今拒不道歉还自称伟大的无耻组织～

**Comment by AquaHacker** [comment]
首先 请支持我对题主 说一声 去你妈的。然后开始文明的和他讲讲，省的他觉得翻墙的都是容易被洗脑的人。

手无寸铁 说话都没人搭理你。 没有话语权

说封锁外国网站的 人大代表 一定不是人民选的。

人民不会跟自己的自由过不去。

起码我不会。从来没有参加过投票的我。不知道人大是什么鬼。

大家谈政治变色。低头夹尾巴做人 。现在连上个网都不让上了。真 TM 逼人 造反 啊。

要知道 翻墙的这波人 都是 什么层次的。

你国还能进步？继续封吧。惹得精英都出国了

你国统治层 就高兴了 愚民教育得以继续实施。

然后不定哪天 就放个片子洗脑告诉你 国家被侵略了 让你去玩命。

帝国主义 毫无疑问。

下载了 4.1.2 没作用。
什么页面都打不开。哦 百度还能打开！

可是 百度 不是用来搜谷歌的吗。。。。。

难道 大清时代 要来了。

Github 不会也给墙了吧。。。。。

留个纪念 耐心等 蓝灯再次亮起，实在不行就只能自行搭建VPN了。

这个鸡巴国家。操。安居乐业成为奢望，买不起房（SB政府也不管） 开不起车（购置税 排量税 收费的公路 ）经济早TM硬着陆了 也只有看看 新闻联播洗洗脑才会觉得能活着就是幸福，生活是什么 想都不敢想。

上网看点东西 还TM管！ 弄GFW 的那帮人 是不是 没有鸡巴！

言论 自由 民主 呵呵 真TM扯淡啊！

在国外的亲戚都没回来
说生孩子给养到18
车子很便宜
加油也跟喝水一样不要钱。
都是大排量 没有涡轮增压 没有限号 没有雾霾

哈哈 挺讽刺天朝的 弄了半天 还是工厂污染 跟车子和做饭没关系嘛。
可是能怎么办呢。你买车子 2/3 是税。

这就是你爱的天朝 每天还希望他变得更好 可是所谓的人大代表 又不是我们选的。提的意见都很奇葩。

政治变的让人谈虎变色。这是一个帝国毫无疑问了啊

让我爱国 汽车购置税、高速费先取消了吧！！

如果从此真的无法翻墙 形成局域网... 这才是真正的圈养猪羊。

每每看到 高举政治与我无关 大旗 看似明哲保身的猪羊们，我都倍感惋惜！

怪不得你国这样，其实都是你们自己导致的。

看到别人需要帮助 你不管，冷漠形成了恶心循环。

下一个强拆的就是你家。

所有的正义都被分化了，看热闹的人多，管闲事的少。

难道真的都是闲事吗，不会到你的头上吗？

气不过的都出国了。

这次事件 看得出来 人们的心态分为了好几拨；

可能不到你头上 大家都不会团结。可是都心怀侥幸 怎么能改变现状？

难道我说一句 那些不让我翻墙的操他妈的没有鸡巴的 还能颠覆了政权？

现在连刀 都打了二维码。 你国真是没自信 在怕什么？

人民和统治层的关系真的恶劣到了这样的地步吗

不用我回答。

反正 国家早已是匪党的机器。

别期待恢复 不太可能啊。

**Comment by anticpc** [comment]
@CherryYING 选择做猪你就低头吃你的食，选择做狗你就用力摇你的尾巴，选择做人你就发出你自己的声音！

**Comment by kuseqingchun** [comment]
借鉴一个故事：1973年8月23日，瑞典首都斯德哥尔摩的一间银行这天突然冲进来两名绑匪，“都别动！举起手来！”这两人都是有前科的惯犯，当时正在工作的4名银行职员，就这样被劫持作为人质。两绑匪以此为要挟，跟警察对峙了足足有6天时间。

这4名被绑架的银行职员，后来在法庭上做证，要告那两名绑匪。但是，他们不仅没有像秋菊打官司一样讨个说法，反而是替这两名绑匪求情，他们也没有对我们怎么样啊，他们也是被逼无奈的啊，这6天他们对我们悉心照顾，求青天大老爷放过他们吧……都是这类的话。

银行职员竟然为劫匪求情，这部是很荒唐的事情么？不，但是他们内心早已习惯，他们认为劫匪才是好人，而警察却是坏人。

**Comment by lemonskkyt** [comment]
觉得翻墙会被洗脑也是神奇，一个生在中国，养在中国， 吃在中国，住在中国，接受中国教育，受中国文化熏陶的中国人，上一下国外的网站就立马被洗脑？？？请问是什么样的教育才可以教出如此不堪一击的中国人？？？

**Comment by hxdq** [comment]
哈哈，楼上说的好，这就叫体制自信，文化自信！

**Comment by hxdq** [comment]
哈哈，楼上说的好，这就叫# **文化自信**！
是建立在对言论封锁的体制自信基础上的！

**Comment by AlbatrossCoder** [comment]
我觉得你们是想让github也被封掉，能不再github讨论这些问题么？

**Comment by ningqivip** [comment]
猪奴

**Comment by koogc** [comment]
@rotencode 这位大哥真是一位伟大的历史学家，经济学家，还是一位优秀的政治家，麻烦用你闪亮✨的键盘敲出来，30年前您要用什么样的办法让刚解放的中国进入发达国家？？？？    麻痹的真是把一群猪喂饱了什么牛逼都敢吹出来

**Comment by filmnoir1991** [comment]
难道你以为现在中国不是资本主义。。。动动脑啊再看看书啊，各种主义搞搞清楚再对比现实。。。中共制度等于社会主义？。。。

**Comment by Tsohg85** [comment]
别扯没用的…开放网络先…

**Comment by koogc** [comment]
@mythlegend 你说的是美国吗？ 在战争时代挑起数次战争，造成成千上万的人员伤亡，无数人无家可归，世界上最伟大的国家，没有之一。。。

**Comment by rotencode** [comment]
@koogc ，1970年左右的朝鲜比韩国还富有，现在韩国人均收入是朝鲜一百倍以上，朝鲜普通人一年的收入不够买件一千多的棉外套。当然，为国为民的金正恩大元帅抱着我不入地狱谁入地狱的决心成为全朝鲜唯一一个可能患高血压高血脂高血糖的人。其他人面黄肌瘦的，怎么可能高血糖。WHO和诺贝尔委员会应该宣传金正恩消灭高血压高血脂高血糖的贡献。
同样1945年的日本一片狼藉。现在人均收入应该是中国5倍以上。
目测什么垃圾培训机构毕业的哈哈。。
