### ISSUE TITLE
恭喜恢复正常~

### ISSUE THREAD

**Issue by cifer-lee** [getlantern/forum#4924]
请在发帖前先按照蓝灯无法使用的解决办法 https://github.com/getlantern/forum/issues/1902 自行解决。自行解决问题通常只需要几十分钟。管理员调查解决问题需要几天至几周。请立即访问https://github.com/getlantern/forum/issues/1902 瞬间解决98%的问题

为了能在最快的时间内解决大家使用蓝灯遇到的问题，请各位用户严格按照发帖格式提交问题。

## 发帖格式
遇到的问题：请详细描述遇到的问题。如果描述不仔细，将无法调查

蓝灯专业版账号Email:  请提供登陆蓝灯专业版的email，免费版不提供技术支持。

应用内报告问题的时间:  请根据 https://github.com/getlantern/forum/issues/1840 在应用内上报问题，请填写专业版的email。请在帖子里注明报告的时间。

截图: 请提供有关问题的截图。 请把图片拖拽到这里。

----
请不要发只有邀请码没有其他内容的帖子,违反者将扣除所有赠送时间。具体见 https://github.com/getlantern/forum/issues/3773

**Comment by shuozhoushi** [comment]
还是不行

**Comment by kangpingmeng** [comment]
我的也打不开Google都。。。显示是已连接。。。但还是打不开

**Comment by tingcom3** [comment]
还是不行呀。

**Comment by Tsohg85** [comment]
然而并没有

**Comment by xman123601** [comment]
能不能不要防这种假消息 ？

**Comment by renhuihhh** [comment]
别逗好吧

**Comment by Leviathans** [comment]
连接中和已连接来回切换 根本没法用

**Comment by 80068** [comment]
别放风了，目前根本无法使用

**Comment by pclxd** [comment]
偶尔链接上不代表稳定啊！我这里就不行！关键是新的算法和机制需要研究，这个还是要花点时间的，毕竟长城网不是吃素的，还需要lantern团队这次吸取经验和教训 为以后提供更稳定快速的服务打下良好基础
估计这几天团队可能没日没夜的弄！
