### ISSUE TITLE
這篇新聞大概重點整理了最近被加強厚牆的一些內容，感覺真帶勁

### ISSUE THREAD

**Issue by KeikoSong** [getlantern/forum#4937]
中共十九大前媒體監管：「盛世」景象，如誰願？
http://www.bbc.com/zhongwen/trad/chinese-news-41593114

有貼給大陸朋友看，說看不到，應該是被封了
能看到的自然看的到，看不到我就貼幾段重點

------------------------------------

上月底，新浪微博的公告稱向所有用戶公開招募1000名微博監督員後許多用戶噤聲，微博的活躍度一線下降。而且自10月1日開始，新浪微博必須進行實名登記。

當然對於網絡欺凌和詐騙等問題，此舉確有作用。但醉翁之意不只在酒。

    十九大前收緊管控? 新浪微博招募千名監督員
    中國網信辦發佈新規 嚴管網絡群組討論

拱手相讓群主之位

近幾年微博戾氣稍重，中國網民開始轉至封閉的社交媒體微信。前兩年微信還是天津爆炸和中國股災等大事件的信息源，網民對時政能各抒己見。不過，上月底，中國國家互聯網信息辦公室發佈《互聯網群組信息服務管理規定》，對網絡群組討論加強管控。

簡而言之就是"誰建群誰負責"、"誰管理誰負責"。

規定一出台，嚇得筆者一位喜歡建群的朋友趕緊拱手相讓自己的群主之位。她說："我幾天內讓出了幾個群主之位。還解散了幾個群。"

在中國，像這位前群主者眾。這不，管控目的達到了。

    BBC中國總編看中共十九大之一：習核心
    BBC中國總編看中共十九大之二：信息管控
    BBC中國總編看中共十九大之三：反腐運動

倒下的VPN和淪陷的WhatsApp

中國網民不笨，知道微信群聊天后台有監控和微信平台有關鍵詞屏蔽功能。於是乎但凡有點招和辦法的網友一開聊"機密"就搬去臉書旗下的社交平台WhatsApp。畢竟今年7月前，此地還安全，眾人認為這是外國公司的平台，應該安全。

直到今年七月中旬，中國有關部門一聲不響的技術干擾給WhatsApp海內外用戶一個大"驚喜"。用戶不得不使用VPN才能順利傳輸視頻和圖片。

沒有VPN？那對不起，當時就傳不了視頻和圖片了。

幸好這個干擾和間斷只持續了幾天，又恢復了正常。但網友知道，中國的有關部門"小試牛刀"後，WhatsApp也淪陷。

九月初中旬，干擾又來了。這回淪陷症狀一摸一樣。

只是網友們可用的VPN少得可憐。

    蘋果中國商店為什麼要下架60多個VPN應用？
    英媒：中國要徹底封鎖VPN翻牆軟件了？

中共十八大後，中國國家主席習近平也親自擔任中央網絡安全和信息化領導小組組長，對網絡出擊。

今年8月1號，蘋果的中國商店下架了60多個VPN應用。
圖片版權 Getty Images

在中國大約7億網民中，有約2億網民經常使用VPN閲讀在國內被屏蔽的內容，包括像臉書（Facebook）和推特（Twitter）等社交媒體內容。

開發商們一片怨言，稱向蘋果上訴。有用嗎？

整頓VPN的動作從今年年初開始。今年1月中國工信部宣佈，所有提供VPN的開發商必須從中國政府取得牌照。

「19大之後恢復正常」？

好吧，國外的東西看不了。看看國內的吧。國內也好不到哪兒去。

比如今年6月，中國的廣電總局叫停網站視聽節目。被要求關停試聽節目服務的有微博，ACFUN(俗稱A站）和鳳凰網等。因為它們不符合國家規定的時政類視聽節目和宣揚負面言論的社會評論性節目"。廣電總局想要達成，"進行全面整改，為廣大網民營造一個更加清朗的網絡空間"。

網絡一片哀嚎，年輕網友們開始"哀悼"A站。

中國網友眼裏快人快語的"金姐"，也不得不在8月底跟觀眾朋友們說後會有期。中國變性人金星的電視脫口秀於8月底被叫停。目前尚未接到複播的消息。金星的秀關注民生，重點在文娛。上節目的多為明星，甚少談及時政。不過"金姐"這麼快人快語，網友稱"啥都敢說"，萬一說多了，說過了如何是好？還是先叫停吧。
圖片版權 Jin Xing
Image caption 《金星秀》於今年8月底停播。

沒了中國上半年網紅級的脫口秀相伴，網友們想，我還有陪伴了二十幾年的《鏘鏘三人行》。咔嚓，九月中旬，這節目也被就停。被叫停的還有鳳凰衛視的《時事辯論會》、點評國際新聞的《震海聽風錄》。據中國的《新周刊》統計，《鏘鏘三人行》對56%的觀眾有觀念上的影響。

    觀察：《鏘鏘三人行》停播 最嚴肅的娛樂消息
    解惑：為什麼BBC"巾幗百名"提名金星？

觀察人士認為，中共19大即將召開，當局循例收緊對媒體的限制。

十八大前中國政府也對媒體加強新聞管制。一些網民也表示理解，也寄希望於未來是否會放開媒體和網絡環境。

VPN供應商Green的客服在回答客戶的在線問詢為何無法登錄時說：「19大之後恢復正常，VIP補償一個月。」

真的過了19大，網友就與這個世界重新連接了嗎？

等著吧，18號就開會了。

-----------------------------------

**Comment by KeikoSong** [comment]
> VPN供應商Green的客服在回答客戶的在線問詢為何無法登錄時說：「19大之後恢復正常，VIP補償一個月。」

這段我笑了

**Comment by Lather0519** [comment]
土共要枪毙的就是你们这种傻逼，知道为什么立墙么？因为你们这群傻逼唯恐天下不乱，一面推断之辞都能不负责地疯狂转载，丝毫不考虑后果，就为了人气。能干这事的除了北方没见过世面的乡下仔（东北三傻，快手称王）没有别人

**Comment by KeikoSong** [comment]
@Lather0519 腦袋過保沒？還沒的話快去換一顆，這種智商充值沒用了，換一個比較靠譜

神經病，好像全世界都你們中國的？
為什麼有人要翻牆？就是為了要有不同的聲音。
如果只需要一個聲音，看看金胖子的北韓，那就是下場。

中國如果有種就乾脆把所有對外網路全部斷光光，自己玩自己的一言堂，國外新聞跟事務跟你們大天朝無關，有多遠滾多遠。

**Comment by KeikoSong** [comment]
正常人的思維：會去在意外面的世界，去了解什麼是好的、什麼是壞的，讓自己更好。
獨裁者的思維：和平就是只能有一個聲音，只有獨裁者的聲音，不同的意見都是不安定的因素。

每次看到北韓的金胖子發病，北韓的民眾被愚弄管制的樣子，就在想，中國接下來就是這樣吧？

以前看過中國人說笑：朝鮮（北韓）人民存在的意義，就是讓中國人覺得自己很幸福。

這個笑話其實不好笑，北韓的現在就是中國的未來。

中國民眾多保重吧。

想想以前推翻滿清的前輩，多少人為了自由而前仆後繼的拚死。
想想為了抗日犧牲的前輩，多少人明知不敵也是不願意當漢奸。

腦子永遠都只有抗日神劇內容的愚民，別再好傻好天真了。

真正的自由是擁有自己的思想，而不是只能有一個聲音，而且還是別人的聲音。

歷史上告訴我們那些邪惡的人才會用折磨肉體跟囚禁的方式去脅迫禁止別人擁有思想。

否則，在不傷害他人自由的情況下，為什麼不能擁有自己的聲音？

**Comment by crosssfa** [comment]
7亿网民2亿翻墙？哪统计出来的？

**Comment by zhongguowangjing** [comment]
@crosssfa 需要统计？反正BBC说什么都是对的，呵呵

**Comment by ApocalypseWolf** [comment]
金星自己都发过微博说是被穿小鞋，这篇新闻的可信度emmm

**Comment by free2017fly** [comment]
不怕为啥要封呀……。此地无"淫"三百两

**Comment by KeikoSong** [comment]
> 7亿网民2亿翻墙？哪统计出来的？
我覺得應該是裝置，不是人

**Comment by KeikoSong** [comment]
> 金星自己都发过微博说是被穿小鞋，这篇新闻的可信度emmm

這種內幕我是不清楚啦
就像是韓國人總是宣稱XXX是他們韓國人一樣
就像是淘寶上面賣假貨的幾乎都不承認賣假貨也一樣
歷史上多的是告訴我們，很多事情的真相都是被某些少數人所竄改的

這種事情全世界都有，但是做的最明目張膽的也只有那些控制言論自由的國家才能做到了

**Comment by provxy** [comment]
哎。十九大召开，弯弯安稳点行不行？还是说，繁体字的，其实是假的弯弯?
我是简体字。
弯弯不用过度担心大陆。搞得好像大陆人都是傻子一样。其实呢，不管怎么样，大陆领导人总比弯弯领导人英明。(你们可以否认。)
十九大前管控这么严，估计是有大动作。关键时期，最好的方法就是，不要搞事，听从国家的安排。
功过事后论。
弯弯。我不怎么想鸟bbc。挑拨离间，黑中国不是一天两天的了。你们自己心没点数?

**Comment by KeikoSong** [comment]
@provxy 自大的中國人，好像全世界的華人只有中華人民共和國以及走入歷史的中華民國而已
不是華人就一定就是這兩個國家的人好嗎？

秦始皇也是華人，難道就是中國人嗎？
那乾脆要不要說美國總統也是中國人算了？反正都是流著一樣地球人的血，乾脆提前宣告中國統一全世界好了？跟韓國人一樣自大這樣好嗎？

中國人的政府管好中國人的事情就好，中華民國的歷史遺民，你們愛怎麼處理那是你們的事情，我們就只是看熱鬧的，看看自大的中國人事怎ˋ麼打算對帶全世界的華人甚至是乾脆只要是黃種人都算是中國人好了？真的是笑話。

認真告訴你，十九大開不開干我毛事？只有關心政治的人跟國家才會在乎這種事情，對於很多人跟我來說，只不過是個談資而已，逗個樂子，什麼都算不上的屁事。

不要太自我感覺良好總是愛吹牛，好像全世界都是中國人的一樣，中國不過短短不到百年的歷史，還是好好管好你們自己人就好，不要老吹噓以前怎樣之類的，華人祖先的豐功偉業，不是小小的中國可以據為己有的，活像是個敗家子一樣，只會夸夸其談，老說當年如何，要讓世界其他國家的人尊重跟認同，不是光靠武力或者是恐嚇就能的，先把自己國家管好吧。

有時候光看你們管理自己同胞的作為，就讓人知道你們政府的做事有多橫行霸道，明明就是外國人血統的新疆人，跟華人根本就是兩個不同的爸媽，也要被你們綁架成為一份子，看了就讓人心寒，活該動不動就被搞分裂，不管是搞分裂的還是搞統一的，都一樣下流，只會用武力跟恐嚇做事，讓人瞧不起。

**Comment by kokoofive** [comment]
我只支持你的一条言论“真正的自由是擁有自己的思想，而不是只能有一個聲音”

至于你说的其他观点，我只能说两岸关系有代沟，交流不来。歇歇吧，大半夜的别这么上火。

**Comment by AynRoark** [comment]
@KeikoSong 

糾正一個錯誤：簡體字不是大陸政府造成的，事實上，在民國期間，政府就已經在實行簡化了。另外從歷史上看，字體的簡化本就是自然而然的，你可以去對比今天的簡體字和古人的筆記，你就會發現現在用的簡體字有很多在很早以前就開始用了，字體本就是為方便交流而慢慢演化的。

另外“活該動不動就被搞分裂，不管是搞分裂的還是搞統一的，都一樣下流”和“我相信你們兩岸一樣都會有好人”是前後矛盾的，你沒發現么。

我讚同，在其他國家的人眼裡，大陸和朝鮮不過是個笑話，談資而已。

大陸網友的言論不值一駁，我搞不清楚為什麼就他這種認知還想要翻墻，“不要搞事，听从国家的安排。”既然這樣，那他為什麼會下載藍燈呢？為什麼會看這個論壇呢？除非是網警。另外“大陆领导人总比弯弯领导人英明。(你们可以否认。)”的意思不就是我不聽我不聽，我就最牛逼嗎？和這種人有什麼好交流的？

真正事實如何，可以翻墻藉由外界的信息交叉印證是很容易的。

**Comment by KeikoSong** [comment]
我認同我的有些話語其實是屬於比較挑釁點的，畢竟老是動不動看到兩岸爭吵的新聞，不管是誰對誰錯，我認為都沒有對錯。

站在第三者的角度來看，我認為只不過是一種認同感的問題，彼此都不認同對方代表自己的時候，就很容易產生爭執，尤其是，不想被對方代表，卻又想代表對方的局面是最無聊的。

而且我得明說，有時候我光看新聞，不管新聞正確與否，但是很明顯的，很多爭議性強的言論就像是我這種有點挑釁意味的言論一樣，本質上是沒有任何幫助的，認真看待人反而會被帶入溝裡。

一個國家以什麼為本？是人民。

但是一個國家的聲音卻總是被少數人所霸佔，不管是政府、任何組織都是一樣，甚至還有一些喜歡興風作浪的人在裡面混水摸魚（我這篇的一些過度言論其實也算是很不恰當跟無裡的）

為什麼我要故意這麼說？或多或少，有點怒其不爭吧，總是覺得我們人類的力量都是浪費在這種鳥事情上面，只為了爭權奪利，只為了面子，而不是多做點所謂對人類更有幫務的事情。

其實中華文化中最有意思的就是歷史了，總是要有外敵的入侵跟壓迫，才有機會合併起來，變得更為強大。

一旦缺乏了外部的壓力，就又開始內鬥搞分裂。

甚至是都還沒有搞定外部壓力，只是稍微變得勢均力敵了，就開始又再內鬥。

少數那種無論任何時代都要內鬥跟自私自利的就不談了，都是人性的劣根性，說多都是淚。

其實如果真的要說，我很佩服中國近幾年的進步，至少在資訊上是越來越強的，只是人文素質還需要好好努力，並不是靠著武力跟恐嚇就可以治國，而是用技術去讓人低頭，用健全和平跟包容的社會制度讓人信服。

希望中國能早日走出封閉的世界吧。

**Comment by KeikoSong** [comment]
@AynRoark 關於簡體字的歷史問題，其實就跟很多歷史一樣，都只是歷史，至於真相如何？那是歷史學家跟有好奇心的人要關注的，對我來說，結論比較重要。

至於您說的前後矛盾，我認同。

其實我的思維就是一種矛盾，我渴望全世界不分人種都是和平的，但是每次看到各種國價新聞甚至是中國新舊政權的兩岸問題，都讓我覺得憤怒跟可笑。

OK，說到可笑，其實國際上太多新聞都讓我可笑。

有個夢想我知道是一種天真。

但是我希望這個世界會變成一個每天發生的新聞都是我們又取得了新的技術突破，讓人類過了更好的日子，可以了解更寬廣的世界跟宇宙，甚至是所到之處，所見之聞，都是美好的一面，沒有醜陋的人性黑暗。

這種想法很天真，我知道，所以我是個矛盾的人，每次看到又在吵種事情，沒上火就算了，當作沒看到，但是一旦又一連串爭執，實在是讓我看心煩意亂。

有些話，的確過分了點，不代表全中國人或者兩岸多數人的想法，但是希望，總有一天別再吵這種話題了，煩心。
