### ISSUE TITLE
刚买的专业版完全没用， 手机安卓版也是一打开就没有响应

### ISSUE THREAD

**Issue by Alierchen** [getlantern/forum#4959]
前天刚买的1年的专业版， 在电脑端显示能连接， 但没有用， 很卡， 连Google都打不开。
手机安卓版的一打开一会就没响应， 授权登入专业版后 都连不上网， lantern也一直在无响应状态。

**Comment by Alierchen** [comment]
怎么样才可以退钱

**Comment by Ricky-Tsang** [comment]
又一個被商業詐騙了

**Comment by ldzg** [comment]
我也想退款？哪里可以退？

**Comment by ylkjick532428** [comment]
给一个时间解决，一个月不解决要发起退款，问题是tmd19大都结束了。。。

**Comment by ddkf2001** [comment]
应该是5毛，前天早几天蓝灯笼就被墙了，你特么上哪儿买专业版去

**Comment by cooconwind** [comment]
我也是,国庆假期刚买的专业版..自从第一天用了之后,就不能再使用了...坑爹.

**Comment by fandeus** [comment]
可以判定这个人是假的购买者，除非他把购买凭证截图，或者邮件内容拿出来，不然吵着退钱的什么的，都是假的。
首先，这段时间，蓝灯有问题，任何一个人都不会购买已知存在问题的产品。然后，建议后面的人，你在购买蓝灯，或者其他的VPN，先试用，选稳定的。

**Comment by makotolove** [comment]
我也怀疑你们怎么买的，打都打不开，还买？

**Comment by truthandlove** [comment]
版主好！大家好！

凡是电脑里装有腾讯公司、360公司 和其它受到中国公安部认证的杀毒软件公司发布的产品（包括非杀毒产品），往往他们的电脑翻墙都受到监控和影响，这些电脑在十九大中国政府加强管控期间，要是能成功翻墙，往往是偶然，甚至连偶然的机会都没有。

翻墙前，我们一定要想清楚，遇到问题的时候，考虑是先向中国政府抗议剥夺公民自由上网的权力，还是肆意指责帮你翻墙的人无能而不是自己无能。我们力争做一个有人格，能信任其他善良的人的人。

**Comment by truthandlove** [comment]
版主好！大家好！
我是翻墙爱好者，代理多种翻墙产品。
对于最新的4.2.1版，很多大陆网友反映用不了，我们的一些用户起初也遇到这种情况，但是，按照下面的基本步骤做，所有相关用户都可以翻墙了。
1。利用蓝灯的uninstall删除，并检查相关文件夹是否确实删除。
2。删除C:\Users\yiwei\AppData\Roaming\byteexec\ 文件夹。
3。删除电脑里所有腾讯、360的相关软件，包括QQ、手机应用宝、杀毒软件。（在翻墙的电脑中，决不用中国大陆软件，可用小红伞、comodo等外国杀毒软件）
4。在任务管理器中观察还是否有 腾讯、 Tecent、360的软件，终止其运行，并彻底删除。
5。重新启动电脑，在用户管理中创建新的管理员帐号。
6。用该新的管理员帐号，进入windows，并用管理员身份安装最新版蓝灯。
7。进入youtube，播放美国高清视频。（我们的用户反映速度高于很多其它翻墙软件）
8。遇到问题的时候，考虑是先向中国政府抗议剥夺公民自由上网的权力，还是肆意指责帮你翻墙的人无能而不是自己无能。

**Comment by truthandlove** [comment]
版主好！大家好！
中国大陆最佳翻墙电脑环境推荐：
1。英文版windows7 ，可加中文语言包。
2。英文杀毒防火墙软件，可关闭微软自带defender和firewall。绝无中国大陆或外国与中国政府合作的软件商的软件。
3。新建管理员账户。

**Comment by cooconwind** [comment]
@fandeus  
这是我的收据号码..10月1号支付的.当天可以用,之后就用不了了.

Paymentwall付款收据（收据号码：w128782204)


交易 ID | 交易日期
-- | --
w128782204 | 2017-10-1 下午7:26 (GMT-5)
交易日期 | Price
两年套餐 | 336.00 CNY
Total 336.00 CNY
Charged amount: US $50.49

**Comment by Alierchen** [comment]
交易 ID	交易日期
w129547127	2017-10-12 上午5:31 (GMT-5)
交易日期	Price
一年套餐	216.00 CNY
Total 216.00 CNY
Charged amount: US $32.79
This payment is for getlantern.org
支付方式 AliPay

**Comment by Alierchen** [comment]
主要是手机版的都没响应。 之前免费版的都能用
