### ISSUE TITLE
买了1年专业版能换登录的邮箱吗

### ISSUE THREAD

**Issue by liujiayi771** [getlantern/forum#496]
实验室3个人一起买了1年的专业版，当时没想太多，是用其中一人的qq邮箱买的，但是我们可能会经常解绑设备（实验室和寝室都有电脑），才想到应该用一个公共邮箱买的，请问现在还能去改那个发验证码的邮箱吗

**Comment by ming27** [comment]
邮箱添错了了，没法收到验证吗，能修改邮箱吗？
