### ISSUE TITLE
mac已经恢复正常，安卓依然登不上。。。

### ISSUE THREAD

**Issue by 1soYang** [getlantern/forum#4984]
请在发帖前先按照蓝灯无法使用的解决办法 https://github.com/getlantern/forum/issues/1902 自行解决。自行解决问题通常只需要几十分钟。管理员调查解决问题需要几天至几周。请立即访问https://github.com/getlantern/forum/issues/1902 瞬间解决98%的问题

为了能在最快的时间内解决大家使用蓝灯遇到的问题，请各位用户严格按照发帖格式提交问题。

## 发帖格式
遇到的问题：请详细描述遇到的问题。如果描述不仔细，将无法调查

蓝灯专业版账号Email:  请提供登陆蓝灯专业版的email，免费版不提供技术支持。

应用内报告问题的时间:  请根据 https://github.com/getlantern/forum/issues/1840 在应用内上报问题，请填写专业版的email。请在帖子里注明报告的时间。

截图: 请提供有关问题的截图。 请把图片拖拽到这里。

----
请不要发只有邀请码没有其他内容的帖子,违反者将扣除所有赠送时间。具体见 https://github.com/getlantern/forum/issues/3773

**Comment by AlephAlpha** [comment]
同安卓，同登不上，而且一开就卡死。

**Comment by Pooh980219** [comment]
表示mac无法使用

**Comment by 1soYang** [comment]
mac更新最新版，可以用，网速稳定，已经用了有一会儿了

**Comment by greenyichang** [comment]
电信也好了，1080P油管，爽歪歪

**Comment by 1soYang** [comment]
手机端的吗？我手机能连上，但是一直一转圈圈……

**Comment by Pooh980219** [comment]
不可能把，难道是我宽带的问题？我用的长城，没卵用。失去服务器连接了，已经更新最新版本

**Comment by greenyichang** [comment]
电脑端可以了，手机端还不行

**Comment by hikycool** [comment]
电脑 mac 和 windows 都不行

**Comment by YaoBeiNaFuns** [comment]
mac刚开始行，现在不行了。还给我变成了普通用户？

**Comment by 1soYang** [comment]
我的mac还可以，正在刷ins，网速没之前稳定了

**Comment by sdfw3er** [comment]
手机端还是不行
