### ISSUE TITLE
我购买了专业版，获取的移动版lantern白屏闪退，如何解决？

### ISSUE THREAD

**Issue by cheakitout** [getlantern/forum#500]
小米手机（红米，型号HM1），安卓系统，版本4.2.1，手机已root，以前用lantern移动版的没问题，最近无法使用了，才发现开始收费了，我交了费，一年180，获取的移动版就出现白屏，闪退。

**Comment by p3rcya** [comment]
正在调查

**Comment by p3rcya** [comment]
请LZ使用这个版本，看看是否解决了？ 
[lantern-installer-3.0.7.apk.zip](https://github.com/getlantern/forum/files/360254/lantern-installer-3.0.7.apk.zip)

**Comment by p3rcya** [comment]
@cheakitout 现在应该已经修复了。如果还有问题，请报告型号和系统版本
