### ISSUE TITLE
登陆lantern，不能连接，还有若干问题

### ISSUE THREAD

**Issue by dianshineng007** [getlantern/forum#5028]
遇到的问题：系统：win10（x64）15063.674 ，chrome，按照“精华帖”彻底删除旧版lantern，下载安装新版4.2.1 beta2，用管理员权限安装的lantern，并用管理员权限启动的lantern，点击“显示蓝灯”进入页面后，首先购买的2年版lantern变成了“您本月的流量已经用完”；其次登陆不起google等；最后 点退出lantern，还有2个进程驻留在后台，要手动关闭。
蓝灯专业版账号Email:  527056971@qq.com

报告的时间：2017/10/15

截图: 请提供有关问题的截图。 请把图片拖拽到这里。
![1](https://user-images.githubusercontent.com/32742397/31577702-17a01d36-b146-11e7-9167-f9d2767057de.png)
![2](https://user-images.githubusercontent.com/32742397/31577705-19c93d0e-b146-11e7-8b73-1cca44db631f.png)

**Comment by kimomoki** [comment]
巨卡啊，连2秒断两分钟，一直显示"连接中"

**Comment by kimomoki** [comment]
我觉得现在这个样子还不如萤火虫，那个至少慢吞吞还能load出来，新版蓝灯断了就彻底换线了

**Comment by hulksuper** [comment]
一样的问题
