### ISSUE TITLE
关于交流群，我觉得某些人存在主观错误！

### ISSUE THREAD

**Issue by ghost** [getlantern/forum#521]
第一：我们确实是lantern吧官方交流群
           百度贴吧：lantern ，我们是吧务组，自己创建的QQ群，不叫lantern吧官方交流群叫什么？
           lantern吧官方交流群 和 lantern官方交流群 两码事，我不知道是不是你自己没有看清楚！

第二：我们上传的lantern3.0.6 确实为官方，甚至到现在都有很多人不相信lantern有PRO，
           你下载以后可以验证“数字签名”。

第三： 我们卖SS这是事实啊，我们不仅交流关于lantern的相关问题，还交流其他翻墙工具。
           有人需要购买稳定的代理，我们提供给他们有问题吗？
           我们有强买强卖吗？只不过我们这次推销的方式欠妥！

第四：之前我们在其他人无法正常使用lantern的时候，我们会推荐赛风、PAC代理、XX-NET等，
           如果实在不行别人要求需要一个稳定的，并且愿意给钱，我们就会推销给他SS。
           但是这次确实太过~

第五：“本论坛可进行任何关于蓝灯(Lantern)以及关于其它翻墙的讨论。........”
           这是吧规，我们有违反吗？

我们需要再次强调一点，我们卖SS是事实，
但是我们是一个翻墙交流群。难道交流群就只能交流免费的？

**还有一件事：
lantern官方相关工作人员已经入驻我们QQ群，我们会在第一时间，分享lantern最新版。
并且我们会告诉用户如果遇到lantern使用上的问题，特别是lantern pro用户，指引他们如何解决等。**

**如果各位还有其他问题，请随时告诉我们。
你不仅可以通过此论坛反馈lantern上的使用问题，更可以加入我们QQ群，了解其他翻墙工具。
至于lantern为什么转型商业化、以及更多lantern目前存在问题，我们会通过QQ群一些人的反馈，收集并汇报至lantern官方工作人员。**
## 
**至于QQ群安全性，我们也正在考虑使用“电报”等其他相对安全的方式沟通。
但是由于需要翻墙，无法及时在墙内获取信息。所以很无奈，我们暂时只能这样。**

**Comment by GD-HBX** [comment]
有无考虑G+社群？

**Comment by helloLC** [comment]
@GD-HBX 建过本群G+，而且G+也有个“lantern中文圈”。但是这种东西都在墙外，QQ群、贴吧是目前最有效、最及时获取信息的墙内途径，无奈lantern吧封了，之前QQ群也封过。
lantern刚发布3.0也是我们第一时间上传分享的，有些人连github都打不开，下载不了。只能用这种方式！

**Comment by wilon** [comment]
呵呵，非加官方俩字镀金，贴吧官方？
已举报该群

**Comment by EdwardAutumn** [comment]
@wilon 他们从来就不是官方，只是第三方，但是管理员非常不明智的加了他们的群，让他们光明正大的说自己官方，我也举报了。

**Comment by wcg928** [comment]
什么情况?

**Comment by p3rcya** [comment]
@helloLC 请不要说这个是官方群。 
@EdwardAutumn 我加入群是为了方便收集用户反馈，不是说让它成为官方群

**Comment by shaomeng** [comment]
@helloLC 这不太厚道吧，去掉官方二字照样可以交流各种信息嘛。

**Comment by NAVrasZ** [comment]
吧务的官方相对于lantern开发官方确实是小一级不适合在这宣传
不过lantern吧以前里面的人挺热心倒是真的，希望Q群也是一样（已习得各种翻姿势我就没必要加了..）

**Comment by kxkxkx** [comment]
贴吧都封了，哪里来的所谓“蓝灯吧官方”？

贴吧官方封了你们的吧，没地儿卖ss了，呵呵，就来这发了，仅此而已。

把自己说的多圣母，就有多婊砸，目测这货为卖ss利用蓝灯当幌子，早晚跑路，估计还得蓝灯背锅，可怜被他骗的小白。

**Comment by kxkxkx** [comment]
商人逐利本无可厚非，君子爱财也应取之有道。
黑心奸商请离开这里，请还蓝灯论坛清净天空。
否则必将会人人唾骂，做金钱的奴隶这样不好！

**Comment by NAVrasZ** [comment]
@kxkxkx 管理员已禁止广告行为，莫激动~~另外不要屠版...

**Comment by helloLC** [comment]
@p3rcya 这个问题，我们已改正。

**Comment by helloLC** [comment]
@wilon @EdwardAutumn 我们再次强调：lantern吧官方交流群！ 如果存在误解，我们会改进！

**Comment by helloLC** [comment]
@NAVrasZ lantern吧创建者，最开始不是我们。你说之前lantern吧发的各种翻墙工具，其实就现在的lantern吧吧主以及QQ群群主。我们一直在管理贴吧和QQ群，最开始我们内部用SS多一些，最后就开始卖SS了。

**Comment by helloLC** [comment]
@shaomeng 不好意思，我们会改进的，以免大家误解！

**Comment by helloLC** [comment]
@kxkxkx 不需要你多说什么，也不需要你把自己说的多么高贵，更把别人贬低的一文不值。
               lantern收费，我从去年都知道，lantern会出问题，“情理之中”罢了！

**Comment by gagazx** [comment]
@EdwardAutumn lantern吧的吧务发的QQ群是lantern吧第三方QQ群？你真逗

**Comment by gagazx** [comment]
@kxkxkx 跑路？至今尚未跑路。相比于lantern这种年付，我更倾向于ss这种月付的翻墙软件。
