### ISSUE TITLE
移动网络蓝灯可以用了！  一起截图举报下这个开发票的

### ISSUE THREAD

**Issue by userfirstone** [getlantern/forum#5242]
举报下这个开发票的，想买蓝灯的可以输入我的邀请码（invitation code） YGV83WK   来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
![2](https://user-images.githubusercontent.com/32631032/31590487-85bccc8a-b243-11e7-827e-ad866fe00ed0.png)
![1](https://user-images.githubusercontent.com/32631032/31590488-85f00af0-b243-11e7-933d-2e291435f843.png)

**Comment by ssy341** [comment]
这个发广告的太猖狂了 ，我举报了电话号码，深圳移动的

**Comment by phihh** [comment]
我的也不能使用

**Comment by Atland123** [comment]
好像四川电信可以用来诶！！！

**Comment by CarlZhong01** [comment]
我建议呼死他。谁有短信轰炸的软件？

**Comment by szwx1314** [comment]
我的能用了，从早晨醒来到现在，安卓移动版速度一直不错，看视频无压力

**Comment by userfirstone** [comment]
我的安卓版版的用不了，电脑可以……

**Comment by manchuriasun** [comment]
安卓的还没更新么？

**Comment by userfirstone** [comment]
版本还是4.1.4
