### ISSUE TITLE
更新后用邮箱登陆，显示“无法根据以上信息找回账号”

### ISSUE THREAD

**Issue by 1021681638** [getlantern/forum#5256]
专业版账户，前几天不能用，后来更新到最新版，用邮箱登陆显示无法根据以上信息找回账号，是我的账户被注销掉了吗？
请管理员分析一下原因
我的账号yin9521@gmail.com
![abc](https://user-images.githubusercontent.com/27947294/31591734-de85c018-b254-11e7-9c22-022a3cee5897.jpg)

**Comment by 1021681638** [comment]
yin9521@gmail.com

**Comment by MartinCrewes** [comment]
还好我当时用的国内邮箱
