### ISSUE TITLE
坐标广州…蓝灯一直在连接中

### ISSUE THREAD

**Issue by apple2303** [getlantern/forum#5258]
前几天能连接上，但没用，所有网站都打不开
今天直接连不上了，论坛在电脑上也打不开
现在发的贴是用手机开了VPN才访问上的
真的是因为十九大吗！！！

**Comment by mythlegend** [comment]
没用360吧？我就是用了360所以才一直翻不了～

**Comment by apple2303** [comment]
浏览器是Chrome

**Comment by apple2303** [comment]
蓝灯登不上就算了吧，只要开了代理服务器，国内网站也上不了了，什么情况！！

**Comment by MICHE0714** [comment]
应该不关360的事情吧
我开着360浏览器和360卫士
一样上外国
只是我先使用遨游VPN连接台湾，然后打开蓝灯，这样蓝灯就正常连接了。
