### ISSUE TITLE
关于在蓝灯官方中文论坛宣传的QQ翻墙群

### ISSUE THREAD

**Issue by EdwardAutumn** [getlantern/forum#527]
@p3rcya
首先我对于作为管理员的你却对此无动于衷表示非常失望。在  #407 里你已提到该群是画面群并关闭了该问题，但是随后此人一直在不断发这个群的问题，你不仅没有惩罚他，反而加入他的群，让他可以堂而皇之的说自己群里有官方人员收集问题和意见，为他的广告群加上了官方商标。如果你想更好的收集问题，完全可以自己建一个QQ群，为什么要加他的广告群？包括我在内不止一个人提出此人是在群里卖ss,@kxkxkx@alivesong@wilon 为何忽略我们的意见？
蓝灯已经不再是一个单纯的免费开源软件，不管你怎么想，不管那些老外怎么想，不管你们心里有什么崇高的理想比如终结互联网审查等等，商业化就做出商业化的样子，让他在这里宣传他的群只会让其他人以为官方和这个卖ss的有合作，如果还以一个天真善良的免费开源软件姿态面对用户，你们不会在商业化道路长久走下去的。

**Comment by p3rcya** [comment]
@kxkxkx @alivesong @wilon @EdwardAutumn 感谢你们的建议。主要是我不喜欢随意删帖，而版规并没有禁止宣传QQ群。既然大家对这个群这么反感，我修改版规，禁止所有QQ群的宣传（除了以后我们官方建群外）。 

但是我会继续在 @panzer1313208 群中收集意见，除非他把我踢出来

**Comment by p3rcya** [comment]
@EdwardAutumn 我主要也是为了表明官方不会随意删帖这个态度。但是如果用户觉得那些类型的帖子不妥，欢迎报告给我。 谢谢你！

**Comment by EdwardAutumn** [comment]
@p3rcya  我也希望蓝灯能够发展的越来越好并且一直用下去，谢谢体谅我激烈的用词。

**Comment by p3rcya** [comment]
@EdwardAutumn 没关系。你为论坛考虑而这么动气，谢谢了！我们一定会虚心接受用户建议的。

**Comment by paperbag** [comment]
@p3rcya 
赶脚你被利用了一把啊，然后你的身份还被卖了。

**Comment by p3rcya** [comment]
@paperbag 用户开心就好。我新注册的帐号，并使用编程随想君提供的多重代理方案，朝廷一般查不到

**Comment by paperbag** [comment]
@p3rcya 
上个月去过你博客，RESOURSE就有某墙外著名博客，可以猜出你是他的读者。

**Comment by ClydeChenT** [comment]
那我们在这里留言会不会被上头查到IP并封掉。细思极恐！ @p3rcya

**Comment by p3rcya** [comment]
@paperbag 我读了多年了。就是我当时建议他到Github建一个Repo，方便境内用户访问。到如今引发了中国对Github发送删帖指令。呵呵

**Comment by p3rcya** [comment]
@ClydeChenT 不会。因为到Github是加密的，而且Github还是比较有骨气的，不会泄漏私人IP。除非你Github帐号被攻破，没有问题

**Comment by ClydeChenT** [comment]
@p3rcya 哦！感谢科普~

**Comment by EdwardAutumn** [comment]
@ClydeChenT 论坛是全程https加密，监听只能看见你在访问github，并不知道你在做什么，再者网警的主要目标是管理员，不是我们。

**Comment by p3rcya** [comment]
@EdwardAutumn 看来我要每天上来报个平安。

**Comment by EdwardAutumn** [comment]
@p3rcya 其实我也想研究研究lantern，最近项目比较闲，但是想起好几个github作者被请去喝茶的世纪，我还是怂了，出钱支持一下算了。

**Comment by p3rcya** [comment]
@EdwardAutumn 哎。。谢谢了

**Comment by paperbag** [comment]
@p3rcya 
关于那个repo，这很collateral freedom....

@ClydeChenT 
GitHub是米国加州旧金山的公司，其次全程使用了HTTP加密。另外呢GitHub里Setting->Security-->Security history还是可以查自己登录IP的哈，实在怕盗号的，可以开Two-factor authentication.本来偶们只是上上Google，查一些资料而已，又木有颠覆国家政权，寻衅滋事什么的，慌啥。

**Comment by panzer1313208** [comment]
卖SS是用户提出的不谢，他们无法用蓝灯，还不能让他们追求速度买其他的收费代理是么？

**Comment by panzer1313208** [comment]
#543 #541 请问你们在看到这些帖子的时候做过什么？看到我卖SS就全出来了？嗯？

**Comment by jeromekai** [comment]
天朝呀，网络天天限行，欲哭无泪
