### ISSUE TITLE
怎样退款？去哪投诉他？

### ISSUE THREAD

**Issue by mattins** [getlantern/forum#5271]
大家来联合起来投拆他

**Comment by 271873489** [comment]
失了智，

**Comment by wuliaowuliao** [comment]
我电脑用最新版的4.2.1 用了两天半了 速度给力 感谢蓝灯团队的程序员  你们辛苦了

**Comment by beboyss** [comment]
去法院，记住不要去中级法院，要去最高法院

**Comment by chihya72** [comment]
注意。这个软件是米果来的。就算你想退也退不了

**Comment by hadow** [comment]
建议楼主去工信部，或许会得到一个满意的答复

**Comment by ZimmerWu** [comment]
去中宣部吧，肯定可以得到一个满意的答复。

**Comment by Jerry9394** [comment]
哈哈，我们翻墙上网本来就犯法的，还去法院投诉？

如果蓝灯真的搞不掂或放弃了，只能自认倒霉了。我也是刚买了2年专业版的，当天买，当天就开始用不了，连续几天无法用，气死了。退款无门，也是只能认栽了。今天还算是能用了，但估计坚持不了多久。
