### ISSUE TITLE
登陆提示“无法根据以上信息找回账号”

### ISSUE THREAD

**Issue by 1021681638** [getlantern/forum#5279]
专业版账户  yin9521@gmail.com
管理员求解决
我是专业版不是免费版，之前有注册账户，还有两年呢，账号没了？看别人都能用我很着急啊，
哭

**Comment by Jerry9394** [comment]
偿试重新下载最新版软件吧。

我是刚买了2年专业版就马上用不了了，今天才开始有一点点正常，但手机版的还不能用。

**Comment by 1021681638** [comment]
我下载的是最新版的，显示：无法根据以上信息找回账号，所以我才发帖的

在 2017/10/16，Jerry9394<notifications@github.com> 写道：

**Comment by 1021681638** [comment]
蓝灯目前能用，但是专业版账户登陆不上去！！！！显示：无法根据以上信息找回账号
![image](https://user-images.githubusercontent.com/27947294/31598301-6fcb9c76-b27f-11e7-82d2-f56100782091.png)

**Comment by 1021681638** [comment]
是账户不存在了吗？
