### ISSUE TITLE
好高兴啊，终于可以上了，速度大大的。版本4.2.2 联通

### ISSUE THREAD

**Issue by shuizhe** [getlantern/forum#5327]
经历了一天的默默等待。

**Comment by shuizhe** [comment]
![tim 20171016183414](https://user-images.githubusercontent.com/32829899/31607853-a99549c2-b2a0-11e7-9324-25b2e808b10b.png)

**Comment by shuizhe** [comment]
![tim 20171016183555](https://user-images.githubusercontent.com/32829899/31607926-e6c993b6-b2a0-11e7-8134-eb80ac7c0a4c.png)
这啥速度，真他奶奶的快！

**Comment by sunrui230601** [comment]
你好，截图上面的参数从哪能看到？

**Comment by shuizhe** [comment]
视频右击 就可以看到了啊

**Comment by GunsN-Roses** [comment]
电信WIF还是不能用

**Comment by jimwoo2008** [comment]
请问楼主：如何安装新版本呢，需要先卸载旧版本吗，安装之后会自动登录专业版吗，谢谢

**Comment by shuizhe** [comment]
装的联通的宽带，杭州，就是在这里下载的最新版本，win7直接安装的没有卸载，能上挺快！到目前为止正常。macbook也是在这里下载的，刚刚很顺畅，目前卡了。安卓能上，速度不理想。测试都是在联通宽带下做的。

我勒个去不能夸啊，就在刚刚卡主了，上不了了，只能说目前还不稳定。

**Comment by shuizhe** [comment]
哎呀  咋这么不稳定啊，刚高兴了下，就给我泼冷水

**Comment by jimwoo2008** [comment]
谢谢，已经连上：）

**Comment by jyufeng** [comment]
哪里下载的422？

**Comment by shuizhe** [comment]
就在这里下的
