### ISSUE TITLE
[最新版下载地址] 请不要再劳烦管理员了

### ISSUE THREAD

**Issue by johnwatsondev** [getlantern/forum#5376]
👿 is in the detail

其实管理员所有的公告中的文件都来自这个 [repo](https://github.com/getlantern/lantern-binaries)。

我们可以查看 commit 历史知晓是否有更新。

Let's fu*k GFW forever.

**Comment by YangJun16** [comment]
请问4.2.4哪里下呢

**Comment by JellyWang7** [comment]
https://github.com/getlantern/lantern/releases

**Comment by qqgmail** [comment]
然而并没有更新

**Comment by johnwatsondev** [comment]
反正我是能用了。:) 
![lantern](https://user-images.githubusercontent.com/12760754/31652761-d90b5b8e-b2e5-11e7-8da4-8b35a8056d61.jpg)

版本号不更新不代表不更新软件本身。@qqgmail @jyufeng @YangJun16

**Comment by jyufeng** [comment]
@johnwatsondev下载了查看数字签名是20171013的，软件根本没有更新哦。

**Comment by YangJun16** [comment]
我又去确认了一下 没更新好吧 @johnwatsondev ！

![819b2da6-740f-41ef-9105-378842ff2db6](https://user-images.githubusercontent.com/14892774/31714723-c9a8cd6c-b433-11e7-99ea-b244143085c2.png)

进去发现！！

![318ffaa0-aa45-45e9-bab0-07ac17571010](https://user-images.githubusercontent.com/14892774/31715343-0d687960-b436-11e7-819c-4e74b12b56fb.png)

**Comment by zhangminglei** [comment]
能用的话，请说明一下你的基本配置是什么，什么系统，什么ISP,等等。这样才有参考性。以及什么地区的

**Comment by johnwatsondev** [comment]
https://github.com/getlantern/lantern-binaries/commit/903574b8ac52fbe3f756c512cefb0ac1a2ec9172

请问下 lantern-installer.dmg.sha256 为什么会变？@YangJun16

**Comment by johnwatsondev** [comment]
macOS Sierra 10.12.6
杭州电信
@zhangminglei

**Comment by zhangminglei** [comment]
是啊，每个人的版本都不一样，所以不具备参考性啊。只有同版本，同地区，同环境下对比才有意义。






在 2017-10-19 10:24:52，"JohnWatsonDev" <notifications@github.com> 写道：


macOS Sierra 10.12.6
杭州电信
@zhangminglei

**Comment by YangJun16** [comment]
人家改了代码还能顺带更新你的？4.24独你一份 可能你是天选之子吧 分享一下你的来源和成果呗 顺便拜个早年 祝你身体健康 @johnwatsondev 。

**Comment by johnwatsondev** [comment]
```shell
# johnwatson @ jwdev-mbp in ~ [17:37:34]
$ shasum -a 256 /ChromeDownload/lantern-installer-beta.dmg
fc62e01e170d50e0b5a6135b69cf97e33a1ce73dda6476d8c05eaa784b7666e0  /ChromeDownload/lantern-installer-beta.dmg

# johnwatson @ jwdev-mbp in ~ [17:37:51]
$ shasum -a 256 /ChromeDownload/lantern-installer.dmg
fc62e01e170d50e0b5a6135b69cf97e33a1ce73dda6476d8c05eaa784b7666e0  /ChromeDownload/lantern-installer.dmg
```

![jietu20171019-174251 2x](https://user-images.githubusercontent.com/12760754/31764839-03892460-b488-11e7-80a9-dec77c8fa5ee.jpg)

不用谢 :)

**Comment by YangJun16** [comment]
心虚急着关闭答案了？BB了半天 上个蓝灯版图截图那么麻烦 intel dis @johnwatsondev

**Comment by YangJun16** [comment]
回了那么多 有点干货没 里面打开还是4.2.1-beta2 上面有人都说了 还在装什么装 上个蓝灯版本截图很难？急着关闭 心虚撒呢 麻烦别at我了 拉低我的智商 @johnwatsondev ！
![8b667258-8f52-4ea9-a364-affa03f157a4](https://user-images.githubusercontent.com/14892774/31768328-7aed8e96-b501-11e7-8600-32131384aa76.png)

**Comment by lxiaoy605** [comment]
@johnwatsondev 试过了，还是不行的,没有反应的！
