### ISSUE TITLE
有人安装过lantern 4.2.4 吗？

### ISSUE THREAD

**Issue by JellyWang7** [getlantern/forum#5386]
https://github.com/getlantern/lantern/releases/tag/4.2.4

想知道有人试过安装这个吗？怎么安装？好用吗？

看了各种帖子也试过安装各种版本但是最后安装好显示的还是4.2.1-beta2
各种卸载重装，修改DNS，各种方法试了一圈都还是不行，也试了几次报告问题
虽然显示已连接而且我也买了专业版，而且也是服务器显示的也是在日本的但是就是打不开youtube，google doc这些
心累啊，求大神帮忙

update:
用Chrome就没有问题，Firefox就不行，原因不明，反正总之现在总算搞定了

Update 2.0：
Chrome 和 Firefox都可以用了，感谢工作人员也谢谢热心帮我的各位！
如果有朋友和我一样Firefox打不开的话就是只要手动设置代理端口就行了，问题马上解决了
----------------------

**Comment by CNthomaslea** [comment]
电脑改DNS后应该是可以用的，手机不太稳定，昨晚我电脑成功后安装手机版4.2.1Bate2 也短暂可用，进lay商店更新了几个APP （包括4.2.2），手机新版本4.2.2就不能用了

**Comment by MayaGates** [comment]
安装包的签名和指纹都是和4.2.1Bate2一样的，应该是版本回退了。

**Comment by leyunhua** [comment]
手机装了4.2.2 出不去

**Comment by MayaGates** [comment]
firefox有个安全插件删除就可以了

**Comment by JellyWang7** [comment]
@MayaGates 谢谢你一直回复我的问题
只是查了一下我的Firefox没有安装任何安全插件耶

**Comment by harlemyin** [comment]
FF如果不是使用系统代理的话，需要自己设置蓝灯端口的

**Comment by JellyWang7** [comment]
@harlemyin 非常感谢，现在好了
