### ISSUE TITLE
花了180开了一年专业版网速慢的要命

### ISSUE THREAD

**Issue by blackwater117** [getlantern/forum#543]
前两天听同学介绍开的，家里是20M的电信光钎宽带，说好的不限速呢，用youtube看UFC卡的真是不要不要的，最低画质都卡，我要怎么说。测试了一下全代理的网速，只有100kb/s，这要怎么办，我的180难道就这样白花了。希望作者尽快解决这个问题。

**Comment by zhaojingwei666** [comment]
我的总是断断续续的，一会可以用，一会又掉线了

**Comment by blackwater117** [comment]
我的虽然很慢但是不掉，是不是算一种安慰了……上google搜索，每次都要输入防机器人验证码，也真是够了。

**Comment by zhaojingwei666** [comment]
我看YOUTUBER卡的不行

**Comment by panzer1313208** [comment]
你们的问题，找这个人解决，@EdwardAutumn @paperbag

**Comment by paperbag** [comment]
@panzer1313208 
呵呵，艾特我干嘛。我又不是lantern开发成员，也不可能是。既然你这么空，你可以满整个issue啊。
要卖ss，还要绑架别人，真有商业头脑。

**Comment by NAVrasZ** [comment]
我又又又看见了电信宽带（手动滑稽），之前我电信50M都看不了高清，某巨巨解释是上传太慢/丢包导致和服务器通讯很差.

**Comment by kiiiw** [comment]
您好，

    真的万分感谢团队的开发，让我们可以有机会免费使用到lantern软件。最近很想购买lantern的付费版，但是考虑到中国的整体环境，我会担心我购买了一年的软件，却不能享受一年的服务。。不知道团队是否可以考虑按月支付。。谢谢您的理解。。也希望团队可以回复我的问题。


   顺祝lantern帮助更多的人翻过长城，走向世界。GOD BLESS YOU.

**Comment by panzer1313208** [comment]
@paperbag 别人不能用蓝灯，所以我卖SS。你们不是说我卖SS，对我进行一系列攻击吗？你们不是天天看到我发群号就来攻击我吗？怎么你们出了会攻击我之外，别的什么都不会？

**Comment by panzer1313208** [comment]
别人买完蓝灯不能用，想退钱也没人退，我卖SS怎么了？我SS很良心，这就够了。公道自在人心。

**Comment by panzer1313208** [comment]
况且我是给那些无法翻墙的人卖SS。另外有一些人是追求速度的。

**Comment by paperbag** [comment]
@panzer1313208 
在这个issue前，我貌似没对你人身攻击吧。
另外，拿别人ss的源码为自己赚钱道德上的确是很高尚的。

**Comment by blackwater117** [comment]
大家别吵架，我就是想向制作者反映一下问题 ，希望能够尽快解决，引战真不是我想要的

**Comment by panzer1313208** [comment]
@paperbag 要不要我把链接贴出来，看看那些对我进行过人身攻击的人？

**Comment by panzer1313208** [comment]
@blackwater117 哥们，我之前在这里发群号，让所有有问题的人加我的群去解决，然后一群人说我发广告，说我卖SS，对我进行人身攻击。我真的笑了，我告诉你啊，蓝灯专业版速度慢的解决方法就是去买SS，别无他法，你看看论坛里多少有问题，多少想退款的人，他们得到的解答，基本上都是请上传log。然后基本就没下文了。

**Comment by p3rcya** [comment]
@blackwater117 网速慢的问题我们已经在解决了
