### ISSUE TITLE
买过蓝灯却不能用的人请看这里。

### ISSUE THREAD

**Issue by panzer1313208** [getlantern/forum#546]
没错，看这里！

**Comment by panzer1313208** [comment]
说出你们的问题，我来解答。

**Comment by 7pitter** [comment]
网速慢、不稳定

**Comment by jaywongchina** [comment]
打开lantern，无法翻墙，退出了后，国内网站也上不去，还得手动将网络的代理设置还原，才能上网。

**Comment by senea** [comment]
twitch和youtube看视频直播看不了，一直转圈圈？可以申请退款吗？

**Comment by panzer1313208** [comment]
@7pitter @jaywongchina 网速慢不稳定，为何不来我群里？我群里有pac等等方法你们都试试啊

**Comment by panzer1313208** [comment]
@senea 退款估计是不太可能了= =

**Comment by panzer1313208** [comment]
群号215060051

**Comment by panzer1313208** [comment]
你们加我QQ吧，569532421

**Comment by senea** [comment]
@panzer1313208   我就想知道是什么问题，看不了视频和直播，

**Comment by panzer1313208** [comment]
@senea 能看网页？

**Comment by kxkxkx** [comment]
![qq 20160712212220](https://cloud.githubusercontent.com/assets/16475312/16768409/da87610e-4876-11e6-8adc-e576bc78d208.png)
![qq 20160712212211](https://cloud.githubusercontent.com/assets/16475312/16768408/da83ed4e-4876-11e6-91b7-cc91e2c5f67b.png)

小白注意不要被骗不要加群

**Comment by senea** [comment]
@panzer1313208   网页能打开，就是看不了视频，20M以上电信光纤，华南地区

**Comment by panzer1313208** [comment]
@kxkxkx 小伙子注意暴露了，

**Comment by panzer1313208** [comment]
@senea 那不应该啊，

**Comment by panzer1313208** [comment]
![1](https://cloud.githubusercontent.com/assets/13449426/16770003/82255924-487d-11e6-9965-eae09ae38451.png)
![2](https://cloud.githubusercontent.com/assets/13449426/16770006/85b31b6c-487d-11e6-894b-acc70922b314.png)
![3](https://cloud.githubusercontent.com/assets/13449426/16770009/887e95b0-487d-11e6-8a4d-350cfda3e387.png)
![4](https://cloud.githubusercontent.com/assets/13449426/16770012/8ac60ec0-487d-11e6-80b7-4a08c4ed1522.jpg)
![5](https://cloud.githubusercontent.com/assets/13449426/16770014/8ca9b98a-487d-11e6-90f2-838c9f552f37.jpg)

**Comment by panzer1313208** [comment]
这就是所谓的免费SS？

**Comment by ssy341** [comment]
@panzer1313208  我新手 ss 是什么 能科普下么？

**Comment by panzer1313208** [comment]
@ssy341 一种类似于VPN，都是别人买VPS搭建的，SS本身是没有官方的。因为软件制作者并不卖。像lantern这样的网页代理，但区别是lantern的作者卖，而SS本身是免费的需要别人去买VPS搭建。

**Comment by ssy341** [comment]
@panzer1313208  ss 有英文全称么？

**Comment by panzer1313208** [comment]
@ssy341 全称是Shadowsocks

**Comment by panzer1313208** [comment]
开源的软件，

**Comment by panzer1313208** [comment]
不过作者被查水表了，也是github里的。

**Comment by panzer1313208** [comment]
所以现在都是用ShadowsocksR

**Comment by 79liue** [comment]
刚刚购买，开关打开没什么反应

**Comment by panzer1313208** [comment]
@79liue 恭喜你被坑了。

**Comment by 79liue** [comment]
好吧😓

**Comment by panzer1313208** [comment]
#79liue 你先加我群试试免费的翻墙方法，等待以后的蓝灯版本吧。

**Comment by 79liue** [comment]
等官方解决吧～不太喜欢加群～谢谢了

**Comment by panzer1313208** [comment]
@79liue 那你等着吧，3个月之内应该会解决

**Comment by 79liue** [comment]
好的～😊

**Comment by panzer1313208** [comment]
@79liue 这个论坛里有几个人，说我发广告群号卖SS。你怎么看？

**Comment by 79liue** [comment]
看不明白，刚进来～另外也不知道啥是ss

**Comment by panzer1313208** [comment]
@79liue SS就是一种类似于VPN的翻墙软件，软件制作者不卖，都是其他人自己买服务器自己弄，然后卖。

**Comment by panzer1313208** [comment]
也就是说你必须要买国外的服务器，才能搭建SS。

**Comment by panzer1313208** [comment]
然后把，我在这里宣传QQ群，然后QQ群里有人想买SS，所以我就卖SS了。

**Comment by panzer1313208** [comment]
但是群里主要是翻墙群，有很多翻墙方法，所以主要买SS的人都是安卓和苹果等手机用户。

**Comment by panzer1313208** [comment]
然后有几个人就说我是骗子，在这里发广告之类的。

**Comment by 79liue** [comment]
搞不清楚，现在用的别的，Mac端比较麻烦，快到期了朋友推荐这个买个试试～不好用就还用原来的～希望能快点好起来吧～加油～

**Comment by panzer1313208** [comment]
@79liue MAC端？用xxnet试试

**Comment by 79liue** [comment]
不折腾了，谢谢
