### ISSUE TITLE
在支付过程中产生错误？？

### ISSUE THREAD

**Issue by zxc413763686** [getlantern/forum#548]
怎么办                留下激活码

**Comment by panzer1313208** [comment]
建议你看一下这个论坛里有多少人反映不能用，有多少人想退钱然后不给退。

**Comment by zxc413763686** [comment]
我已经买了    非常好用  youtube 3M/s ？？？

**Comment by panzer1313208** [comment]
那挺好。

**Comment by panzer1313208** [comment]
#538 #535 #532 #528 #526

**Comment by zxc413763686** [comment]
你应该是专门黑这个软件的吧

**Comment by panzer1313208** [comment]
@zxc413763686 #538 #535 #532 #528 #526

**Comment by panzer1313208** [comment]
我作为lantern吧的吧主，黑lantern？你想多了。

**Comment by panzer1313208** [comment]
这个软件有许许多多的问题，这都是有目共睹的，比如什么关掉lantern之后无法使用IE、无法玩游戏。

**Comment by panzer1313208** [comment]
比如什么打开软件之后没有效果，一直转圈，上不了谷歌。

**Comment by zxc413763686** [comment]
我是在询问如何付款

**Comment by panzer1313208** [comment]
@zxc413763686 自相矛盾？
![2 pq yiucm 4skbhq yb8](https://cloud.githubusercontent.com/assets/13449426/16772068/4fdc71e8-4885-11e6-8d1f-d0cd39e3e1e3.png)

**Comment by panzer1313208** [comment]
买了没付款？

**Comment by zxc413763686** [comment]
我用以前用的VPN那种根本没这个好  我用免费流量都可以很好  所谓才要买

**Comment by zxc413763686** [comment]
怎么截图 要我给你看下网速吗？

**Comment by panzer1313208** [comment]
买了没付款？？

**Comment by zxc413763686** [comment]
你看我标题是什么 我是在问付款不成功   我不是想听你废话

**Comment by panzer1313208** [comment]
![hcg l 0ax5w g0a doj4t](https://cloud.githubusercontent.com/assets/13449426/16772130/86f71dcc-4885-11e6-86cf-3f9468fc47fc.png)

**Comment by panzer1313208** [comment]
付款不成功，请问你为什么要说已经买了？付款不成功你是怎么买的？

**Comment by panzer1313208** [comment]
@zxc413763686 解决办法就是艾特管理员，让管理员修复软件。

**Comment by zxc413763686** [comment]
![qq 20160712230734](https://cloud.githubusercontent.com/assets/20420483/16772174/c1e941e4-4885-11e6-8059-de972a6af1b6.png)
早在我回复你的时候 已经付款成功了

**Comment by zxc413763686** [comment]
![qq 20160712230705](https://cloud.githubusercontent.com/assets/20420483/16772214/edaf8946-4885-11e6-958d-205c4185d027.png)

**Comment by zxc413763686** [comment]
你自己对一下日期吧

**Comment by panzer1313208** [comment]
恭喜你。

**Comment by zxc413763686** [comment]
![qq 20160712231055](https://cloud.githubusercontent.com/assets/20420483/16772274/38f98ffa-4886-11e6-9962-a87d36b439b9.png)
