### ISSUE TITLE
揭发本社区里的qq骗子群

### ISSUE THREAD

**Issue by nengliang** [getlantern/forum#550]
管理员在吗 在您这里看到的翻墙互助群 被踢了

原来翻墙互助群是为了卖ss 

![qq 20160712220217](https://cloud.githubusercontent.com/assets/20421090/16769764/9868f11a-487c-11e6-8eeb-57a3eaab4eea.png)

![default](https://cloud.githubusercontent.com/assets/20421090/16770330/1de935f0-487f-11e6-846a-f3ba1fb7b97c.jpg)

**Comment by nengliang** [comment]
大号拉人 小号踹人 这买卖呵呵

**Comment by panzer1313208** [comment]
我T的？我小号？

**Comment by panzer1313208** [comment]
你去群里问问。是我小号吗？

**Comment by panzer1313208** [comment]
欲加之罪何患无辞？

**Comment by panzer1313208** [comment]
![1](https://cloud.githubusercontent.com/assets/13449426/16770974/834b6e20-4881-11e6-9b59-24315c62e32f.png)
![2](https://cloud.githubusercontent.com/assets/13449426/16770978/86535344-4881-11e6-9a93-4a4c07a68d42.png)
![3](https://cloud.githubusercontent.com/assets/13449426/16770981/89026f12-4881-11e6-926e-795e0b7279ad.png)
![4](https://cloud.githubusercontent.com/assets/13449426/16770984/8b8dcfb0-4881-11e6-9b45-845e583853f0.jpg)
![5](https://cloud.githubusercontent.com/assets/13449426/16770986/8d8acd5e-4881-11e6-9122-7352d16caef7.jpg)

**Comment by panzer1313208** [comment]
这就是你说的免费SS？

**Comment by panzer1313208** [comment]
我卖SS是因为别人买SS，要不要我截图下？

**Comment by panzer1313208** [comment]
![1](https://cloud.githubusercontent.com/assets/13449426/16771180/202df8e8-4882-11e6-811a-248f100e307a.png)
![2](https://cloud.githubusercontent.com/assets/13449426/16771183/21b324fe-4882-11e6-9366-5a4feb77c5a8.png)
![3](https://cloud.githubusercontent.com/assets/13449426/16771188/237270b0-4882-11e6-91d4-ad04206c3b61.png)
![4](https://cloud.githubusercontent.com/assets/13449426/16771191/2513df9e-4882-11e6-93d2-7cc8c8218da7.png)

**Comment by panzer1313208** [comment]
别人要买SS我为什么不卖？

**Comment by panzer1313208** [comment]
你不就是看到我损害了你的利益么？呵呵

**Comment by nengliang** [comment]
看管理员是否允许让你在这儿发广告吧

**Comment by panzer1313208** [comment]
@nengliang 你怎么不说这么多人不能用，管理员为什么不解答呢？

**Comment by panzer1313208** [comment]
@nengliang 你怎么不说这里这么多人想退钱，管理员不给退呢？

**Comment by panzer1313208** [comment]
@nengliang 一开始允许，然后这几个人一直在论坛里拿我卖SS说事，说我发QQ群是发广告之类的。

**Comment by p3rcya** [comment]
现在已经禁止发广告。 如果有人在看到 @panzer1313208 发广告，欢迎向我举报。我会ban他

**Comment by p3rcya** [comment]
已经ban了 @panzer1313208
