### ISSUE TITLE
google scholar can't access

### ISSUE THREAD

**Issue by pobingwanghai** [getlantern/forum#5512]
google report:
We're sorry...

... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.
test issues:
without lantern ,can access to scholar, with lantern, report error.
so it is not the problem of my internet or computer, it is a bug of lantern

**Comment by Restlessness** [comment]
I have this problem too

**Comment by Nz666-Kshatriya** [comment]
Personal network ￥15 permonth contact Wechat: kashatriya

**Comment by cryobeer** [comment]
I have the same problem too!

**Comment by studyself** [comment]
the same problem.
How to fix it?
