### ISSUE TITLE
建议能不能开个微博账号

### ISSUE THREAD

**Issue by xhfc** [getlantern/forum#557]
建议开个微博账号，有问题反馈比较方便，有活动或者软件有问题的时候也可以发公告。

**Comment by p3rcya** [comment]
微博会被封。请牢记论坛地址

**Comment by xhfc** [comment]
云墙那家就有微博账号啊...不过既然你这么说那就不勉强了

**Comment by xhfc** [comment]
为什么下载了电脑端最新版，安装了之后电脑还是上不了外网

**Comment by p3rcya** [comment]
@xhfc 请按照此帖上传log https://github.com/getlantern/forum/issues/358 ，方便我们调查，谢谢
