### ISSUE TITLE
蓝灯专业版更新到4.2.5终于可以正常使用了

### ISSUE THREAD

**Issue by lweiandroid** [getlantern/forum#5579]
查看https://github.com/getlantern/forum/issues/1902，安装最新版本蓝灯，目前是4.2.5，终于可以正常使用了。
![image](https://user-images.githubusercontent.com/13897169/31810633-14bdf332-b5af-11e7-85a4-86aae26982ff.png)

**Comment by qizhiqiang1** [comment]
安卓还是不可以

**Comment by qizhiqiang1** [comment]
连接打不开，有没有最新的

**Comment by shiwanxin** [comment]
没有问题可以用
