### ISSUE TITLE
问下官方，为何付费通道还开着，好多人掉进坑里，要脸不

### ISSUE THREAD

**Issue by RenCB** [getlantern/forum#5642]
好多人还不知道你们挂了，你们官网吹牛逼的标语就不能换个公告吗，不换也行，能把付费通道关了吗，别坑人了好吗，是想捞一笔跑路吗？

**Comment by ningqivip** [comment]
稳如跑路

**Comment by MICHE0714** [comment]
是啊 ,我也奇怪,怎么还开着收费通道,这......坑人

**Comment by Ricky-Tsang** [comment]
干你母！！！！！

**Comment by RenCB** [comment]
@Ricky-Tsang  你他妈是狗？s傻逼东西，没看到老子关了问题了？难道是老子操你妈比的时侯把你狗眼操瞎了？
