### ISSUE TITLE
一个开源软件改成收费的，出于什么原因

### ISSUE THREAD

**Issue by shangxinbo** [getlantern/forum#570]
我只问一下原因，不爱，另p3rcya这家伙是哪根葱

**Comment by wz7465** [comment]
猪养肥了要宰，商业规律

**Comment by p3rcya** [comment]
我是蓝灯官方的工作人员。请看我这帖 https://github.com/getlantern/forum/issues/378 中说为什么要收费

**Comment by wz7465** [comment]
一件事物，自然有两种话语体系，官方人员自然官方语系喽，其实大家都懂。我认为免费共享精神只扎根于个人，蓝灯一开始就是商业化组建的团队，收费其实无可厚非，只是在软件远未进入稳定期，不能提供可靠服务就急急推出收费，吃相难看了点

**Comment by kaychenl** [comment]
同意楼上

**Comment by zsqp447** [comment]
说的好像开源就一定是免费似的

**Comment by 7pitter** [comment]
@wz7465 同意

**Comment by ShangXinbo** [comment]
@p3rcya #378 这个只说明了专业版和免费版的区别，请不要扭转话题，请直接回答为什么要收费

**Comment by p3rcya** [comment]
@ShangXinbo 里面不是写了么？
2.近期GFW工作人员搞很多个IP来检测蓝灯的IP，进行封锁。专业版需要付费，GFW就没办法一下子注册很多帐号，来批量封锁IP。所以付费能有效抵御GFW的封锁。
3.专业版支持meek等一些特殊的翻墙协议。因为这些协议耗费大，或者是被广泛使用后GFW会封锁，只有专业版才能使用。

**Comment by joefei** [comment]
路人表示，linux不是也有收费版本么。而且蓝灯这类软件的核心是服务器和流量。如果维护者不再提供服务器和流量，那这开源软件也就废了。

**Comment by p3rcya** [comment]
@joefei 谢谢你的理解

**Comment by bannedbook** [comment]
免费是良心，收费也是正常，毕竟都要生存。免费的也有很多选择，比如可以用[GoAgent翻墙](https://git.io/fanqiang)

**Comment by tuchangwei** [comment]
支持收费。现在为了翻墙，买了一个VPN和一个VPS。VPN要不经常断，要不国内速度慢，VPS只能用浏览器走SSH。都很费心。

lantern免费了那么久，已经很感激，一定要付费支持下。

也希望lantern越来越好。

**Comment by wz7465** [comment]
立足自力更生，不断学习，如今自建服务器，稳定高速翻墙，用足带宽30m，无限流量，关键这一切还是完全免费的，爽翻了！

**Comment by sjemohx** [comment]
@wz7465 老司机求上车啊！

**Comment by wz7465** [comment]
想完全免费？别想了，独乐乐才叫爽！至于那些有vps的，如果还翻不爽，我也只能无语了

**Comment by 1102568869** [comment]
买个HK,JP,UK,USA随便哪儿的VPS,小供应商价格低至30元不到,自己搭建一个VPN服务器,独享带宽,妥妥的,关键这只是附加服务啊,VPS本身还能用来跑应用,博客,私服,乱七八糟的啊,还不用备案域名!

**Comment by itgoyo** [comment]
啥？lantern开源？你是什么时候知道这个软件的？商业闭源好几年了
