### ISSUE TITLE
隔壁赛风都努力在恢复了，蓝灯呢？

### ISSUE THREAD

**Issue by wangchunming** [getlantern/forum#5719]
隔壁赛风自从2017年10月11日发出网络被攻击声明开始就一直在努力恢复，只要确保你所在网络亚马逊存储可以直接连接的情况下，就可以正常连接了，翻墙已经不是问题了。（中国移动除外，因为已经墙了亚马逊存储了）
蓝灯这几天一直都没好，断断续续的，现在又不能用了。

**Comment by wangchunming** [comment]
另外近段时间自由门工作一直都正常。

**Comment by hayaya** [comment]
再封也挡不住国人看郭文贵视频

**Comment by thezzycom** [comment]
ssr呗 免费分享一下
ssr://MjMuMjQ3LjI1LjE3MTo0NDM6YXV0aF9zaGExX3Y0OmNoYWNoYTIwOmh0dHBfc2ltcGxlOmNYRXRjWFZ1TFRVeU9UQXhOamd6TkEvP29iZnNwYXJhbT0mcmVtYXJrcz01WVdONkxTNTZMU201WS0zVVZIbnZxUTFNamt3TVRZNE16UQ
