### ISSUE TITLE
请问登录不需要密码吗，会不会被别人盗用？

### ISSUE THREAD

**Issue by ddianxing** [getlantern/forum#5744]
刚刚升级到两年的PRO版，发现没有要求设置密码，这样的话账号会不会被别人盗用？

另外分享下我的邀请码，需要朋友可以使用…… Y6P8GJ

Use my code Y6P8GJ and get 3 months free when you sign up!

![sshot-1](https://user-images.githubusercontent.com/33029861/31923859-da180f02-b8af-11e7-8495-798961c9c7ba.png)

**Comment by thezzycom** [comment]
别人不能动你的设备就不会被盗，授权服务器在蓝灯哪里，如果被盗那就是蓝灯的问题，话说，你能用？

**Comment by BarbarianShield** [comment]
有时候需要邮箱的验证码

**Comment by shuizhe** [comment]
对啊  话说 你能用？
