### ISSUE TITLE
多种下载渠道支持deb版本的lantern

### ISSUE THREAD

**Issue by TimYi** [getlantern/forum#5800]
我是ubuntu的用户，也是lantern的付费用户。github下载lantern下载不了，希望在everynote等渠道上也添加deb包的下载支持。

**Comment by TimYi** [comment]
尤其是lantern最近失效，急需升级版本改善服务。

**Comment by Jerry9394** [comment]
本身服务器的问题，更新也没有，还是期望蓝灯赶紧把根本问题解决吧。

**Comment by WoNangbang** [comment]
我昨天装的ubuntu17.10

**Comment by TimYi** [comment]
买自己的亚马逊，自己搭vpn了，这样总不会被封了。
