### ISSUE TITLE
4.31版本在win10测试说明

### ISSUE THREAD

**Issue by kkdds2017** [getlantern/forum#5842]
请大家升级到4.3.1按照如下步骤操作：
升级后见版本号：
<img src="https://ws1.sinaimg.cn/large/6014db39ly1fkuuctardvj211w0hhq3h.jpg"/>
点击“”设置“”
<img src="https://ws1.sinaimg.cn/large/6014db39ly1fkuuc1ii5xj20ib0diaah.jpg"/>
务必不要勾选“”代理全部流量“”
测试目前比较稳定，360和一系列软件都关掉
再次说明，我是专业版用户啊

**Comment by kkdds2017** [comment]
<img src="https://ws1.sinaimg.cn/large/6014db39ly1fkuug2os2rj211w0hhq3h.jpg"/>
<img src="https://ws1.sinaimg.cn/large/6014db39ly1fkuugrgcc5j20ib0diaah.jpg"/>

**Comment by kkdds2017** [comment]
坐标，郑州 带宽移动宽带

**Comment by andylinsu** [comment]
没有找到下载4.3.1的连接啊 说是最新的下载完了还是4.2.5啊

**Comment by kkdds2017** [comment]
<img src="http://ww1.sinaimg.cn/large/6014db39ly1fkuv5vm52bj211w0hhq3h.jpg"/>
