### ISSUE TITLE
想知道北京的小伙伴是不是全都用不了了……

### ISSUE THREAD

**Issue by TangBean** [getlantern/forum#5858]
请在发帖前先按照蓝灯无法使用的解决办法 https://github.com/getlantern/forum/issues/1902 自行解决。自行解决问题通常只需要几十分钟。管理员调查解决问题需要几天至几周。请立即访问https://github.com/getlantern/forum/issues/1902 瞬间解决98%的问题

为了能在最快的时间内解决大家使用蓝灯遇到的问题，请各位用户严格按照发帖格式提交问题。

## 发帖格式
遇到的问题：请详细描述遇到的问题。如果描述不仔细，将无法调查

蓝灯专业版账号Email:  请提供登陆蓝灯专业版的email，免费版不提供技术支持。

应用内报告问题的时间:  请根据 https://github.com/getlantern/forum/issues/1840 在应用内上报问题，请填写专业版的email。请在帖子里注明报告的时间。

截图: 请提供有关问题的截图。 请把图片拖拽到这里。

----
请不要发只有邀请码没有其他内容的帖子,违反者将扣除所有赠送时间。具体见 https://github.com/getlantern/forum/issues/3773

想知道北京的小伙伴是不是全都用不了了……不能翻墙真的好不方便……

**Comment by Cold5721** [comment]
联通4g可以。

**Comment by beboyss** [comment]
无法用

**Comment by HelloXiaoxi** [comment]
嗯确实不，能用了。哈哈。
![2017-10-26 8 54 58](https://user-images.githubusercontent.com/25526254/32031044-7993fa96-ba31-11e7-9154-f226a69bf643.png)

**Comment by tunnelode** [comment]
根本不能用。

**Comment by xidianzhangjun** [comment]
安卓移动4G用不了。

**Comment by ddmu** [comment]
我反正这段时间都没法翻了，不知道啥时候能恢复，急盼。

**Comment by sunorign** [comment]
快半个月了都不能用

**Comment by fuqian95** [comment]
北京，用不了。

**Comment by Maomaoa1** [comment]
北京海淀联通100M光纤昨天下午就不能用了

**Comment by cat789** [comment]
BJ,Unicom, It can always be used and set up problems.
