### ISSUE TITLE
昨天买的专业版，买了就用不了。能退钱吗？

### ISSUE THREAD

**Issue by liangluping** [getlantern/forum#5918]
不管安装什么版本，改了什么配置。
都用不了。
使用天行VPN可以正常访问。
想问，我花的338块能退吗 ？
第一次觉得这钱花的真冤枉。

**Comment by beboyss** [comment]
勇士，一路走好

**Comment by levenwindy** [comment]
花这么多！不如你每月给我15，我担保你ss可以正常访问

**Comment by beboyss** [comment]
@levenwindy ss有流量限制吧

**Comment by CantoneseTeaAndMilk** [comment]
我也和你一样 钱交了 连个客服都没有 也没个说法

**Comment by Mephistogu** [comment]
也是昨天买的338，想退钱

**Comment by wsnjsa** [comment]
客服系统都没的，问题回复也没信，想退款都没法，论坛也不活跃，简直坑爹。什么情况都不知道，也没个管理的现身来个说法。

**Comment by levenwindy** [comment]
@beboyss  给你500g你用得完？300元都可以包一台cn2 最优秀的线路了

**Comment by levenwindy** [comment]
@Mephistogu  10块钱包你每个月晚上高峰期也可以1080p流畅 ，现在都用ss了
