### ISSUE TITLE
感谢蓝灯团队的同时，希望团队更Professional，至少版本号别出错啊！

### ISSUE THREAD

**Issue by Woodtrain** [getlantern/forum#5928]
论坛上明明写的最新版本是4.3.X，可是下载时都是4.2.X，无论是PC版或是安卓版。蓝灯陪伴我快两年了吧，心里由衷感谢团队的努力，说实在话，当初最开始只有免费版时我还给团队发信，问如何捐助，有了收费版之后我其实心里反而更安省了。问题层出不穷，希望团队不忘初心，你们做的是一件利国利人当然也利己的很有价值的事业！

**Comment by anticpc** [comment]
4.3.x是测试版

**Comment by gaojiahang** [comment]
@woodtrain      你能用？？

**Comment by Woodtrain** [comment]
4.2.2安卓版，江苏移动，不行啊

**Comment by Woodtrain** [comment]
4.3.2安卓版+江苏电信
4.2.5PC版+江苏电信
付费用户
亲测可用
时间：10月27号中午12点
