### ISSUE TITLE
电脑版退出Lantern后，任务管理器中仍有Lantern.exe的进程存在，然后IE无法打开任何网页

### ISSUE THREAD

**Issue by Portan** [getlantern/forum#594]
如题，我的电脑是64位win7. 
且不说打开lantern3.0.6上不了google，退出后，IE上不了网，任务管理器中仍有Lantern.exe的进程存在。
IE要reset一下后才可以上网，不知道什么原因？

**Comment by Portan** [comment]
另外，为什么打开Lantern后这个网站要走lantern流量，明明没有被GFW封。

**Comment by temnia** [comment]
internet选项>连接>局域网设置，把脚本关闭

**Comment by ssy341** [comment]
参考这个 [#4969](https://github.com/getlantern/lantern/issues/4969#issuecomment-231642916)楼上的图解版

**Comment by zsqp447** [comment]
没必要关lantern，直接在设置里把系统代理关闭，要用的时候再勾上，又快又方便

**Comment by ssy341** [comment]
@zsqp447 这个好粗暴直接
