### ISSUE TITLE
蓝灯挂了就骂，你们这么爱翻墙就滚走啊，让你们走还说我有什么权利？就凭你们也配翻墙？

### ISSUE THREAD

**Issue by tongxm** [getlantern/forum#6051]
我是中国人，我有天经地义的权利捍卫我的祖国。我认为你们这些说外国月亮圆，外国空气甜的人，严重危害了我国家安全，你们一群屌丝键盘侠没本事移民哈哈哈，就凭你们还搞技术，还科学家呢。技术单位都提供国际互联网直连通道，根本不需要来用蓝灯……一个蓝灯挂了你们就都翻不上去了还妄称自己是搞技术的，还查资料，好好考个清华计算机的本科，好好学学互联网协议是什么东西，再来逼逼……我不管什么五毛六毛的，我就看不惯你们自以为自己会上个github就是什么类人猿了，连一个简单到爆的绕开协议的代码都不会， 就靠着这些全是后门的VPN翻，翻不出去还要骂蓝灯，人家觉得你们二逼你们还要封号哈哈哈哈真是太可笑了，你们此生也就止步于此

**Comment by lastdemon** [comment]
共匪的粉蛆阉狗还祖国呢，共匪的党国吧？赵家的阉狗就别冒充人了，吃你主子的狗屎去

**Comment by brookier** [comment]
来，大家欣赏下楼主 ![](https://scontent-sea1-1.cdninstagram.com/t51.2885-15/s480x480/e15/10251365_264367973746094_1750018448_n.jpg?ig_cache_key=NzA5OTYzNjAyNTE5MzUxODkw.2)

**Comment by lwtbn1** [comment]
你个傻逼，高端人士都出国了，你还在中国写代码？你的八辈祖先脸都没了？你可知否啊！

**Comment by Ricky-Tsang** [comment]
@brookier 爆照爆得好阿 看樣子樓主頭那麼多 裡面的屎一定裝了很多

**Comment by Ricky-Tsang** [comment]
樓主剛註冊的號 看來就是搞事情的

**Comment by Ricky-Tsang** [comment]
大家一起來黑白打印樓主的照片 可用來擦屁股上廁所

**Comment by gddwl** [comment]
楼主傻逼，找骂

**Comment by fx0101** [comment]
楼主：众人皆醉我独醒

**Comment by logoooout** [comment]
楼主 自以为 和自己不相干 当你自己真正用到的时候 我不知道你自己是不是也是这幅嘴脸

**Comment by ningqivip** [comment]
小粉红，给你爷爷我跪下。
