### ISSUE TITLE
按今天的状况来看又全线阵亡了

### ISSUE THREAD

**Issue by Restlessness** [getlantern/forum#6079]
mac。安卓和windows10全挂了

**Comment by L807217649** [comment]
江西电信，我的pc和安卓都用不了，两天了，也没个说法

**Comment by harlemyin** [comment]
扬州电信，继续保持可用

**Comment by lemonskkyt** [comment]
哎，lantern的技术真是让人怀疑了，都这么久了，还是搞不定，服务器也已经换了吧，结果还是连个免费的赛风都比不了，3.2也不知道更新了什么，没连上也显示已经连接

**Comment by Restlessness** [comment]
![webwxgetmsgimg](https://user-images.githubusercontent.com/12756670/32141469-4b59e964-bcbc-11e7-9f75-5b39a68f56ff.jpg)
服务器根本没换，这是今天下午我测试的 依旧是阿里云服务

**Comment by lining1994** [comment]
两台电脑正常使用五六天的飘过～～～

**Comment by zhangguoxiao2017** [comment]
自从19大开完之后，
每天都能稳定使用。。

**Comment by mythlegend** [comment]
即使连上了也不代表能用，正常能用的时间只有不能用的十分之一，不断反复刷新页面，哎~~~
