### ISSUE TITLE
"人在做，天在看“？屁！如果不改变愚昧顽固的阿Q精神，我们的天会越来越黑

### ISSUE THREAD

**Issue by johnx7271** [getlantern/forum#6082]
罗伯特。肯尼迪的名句：Each time a man stands up for an ideal, or acts to improve the lot of others, or strikes out against injustice, he sends forth a tiny ripple of hope, and crossing each other from a million different centers of energy and daring, those ripples build a current that can sweep down the mightiest walls of oppression and resistance.

**Comment by gmvp3** [comment]
老郭都闭嘴了，你能比他牛？

**Comment by johnx7271** [comment]
@gmvp3 你的洗地的干活？或者实在太愚蠢，智商低于一百吧？
郭某本质是和共产党合谋的奸商，无知愚蠢自私，通过拍马行贿抬轿而发财。
我是个有头脑的小老百姓，虽然没他牛，但和他不一样。

**Comment by mamegu** [comment]
发这贴的也是个脑残，智商和小粉红一个级别的

**Comment by gmvp3** [comment]
你的确和老郭不同，只能在这发发牢骚

**Comment by lastdemon** [comment]
老郭没闭嘴，又开始直播了啊

**Comment by lacy25** [comment]
因为现在的国情如此，民智未开，人云亦云、跟风以反政府为荣，逢共必反的美分党太多，所以就该设置gfw，美分党总是说五毛是被土共洗脑，其实你们何尝不是被轮子、灯塔国洗脑？诚然，这个国家有太多的问题，但是土共在几十年里带领天朝取得这么大的成就，这是毋庸置疑的，发展中难免有这样那样的毛病和矛盾，但是我看到了进步，西方的月亮并不总是圆的，慕洋犬们醒醒吧

**Comment by gmvp3** [comment]
五毛来了，大家退散

**Comment by linli9500** [comment]
现在看到郭某就恶心
