### ISSUE TITLE
为什么还是用阿里云服务呢

### ISSUE THREAD

**Issue by Restlessness** [getlantern/forum#6083]
现在mac，win10，安卓wifi，lantern 4.2.5，4.3.2 都全部阵亡。 还剩安卓4g能用。用测IP的方式一测还是阿里云服务。 对蓝灯的未来bu不敢抱太大希望
![webwxgetmsgimg](https://user-images.githubusercontent.com/12756670/32141491-dbb5440e-bcbc-11e7-9197-ee3368b2e051.jpg)

**Comment by gmvp3** [comment]
不懂帮顶

**Comment by xiuluojia** [comment]
哎 搞不懂

**Comment by GD-HBX** [comment]
楼明聪明，把能用的IP和线路爆出来
