### ISSUE TITLE
我发现里面混进了不少轮子和独子，是非大家自己好好看清楚.................

### ISSUE THREAD

**Issue by gddwl** [getlantern/forum#6097]
请在发帖前先按照蓝灯无法使用的解决办法 https://github.com/getlantern/forum/issues/1902 自行解决。自行解决问题通常只需要几十分钟。管理员调查解决问题需要几天至几周。请立即访问https://github.com/getlantern/forum/issues/1902 瞬间解决98%的问题

为了能在最快的时间内解决大家使用蓝灯遇到的问题，请各位用户严格按照发帖格式提交问题。

## 发帖格式
遇到的问题：请详细描述遇到的问题。如果描述不仔细，将无法调查

蓝灯专业版账号Email:  请提供登陆蓝灯专业版的email，免费版不提供技术支持。

应用内报告问题的时间:  请根据 https://github.com/getlantern/forum/issues/1840 在应用内上报问题，请填写专业版的email。请在帖子里注明报告的时间。

截图: 请提供有关问题的截图。 请把图片拖拽到这里。

----
请不要发只有邀请码没有其他内容的帖子,违反者将扣除所有赠送时间。具体见 https://github.com/getlantern/forum/issues/3773

**Comment by pool360** [comment]
除了自家的VPN，发现一个VPN上报一个，发现两个上报一双，封完了，傻逼们自然会回到正常人的生活。省的被洗脑，开始上报所有已知的翻墙工具，喷子们服不服？服不服？劳资专治不服

**Comment by lastdemon** [comment]
@pool360 这不愧是杂种粉蛆啊，你国还真从来不缺你这种贱货阉狗，瞧瞧这阉狗太监多得意啊

**Comment by lastdemon** [comment]
@pool360 对了赶紧把自己用的也举报了啊，阉狗对共匪怎么能这么不忠诚呢，小杂种赶紧听你主子的话滚回墙里去啊

**Comment by pool360** [comment]
@myleshorton 自己用的举不举报关你卵事，你家老母死了还不去哭丧，剁了喂狗最好，呵呵
