### ISSUE TITLE
请问哪里能下到最新的4.3.X版本？

### ISSUE THREAD

**Issue by helloworldit** [getlantern/forum#6120]
看github论坛首页显示最新的是4.3.x版本，我从官网https://getlantern.org/zh_CN/下载是4.2. 5
请问哪里能下到最新版？谢谢

**Comment by Guoyuh78** [comment]
点这里https://github.com/getlantern/forum/issues/5964

**Comment by lancefee** [comment]
https://raw.githubusercontent.com/getlantern/lantern-binaries/master/lantern-installer.exe
