### ISSUE TITLE
蓝灯不能用和运营商没关系，和蓝灯的账号体系有关

### ISSUE THREAD

**Issue by dick318** [getlantern/forum#6146]
我用自己的账号 不能连接，但是同事的一直能访问，让同事给我授权了之后，我就能用了，说明和网络封锁半毛钱关系没有，就是蓝灯自己的问题

**Comment by Guoyuh78** [comment]
妈的

**Comment by Ieyasu1543** [comment]
那涉及人数也太多了，我的账号时好时坏的

**Comment by tunnelode** [comment]
居然有这种事。他妈的蓝灯的人不露面啊。这帮死猪。太气人了。

**Comment by gddwl** [comment]
艹他妈的

**Comment by HelloXiaoxi** [comment]
你把你的号发上来啊，授权给别人一下看看能不能用。

**Comment by MartinCrewes** [comment]
那蓝灯为啥要这样做

**Comment by yjfzz** [comment]
付了钱，一直没正常用过！

**Comment by Restlessness** [comment]
是的我同事用的跟我一样的网络。 我的不能用。 我同事一直好好的。真的是分账号

**Comment by JiejunHu** [comment]
到底是什么情况，大家都怎么解决呢？我的mac点击应用都打不开

**Comment by jamicc** [comment]
确实有这种情况，我们公司就是这样，有人能用，有人不能用。而且这种情况也在其他好几个同类型软件上发生过。

**Comment by QIcareful** [comment]
对的,现在就是这样的情况.

**Comment by lzhlewis2015** [comment]
我 用自己的电信4g 不能用， 用单位的网线上网然后挂蓝灯就可以用。

**Comment by pool360** [comment]
蓝灯代理服务器是随机选择的，并非在同一网络下别人能你就能用，电脑不同代理服务器也不同，有的能连接，有的不能

**Comment by effygwave** [comment]
不同账号对应的是专属的服务器，有可能恰好你的服务器被墙了。。发日志／账号让管理员改服务器 @dick318

**Comment by xjwang1126** [comment]
跟楼主发现同样的问题 不知道要不要再买个账号

**Comment by effygwave** [comment]
你对lantern也是真爱，好待等他稳定些来，况且他们应该让每个pro都好用啊，凭什么要再买 @xjwang1126

**Comment by sdra1984** [comment]
你们仔细看现在论坛里的内容，凡是标题吐槽的，基本没有回复，凡是说能用的，下面一堆人跟着回复也能用了，呵呵~好可怕！蓝灯的水军真多！Twitter跟G+上都骂疯了，这里倒是很和谐！

**Comment by ethanjia** [comment]
蓝灯用不了上不了推特和g+啊。买了一年买了蓝灯，还有20天到期，平时刷刷youtube和por*hub。难道蓝灯也有道德体系吗，哈哈

**Comment by cat789** [comment]
YES，That's the problem。I found it long ago、、、

**Comment by xjwang1126** [comment]
@effygwave 以前蓝灯还是做的很好的 只可惜这次没有逃掉灾难 还想等等蓝灯官方的回复 如果没有 只能换其他家 比较工作需要 不能这样干等

**Comment by TizenWong** [comment]
我靠？我是专业版啊，现在更新完软件，自己的账户等不进去啊，gmail的邮箱账户

**Comment by Ricky-Tsang** [comment]
真是這樣的話 就操蛋了...
