### ISSUE TITLE
该邮件地址已被另一用户使用

### ISSUE THREAD

**Issue by zsqp447** [getlantern/forum#615]
3.07，之前从未购买成功过，这次出现了这个提示
[lantern - 副本.txt](https://github.com/getlantern/forum/files/365069/lantern.-.txt)

**Comment by zsqp447** [comment]
难道是我已经购买成功了，怎么没收到扣款消息

**Comment by p3rcya** [comment]
那你登陆试试看

**Comment by zsqp447** [comment]
确实成功了，速度有所提升
