### ISSUE TITLE
GM在吗，我用的是老版本2.2.4，翻不了墙，可以帮忙下吗~

### ISSUE THREAD

**Issue by 772077730** [getlantern/forum#619]
为什么文档也上传不上去，心好累

**Comment by yzs0324** [comment]
升级啊

**Comment by p3rcya** [comment]
升级到最新的3.0.7 啊 下载地址 https://github.com/getlantern/forum/issues/611

**Comment by 772077730** [comment]
升级了，但是不能上谷歌，脸书，推特……只能够上Chrome的网上商店
[lantern.txt](https://github.com/getlantern/forum/files/365335/lantern.txt)

**Comment by 772077730** [comment]
升级成了3.0.7
