### ISSUE TITLE
我这个好像可以用了.不知道能稳定多久

### ISSUE THREAD

**Issue by Cold5721** [getlantern/forum#6212]
截图记录一下网速
![_20171031160738](https://user-images.githubusercontent.com/30823032/32213303-a2e5a552-be55-11e7-91d2-60c979562133.jpg)

**Comment by EricRae** [comment]
不要嘚瑟，我上午刚说可以用，现在已经死的不能再死了

**Comment by KhanAa** [comment]
我的昨天下午能用，晚上就歇菜了

**Comment by Cold5721** [comment]
@EricRae 吓得我赶紧把帖子删了
