### ISSUE TITLE
遇到问题的能抓个包么？

### ISSUE THREAD

**Issue by wangchunming** [getlantern/forum#6220]
打开wireshark，开启抓包，重复一遍你连接时候的动作，完成后保存，利用任何可以放在这里的方式把抓到的包放在这里。
这更有利于解决问题。

**Comment by offfar** [comment]
最好留个邮箱给你发附件.pcapng

**Comment by ROGSICA** [comment]
大家不要轻信，楼主多半网警，抓包分析彻底搞垮蓝灯

**Comment by offfar** [comment]
谢谢提醒。
