### ISSUE TITLE
蓝灯免费版能用，收费版不能用的原因找到了。

### ISSUE THREAD

**Issue by wangchunming** [getlantern/forum#6271]
【之前我发了个贴说能不能把有问题的抓个包放上来，有人说我是网警，好吧】

蓝灯免费版能用，收费版不能用的的原因是因为免费版用的是digitalocean的服务器，收费版用的是东京和新加坡阿里云的服务器。
其次，蓝灯极容易被封杀的原因是因为蓝灯工作的原理和赛风不一致，蓝灯是透明代理，会在数据包里面发送用户的ip地址到服务器然后中转出去，中转出去的时候蓝灯也会把用户ip带出去，赛风和其他VPN都不会。
而各类国产软件是很容易就可以获得到蓝灯服务器的ip的，并且因为数据包里面包含了用户的源ip地址，配合国产软件封杀起来极其容易，总之，想安全那是绝对不要用蓝灯的。
蓝灯的证书似乎是自签名，因为我没有其证书所以更多情况不得而知。（例如传输的到底是什么）
各位也都看到了有些人卸载了国产软件就可以用蓝灯的事情了吧，出现这种情况的原因是这样的，蓝灯不仅仅是靠TCP通信，也会有UDP数据包传出去，而UDP数据是最容易拦截的，有些软件就干这事。

使用工具：windows+wireshark+火绒剑+黑客圈经常用的一款进程信息动作捕捉工具

因此各位现在千万不要急着买专业版！！！！

**Comment by XiuJingmin** [comment]
刚买了两年的……能不能退款啊摔！

**Comment by levenwindy** [comment]
不能用的时候
+群120926093
ss，我10元每个月包你看youtube 1080p流畅，15元电信最优质的cn2(gia线路)
抢生意，，笑～
