### ISSUE TITLE
免费版不给用了，为什么我一直没有流量啊？？？？

### ISSUE THREAD

**Issue by Varorbc** [getlantern/forum#6276]
免费版不给用了，为什么我一直没有流量啊？？？？

**Comment by HelloXiaoxi** [comment]
别人收费版都不能用，都嚷嚷退钱呢，你个免费版瞎嚷嚷什么?就跟你能用似的？

**Comment by FSD001** [comment]
# **楼主，请看我的专业版**
![image](https://raw.githubusercontent.com/FSD001/damon.github.io/master/2017-11-01_023710.jpg)
![image](https://raw.githubusercontent.com/FSD001/damon.github.io/master/2017-11-01_023727.jpg)

**Comment by EricRae** [comment]
你没发现帖子都是付费的。。。。我们免费的能上就行了，速度慢点也OK。   -------来自免费党的觉悟

**Comment by levenwindy** [comment]
不能用的时候
+群120926093
ss，我10元每个月包你看youtube 1080p流畅，15元电信最优质的cn2(gia线路)
抢生意，，笑～
