### ISSUE TITLE
需要蓝灯专业版的联系我,低价出

### ISSUE THREAD

**Issue by cweijan** [getlantern/forum#6281]
我的专业版买了两年,到2019-07-09过期,不想用蓝灯了,转让,邮箱cweijan@163.com

**Comment by VincyChan** [comment]
哥们你还蛮搞笑的，哈哈

**Comment by levenwindy** [comment]
不能用的时候
+群120926093
ss，我10元每个月包你看youtube 1080p流畅，15元电信最优质的cn2(gia线路)
抢生意，，笑～

**Comment by offfar** [comment]
你不能用给别人挖坑
