### ISSUE TITLE
刚买了2年就不能用了？我以为19过去就好了，耐心在等结果呢？要求退款！

### ISSUE THREAD

**Issue by w651775549** [getlantern/forum#6284]

**Comment by rizi800** [comment]
已经好用了吧，android

**Comment by FSD001** [comment]
兄弟 发帖能把官方自带的内容删了不？

**Comment by w651775549** [comment]
我PC加ios

**Comment by FSD001** [comment]
![image](https://raw.githubusercontent.com/FSD001/damon.github.io/master/2017-11-01_023710.jpg)
![image](https://raw.githubusercontent.com/FSD001/damon.github.io/master/2017-11-01_023727.jpg)

**Comment by FSD001** [comment]
我专业版都没流量了 你们还能用？

**Comment by MosesXY** [comment]
＠FSD001 楼上的兄弟，全屏截图，好增加可信度。先登录上专业版，然后全屏截取，把专业版登录信息和提示流量用完的那则通知包含在同一张图里上传，你这样分开用两张图上传看不出问题
