### ISSUE TITLE
4.4.0Mac安卓不能用。 家里的win10装的4.3.2一直不能用竟然复活能用了

### ISSUE THREAD

**Issue by Restlessness** [getlantern/forum#6322]
好神奇。看来是有关部门封的快啊。 我同事用的4.2.5一直可以而且速度贼快。早知道不手贱升级了

**Comment by Restlessness** [comment]
安卓4.4.0也恢复使用了

**Comment by Restlessness** [comment]
Mac有待明天检查。安卓稳定性待时间检验

**Comment by levenwindy** [comment]
+群120926093 
ss，我10元每个月包你看youtube 1080p流畅，15元电信最优质的cn2(gia线路)

**Comment by GMCLucas** [comment]
刚才发现，之前的蓝灯插件版谷歌浏览器，居然也能上Google了，速度还不慢。这真尴尬了。团队做了那么多次升级其实是无效的，GFW想放就放，想紧，你插翅难逃

**Comment by Restlessness** [comment]
今早上一看又死了。 再分享个我已经用了三年的ss提供商。一年100块。每月50G流量，同时最多三台设备可以用。虽然十九大也挂了，不过他们在挂之前就给了告示。大家想用的用连接，我多赚30天：)
https://portal.shadowsocks.la/aff.php?aff=12008
