### ISSUE TITLE
刚付费就用了三天，谁赔我一个月的亏损

### ISSUE THREAD

**Issue by Clowlar** [getlantern/forum#6344]
请在发帖前先按照蓝灯无法使用的解决办法 https://github.com/getlantern/forum/issues/1902 自行解决。自行解决问题通常只需要几十分钟。管理员调查解决问题需要几天至几周。请立即访问https://github.com/getlantern/forum/issues/1902 瞬间解决98%的问题

为了能在最快的时间内解决大家使用蓝灯遇到的问题，请各位用户严格按照发帖格式提交问题。

## 发帖格式
遇到的问题：请详细描述遇到的问题。如果描述不仔细，将无法调查

蓝灯专业版账号Email:  请提供登陆蓝灯专业版的email，免费版不提供技术支持。

应用内报告问题的时间:  请根据 https://github.com/getlantern/forum/issues/1840 在应用内上报问题，请填写专业版的email。请在帖子里注明报告的时间。

截图: 请提供有关问题的截图。 请把图片拖拽到这里。

----
请不要发只有邀请码没有其他内容的帖子,违反者将扣除所有赠送时间。具体见 https://github.com/getlantern/forum/issues/3773

**Comment by winyiday** [comment]
群120926093 可月租可测试 ss YouTube可流畅

**Comment by molur1234** [comment]
还能有一个月的套餐？你那个不是蓝灯吧

**Comment by mxujm1** [comment]
@molur1234 他是说刚买3天就一个月无法使用了把，我是去年蓝灯刚开专业版时买的，记得去年也是付款后无法使用，时间差不多一个多月把，修复后是补了时间的，这个不用担心

**Comment by offfar** [comment]
30号买的，我一天都享受过真正的专业版，除了当天经过n分钟才打开过google外。

**Comment by jay173361646** [comment]
给延长一个月吧
