### ISSUE TITLE
lantern不能用-专业版 Mac OS

### ISSUE THREAD

**Issue by PangTF** [getlantern/forum#6351]
刚购买的1年服务不到一个星期，按照#1902尝试了。
尝试了4个浏览器(firefox, chrome, Safari， qq)，都不行。
重新安装了lantern，查看了高级代理。

要求退款。
账号qdpangtf@gmail.com

**Comment by PangTF** [comment]
ps：我是按照上个问题的格式写的

**Comment by Halezhang** [comment]
SS依然坚挺的， 我的邮箱 353739894@qq.com

**Comment by frankyanghao** [comment]
刚刚恢复

**Comment by PangTF** [comment]
求退款

**Comment by Ghostwithout** [comment]
你好，麻烦到lantern界面反馈问题，上传日志以便后台调查，谢谢！
