### ISSUE TITLE
蓝灯我走了！不用送了~

### ISSUE THREAD

**Issue by godliness** [getlantern/forum#6352]
再见了蓝灯，某某会议已经结束了，还是不能使用，我灰心了，我还有23个月的会员，我不要了，钱估计你肯定是不给退了，因为对于这么多的付费用户的抱怨你们都没有个说法，这种300块钱的小事估计找谁谁都不会搭理我，我已卸载。

**Comment by tssn-sh** [comment]
别灰心！刚下了个hosts文件，居然能用了，也许和这个文件有关，就是不知道稳定不？你可以试试替换这个文件。

**Comment by godliness** [comment]
@tssn-sh 刚买了自己的海外服务器，再也不用担心了。。。

**Comment by BigBlackHardThick** [comment]
可以一起用吗。。。。我不是经常用，偶尔下点youtube，，，
