### ISSUE TITLE
这么久了，蓝灯要说点什么吧！

### ISSUE THREAD

**Issue by april909** [getlantern/forum#6374]
好久夸，不好就提意见，这叫粉丝。
好不好都要说难听的，这叫黑子。
好不好都要夸，这叫信徒。

这么多人付了费，也确实很久不能用。该不该有点歉意说句话呢?
green关停的时候，刚续了两年，本来没报啥希望的，他们确最后感动我了一把。

如果一直这样 蓝灯我只上当一回
green团队如果回来 我一定支持

人呢都是将心比心

**Comment by molur1234** [comment]
也许两年后，不用爬梯子翻墙了。

**Comment by winyiday** [comment]
实在不能用的话，群120926093 可测试 可月租ss YouTube流畅

**Comment by vialluck** [comment]
看看他们对付款用户得态度，免费速度飞快，付款用户反而打不开网页，连个说法也没有。
看样子还是想继续骗钱，退款真没什么希望，跟green有法比？
蓝灯团队，我日你们妈批

**Comment by yjfzz** [comment]
蓝灯团队，我日你们妈批

**Comment by bluewrap** [comment]
今天想看看有没有更新，跑来一看都晕了，什么情况？北京联通，除了开始的几天，一直都可以用啊

**Comment by mxujm1** [comment]
green新版改名叫seed，虽然只恢复了几个节点，不过良心啊

**Comment by april909** [comment]
@molur1234 理想很丰满

**Comment by april909** [comment]
@winyiday 被逼的 已准备了n多备用梯子

**Comment by april909** [comment]
@bluewrap 好运气的人啊

**Comment by april909** [comment]
@mxujm1 真的吗 那里可以下载 googleplay可以下载吗

**Comment by april909** [comment]
@
