### ISSUE TITLE
牛逼 4.2.5 win7 可以用了我的邀请码  ：YGV83WK

### ISSUE THREAD

**Issue by userfirstone** [getlantern/forum#6383]
![fseq0tu ntj v8 i rucl2](https://user-images.githubusercontent.com/32631032/32314407-bb6f5896-bfe2-11e7-802d-c19dd3ecfa48.png)
![1](https://user-images.githubusercontent.com/32631032/32314419-c8235a60-bfe2-11e7-9c9a-61dae89ef920.png)
输入我的邀请码 YGV83WK 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by userfirstone** [comment]
安卓版也恢复了，666

**Comment by andileexxx** [comment]
能用了 就是没以前速度快

**Comment by hhzhaoheng** [comment]
我的还不能用，好烦

**Comment by fly111222** [comment]
哪里有4.2.5版本的
