### ISSUE TITLE
没记住授权码就找不到了？

### ISSUE THREAD

**Issue by Akatsukir** [getlantern/forum#6389]
遇到的问题：第一次授权设备的时候显示了授权码，当时没记下来。想再授权一台设备的时候就只有填授权码的页面了。。。那我当时没记下来就没办法再授权了吗？在哪里能看到授权码？
 

蓝灯专业版账号Email:  382608905@qq.com

**Comment by Ghostwithout** [comment]
你好，请在需要授权的设备上选“授权设备使用专业版”，该界面会收到验证码，然后请到专业版设备输入验证码，即可完成手机授权。谢谢！
