### ISSUE TITLE
4.3.2慢的要死，准备升级4.4完事微软直接拦截。不能用请给解决办法，别让我们升级了

### ISSUE THREAD

**Issue by caelum1989** [getlantern/forum#6396]
RT：4.3.2慢的要死 准备升级4.4完事微软直接拦截！~

_

**Comment by caelum1989** [comment]
![qq 20171102191034](https://user-images.githubusercontent.com/33317695/32324287-ddff2f80-c005-11e7-97a9-46bfb5e4d3e2.png)

**Comment by caelum1989** [comment]
![qq 20171102191730](https://user-images.githubusercontent.com/33317695/32324298-e621e1e4-c005-11e7-9287-4c1662af2e1c.png)

**Comment by Ghostwithout** [comment]
windows防火墙会拦截lantern，关闭后即可使用。谢谢！
