### ISSUE TITLE
你好授权码可以给我吗

### ISSUE THREAD

**Issue by ugamoda** [getlantern/forum#6423]
我没有授权码

**Comment by ugamoda** [comment]
![6cd26a233addb2689cdade13478458f](https://user-images.githubusercontent.com/33328478/32343636-27813af2-c03f-11e7-932d-4804437ca43b.png)
![72576487328873009](https://user-images.githubusercontent.com/33328478/32343638-27dc06bc-c03f-11e7-879b-732a3572417f.png)
![253000474482005910](https://user-images.githubusercontent.com/33328478/32343639-280e5c16-c03f-11e7-9f5e-709716bfa411.png)

**Comment by Guoyuh78** [comment]
授权码在你的注册邮箱查看

**Comment by Restlessness** [comment]
我就收到过一次lantern的邮件还在垃圾邮件里。 其他的邮件是被邮箱直接弄没了吗。邮箱是微软的

**Comment by Ghostwithout** [comment]
你好，如果是新购买lantern专业版没更新，请退出lantern再登录即可；如果是授权新设备，请获得动态码之后输入到已经是专业版到设备上，即可完成授权。谢谢！
