### ISSUE TITLE
要退款的看这里

### ISSUE THREAD

**Issue by q474818917** [getlantern/forum#6457]
大家都留下退款方式吧，我先来，支付宝：474818917@qq.com

**Comment by shanxueyi** [comment]
你个智障，故意暴露联系方式，来引诱别人上当

**Comment by desususu** [comment]
这段时间太多zz了…
索要发票的，微信投诉的，用QQ群卖ss服务的，现在还来个主动暴露支付宝账号的，真的一个个都闲过得太平静想来点风生水起的滋味么？

**Comment by Chinaguigui** [comment]
怕不是骗子吧

**Comment by lewis615** [comment]
果然是对自己个人信息不保护的典型。。随便一搜社工库你的密码就出来了
