### ISSUE TITLE
蓝灯永远可以免费使用

### ISSUE THREAD

**Issue by ghost** [getlantern/forum#648]
蓝灯永远可以免费使用。免费版每个月有800MB流量限制，但免费版流量用完之后还是可以继续使用，只是会限速而已，但浏览网页没有问题。

这个问题我们已经说了很多遍，但是还有用户询问，特此说明。

如果有其他问题，请阅读
[蓝灯和VPN的区别](https://github.com/getlantern/forum/issues/361)

[蓝灯专业版和免费版的区别](https://github.com/getlantern/forum/issues/378)

**Comment by givendeng** [comment]
(⊙o⊙)哦 因为前段时间蓝灯旧版本不能用 今天更新了才知道有这么大变化

**Comment by bigbook777** [comment]
怎么取消蓝灯邀请码发到邮箱。每天都很多邀请码邮件发过来。影像其他邮件接收。

**Comment by p3rcya** [comment]
邮件内有退订选项

**Comment by LastingLove1127** [comment]
Good Nice

**Comment by EganLi** [comment]
换了手机后用不了

**Comment by gitgdeng** [comment]
good to know that!

**Comment by justincoolgang** [comment]
that is good

**Comment by justincoolgang** [comment]
会影响浏览facebook吗 里面有大量的照片？

**Comment by 706763801** [comment]
怎么没有中文版
