### ISSUE TITLE
看来还是自己搭vpn比较靠谱点

### ISSUE THREAD

**Issue by deepred5** [getlantern/forum#6487]
蓝灯挂了以后，最终还是选择自己搭vpn，其实私人SS实现起来还是比较简单的。我这里写了下教程，有兴趣可以看下
[教程地址](http://anata.me/2017/10/22/%E5%88%A9%E7%94%A8vps%E6%90%AD%E5%BB%BA%E8%87%AA%E5%B7%B1%E7%9A%84ss%E6%A2%AF%E5%AD%90/)

**Comment by kanganxi** [comment]
自己搭建的速度咋样？

**Comment by deepred5** [comment]
@kanganxi  反正基本满足我平时上网需求，看youtube也还是蛮流畅的

**Comment by kanganxi** [comment]
很担心万一IP被墙了，怎么办？还有你搭建买服务器的成本是多少，还有需要买什么配置的，满足看视频需求

**Comment by yzou** [comment]
推荐一个我用的，邀请码：4UT35F

https://www.plexvpn.pro/register?invite_code=4UT35F

**Comment by gonggy** [comment]
@deepred5 我刚刚装了一下，香港的阿里云ECS，用的你的教程，centos7.2，部署成功了，但是貌似不好使啊，ios可以连上，但是外网打不开的，Windows的PAC文件也无法更新。大概啥原因呢？

**Comment by zxfxpower** [comment]
还不错，用的阿里云美国硅谷的最低配服务器(CentOS)

**Comment by gonggy** [comment]
额，可以了，安全组忽略了，忘记要配置云服务器的安全组。thx。
