### ISSUE TITLE
被革命前，法国贵族说，那些贫民没有饭吃，为什么不吃面包？类似的，对习共当局来说，gfw是不是根本不算什么？

### ISSUE THREAD

**Issue by johnx7271** [getlantern/forum#6515]
如果把工人的机床给封了，把农民的拖拉机给封了，工人和农民会干什么？？？？？
习共当局把gfw弄得越来越高，越来越厚，这对科研人员来讲，就跟上述行为是类似的性质，习共当局大概是不能理解到这点的。就像那些法国贵族那样，“那些贫民没有饭吃，为什么不吃面包？”

很多中国人，面对恶行时会说："人在做，天在看“，或者：“天塌下来，有高个子顶着”。

屁，宇宙中不存在一个能够干预人世的天。当初希特勒虐杀了6百万犹太人，如果不是数千万的俄国小百姓，拼上性命，殊死反抗，当今世界，恐怕留不下几个民族。这些反抗的小百姓，就是天！我们大家一起，构成了天。

”天塌下来，有高个子顶着“，谁是高个子？薄熙来算高个子，他有意愿帮你顶吗？就算他有，他有能力吗？天太沉重，一万个高个子也顶不住，只有每个人都挺直了腰板和脊柱，才能把天的重量分担下来，才不会大家一起被压死。

指靠高个子的想法，会象传染病一样，流行起来，最后没有几个人敢站起来。高个子会指望更高的高个子，最后，只能指望那个并不存在的“会干预人世的天”。而敢站起来的人也会被压垮，天就会越来越低，越来越暗。不仅如此，那些有靠天想法的人，本身也会增加那黑暗天空的重量，让抵抗的人，变得更加渺小和无力。

大家知道怎么对付传染病吧? 每个人都要积极的行动，不感染，才能让传染止步。当你有"人在做，天在看“，或者：“天塌下来，有高个子顶着”的想法时，你就成了一个感染源。为了让我们有一个明亮的可以舒展筋骨的天空，停止这么想吧！

罗伯特。肯尼迪的名句：Each time a man stands up for an ideal, or acts to improve the lot of others, or strikes out against injustice, he sends forth a tiny ripple of hope, and crossing each other from a million different centers of energy and daring, those ripples build a current that can sweep down the mightiest walls of oppression and resistance.

从今天开始，丢掉对天的幻想，为了我们共同的天，做一点力所能及的行动，分担一点点你无法逃避的责任。

**Comment by Lather0519** [comment]
说得好，现在什么时代？冷兵器时代么？还是大街上随便就可以捡枪？

**Comment by kimomoki** [comment]
买通各种杀毒软件乱删翻墙软件也是可以…连小A都堕落了…其实大家只要做到不冷漠说真话就行，不需要做什么，

**Comment by liuluck7** [comment]
煞笔理论。智障！

**Comment by 6726** [comment]
转载一段被人遗忘的历史


严刑拷打 强逼农民上缴粮食


太安是宗艾公社的重点村，在王维的直接插手下，杀气腾腾，乌烟瘴气。全村952人中，有121人被斗，致死者达36人。该村当年实产粮食66。7万斤，征购任务竟达74。9万斤，王维还要再加40万斤。为了完成任务，王维等人以“抵抗统购统销”，“对党欺骗隐瞒”为借口，对农民严刑拷打，逼要粮食。原任支书被打伤撤职后，指定了打人凶手梁某为新的支部书记，和学校教师苏景云等人狼狈为奸，操纵全村运动，同时还组织起40多人的打人队。社员赵义元夫妇，被他们捆起来摔打，打坏胳膊，打掉牙齿，口鼻流血，最后被逼上吊自杀。在摔打副队长张信时，将张几次高高抬起，摔在地上，用拳头猛击胸部，抓住头发在地上猛磕脑袋。张已奄奄一息，还大骂他“打死你，哪里还在乎一个人半个人”，接着又是一阵脚踢，直至气绝身亡。苏景云将一个生完孩子刚满月的妇女脱掉衣服，拉到院里挨冻。一个干部乞求，他竟惨无人道地吼叫：“不怕，冻死我负责。”仅他就亲自打过86人，推打后死亡6人，畏斗投井服毒死亡8人，新任支书梁某打过82人。
这年，宗艾公社在凹儿修建一座小型水库，800多民工都是离家在外，没有什么粮食可挖，但揪斗打人之风还是十分猖獗。被斗者达121人，致死10人。这个工地上有一个专设的执法队。一次，一个叫张四姐的妇女被摔打后，子宫出血不止。她央求说：“我还有一个吃奶的孩子”。但人称“母老虎”的执法队长任某某却大喊大叫：“死一个算什么，死十个也没关系。”还有一位五十多岁的劳动标兵王狗小，因劳累过度，休息时被“母老虎”发现后，活活摔死。二十多岁的民工任文厚被摔死后，水库派人直接将尸体拉到该家坟地埋葬，父母想看一眼都不允许。
在“挖粮集资”运动中，死人事件接连不断，县委书记王之一却说：“不要大惊小怪”，“死人不可避免”，模仿毛泽东的话说什么这是“九个指头与一个指头的问题”，声称“不能给群众运动泼冷水”。他们经常在电话中三令五申：必须限期完成任务。因此，下边蛮干的人气焰更加嚣张，叫嚷什么：“死人算什么，死是他不愿意过社会主义的关，把资产阶级思想带到棺材里去啦”！
寿阳县的“挖粮集资”运动，从1959年10月底发动，到1960年1月结束，经历三个月。全县有11159户被抄家搜查，24063户被掠夺财产，3116人遭到残酷斗争，打死、逼死、吓死、饿死349人，人民生活极度困难，民不聊生，疫病蔓延，牲畜死亡，人口外流，人心惶惶，全县城乡笼罩在一片红色恐怖气氛中。
中国大陆在1959－1962年间饿死4000多万人。河南省信阳地区就达20万人。寿阳事件中的死亡人数，虽赶不上这些“死亡大县”多，却活生生地反映出当时的中国老百姓是生活在怎样的黑暗社会中。在中国五千年历史上，这段历史的残酷程度是前所未有的。

**Comment by wangchunming** [comment]
薄熙来当初和李彦宏有交易。

**Comment by johnx7271** [comment]
@Lather0519 ：
“说得好，但是现在什么时代？冷兵器时代么？还是大街上随便就可以捡枪？”
我其实已经回答了："从今天开始，丢掉对天的幻想，为了我们共同的天，做一点力所能及的行动，分担一点点你无法逃避的责任。"
天下事，非别人家门前的雪，是每个人的事，只用心思考，见缝插针，就能一点点积累，水滴石穿。
暗黑势力，之所以强大，也是一点点积累起来的，打败暗黑势力，怎么可能一蹴而就？

**Comment by a29120834** [comment]
那你说，怎么分担，你说这一大通有屁用？有什么计划？什么时间什么地点，怎么解决，你说我跟咋样

**Comment by johnx7271** [comment]
@a29120834 , 你那么听话，好啊，如果你不是故意来搅混水的，先向liuluck7  吐口说，骂它是五毛猪，鉴于你的能力， 这就就够了。

**Comment by lastdemon** [comment]
不去解决问题，解决提出问题的人，这是共匪一切行为的指导思想，共匪真正的意识形态不是什么共产主义，而是闭嘴主义。
另外对习而言，你可以想想赵王回车，他显然是个对现代信息技术压根一窍不通的人，估计说不定连啥叫gfw都不知道，九成九是从来不上网的，这种朽木的想法会是如何可想而知

**Comment by Ricky-Tsang** [comment]
那你說做啥了... 屌~
