### ISSUE TITLE
蓝灯用不了，换另外一种

### ISSUE THREAD

**Issue by bjsy2003** [getlantern/forum#6543]
能用的话，我是非常支持lantern的
但是不能用又急着用的，可以尝试下ss ，支持手机电脑
YouTube可1080p ，流畅
群120926093 可测试 不用包年，可月租15
电信 联通 直连
管理每天都会在线回答各种问题，进群看公告，谢谢

![2](https://user-images.githubusercontent.com/33351692/32414144-85d579ba-c25b-11e7-9b60-967bb3021e78.jpg)

我面对的是一个活生生的人，搭建服务器，测试都需要时间。但是我敢保证：回复客户的每一条信息24小时内

**Comment by gmvp3** [comment]
坐等楼主被抓

**Comment by adencp** [comment]
早晚不等 QQ
