### ISSUE TITLE
出了问题，除了上传log还有别的方法吗？

### ISSUE THREAD

**Issue by physfrank** [getlantern/forum#655]
废了九牛二虎之力买了专业版，登录不上。我看了一下，都是让上传log。我不知道什么是log，是不是就不能解决问题了。

**Comment by p3rcya** [comment]
这帖中相信说明了上传过程 https://github.com/getlantern/forum/issues/358 不上传我们很难调查具体原因

**Comment by physfrank** [comment]
[lantern.txt](https://github.com/getlantern/forum/files/367167/lantern.txt)

**Comment by physfrank** [comment]
我们上传了log，谁都可以下载，这样安全吗？！

**Comment by zsqp447** [comment]
又不会暴露你个人真实ip信息，瞎担心什么
