### ISSUE TITLE
#1902 解决不了,  深圳电信 专业版本 MAC 不能用好多天了.

### ISSUE THREAD

**Issue by icyrus** [getlantern/forum#6550]
#1902 解决不了, 
 深圳电信 专业版  MAC系统 好多天不能用了.

**Comment by cool-firer** [comment]
同深圳，mac windows都用不了啊

**Comment by anticpc** [comment]
@icyrus @cool-firer 先用ss/ssr顶几天吧

**Comment by Ghostwithout** [comment]
你好，lantern从10月下旬已经陆续开始恢复，但不同的宽带服务商访问Lantern服务器的质量不一，也是不能连接或者连接缓慢到原因之一。可以尝试换个网络环境以及不同时段访问。如有问题，请到lantern界面反馈问题并上传日志供后台调查。谢谢！
