### ISSUE TITLE
代理?我才是巨头

### ISSUE THREAD

**Issue by littleniao** [getlantern/forum#6551]
刚才看见有人说要合伙买代理价，我都代理这么久了居然没人来找我，代理我才是巨头好吗？
刚开始做代理的时候我还战战兢兢，怕黄了，没想到最快的时候两个星期多就可以搞定，好友同学照样宰，甚至还加那么一点点价。
若有需要的蓝友可以联系我邮箱`1848976085@qq.com`,你们都清楚行当了我也不好再加价，以代理价出。
我感觉代理太多了，是不是要被请去喝茶啊~哈哈哈
![20171105210014](https://user-images.githubusercontent.com/33394667/32415293-8dd30e0e-c272-11e7-9f97-1591f106acc1.png)
![20171105210035](https://user-images.githubusercontent.com/33394667/32415297-9c9eb334-c272-11e7-9a8c-486f3d3aa326.png)
![20171105211551](https://user-images.githubusercontent.com/33394667/32415301-a2f19364-c272-11e7-8a4c-b503953692a1.png)

===================================================================
好吧，更新补充一下
我才发一下就有人来说是骗子@Ricky-Tsang，我不求你来要我的代理价，但请不要诽谤好吗！
下面两图或许就是你要的灯！

![20171105221715](https://user-images.githubusercontent.com/33394667/32415724-e3b0cf9a-c278-11e7-8aee-2d6ee0e69edd.png)

![20171105221701](https://user-images.githubusercontent.com/33394667/32415721-dec9dc88-c278-11e7-8e8c-37c5bc6cfe2e.png)

**Comment by Ricky-Tsang** [comment]
代雞巴 熄燈了 還騙錢

**Comment by gmvp3** [comment]
砸手里了吧，可怜的楼主

**Comment by Ricky-Tsang** [comment]
連日期都沒有騙誰呢？ 你能用不代表個個都能用 怎麼啦？ 繼續騙錢？ 自己死也要拉人墊背？ 爛手里吧等著~

**Comment by littleniao** [comment]
@Ricky-Tsang  5个买代理单都有日期时间摆在那儿，看来你看不大懂阿拉伯数字。要是烂手里我还代理这么多次？哎~跟你这种人解释真心累！

**Comment by littleniao** [comment]
@gmvp3 不会黄的，已经第五次代理了。

**Comment by Lather0519** [comment]
算了吧，为了那几十块钱跑到这里来装逼

**Comment by liumao** [comment]
代理啥，唉，先用用看吧！
