### ISSUE TITLE
付费了没有收到激活代码

### ISSUE THREAD

**Issue by kaicaysmic** [getlantern/forum#6556]
由于系统重装，蓝灯在电脑的授权清空了，在kaicaysmic@gmail.com里面没有收到激活代码，只收到付费收据，希望重新发放一下激活代码到注册邮箱，谢谢。

交易 ID | 交易日期
-- | --
w12956**** | 2017-10-12 上午10:48 (GMT-5)
交易日期 | Price
一年套餐 | 216.00 CNY
Total 216.00 CNY

**Comment by xlqz7748** [comment]
直接邮箱地址可以登录吧1

**Comment by Ghostwithout** [comment]
@kaicaysmic 你好，请在左边菜单点击“授权设备使用专业版”，在里面输入购买时的邮箱，激活码就会发到你的邮箱，然后输入激活码即可。谢谢！
