### ISSUE TITLE
通知：北京联通流畅，北京电信不通！

### ISSUE THREAD

**Issue by godliness** [getlantern/forum#6569]
家里是北京联通的，速度飞快，公司是电信的，肯本不通！

**Comment by forgetallthing** [comment]
西城区北京联通，登上专业版就时断时续，退出登录使用免费版反而挺稳定的...

**Comment by ll-githup** [comment]
我的是刚好相反 家里（方正宽带）不通 公司（联通）通

**Comment by zj151** [comment]
公司铁通 家里移动 另外手机4G 都不通 唉

**Comment by godliness** [comment]
我和同事都是一个办公网 北京电信 他能上 我不能  他是网线连接 我是wifi 公网IP都一样的
我就不清楚了。。。。

**Comment by saikame** [comment]
能上谷歌 能上油管 但就是登录不了西瓜？为什么？？？

**Comment by mars1224bj** [comment]
北京联通登陆专业版根本用不了。现在用免费版也不能用了~~~~
