### ISSUE TITLE
北京连不上,快一个月都 用不了神灯,google也用不了,可有解决方案

### ISSUE THREAD

**Issue by yanminmin** [getlantern/forum#6570]
![image](https://user-images.githubusercontent.com/1975597/32422728-a128e362-c267-11e7-8433-052d353d68d8.png)

**Comment by yanminmin** [comment]
北京市北京市 电信

**Comment by yanminmin** [comment]
ERROR detour: detour.go:160 Caused by: Still unable to dial connect://sdk.accountkit.com:443 after 1 attempts
Nov 06 02:42:14.762 - 21m13s ERROR flashlight.client: handler.go:33 Still unable to dial connect://sdk.accountkit.com:443 after 1 attempts [op=proxy origin=sdk.accountkit.com:443 origin_host=sdk.accountkit.com origin_port=443 root_op=proxy user_agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36]
Nov 06 02:42:14.762 - 21m13s ERROR balancer: balancer.go:202 Unable to dial via fp-sbtk1a-20171006-036-obfs4 (47.74.20.39:23008) to connect://connect.facebook.net:443: Unable to dial server fp-sbtk1a-20171006-036-obfs4 (47.74.20.39:23008): dial tcp 47.74.20.39:23008: i/o timeout on pass 0...continuing [detour=true error=Unable to dial via %v to %s://%s: %v on pass %v...continuing error_location=github.com/getlantern/flashlight/balancer.(*Balancer).DialContext (balancer.go:202) error_op=dial error_text=Unable to dial via fp-sbtk1a-20171006-036-obfs4 (47.74.20.39:23008) to connect://connect.facebook.net:443: Unable to dial server fp-sbtk1a-20171006-036-obfs4 (47.74.20.39:23008): dial tcp 47.74.20.39:23008: i/o timeout on pass 0...continuing error_type=errors.Error local_addr=47.74.20.39:23008 local_proxy_type=http network=tcp op=proxied_dialer origin=connect.facebook.net:443 origin_host=connect.facebook.net origin_port=443 root_op=proxy user_agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36]
ERROR balancer: balancer.go:202   at github.com/getlantern/flashlight/balancer.(*Balancer).DialContext (balancer.go:202)
ERROR balancer: balancer.go:202   at github.com/getlantern/flashlight/client.(*Client).getDialer.func3 (client.go:412)
ERROR balancer: balancer.go:202   at github.com/getlantern/flashlight/vendor/github.com/getlantern/detour.Dialer.func1 (detour.go:158)
ERROR balancer: balancer.go:202   at github.com/getlantern/flashlight/client.(*Client).doDial (client.go:370)
ERROR balancer: balancer.go:202   at github.com/getlantern/flashlight/client.(*Client).dial (client.go:342)
ERROR balancer: balancer.go:202   at github.com/getlantern/flashlight/client.(*Client).(github.com/getlantern/flashlight/client.dial)-fm (client.go:155)
ERROR balancer: balancer.go:202   at github.com/getlantern/flashlight/vendor/github.com/getlantern/proxy.(*proxy).dialAndCopy (proxy_connect.go:105)
ERROR balancer: balancer.go:202   at github.com/getlantern/flashlight/vendor/github.com/getlantern/proxy.(*proxy).processRequests (proxy_http.go:131)
ERROR balancer: balancer.go:202   at github.com/getlantern/flashlight/vendor/github.com/getlantern/proxy.(*proxy).Handle (proxy_http.go:92)
ERROR balancer: balancer.go:202   at github.com/getlantern/flashlight/client.(*Client).handle (handler.go:31)
ERROR balancer: balancer.go:202   at runtime.goexit (asm_amd64.s:2337)
ERROR balancer: balancer.go:202 Caused by: Unable to dial server fp-sbtk1a-20171006-036-obfs4 (47.74.20.39:23008): dial tcp 47.74.20.39:23008: i/o timeout
ERROR balancer: balancer.go:202   at github.com/getlantern/flashlight/chained.(*proxy).doDialInternal (dialer.go:221)
ERROR balancer: balancer.go:202   at github.com/getlantern/flashlight/chained.(*proxy).dialInternal.func1 (dialer.go:200)
ERROR balancer: balancer.go:202   at runtime.goexit (asm_amd64.s:2337)
ERROR balancer: balancer.go:202 Caused by: i/o timeout

**Comment by ImHere01** [comment]
可以用无界浏览，我的杀软未报毒，不过速度不行，上谷歌搜索可以的

**Comment by xiguataida** [comment]
不知道为什么，我家是移动的，公司是电信的，但是电信的能翻墙，而家里不行

**Comment by Ghostwithout** [comment]
你好， 
@yanminmin 请到lantern界面反馈问题并上传日志供后台调查。
@xiguataida 不同的宽带服务商访问Lantern服务器的质量不一，所以可能出现公司可以家里不可以。
谢谢！
