### ISSUE TITLE
那么，重庆联通今天能用了吗？不行。

### ISSUE THREAD

**Issue by FruitsBlend** [getlantern/forum#6572]
大会之后就没好过一次，每天来记录一下，希望会叫的孩子有奶吃吧。

11月16日，无法使用，反复断线中。

**Comment by Ghostwithout** [comment]
你好，lantern从10月下旬已经陆续开始恢复，但不同的宽带服务商访问Lantern服务器的质量不一，也是不能连接或者连接缓慢到原因之一。可以尝试换个网络环境以及不同时段访问。如有问题，请到lantern界面反馈问题并上传日志供后台调查。谢谢！
