### ISSUE TITLE
蓝灯我不想骂人，我只想有人帮我解决问题，我已经发了好几个帖子了，你们人都死哪去了

### ISSUE THREAD

**Issue by LeonZXY** [getlantern/forum#6581]
我已经陆陆续续发了很多求助帖子，10月28号到现在一直没办法使用，你们能不能负点责任，我艹！！！！！！！！

**Comment by hhzhaoheng** [comment]
估计地域问题吧，我也是今天测试了下，发现居然能用了，赶紧同步下我的标签

**Comment by whyrookie** [comment]
杭州，基本不能用。。有一两次可以，这都什么时候了，还不行，这的该喷啊

**Comment by cool-firer** [comment]
声援

**Comment by chriema** [comment]
杭州大部分都已经可以用了啊，我这里基本都在用了。另外我想说很多连不上可能是自己的问题造成的。。建议先排查自己，毕竟有很多朋友都已经可以用了

**Comment by yjfzz** [comment]
他妈的，管他什么地域问题，付了钱不能用就要负责，就应该要退款！没技术就不要收钱！！！申请退款！！！申请退款！！！申请退款！！！申请退款！！！申请退款！！！申请退款！！！申请退款！！！申请退款！！！申请退款！！！申请退款！！！申请退款！！！

**Comment by 6726** [comment]
前几天已经能用了，前两天速度不行，今天速度很快

**Comment by effygwave** [comment]
你到lantern界面去反馈问题，那样可以上传日志，才能便于检查问题 @LeonZXY

**Comment by LeonZXY** [comment]
@effygwave lantern的页面都打不开

**Comment by shiwanxin** [comment]
换别的吧

**Comment by FuckSB** [comment]
你买之前应该了解清楚，蓝灯是个开源软件，一群程序员组成的开发团队，没有什么所谓的客服，不可能给你开小灶专门耐心解决你的问题。要客服，国内国外各种vpn多的是

**Comment by LeonZXY** [comment]
@FuckSB 那现在就忍着是么？

**Comment by FuckSB** [comment]
@LeonZXY 没有任何这个意思，只要蓝灯还在更新还没有跑路，只有等开发团队修复。本人2年的还有2个月到期，之前用着挺不错的，就这个月敏感时期不稳定。到期后我不打算续费了，并不是不信任蓝灯，而是知道这个东西的人越来越多了，梯子这种东西只要知道的人多了只有一个下场。
