### ISSUE TITLE
很抱歉，蓝灯似乎未在运行。请重启蓝灯并重试。

### ISSUE THREAD

**Issue by animationhankhuo** [getlantern/forum#6588]
提示：很抱歉，蓝灯似乎未在运行。请重启蓝灯并重试。
而且开机自动启动，在提示上面信息之前点开设置，开机启动按钮为关。
无法升级到专业版，一开蓝灯就提示上面信息然后点击重试一样。已经按照帖子操作进行过操作没用
顺带一提刚更新的4.4
邮箱847821475@qq.com
现在想要登陆专业版的话我是是用以前的 3.6.3版本登陆专业版然后用4.4版本覆盖安装
下面为log
[lantern.log](https://github.com/getlantern/forum/files/1445751/lantern.log)

![image](https://user-images.githubusercontent.com/20492352/32435818-0905ab22-c31d-11e7-9e24-48332e2fcc01.png)
![image](https://user-images.githubusercontent.com/20492352/32435821-0b753940-c31d-11e7-8f3c-dfdd496e16f0.png)

**Comment by Ghostwithout** [comment]
你好，根据日志，你到帐号已经更新到4.4.0，同时能成功连接服务器。请试试点击退出lantern再重新打开。谢谢！

**Comment by animationhankhuo** [comment]
然而点击重试之后 仍然是这个样子的，可能是系统的原因么？要不要我尝试重装系统？

**Comment by dingjiheike** [comment]
蓝灯可以用啊  我这边刚弄好

**Comment by animationhankhuo** [comment]
你看我截图里 连版本都显示不出来……我觉得 不是网络的问题了都

**Comment by animationhankhuo** [comment]
[lantern.zip](https://github.com/getlantern/forum/files/1450596/lantern.zip)

我用uninstall卸载之后，重启电脑，再次安装，未登录状态下仍为截图情况log已上传，请管理员排查
![2](https://user-images.githubusercontent.com/20492352/32502083-c56ef960-c414-11e7-8d5c-45c5749e191b.PNG)

**Comment by stepinsky** [comment]
我也是同样的问题，实际上已成功科学上网，但是没法看到状态，需要给其他设备授权就不能做，显示界面一直是提示错误，请尽快解决

**Comment by animationhankhuo** [comment]
恩，的确不登录状态确实可以科学上网，但油管视频看都看不了，不管多少清晰度，播放按钮都点不了，应该是速度的原因吧，不太清楚。
但，登陆专业版之后（安装3.6.3版本登陆再用4.4覆盖安装），有时候连百度都打不开，很奇怪。

**Comment by animationhankhuo** [comment]
问题已解决，不知道什么原因跟，重置LSP后安装3.6.3版本也发生连接失败（可能是低版本的过失），重新用4.4覆盖后就好了。此问题closed

**Comment by stepinsky** [comment]
我安装3.6.3版本后重新用4.4覆盖还是一样的错误，不能解决问题，邮箱4804577@qq.com
