### ISSUE TITLE
退出登录问题

### ISSUE THREAD

**Issue by fresh08** [getlantern/forum#6590]
退出登录时，出现
![issue](https://user-images.githubusercontent.com/13703811/32437044-fee66704-c320-11e7-88b3-fc8f1456dbec.png)
这台电脑是公司电脑，
怎么解绑这台设备？

**Comment by Ghostwithout** [comment]
你好，lantern默认只有一台设备到时候不能解绑，如果你需要解绑公司电脑，你可以授权其他设备后再解绑这台。谢谢！
