### ISSUE TITLE
蓝灯全面恢复可用！别嚷嚷退钱了！别逼逼了！

### ISSUE THREAD

**Issue by AquaHacker** [getlantern/forum#6593]
蓝灯全面恢复可用！有些人别有用心，就别逼逼了。

可以说
政府很希望蓝灯的口碑从此一蹶不振
然后大量流失用户
这样就不攻自破省的花钱人力跟蓝灯较量了！

目前蓝灯可用，就不要炒热度了。低调的用！

那些嚷嚷退钱的。呵呵。傻逼！退你麻痹啊！

蓝灯付费用户在线率为97%-100%

别问我怎么知道的！别没事捣乱！

**Comment by lemonskkyt** [comment]
看完我马上关掉赛风，打开lantern，嗯，看来我不是lantern用户

**Comment by YosimaK** [comment]
不知道你这97%哪来的

**Comment by maomaochong1003** [comment]
胡扯，我这里一直上不了

**Comment by Yiranwu** [comment]
抽奖而已

**Comment by q474818917** [comment]
曹你mabi，97%尼玛币啊，眼瞎

**Comment by anole1980** [comment]
楼主不会是个傻子吧！？

**Comment by 1soYang** [comment]
笑笑，不说话

**Comment by crazyrock98** [comment]
我这里可以用了，速度稳定

**Comment by dreday966** [comment]
用不了啊

**Comment by liuluck7** [comment]
楼主就是个煞笔玩意，能你麻痹啊。草你吗的狗 B

**Comment by ningqivip** [comment]
尼玛个傻逼，劳资就不能用

**Comment by GodHasBug** [comment]
你妈死了

**Comment by til000** [comment]
全你妈  你上不上关我屁事，我没上才是重要的。

**Comment by hansanning** [comment]
好吧 我是那3%

**Comment by 6726** [comment]
几天前就可以用了，不能用的有升级到最新版吗？

**Comment by Ricky-Tsang** [comment]
樓主是個大智障阿 能上的話有毛功夫上來噴 水軍？你憑什麼去代表你口中的97% 智障阿 你媽炸了還不趕緊回家

**Comment by HelloXiaoxi** [comment]
说得好，那帮狗肯定在19big期间买了别家的vpn，现在蓝灯完全恢复了又嚷嚷退钱，我去你妈的，退尼玛b。

**Comment by PotatoSmith** [comment]
安静的在国内好好打字不好么，键盘侠翻墙意义何在？

**Comment by molur1234** [comment]
不能用的，看着骂骂咧咧就是人品问题，活该。当然不怀疑是其他商家水军，现在欺骗广告不好用了，就换个方式诋毁。

**Comment by lucasat7startent** [comment]
看到这么多人在骂楼主我就放心了

**Comment by 1561316811** [comment]
麻痹，我这不能用，试用版可以，专业版交钱反而不行。一天都没用到，今天刚买的，垃圾，退钱，狗比楼主。

**Comment by 1561316811** [comment]
你死全家，楼主，我超你妈

**Comment by 1561316811** [comment]
垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾垃圾

**Comment by q474818917** [comment]
这sb肯定是lantern官方的，大家怼着这sb骂

**Comment by 1561316811** [comment]
不能用的都过来骂

**Comment by lcx913** [comment]
用不了不知道回报问题吗？这几天都在慢慢恢复，楼上少在这煽风点火

**Comment by 1561316811** [comment]
回报，没用没用没用，垃圾垃圾，刚买的就不能用。

**Comment by misland** [comment]
不能用，楼主是何居心，有问题不赶紧解决在这里造谣有何用？

**Comment by husheng333** [comment]
能用了，但是下载和以前一样只有100KB等于用不了

**Comment by lcx913** [comment]
我这边恢复得差不多了……pixiv是我回报过才能上的，看样子有地区问题，不是很懂这方面的东西

**Comment by dingjiheike** [comment]
唉 真服了你们，不就翻个墙而已，非得要升个啥专业版，现在蓝灯出问题了，又想着赔偿，无语了。。。你们每发一个帖子，我这边就一封右键，今天一天 我都收到了200多封，全部都是说蓝灯的帖子，我也服了你们了。砸了了钱了，出了问题了，等它修复不就行了，急啥呀  你要看视频，今天看跟明天看不也是一样吗，又不是家常便饭非得天天吃，也别说我是喷子啥，我也知道你们花几百块之后不能翻墙，心里不舒服，我也有过类似的，不过还好我现在经济不是很好，在升级蓝灯专业版的时候，硬是下不去手，还好没点，看到你们你在这发牢骚了。不过条条大路通罗马，你们难道就没有其他的办法翻墙么- -想我几十G的资源也是翻墙下载来的，蓝灯这玩意我也是几个月前才知道这个玩意是翻墙用的，所以说兄弟们，省省吧，你们要是骂能解决问题的话，估计这事早就完了。这程序是人写的，出了bug了，那程序员自个心里也不好受，毕竟他的加班加点的找bug，搞不出啥情况，服务器又给蹦了，那心情可贼鸡巴难受，就跟你们现在差不多一样的，将心比心吧。我只是说说而已，你们要接着喷，我也不拦你们，毕竟蓝灯也不是我家的。时间不早了 22：28了，早点休息吧。晚安了~

**Comment by q474818917** [comment]
楼上的兄弟说的话我不同意，结合现在的共享单车想想，都是小额款，都想着卷一波走人呢，更何况这都没有法律监控的，共享单车还有政府部门帮忙解决问题呢，lantern随时随地都可以卷一波走人

**Comment by dingjiheike** [comment]
我又没说不让你们喷，我只是说说而已，你们自个当初买的时候就应该想清楚这玩意，国内就不让你们翻墙，你们自个要花钱弄个这玩意，出了问题还嚷嚷着要赔偿，怪谁？lantern出了问题，你们也只能等着，要么等他们修复好，你们接着用，要么就像你说的，等他们铺盖走人。 这样嚷嚷着的说退款退款也只能是让他们给你们一点甜头，这不补偿你们一个月了。

**Comment by williamddd** [comment]
国内的基本都被封杀了，就是存活的，也存在跑路风险，你还是直接买国外的吧
zhihu.page.tl
http://williamddd.doodlekit.com
https://diigo.com/0anh1v
