### ISSUE TITLE
这蓝灯逼疯了一群狗，引来了一群狼。

### ISSUE THREAD

**Issue by molur1234** [getlantern/forum#6603]
到底那些是狼是狗也分不清。那些不能用的现在还咬那些说能用的，真搞不懂，是不是咬不到蓝灯，对正常的就看不顺眼了，真是疯了。

**Comment by Restlessness** [comment]
擒获圣母婊一枚

**Comment by HelloXiaoxi** [comment]
那帮狗就想退钱，sb退尼玛个毛。就不给丫退，哈哈哈。老子继续youtube啦。

**Comment by PotatoSmith** [comment]
侮辱别人来体现自身高雅？？

**Comment by beboyss** [comment]
有的人就是贱，自己得了便宜，还他妈的卖乖，坐看HelloXiaoxi这只狗不能用的时候怎么叫唤

**Comment by molur1234** [comment]
都相信有很多人不能用，也没取笑不能用的，主要这群疯狗跟着那广告狗看着谁说能用就咬。
