### ISSUE TITLE
蓝灯qq邮箱收不到专业版登陆密码啊！

### ISSUE THREAD

**Issue by Chrisxi0318** [getlantern/forum#6613]

**Comment by George-Kou** [comment]
我的也是，一直收不到邮件，以前邮件几乎秒发的。幸亏专业版在电脑上登陆了，然后昨天授权了手机端的蓝灯。

**Comment by 26141** [comment]
之前都是秒发，现在基本要等3-5小时才能收到

**Comment by Ghostwithout** [comment]
你好，左边菜单点击“授权设备使用专业版”，在里面输入购买时的邮箱，激活码就会发到你的邮箱，然后输入激活码即可；如果是绑定新设备，请在新设备选择“授权设备使用专业版”，该界面会收到验证码，然后请到专业版设备输入验证码。谢谢！
