### ISSUE TITLE
错误或者无效的设备关联码

### ISSUE THREAD

**Issue by zackfly** [getlantern/forum#6615]
![1](https://user-images.githubusercontent.com/5593858/32473707-e71a7150-c3a3-11e7-9bbe-23ab5d25e5e3.png)
无法给我的pc授权
账号3996643046@qq.com

ps. 这个邮箱是我注册的时候写错了，能改成huxiaofan@outlook.com吗？

**Comment by userfirstone** [comment]
拉闸……

**Comment by zackfly** [comment]
@userfirstone 拉闸是什么意思。。。

**Comment by zackfly** [comment]
@angelwithout @Ghostwithout

**Comment by zackfly** [comment]
@GLantern

**Comment by zackfly** [comment]
@lanterncyborg

**Comment by zackfly** [comment]
@angelwithout
