### ISSUE TITLE
购买pro后显示的时间有点问题

### ISSUE THREAD

**Issue by soZra** [getlantern/forum#662]
刚买了一年后，帐号管理那里显示的是1970年就过期了，什么情况，是bug吗？
![lan](https://cloud.githubusercontent.com/assets/18065661/16895696/672dfb1c-4bb1-11e6-9ff2-f2e2e813273f.png)

**Comment by p3rcya** [comment]
请按照此帖上传log https://github.com/getlantern/forum/issues/358 ，方便我们调查，谢谢

**Comment by soZra** [comment]
@p3rcya  
[lantern.txt](https://github.com/getlantern/forum/files/367605/lantern.txt)

**Comment by soZra** [comment]
@p3rcya 我还刚发现了一个问题，明明蓝灯就在后台运行着，但是每次点显示蓝灯打开的网页都是未登录的，要重新登录，而且好像使用的也是免费版的流量，

**Comment by p3rcya** [comment]
我们正在调查
