### ISSUE TITLE
Mac最新版lantern无法打开，专业版用户（附上log）

### ISSUE THREAD

**Issue by LemonadeCandy00** [getlantern/forum#6630]
专业版今年2月后几台电脑连着用着都没问题，十九大期间无法连接后尝试退出重启就再也没办法打开应用，即点击图标safari不会自动打开应用页面，上方状态栏里面也不会有蓝灯图标。log已经附上了，尝试过论坛里解决方式但是没看懂 _“端口为***”_ 这一部分就没有成功，删除重装蓝灯很多次也没有用。之前蓝灯用着一直都挺好的，但如果之后连应用都打不开就觉得很郁闷，请管理员帮忙看下我这边是什么原因，谢谢！

专业版账号：402857090@qq.com

报告时间：2017.11.07 15:18

问题发生时间：大约10月5日

[lantern log.zip](https://github.com/getlantern/forum/files/1448984/lantern.log.zip)

**Comment by HelloXiaoxi** [comment]
虽然都是mac但我的可以正常使用。
帮顶，问题叙述很完整。

**Comment by LemonadeCandy00** [comment]
补充：目前用Firefly替代中，可以连上。如果是设置的问题的话最初lanter那能正常使用也有点说不通。想念用lantern刷油管的时光QAQ

**Comment by xudonghai123** [comment]
我的也是MAC专业版   从昨天开始正常使用

**Comment by LemonadeCandy00** [comment]
@HelloXiaoxi 谢谢帮顶～打不开某种意义上比连不上更郁闷……你用的时候有没有设置过端口呀？mac小白虽然找到了设置的地方但是不知道***是什么意思，而且*号也没法输入，懵圈ing

**Comment by LemonadeCandy00** [comment]
用Mac的层主们有没有设置过端口呀～管理员不知道什么时候能看到，如果有人设置成功的话真心求教！

**Comment by Edward27W** [comment]
我把DNS改成8.8.4.4之后就能用了。

**Comment by LemonadeCandy00** [comment]
@Edward27W 我的电脑不行，好气哦QAQ不过还是谢谢你～

**Comment by whimsycwd** [comment]
@Edward27W 不太懂是什么原理。 在瞎试 ， 做了两个事情
1. 重新下了最新版的lantern
2. 把DNS改成 8.8.4.4

不确定是什么起作用了。 方便讲一下原理？

**Comment by Edward27W** [comment]
@whimsycwd 我之前用8.8.8.8，尽管能连上但是根本打不开网页；后来无意中发现8.8.4.4是谷歌的备用DNS，心想试试看就成功了。我估计是前一个地址被某种手段堵塞了，而后一个暂时还安全。

**Comment by Edward27W** [comment]
@LemonadeCandy00 不客气，看来也不是所有地方都管用

**Comment by LemonadeCandy00** [comment]
自顶

**Comment by LemonadeCandy00** [comment]
再顶

**Comment by LemonadeCandy00** [comment]
好的解决了……问题发生几天后mac系统更新，之前没在意后来更新了一下搞定。谢谢给我提供建议的各位
