### ISSUE TITLE
2017.11.08 下载了最新版本4.4.0，管理员身份安装并且运行（提示是否允许此程序改变计算机，确定）后，未出现任何反应。任务栏里查看没有蓝灯的小图标，也未像以前自己弹出一个蓝灯的Chrome网页。这不是第一次了， 前几天也试过，但前几天卸载4.4.0，装回以前的3.6.2后，可以看到任务栏蓝灯小图标和打开的蓝灯Chrome主页。

### ISSUE THREAD

**Issue by lib5515** [getlantern/forum#6682]
2017.11.08 下载了最新版本4.4.0，管理员身份安装并且运行（提示是否允许此程序改变计算机，确定）后，未出现任何反应。任务栏里查看没有蓝灯的小图标，也未像以前自己弹出一个蓝灯的Chrome网页。这不是第一次了， 前几天也试过，但前几天卸载4.4.0，装回以前的3.6.2后，可以看到任务栏蓝灯小图标和打开的蓝灯Chrome主页。

**Comment by HelloXiaoxi** [comment]
能用哪个用哪个啊 我去  这tm肯定是你系统问题啊宝贝。
