### ISSUE TITLE
蓝灯被封是活该，封了好，封了妙。特么的一天到晚发布反动言论你特么不被封才怪。嫌中国不好？滚回你霉国爹那里去！

### ISSUE THREAD

**Issue by wxp11** [getlantern/forum#6716]
热烈庆祝蓝灯被封。

**Comment by godliness** [comment]
Stupid donkey

**Comment by wxp11** [comment]
@godliness 杂种

**Comment by hxhysy1994** [comment]
看着傻逼玩意，你就是翻墙看反动呢？怨不得心里和长屎了一样，反也反的是你这种杂种，自己啥逼样看别人就傻逼样？你真为你狗妈心疼，有你这么个狗儿子你爸也给每天吃屎养你，真他妈的废物，这么讨厌上你妈国外网，滚回自己狗窝带着不好？出来丢你狗爹妈的脸？

**Comment by fujianchina** [comment]
大部分人都不是傻子
内容真假一看便知只要他不是傻子
再说大部分也不会去看那些内容
狼友应该更多的吧？
我们是有挺多问题至少比以前要好蛤蟆时代真叫差劲
