### ISSUE TITLE
蓝灯白天特别慢，晚上速度很快，是不是白天在线用户数多导致的？

### ISSUE THREAD

**Issue by leolingg** [getlantern/forum#6761]
#### 问题描述：
> 我公司网络江苏南京的电信，白天使用蓝灯特别的慢，打开一个google的首页都需要15多秒甚至更长，
或者直接提示网络不可到达，白天打开youtube等基本比这个慢的更多；晚上速度很快基本打开秒开；
是不是跟白天在线用户数多的原因？如果是这样是否应该考虑增加节点服务器数量或者带宽？

**Comment by YosimaK** [comment]
跟你的带宽没关系，之前是免费版能上，现在是专业版能上了，我怀疑免费版和专业版服务器对换了，现在很稳定，但是速度慢，而且连接上的时候左下角显示谷歌的服务器了，不是阿里的了  所以慢
