### ISSUE TITLE
蓝灯侠带来一个可触发，又绝对不应该触发的bug

### ISSUE THREAD

**Issue by Amouwar** [getlantern/forum#6828]
各位蓝灯用户你们好：
在购买蓝灯时，不管你是直接购买还是通过代理商购买，都有概率触发这个bug
当你完成付费或者输入激活码之后下面会有一个继续的选项点击之后会有几秒钟完全无响应，这个时候不是程序卡了而是在确认交易，懒灯又懒得写个等待的界面，最快一年才出一次的界面貌似真不重要，但是！这几秒钟内强行退出蓝灯是可行的，如果你在这几秒钟内强行退出了蓝灯，那么不管你什么设备绝对会触发这个bug！
你的账号绝对是专业版账号，你的账号绝对会在登录后三十秒内闪退！表示不知道怎么解决望蓝灯重视

**Comment by ATcn** [comment]
清空重装，从服务器重新拉取资料，不能解决？

**Comment by Amouwar** [comment]
你不仅清空重装无法解决，就算是你换一个新设备装一个新蓝灯来登录也无法解决！这个bug目前我没有找到解决方法

**Comment by chengfan2017** [comment]
你又解决不了，说什么

**Comment by Amouwar** [comment]
为了更少的人触发这个bug

**Comment by sincerelamb** [comment]
卧槽我有台电脑就是这个bug
现在怎么都登录不上lantern

**Comment by angelwithout** [comment]
感谢上报这个问题。

**Comment by orbancanon** [comment]
换新设备装蓝灯也不行？这似乎跟原来的帐号没有丝毫关系啊。有相关日志可以看不 @Amouwar ？如果你在Lantern界面上报告过问题的话，请告诉我报告时的邮箱。

**Comment by sincerelamb** [comment]
你好
我这里新设备倒是没问题
老设备闪退 不停闪退
没法在界面上报告问题

**Comment by orbancanon** [comment]
@sincerelamb 请按https://github.com/getlantern/forum/issues/1840#issuecomment-260143243 的方法手工收集日志，传到这里或者发给我orbancanon@gmail.com

**Comment by sincerelamb** [comment]
之前我不知道可以发issue还以为是我自己机器的问题
重装系统了...目前运行平稳

**Comment by sincerelamb** [comment]
@orbancanon  看看吧 今天出现的
发你邮箱

**Comment by orbancanon** [comment]
@sincerelamb 从你的日志里看到以前曾有人报告过一次的灵异现象：蓝灯开始工作得还不错，但运行到整2分钟时就悄悄地被干掉了……迄今无解

你回忆一下是不是每次都是两分钟？

**Comment by orbancanon** [comment]
这个应该是不定期出现吧，而不是反复闪退

**Comment by 709979651** [comment]
@orbancanon 买完专业版就没用过，绑定之后说是已到期让续费，问题我才刚买的两年的，邮箱709979651@qq.com，您给看下

**Comment by sincerelamb** [comment]
这是新出现的 应该是你说的那种情况..

**Comment by 709979651** [comment]
@orbancanon 能帮忙看看怎么回事吗

**Comment by orbancanon** [comment]
@709979651 没查到你最近的购买记录呢？请把购买记录截图发邮件到orbancanon@gmail.com，我好查证

**Comment by 709979651** [comment]
@orbancanon 已发，帮我看下，多谢

**Comment by 709979651** [comment]
@orbancanon 请问收到了吗，什么时候可以恢复正常
