### ISSUE TITLE
折价转卖蓝灯专业版26个月，三台设备

### ISSUE THREAD

**Issue by snfh2014** [getlantern/forum#6831]
暂时不需要了，有人需要吗，专业版3台设备，还剩26个月

**Comment by ruyiyuerqu** [comment]
怎么转呀，多少钱

**Comment by snfh2014** [comment]
@ruyiyuerqu走阿里?     200可以?我看邮箱能不能换，换不了也没关系随时联系我就成

**Comment by ruyiyuerqu** [comment]
@snfh2014  留微信号我加你聊下，刚发现这个软件和论坛，还不是很懂，有私信的话私信我微信号也可以

**Comment by snfh2014** [comment]
@ruyiyuerqu 这个snfhhfns

**Comment by ruyiyuerqu** [comment]
@snfh2014 是微信号吗？该用户不存在==

**Comment by snfh2014** [comment]
你加qq吧，907218578

**Comment by shiwanxin** [comment]
哈哈远去的蓝灯

**Comment by tudoser** [comment]
请问你在IOS端用的哪款VPN，可以分享下吗？谢谢

**Comment by snfh2014** [comment]
已经转了，谢谢关注
