### ISSUE TITLE
不打算使用了, 有需要的就直接用吧。账号：wujunbo1111@yeah.net

### ISSUE THREAD

**Issue by negativelo** [getlantern/forum#6836]
请在发帖前先按照蓝灯无法使用的解决办法 https://github.com/getlantern/forum/issues/1902 自行解决。自行解决问题通常只需要几十分钟。管理员调查解决问题需要几天至几周。请立即访问https://github.com/getlantern/forum/issues/1902 瞬间解决98%的问题

为了能在最快的时间内解决大家使用蓝灯遇到的问题，请各位用户严格按照发帖格式提交问题。

## 发帖格式
遇到的问题：请详细描述遇到的问题。如果描述不仔细，将无法调查

蓝灯专业版账号Email:  请提供登陆蓝灯专业版的email，免费版不提供技术支持。

应用内报告问题的时间:  请根据 https://github.com/getlantern/forum/issues/1840 在应用内上报问题，请填写专业版的email。请在帖子里注明报告的时间。

截图: 请提供有关问题的截图。 请把图片拖拽到这里。

----
邀请码在本论坛请以签名形式发布或发到其他论坛。具体见 https://github.com/getlantern/forum/issues/3773

**Comment by corningsun** [comment]
@negativelo 大兄弟，我收不到 邮箱验证码啊。。

能不能授权我的设备使用您的专业版帐户，谢谢啦！

动态授权码：**068398**

![](https://i.imgur.com/EiDnsYP.png)

**Comment by negativelo** [comment]
@corningsun 失误，我也是第一次这么弄。我还说怎么一直发这个。最新的一个是930540。不行的话就重新点下

**Comment by KbSimon** [comment]
大佬 我也想用 能发下邮箱登陆码么 ？ 谢谢啦！

**Comment by chuckcai6419** [comment]
同求！

**Comment by chuckcai6419** [comment]
同求，感谢分享一下登录码！

**Comment by makunhua** [comment]
感谢！求分享登录码

**Comment by negativelo** [comment]
不知道可行不 登录码太多了 被当作垃圾邮件处理了
![qq 20171113131730](https://user-images.githubusercontent.com/4110994/32710714-5ec85624-c875-11e7-8e48-b83fd1a8be9a.jpg)

**Comment by makunhua** [comment]
哥们，这个是邀请码，不是分享码😊，分享码是纯数字，麻烦您了！

2017年11月13日 09:22，"伍俊波" <notifications@github.com>写道：

**Comment by negativelo** [comment]
我也绝望啊 找不到分享在那
![qq 20171113135228](https://user-images.githubusercontent.com/4110994/32711535-5fb66968-c87a-11e7-89c8-84271d75bd6d.jpg)

**Comment by makunhua** [comment]
你收到蓝灯发给你的邮件📩，应该在邮件里。

2017年11月13日 09:56，"伍俊波" <notifications@github.com>写道：

我也绝望啊 找不到分享在那
[image: qq 20171113135228]
<https://user-images.githubusercontent.com/4110994/32711535-5fb66968-c87a-11e7-89c8-84271d75bd6d.jpg>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/getlantern/forum/issues/6836#issuecomment-343821444>,
or mute the thread

**Comment by negativelo** [comment]
430503

**Comment by makunhua** [comment]
搞定，非常感谢！祝快乐！

2017年11月13日 10:09，"伍俊波" <notifications@github.com>写道：

**Comment by chuckcai6419** [comment]
@negativelo 刚看到，又过期了，还能分享下么？

**Comment by negativelo** [comment]
@chuckcai6419 设备应该满了 094007 356055 发了两个前面那个是最新的

**Comment by chuckcai6419** [comment]
@negativelo
 谢谢，还没满！登录了～非常感谢

**Comment by corningsun** [comment]
@negativelo 
可以用，非常感谢～
![](https://i.imgur.com/yWJzHEn.png)

**Comment by jianzhao0806** [comment]
大佬，发下验证码😁😁😁😁

**Comment by negativelo** [comment]
最新一个527465

**Comment by makunhua** [comment]
朋友，你好！我换手机了，麻烦你重新给我一下验证码，谢谢！

2017年11月14日 09:13，"伍俊波" <notifications@github.com>写道：
