### ISSUE TITLE
出租一个设备位，11个月80

### ISSUE THREAD

**Issue by zhaoweihaoChina** [getlantern/forum#6870]
账号还有11个月，因为前阵子蓝灯故障我买了服务器搭建SSR，所以要出租一个设备位帮补一下
11个月80，一个月10，需要的留言或者联系我邮箱：zhaoweihaochn@foxmail.com
我会尽快回复

**Comment by Carlbowen** [comment]
您好，我想使用PC端的蓝灯专业版，但一直没找到安装包，您有安装包吗，方便的话，发我下，谢谢
476503522@qq.com

**Comment by zhaoweihaoChina** [comment]
@Carlbowen 发过去了
