### ISSUE TITLE
官方文档不够详细，问了很多遍没人回答的问题，求帮助！！!

### ISSUE THREAD

**Issue by zach007** [getlantern/forum#6883]
请问无图形界面应该怎么安装lantern呢？有技术人员支援一下吗，真的问了好久，一个多月了~
以下官方文档看不懂，求帮助！
Building Lantern for running on a server

To run Lantern on a server, you simply need to set a flag to build it in headless mode and then tell it to run on any local address as opposed to binding to localhost (so that it's accessible from other machines). You can do this as follows:

HEADLESS=true make docker-linux or, if you're already running on Linux just HEADLESS=true make linux
./lantern_linux_amd64 --addr 0.0.0.0:8787 or ./lantern_linux_386 --addr 0.0.0.0:8787

**Comment by dxccat** [comment]
@zach007 我猜测，是这样的。仅仅是猜测，我不太懂linux以及终端等界面，如果又误还请见谅。
先明确自己linux系统的网络ip地址，假设你的linux服务器地址为192.168.1.1，那么打开终端（terminal），输入
`./lantern_linux_amd64 --addr 192.168.1.1:8787`（64位系统）或者
`./lantern_linux_386 --addr 192.168.1.1:8787`（32位系统）
不过是否需要首先进入蓝灯的安装路径，或者上述命令需要在root环境下运行，可能需要自己试一试。
配置好后，在别的电脑上配置代理服务器，服务器地址为192.168.1.1，端口为8787。当然，你的其他电脑如果也是无图形界面的情况，你可以查一下具体的配置命令。
如果可以，可以回帖说明一下。如果我的方法不可行，也许我们可以再进行探讨。
