### ISSUE TITLE
付费后邮箱未收到激活码

### ISSUE THREAD

**Issue by mythria** [getlantern/forum#7003]
购买了2年的Pro版，未收到激活码。看之前的帖子，有人也是用的网易邮箱，也没收到激活码。所以是网易邮箱的问题吗？怎么才能找回激活码呢？

**Comment by ddianxing** [comment]
没有激活码的，付款后账户自动就升级为Pro用户了。

**Comment by mythria** [comment]
@ddianxing 但是如果我要添加一台新设备，就要求我输入购买Pro版的邮箱、以及25位“激活码”，这个激活码是在哪里找的呢？

**Comment by ddianxing** [comment]
不需要那么麻烦的，添加新设备时在新设备上选择“已有账号，关联此设备”，会得到一组数字，再在已登录账户的设备中填入这组数字，新设备就会自动关联上了。

**Comment by mythria** [comment]
@ddianxing 明白了。谢谢！
