### ISSUE TITLE
不能登录google play

### ISSUE THREAD

**Issue by azad211** [getlantern/forum#704]
google play已经登录了，但还是无法进行下载，点击下载时一直提示“需要验证身份，您需要登录自己的google帐号”

**Comment by p3rcya** [comment]
那是你Google账号的问题，请按照Google要求验证

**Comment by azad211** [comment]
google play里已经显示我登录后的账户名称了，我也成功开启手机号登录功能了，但是在google play 里还是一点下载就提示我“需要验证身份，您需要登录自己的谷歌帐号”

**Comment by azad211** [comment]
在手机设置里，把谷歌账户移除后又重新添加一遍后就可以啦～～～
