### ISSUE TITLE
有没有想一起买个专业版账号的？专业版账号可以供三台设备使用，花费可以平摊

### ISSUE THREAD

**Issue by liuheng0315** [getlantern/forum#7054]

**Comment by orange520** [comment]
現在這玩意都不知道能用不

**Comment by dxt147258** [comment]
可以算我一个

**Comment by liuheng0315** [comment]
@orange520 @dxt147258 留你们的联系方式，我加你们，或者你们加我Q：244802041，不忽悠人的，可以加微信，三人平摊，不会骗人也不会闹眼子！！

**Comment by liuheng0315** [comment]
速度还挺快，看1080P的还是可以，购买了两年的蓝灯，目前还有27个月，出售两个位子，本人只用的到一个，位子一个月5块钱就好，图个方便开的，需要的请联系我qq：244802041，输入我的邀请码 HQ4DS5 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
