### ISSUE TITLE
用lantern登录不了第一会所了

### ISSUE THREAD

**Issue by yzs0324** [getlantern/forum#706]
Windows和安卓版都登不上，Windows提示Gateway Timeout，求破

**Comment by Rice321** [comment]
请将logs 发送到 #358 便于我们团队进一步发现问题，改善问题。谢谢

**Comment by yzs0324** [comment]
https://pan.baidu.com/s/1gfK3X1T

logs.rar



@Rice321 我logs文件夹里有6个文件，不知道上传哪个好，就打包上传了

**Comment by Rice321** [comment]
@yzs0324  请发送到→ #358 thanks!

**Comment by Hwatu** [comment]
第一会所 地址是? 我帮你测试一下.

**Comment by yzs0324** [comment]
OK了，能上了
