### ISSUE TITLE
已经付费，为什么还不能使用？显示无法根据以上信息找回账号！！！！！

### ISSUE THREAD

**Issue by liuheng0315** [getlantern/forum#7089]
已付费，无法使用，有没有相关人员解答一下

**Comment by 571114078** [comment]
借楼，本人11月 19号购买的一年蓝灯专业版，现还有一个设备位出租，10块一个月简单粗暴，微信扣扣同号 571114078。闲着也是闲着，不如拿出来分享下，需要的联系小弟。
![qq 20171120232345](https://user-images.githubusercontent.com/24888919/33026541-9deeadf4-ce4b-11e7-96e5-2dc479581af7.png)
