### ISSUE TITLE
付款之后没有换成专业版，还是不能使用！！请客服联系我一下，这样搞我很绝望！！！！

### ISSUE THREAD

**Issue by liuheng0315** [getlantern/forum#7091]
付款之后还是显示的普通版本，没有升级为专业版， 请客服尽快联系我244802041@qq.com发邮件联系我可以告知更详尽联系方法.

请在发帖前先按照蓝灯无法使用的解决办法 #1902 自行解决。自行解决问题通常只需要几十分钟。管理员调查解决问题需要几天至几周。请立即访问#1902 瞬间解决98%的问题

为了能在最快的时间内解决大家使用蓝灯遇到的问题，请各位用户严格按照发帖格式提交问题。

**Comment by 571114078** [comment]
借楼，本人11月 19号购买的一年蓝灯专业版，现还有一个设备位出租，10块一个月简单粗暴，微信扣扣同号 571114078。闲着也是闲着，不如拿出来分享下，需要的联系小弟。
![qq 20171120232345](https://user-images.githubusercontent.com/24888919/33026522-9049dc14-ce4b-11e7-81bb-37d065e18e31.png)

**Comment by liuheng0315** [comment]
蓝灯速度还挺快，看1080P的还是可以，输入我的邀请码 HQ4DS5 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by Ghostwithout** [comment]
你好，请告知你购买时的邮箱，以便查询。建议到lantern界面反馈问题，上传日志可调查。谢谢！@liuheng0315
