### ISSUE TITLE
无法根据以上信息找回账号

### ISSUE THREAD

**Issue by yumenwakaka** [getlantern/forum#7093]
付款成功 邮箱里已经收到付款收据 但是没有收到code 也没有自动更新成专业版
用邮箱登录显示 无法根据以上信息找回账号
看到请联系13811359141@163.com

**Comment by liuheng0315** [comment]
一样的问题，客服看到请联系liuheng0315@gmail.com，请尽快解决

**Comment by yumenwakaka** [comment]
我的 刚好了 你的好了么
