### ISSUE TITLE
大家都来谈一谈，论人与人之间的信任！！！！

### ISSUE THREAD

**Issue by liuheng0315** [getlantern/forum#7105]
买了一个专业版的账号，其他蓝灯爱好者也在我这里买了多余的位子，我个人只用一个位子就好，所有多出两个位子，感谢有几位老哥能相信我，和我一起平分了专业账号的money，我也没有赚他们的什么钱，只是自己图个方便而已，再次感谢相信我的老哥！！！所有说我觉得这个社会上人与人之间的信任还是存在的，只是碰见了那些坑蒙拐骗的，让我们不在相信其它人而已。
我相信能在github上面玩一下的人，一般都是能够信任的人！哈哈，谈一下你们的想法吧。。。。
以下是我的邀请码，输入我的邀请码 HQ4DS5 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by liuheng0315** [comment]
以下是我的邀请码，输入我的邀请码 HQ4DS5 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by 854010588** [comment]
标题党，就因为邀请码能获得赠送，现在论坛里到处都是这种帖子，真正反馈问题和解决问题的没有

**Comment by liuheng0315** [comment]
@854010588 也发了开始购买专业版的没有自动变成专业版的帖子，帖子里面有个管理员，发购买的邮箱给他就可以解决

**Comment by lemonskkyt** [comment]
@854010588  挺好的，说明大多数人都正常使用了，我的可以用到2028年6月11日，怀疑lantern能不能活这么久，真要能活这么久，说不定到了那个时候，账号的剩余时间够我用到退休

**Comment by liuheng0315** [comment]
@lemonskkyt 你是怎么做到2028年的，我的哥，你厉害！

**Comment by lemonskkyt** [comment]
@liuheng0315 我买的早，去年7月刚收费那会儿就买了，然后不是有一个邀请码的帖子，一开始我还没去里面回复，后面看到好多人都在那回复了，所以也留了自己的 邀请码，然后就用了一年，送了十年

**Comment by HelloXiaoxi** [comment]
草泥马之前嚷嚷不能用的狗呢？全tm老实了？

**Comment by liuheng0315** [comment]
能用
以下是我的邀请码，输入我的邀请码 HQ4DS5 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
