### ISSUE TITLE
忘了用户名 邮箱又一直收不到邮件

### ISSUE THREAD

**Issue by buakaw1989** [getlantern/forum#7140]
用户名完全忘了 邮箱又收不到邮件 买了两年专业版 换台电脑没法上了
邮箱：425087406@qq.com

**Comment by Ghostwithout** [comment]
你好， QQ邮箱是能收到验证码的，请在lantern界面左边菜单点击“授权设备使用专业版”，在里面输入购买时的邮箱，激活码就会发到你的邮箱，然后输入激活码即可。谢谢！
