### ISSUE TITLE
无法授权

### ISSUE THREAD

**Issue by zackfly** [getlantern/forum#7144]
![image](https://user-images.githubusercontent.com/5593858/33132546-e79b5954-cfd4-11e7-9d90-7f1e3c9eaab8.png)

无法给我的pc授权
账号3996643046@qq.com

目前两台设备能用，但是解绑界面只能看到一台安卓设备。
ps. 这个邮箱是我注册的时候写错了，能改成huxiaofan@outlook.com吗？不然除了授权的方式 没法再其他电脑登录

**Comment by H004** [comment]
邀请码5PHJVS  我有蓝灯专业版还可以授权一台设备，27个月 只要120  需要的加我VQ476952017

**Comment by ouhaochuan** [comment]
两个终端，已授权叫A，等待授权的叫B，先在B点击授权设备使用专业版，在弹出的页面选择已有其他专业版的设备，授权此设备，此时会看到一个动态授权码，复制这个授权码，然后到A，点击授权其他设备使用专业版，输入动态授权码即可

输入我的邀请码 YPDD3TG 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by zackfly** [comment]
这是个bug ，不然你以为我上面这个无效的码是哪里来的。

**Comment by ouhaochuan** [comment]
检查操作系统版本、软件版本，如果大家环境都一样，没理由我的可以你的不可以

**Comment by zackfly** [comment]
我和操作不一样啊老哥，我在不稳定的时候解绑了，然后就没法绑定了。
而且是后端报错懂不？

**Comment by zackfly** [comment]
我和你操作不一样啊老哥，我在不稳定的时候解绑了，然后就没法绑定了。你这说法也太绝对了

**Comment by ouhaochuan** [comment]
在设置界面里反应问题吧，这里估计没有官方技术支持看的
