### ISSUE TITLE
蓝灯太不稳定，有好用的VPN推荐吗？

### ISSUE THREAD

**Issue by wizardmly** [getlantern/forum#7145]
说实话，自从这次事件之后，蓝灯再不像从前一样开箱即用，速度爆表了。 
现在经常性的打开一会用着没多久就断线，又得重新打开重连节点，我对蓝灯已经失去了耐心了。 
大家有没有好的VPN推荐

**Comment by wii7736666** [comment]
现在VPN估计已经绝迹了，现在大多用SSR，有能力自己搭建没能力的话去买SSR服务
https://www.binbinss.club/
邀请码
NKaSLsfqRciAEg7Xd2Eu7goF4aoDzXGl
fAySCYDQ1hfnsBNM7pcEfib2AmHiLWlg
ptxlteS3Eg7FhRyDKVxvaacm5JRCnX76
PmViQrvVutWC2HV8fS3Ece80qOcVb6bK
AngTxNzqUSX2wgucNg0KllBB54hTNkat
qSsLwgljKxYZfm7GWaweCkI6wKWrYVQu
fmj6G7ab1FDASrrghAEQ4RzcDe4kfAXQ
jXV9YoiYI9Fqzshiy5n0O70bYDx1jMf6
7YL3Kut8B2JNxpD0vtmFWDq9WoaG7jj3
lCa6h8vFnHysQNaZuj5oBNEsdsRAFqA4

**Comment by wii7736666** [comment]
这个还是挺实惠的，10元一月50G流量
免费的每月10G流量，不过限速0.5Mbps

**Comment by siaimes** [comment]
https://github.com/siaimes/BTGFW 这里有教程啊！

**Comment by wii7736666** [comment]
目前还能用的邀请码
fmj6G7ab1FDASrrghAEQ4RzcDe4kfAXQ
qSsLwgljKxYZfm7GWaweCkI6wKWrYVQu
AngTxNzqUSX2wgucNg0KllBB54hTNkat
PmViQrvVutWC2HV8fS3Ece80qOcVb6bK
ptxlteS3Eg7FhRyDKVxvaacm5JRCnX76

**Comment by yzou** [comment]
https://www.plexvpn.pro?invite_code=4UT35F

**Comment by shiwanxin** [comment]
vpn太多了

**Comment by diaodada** [comment]
2018年国内可用的VPN推荐 快速稳定不掉线国外VPN
https://vpnbay.com/
知乎推荐的免费/付费VPN（安卓/iOS翻墙软件）加速器官网
VPN已经被全网封杀，整理了一批可以用的，方便大家使用，需要的朋友记得收藏分享网址
https://vpnbay.com/the-5-best-vpn-services-for-2018.html

**Comment by hallochina** [comment]
分享我测试并推荐的付费vpn
在中国，最好用的付费VPN推荐 https://vpnchina.zdhweb.com/p/vpn-china.html
你可以根据自己的偏好选择注册所有推荐的vpn，然后根据使用效果，哪个好用就付款哪个。

**Comment by chinahallo** [comment]
有呀，在china，测试并推荐好用的付费v.pn
https://vpnchina.zdhweb.com
