### ISSUE TITLE
输入我的邀请码YJ3WJJ6 来获得三个月的蓝灯专业版！最新蓝灯官方下载地址，永久有效！

### ISSUE THREAD

**Issue by handkey** [getlantern/forum#7181]
请填入邀请码    **YJ3WJJ6**   获得额外三个月期限！

[https://getlantern.org/en_US/](url)  最新蓝灯官方下载地址，永久有效！
![clipboard](https://user-images.githubusercontent.com/11023244/33203195-328500c6-d13a-11e7-9be3-50915f15bb30.png)

**Comment by dingjiheike** [comment]
你真的确定这个链接是永久有效？而不是来发邀请码的？

**Comment by liuheng0315** [comment]
输入我的邀请码 HQ4DS5 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
