### ISSUE TITLE
第一台Mac可用，第二台输入了邮件地址就不停的转圈没法输入验证码

### ISSUE THREAD

**Issue by dubisheng** [getlantern/forum#719]

**Comment by dubisheng** [comment]
第二台Windows的情况：转圈了好半天，现在重新看，不转了，但是同时输入验证码的地方也没办法输入。另一台Mac不知道是不是因为0流量，到现在都还在转。

**Comment by p3rcya** [comment]
请按照此帖上传log https://github.com/getlantern/forum/issues/358 ，方便我们调查，谢谢
