### ISSUE TITLE
声云 soundcloud音乐分享网站 无法显示图片，限制访问求解决，谢谢。

### ISSUE THREAD

**Issue by Puberty** [getlantern/forum#7210]
遇到的问题：soundcloud.com网站  提供音乐分享社区服务 简称：声云  首先进入网页无法加载专辑歌曲图片，从本网站访问音乐人主页社交媒体网址 例如: YouTube   Twitter  访问受限，如下图所示，请解决，谢谢。 

蓝灯专业版账号Email:  专业版账号 1091956036@qq.com

截图: 
![screenshot_20171121-142903](https://user-images.githubusercontent.com/33982794/33231300-a1ba88e6-d22d-11e7-974c-b842885f5fed.png)
![screenshot_20171121-142900](https://user-images.githubusercontent.com/33982794/33231306-b6b9c2b6-d22d-11e7-9906-4517e7bbf9bb.png)
![screenshot_20171121-142907](https://user-images.githubusercontent.com/33982794/33231307-ba74f51a-d22d-11e7-8cc3-609d1700fd45.png)

**Comment by PineappleLovegood** [comment]
显示蓝灯--蓝灯专业版--设置--高级设置--代理全部流量（打勾） 就可以了

**Comment by Puberty** [comment]
@
