### ISSUE TITLE
出租一个摊位

### ISSUE THREAD

**Issue by jlanke** [getlantern/forum#7228]
刚开通两年的，出租一个摊位，一个月8元

**Comment by godelescher** [comment]
可以加微信说吗？我要

**Comment by kanganxi** [comment]
搭楼出租，微信kanganxi001,目前还有29个月

**Comment by jlanke** [comment]
j8j8y1069

2017年11月27日 09:15，"godelescher" <notifications@github.com>写道：

**Comment by kanganxi** [comment]
@jlanke 兄弟加我微信吧，kanganxi001你的我根本搜不到

**Comment by jlanke** [comment]
j8j8y1069

**Comment by wjp719** [comment]
输入我的邀请码 FZLFZ9 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
