### ISSUE TITLE
现在蓝灯恢复可用了， 可以全速观看youtube1080的视频， 输入我的邀请码 YX7TRB4来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum 

### ISSUE THREAD

**Issue by lanternPromote1** [getlantern/forum#7246]
现在蓝灯恢复可用了， 可以全速观看youtube1080的视频， 输入我的邀请码 YX7TRB4来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by wjp719** [comment]
输入我的邀请码 FZLFZ9 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
