### ISSUE TITLE
Google验证码问题预计这星期解决

### ISSUE THREAD

**Issue by p3rcya** [getlantern/forum#725]
这个是Google将流量误判为垃圾流量的原因。我们后台正在解决，估计这星期解决。各位可以先用https://www.startpage.com/ 代替，其搜索结果来自Google。

**Comment by zsqp447** [comment]
嗯，虽然速度还是有点慢，但已经比原来快多了，从专业版推出以来，你们已经陆续改善了转圈圈问题，付款问题，到期时间和登陆问题，并提升了速度稳定性，看到自己喜欢的软件一点点进步也是件很开心的事情，希望你们继续努力

**Comment by kingdynasty** [comment]
继续努力！

**Comment by p3rcya** [comment]
谢谢！我们正在全力解决用户遇到的问题。

**Comment by Maggie2000** [comment]
How about Youtube? It needs 人机界面判断 from time to time.

**Comment by p3rcya** [comment]
是一个问题。

**Comment by merlinfong** [comment]
@p3rcya  建议蓝灯官方统一针对公测阶段每一个热点反馈问题开精华帖，譬如，上网速度的反馈、维权退款的诉求、承诺赠送时长但还没做到等等客户投诉和建议的精华帖

**Comment by merlinfong** [comment]
@p3rcya  建议蓝灯官方统一针对公测阶段每一个热点反馈问题开精华帖，譬如，上网速度的反馈、维权退款的诉求、承诺赠送时长但还没做到等等客户投诉和建议的精华帖

**Comment by bluewrap** [comment]
我已经快被 Google 的 403 Forbidden 搞崩溃了，本来就是重度 google 用户，虽然另外也有几种备用VPN，但是都不 如Lantern 轻量便捷，而且不影响国内网页速度和区域判定，所以第一时间买了专业版，Startpage 这个我知道，但还是不如 google 用的习惯，总是在需要查询资料的重要时刻，跳出 403。拜托尽快解决，这个真的不能忍啊。

**Comment by p3rcya** [comment]
正在全力解决！
