### ISSUE TITLE
蓝灯能不能推出一个月购买的专业版，直接买一两年感觉不放心

### ISSUE THREAD

**Issue by freakingcool** [getlantern/forum#727]
如题

**Comment by p3rcya** [comment]
现在只有一年版主要是因为 1.你蓝灯本来就可以免费使用，相当于测试 2.通过邀请朋友，可以获得1月或1季的专业版。 若购买两年版双方都获赠3个月，若购买一年版双方都获赠1个月。 3.给GFW增加负担。若提供1个月版，GFW可购买这种收集IP并封杀。而现在GFW要支持12倍的价格。代价足够高，可以保证专业版的稳定性

**Comment by kunkunwang** [comment]
楼上的理论站得住脚吗？GFW缺钱吗？？？12倍的价格就足够高了？12万倍的价格他们都出的来？

**Comment by EdwardAutumn** [comment]
楼上你貌似比开发人员和GFW人员都懂啊。

**Comment by freakingcool** [comment]
那我还是等等蓝灯3正式版吧，暂时用用shadowsocks
