### ISSUE TITLE
输入我的邀请码 YGFG27Y 来获得三个月的蓝灯专业版

### ISSUE THREAD

**Issue by aries7686** [getlantern/forum#7271]
输入我的邀请码 YGFG27Y 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by williamniels** [comment]
输入我的邀请码 Y2PWGQ3 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum#
