### ISSUE TITLE
推荐一个超级实用的SSR教程，自建VPN稳定不掉线！

### ISSUE THREAD

**Issue by ghost** [getlantern/forum#7308]
[传送门](https://github.com/sun-book/BTGFW)

**Comment by wjp719** [comment]
不错

输入我的邀请码 FZLFZ9 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by rain526** [comment]
三个月邀请码：YMGG2TY

**Comment by hallochina** [comment]
能不折腾，还是别折腾了，走付费vpn吧
https://vpnchina.zdhweb.com/p/vpn-china.html
你可以根据自己的偏好选择注册所有推荐的vpn，然后根据使用效果，哪个好用就付款哪个。
