### ISSUE TITLE
重装了系统

### ISSUE THREAD

**Issue by Kellyfeb** [getlantern/forum#7309]
电脑重装了win7后就不能自动登录专业版了，请帮助，谢谢

**Comment by wjp719** [comment]
重新授权一下

输入我的邀请码 FZLFZ9 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by Kristinxx** [comment]
点升级，在弹出的窗口里面点 已有账号 试试看？
输入我的邀请码 Y2UDW6C 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by Kellyfeb** [comment]
@angelwithout 请帮忙解决，谢谢

**Comment by Kellyfeb** [comment]
@ghost 请帮忙解决，谢谢
