### ISSUE TITLE
archlinux使用不了啊

### ISSUE THREAD

**Issue by csyezheng** [getlantern/forum#7314]
archlinx下：
用yaourt安装lantern-bin，不能正常访问google
用dpkg安装deb包，也不能正常访问。。。

windows虚拟机和另外一台ubuntu系统的都可以正常使用lantern.

用archlinux的朋友们都是怎么访问google啊？

**Comment by YuzhouZhang** [comment]
还是装ubuntu吧，我一直用fedora的，为了用lantern换ubuntu了

**Comment by csyezheng** [comment]
修改端口就能用了
