### ISSUE TITLE
如何在终端翻墙？

### ISSUE THREAD

**Issue by zzd1992** [getlantern/forum#7315]
我用的ubuntu，现在在浏览器可以翻墙。
但是在终端不能翻墙。（写了批量下载YouTube视频的代码在终端跑，一个都下不了）
是因为浏览器翻墙和终端翻墙不是一回事的缘故吗？
如果是的话，请问如何用Latern在终端翻墙？

**Comment by woodword** [comment]
代理全部流量

**Comment by fang110** [comment]
我的邀请码 Y2PHNZ9

来获得三个月的蓝灯专业版！
立即下载 https://github.com/getlantern/forum

**Comment by wjp719** [comment]
可以开全局代理

输入我的邀请码 FZLFZ9 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by Randyshu2018** [comment]
开了全局代理-也不行。。。如果可以了，麻烦告知下

**Comment by ttdchp** [comment]
用17yun 加速器。。。全平台通用
https://27yun.vip
