### ISSUE TITLE
一个设备位

### ISSUE THREAD

**Issue by 764958540** [getlantern/forum#7326]
一个位 10个月 60块 qq2936847953

**Comment by cinqs** [comment]
输入我的邀请码 YXR7WXF 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

## YXR7WXF

**Comment by chaodai2** [comment]
本人需要，请联系QQ8957683

**Comment by fang110** [comment]
我的邀请码 Y2PHNZ9

来获得三个月的蓝灯专业版！
立即下载 https://github.com/getlantern/forum
