### ISSUE TITLE
【求助】蓝灯显示已连接但是仍无法访问墙外网站。

### ISSUE THREAD

**Issue by samidareisen** [getlantern/forum#7329]
因为这个原因一直没敢买正式版，按照管理员说的方法都试过了，但还是解决不了问题……打开以后没有任何错误报告，但就是访问不了外网。

**Comment by cinqs** [comment]
你使用的什么浏览器？Chrome最好配置，你可以试试。

输入我的邀请码 YXR7WXF 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

## YXR7WXF

**Comment by samidareisen** [comment]
您好，使用的是火狐，也需要配置吗？

**Comment by jasonzhao1002** [comment]
感觉蓝灯现在问题太多 我之前买了一年现在不用了 现在换了express vpn 确实可以 油管自动720p毫无压力 不过就是有点贵。。。。80左右一个月 不过用我这个链接  http://www.expressrefer.com/refer-friend?referrer_id=14546108&utm_campaign=referrals&utm_medium=copy_link&utm_source=referral_dashboard  你可以额外多获得一个月 当然 我也多得一个月

**Comment by y976362357** [comment]
今天下午就不能到墙外去了

**Comment by fang110** [comment]
我的邀请码 Y2PHNZ9

来获得三个月的蓝灯专业版！
立即下载 https://github.com/getlantern/forum

**Comment by wjp719** [comment]
我这里可以啊

输入我的邀请码 FZLFZ9 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by cinqs** [comment]
正常情况下是不用的，你在蓝灯管理页面那里点击左上角，然后点 设置，看看里面是不是该勾选的都勾选了

**Comment by samidareisen** [comment]
一百美金一年对于学生党来说还是太贵了呀……

**Comment by samidareisen** [comment]
@jasonzhao1002 一百美金一年对于学生党来说还是太贵了呀……

**Comment by samidareisen** [comment]
@cinqs 除了开机运行以外都勾了

**Comment by samidareisen** [comment]
@y976362357 我这边从下载到现在都不行……

**Comment by cinqs** [comment]
@samidareisen 那就不知道怎么回事了... 是不是你安装了什么安全软件组织了软件自动设置代理。

你去 IE -》 Internet选项 -》 链接 -》 局域网设置 那里看看是不是设置的正确

**Comment by samidareisen** [comment]
@cinqs 也是按照帖子里面写的设置了……但就是不行_(:3」∠)_

**Comment by samidareisen** [comment]
@cinqs 而且不是全部不行，能上的去PIXIV和teitter还有tumblr，但是上不去DMM游戏……并且只能浏览器内使用，其他浏览器就打不开被墙网页。
