### ISSUE TITLE
我的邀请码 4MD7WH 来获得三个月的蓝灯专业版

### ISSUE THREAD

**Issue by fengfaan** [getlantern/forum#7330]
输入我的邀请码 4MD7WH 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by fengfaan** [comment]
可以出租，一月10块

**Comment by cinqs** [comment]
输入我的邀请码 YXR7WXF 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
## YXR7WXF

**Comment by rain526** [comment]
三个月邀请码：YZD6NU
