### ISSUE TITLE
新买的蓝灯，pc无法授权

### ISSUE THREAD

**Issue by viliv715** [getlantern/forum#7334]
12月2号买的蓝灯，账号viliv715@126.com。输入了邀请码，刚开始登陆是还剩13个月，现在已经剩余12个月了。怎么这么快就扣除了一个月。
另外，我使用手机登陆了专业版，给pc授权时，提示“错误或者无效的设备关联”，pc上安装的是github最新版本Lantern 4.4.1 (20171120.170626)，生成的动态授权码为152734，在手机上输入后，提示如上所示。

**Comment by cinqs** [comment]
你是不是输入晚了？应该这个码是有时效的吧

**Comment by wjp719** [comment]
试试用输入邮箱 让发邮箱动态码

输入我的邀请码 FZLFZ9 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by zbxsql** [comment]
被坑了么。。。不如用包月的。。。https://27yun.vip

**Comment by rain526** [comment]
三个月邀请码：YZD6NU

**Comment by huodabao** [comment]
Lantern坑爹得很，又贵，又限制设备数量，还老是连不上，我应经转战SSR了，详情点我头像看吧~

**Comment by fookuloi** [comment]
Lantern很坑的，收了钱就不管了，我给你推荐个便宜好用的，点我头像查看

**Comment by lnet** [comment]
输入我的邀请码 三个月邀请码YZD6NU

**Comment by Ghostwithout** [comment]
一个帐号最多绑定三台设备，记录显示已经绑定了三台，所以无法新增。lantern主界面到时间是约数，具体到帐号管理看准确时间。谢谢！ @viliv715
