### ISSUE TITLE
出一个多余的位子，还有十个月，60块

### ISSUE THREAD

**Issue by gntdhuf** [getlantern/forum#7346]
需要私聊QQ762186702

**Comment by wjp719** [comment]
输入我的邀请码 FZLFZ9 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by rain526** [comment]
三个月邀请码：YMGG2TY

**Comment by jinweijie0527** [comment]
这SB是骗子，不要买。他的银行账号6666669819157425，名字：王宏宇。
