### ISSUE TITLE
输入我的邀请码 YPCTTW8 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

### ISSUE THREAD

**Issue by jzbinly** [getlantern/forum#7388]
如题

**Comment by lingfengzhilian** [comment]
YPCTTW8

**Comment by KingToBest** [comment]
输入我的邀请码 9PS7XV 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by KingToBest** [comment]
输入我的邀请码 9PS7XV 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
