### ISSUE TITLE
人机验证又来了，他的朋友也来了

### ISSUE THREAD

**Issue by max210** [getlantern/forum#7415]
请在发帖前先按照蓝灯无法使用的解决办法 https://github.com/getlantern/forum/issues/1902 自行解决。自行解决问题通常只需要几十分钟。管理员调查解决问题需要几天至几周。请立即访问https://github.com/getlantern/forum/issues/1902 瞬间解决98%的问题

为了能在最快的时间内解决大家使用蓝灯遇到的问题，请各位用户严格按照发帖格式提交问题。

## 发帖格式
遇到的问题：请详细描述遇到的问题。如果描述不仔细，将无法调查

蓝灯专业版账号Email:  请提供登陆蓝灯专业版的email，免费版不提供技术支持。

应用内报告问题的时间:  请根据 https://github.com/getlantern/forum/issues/1840 在应用内上报问题，请填写专业版的email。请在帖子里注明报告的时间。

截图: 请提供有关问题的截图。 请把图片拖拽到这里。

----
邀请码在本论坛请以签名形式发布或发到其他论坛。具体见 https://github.com/getlantern/forum/issues/3773

**Comment by max210** [comment]
最近又出现了人机验证，有时候还会出现这个问题

**Comment by max210** [comment]
<img width="1241" alt="2017-12-08 16 49 55" src="https://user-images.githubusercontent.com/27328565/33758157-1f878c42-dc38-11e7-996a-2b7eac819e05.png">

**Comment by ck8918** [comment]
目前东京线路变为阿里巴巴了

**Comment by rain526** [comment]
我有段时间也要人机验证，过了不久就没了。。
三个月邀请码：YMGG2TY

**Comment by wjp719** [comment]
输入我的邀请码 FZLFZ9 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by KingToBest** [comment]
输入我的邀请码 9PS7XV 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
