### ISSUE TITLE
购买专业版时，输入邀请码，可获得多三个月的使用时间。 YP33WG5 

### ISSUE THREAD

**Issue by pangzuhui** [getlantern/forum#7452]
购买专业版时，输入此邀请码，可获得多三个月的使用时间。 YP33WG5 
蓝灯的下载地址：https://github.com/getlantern/forum   更新版本后稳定，高速！
![qq 20171210195650](https://user-images.githubusercontent.com/34409344/33804671-c95378b4-dde4-11e7-9ee8-abab69d45e65.png)

**Comment by KingToBest** [comment]
输入我的邀请码 9PS7XV 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
