### ISSUE TITLE
好友购买两年套餐后，会赠送双方3个月专业版；好友购买一年套餐后，则赠送双方1个月。YP3R75C

### ISSUE THREAD

**Issue by smoroc** [getlantern/forum#7454]
好友购买两年套餐后，会赠送双方3个月专业版；好友购买一年套餐后，则赠送双方1个月。
分享您的邀请码
YP3R75C

**Comment by KingToBest** [comment]
输入我的邀请码 9PS7XV 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
