### ISSUE TITLE
好友购买两年套餐后，会赠送双方3个月专业版；好友购买一年套餐后，则赠送双方1个月。输入我的邀请码 YP3KNVR 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

### ISSUE THREAD

**Issue by yantailee** [getlantern/forum#7457]
好友购买两年套餐后，会赠送双方3个月专业版；好友购买一年套餐后，则赠送双方1个月。输入我的邀请码 YP3KNVR 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by KingToBest** [comment]
输入我的邀请码 9PS7XV 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by 2cm-miao** [comment]
输入我的邀请码 H3Q9SJ 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
