### ISSUE TITLE
Mac终端不走lantern代理

### ISSUE THREAD

**Issue by liubin1777** [getlantern/forum#7476]
macOS Sierra 10.12.6系统，设置lantern全局代理，但是终端不走代理，ping不通www.google.com

**Comment by wilon** [comment]
终端不走代理，ping 是 ping 不通的。需你的命令自己走代理，可以使用 
```
curl -kvx 127.0.0.1:50361 http://www.google.com/
```
能返回302信息就是 Lantern 可用。
```diff
+ 输入我的邀请码 YMY7D4Q 来获得三个月的蓝灯专业版！
- 输入我的邀请码 YMY7D4Q 来获得三个月的蓝灯专业版！
```

**Comment by wjp719** [comment]
输入我的邀请码 FZLFZ9 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
