### ISSUE TITLE
寻合租

### ISSUE THREAD

**Issue by justwait6** [getlantern/forum#7517]
学生党一枚，看网页，偶尔要下载视频，不玩游戏，不刷剧，想买个2年的。
找小伙伴（有两个当然更好啦），价格均摊。
有意留言。或加q，2551372733

**Comment by LanternDistr** [comment]
@justwait6 你好，我联系你了，请加一下QQ

**Comment by 597875692** [comment]
多少钱

**Comment by LanternDistr** [comment]
@597875692 10块一个月 3288712874

**Comment by 752134268** [comment]
建议还是和朋友合租，现在骗子太多了

**Comment by Cydiaduweijian** [comment]
和朋友分享邀请码免费获赠专业版
好友购买两年套餐后，会赠送双方3个月专业版;好友购买一年套餐后，则赠送双方1个月。
分享您的邀请码
三个月邀请码：YGRTQSF

**Comment by justwait6** [comment]
已OK了，大家加油( >_<  注意别被骗 )
结贴了

**Comment by 597875692** [comment]
我有一个授权位 需要请回复




| |
tao
|
|
邮箱：litao_wy2015@163.com
|

签名由 网易邮箱大师 定制

在2017年12月16日 15:21，justwait6 写道：

Closed #7517.
