### ISSUE TITLE
lantern能代理Mac终端的流量吗？

### ISSUE THREAD

**Issue by xuwv** [getlantern/forum#756]
想在Terminal中下载东西，设置好http_proxy和https_proxy为127.0.0.1:8787，但是仍然失败。网页能访问。

**Comment by xuwv** [comment]
@p3rcya @orbancanon 帮忙啊

**Comment by zhuyingtao** [comment]
请问您是怎么解决的呢？

**Comment by xuwv** [comment]
已经弃用了

________________________________
发件人: geekzhu <notifications@github.com>
发送时间: 2017年8月28日 13:27:52
收件人: getlantern/forum
抄送: chasel; State change
主题: Re: [getlantern/forum] lantern能代理Mac终端的流量吗？ (#756)


请问您是怎么解决的呢？

―

**Comment by xuwv** [comment]
已经弃用了
