### ISSUE TITLE
真实有效！！！！输入我的邀请码 HVY2G7 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

### ISSUE THREAD

**Issue by 597875692** [getlantern/forum#7609]
真实有效，输入立即获得额外三个月专业版使用时长！！！

**Comment by xx0508** [comment]
在哪里输入

**Comment by 597875692** [comment]
购买专业版 下方点击有代理方邀请码 输入购买即可




| |
tao
|
|
邮箱：litao_wy2015@163.com
|

签名由 网易邮箱大师 定制

在2017年12月20日 21:43，xx0508 写道：

在哪里输入
