### ISSUE TITLE
无法登陆的问题

### ISSUE THREAD

**Issue by steve-liuxu** [getlantern/forum#761]
我使用的是 win10系统，chrome浏览器。买了一年专业版，但是没法登陆，现在显示流量都快使用完了，希望开发组能给出一个解决办法。 
![qq 20160722041855](https://cloud.githubusercontent.com/assets/12738076/17037490/c8434be4-4fc3-11e6-8e5a-dd5427b8f5a1.jpg)
![qq 20160722041912](https://cloud.githubusercontent.com/assets/12738076/17037491/c845efb6-4fc3-11e6-9263-6dec35824b38.jpg)

**Comment by p3rcya** [comment]
没发登陆是卡在验证码界面么？ 请按照此帖上传log https://github.com/getlantern/forum/issues/358 ，方便我们调查，谢谢

**Comment by steve-liuxu** [comment]
不是的 （虽然有时候会出现卡在验证码界面的情况）是登陆账号之后，再次打开蓝灯的页面，仍然显示未登录
以下是日志文件
[lantern.txt](https://github.com/getlantern/forum/files/376911/lantern.txt)

**Comment by p3rcya** [comment]
帐号管理界面截图上传下，谢谢

**Comment by steve-liuxu** [comment]
![qq 20160722043814](https://cloud.githubusercontent.com/assets/12738076/17038067/7509784c-4fc6-11e6-9087-674de69be24a.jpg)

**Comment by steve-liuxu** [comment]
再次打开，仍然显示未登录
![image](https://cloud.githubusercontent.com/assets/12738076/17038088/8896b4f6-4fc6-11e6-9a31-26f2325e55e5.png)

**Comment by p3rcya** [comment]
正在调查

**Comment by p3rcya** [comment]
请问你是什么时候购买Pro的？

**Comment by steve-liuxu** [comment]
07-17 上周日

**Comment by p3rcya** [comment]
@steve-liuxu 请上传下支付宝帐号和支付记录，谢谢

**Comment by steve-liuxu** [comment]
![screenshot_2016-07-24-02-40-57_com eg android ali](https://cloud.githubusercontent.com/assets/12738076/17079614/2cbe44ea-5148-11e6-8c39-7f1402c43a26.png)

**Comment by steve-liuxu** [comment]
![screenshot_2016-07-24-02-42-53_com eg android ali](https://cloud.githubusercontent.com/assets/12738076/17079623/64836540-5148-11e6-9666-a748661394b4.png)

**Comment by p3rcya** [comment]
好，正在添加。

**Comment by p3rcya** [comment]
已经添加

**Comment by steve-liuxu** [comment]
有劳了
