### ISSUE TITLE
全局代理后为什么无法访问github?

### ISSUE THREAD

**Issue by cnbattle** [getlantern/forum#7620]
是github的原因还是别的原因?

自己也搭建了一个,链接后,也是无法访问github ,在服务器上github 能ping通 

别问为什么会有这样情景, 有兴趣的去看看golang的 dep ensure

![image](https://user-images.githubusercontent.com/10772658/34237965-5256c186-e63a-11e7-9633-58bb863f0a06.png)

**Comment by weifangbird** [comment]
输入我的邀请码 Y25FVGW 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
