### ISSUE TITLE
输入我的邀请码 JRD7SR 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

### ISSUE THREAD

**Issue by leyunhua** [getlantern/forum#7629]
输入我的邀请码 JRD7SR 来获得三个月的蓝灯专业版！立
![unnamed qq screenshot20171221201910](https://user-images.githubusercontent.com/31621162/34255566-480f4750-e68c-11e7-9991-12c21f232c32.png)
即下载 https://github.com/getlantern/forum

**Comment by hyxjfl01** [comment]
![301329076](https://user-images.githubusercontent.com/32521327/34269631-1a8e0ad0-e6c0-11e7-8888-90b89887e01a.jpg)
