### ISSUE TITLE
输入我的邀请码 YGHVRD3 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

### ISSUE THREAD

**Issue by Emily004** [getlantern/forum#7635]
一起来用VPN啊～～～～

**Comment by yzthr** [comment]
输入我的邀请码 YMYW9CT 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by 597875692** [comment]
真实有效！！
输入我的邀请码 HVY2G7 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/
