### ISSUE TITLE
ios不远了！邀请码 HVY2G7 三个月专业版！立即下载 https://github.com/getlantern/forum

### ISSUE THREAD

**Issue by 597875692** [getlantern/forum#7651]
ios版不远了，耐心等候！
真实有效！
输入我的邀请码 HVY2G7 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by lushan9521** [comment]
就算出来了估计也是美区的，中国区不会上架，而且我们很难注册美区账号

**Comment by 597875692** [comment]
不是也可以不通过app商店安装吗




| |
tao
|
|
邮箱：litao_wy2015@163.com
|

签名由 网易邮箱大师 定制

在2017年12月23日 11:20，鲁山 写道：

就算出来了估计也是美区的，中国区不会上架，而且我们很难注册美区账号
