### ISSUE TITLE
真实有效邀请码！！！ HVY2G7 获得三个月专业版！立即下载 https://github.com/getlantern/forum

### ISSUE THREAD

**Issue by 597875692** [getlantern/forum#7665]
购买专业版页下方点击输入代理商邀请码立即获赠三个月额外使用时长！

输入我的邀请码 HVY2G7 来获得三个月的蓝灯专业版！
立即下载 https://github.com/getlantern/forum

**Comment by orbancanon** [comment]
@597875692  请不要发只有邀请码没有其他内容的帖子，否则将被封号 https://github.com/getlantern/forum/issues/7094
