### ISSUE TITLE
我今天购买了LANTERN，注册错了邮箱。没法验证捆绑，急

### ISSUE THREAD

**Issue by shawnsong11** [getlantern/forum#767]
麻烦管理员帮助后台处理一下。

今天刚购买的 正确邮箱应该是shawn_song11@163.com， 可以被我注册成了shawn_song@163.com 

麻烦帮忙

**Comment by p3rcya** [comment]
我们会上线邮箱修改功能。请不要退出

**Comment by shawnsong11** [comment]
亲，关键我现在购买了不能捆绑，用不了。。。

**Comment by shawnsong11** [comment]
能后台先给我处理一下吧，把注册的邮箱由 shawn_song@163.com 改成shawn_song11@163.com 

我购买了1年的专业版，已经付款，但是由于邮箱错误，无法验证捆绑，用不了

**Comment by shawnsong11** [comment]
shawn_song@163.com  不是我的邮箱，我收不到验证码。。。。

**Comment by p3rcya** [comment]
我们以后能支持直接修改邮箱的，不需要验证码。

**Comment by shawnsong11** [comment]
亲，那我付过专业板的钱了，现在怎么处理？ 我需要使用

**Comment by shawnsong11** [comment]
我现在需要登录专业版。。。希望你们能解决一下。 毕竟蓝灯口碑还是不错的，我也是朋友推荐，今天刚刚购买的你们一年的订阅

**Comment by p3rcya** [comment]
好，我们后台解决下

**Comment by p3rcya** [comment]
已经修改
