### ISSUE TITLE
ios版本即将上线！输入邀请码 HVY2G7 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

### ISSUE THREAD

**Issue by 597875692** [getlantern/forum#7672]
长期代理真实有效！购买输入代理商邀请码立即获赠3个月额外使用时长！
输入我的邀请码 HVY2G7 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by zwtall** [comment]
输入我的邀请码 K3BHBS 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by AkiraTyou** [comment]
ios版本？没有的。根本不可能上Appstore!

**Comment by 597875692** [comment]
等官方消息吧




| |
tao
|
|
邮箱：litao_wy2015@163.com
|

签名由 网易邮箱大师 定制

在2017年12月25日 16:54，AkiraTyou 写道：

ios版本？没有的。根本不可能上Appstore!
