### ISSUE TITLE
互相帮助，这是我的邀请码： YXHR4K3。谢谢合作！

### ISSUE THREAD

**Issue by shisanlanlan** [getlantern/forum#7689]
输入我的邀请码 YXHR4K3 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by orbancanon** [comment]
@shisanlanlan  请不要发只有邀请码没有其他内容的帖子，否则将被封号 https://github.com/getlantern/forum/issues/7094
