### ISSUE TITLE
chrome不能用，已按照自行解决办法试过，望解决！

### ISSUE THREAD

**Issue by zwy1121** [getlantern/forum#7700]
遇到的问题：win10 64位，校内VPN客户端连接网络。网络代理已按lantern设置，未安装迅雷，chrome插件全关。IE和Edge能翻，最新版chrome和firefox57不能翻（firefox已设置手动代理，ip和端口填好）。自行解决的帖子办法均试过，无效。
蓝灯专业版账户Email：sevenwalk@163.com
应用内报告问题的时间：2017年12月25日23：30-24：00

**Comment by zwy1121** [comment]
用SwitchyOmega已自行解决

**Comment by orbancanon** [comment]
@zwy1121 那我关帖了。这种情况可以在地址栏打开 chrome://net-internals#proxy 验证一下代理是否生效。

**Comment by zwy1121** [comment]
代理已生效，谢谢！
