### ISSUE TITLE
请问诸位人兄，关于就是，如果三台设备都授权了，如果其中一台不用了，要授权另一台是要先退出吗？还有，你们这些租给别人的，万一别人直接把你们设备全部退出，然后占用三个设备，这样还有办法拿回自己的设备吗？一直不解的问题。如果发生这种清况，蓝灯售后会帮忙解决吗？一直想问的。😂😂

### ISSUE THREAD

**Issue by kevin08gao** [getlantern/forum#7717]
请在发帖前先按照蓝灯无法使用的解决办法 https://github.com/getlantern/forum/issues/1902 自行解决。自行解决问题通常只需要几十分钟。管理员调查解决问题需要几天至几周。请立即访问https://github.com/getlantern/forum/issues/1902 瞬间解决98%的问题

为了能在最快的时间内解决大家使用蓝灯遇到的问题，请各位用户严格按照发帖格式提交问题。

## 发帖格式
遇到的问题：请详细描述遇到的问题。如果描述不仔细，将无法调查

蓝灯专业版账号Email:  请提供登陆蓝灯专业版的email，免费版不提供技术支持。

应用内报告问题的时间:  请根据 https://github.com/getlantern/forum/issues/1840 在应用内上报问题，请填写专业版的email。请在帖子里注明报告的时间。

截图: 请提供有关问题的截图。 请把图片拖拽到这里。

----
邀请码在本论坛请以签名形式发布或发到其他论坛。具体见 https://github.com/getlantern/forum/issues/3773

**Comment by zwtall** [comment]
有邮箱的那个，算主号，可以控制其他设备绑定与否。如果解绑的非主号，直接在主号控制台操作，对从号解绑。让后再授权其他设备。如果主号对应设备要解绑，退出后，根据邮箱验证码从新登陆即可。

**Comment by kevin08gao** [comment]
@zwtall 不是的，我感觉三个都有邮箱，三个都是主号，三个都能直接退出和登陆。

**Comment by Drline** [comment]
只有主号才需要登录，副号直接输入验证码就行了

**Comment by philipz12** [comment]
可以互相解绑或者绑定

我的邀请码 X49M25 ，常年有效！

**Comment by ouhaochuan** [comment]
实践是检验真理的。。。

输入我的邀请码 YPDD3TG 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
