### ISSUE TITLE
golang.org 许多地方无法访问，go get 命令经常访问这个

### ISSUE THREAD

**Issue by modifMX** [getlantern/forum#7732]
请在发帖前先按照蓝灯无法使用的解决办法 https://github.com/getlantern/forum/issues/1902 自行解决。自行解决问题通常只需要几十分钟。管理员调查解决问题需要几天至几周。请立即访问https://github.com/getlantern/forum/issues/1902 瞬间解决98%的问题

为了能在最快的时间内解决大家使用蓝灯遇到的问题，请各位用户严格按照发帖格式提交问题。

## 发帖格式
遇到的问题：请详细描述遇到的问题。如果描述不仔细，将无法调查

蓝灯专业版账号Email:  请提供登陆蓝灯专业版的email，免费版不提供技术支持。

应用内报告问题的时间:  请根据 https://github.com/getlantern/forum/issues/1840 在应用内上报问题，请填写专业版的email。请在帖子里注明报告的时间。

截图: 请提供有关问题的截图。 请把图片拖拽到这里。

----
邀请码在本论坛请以签名形式发布或发到其他论坛。具体见 https://github.com/getlantern/forum/issues/3773

package golang.org/x/net/html: unrecognized import path "golang.org/x/net/html" (https fetch: Get https://golang.org/x/net/html?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package golang.org/x/oauth2: unrecognized import path "golang.org/x/oauth2" (https fetch: Get https://golang.org/x/oauth2?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package golang.org/x/oauth2/facebook: unrecognized import path "golang.org/x/oauth2/facebook" (https fetch: Get https://golang.org/x/oauth2/facebook?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package golang.org/x/oauth2/google: unrecognized import path "golang.org/x/oauth2/google" (https fetch: Get https://golang.org/x/oauth2/google?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package golang.org/x/crypto/bcrypt: unrecognized import path "golang.org/x/crypto/bcrypt" (https fetch: Get https://golang.org/x/crypto/bcrypt?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package golang.org/x/image/bmp: unrecognized import path "golang.org/x/image/bmp" (https fetch: Get https://golang.org/x/image/bmp?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package golang.org/x/image/tiff: unrecognized import path "golang.org/x/image/tiff" (https fetch: Get https://golang.org/x/image/tiff?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package golang.org/x/net/context: unrecognized import path "golang.org/x/net/context" (https fetch: Get https://golang.org/x/net/context?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

**Comment by orbancanon** [comment]
1. 发帖请按要求的格式
1. 请手工设置git需要的代理（Lantern左侧菜单->设置->高级下可以看到）。怎么设请自行Google。
