### ISSUE TITLE
不知道这个视频对开发者们有没有用

### ISSUE THREAD

**Issue by GD-HBX** [getlantern/forum#775]
https://www.youtube.com/watch?v=NgYdmRR7JtY

**Comment by zsqp447** [comment]
这些东西我这种菜鸟都知道牛X闪闪的开发人员会不知道，再说视频里那些只是管中窥豹，除了方校长没人能完全理解GFW

**Comment by p3rcya** [comment]
@GD-HBX 哈哈，这个我帮他一起搞的。

**Comment by GD-HBX** [comment]
：）
