### ISSUE TITLE
找人合租。可看4k视频，BBR加速，美国节点。

### ISSUE THREAD

**Issue by Lewis20170** [getlantern/forum#7755]
找人合租。可看4k视频，BBR加速，美国节点。

![youtube](https://user-images.githubusercontent.com/34594600/34450921-05dd1268-ed53-11e7-804c-f06d00eda461.png)

**Comment by Lewis20170** [comment]
![test](https://user-images.githubusercontent.com/34594600/34450954-bd7e25c4-ed53-11e7-9c39-f6ddc6d815b2.png)

**Comment by Lewis20170** [comment]
![test2](https://user-images.githubusercontent.com/34594600/34451033-e747a1b8-ed54-11e7-99fd-1ff2d169c3ca.png)

**Comment by Lewis20170** [comment]
需要的留下QQ

**Comment by gsdkasdk** [comment]
不要再用垃圾lantern了， 买了年费就不管了，肠子都悔青了!
推荐一个自用的shadowsocks SS/SSR服务商，一直在用，速度杠杠的~|价|格|优|惠|低至5元/50G/月。在最近跑路关停潮日益严重的日子,依旧坚挺~已屏蔽国内ip，需翻墙访问～
http://cp.dawangidc.com/aff.php?aff=523
购买服务后请看配置教程
https://fqjsjl.tumblr.com

**Comment by Lewis20170** [comment]
人满了。。
