### ISSUE TITLE
请问抽风啥时会好？

### ISSUE THREAD

**Issue by yzs0324** [getlantern/forum#777]
表示我这里从昨天开始就用不了lantern了，提示是「Still unable to dial tcp://sis001.us:80 after 3 attempts」

**Comment by p3rcya** [comment]
请问是专业版还是免费版？ 请按照此帖上传log https://github.com/getlantern/forum/issues/358 ，方便我们调查，谢谢

**Comment by yzs0324** [comment]
@p3rcya 帖子四天前就被锁了不是嘛(手动哭脸

**Comment by yzs0324** [comment]
http://pan.baidu.com/s/1dFz9Bvb

为什么我上传不了ZIP啊
