### ISSUE TITLE
警惕！！蓝灯已成为刑侦工具

### ISSUE THREAD

**Issue by ghost** [getlantern/forum#7790]
### &#x56e0;&#x6b64;&#x5404;&#x4f4d;&#x73b0;&#x5728;&#x5343;&#x4e07;&#x4e0d;&#x8981;&#x6025;&#x7740;&#x4e70;&#x4e13;&#x4e1a;&#x7248;&#xff01;&#xff01;&#x5982;&#x679c;&#x4f60;&#x7528;&#x84dd;&#x706f;&#x4e0a;&#x7ffb;&#x5899;&#x7f51;&#x7ad9;&#xff0c;&#x8bf4;&#x4e0d;&#x5b9a;&#x54ea;&#x5929;&#x4f60;&#x5c31;&#x88ab;&#x67e5;&#x6c34;&#x8868;&#x4e86;&#xff01;&#xff01;

**Comment by abblee** [comment]
谢谢告知，我翻墙主要是看看外面的世界，而不是说我们自己的家园。

输入我的邀请码 YPN47RR 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by wddfzfx** [comment]
确实，lantern用的是阿里云服务器，有后门，特别不安全，所有的浏览记录都会被保存！
推荐一个自用的shadowsocks SS/SSR服务商，一直在用，速度杠杠的~|价|格|优|惠|低至5元/50G/月。在最近跑路关停潮日益严重的日子,依旧坚挺~已屏蔽国内ip，需翻墙访问～
http://cp.dawangidc.com/aff.php?aff=523
购买服务后请看配置教程
https://fqjsjl.tumblr.com

**Comment by wucwd9k5** [comment]
[是啊](https://blog.siaimes.me/2017/11/09/p6/)，想想十九大期间蓝灯崩掉的那一个月吧！！！
[ssr](https://blog.siaimes.me/2017/11/09/p6/)就没这个烦恼了，各种[协议](https://blog.siaimes.me/2017/11/09/p6/)，各种[混淆](https://blog.siaimes.me/2017/11/09/p6/)。哪有那么牛逼的墙能ban住[ssr](https://blog.siaimes.me/2017/11/09/p6/)的！

**Comment by sfshine** [comment]
工作需要而已,  如果真是这样那反而更好了, 大家都透明了, 做什么颠覆政权的事情政府都知道了. 也不会禁用我们这些工作需要的人了. , 倒是你, 别有用心,   得小心了.

**Comment by china-richway2** [comment]
想确认一下@ghost是该论坛的管理员吗？这些言论与蓝灯的立场不太一致，希望其它管理员@angel_without确认一下是否被盗号还是官方公告。
另外，蓝灯为什么会带出用户的ip地址？无论是透明代理还是一般的vpn，只要进行了足够强的加密，理论上GFW只会看到用户在访问蓝灯，网站只能看到是某个蓝灯用户在进行访问，要把用户和网站关联起来，唯一的方法是在蓝灯服务器上设置后门，例如加入X-Forwarded-For头。但蓝灯一直以来对用户的隐私也有一定的保证，不应该故意加入这样的后门。

**Comment by china-richway2** [comment]
@angelwithout

**Comment by zsqp447** [comment]
哈哈，楼主我知道你的身份了，你是XX部的对不

**Comment by wiinduuasd** [comment]
推荐一个自用的shadowsocks SS/SSR服务商，一直在用，速度杠杠的~|价|格|优|惠|低至5元/50G/月。在最近跑路关停潮日益严重的日子,依旧坚挺~已屏蔽国内ip，需翻墙访问～ http://cp.dawangidc.com/aff.php?aff=523 购买服务后请看配置教程 https://fqjsjl.tumblr.com

**Comment by dannymou** [comment]
我想大多数人翻墙只是为了学习或者工作需要，透明化我也感觉没什么不好

**Comment by philipz12** [comment]
就是为了用Google才翻，工作需要，国家为了阻止那部分有企图人，把我们这些良民也阻止了

我的邀请码 X49M25, 常年有效。
