### ISSUE TITLE
输入我的邀请码 5QJ3CJ 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

### ISSUE THREAD

**Issue by renxinqiang** [getlantern/forum#7896]
输入我的邀请码 5QJ3CJ 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by xusandao375** [comment]
你的蓝灯专业版怎么登陆的，我的怎么找不到登陆的地方。。。

**Comment by Janlor** [comment]
借楼，输入我的邀请码 5XV5VN 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by renxinqiang** [comment]
@xusandao375 
![image](https://user-images.githubusercontent.com/9512353/34866374-55602dca-f7b7-11e7-956e-cc0c5d6c602e.png)

点开菜单

![image](https://user-images.githubusercontent.com/9512353/34866415-726836ce-f7b7-11e7-9b5d-3a9aacf8cc47.png)

里面会有相关操作

**Comment by xusandao375** [comment]
我“显示蓝灯”点了完全没反应。。。
