### ISSUE TITLE
Google 验证码问题已经修复

### ISSUE THREAD

**Issue by p3rcya** [getlantern/forum#791]
访问Google等出现验证码的频率应该大幅降低了，但是偶尔出现是正常的，输入后就能继续访问了。

如果各位还是频繁遇到验证码，请在本帖上传截图并请按照此帖上传log https://github.com/getlantern/forum/issues/358 ，方便我们调查，谢谢 。

**Comment by AvernusKaInferno** [comment]
申请将账号邮箱770356117@qq.com改为avernuskainferno@gmail.com，很急，现在用不了

**Comment by ganpeng** [comment]
我升级之后邮箱收不到验证码，能换个邮箱吗，还是怎么办？这是注册的邮箱464860687@qq.com

**Comment by xieyingli** [comment]
mac版不响应的问题求修复啊啊啊

**Comment by unever** [comment]
依旧频繁遇到验证码问题，附上log。
[lantern - 副本.txt](https://github.com/getlantern/forum/files/379905/lantern.-.txt)

**Comment by orbancanon** [comment]
@ganpeng @AvernusKaInferno 前几天被国内的一些邮箱屏蔽了。现在应该可以收到验证码了，只是可能会延迟一段时间（还是这些邮箱捣乱）。

@unever 从日志看，虽然我们的修复措施已经生效了，但如果Lantern服务器有多个用户同时访问Google，Google还是偶尔认为可疑。这个并没有太好的办法，但如果有新的缓解办法，我们会尽快用上的！

**Comment by lxq959** [comment]
我的邮箱 lxq959@zjip.com 无法收到验证码

**Comment by unever** [comment]
@orbancanon Lantern服务器多个用户访问Google应该算是常态吧，其实有部分用户翻墙就是为了访问Google，所以这个问题希望早日能彻底修复。但，这两天使用的情况来看，几乎遇不到了，除了反馈问题时比较频繁的遇到，后来基本没遇到，希望是修复了。开发组辛苦，谢谢回复。
