### ISSUE TITLE
买了专业版，现在的体验太差，申请退款！请问怎么申请？

### ISSUE THREAD

**Issue by wangshen27** [getlantern/forum#793]
现在的专业版的速度实在太慢了，无法正常使用，问题还一大堆，用着太闹心了！我要申请退款，请告诉我申请退款该怎么做？

**Comment by huchiwen** [comment]
我也想退款~

**Comment by ivanbirth851230** [comment]
我想我们需要给予lantern团队时间不是吗？ 毕竟现在是公测阶段，同时他们也没闲着，眼下最主要的就是速度稳定问题，我们耐心等待就好。毕竟我们购买lantern是之前有过好的体验，信任他们才会选择，既然他们之前能做好，那没有理由现在或者未来更糟不是吗？

**Comment by huchiwen** [comment]
买了一个星期 一直都是断断续续的 连不上 好烦人啊~ 解决速度太慢了吧

**Comment by zsqp447** [comment]
不能退的哦

**Comment by wangshen27** [comment]
@ivanbirth851230 我认为一个软件在公测阶段就不该有收费版本！要公测专业版完全可以采取邀请制，开放给一部分用户使用；再者现在蓝灯的专业版收费可真不低啊，掏这么多钱来当小白鼠可真让人憋屈；还有，既然现在处于公测阶段，那用户在购买专业版的时候就应该提醒用户专业版现处于公测阶段，而不是等用户购买了，用着不爽了来反馈了才站出来说现在是在公测阶段……

**Comment by p3rcya** [comment]
公测阶段购买专业版的用户会有一个月额外时间赠送，请大家稍安勿躁

**Comment by huchiwen** [comment]
希望你们开发团队早点解决。
