### ISSUE TITLE
刚买的专业版，邮箱一直接收不到登陆验证码。

### ISSUE THREAD

**Issue by rainbowcher3** [getlantern/forum#7935]
付款后收到了付款通知的邮件后，在mac网页版登陆账号等待发送邮件，已经过了10个小时，还是没有收到登陆码的邮件。邮箱为：2045909002@qq.com

**Comment by Ghostwithout** [comment]
购买后会自动变成专业版，点开lantern界面左上角，可以看到lantern专业版。谢谢！

**Comment by rainbowcher3** [comment]
之前是用朋友授权的账号。现在切换账号购买不了，所以让美国的朋友帮忙买的账号。如今页面还是之前已经过期的专业版，输入自己买的账号一直没收到邮件登陆码。（我是Mac）

**Comment by philipz12** [comment]
卸载干净重装
------------
邀请码 X49M25，常年有效。

**Comment by rainbowcher3** [comment]
用google chrome登录解决了，收到邮件
