### ISSUE TITLE
好消息，搬瓦工补货19.9美金套餐 （购买后网页面板有一键搭建SS功能）6分钟搞定

### ISSUE THREAD

**Issue by ghost** [getlantern/forum#7964]
经过长时间断货，搬瓦工昨天半夜补货了19.9美金的VPS套餐，大家只要进入以下链接注册，然后去我的服务-控制面板-一键生成ss参数，就可以使用了。

# [Bandwagonhost官网](https://bwh1.net/aff.php?aff=24912)

*支持支付宝付款！付款时填入 BWH1ZBPVK  优惠码 可以优惠6%
*19.9美金的一般个人使用速度不错，如果多人使用，可以考虑29.9美金的CN2加速线路。

欲购从速，我估计近几天又会断货，中国人民太热情了。

如果英文不好的，可以百度查看各种安装教程，海了去了。

[**视频教程**](https://www.iwander6.com/2018/01/18/%E6%90%AC%E7%93%A6%E5%B7%A5bandwagonhost%E8%B4%AD%E4%B9%B0%E5%8F%8A%E4%B8%80%E9%94%AE%E5%AE%89%E8%A3%85%E6%95%99%E7%A8%8B/)

**Comment by kuseqingchun** [comment]
标记下，搬瓦工，确实不错价格便宜。不是一般的便宜

**Comment by Heymanthere** [comment]
@kuseqingchun 我等这个补货等了好几个月了，终于补齐了。

**Comment by humu222w** [comment]
搬瓦工国内挺火的新手村级别，很多人第一台VPS要么是搬瓦工要么是Vultr要么是Linode

**Comment by Heymanthere** [comment]
@humu222w 嗯，搬瓦工支持一键安装，而且支持支付宝，所以入门很容易。

**Comment by Heymanthere** [comment]
注意：付款时候尽量不要在代理情况下，可能出现厂家判定购买过程有问题。

**Comment by pheonixjj** [comment]
请问，这个只能是LINUX系统才能搭建vpn吗？ win10可以嘛？

**Comment by Holeihai** [comment]
@pheonixjj windows可以的，都网页端直接生成的。看看视频就知道了
如果想自己定制端口和密码，那就百度看别的教程，非常多。

**Comment by evanoxu** [comment]
不要太火了啊。。最近都被盯上了吧？延迟变得巨慢。
