### ISSUE TITLE
续期专业版，钱款已扣，并未充值成功

### ISSUE THREAD

**Issue by MrJ2puddin** [getlantern/forum#7980]
遇到的问题：续期专业版，钱款已扣，并未充值成功
蓝灯专业版账号Email:  jiazhen122@gmail.com

截图: 
<img width="404" alt="2018-01-19 1 12 04" src="https://user-images.githubusercontent.com/29668995/35135794-6f726292-fd1a-11e7-973c-935e4d5c449c.png">

**Comment by MrJ2puddin** [comment]
<img width="1550" alt="2018-01-19 1 13 52" src="https://user-images.githubusercontent.com/29668995/35135837-b3fc169c-fd1a-11e7-9772-24e690082429.png">

**Comment by Ghostwithout** [comment]
你好，重启lantern即可，已经更新到2020年4月了，谢谢。 @MrJ2puddin
