### ISSUE TITLE
程序猿有需要学习LINUX的可以考虑买个搬瓦工19.9/年的 有英文基础或者动手能力的也能搞定SS

### ISSUE THREAD

**Issue by Landengchuzufang** [getlantern/forum#8002]
作为程序猿，玩个LINUX的话现在可以考虑买搬瓦工的19.9年套餐，配置如下：

SSD: 10 GB RAID-10
RAM: 512 MB
CPU: 1x Intel Xeon
Transfer: 500 GB/mo
Link speed: 1 Gigabit

个人使用练习LINUX Shell 或者 自己搭载个SS科学上网还是蛮合算的，搬瓦工支持支付宝了，同时ss一键脚本也内置在后台。为了吸引中国客户，还在国内做了镜像网站： # **[镜像官网链接](https://bwh1.net/aff.php?aff=24912)**
这样方便了大家购买，优惠码还能打94折。

傻瓜式教程网上也很多：
0. [注册教程](http://hostingset.com/)
1. [一键安装教程](https://www.iqiqi.org/banwagong-vps-setup-shadowsocks/)
2. [自定义安装教程](http://blog.anning.tv/14.html)： 需要下载SSH链接软件比如xshell或者securecrt等

**Comment by orbancanon** [comment]
该文章链接到伪造的搬瓦工网站，已清除。请勿再用马甲推广该网站，否则将采取进一步措施。
