### ISSUE TITLE
搬瓦工VPS年付低至19美元，分享自建科学上网教程

### ISSUE THREAD

**Issue by Landengchuzufang** [getlantern/forum#8006]
# **[国内镜像官网链接](https://bwh1.net/aff.php?aff=24912)**
*以上网址证明是搬瓦工认证镜像，无需翻墙。
教程详细请参考楼下一个链接即可，写得很详细。
链接直达： [点我](https://www.tbreak.top/kda/56/)

**Comment by haochiburujiaozi** [comment]
谢谢分享，亲测可用。

**Comment by tibreak** [comment]
https://www.tbreak.top/kda/56/
