### ISSUE TITLE
九张图教你如何科学上网！！！

### ISSUE THREAD

**Issue by MCaaacc** [getlantern/forum#8040]
优惠码         BWH1ZBPVK（6.00%）
[**点击直达官网**](https://bwh1.net/aff.php?aff=26275)
[**点击进入教程**](https://pan.baidu.com/s/1mj7DdVy)

**Comment by orbancanon** [comment]
该文章链接到伪造的搬瓦工网站，已清除。请勿再用马甲推广该网站，否则将采取进一步措施。
