### ISSUE TITLE
安卓,IOS, PC,搭建穿墙服务的正确姿势

### ISSUE THREAD

**Issue by lanterner** [getlantern/forum#8042]
IOS客户端建议下载postern或wingy（无需注册美区ID）,其他客户端在教程内有地址，首先，建议买一个最近非常优惠的$19.9搬瓦工虚拟服务器，自己搭建的肯定比公众使用的快，并且没有设备数限制，而且教程也不难。
# [ 搬瓦工官网链接 ](https://www.bwh1.net/aff.php?aff=22647)

# [图文教程链接](https://www.tbreak.top/kda/56/)

**Comment by orbancanon** [comment]
该文章链接到伪造的搬瓦工网站，已清除。请勿再用马甲推广该网站，否则将采取进一步措施。
