### ISSUE TITLE
美区AppleID注册教程

### ISSUE THREAD

**Issue by AppleIDReg** [getlantern/forum#8043]
现行网上的注册教程都失败了，原因是苹果加大了判断程式，需要挂代理的同时设置好自己的地理位置和时区，这样才可能躲过判断，在付款信息里出现【无】这个选项。
详细教程分享请看：
## 
**[美区ID注册链接](https://www.iwander6.com/%E7%BE%8E%E5%8C%BAapple-id%E7%94%B3%E8%AF%B7%E6%95%99%E7%A8%8B/)**

**Comment by orbancanon** [comment]
该文章链接到伪造的搬瓦工网站，已清除。请勿再用马甲推广该网站，否则将采取进一步措施。
