### ISSUE TITLE
输入我的邀请码 YGWVM63 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

### ISSUE THREAD

**Issue by tangshiyang** [getlantern/forum#8063]
输入我的邀请码 YGWVM63 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by wxp11** [comment]
![image](https://user-images.githubusercontent.com/16205085/35332648-9ee75aac-0146-11e8-9ebd-9307c98a992f.png)
# 输入我的邀请码 4UMKCB 来获得三个月的蓝灯专业版！永久有效！:red_circle:[立即下载](https://github.com/getlantern/forum/issues/833):red_circle:

## 另分享一个youtube视频下载神器，需要的自取，不定期更新。播放页直接显示下载按钮，一键下载。链接：https://pan.baidu.com/s/1mjAvbsO 密码：6din 谁用谁知道。如连接失效请留言。
### :red_circle:[蓝灯邀请码汇总-3](https://github.com/getlantern/forum/issues/7866):red_circle:
