### ISSUE TITLE
输入我的邀请码 YYXUZRV 来获得三个月的蓝灯专业版！（注意：买2年才送三月，买1年只送1月）

### ISSUE THREAD

**Issue by fateblessme** [getlantern/forum#8077]
输入我的邀请码 YYXUZRV 来获得三个月的蓝灯专业版！
立即下载 https://github.com/getlantern/forum
（注意：买2年才送三月，买1年只送1月）

**Comment by lanlongning** [comment]
我的好记，用我的，长期有效剩余40个月
输入我的邀请码#  J9B879 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
