### ISSUE TITLE
Win 10 Pro Insider Preview下蓝灯无法启动，闪退

### ISSUE THREAD

**Issue by huercha** [getlantern/forum#8191]
操作系统版本：Win 10 Pro Insider Preview Build 17083.rs_prerelease.180119-1645
蓝灯版本：Win 4.4.2
现象：蓝灯无法启动，闪退，请见附件Log
[lantern.log](https://github.com/getlantern/forum/files/1689262/lantern.log)

**Comment by orbancanon** [comment]
@huercha 你修改了Lantern的默认启动参数，然后这个参数无效了 。
```
listen tcp 192.168.1.105:8787: bind: The requested address is not valid in its context.
```
请到C:\Users\Administrator\AppData\Roaming\Lantern\settings.yaml 里把addr那一项修改或者删除。
