### ISSUE TITLE
请帮忙重新绑定账号 邮箱:354037968@qq.com

### ISSUE THREAD

**Issue by yb19890724** [getlantern/forum#8194]
![35567079-adf21eee-05fe-11e8-92b8-e76efdaf651e](https://user-images.githubusercontent.com/21005459/35739639-2f9dc77a-086d-11e8-8995-ecdf9bc3c271.png)

**Comment by Ghostwithout** [comment]
请提供需要变更的邮箱，核实后可修改，谢谢！

**Comment by yb19890724** [comment]
@Ghostwithout 
354037968@qq.com

**Comment by yb19890724** [comment]
@Ghostwithout
354037968@qq.com

**Comment by yb19890724** [comment]
@Ghostwithout
354037968@qq.com

**Comment by yb19890724** [comment]
@Ghostwithout

354037968@qq.com

**Comment by yb19890724** [comment]
@Ghostwithout

绑定邮箱:354037968@qq.com

**Comment by yb19890724** [comment]
@Ghostwithout

绑定邮箱：354037968@qq.com

**Comment by yb19890724** [comment]
@Ghostwithout

绑定邮箱：354037968@qq.com
