### ISSUE TITLE
蓝灯扑街了，来试试v2ray

### ISSUE THREAD

**Issue by dgdcg** [getlantern/forum#8248]
教程很简单，几分钟就ok了，自己搭建没有任何设备限制，爱怎么玩，就怎么玩。
# [搬瓦工官网](https://www.bwh1.net/aff.php?aff=22647)
# [图文教程链接](https://www.tbreak.top/kda/56/)

**Comment by asdg-asdf** [comment]
我目前用lantern状态良好 不知道为什么你说不灵了
输入我的邀请码 JWBMX4 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by asdg-asdf** [comment]
我目前用lantern状态良好 不知道为什么你说不灵了
输入我的邀请码 JWBMX4 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
对了 地点beijing
