### ISSUE TITLE
新唐人电视台：自由浏览应用已被中共控制！！！

### ISSUE THREAD

**Issue by vasubo** [getlantern/forum#8260]
http://www.ntdtv.com/xtr/gb/2018/01/22/a1360380.html
自由浏览（英语：FreeBrowser）是一款由GreatFire开发的安卓破网软件，于2015年2月发布。在中共进一步审查与封锁网络的情况下，有大陆用户披露，自由浏览应用已被中共控制。

1月22日，有大陆读者向新唐人投书说，自由浏览应用已被中共控制......

该读者并发布了两点声明：

一：我不清楚中共政府是什么时候控制了，自由浏览这个github项目，它除了有app.还有一些源码。大概是旧年开始发现我安装这个app后，它的界面就不停地截图，每秒截图好几次，很快，你触屏越快它就截图越快。不停出现红色边框。但是在手机里是找不到这些截图的。

今天我谷歌搜索了原因才发现，这项目被中共控制，太危险了。

搜索的证据网址 programthink/zhao#131 您可以亲自用没有任何私人资料的安卓手机安装自由浏览试试，打开后，它截图的红框闪得比你触摸屏幕还快！

这消息我将告诉几家新闻媒体，希望都能公布出来，这事情实在太严重。

**Comment by jinlx** [comment]
emmmm...外国势力给了你多少钱，中国爸爸给你两倍
