### ISSUE TITLE
蓝灯支持不全面，试试这个

### ISSUE THREAD

**Issue by dgdcg** [getlantern/forum#8268]
教程很简单，几分钟就ok了，全终端支持，
自己搭建没有任何设备限制，爱怎么玩，就怎么玩。
# [搬瓦工官网](https://www.bwh1.net/aff.php?aff=22647)
# [图文教程链接](https://www.tbreak.top/kda/56/)

**Comment by FGorGor** [comment]
为什么看到好多发介绍搬瓦工的都有介绍月付2.99那款，而我进去一直没显示那款
