### ISSUE TITLE
lantern ubuntu16.04 系统下无法升级到专业版, windows下和手机上能正常升级.

### ISSUE THREAD

**Issue by hhmaizi** [getlantern/forum#8269]
请在发帖前先按照蓝灯无法使用的解决办法 https://github.com/getlantern/forum/issues/1902 自行解决。自行解决问题通常只需要几十分钟。管理员调查解决问题需要几天至几周。请立即访问https://github.com/getlantern/forum/issues/1902 瞬间解决98%的问题

为了能在最快的时间内解决大家使用蓝灯遇到的问题，请各位用户严格按照发帖格式提交问题。

## 发帖格式
遇到的问题：请详细描述遇到的问题。如果描述不仔细，将无法调查

蓝灯专业版账号Email:  请提供登陆蓝灯专业版的email，免费版不提供技术支持。

应用内报告问题的时间:  请根据 https://github.com/getlantern/forum/issues/1840 在应用内上报问题，请填写专业版的email。请在帖子里注明报告的时间。

截图: 请提供有关问题的截图。 请把图片拖拽到这里。

----
邀请码在本论坛请以签名形式发布或发到其他论坛。具体见 https://github.com/getlantern/forum/issues/3773

![screenshot from 2018-02-10 10-58-50](https://user-images.githubusercontent.com/12286443/36058021-a8766284-0e52-11e8-8f73-9537d7ae82ed.png)
![screenshot from 2018-02-10 10-58-50](https://user-images.githubusercontent.com/12286443/36058025-b57821e8-0e52-11e8-97a0-c31398de5d9f.png)

**Comment by hhmaizi** [comment]
可以访问外网,但是无法使用付费版

**Comment by Ghostwithout** [comment]
请在https://github.com/getlantern/forum/ 下载使用。 @hhmaizi
