### ISSUE TITLE
华为更新系统8.0.0.336后蓝灯无法使用

### ISSUE THREAD

**Issue by shinwahtsang** [getlantern/forum#8295]
华为更新系统8.0.0.336后蓝灯无法使用

**Comment by Ghostwithout** [comment]
请参照https://github.com/getlantern/forum/issues/7619 
进手机管家，启动管理，把蓝灯设置成自动管理（也就是点亮开关）看能恢复不？

**Comment by shinwahtsang** [comment]
pefekt!

问题解决 

ticket closed!
