### ISSUE TITLE
云主机10分钟搭建ssr科学上网服务教程，年付只需180元

### ISSUE THREAD

**Issue by fcghm** [getlantern/forum#8303]
买个搬瓦工VPS，输入优惠码后年付28.19美元起，折合人民币180元，
可以找朋友一起合租，3人平摊每人60元，支持支付宝付款
然后自己搭建
教程很简单，几分钟就ok了，youtube 1080p无压力。
# [搬瓦工官网](https://www.bwh1.net/aff.php?aff=22647)
# [图文教程链接](https://www.tbreak.top/kda/56/)
别问我是谁，我是雷锋

**Comment by sblig** [comment]
http://27yun.vip/aff.php?aff=55
偶然遇见，挺方便的
