### ISSUE TITLE
维基百科无法创建账号

### ISSUE THREAD

**Issue by wangshen27** [getlantern/forum#831]
用lantern，没法注册维基百科的账号，IP被block了！希望能解决一下！
![wikipedia](https://cloud.githubusercontent.com/assets/3361433/17125034/a568baf2-5322-11e6-87e2-53b52685eef1.png)

**Comment by p3rcya** [comment]
这个是维基百科的问题

**Comment by wangshen27** [comment]
@p3rcya 这不对吧！为什么用其他的翻墙工具、VPN就可以，而lantern的IP却要被封掉？至少该有个原因吧！

**Comment by p3rcya** [comment]
请看这里 https://meta.wikimedia.org/wiki/No_open_proxies/zh

**Comment by wangshen27** [comment]
@p3rcya 明白了！谢谢，谢谢！
