### ISSUE TITLE
这特么的，托还真是多

### ISSUE THREAD

**Issue by bfxyly** [getlantern/forum#8314]
真是看扁别人的智商，这里是issue，什么时候才来这里？用蓝灯出现问题的才会出现在这里。
你特么的能用，用的好好的，你吃饱了撑着来这里闲逛？
看到一些回复，类似什么“我的能用”啊之类的，我不禁感到怀疑，你能用，你早就翻墙看YouTube去了。
很简单的逻辑，你的电脑能正常使用，你会去电脑维修的地方瞎JB逛？会去告诉那些在修电脑的人：我的电脑能用？

**Comment by FGorGor** [comment]
你是在有问题来这，不代表所有人都是啊，我的确能上，刚刚来这是想反应问题，同时也回复了几个帖的"我的能用"

**Comment by LanternLease** [comment]
你这智商真不用别人看扁。
