### ISSUE TITLE
有客服么？ 无缘无故扣了2次费

### ISSUE THREAD

**Issue by ChaoCB** [getlantern/forum#8349]
为什么我购买了2年的却扣了2次费？
到现在也没有取消第一笔交易 请客服确认一下 邮箱就是我的账号邮箱

**Comment by pshikun** [comment]
输入我的邀请码58GG2S来获得3个月的蓝灯专业版！最新出炉的，欢迎各位，立即下载https://github.com/getlantern/forum

**Comment by Ghostwithout** [comment]
请告知你的邮箱和扣费截屏，以便调查。谢谢！

**Comment by ChaoCB** [comment]
@Ghostwithout 
网银内没法截图 所以只发记录
账号 819229691@qq.com
支付记录
2018/02/22 01:56:05(GMT+09) TSI-PAYMENTWALL 57,763KRW支出
2018/02/22 02:38:55(GMT+09) TSI-PAYMENTWALL 57,763KRW支出
第一次支付完之后出现过一次验证失败 但还是扣费了 无奈再尝试第二次交易 然后成功了
但是第一次交易扣费之后没有返还
请客服尽快确认一下

**Comment by Ghostwithout** [comment]
涉及个人信息，已经通过邮件回复，请查看。谢谢！

**Comment by ChaoCB** [comment]
@Ghostwithout
已经回复邮件了 还是没有答复吗 钱还是没返还 依然是扣了2次费
