### ISSUE TITLE
无法用激活时候填写的邮箱登录

### ISSUE THREAD

**Issue by shanligang1017** [getlantern/forum#8412]
登录提示如下
![2018-02-26_102835](https://user-images.githubusercontent.com/28751979/36650772-226c81ce-1ae0-11e8-9852-e9e04a120a9a.jpg)

购买的订单号如下
![2018-02-26_102934](https://user-images.githubusercontent.com/28751979/36650784-2e1c41c6-1ae0-11e8-8a0c-3e0ec393eebf.jpg)

希望帮忙看看，我记得激活时候用的邮箱就是kardel@163.com

**Comment by Ghostwithout** [comment]
你在哪里买的或者哪里知道这个网址的，lantern只有一个官网https://getlantern.org/，你上传的界面不是lantern的购买界面。 @shanligang1017

**Comment by shanligang1017** [comment]
忘记了是从哪里知道的了，反正是中国这边推荐的，是可以有优惠，300两年，而且是可以正常激活的，还有个群呢，难道是途径有问题？就算途径不一样，但是我激活是从正规的APP上激活的，填写的邮箱应该也要有效啊，我这种人很多，在QQ群都炸锅了，忘尽快解决，激活码为CKHJG-BTCDB-2CRJW-36TB3-PTVYY。@Ghostwithout

**Comment by shanligang1017** [comment]
既然能激活，什么方式获得的激活码应该是没啥关系吧，如果不行为何不直接提示不能激活，既然激活了，那激活的邮箱应该也一样要绑定啊，从群里得知以前都是可以，只是最近不行，而且在这个论坛里issue上搜索结果来看软件购买我看一样存在邮箱不能的问题，根本就是你们技术或者服务器上的问题，请不要推给从哪里买的身上，行不行？@Ghostwithout

**Comment by shanligang1017** [comment]
购买是从你们的代理商购买的，应该是正规渠道

**Comment by Ghostwithout** [comment]
‘正规的APP上激活’－这个APP是指的什么，哪里来的？在哪里激活的？请提供所有相关截图和信息来源及购买情况，看到底是代理商还是遇到假的lantern了。通过我们代理商购买，给到的是25位reseller code/激活码。

![image](https://user-images.githubusercontent.com/33254750/36731839-e8310976-1c06-11e8-9b42-f31a987f3b8f.png)
目前看来，这个页面都不是lantern的，lantern只有一个官网https://getlantern.org/，而且除了个这个论坛，没有建立任何微信群QQ群。

![image](https://user-images.githubusercontent.com/33254750/36731975-578bb5b4-1c07-11e8-8d99-e3582f6cd810.png)
上图baidu搜索出来的结果都是假的。

**Comment by shanligang1017** [comment]
正规的APP就是你们github上下载的，从https://www.lanternpro.club/这上面买的优惠激活码，现在是处于激活状态，只是怕到时候授权的设备都重装就没有授权的方法了所以才来问邮箱登录的问题的。请问不是真的激活码能激活？激活码不方便在这上面贴出来。我就想问激活了还能是假的激活码吗？APP内提交问题也已经提交了，未见任何回复，里面提交的是有激活码的，直接一查就是。算了，我直接帖出来激活码吧，你帮我查下就是了见图，现在三台设备都授权了，取消一个尝试邮箱登录是不行的。如果这个网站不是你们代理的，那请问为何可以正常激活 
![2018-02-28_090126](https://user-images.githubusercontent.com/28751979/36764146-34b22762-1c66-11e8-8aea-523625b7cc9a.jpg)
![2018-02-28_090147](https://user-images.githubusercontent.com/28751979/36764150-3961e18a-1c66-11e8-9f01-70d4274ac57d.jpg)
![2018-02-28_090211](https://user-images.githubusercontent.com/28751979/36764153-3d8cb82a-1c66-11e8-9dc3-86841d4e2e18.jpg)


@Ghostwithout

**Comment by shanligang1017** [comment]
不管我们买的代理是不是你们授权的，既然能激活那就是你们的用户，至于你们激活码为何能在不授权的网站买到那是你们自己内部的问题  @Ghostwithout

**Comment by shanligang1017** [comment]
现在直接不回复了？@Ghostwithout

**Comment by orbancanon** [comment]
@shanligang1017 我们后台查了，邮箱没有绑上。现在已经给你恢复了，抱歉！我们正在查找是不是App有什么bug导致特定情况下没能绑上邮箱。

**Comment by shanligang1017** [comment]
恩，已经帮我绑上这个邮箱了吗，谢谢！确实应该查找下问题，因为类似的人不少@orbancanon

**Comment by shanligang1017** [comment]
刚试了下，终于可以登录了，谢谢管理
