### ISSUE TITLE
电脑共享蓝灯VPN至iOS手机和Android手机图形化详细教程

### ISSUE THREAD

**Issue by Ouksnack** [getlantern/forum#8426]
下载地址：
https://share.weiyun.com/895a14ceed77ebae88e2b8b84a490dfa

**Comment by huiyu998** [comment]
支持技术贴

**Comment by wjw513280** [comment]
@Ouksnack win10企业版用外置无线网卡试了一下，好像没有用。手机WIFI不挂代理，网络正常，挂代理，网络直接中断，就不要说用蓝灯翻墙了。不知道是何原因？

**Comment by Ouksnack** [comment]
@wjw513280 如果你的PC端蓝灯可以正常使用，在电脑和手机同一WiFi下一样可以走蓝灯代理路线

**Comment by wjw513280** [comment]
@不用热点可以连接吗？以前有人发过，但是试了一次，好像也不行。

**Comment by wjw513280** [comment]
PC端蓝灯一切正常。

**Comment by wjw513280** [comment]
@Ouksnack PC端蓝灯一切正常。

**Comment by CarlZhong01** [comment]
应该是 -addr= ？

**Comment by wjw513280** [comment]
不行啊，不知道别人有没有成功，我是弄不好了。。。。几个办法都尝试了，还是不行。

**Comment by wjw513280** [comment]
不行啊，不知道别人有没有成功，我是弄不好了。。。。几个办法都尝试了，还是不行。

**Comment by Ouksnack** [comment]
@wjw513280 你用的时什么手机系统？

**Comment by wjw513280** [comment]
@Ouksnack 我2个手机，安卓的和IOS的都不行，不过安卓的有APP可以安卓，IOS没有APP，所以想尝试IOS的翻墙，还是不行。

**Comment by Ouksnack** [comment]
你可以用你的电脑下载TeamViewer 13这个软件安装好以后告诉我你的id和密码
https://dl.tvcdn.de/download/TeamViewer_Setup.exe

**Comment by Ghostwithout** [comment]
楼主好有爱心，可以加精华吗？告知邀请码，赠送三个月，感谢分享！！ @Ouksnack

**Comment by williamddd** [comment]
国内的基本都被封杀了，就是存活的，也存在跑路风险，你还是直接买国外的吧
zhihu.page.tl
http://williamddd.doodlekit.com
https://diigo.com/0anh1v
