### ISSUE TITLE
搬瓦工VPS|年付120元补货了|支持支付宝|一键搭建

### ISSUE THREAD

**Issue by tisihua** [getlantern/forum#8428]
搬瓦工是著名的VPS加拿大品牌，支持支付宝付款、30天无理由退款、Shadowsocks一键搭建

当前最优惠套餐是19.9美金一年(可输入优惠码，教程有提供），2个人平摊大概一人60人民币即可。

自己搭建的SS服务器支持IOS等各种平台，速度好，隐私安全。
按着图文教程，10分钟搞定注册和搭建。
# [搬瓦工官网](https://www.bwh1.net/aff.php?aff=22647)
# [图文教程链接](https://www.tbreak.top/kda/56/)

**Comment by zjm1231** [comment]
容易被墙

**Comment by Qzeqi** [comment]
搬瓦工被墙的一大把

**Comment by tisihua** [comment]
那是因为姿势不正确
