### ISSUE TITLE
输入我的邀请码 N6Z6XZ 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

### ISSUE THREAD

**Issue by luchi2012** [getlantern/forum#8435]
输入我的邀请码 N6Z6XZ 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by KangHanfei** [comment]
输入我的邀请码 YH4D57F 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by sanfangjia** [comment]
输入我的邀请码 YSW9UQ 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
