### ISSUE TITLE
购买了lantern 但是没有绑定邮箱。  购买了两年的套餐，重装系统后无法登陆。 使用支付宝账号也无法登陆

### ISSUE THREAD

**Issue by Garfiebobo** [getlantern/forum#8438]
## 发帖格式
2017年6月 购买的lantern 两年套餐， 2018年2月26号我重装系统后 发现Lantern账户无法登陆 ，使用支付宝账号也无法登陆。

支付宝账号是18801192674
这是付款截图
请客服帮我绑定下邮箱 545990071@qq.com  谢谢
![screenshot_20180227-161906](https://user-images.githubusercontent.com/19267769/36717880-c1f3a5ba-1bda-11e8-9f3b-64d55e3260cb.png)

**Comment by Ghostwithout** [comment]
你好，经查询，绑定的邮箱是1880＊＊＊2674@sina.cn，可通过如下方式授权专业版：
－在lantern界面左边菜单点击“授权设备使用专业版”，在里面输入购买时的邮箱，激活码就会发到你的邮箱，然后输入激活码即可； 
－在新设备选择“授权设备使用专业版”，该界面会收到验证码，然后请到专业版设备输入验证码。谢谢！ @Garfiebobo

**Comment by Garfiebobo** [comment]
3Q 已经查到了
