### ISSUE TITLE
[求助]我的专业版账号管理界面显示无邮箱地址，也无法用其登录

### ISSUE THREAD

**Issue by Yunhexiong** [getlantern/forum#8446]
发帖格式
遇到的问题：我在应用内使用**代理商提供的25位激活码**并激活成功（1年），当时填写（并确认）的邮箱是：562192782@qq.com，## 激活成功页面正常显示，我也获得了12个月的正常使用时间——
但随后我发现，我的账号管理界面并没有邮箱地址，也就是该界面的邮箱地址后显示为空！
我可以正常使用VPN和授权设备，但不能在退出登录后使用我的激活邮箱地址登录。

BTW：看到有类似的用户出现了在疑似假冒的代理商网站购买后和我相同的情况，请工作人员也谅解我们用户着急的心情——在应用内填写了邮箱并成功激活这一点是肯定的吧？
既然已经激活成功，那应该有邮箱地址出现才对，和我们是否在非正规渠道购买了激活码并无因果关系——如果我们购买之后无法激活，纯属我们上当受骗，但我们觉得邮箱注册信息异常是激活程序的问题
所以请工作人员调查一下这个情况，如果需要我可以提供我的激活码，请联系我的邮箱或直接在本帖下方回复我，谢谢！

蓝灯专业版账号Email:  激活时填写的是562192782@qq.com

截图: 请提供有关问题的截图。 请把图片拖拽到这里。
![_20180228004635](https://user-images.githubusercontent.com/36894979/36741747-d2864af6-1bdd-11e8-9a21-e61ea05904e2.png)

**Comment by Yunhexiong** [comment]
@Ghostwithout

**Comment by Ghostwithout** [comment]
你好，麻烦告知你的激活码／推荐码（左上角邀请朋友那里可以看到），以及购买凭证以便调查，谢谢！ @Yunhexiong

**Comment by Yunhexiong** [comment]
你好！
我的激活码如下
![491526714198660822](https://user-images.githubusercontent.com/36894979/36776269-1b96054a-1c5d-11e8-9f68-4dda669e2da6.jpg)

我的邀请码如下：
![_20180228155621](https://user-images.githubusercontent.com/36894979/36776236-fe19cd30-1c5c-11e8-86a1-0155a78c2f12.png)

需要请你们注意的是，我发帖之后注意到，我是在http://www.lanternpro.co/ 这个网站# 也就是你们帖子所说的假冒网站上购买的激活码，请查实这类激活码是否出自你们内部，或是别的代理途径？

**Comment by Ghostwithout** [comment]
你好，已经为你绑定邮箱562192782@qq.com，谢谢！ @Yunhexiong
