### ISSUE TITLE
手机系统升级后授权掉了

### ISSUE THREAD

**Issue by chainswer** [getlantern/forum#8486]
手机系统升级后授权掉了
无法通过激活时的邮箱找回, 邮箱:18609157031@163.com,激活时间,2018年03月01日,激活码:CRXQM-DX2VH-GDTY3-7KCK6-YH39W,请管理员看下, 帮恢复一下,谢谢

**Comment by Ghostwithout** [comment]
你好，已经绑定18609157031@163.com 
谢谢！ @chainswer
