### ISSUE TITLE
lantern代理的IP是不是每天都在变？

### ISSUE THREAD

**Issue by wangshen27** [getlantern/forum#850]
lantern代理的IP是不是每天都在变？

**Comment by p3rcya** [comment]
不一定。

**Comment by wangshen27** [comment]
@p3rcya 最近几天我的IP一直再变，每天的都不一样。因为这样，我的google账号这几天天天都被停用了！

**Comment by p3rcya** [comment]
最好加个两步验证，这样就不会被停用了

**Comment by wangshen27** [comment]
@p3rcya 一直都是两步验证！最近每天只要一发邮件就被停用了，还有从维基百科申请来的IP封禁例外也因IP天天改变而不能用了……可不可以一段时间内，让IP固定下来，隔六七天改变一次？

**Comment by p3rcya** [comment]
不好意思。 这个我们以后会加入。但是改变IP才能防止GFW，所以这个不一定可以

**Comment by wangshen27** [comment]
@p3rcya 谢谢，麻烦尝试一下！
