### ISSUE TITLE
新手刚刚入坑，为什么买了一年专业版还是不能上YouTube

### ISSUE THREAD

**Issue by aadd1991** [getlantern/forum#8502]
PC端上不了外网

**Comment by aadd1991** [comment]
顺便说下，手机版可以上Google play下东西

**Comment by Chinaguigui** [comment]
你打开全局代理就行了

**Comment by aadd1991** [comment]
@Chinaguigui  开了全局也不行 - =

**Comment by Chinaguigui** [comment]
@aadd1991 喵喵喵？这个嘛 估计网络问题 还是什么原因我不知道 其实我广州电信100兆 能看任何国外网站

**Comment by aadd1991** [comment]
@Chinaguigui   我广州联通100M的  QAQ，手机上YouTube很流畅，汤不热很卡
有人说最近开会所以不能用，不知道是不是
