### ISSUE TITLE
关于蓝灯iOS端问题

### ISSUE THREAD

**Issue by TongFangyuan** [getlantern/forum#8521]
蓝灯iOS端什么时候出来
现在已经2018年3月了

----
输入我的邀请码 WM2GRY 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by TongFangyuan** [comment]
有没有明确的计划可以公布下呢

-----------------
输入我的邀请码 WM2GRY 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by TongFangyuan** [comment]
顺便出售一个坑位,价格好说

----------------------
![61520324817_ pic](https://user-images.githubusercontent.com/9019860/37021698-65ec5858-215b-11e8-9ef5-025c75037ba8.jpg)

---------------------
输入我的邀请码 WM2GRY 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by TongFangyuan** [comment]
68/年 企鹅: 573682532

**Comment by akingbr** [comment]
今天下了vyprvpn了，在ios上，速度很快

**Comment by Ouksnack** [comment]
ios权限管的最严了，不像安卓一样随便，你以为说有就有啊

**Comment by acaesar17** [comment]
蓝灯iOS端什么时候出来
现在已经2018年3月了

**Comment by plusOneSecond** [comment]
一直在跳票，2016推到2017，2017推到2018，现在2018过去半年了也没出来。
完成不了的事情请不要随便承诺好吗？
