### ISSUE TITLE
激活码激活没有绑上邮箱, 不显示邮箱

### ISSUE THREAD

**Issue by heyuanjundai** [getlantern/forum#8544]
激活码激活没有绑上邮箱, 不显示邮箱,现在无法登录

激活的邮箱 | 691302655@qq.com 
激活的时间 | 2018年03月05
使用的激活码 | 266DY-DGXWB-2DKTP-W6MYB-WG23K

请处理一下, 谢谢管理员大人

**Comment by Ghostwithout** [comment]
你好，已更新，谢谢！ @heyuanjundai
