### ISSUE TITLE
今天下午开始不能翻了

### ISSUE THREAD

**Issue by shanligang1017** [getlantern/forum#8618]
今天下午开始突然不能用了，上午还是可以的，可以排除手机环境的问题，并且另一个手机也不行了，看了下今天开始有些人不行有些还是可以正常使用，不知道是不是和账号有关系，我的账号kardel@163.com，麻烦帮忙看下

**Comment by weihan0917** [comment]
我的也是翻不了墙，一直掉线

**Comment by xiaohangquan** [comment]
一样

**Comment by MRPIN233** [comment]
同..今天下午开始炸了.现在在用赛风维持和外界联系..

**Comment by MRPIN233** [comment]
希望蓝灯加油早日修复..

**Comment by Maomaoa1** [comment]
我也是下午挂了，上午还好的

**Comment by Maomaoa1** [comment]
@MRPIN233  你有赛风的下载地址吗？谢谢了

**Comment by MRPIN233** [comment]
https://github.com/getlantern/forum/issues/4775

这个帖子有.

**Comment by aptx4869670** [comment]
一样，希望尽快解决

**Comment by Evelynhql** [comment]
我也是，我还以为是我这面的网络问题。。。没想到用4g，卸载了重装还是不行

**Comment by WhiteJee** [comment]
我的已经恢复了

**Comment by Declarcall** [comment]
已恢复

**Comment by shanligang1017** [comment]
应该是昨天记者会的原因，今天陆续恢复了

**Comment by hao8857305** [comment]
2018/3/12掉线一天
