### ISSUE TITLE
出现已连接，实际没有网络的情况报个到

### ISSUE THREAD

**Issue by Xbigfat** [getlantern/forum#8639]
早上起来发现可以连接，显示连接上，但是没有外网ip地址。是出bug了吗？
地区：安徽
节点：Japan 
同出现问题的队友来报道，方便的话带上地址，节点。

**Comment by Cyndee4125** [comment]
一样的情况，专业版湖北的。蓝灯是要挂了吗

**Comment by Baogh** [comment]
同问

**Comment by blue1982414** [comment]
一样的情况，无法访问外网 又被feng了？（上海）

**Comment by Wayman1306** [comment]
杭州这边也一样

**Comment by zcchinese** [comment]
广东一样的情况

**Comment by ZH3057** [comment]
北京 一样情况

**Comment by DongZcC** [comment]
杭州也这样

**Comment by shangsanyu** [comment]
广州+1,3.11晚投票完之后G，我只想安静的看油管小姐姐而已

**Comment by xybin1990** [comment]
深圳，Japan节点

**Comment by josephyuen** [comment]
长沙， Japan节点

**Comment by orchid251** [comment]
上海，电信，JPN绿灯但是没网

**Comment by lbjhzj** [comment]
成都,电信,连上不能登录,就自动断开

**Comment by shoofywx** [comment]
山东济南联通，JP有时绿灯有时变灰，山东济南电信好点，但非常非常不稳定

**Comment by leeight** [comment]
上海，电信，JPN绿灯但是没网

**Comment by hisui123** [comment]
经常抽风的 等等吧

**Comment by abs360cc** [comment]
陕西，专业版电脑安卓都连不上，工作人员辛苦了（推特和油管上不去难受的打滚）

**Comment by boweyy** [comment]
昨天夜里11点买的，今天就不行了？我擦？什么鬼

**Comment by xingchengMa** [comment]
从昨天开始就一直这样， 没有公告什么都没有，我们一群人在这傻不拉几的等，您那边就跟什么都没发生一样，一点回音儿没有，你好歹回个话啊，我们要求真的不高，不要求你马上恢复，只是回个话就好，就只是回个话，好吗？？？？

**Comment by haley924** [comment]
重庆这里也是一样，一会连得上一会连不上

**Comment by fultonlee1** [comment]
宁波也是一样，不稳定

**Comment by wabyt** [comment]
辽宁同样情况，什么时候才能上啊。工作要用邮箱呢。

**Comment by boom1213** [comment]
正常操作。。半个多月都是不稳定状态了

**Comment by Leona11** [comment]
广东 一样已连接、连接中跳来跳去 ，没有一秒能正常连接上用的

**Comment by Elainejx** [comment]
北京一样。。上周还能正常使用的呢

**Comment by leslieeilsel** [comment]
西安专业版无法使用，难道因为在开会？

**Comment by xybin1990** [comment]
@leslieeilsel 你懂的

**Comment by Evelynhql** [comment]
贵州 手机版

**Comment by seulzzy** [comment]
前天还能正常使用。。昨天晚上开始就是连接上会直接变灰了。。僵硬。。上海。。电信

**Comment by al310517** [comment]
杭州表示 蓝灯貌似又挂了...

**Comment by avilang** [comment]
广东 一样已连接、连接中跳来跳去 ，没有一秒能正常连接上用的

**Comment by hisui123** [comment]
刚才能正常用了一会 赶紧推特上给朱夏点了个赞 然后立刻不能用了...

**Comment by junxi88** [comment]
江苏苏州电信表示现在恢复了

**Comment by DongZcC** [comment]
恢复了

**Comment by RedspyJD** [comment]
两天前就开始不能用了，一直没恢复

**Comment by lousiwei** [comment]
救命
