### ISSUE TITLE
【友情提示】官方iOS版迟迟不出，昨天蓝灯又突然失效，目前有一款免费的手机VPN客户端可以使用，亲测有效。

### ISSUE THREAD

**Issue by VisionKwok** [getlantern/forum#8671]
##  iPhone手机可以用外区的苹果ID账号下载一个 **` Opera VPN`**，安装后同意服务条款，如图按下开启，连接后就能翻墙了。（没有外区苹果ID的话，可以淘宝买一个）
![img_7192](https://user-images.githubusercontent.com/31103660/37279334-7f3d3334-25b8-11e8-8874-a1c3a27b9abe.PNG)
但愿会议结束后蓝灯能尽快修复，我还脑子发热，一口气买了3年的，可愁死我了，蓝灯一直挺稳定的，毕竟是特殊时期，只能等待了。

蓝灯如果恢复了，大家可以考虑用一下我的邀请码：**`JRDS96`** （特殊时期还是等待吧，别急着续费或购买）
# **`JRDS96`**
蓝灯这架梯子可千万不能倒！

**Comment by bayernzy** [comment]
港真 越多人知道  越快GG
