### ISSUE TITLE
PC版蓝灯，.5最新版本专业版显示已连接确无法访问油管等网站。坐标烟台联通

### ISSUE THREAD

**Issue by Battleyunyun** [getlantern/forum#8726]
emil:812753020@qq.com
希望获得解决方法

**Comment by 15884282694** [comment]
我的也是992038290@qq.com--Sent from Yandex.Mail for mobile13.03.2018, 14:19, "Battleyunyun" <notifications@github.com>:emil:812753020@qq.com
希望获得解决方法

**Comment by ys73** [comment]
南京联通，同样问题。
