### ISSUE TITLE
Lantern 3.0.7 打开闪退

### ISSUE THREAD

**Issue by wfluw** [getlantern/forum#876]
OS: Windows

> Jul 31 05:55:25.878 - 0m0s DEBUG flashlight.app: app.go:85 map[pprofaddr: readableconfig:false test.bench: test.count:1 uiaddr:127.0.0.1:16823 configdir: obfs4-distBias:false proxyall:false test.benchmem:false test.cpu: test.trace: country:xx borda-sample-percentage:0.01 headless:false test.coverprofile: test.parallel:8 test.run: addr: clear-proxy-settings:false cpuprofile: help:false startup:false test.benchtime:1s test.cpuprofile: borda-report-interval:5m0s frontedconfig: registerat: test.outputdir: test.v:false staging:false force-proxy-addr: stickyconfig:false test.blockprofile: memprofile: test.blockprofilerate:1 test.memprofile: force-auth-token: cloudconfigca: test.memprofilerate:0 test.short:false test.timeout:0 cloudconfig:]
Jul 31 05:55:25.878 - 0m0s DEBUG flashlight: flashlight.go:162 ---- flashlight version: 3.0.7, release: 3.0.7, build revision date: 20160714.225517 ----
Jul 31 05:55:25.878 - 0m0s DEBUG flashlight: flashlight.go:89 Initializing configuration
Jul 31 05:55:25.878 - 0m0s DEBUG flashlight.config: fetcher.go:76 Not configuring for staging. Using flags: map[force-proxy-addr: frontedconfig: registerat: test.outputdir: test.v:false staging:false memprofile: stickyconfig:false test.blockprofile: force-auth-token: test.blockprofilerate:1 test.memprofile: cloudconfig: cloudconfigca: test.memprofilerate:0 test.short:false test.timeout:0 configdir: pprofaddr: readableconfig:false test.bench: test.count:1 uiaddr:127.0.0.1:16823 country:xx obfs4-distBias:false proxyall:false test.benchmem:false test.cpu: test.trace: addr: borda-sample-percentage:0.01 headless:false test.coverprofile: test.parallel:8 test.run: test.cpuprofile: borda-report-interval:5m0s clear-proxy-settings:false cpuprofile: help:false startup:false test.benchtime:1s]
Jul 31 05:55:25.878 - 0m0s DEBUG flashlight.config: fetcher.go:92 Will poll for config at http://config.getiantem.org/cloud.yaml.gz (http://d2wi0vwulmtn99.cloudfront.net/cloud.yaml.gz)
Jul 31 05:55:25.878 - 0m0s DEBUG flashlight.config: config.go:171 Using config dir C:\Users\a\AppData\Roaming\Lantern
Jul 31 05:55:25.888 - 0m0s DEBUG i18n: translate.go:105 Setting locale en_US
Jul 31 05:55:25.888 - 0m0s DEBUG flashlight.ui: ui.go:126 Accessing translations
Jul 31 05:55:25.918 - 0m0s DEBUG yamlconf: yamlconf_disk.go:130 *********************** Read from disk in 40.0001ms
Jul 31 05:55:25.918 - 0m0s DEBUG flashlight.config: config.go:78 Found 6 chained servers in config on disk
Jul 31 05:55:25.918 - 0m0s DEBUG flashlight.config: config.go:80 chained server: &{
&{<ip> PvQ+I+g/FithtYXz49ScJZaJzIp5adH34Ebcv8+E4+8PwvPz6tsi+u1TGS1NuOMKS8+6LA 1bVUm29nTyJkNWfWHEnAvSM3a8mNySmVrSQcGSZaaqwZLQfu5ihPMdqT3tCYsAiE true obfs4 map[iat-mode:0]}
Jul 31 05:55:25.918 - 0m0s DEBUG flashlight.config: config.go:80 chained server: &{
&{<ip> -----BEGIN CERTIFICATE-----
MIIDrDCCApSgAwIBAgIEbpWolTANBgkqhkiG9w0BAQsFADB+MQswCQYDVQQGEwJVUzERMA8GA1UE
CBMIVmlyZ2luaWExEjAQBgNVBAcTCUJ1bGxkb3plZDESMBAGA1UEChMJQnVkIEdyaWxsMRowGAYD
VQQLExFQZXR0aWZvZyBMb25nYm9hdDEYMBYGA1UEAxMPUGF0cmltb255IFBlYXJsMB4XDTE2MDYx
NzEyMzUwN1oXDTE3MDYxNzEyMzUwN1owfjELMAkGA1UEBhMCVVMxETAPBgNVBAgTCFZpcmdpbmlh
MRIwEAYDVQQHEwlCdWxsZG96ZWQxEjAQBgNVBAoTCUJ1ZCBHcmlsbDEaMBgGA1UECxMRUGV0dGlm
b2cgTG9uZ2JvYXQxGDAWBgNVBAMTD1BhdHJpbW9ueSBQZWFybDCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBANbmuLHBXNRIxYZNECZmjOM9n1PANIoxieHPGY72S3uUPs7gl3KUo/dafqMh
aLTuQBBYm04bkdGIOf116JJIDIeR7JxO3VwoLDuKwpIuEcyE6mUjTPVHluIMuAs6xPRv09tzvkVy
rL3+8+CgyrabkJOeHs6YZ0yChXPeA/h9koh4FoC0rOO/nZUNJgDPOnDIro/2CoCqp6+9oxOpl5ea
R5R4A9rnvk0mRs2pithdIdqM/zOOQ3V2koTLrndqZtgjdbVkKgbw4kQhqOd/BNLVVcYu7b0+h+J/
9vJSlv7qkFJkKylfUEIBiJoUFCbfRuuXDqVK4zYgE2zaVOAGwzNDVE8CAwEAAaMyMDAwDwYDVR0R
BAgwBocEaIOGfzAdBgNVHQ4EFgQUTVHwUpyXGzE3CynWZ5MdP4QBPF8wDQYJKoZIhvcNAQELBQAD
ggEBAMaBh12rS1dwHOYSxqntI6u8U2wWIcYWTMTcGDlcsyF5lQrkM/4kyszsKiFG7e7yVI4MzUH8
4yp6T4rF18+3Ydl7xlw65eAtj78RiI96yGnCNgMJgE5LdNCdyGlkJdbu5Z1WvsILiZcsaVUpBRMP
4LS3TtbXd3z3gv8vHzwIYyVGaWY0M+iTQxekHkGdZBYpse2/ozBk0nBvAd31aJRXFqUwtw3Jzt/x
Qm3M4b4h5IOg0UrO3yHHIkkGbfF/ofgA+WgVg2vTCy/L2vhbYplIDxGqv479WfM50tHuUErRmC08
dgzPfozpU9tGDZ00LaVjjOjTBMyDE2wwxB6liQWSobE=
-----END CERTIFICATE----- lvQsMhrj9lP8WdczgGHjfFBc6Z7ZFNTaqBdv1Oc8uinPNn6cxeX8srdWaVT3TTaN true  map[]}
Jul 31 05:55:25.918 - 0m0s DEBUG flashlight.config: config.go:80 chained server: &{<ip> -----BEGIN CERTIFICATE-----
MIID0jCCArqgAwIBAgIEDPI7KTANBgkqhkiG9w0BAQsFADCBkDELMAkGA1UEBhMCVVMxEzARBgNV
BAgTCkNhbGlmb3JuaWExFDASBgNVBAcTC0luaGliaXRpb25zMQ8wDQYDVQQKEwZCYXJvbnMxLTAr
BgNVBAsTJENob3BwZXIgQWR2ZXJzYXJ5IFdlaWVyc3RyYXNzIEtsdXR6eTEWMBQGA1UEAxMNUHJl
Y2lwaXRvdXNseTAeFw0xNjA2MDcxMjM2MjZaFw0xNzA2MDcxMjM2MjZaMIGQMQswCQYDVQQGEwJV
UzETMBEGA1UECBMKQ2FsaWZvcm5pYTEUMBIGA1UEBxMLSW5oaWJpdGlvbnMxDzANBgNVBAoTBkJh
cm9uczEtMCsGA1UECxMkQ2hvcHBlciBBZHZlcnNhcnkgV2VpZXJzdHJhc3MgS2x1dHp5MRYwFAYD
VQQDEw1QcmVjaXBpdG91c2x5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlfvM3bcT
/NHxQQmHofRDkVvopAGRR4DlntGJ1rR+MS1jqcxRgo+WaUl1Y5X1ndeYW8dEOhUAPvkwpAtu2Bs9
6lVwWqITEeRnF0N/MVKDEoZKaX15BiF3PjbZUd4JQYOEQwK8H4bcTJOnpemfqrV8TyWb426kLEWf
iJyUimQHZ1kKiUHYFkyCR9zBK/LEMw2UndiLmDCgITRc1trSsaRDK8JRJ3x+ZWZpLr3cn/6dmmzR
xSUj/NpT96AjvOv+r5/w7y17cpSs7IrrjKFOh5eeUbNM2FmswmIW4YGqWgP2K8epCBRGtowHIbx/
qJZKq5kSC4235+zQOpEK8TzIy9QkVwIDAQABozIwMDAPBgNVHREECDAGhwS8puL0MB0GA1UdDgQW
BBTvW82oLS/X1as+YIdPnMop5AMjHjANBgkqhkiG9w0BAQsFAAOCAQEACQgbDCmCrOjxzHXC0bat
aoVKRa0aPadbP/d1Tq0uGTz3D3Nx1jevRS/ht38lY+gzDyFegui4SA5Td3mSFyBX0Hj1etrXJ5na
xQrBT6s4+LfJ8RD2/BL815ti9Rt6YlyHsDrYDhRyfhPfoBEhNq7mDVfwE/zB7wSZSzVe6b2O9X4Y
Mxqs5yVA9gWJj5ZrOkQZT3C4TCeoTKQ/gOF+OcZE/MiGgUHF5C+uzPSd04gWi3rLlZz2pnqzPeIc
sgKRkK0Aa8hNTgWDpquI+NY0JnhCGkcaKldNqrYsZEs77Y7oOgehVukOYROnHBUpLuB8TXne6U7U
d36iTzZy9G08pFAusQ==
-----END CERTIFICATE----- KGhBi9HH8ZgkA8jRW2wmynBqW7I4vtVgStKf6r6YGMJdUo7RL4LHOOu24aww7Bwe true  map[]}
Jul 31 05:55:25.918 - 0m0s DEBUG flashlight.config: config.go:80 chained server: &{<ip> -----BEGIN CERTIFICATE-----
MIIDnDCCAoSgAwIBAgIECy9vaTANBgkqhkiG9w0BAQsFADB2MQswCQYDVQQGEwJVUzEVMBMGA1UE
CBMMTWFzc2FjaHVzZXRzMREwDwYDVQQHEwhIb3JzZWZseTEUMBIGA1UEChMLVHlpbmcgU2NydWIx
JzAlBgNVBAMTHlNwYXJyaW5nIENvbnNpc3RlZCBBbHRlcm5hdGVseTAeFw0xNjA0MDgxNDUxNTla
Fw0xNzA0MDgxNDUxNTlaMHYxCzAJBgNVBAYTAlVTMRUwEwYDVQQIEwxNYXNzYWNodXNldHMxETAP
BgNVBAcTCEhvcnNlZmx5MRQwEgYDVQQKEwtUeWluZyBTY3J1YjEnMCUGA1UEAxMeU3BhcnJpbmcg
Q29uc2lzdGVkIEFsdGVybmF0ZWx5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkUuO
OKW6qzYloc//BPfP/yv2KXhECDx5KWls0bzTJ42l2Ugvh1GlJ0di8DBbc7jnac/i7Z2sKbm34gwg
7e/nNFyNC+XzI8jrqRuinYebsKku+aaN+fEsdLlxaTlIO/7X2nDqcMDahia69wS6S434VsVycMBF
y7/UkxYkDAyVH6y5D/wxY/BRpSSCGlQ9fgT+YlQdD5RRvVX2di9isBqLmKRujuxzqOV+dYVWCSBE
NHdh2IoOo+r+sHzzzcrNSOgxb46MrLKra7aMGlrpUxxPtd1G/6vz3YHpd2imULeagSvyiepR2FkT
BVjgPHI65BhzWl8kX8bm53mLSpnHt+b32wIDAQABozIwMDAPBgNVHREECDAGhwSLoitNMB0GA1Ud
DgQWBBS327/rp9X0701L8C9lqctiR0/hlDANBgkqhkiG9w0BAQsFAAOCAQEAUGlS7i86P82x56YR
3Ee3Rvz89vjmx0qIaqOReQwbMY9jhXA1vbhY8dJlTTTtbDEHwtdtjjzodee/oE6pu5W+m77uUq7i
gumxU2/GmT2tg4dhqxd63EpsYOd8w8YBX4iuWOl8V1YTo1L0aB67ReJVE+An/tRQxKhsHPSTje5O
/++Oh6+3NHUAD5wf9GSsnOXWfSLmWBVNdOL/kRbf46gStFe1KHeM2PdO8panuwEFiOHmzI3p3bdV
izs6lXEL8w5DkZ5VCwA5Qr5xdDwwEs7GqqCTkoheh6Qh6KFxzeTQIHIksGiIgDVw435YANBq6tLi
Qb828Vtv95xhbMDgYr5taQ==
-----END CERTIFICATE----- fGq3Teqtyws0KLhfwwdNryQUKBldaRHC4kvtJhNjwQGb7TYIlrlSRJEVCw2Mq8sm true  map[]}
Jul 31 05:55:25.918 - 0m0s DEBUG flashlight.config: config.go:80 chained server: &{<ip> JvOH56aSJGHsqHDrT6yrETs5kpyZQjpmUuJ4IzfXdH9BdPzmsMCMU++FW5kcS32zsXPBMA eDcJwMnOZlpO9CioKsg3lACINrheWxOWoxG6TBtDb65xwZOvPy0AOQdnws53vsAU true obfs4 map[iat-mode:0]}
Jul 31 05:55:25.918 - 0m0s DEBUG flashlight.config: config.go:80 chained server: &{<ip> 3TWLGKIIJf6dJHdJmwwfcfITKQODe2OLinfkn6LC0bMoNXdiN3IZDsylSfNAOgm1Y7zjCA 6VdHpaWu6VgrScK1gXbIYmd79NmIh47EKv2B9HW5BlGXEiqJHe6R6EPHIvlLHZxg true obfs4 map[iat-mode:0]}
Jul 31 05:55:25.918 - 0m0s DEBUG yamlconf: yamlconf_disk.go:68 Configuration changed on disk, applying
Jul 31 05:55:25.918 - 0m0s DEBUG yamlconf: yamlconf.go:165 Loading per session setup
Jul 31 05:55:25.948 - 0m0s DEBUG flashlight.config: config.go:144 Returning config
Jul 31 05:55:25.948 - 0m0s DEBUG flashlight.app: app.go:119 Got first config
Jul 31 05:55:25.948 - 0m0s DEBUG flashlight.config: bootstrap.go:141 Opening bootstrap file from: C:\Users\a\AppData\Roaming\Lantern\.packaged-lantern.yaml
Jul 31 05:55:25.948 - 0m0s DEBUG flashlight.config: bootstrap.go:57 Opening file at: C:\Users\a\AppData\Roaming\Lantern\.packaged-lantern.yaml
Jul 31 05:55:25.948 - 0m0s DEBUG flashlight.config: bootstrap.go:67 Read bytes: startupurl:
Jul 31 05:55:25.948 - 0m0s DEBUG flashlight.app: app.go:156 Starting client UI at 127.0.0.1:16823
Jul 31 05:55:25.948 - 0m0s DEBUG flashlight.ui: ui.go:108 UI available at http://127.0.0.1:16823
Jul 31 05:55:25.948 - 0m0s DEBUG flashlight.app: bandwidth.go:32 Sending current bandwidth quota to new client
Jul 31 05:55:25.948 - 0m0s DEBUG flashlight: flashlight.go:99 Preparing to start client proxy
Jul 31 05:55:25.948 - 0m0s DEBUG flashlight.geolookup: geolookup.go:57 Requested refresh
Jul 31 05:55:25.948 - 0m0s DEBUG fronted: cache.go:95 Got existing instance
Jul 31 05:55:25.948 - 0m0s DEBUG fronted: cache.go:26 Attempting to prepopulate masquerades from cache
Jul 31 05:55:25.958 - 0m0s DEBUG flashlight.ui: ui.go:126 Accessing translations
Jul 31 05:55:25.958 - 0m0s DEBUG flashlight.ui: ui.go:126 Accessing translations
Jul 31 05:55:25.958 - 0m0s DEBUG flashlight.ui: ui.go:126 Accessing translations
Jul 31 05:55:25.958 - 0m0s FATAL flashlight.app: app.go:175 listen tcp 127.0.0.1:1233: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by p3rcya** [comment]
@orbancanon 你看看

**Comment by orbancanon** [comment]
@p3rcya https://github.com/getlantern/lantern-desktop-ui/issues/52 should solve it

**Comment by orbancanon** [comment]
@p3rcya https://github.com/getlantern/lantern-desktop-ui/issues/52 should solve it

**Comment by wfluw** [comment]
解决了吗, 下个版本什么时候放出来, 现在都用不了了

**Comment by orbancanon** [comment]
@wfluw 你的电脑不让Lantern使用1233端口，造成无法启动。你看看是不是本地有什么设置造成这种情况。默认情况下这个端口是可以用的。

**Comment by wfluw** [comment]
@orbancanon 换了一个网络环境可以使用了
本地设置怎么查看呢...?

**Comment by orbancanon** [comment]
可以了就好…… 到底是什么原因从Lantern的日志里看不出来。能看出的只有这一行
> Jul 31 05:55:25.958 - 0m0s FATAL flashlight.app: app.go:175 listen tcp 127.0.0.1:1233: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by wfluw** [comment]
在之前的网络环境可以使用3.0.7版本以前的Lantern... 是不是更新改了什么呢. 话说端口能不能手动设置改掉?

**Comment by orbancanon** [comment]
@wfluw 3.0.x才用了这个1233端口的，2.x没有用。后面会想办法把对这个端口的依赖去掉，但要等一阵儿才行……

**Comment by wfluw** [comment]
好的, 谢谢0.0
那我关掉了
