### ISSUE TITLE
win10系统更新后，不能登录专业版

### ISSUE THREAD

**Issue by lysidney** [getlantern/forum#8774]
如题，下午更新 win10 系统后，再打开蓝灯就是免费版界面，点升级到专业版也不弹出输入帐户的窗口，虽然现在蓝灯暂时废了，但也不能登不上专业版呀。
![default](https://user-images.githubusercontent.com/37281588/37389259-91b06efe-279e-11e8-8fb1-012b3fb75eba.PNG)

**Comment by xuying163** [comment]
这是因为服务器挂了

**Comment by xuying163** [comment]
无法跳转登录界面
