### ISSUE TITLE
推荐个临时代替品

### ISSUE THREAD

**Issue by shiranmegan** [getlantern/forum#8800]
https://en.greennode.biz
先装shadowsocks然后买账号，价格不贵，等蓝灯好了再取消

**Comment by w452187971** [comment]
买了个https://mewume.com/ 5元一个月~还算稳定40G流量够用了
三个邀请码 TWVoxoJUDQFK98tKez1IzEWz6J39BYBW
H1IWziQocW3erhOX6fSVkp0A6EszSmqj
TKzTH709nrZW7Vvr8J8BdHGz5YDrH8OO

**Comment by Ouksnack** [comment]
自由么，无界，xx -net 大把的，不行的话就下载一键翻墙浏览器

**Comment by Uer1900** [comment]
自己搭建也不费事儿，跟着教程花半小时搞定自己自足。
[官网地址](https://bwh1.net/aff.php?aff=24912)
[教程链接](https://www.tbreak.top/kda/56/)

**Comment by songokudeen** [comment]
ExpressVPN，买一个月试试，一个月内不满意随时退。用这个链接注册咱俩各多加一个月：https://www.expressrefer.com/refer-friend?referrer_id=14564536&utm_campaign=referrals&utm_medium=copy_link&utm_source=referral_dashboard

**Comment by w452187971** [comment]
原来的用完了~再来几个
买了个https://mewume.com/ 5元一个月~还算稳定40G流量够用了
20个邀请码 用掉一个就失效一个
eGrq3t07nlwGLxwGcw6iCAwSrH7uW3c1
YbrS69GhYMnTZ5NQ2VpQHVEV8GDB91rA
nmnxwycH0AU8PbZFWKWshvCqVy5zDQFn
xPWhY7wz06Fnz1CtcLoEAfC1YmkpfGRf
l934Ira5FdFL0w8hoCrFaJ6H649etFkZ
T2w9bXX8QDHiJXtBbGPbfoCFfQox9867
g0Yb8Dg2pygZlX7z7MnwTqJOfldTiwqz
UNBP7GQBzdAI8PgjTNH0SPn2FPMTRsmf
dDLUZpFREz4Hggp1MAMZA0zHfio9l69Y
6W24scgFSS63jOnDu1lYaCICYsUs4tYz
0Mn4AufQ8oapOXi8znLhoSzY0IjISIBk
rbUfRZ9LDsp37i9n6gxQZBXiCWp4X9Be
SHYy2FBB6krY6QmTcCjRPypHwy7GzZwk
ok2vku8c8cCnzOY990rum1GkHf746mYN
qJIMb01TMGkDNCfj38Q3coBcYYwNBfEm
mby4V17eL4mTMuXWkmwRmxrlRjNItF6P
BgLmzqDq27jXoC1yqJGJ6kqgMwEaCoRA
wMb9VP6JT5ywHVLxRag6I9Ci3bQXlpoX
ZOfOlcY50Q0VE0WLSMO5dKzFVQ6ktyKm
lZQjLKILOqa5cKBoOcOFayHxPAcjmVmJ

**Comment by xxxvy88** [comment]
https://mewu.cc/auth/register
邀请码可以重复使用的
QUiGThJ7VJ4N15DPe3XdYXb3Nl184hjw
