### ISSUE TITLE
有人知道现在 Express VPN 好用吗

### ISSUE THREAD

**Issue by lysidney** [getlantern/forum#8802]
如题，想买一个月 express 解急之用，但不知道这个时期它有事儿没，据说这是最好的 VPN。

**Comment by Uer1900** [comment]
价格太贵了，自己买个搬瓦工花半小时搭建一下好了。搬瓦工一个月一个月买，万一中途被禁，你还可以无条件退款。
[官网地址](https://bwh1.net/aff.php?aff=24912)
[教程链接](https://www.tbreak.top/kda/56/)

**Comment by wtm92** [comment]
好用 我用着呢 express 美国节点不能访问国内网站 比较蛋疼

**Comment by Lvhui233** [comment]
好用 但是有点贵 ssr自己搭一个比这个便宜点

**Comment by songokudeen** [comment]
ExpressVPN吊打lantern. 我这里用UDP protocol, 连接Taiwan, LA, Japan, HK的节点，宽带有多快，翻墙就有多快。就是贵很多，我买的15个月的，相当于每月6.67美元。
通过这个链接买ExpressVPN，咱俩各会多加一个月的时间：https://www.expressrefer.com/refer-friend?referrer_id=14564536&utm_campaign=referrals&utm_medium=copy_link&utm_source=referral_dashboard
