### ISSUE TITLE
哪位亲能告訴我灯是怎么了？

### ISSUE THREAD

**Issue by chengski** [getlantern/forum#8808]
最近两天上灯查资料，连网两秒钟，断网两小时。我要查的资料，搁置快两天了……请亲们告诉我为什么？我猜了如下三个原因，烦请亲们告知一下，省得我老上被虐……
1.因为某会，所以暂时关闭？
2.灯已经彻底被关闭？
3.需要升级灯？

**Comment by qq735100242** [comment]
根据去年十月的情况来看 应该会有一段时间用不了 最终会解决 这段时间我建议你可以先尝试一下别的科学上网方式。

**Comment by yuanyuntian** [comment]
个别地区有问题，有段时间，我也是！耐心等吧

**Comment by yls133** [comment]
可以先用ExpressVPN，可以买一个月，一个月之内还可以全额退款https://www.expressrefer.com/refer-friend?referrer_id=14515694&utm_campaign=referrals&utm_medium=copy_link&utm_source=referral_dashboard

**Comment by yls133** [comment]
![qq 20180315210222](https://user-images.githubusercontent.com/33277029/37464744-40c66b78-2894-11e8-8bc1-67a412afe3bb.jpg)

**Comment by xebecy** [comment]
到现在官方还没给答复，我们像你一样只能猜测

**Comment by userfirstone** [comment]
快递都不能寄，你还要翻—   过分了吧，特殊时期老实点

**Comment by KirnMeng** [comment]
自己租服务器搭梯子吧，一年20美金，蓝灯用的难受。

**Comment by aotian16** [comment]
@KirnMeng  什么服务器啊，这么便宜

**Comment by android1122** [comment]
自建搬瓦工ssr，有合租的没？

**Comment by sblig** [comment]
http://27yun.vip/aff.php?aff=55
偶然遇见，挺方便的
