### ISSUE TITLE
7.30买的 现在已经不行

### ISSUE THREAD

**Issue by lkchill** [getlantern/forum#881]
如题

**Comment by lkchill** [comment]
昨晚买了 感觉还可以 很快 没想到 今天已经不行。老实说180支持你们开发我是很赞成的，但是这个效果 我是不是要把这年的体验完，你们才完善，或者被禁止？哎，多失望的一次交易

**Comment by lkchill** [comment]
对了 这个对街霸5的链接登陆有帮助不

**Comment by candyhenry** [comment]
这么坑爹，我今天买了两年

**Comment by p3rcya** [comment]
@lkchill 请问具体是什么问题？请提供截图并请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 ，方便我们调查，谢谢

**Comment by lkchill** [comment]
具体啊 就好像开了之后一些国内视频站慢 然偶youtube也慢 （没有全局）
还有就是我玩街霸，要关了才能连上，（昨晚还可以连而且比平时快）今天就开了就连不上，错误代码1000a（看不懂）

**Comment by lkchill** [comment]
又有新问题了 ，我给我朋友试用，他觉得不错 他买了现在他怎么退我那个号

**Comment by p3rcya** [comment]
去蓝灯安装目录吧所有文件都删除掉

**Comment by lkchill** [comment]
哎，我重装之后怎么重新授权我的pc

**Comment by p3rcya** [comment]
用email登陆不行么？

**Comment by lkchill** [comment]
我根本没有找到登陆的位置

**Comment by lkchill** [comment]
他只叫我选择免费版和付费

**Comment by lkchill** [comment]
按了登陆只出现验证码 叫我去验证

**Comment by lkchill** [comment]
还没有解决吗。。。

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
