### ISSUE TITLE
VPN搭建教程推荐 | 30分钟即可搞定，附详细图文教程

### ISSUE THREAD

**Issue by ghost** [getlantern/forum#8816]
市面上大多数VPN都是基于Shadowsocks的，需要填入IP地址、密码、端口、选择加密方式。而付费的缺点是：
1. 价格昂贵
2. 容易被封（卖家跑路）
3. 隐私无保证

而实际上自己购买VPS，然后根据教程搭建VPN是非常容易的事，普通人一般半小时左右肯定能搞定。搬瓦工是美国老牌VPS供应商，最便宜套餐19.99美金一年（经常缺货），折后相当于120人民币一年，足够满足1～3个人日常使用。

如果有需要，可以找2个朋友合买，非常划算：

1. ### [官网连接](https://bwh1.net/aff.php?aff=24912)
2. ### [教程链接](http://www.vpsintro.com/main/bandwagonhost/)

**Comment by hallochina** [comment]
能不折腾，还是别折腾了，走付费vpn吧
https://vpnchina.zdhweb.com/p/vpn-china.html
你可以根据自己的偏好选择注册所有推荐的vpn，然后根据使用效果，哪个好用就付款哪个。
