### ISSUE TITLE
求助，无法收到邮箱登录码

### ISSUE THREAD

**Issue by pikachuusama** [getlantern/forum#8835]
蓝灯专业版账号Email：781510334@qq.com  ，管理员看到请帮忙解决一下，急~！

**Comment by lybPigff** [comment]
打开蓝灯管理，在账户管理里去掉一个，就能收到邮箱了。

**Comment by pikachuusama** [comment]
@lybPigff 我列表只有一个设备

**Comment by Ghostwithout** [comment]
你好，
能截屏看下吗？
如果授权设备可以用如下方法：
－在lantern界面左边菜单点击“授权设备使用专业版”，在里面输入购买时的邮箱，激活码就会发到你的邮箱，然后输入激活码即可； 
－在新设备选择“授权设备使用专业版”，该界面会收到验证码，然后请到专业版设备输入验证码。谢谢！ @pikachuusama

**Comment by pikachuusama** [comment]
@Ghostwithout 
![qq 20180316193638](https://user-images.githubusercontent.com/37440215/37520884-b35c3094-2959-11e8-89d8-7ac1fe940ce9.png)
![_20180316203421](https://user-images.githubusercontent.com/37440215/37520897-bbe6bcde-2959-11e8-8e25-6657809b8774.jpg)
你好，等了好久了，就是收不到，邮箱也自查过了，没有设置黑名单，没有拦截记录，垃圾箱里也没有。

**Comment by demiarc** [comment]
@Ghostwithout 大约1小时前在电脑端重装了一下最新版，同样是QQ邮箱，遇到和LZ完全相同的问题——个人强烈怀疑是QQ邮箱过滤方面的问题，但我也没办法就这个问题去问腾讯客服……

**Comment by pikachuusama** [comment]
@Ghostwithout 刚才又试了，终于收到了，谢谢！

**Comment by pikachuusama** [comment]
@demiarc 我刚才又试了一遍，终于收到了，兄弟
