### ISSUE TITLE
macOS Beta版 3.0.7无法正常工作

### ISSUE THREAD

**Issue by longfangsong** [getlantern/forum#885]
我更新了macOS Sierra之后，使用了官网上下载的最新版本lantern3.0.7，发现无法浏览任何网页（Safari和Chrome都一样）

**Comment by xieyingli** [comment]
这个问题已经好久好久了。。。

**Comment by longfangsong** [comment]
现在下载了3.0.2版本，工作正常

**Comment by longfangsong** [comment]
重启Lantern又能翻了，过了一会又不行了……
不太稳定啊

**Comment by Hwatu** [comment]
this is the question
