### ISSUE TITLE
还在为VPN不能稳定快速上网而头疼和担心吗？现在免费SSR注册就送10G流量，还有免费现金9元流量卷到账户可以使用，速度快，节点多

### ISSUE THREAD

**Issue by sangxiuzhong** [getlantern/forum#8859]
请在发帖前先按照蓝灯无法使用的解决办法 https://github.com/getlantern/forum/issues/1902 自行解决。自行解决问题通常只需要几十分钟。管理员调查解决问题需要几天至几周。请立即访问https://github.com/getlantern/forum/issues/1902 瞬间解决98%的问题

为了能在最快的时间内解决大家使用蓝灯遇到的问题，请各位用户严格按照发帖格式提交问题。

## 发帖格式
遇到的问题：请详细描述遇到的问题。如果描述不仔细，将无法调查

蓝灯专业版账号Email:  请提供登陆蓝灯专业版的email，免费版不提供技术支持。

应用内报告问题的时间:  请根据 https://github.com/getlantern/forum/issues/1840 在应用内上报问题，请填写专业版的email。请在帖子里注明报告的时间。

截图: 请提供有关问题的截图。 请把图片拖拽到这里。

----
邀请码在本论坛请以签名形式发布或发到其他论坛。具体见 https://github.com/getlantern/forum/issues/3773

**Comment by sangxiuzhong** [comment]
网址是http://anythink.info/user
每天可以签到送300-500M流量，节点多且不同的节点所消耗流量比例不同最低0.5比1也就是1M的流量只消耗你个人所拥有当前流量的0.5划算的很，总之绝对比一般的VPN稳定快速，让你不再为网速不稳，担心不能科学上网而头疼。以下为部分内容预览，没有邀请码注册不了，数量有限，先到先得
亲测可用
bQwzEMdD0Q5xVQus1ZJPUluEgIiLD92H
VfZBA1O68lgB8hWmHoZWE54g4RcAhmfu
RdYbHZYhn8QJZDT29mNSJF6tFXNSALhG
z5L8ry5bdylZsuciZzo6ze8CLvGvNZXu
loo81eYaHRanMNsL7gHzIBmxwo4FCe5K
RBSlsdBCFNiia1pN8YC0Hg67hv53dtNA
xl9DTreuhV0GJXoW8tGQIELnoxnREsc3
kC8HDjwexzG6KfB02qa1hFD86GfZPJuY
--




loo81eYaHRanMNsL7gHzIBmxwo4FCe5K
--

**Comment by sangxiuzhong** [comment]
NcNbYRCX1l4PvDtNV3JTE2KTmCcBg8NU
q79JMv70ntnfh5DSSaiDpTuzTDTIprxz
olrECXl0yvl4CyLrtja8tPW9JccsSlQv
a23oiTh0g4VI2TyfTaeHuuvpXJ82ZJz6
--

**Comment by sangxiuzhong** [comment]
有问题请咨询Q3023958291

**Comment by 1225702013** [comment]
邀请码
1mfECiEXqWjOqu4TRZfzzgSj9dXzG823
8nQMdZJmnwtvbfzprWrTo8cTQdma9w0S
T9PvRSVC89uDuN2cmTfx0ssJTaCkDA1J

**Comment by lzjun812** [comment]
不够的这里还有
Lw7NO3u4du6CZpS6Ur9MFx4ai0GTHDv5 | 可用
11003 | OauSs8LyEfvuS04UGlrygaCY1fpqdlyF | 可用
11014 | 946kWWMt0oQj5jRPhXKtzwlp1lOBuEp1 | 可用
11060 | cFZZ1u6B9Aw5kMRVp3brPp2U2EPecuV8 | 可用
11019 | fd1Gm9s4aMH99EvlHbJ2TnwmIL1JDKyv | 可用
11015 | gXnWNxtta9m16EtToSLBbD4CngVTJfur | 可用
11007 | UeIQkubBYTq1d591Px4jB18LgqqgaMfM | 可用
11016 | cA4mhXyvgYWJrfrYjVNMq8cT9FxVaWNZ | 可用
11004 | eIv8BVB1UuQYd30NmY7PGKOU78GGyLN2 | 可用
11008 | 1S3m8MVIEeHs7PX1PiXtZWm1EIWe6C9X | 可用
11017 | 68VM7pyV6ivY2GTVHzbcQewO93KYQGiU | 可用
11010 | 419RugIs1Hxj9T9eXFL1ZDeKH8OVxhI9 | 可用
11009 | RCrfQKzB80fDHEYUN3zWvzjJ3XcF2hnF | 可用
11018 | 0tek8xJe3ULlR0aHMiifLtivaOdE48WI | 可用
11012 | bfvlcVM3it3QZNyngIzRGIs5KkH7CNfv | 可用
11012 | bfvlcVM3it3QZNyngIzRGIs5KkH7CNfv | 可用
11029 | k2lU0AmDThEPrUVn6BX4AhQDelgISwZh | 可用
11006 | Lw7NO3u4du6CZpS6Ur9MFx4ai0GTHDv5 | 可用
11030 | cz4LJRI3uYLqZtkVF6zQfcmvy89Oqvzv | 可用
11007 | UeIQkubBYTq1d591Px4jB18LgqqgaMfM | 可用
11015 | gXnWNxtta9m16EtToSLBbD4CngVTJfur | 可用
11025 | kDkpn6usKtgg3zcnP5aI1OfkAofnciLu | 可用
11008 | 1S3m8MVIEeHs7PX1PiXtZWm1EIWe6C9X | 可用
11019 | fd1Gm9s4aMH99EvlHbJ2TnwmIL1JDKyv | 可用
11014 | 946kWWMt0oQj5jRPhXKtzwlp1lOBuEp1 | 可用
11009 | RCrfQKzB80fDHEYUN3zWvzjJ3XcF2hnF | 可用
11023 | g0YYrFVtWdWSqPiGINWD00JBKwOmpgYY | 可用
11027 | fIU3F6f9N9jrSJ1rQYU3e8y264Ubfdbg | 可用
11022 | O6mCKwOb4eCeN5Hmz4AN2eSo0L0sC9Rs | 可用
11034 | qjWn1UCEgc1kr6n3DTCAobzx3pikkcBo | 可用
11009 | RCrfQKzB80fDHEYUN3zWvzjJ3XcF2hnF | 可用
11053 | 0xiOPZQSO6Enrf5nvfbLHII1Ags43APE | 可用
11026 | I7oxbXipU7bIkCA5LN1L6CpVgNE8ucms | 可用
11046 | 3zHNHRP7gmuEtXf2GIrCViVvk58X3PPl | 可用
11050 | 52vaE3vPU7ts79GFeGvIWjS5wBW3Phxh | 可用
11045 | BoZbUrjfASxlDNfVlDukYOmlTbc63ya1 | 可用
11042 | UwRSSbSKGH4NnlJuNRTb7TjgNXy6QWpc | 可用
11040 | kxZjTzVO1unPJfdsAZkEybNhrETGJ2cP | 可用
11037 | OHqjWCw1P4atYl4VfPKBk4xufLGfOVLM | 可用
11006 | Lw7NO3u4du6CZpS6Ur9MFx4ai0GTHDv5 | 可用
11028 | 9fx6O8YTvvLNLYhgpcTqlPWCcuKFnWoI | 可用
11022 | O6mCKwOb4eCeN5Hmz4AN2eSo0L0sC9Rs | 可用
11019 | fd1Gm9s4aMH99EvlHbJ2TnwmIL1JDKyv | 可用
11052 | DM4D4XabDDJcxTfHcb9PV4gxITMiGzHR | 可用
11057 | yUOBsJqtlnj37ZNWVGCKASinR5VxynwU | 可用

**Comment by Giantdicky** [comment]
sOO639KoQQ3hWxlJiMunwbetz8kjogke
sqBw4jq8RGB41rZgX9c6nzu9AbNAqJr1
yxPXFSXdH6gqIQOUGBjaZ8GgNIJJS0Qp
5Vi8WB3tsg4to7uzq24D2NQHPtOziyWz
IG2OfFaK4CVbCWOnSeNNZSeZETHN00Nw
Xv3JKALRczl7o16pRQS6Ik83xYyHs8Oj
6azSFLcwudhC57oAbgegO6NowFYPDB6J
QPLBqcFcyLaxPhlN1Gr38s3YMdDprvSs

**Comment by Giantdicky** [comment]
24369	sOO639KoQQ3hWxlJiMunwbetz8kjogke	可用
24366	sqBw4jq8RGB41rZgX9c6nzu9AbNAqJr1	可用
24374	yxPXFSXdH6gqIQOUGBjaZ8GgNIJJS0Qp	可用
24362	5Vi8WB3tsg4to7uzq24D2NQHPtOziyWz	可用
24371	IG2OfFaK4CVbCWOnSeNNZSeZETHN00Nw	可用
24365	Xv3JKALRczl7o16pRQS6Ik83xYyHs8Oj	可用
24373	6azSFLcwudhC57oAbgegO6NowFYPDB6J	可用
24367	QPLBqcFcyLaxPhlN1Gr38s3YMdDprvSs	可用
24375	l8Jls2QDVum8qSdtK2SAraMkjCEjuhKW	可用
24372	ILFtxjnIkYjvdJSXy7hl4t0caPyHscbe	可用
24368	8xej2YWYRzk9UdjCrlkpqDB96o86jael	可用
24370	Ujl5tqzJFaqAkErK4PS0iuHgcNd9SQze	可用
24364	73Gu0MoaAYh1yaxFtyRtz3mYmg71pqBe	可用
24363	9sbd2YIx6SQIfryWNUkpU8rki8GcVET6	可用
24339	QH9xgPQ9dzl86S9sl5ldSh2riKYKlRd5	可用

**Comment by Giantdicky** [comment]
24354	m8xPqmvzEmDiGDrb4y5xnnjtsNtbQfwz	可用
24348	KrREgrqMoksUzTQPkSLroFZv5tlIJhPF	可用
24355	a8enk2ewaITrlmM4ObMD18Or7ca8MO27	可用
24357	PuqRWvbESpEs1JsuWNAv9QMcNMXHB8e7	可用
24347	QuNfsMJddObMQN4DRXOZYD1t4jBCZFmQ	可用
24343	VZRFuQDDMm77plgJOp0FNe0N17NSXiEw	可用
24350	qlgN6ceiojbaUv8yVZ5doKPD2XGgYKLK	可用
24349	TQ9WWwYFzdkb1oEzyv1Nfe7ojI9Zrv2h	可用
24339	QH9xgPQ9dzl86S9sl5ldSh2riKYKlRd5	可用
24345	LsBX6RC6LAl0CwbzQ3ucXGGK2NzRsfic	可用
24352	43ut8BQI5mfXM4H2p51aFAbsW51qthXo	可用
24344	w1xmQcUuiYfP48cxzHhFXBnUVkKpqvkI	可用
24356	FZ1iY2Ax89ZRmm08uXYLwQHxPWlNzeCi	可用
24353	8O19TUPEQ2bDMe1MnJBoZT1Asv29Ly9r	可用
24346	t683Jml6l0daxah9XBAbjox5QMIgjAtX	可用

**Comment by Giantdicky** [comment]
24328	3mFRdp6MwUat6FJE2PjpzAuIl3x1JAu9	可用
24346	t683Jml6l0daxah9XBAbjox5QMIgjAtX	可用
24331	a04AMPwWuXPXBx2p8fIy9vEc7d6U1U66	可用
24339	QH9xgPQ9dzl86S9sl5ldSh2riKYKlRd5	可用
24330	oYq0Vb6v4X10z2taE38nTlETx0IOY9cb	可用
24333	ulVuklDprGvX7XOESqxnIqGzAEBYP5lj	可用
24334	mQhQrJNC4GJz0exWlmB8pzYKIehyY5R5	可用
24361	i8oFQGrIDcmG32XlpKUXLIfGVo0GY6GN	可用
24357	PuqRWvbESpEs1JsuWNAv9QMcNMXHB8e7	可用
24354	m8xPqmvzEmDiGDrb4y5xnnjtsNtbQfwz	可用
24347	QuNfsMJddObMQN4DRXOZYD1t4jBCZFmQ	可用
24343	VZRFuQDDMm77plgJOp0FNe0N17NSXiEw	可用
24353	8O19TUPEQ2bDMe1MnJBoZT1Asv29Ly9r	可用
24337	FxDK7IynIN0yXI8jRZxnRc5MuGgPU31x	可用
24336	idNuyWOdcgFunfQJK7YCuysYMnRmo3Pj	可用
