### ISSUE TITLE
新科学上网

### ISSUE THREAD

**Issue by Holygreatpower** [getlantern/forum#8868]
网址是# http://anythink.info/user
每天可以签到送300-500M流量，节点多且不同的节点所消耗流量比例不同最低0.5比1也就是1M的流量只消耗你个人所拥有当前流量的0.5划算的很，总之绝对比一般的VPN稳定快速，让你不再为网速不稳，担心不能科学上网而头疼。以下为部分内容预览，没有邀请码注册不了，数量有限，先到先得
亲测可用（油管1080p没毛病）

24317 | 132FIVKlD16qABTHOE5yStb1NnmuRdiG | 可用
24318 | Znx8LXH9pMcvkHiNm819vaGegAeZldMJ | 可用
24319 | fC8Co7yZJSCd1tr7CdCNKvI9RfcX2R6e | 可用
24320 | GfBmDqCS0Ege97f7Cx0x4a4KKG0C18U7 | 可用
24321 | kftphyMbpmwXY4NiCirPVXeU8glM3r9V | 可用
24322 | qebNqCKXw90CEo5MFCX2rfnx3vnFLxXU | 可用
24323 | RFKy0VpDSwiIvn8hcVCWCLPjbfNU7EOT | 可用
24324 | p9MZAfWU1FKXAKMVHkC1VKe6XSz9FxDH | 可用
24325 | jGxlA6TctJx3VqitImvFrRFIPWMkvBD9 | 可用
24326 | FPbY1ZhnfanSfa8PgM3VK88mma1yIHW0 | 可用
24327 | wYxlplf0J3rNhSvW1H2hR5k9MoYxWAVh | 可用
24306 | TE7DEuoEsJcbZmBdJuKcmOgqjhYV6Fsz | 可用
24305 | PMsAnr6sP7rLdHymzx8kQUhFdJiCNjaG | 可用
24304 | ArAgcA1IxZ61IxWzX8AVJRk3z3orUWGP | 可用
24303 | klvb8lDKTqDAgdcy9bgIpmBjX7yVtuwa | 可用

24319 | fC8Co7yZJSCd1tr7CdCNKvI9RfcX2R6e | 可用
24318 | Znx8LXH9pMcvkHiNm819vaGegAeZldMJ | 可用
24317 | 132FIVKlD16qABTHOE5yStb1NnmuRdiG | 可用
24311 | tPI0xjSLgf6ME22yog92xhxuHtSKkGTY | 可用
24312 | P5q8ptaabZ959VHG5P307d3i72MsOvde | 可用
24313 | 3Q59ohQtv8uI11h7aXho57F1bfTRHzvh | 可用
24314 | IqtS9vv930qacvVijbLPXYjv841Odwmh | 可用
24315 | 8228khWwdjsoQbEhysUpdZALdg7GOPYJ | 可用
24316 | HF2OvM45q4ut1Px4SX26PLXT3kSCaIOr | 可用
24287 | TRLPLywawKjdKEOKMaANK6Nw8kryzTrQ | 可用
24290 | DKI7IkXa4esDyhiWIgM2J7Vch9IDrAdG | 可用
24289 | quld3nmrYh8FuUfBT7278DtsvMEtaaIf | 可用
24288 | vnbOQFWfeqCOjQL0rcMxaPuGnHHsQ4lw | 可用
24282 | pYkfYasmmQU44HSdabTJqrT20sa06qDI | 可用
24281 | qa0z8U11agie6zd9DbaflsZGdkN0fj37 | 可用

24282 | pYkfYasmmQU44HSdabTJqrT20sa06qDI | 可用
24283 | hWeMPBoBtNtN8RVsA3Fqyqs5SC2BOAvu | 可用
24284 | 7sEyJnP3GCr6a7YuZjAQCFwm2OcYqu5C | 可用
24285 | olRVWdqAF31wvpj6idRjw5iItjOl8wgG | 可用
24286 | dOTeTPodxdtbWSmDUXuwbELyVbh1MPOd | 可用
24287 | TRLPLywawKjdKEOKMaANK6Nw8kryzTrQ | 可用
24288 | vnbOQFWfeqCOjQL0rcMxaPuGnHHsQ4lw | 可用
24289 | quld3nmrYh8FuUfBT7278DtsvMEtaaIf | 可用
24290 | DKI7IkXa4esDyhiWIgM2J7Vch9IDrAdG | 可用
24291 | kR24dE1xjEaH131VOqoqTjFGChmb4J8I | 可用

**Comment by lzjun812** [comment]
Lw7NO3u4du6CZpS6Ur9MFx4ai0GTHDv5 | 可用
11003 | OauSs8LyEfvuS04UGlrygaCY1fpqdlyF | 可用
11014 | 946kWWMt0oQj5jRPhXKtzwlp1lOBuEp1 | 可用
11060 | cFZZ1u6B9Aw5kMRVp3brPp2U2EPecuV8 | 可用
11019 | fd1Gm9s4aMH99EvlHbJ2TnwmIL1JDKyv | 可用
11015 | gXnWNxtta9m16EtToSLBbD4CngVTJfur | 可用
11007 | UeIQkubBYTq1d591Px4jB18LgqqgaMfM | 可用
11016 | cA4mhXyvgYWJrfrYjVNMq8cT9FxVaWNZ | 可用
11004 | eIv8BVB1UuQYd30NmY7PGKOU78GGyLN2 | 可用
11008 | 1S3m8MVIEeHs7PX1PiXtZWm1EIWe6C9X | 可用
11017 | 68VM7pyV6ivY2GTVHzbcQewO93KYQGiU | 可用
11010 | 419RugIs1Hxj9T9eXFL1ZDeKH8OVxhI9 | 可用
11009 | RCrfQKzB80fDHEYUN3zWvzjJ3XcF2hnF | 可用
11018 | 0tek8xJe3ULlR0aHMiifLtivaOdE48WI | 可用
11012 | bfvlcVM3it3QZNyngIzRGIs5KkH7CNfv | 可用
11012 | bfvlcVM3it3QZNyngIzRGIs5KkH7CNfv | 可用
11029 | k2lU0AmDThEPrUVn6BX4AhQDelgISwZh | 可用
11006 | Lw7NO3u4du6CZpS6Ur9MFx4ai0GTHDv5 | 可用
11030 | cz4LJRI3uYLqZtkVF6zQfcmvy89Oqvzv | 可用
11007 | UeIQkubBYTq1d591Px4jB18LgqqgaMfM | 可用
11015 | gXnWNxtta9m16EtToSLBbD4CngVTJfur | 可用
11025 | kDkpn6usKtgg3zcnP5aI1OfkAofnciLu | 可用
11008 | 1S3m8MVIEeHs7PX1PiXtZWm1EIWe6C9X | 可用
11019 | fd1Gm9s4aMH99EvlHbJ2TnwmIL1JDKyv | 可用
11014 | 946kWWMt0oQj5jRPhXKtzwlp1lOBuEp1 | 可用
11009 | RCrfQKzB80fDHEYUN3zWvzjJ3XcF2hnF | 可用
11023 | g0YYrFVtWdWSqPiGINWD00JBKwOmpgYY | 可用
11027 | fIU3F6f9N9jrSJ1rQYU3e8y264Ubfdbg | 可用
11022 | O6mCKwOb4eCeN5Hmz4AN2eSo0L0sC9Rs | 可用
11034 | qjWn1UCEgc1kr6n3DTCAobzx3pikkcBo | 可用
11009 | RCrfQKzB80fDHEYUN3zWvzjJ3XcF2hnF | 可用
11053 | 0xiOPZQSO6Enrf5nvfbLHII1Ags43APE | 可用
11026 | I7oxbXipU7bIkCA5LN1L6CpVgNE8ucms | 可用
11046 | 3zHNHRP7gmuEtXf2GIrCViVvk58X3PPl | 可用
11050 | 52vaE3vPU7ts79GFeGvIWjS5wBW3Phxh | 可用
11045 | BoZbUrjfASxlDNfVlDukYOmlTbc63ya1 | 可用
11042 | UwRSSbSKGH4NnlJuNRTb7TjgNXy6QWpc | 可用
11040 | kxZjTzVO1unPJfdsAZkEybNhrETGJ2cP | 可用
11037 | OHqjWCw1P4atYl4VfPKBk4xufLGfOVLM | 可用
11006 | Lw7NO3u4du6CZpS6Ur9MFx4ai0GTHDv5 | 可用
11028 | 9fx6O8YTvvLNLYhgpcTqlPWCcuKFnWoI | 可用
11022 | O6mCKwOb4eCeN5Hmz4AN2eSo0L0sC9Rs | 可用
11019 | fd1Gm9s4aMH99EvlHbJ2TnwmIL1JDKyv | 可用
11052 | DM4D4XabDDJcxTfHcb9PV4gxITMiGzHR | 可用
11057 | yUOBsJqtlnj37ZNWVGCKASinR5VxynwU | 可用
