### ISSUE TITLE
蓝灯的 4.5.X  百度就可以找到。 不是在这里提供的那个网址。

### ISSUE THREAD

**Issue by Itroads** [getlantern/forum#8872]
这点事，也不知道为什么。 在这里问，从来没人回答。 一个开源的东西，至于这样么。

**Comment by wuhan258827** [comment]
除了这里的下载，其他的都是假的千万别安装

**Comment by wuhan258827** [comment]
除了这里的下载，其他的都是假的千万别安装

**Comment by WhoCareJY** [comment]
额。。。 可是已经装上了。 怎么办啊。

**Comment by WhoCareJY** [comment]
那也没人出来声明一下啊。 官方说一下，4.5版本是不存在的。

**Comment by Ghostwithout** [comment]
你好，请在https://github.com/getlantern/forum/ 下载最新版本使用。谢谢！ @WhoCareJY
