### ISSUE TITLE
自助搭建SS服务器 | 解决上网问题

### ISSUE THREAD

**Issue by Lemoreright** [getlantern/forum#8875]
市面上大多数VPN都是基于Shadowsocks的，需要填入IP地址、密码、端口、选择加密方式。而付费的缺点是：
1. 价格昂贵
2. 容易被封（卖家跑路）
3. 隐私无保证

而实际上自己购买VPS，然后根据教程搭建VPN是非常容易的事，普通人一般半小时左右肯定能搞定。搬瓦工是美国老牌VPS供应商，最便宜套餐19.99美金一年（经常缺货），折后相当于120人民币一年，足够满足1～3个人日常使用。

如果有需要，可以找2个朋友合买，非常划算：

1. ### [官网连接](https://bwh1.net/aff.php?aff=24912)
2. ### [教程链接](http://www.vpsintro.com/main/bandwagonhost/)
3. ### [多端口搭建教程](http://blog.anning.tv/14.html)

----
邀请码在本论坛请以签名形式发布或发到其他论坛。具体见 https://github.com/getlantern/forum/issues/3773

**Comment by 4044ever** [comment]
kick the spammers out!

**Comment by sousuo28** [comment]
有啥意义，现在电信运营商都能查出用户是否使用这些来

**Comment by w452187971** [comment]
买了个https://mewume.com/ 5元一个月~还算稳定40G流量够用了
20个邀请码 用掉一个就失效一个
4iaPgJ6L0cYzYZNx7crH1X0Wr6HwnZyn
IHfjDp3Fab0ymh2HZ14gpDrE6LF0eE83
msOEhK82cpLuf6B1opTCGsSn9mREG62G
onMKmqoyv6HkIiJZ27anFbEpnnN8xTwD
gpxf8RjVE2XfjuOREoLJ7Vu0qJh6bEZD
aqlioaa62qDp4qe8QxjgeWcgJd46nb5Z
jXEvqKuCr5KcYla9QpVMXmNzrs8jLZER
BAEmKC5RLdYM2BaWmmcilgSwkHeTwESV
jNS5OyYXa9hui5B8YkTnocMLGOdvbn8C
50Dx1tlNc43RRAkgluHy0YGY7hOYdqEP
x0SakRzJrnkkkfP1IIdmMp1mgZXGC8pU
Ilr2XbsG2FZmCPsE78TlWzd6I6ZuAuPU
ybY76y9EQYlj923TkpdoadfhOAekOU82
ZW89PDzy7r6FtHu4G6nfWtzveYObny99
twGRNxqG22raeHqaWAJ8UF8K9df7lVpC
CNBNpMnlxvW2AGG5OLRroDIOPHWF0Pmg
qSH7riWmD9m3kAl4WdzoSHtNZSVQmlnT
Pd5r57LX0Ymq8qF5EvMJvLhSh2VlxS5T
9vGuVo4GQFriRbXXgoUgBBzHzj7LN47m
Z0r5NryhDB9q9XjehJnzO31oJqeelnKj
