### ISSUE TITLE
蓝灯又可以用咯。输入我的邀请码 XZPRJX 来获得三个月的蓝灯专业版！

### ISSUE THREAD

**Issue by shenshizhong** [getlantern/forum#8904]
等了几天，现在蓝灯又可以happy的用咯。输入我的邀请码 XZPRJX 来获得三个月的蓝灯专业版！

**Comment by lanlongning** [comment]
输入我的邀请码 **J9B879** 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
邀请码有效期3年半，欢迎使用

**Comment by lanlongning** [comment]
输入我的邀请码 **J9B879** 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
邀请码有效期3年半，欢迎使用

**Comment by Foskill** [comment]
?
