### ISSUE TITLE
【输入我的邀请码 X7T5FW 来获得三个月的蓝灯专业版】授权其他电脑几乎无效过了好几个小时了。

### ISSUE THREAD

**Issue by cnjelly** [getlantern/forum#9000]
专业版用户：hxwebs@vip.qq.com
授权其他电脑几乎无效过了好几个小时了。目前都是最新版本2018317windows版本，授权是mac系统的最新版本

----
输入我的邀请码 X7T5FW 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by chgzjwf** [comment]
上午一直不行，下午3点多可以了。你可以再尝试一下！
不过我不知道是不是我用了另一个办法，最新版一直不行，
我卸装了最新版，安装了4.4.1的旧版本，然后手机端授权，就可以了。
