### ISSUE TITLE
手机版使用一段时间后连接中断

### ISSUE THREAD

**Issue by EdwardAutumn** [getlantern/forum#902]
貌似这个问题存在很久了，使用一段时间后连接会中断，重启应用后又会恢复，日志已发送。

**Comment by helloLC** [comment]
你手机屏幕熄屏没有？
如果关闭了屏幕，而且左上角的“钥匙”的图标不见了，那就是lantern进程被杀掉了，或者崩溃了。
如果是突然不能用，那么就可以连接被重置。

**Comment by EdwardAutumn** [comment]
@helloLC 并没有，就是突然连不上去了

**Comment by helloLC** [comment]
@EdwardAutumn 你确定左上角的“钥匙”图标还在？下拉状态栏，有没有“lantern vpn”已启动？
如果两点都不存在，那么就APP崩溃了。如果lantern一直保持开启，点击“管理网络”没有接受到数据，那么就是连接被GFW重置，或者代理服务器出问题。

**Comment by EdwardAutumn** [comment]
@helloLC 百分百确定。我是个程序员，如果是这么低级的问题我就不会上来问

**Comment by helloLC** [comment]
@EdwardAutumn 我只说一下，我在PC上遇到过lantern自己代理服务器挂过，MTR可以到机房。
lantern 3.0貌似特别喜欢崩溃。你试试看2.2.5以下版本。还是一样的解决结果那只能说明要么被GFW重置，要么代理服务器问题。

**Comment by p3rcya** [comment]
这个 @orbancanon 你看看
