### ISSUE TITLE
mac 4.5.7专业班版无法翻墙

### ISSUE THREAD

**Issue by abc19842008** [getlantern/forum#9030]
遇到的问题：使用的是专业版,下载了最新的4.5.7版本,无法翻墙,偶尔能打开youtube和google

蓝灯专业版账号Email: fumin1984@126.com

**Comment by zwtall** [comment]
最近敏感时期，熬过去就好了

**Comment by nabu888** [comment]
疯了买lantern

**Comment by abc19842008** [comment]
现在可以了,感谢支持!

**Comment by BLF123** [comment]
现在可以了吗？
