### ISSUE TITLE
浙江移动宽带开蓝灯翻不了

### ISSUE THREAD

**Issue by shanligang1017** [getlantern/forum#9061]
我浙江移动宽带别的vpn可以，蓝灯不行，但是切换到广电宽带蓝灯又是可以的，有没有浙江移动和我一样情况的，希望管理查找原因解决

**Comment by lemonskkyt** [comment]
一样，完全不能用，只能龟速 赛风 暂时对付

**Comment by zdfmaik** [comment]
我已经放弃蓝灯了。改用17Yun 
https://27yun.vip
自选线路 视频秒开，手机pc都能用，就是小贵。。最重要的是有客服😂。
