### ISSUE TITLE
专业版续期后因找不回邮箱无法使用，请帮忙更改邮箱

### ISSUE THREAD

**Issue by liuximing2016** [getlantern/forum#9108]
原邮箱 liuximing_2016@qq.com
需要更改为邮箱 liuximing2016@qq.com
续期交易截图：
![image](https://user-images.githubusercontent.com/23612674/37873824-89420c3a-3056-11e8-89d8-8b7cf75b7772.png)

**Comment by Ghostwithout** [comment]
你好，已更新，请核实。谢谢！ @liuximing2016

**Comment by liuximing2016** [comment]
@Ghostwithout 核实已成功，谢谢！
