### ISSUE TITLE
建议尽快更新到Lantern4.5.7

### ISSUE THREAD

**Issue by Ghostwithout** [getlantern/forum#9112]
各位Lantern童鞋，

目前的Lantern最新版本为4.5.7，自动更新已经打开。请在Lantern界面左下角查看是否为最新版，如果没有，建议重启Lantern或电脑，以完成自动更新。
如果现有版本过旧，无法自动获取新版本，请到https://github.com/getlantern/forum/issues/833 下载。
谢谢大家的支持与理解，我们仍将努力提供快速稳定的服务。

**Comment by weihan0917** [comment]
4.5.7 那么慢，那么卡，什么再更新？

**Comment by DarkGoril0220** [comment]
福建福州地区4.5.7会一直在日本 香港 美国三个地方切换

**Comment by icycheng** [comment]
4.5.7 US HK JP变着切，卡到飞根本没法用

**Comment by ys1989611** [comment]
我这里是上海，已经更新到最新了4.5.7 为什么打开 Lantern 后，状态的图标不显示出来，也连不上！？？？

**Comment by ys1989611** [comment]
刚买了2年的专业版，买完竟然连接不上，我要退钱！！！！

**Comment by coinbebelu** [comment]
看来切换服务器的不是个例,希望蓝灯团队尽快解决

**Comment by ys1989611** [comment]
你们能连上？

**Comment by ys1989611** [comment]
我的一打开蓝灯，状态图示闪一下就没了，根本链接不上。

**Comment by BLAZE-Windy** [comment]
最新的4.5.7并没什么用，能上，但是依旧卡得飞起。

**Comment by BooleLean** [comment]
能用，速度还可以，就是不稳定，偶尔软件自动关闭退出

**Comment by handsomebubu** [comment]
新版本还是经常被杀软被杀掉

**Comment by 80068** [comment]
4.5.7已经升级，有时候被阻断，在使用过程中时断时续。而且多是用一会就断，然后彻底连接不了。【天津联通】光线设备是【WO光猫】、另外希望蓝灯组织团队尽快破解【联通WO光猫】设备封锁限制机制。研发全新不受联通光猫设备限制的新蓝灯。2017蓝灯的已经过时了。希望尽快研发该软件的2018新版本。

**Comment by kevinsnake** [comment]
我的一打开蓝灯，状态图示闪一下就没了，根本链接不上。
--

我也遇到同样问题，图标闪了几秒就消失，无法连接。

**Comment by grasscase** [comment]
4.5.4最好用！！！！！！！！！！！

**Comment by amylmy** [comment]
@kevinsnake @ys1989611 这个问题貌似是端口冲突了，我以前也遇到过。
先退出lantern，找到lantern.exe所在的目录，打开settings.yaml 修改下端口，不要冲突就好

**Comment by ys1989611** [comment]
@amylmy 找到文件了，看不懂不知道怎么改啊，讨教，谢谢了。

**Comment by ys1989611** [comment]
@grasscase 4.5.4版本分享下呗。

**Comment by amylmy** [comment]
@ys1989611 

**addr: 127.0.0.1:62365
socksAddr: 127.0.0.1:62364
uiAddr: localhost:62361**
这几行，冒号后面的就是端口，发现新更新的版本我的是52...，我都改成了62...就ok了
应该是52...的已经被占用了。

**Comment by amylmy** [comment]
@ys1989611 
ps:  4.5.4的版本貌似总是断啊，我升到4.5.7就ok了，只是服务器在US的时候会略慢。。。

**Comment by amylmy** [comment]
@ys1989611 你改下试试，每个人电脑不一样，不知道你哪些端口被占用了。

**Comment by ys1989611** [comment]
@amylmy   下边这三个都要改吗？
addr: 127.0.0.1:62222
falsesocksAddr: 127.0.0.1:62223
trueuiAddr: localhost:62219

**Comment by amylmy** [comment]
@ys1989611 
这里面 **addr** 对应的是的HTTP(S)代理服务器的ip和端口
**socksAddr** 对应的SOCKS代理服务器
**uiAddr** 对应启动时候的管理页面

我的管理页面是可以打开的，所以只改了前两个。你先改了试试吧。。。
不行，大不了再改回来啊。。。

**Comment by ys1989611** [comment]
@amylmy 我改了下，不好便。我删除重新装一下看吧，还不好用就是蓝灯的问题。之前也遇到后，后来自己好的。应该是蓝灯的问题。

**Comment by amylmy** [comment]
@ys1989611 嗯 反正我的用着好好的 其他我不管啦~

**Comment by ys1989611** [comment]
@amylmy 你是哪里的朋友？感觉蓝灯好像有些地方的好用，有些地方不好用，我上海电信

**Comment by amylmy** [comment]
坐标武汉，校园网

**Comment by ys1989611** [comment]
@amylmy 
安装完后提示  please allow certimporter.exe to make changes to your system
这啥意思？

**Comment by amylmy** [comment]
你allow就好。。。可以看下其他的 issue...
我并不是客服23333333

**Comment by ys1989611** [comment]
@amylmy 重装好了，不知道还会不会掉。

**Comment by DEADGODImmathplus** [comment]
我遇到了以下问题：
1.电信宽带，lantern4.5.7版本。
2.chrome浏览器，开启蓝灯后，只可以打开一个YouTube视频以及网页内容，但要继续打开第二个YouTube视频，需要重启蓝灯才行，否则，网页会卡在那里，迟迟不跳转。
据说是因为chrome内核使用的是QUIC网络协议，与中国网络不兼容所致。但我关闭该协议后，问题依然存在。
3.切换到Firefox浏览器后，YouTube视频倒是可以连续打开。但是，我不太习惯用这个浏览器。说明，确实是chrome的问题。
4.列为网友，有没有高人，能帮忙解决一下这个问题。

**Comment by jackshi618** [comment]
楼上和我完全一样，视频只能看一段

**Comment by shanligang1017** [comment]
服务器切换来切换去的，根本不能用，US,HK,JP也就JP得可以用，其他几个要嘛比56K拨号还慢，要嘛就是不能用，请问切换的目的何在？？请正面回答

**Comment by jacintoo** [comment]
卡到无法使用…………

**Comment by Panzhipeng1** [comment]
网速还是很慢啊

**Comment by wilon** [comment]
支持！

```diff
+ 输入我的邀请码 YMD8TTG 来获得三个月的蓝灯专业版！
- 输入我的邀请码 YMD8TTG 来获得三个月的蓝灯专业版！
        ```

**Comment by Banana1130** [comment]
4.5.7超级卡啊，3个服务器不断来回切换，只有JP可以用。但一会又变其他两个慢的。

**Comment by didige** [comment]
联网 30 秒,掉网  1 小时 ,,迟迟修复不了,还不给个说法, 有没有投诉的地方,显示已连接,就是上不去,如果能上去卡到爆

**Comment by handsomebubu** [comment]
刚刚重新装上了4.4.2  速度飞起

**Comment by userfirstone** [comment]
最新版用不了，蓝瘦，差评

**Comment by ghostlwp** [comment]
MAC依然用不了，4.5.7版本。ping的google和youtube。都是超时

**Comment by jiunnyeuchen** [comment]
沒有用，還是卡卡的，跑網頁還行，但YouTube，直接卡。

**Comment by DanielJJJ** [comment]
在Issues里看到很多可悲的帖子。

中国这边强行限制阻断的链接（包括限速），是定时开关的，不信的人自己24小时坚持使用看看哪个时段最流畅，这个阻断只是针对Lantern在内的所有相关软件，一旦阻断，你开着Lantern上不被禁止的网站都有困难，但你不用这些软件登录不被禁止的网站是正常速度，正常的网络并没有被阻断（可那就是中国的局域网），不是什么浏览器的问题，**Lantern本身能做到的都能做到，不要做无意义的推测**，**问题就是中国这边不停加重的手动限速/阻断。*面对这些困难，Lantern是需要时间来应对和升级的，要怪怪中国政府和阻断技术的开发人员，你们责怪Lantern，不觉得自己很像中国政府的奴隶么，issue里看起来就像是一堆水军故意刷舆论一样？你们归根结底在依靠Lantern的技术获取网络上的自由，在Github这种为程序员设计的开源社区提供不了技术上的支持，怨天叫地和那些翻不了墙被归化了的人有什么区别，你们这个样子翻墙到底是干什么的。

而且Lantern是美国政府资助开发的软件，等同于和中国政府作对，这个软件和Github都是美国管理的资源，我不明白你们在国内受到了什么样的洗礼竟然觉得要有客服，要说法，要投诉？？？？问题很简单，你们在违背中国政府的意愿使用lantern，中国政府剥夺了你们的权利，你们找美国人要，很多人的态度就像是美国人剥夺了你们的权利一样，我真的不明白，你们有多少人是被雇佣的水军，有多少是想上互联网的？

**Comment by jessiesh** [comment]
我也是上海电信，mac，4.5.7版本，情况和您一样，一打开蓝灯，状态图示闪一下就没了，链接不上。@ys1989611

**Comment by kevinsnake** [comment]
@amylmy 
非常感谢您底建议和帮助，按您底方法改了设置，现在可以使用蓝灯了。

再次感谢！

**Comment by lemonskkyt** [comment]
还是不行，昨天失眠了，四五点钟快的飞起，早上用就不行了

**Comment by lemonskkyt** [comment]
白天断断续续的不能正常使用

**Comment by qcj912** [comment]
可以打开网页，但是看不了直播。以前我安利蓝灯的时候说的都是直播720以上画质随心看。怀念那个时候。请快点搞好吧。

**Comment by jessiesh** [comment]
您好，我是上海电信，mac，4.5.7版本，，一打开蓝灯，状态图示闪一下就没了，链接不上。您说的更改设置，在MAC上是如何改的？谢谢！@amylmy

**Comment by kkisme** [comment]
早就更新了，卡到飞起，反正自从买了会员后就没有好好用过。

**Comment by irol765** [comment]
Ubuntu 14.04 64位 还是4.5.4，4.5.7什么时候有？

**Comment by gy0473** [comment]
不采取你们的建议谢谢

**Comment by nieflsky** [comment]
海南海口地区4.5.7（mac）一直在日本 香港 美国三个地方频繁切换

**Comment by neillyang** [comment]
3个服务器跳来跳去不稳定的看来不是个人的问题咯，速度也不稳定

**Comment by rocknrollfly** [comment]
最新版目前仍然卡顿，不是很稳定，请快点优化。蓝灯是付费APP，应该为用户提供优质服务

**Comment by weihan0917** [comment]
为什么还没有解决问题？ 几时能解决给大家说一声呀

**Comment by 80068** [comment]
希望杰布-布什能救助我们这些上网的网民

**Comment by didige** [comment]
非常不同意为蓝灯洗地的,
我们是消费者,我们买你们的商品,是认为你可以达到我们的所想要目的
但是,事与愿违,未能所愿
就最近蓝灯的表现,也可以说是最近两个月的表现,实在是差强人意,我已经忍你两个月了,
我只是想流畅的看个  UTUBE  都满足不了,哪怕是480P这样渣的画质我都可以忍受,但是,还是卡的狗也不是
你说蓝灯已经努力了,为的就是让我们能看到国外的世界,
也可以说是GFW阻断了我们的网,或是节点等等
话说回来,要是不阻断,我还要花钱买你们的服务干嘛啊,
你别忘了,你TM的,是收费的,不是免费的,
我花钱难到就买你这样渣服务 , 
就为了让你们墙外的羞辱我们墙内的.
真想说句脏话.

**Comment by didige** [comment]
如果没那技术,达不到自己所宣传的效果,
那么,就请你别TM的出来卖,
卖完,还要立牌坊.
就当 花这点钱 买狗粮了!

**Comment by binj05** [comment]
更新到最新版还是不能用.....

**Comment by xumengjing** [comment]
@DanielJJJ  那你能解释下免费的VPN PLUS 会比蓝灯好。蓝灯对得起付费的用户？消费者买了产品，产品这么差，还不能抱怨了？

**Comment by ningqivip** [comment]
卡成狗🐶

**Comment by lllllion** [comment]
买了两年337，感觉像是打水漂

**Comment by iamhaley** [comment]
蓝灯启动后瞬间自动关闭.
版本v4.5.7 | Mac OS 10.13.3

**Comment by shanligang1017** [comment]
@DanielJJJ 别再国外就感觉高人一等，我们付费是为了什么，不就为了服务，现在没了服务我们不找服务商找谁，难道我们手机没信号找国家不找运营商？

**Comment by jessiesh** [comment]
我的情况和您一样，mac，lantern4.5.7，您是如何解决的？能否分享一下，谢谢！@ iamhaley

**Comment by qunimadelandeng** [comment]
大家别骂蓝灯了 咱们国情就是这样 另外买东西是你情我愿的事儿 买之前用蓝灯的免费版完全可以多看看论坛里的帖子 喜欢不喜欢 自行决定 蓝灯现在提供不了大家的优质服务 完全可以退灯 另则他路 总不能不卡的时候没人夸奖 这一阵上不了了就哔哔嚷着退钱 有点素质 大家多报一些有用的东西 比如坐标哪里能用了 什么情况不能用 大家都是客户也是产品经理 蓝灯后台才能解决实际的问题 不然你嚷嚷半天 没什么鸟用 害的我们邮箱天天看这些破邮件  谁尼玛稀罕你这破邀请码

**Comment by iamhaley** [comment]
@jessiesh 将蓝灯退出后彻底卸载，最好之后重启一次Mac，然后重新下载安装4.5.7版本，祈祷能恢复。
我现在看启动页面左下角的版本是Lantern 4.5.7(20180317.130654)，目测是03-17发布的老版本，不知道这个时间戳与实际发布时间是否一致，亦或是刚修复过的版本。

**Comment by jessiesh** [comment]
在应用程序中，将lantern删除，再重启，这个是否算彻底删除？还有其他步骤吗？谢谢！@iamhaley

**Comment by iamyrc** [comment]
@amylmy 
改了端口后可以用了，之前都是断断续续的，感谢分享。

**Comment by my4399** [comment]
Lantern 4.5.7 (20180317.130654)

更新到了这个版本，谷歌还是打不开，youtube还是打不开。广州电信地区，ip  113.65.188.252

**Comment by sonders666** [comment]
分享一个邀请码 **YFMHDBT**

**Comment by iamhaley** [comment]
@jessiesh 没有了，你可以尝试从应用程序找到Lantern-->显示包内容-->Contens-->MacOS-->双击lantern可执行程序。
该方式尝试从后台执行Lantern启动程序，如果你与我之前的情况一致，会在启动后出现的窗口最下方找到以'ERROR'打头的行，将所有ERROR行信息黏贴出来，方便蓝灯开发人员或者其它开发同行帮忙解决。
如果错误信息中出现了类似端口冲突信息，可以尝试从之前的楼层中找到解决方法，祝好运。

**Comment by jessiesh** [comment]
lantern崩溃和错误的日志和您一模一样，问题是我反复卸载安装4.5.7，重启Mac，问题依旧。谢谢您给予我的帮助！

**Comment by jessiesh** [comment]
lantern崩溃和错误的日志和您一模一样，问题是我反复卸载安装4.5.7，重启Mac，问题依旧。谢谢您给予我的帮助！@iamhaley

**Comment by hk1011** [comment]
老版本一直是JP服务器用的好好的，4.5.7非给我换成HK的，又卡又慢，一些网站还上不去了，智能选择？呵呵了

**Comment by leehenryjz** [comment]
还是老版本强

**Comment by huahuomm** [comment]
支持lantern

**Comment by joe1280** [comment]
SSR 高速VPN 看4K视频杠杠 免费试用 QQ 
(支持苹果、安卓、PC 、MAC)

**Comment by SJTUboy** [comment]
Lantern是否已被教育网定点识别？

上海教育网主干节点Wifi下，Lantern 4.5.7基本不能用，Server在UK/JP/HK之间不停切换，一般两分钟后被断开

手机开热点（上海移动），流量就很稳，1080P YouTube无压力

比较好奇，希望有人解答，谢谢！

**Comment by imcmc** [comment]
JP,US,HK不停切换，只有跳到JP的时候不卡

**Comment by smith09** [comment]
#请注意
不会用代理插件的----看过来～
有具体的【小白步骤】教你
# 这次蓝灯修复之后，更新了端口。

所以，使用【（火狐）pan插件 或者 （谷歌）SwitchyOmega插件】的人……
# 记得要把端口改写成新的。否则连不上。

我之前就是由于这个原因，好几天连不上lantern的。
小白们安装【（火狐）pan插件 或者 （谷歌）SwitchyOmega插件】后记得要下载“[proxy]GFwList（主页，过滤规则列表）”这个规则列表，一定要有“GFW”字样的，因为这个是专治GFW的。
火狐浏览器如下

https://github.com/XX-net/XX-Net/wiki/%E4%BD%BF%E7%94%A8Firefox%E6%B5%8F%E8%A7%88%E5%99%A8#%E8%AE%BE%E7%BD%AE%E4%BB%A3%E7%90%86
找到“设置代理-方案二：安装和使用代理切换插件”
谷歌浏览器如下

https://github.com/XX-net/XX-Net/wiki/%E5%AE%89%E8%A3%85%E5%92%8C%E4%BD%BF%E7%94%A8-SwitchyOmega

安装和使用 SwitchyOmega

=================================================
如果你使用其他浏览器，除非你是软件高手，否则……为了你的安全，换成这两个其中之一吧（毕竟是大众口碑最好的）

附上我的邀请码，用不用看您方便：
# 使用邀請碼 YJX4SGY 註冊後可以得到3個月免費專業版試用!
