### ISSUE TITLE
蓝灯将补偿专业版用户一个月使用时间

### ISSUE THREAD

**Issue by ghostwith** [getlantern/forum#9147]
因为众所周知的原因，近期部分用户的连接不是很稳定，开发组正在全力修复。为了感谢专业版用户对蓝灯的支持，**所有专业版用户近期都将自动获得一个月的使用时间，无需任何手动操作**。大家可以去账号管理查看过期时间(若还未生效，请过几天再查看)。

请大家保持版面清洁，方便开发团队查看。发一些没有意义的信息只会增加开发团队的工作量，拖后开发进度，最终可能反而损害所有用户的利益。

感谢大家对蓝灯的支持！

**Comment by binj05** [comment]
HK和US服务器都不能用 就偶尔自动跳到JP可以用一会儿.....

**Comment by 1tongwang** [comment]
我的HK服务器可用了

**Comment by qpywdiy** [comment]
lantern未完全修复之前，可以用[永久免费的软件](https://github.com/Alvin9999/new-pac/wiki) 过度一下
作为lantern的粉丝，要有耐心，磨出来的0.0

**Comment by shanligang1017** [comment]
补偿不补尝倒无所谓，只希望尽快解决跳转US,HK国内不能用的问题

**Comment by sxawe** [comment]
不是我说。。。。感觉这一年光靠补偿就能挺1年半了。。。

**Comment by maya0310** [comment]
输入我的邀请码 GYMM6M 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by wilon** [comment]
支持！

```diff
+ 输入我的邀请码 YMD8TTG 来获得三个月的蓝灯专业版！
- 输入我的邀请码 YMD8TTG 来获得三个月的蓝灯专业版！
        ```

**Comment by bbbbblllll** [comment]
昨天开始就稳定了

**Comment by lemonskkyt** [comment]
别急啊，能不能先解决再补偿，还是不能正常用

**Comment by shanligang1017** [comment]
就现在这种情况，给我补偿到永久都没啥用，补偿得稳定的前提才有效

**Comment by OscarHall** [comment]
希望能更加稳定快速吧，加油

**Comment by ningqivip** [comment]
都不能用了

**Comment by meflm** [comment]
自从开会起，就不能用了，到现在都不行，更新版本后，总是跳转香港和美国，不如之前的JP稳定，20多天没法用了

**Comment by a1098536460** [comment]
希望大会过后可以稳定起来。话说每次都有补偿，能正常用到结束的话，好赚啊

**Comment by 792472461** [comment]
今天刚买的，如果早点看看你们的评论，哎

**Comment by myzone1987** [comment]
希望越来越好吧，最近真的太不稳定了~

**Comment by 792472461** [comment]
我现在谷歌上不了了。你们呢

**Comment by rocknrollfly** [comment]
虽然我这里速度还行但不太稳定，还有补偿的一个月使用时间也还没到帐。
不过，支持蓝灯，加油！

**Comment by 80068** [comment]
感谢此举，因为目前使用蓝灯还在断断续续的封锁，不稳定。希望加速研发新软件。或者再研发一款【绿灯】软件与蓝灯并肩使用。目前【天津联通】每次打开蓝灯只能使用1分钟的时间，深夜会稍稳定一些。所以目前看还不是那么顺畅。所以加速不能掉以轻心。要多管齐下，多重并举，才能使蓝灯变得更急速更深不可测。

**Comment by EntwicklungLM** [comment]
依然很慢
不慢的时候又有可能不稳定

**Comment by icycheng** [comment]
时间并没有到账啊 账号icycheng424@163.com

**Comment by dALAOCU1008** [comment]
依旧加载网络非常的缓慢。

**Comment by neillyang** [comment]
稳定毛线，不仅速度慢还出现闪退了。

**Comment by neillyang** [comment]
稳定毛线，不仅速度慢还出现闪退了。

**Comment by xbdxnss** [comment]
1.没有时间到账
2.体验太差，运气好等个几十秒打开一个网页，运气不好直接连不上
3.付费的是不是还不如免费的，当初用免费的还能正常用，买了两年的才用一个月就不行了？

**Comment by pathfinder-hello** [comment]
这个老跳转服务 不稳定网速和之前简直不是一个次元的了

**Comment by 1245134377** [comment]
我不要补偿，我要的是稳定！
安卓经常在US和HK之间跳根本就用不了！
PC能翻油管都慢得要死，一直转圈圈。
这样就算你补偿1年有个卵用！
就不能把问题解决了先吗？
某会都结束一个星期了！

**Comment by wjw513280** [comment]
@ghostwith  反映2个问题：第一个问题是蓝灯4.4.2版本明明可以正常使用，为何要强制升级到最新版本，最新版本反而用不了了。 第二个问题，补偿时间貌似没有到账。

**Comment by wjw513280** [comment]
@Ghostwithout  反映2个问题：第一个问题是蓝灯4.4.2版本明明可以正常使用，为何要强制升级到最新版本，最新版本反而用不了了。 第二个问题，补偿时间貌似没有到账。

**Comment by amnour** [comment]
@Ghostwithout 为什么授权不了新的版本啊？

**Comment by leehenryjz** [comment]
我也沒有到賬過，補償的1個月   @Ghostwithout

**Comment by bsou911** [comment]
重庆电信还是不稳定！也就几十kb的速度吧

**Comment by GeofferyGeng** [comment]
刚刚有五分钟个正常了，现在又凉了//

**Comment by archmagesfather** [comment]
虽然用的白嫖版本。
不明白为什么总是选择JP的服务器，明明就是封杀的重灾区。
修复半个月，使用两分钟。习惯了。
口号是秒杀威屁恩，是事实效果远不如一些独立开发者的良心作品。

**Comment by XXZs** [comment]
开发者们加油吧，现在JP、HK、US三个节点不断跳来跳去的太痛苦了

**Comment by han814992037** [comment]
坐标北京后场村，现在比较稳定，youtube可看720视频，不过还会断一两下，望开发组，多多努力！！！加油！！！谢谢！！！

**Comment by Zhaosiqizz** [comment]
我的蓝灯 localhost:56340 页面进不去，就蓝灯的那个页面都进不去怎么解决。。而且打开蓝灯浏览器就改了代理，必须把局域网的设置代理服务器勾掉才能访问国内网站。  这个问题应该怎么解决？

**Comment by gy0473** [comment]
啥时候打开啥时候给我连HK，不然就是US，要是都能翻我也就不想骂了，关键是连了这俩整个跟断网一样，求只给我连JP好么 9535RC

**Comment by han814992037** [comment]
这两天进步十分明显，虽然HK和US、JP来回跳，但是基本全都可用，速度相当可观，youtube可以直接跳到720P，360P毫无压力，只是偶尔会断一两下，但是很快又会恢复，所以谢谢开发组了，多多努力，眼看马上就要恢复如初了！加油！！！辛苦了！！！谢谢！！！
坐标北京后场村路

**Comment by breky** [comment]
看着你们都不能用，我就放心了。不用我再折腾电脑了。

开发组大佬们，我知道你们很累，但是可以的话，加把劲呀。学校资源少，不用梯子，下不了国外文献呀。

鞠躬(90°)

**Comment by joe1280** [comment]
SSR 高速VPN 看4K视频杠杠 免费试用 QQ 97007624 
SSR 高速VPN 看4K视频杠杠 免费试用 QQ 97007624SSR 高速VPN 看4K视频杠杠 免费试用 QQ 
(支持苹果、安卓、PC 、MAC)

**Comment by joe1280** [comment]
SSR 高速VPN 看4K视频杠杠 免费试用 QQ 
(支持苹果、安卓、PC 、MAC)

**Comment by lanternor** [comment]
请问补偿的一个月是否已经全部派送完毕了？因为我还未收到

**Comment by BLAZE-Windy** [comment]
等了我三天，还没收到。

**Comment by shanligang1017** [comment]
@ghostwith 这几天有点稳定起来了，希望更加努力，另外我没有收到补偿的一个月，是不是通过代理商买的收不到呀，请解决！

**Comment by xiexulei1** [comment]
我说我怎么又变成11个月了，原来是补偿了一个月，冒昧问一句，咱们程序员去墙外能干哪些事啊？我还是新司机啊

**Comment by gblje** [comment]
输入我的邀请码 **KJX2M6** 来获得三个月的蓝灯专业版！

**Comment by kkisme** [comment]
补偿有啥用啊，不稳定期间应该不算会员时间。等稳定了在算，再加补偿天数。

**Comment by lemonskkyt** [comment]
我想知道，我现在还是不能正常使用，lantern有在解决这个问题吗？？？？？？
.
.
.

还是说依然不能正常使用的用户就自求多福了？

**Comment by ericericsun** [comment]
输入我的邀请码 M989RM 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by lemonskkyt** [comment]
昨天晚上开始，可以正常使用了

**Comment by abc9991** [comment]
到现在我的还是不能用,不知道什么原因?

**Comment by Mrrong** [comment]
我买了2年的，前段时间老是不稳定，今天就安装了个最新版本，反而弄不了了，好捉急啊，还有谁遇到一样的问题，求官方或者大神帮我解决，急~急~急~

**Comment by sonders666** [comment]
分享一个邀请码 **YFMHDBT**

**Comment by 1245134377** [comment]
补偿到现在还没看到

**Comment by liu726301387** [comment]
为什么补偿还没到呢?

**Comment by rayonlau** [comment]
我没收到补偿

**Comment by smith09** [comment]
**#请注意**
不会用代理插件的----看过来～ 
有具体的【小白步骤】教你
这次蓝灯修复之后，更新了端口。
所以，使用【（火狐）pan插件 或者 （谷歌）SwitchyOmega插件】，记得要把端口改写成新的。否则连不上。
我之前就是由于这个原因，好几天连不上lantern的。
小白们安装【（火狐）pan插件 或者 （谷歌）SwitchyOmega插件】后记得要下载“[proxy]GFwList（主页，过滤规则列表）”这个规则列表，一定要有“GFW”字样的，因为这个是专治GFW的。

火狐浏览器如下
https://github.com/XX-net/XX-Net/wiki/%E4%BD%BF%E7%94%A8Firefox%E6%B5%8F%E8%A7%88%E5%99%A8#%E8%AE%BE%E7%BD%AE%E4%BB%A3%E7%90%86
找到“设置代理-方案二：安装和使用代理切换插件”

谷歌浏览器如下
https://github.com/XX-net/XX-Net/wiki/%E5%AE%89%E8%A3%85%E5%92%8C%E4%BD%BF%E7%94%A8-SwitchyOmega

安装和使用 SwitchyOmega
=================================================
如果你使用其他浏览器，除非你是软件高手，否则……为了你的安全，换成这两个其中之一吧（毕竟是大众口碑最好的）

附上我的邀请码，用不用看您方便：
使用邀請碼 **YJX4SGY** 註冊後可以得到3個月免費專業版試用!
![2018-04-02_173131](https://user-images.githubusercontent.com/23282821/38191568-cdb0f6d0-3658-11e8-8a42-033f7ed8b74b.JPG)

**Comment by Ghostwithout** [comment]
请到lantern界面账号管理查看赠送的一个月，如果没有更新，请重启lantern. 谢谢！
![image](https://user-images.githubusercontent.com/33254750/38222859-1851d5a8-371a-11e8-85d9-5021b2e5e3ea.png)

**Comment by handsomebubu** [comment]
也就晚上稳定         白天依旧是3个点跳来跳去

**Comment by pphitass** [comment]
这几天好点了，，，一个月没到账的来说下。。。

**Comment by OscarHall** [comment]
我也还没到账怎么办

**Comment by han814992037** [comment]
已经到账！谢谢开发组！辛苦了！！！我会尽量推荐给我的朋友和同事的！！！

**Comment by molijin** [comment]
又补偿了，哈哈哈！良心卖家

**Comment by tingcom3** [comment]
我也到账了，诚信的官方。

**Comment by xdcccr** [comment]
新客户有补偿吗？？

**Comment by XXZs** [comment]
补偿收到了，功能也恢复了六成以上，开心

**Comment by SeanBurt** [comment]
刚入手的专业版，google无法使用。
ip：北京市北京市 鹏博士宽带

**Comment by ShifuHe** [comment]
深圳移动还可以用，分享邀请码 LDRYQ7
立即下载 https://github.com/getlantern/forum

**Comment by lucyddd** [comment]
国内的基本都被封杀了，就是存活的，也存在跑路风险，你还是直接买国外的吧，替代蓝灯，天行，Green，豆荚等
http://zhizhi.npage.de/

**Comment by xdcccr** [comment]
补偿一直没到，而且服务器一直是UK或JP，感觉略坑？
