### ISSUE TITLE
IOS版什么时候能上？

### ISSUE THREAD

**Issue by zhongyuan332** [getlantern/forum#9157]
最近在玩游戏，国内网根本连不上，ios也不能用，只想知道什么时候上ios版？

**Comment by Lshic** [comment]
就是啊，明明说今年初的，哎

**Comment by s906857** [comment]
IOS 用17Yun  小贵 速度还不错
https://27yun.vip

**Comment by BLAZE-Windy** [comment]
听说因为苹果的审核严格，很难通过。

**Comment by joe1280** [comment]
SSR 高速VPN 看4K视频杠杠 免费试用 QQ 97007624 支持IOS

**Comment by huahuomm** [comment]
上了也没法放apple store吧      党会让苹果下架的

**Comment by joe1280** [comment]
我有美国的apple store账号和密码

**Comment by herongZhang** [comment]
希望iOS的赶紧上

**Comment by icycheng** [comment]
iOS的可以搞个台湾Apple ID去台区App Store下载，有很多能用的
