### ISSUE TITLE
失望了，现已自建SSR梯子，推荐大家也别指望蓝灯了，自己动手，丰衣足食才是正道

### ISSUE THREAD

**Issue by zhongluqiang** [getlantern/forum#9185]
在经历了蓝灯反复失效以及现在仍未解决的情况下，我终于对蓝灯失望了。虽然我的专业版还有9个月，但已经经不起这么折腾了。前两天参考某位道友的帖子，自己在vultr上搭建了一个SSR服务器。前后花了不到半小时，一直用到现在，并未感觉有什么不方便，网速还可以，也能自动切换国内国外代理，感叹为什么当初不花点耐心仔细学一下，可以省下不少折腾的时间。帖子地址如下：
https://github.com/btgfw/btgfw
用的vultr上New York节点的服务器，最低配置的2.5$一个月的，配置switchyOmega插件，真的非常方便，推荐给大家，毕竟自己动手，丰衣足食。

**Comment by lanternor** [comment]
道友是吸毒者的意思.

**Comment by shanligang1017** [comment]
用蓝灯我是为了便宜不限流量，自建的一般比较贵和限流量

**Comment by anticpc** [comment]
@shanligang1017 合租15-18一个月行情价，一般流量限制可以忽略不计

**Comment by sblig** [comment]
http://27yun.vip/aff.php?aff=55
偶然遇见，挺方便的
