### ISSUE TITLE
合租自己搭建的SSR，低延时稳定，账号试用

### ISSUE THREAD

**Issue by optimus1009** [getlantern/forum#9188]
YouTube 1080p, 2K 没压力，4K看你网络带宽，平时移动4G网速度是 ~3m/s ,  走的是cn2网络，内地香港直连，自己是算法工程师，自己会维护，基本不会掉的，因为每个人的网络环境不一样，可以试用测试账号，如果感觉不行也没啥影响，不限流量网速
**wechat: x-lin0914**

看看下面的 ping值 

![37962862-195ce648-31ef-11e8-9052-eafcc8776a04](https://user-images.githubusercontent.com/11548953/38015548-b7ef41a2-329e-11e8-9cbf-c48ac6b429c0.png)

**Comment by hub518123** [comment]
这个VPS是gigsgigs的机器吧，他们家的VPS性价比还是比较高的
