### ISSUE TITLE
合租自己的SSR, Ping值30ms, 账号试用，个人搭建，求分担

### ISSUE THREAD

**Issue by optimus1009** [getlantern/forum#9222]
YouTube 1080p, 2K 没压力，4K看你网络带宽，平时移动4G网速度是 ~3m/s , 走的是cn2网络，内地香港直连，自己是算法工程师，自己会维护，基本不会掉的，因为每个人的网络环境不一样，可以试用测试账号，如果感觉不行也没啥影响，
1: 不限流量网速
2: pc 手机，ios ,mac 都能用
**wechat: x-lin0914**
下面的Ping值， 这延时应该够可以了吧，
![37962862-195ce648-31ef-11e8-9052-eafcc8776a04](https://user-images.githubusercontent.com/11548953/38085521-6e5284f6-3383-11e8-9306-f15b985200ab.png)

**Comment by lkoo5488** [comment]
怎么联系?

**Comment by optimus1009** [comment]
微信 x-lin0914
