### ISSUE TITLE
SSR合租，一起分摊

### ISSUE THREAD

**Issue by optimus1009** [getlantern/forum#9243]
YouTube 1080p, 2K 没压力，4K看你网络带宽，平时移动4G网速度是 ~3m/s , 走的是cn2网络，内地香港直连，自己是算法工程师，自己会维护，基本不会掉的，因为每个人的网络环境不一样，可以试用测试账号，如果感觉不行也没啥影响，
1: 不限流量网速
2: pc 手机，ios ,mac 都能用

# **wechat: x-lin0914**

**# ping值，延时很低，也很稳定，没有跳ping**
![ping](https://user-images.githubusercontent.com/11548953/38158530-e86fdce8-34c8-11e8-944b-7d5e6b8c9c28.png)

**# 这是YouTube4K**

![youtube](https://user-images.githubusercontent.com/11548953/38158536-0236eb3a-34c9-11e8-9e06-65a912466f10.jpg)

**Comment by wanlilu** [comment]
怎么联系你？

**Comment by optimus1009** [comment]
wx:   x-lin0914

**Comment by sblig** [comment]
http://27yun.vip/aff.php?aff=55
偶然遇见，挺方便的

**Comment by sblig** [comment]
http://27yun.vip/aff.php?aff=55
偶然遇见，挺方便的
