### ISSUE TITLE
个人SSR服务器合租，一起分摊

### ISSUE THREAD

**Issue by optimus1009** [getlantern/forum#9247]
YouTube 1080p, 2K 没压力，4K看你网络带宽，平时移动4G网速度是 ~3m/s , 走的是cn2网络，内地香港直连，自己是算法工程师，自己会维护，基本不会掉的，因为每个人的网络环境不一样，可以试用测试账号，如果感觉不行也没啥影响，
1: 不限流量网速
2: pc 手机，ios ,mac 都能用

# **wechat: x-lin0914**

# **ping值很低，很稳**
![ping](https://user-images.githubusercontent.com/11548953/38160535-417b9ce0-34f2-11e8-898d-8a20d0d1c6f7.png)

# **YouTube 4K**

![youtube_2](https://user-images.githubusercontent.com/11548953/38160539-50dc2e48-34f2-11e8-93a4-dae3b090eead.png)

**Comment by Resister** [comment]
朋友，方便详谈嘛，我有意合租，技术方面我也能帮忙，我是做图形渲染的，
