### ISSUE TITLE
关于蓝灯速度和线路的问题。

### ISSUE THREAD

**Issue by p3rcya** [getlantern/forum#930]
我们正在购买更好的网络线路，来解决网速慢的问题。
公测时间内购买专业版有两个月额外时间赠送，所以请稍安勿躁。

如果各位有优质线路推荐，欢迎大家回帖。我们会在后台测试，来决定是否购买这些推荐的线路。谢谢！

**Comment by unever** [comment]
> Error while resend buffer to feedly.com: write tcp 192.168.1.2:50642->104.131.**.**:43247: i/o timeout

有些网站偶现，比如上面的feedly.com，而有些网站永久这样报错，比如：http://apk-dl.com/

类似这样的问题也挺频繁的，请问如何解决？

**Comment by YOYOsheep** [comment]
嗯，在耐心等候

**Comment by p3rcya** [comment]
@orbancanon 你看看feedly为什么无法访问

**Comment by infinitebook** [comment]
然而我并没有那2个月的额外时间赠送，而且网速确实很慢

**Comment by p3rcya** [comment]
正式版推出后，我们再后台加入

**Comment by orbancanon** [comment]
@unever 看起来跟这个有关 https://github.com/getlantern/lantern/issues/5023

@fffw can you also check http://apk-dl.com/?
