### ISSUE TITLE
强烈要求加快iOS版的开发进度！！！

### ISSUE THREAD

**Issue by amylmy** [getlantern/forum#9310]
虽然我知道有一些诸如在PC端设置ip和端口来共享给手机用的方法。
但这真的很鸡肋，有电脑的时候谁还一直按手机呢。。。

在外面有时候用手机查东西真的很麻烦。。。

虽然有看到lantern的开发者们在google+上说正在全力提高系统不被block的能力。。。
这个当然是关键。。。

但。。。
iOS端也真的真的很重要呀~

顺便说一句！照现在的情形看，想在特殊时期完全不被block，不受一点影响可能真的很难。。。
要知道。。。正所谓，道高一尺魔高一丈。。。

而。。。
开一个iOS的有那么那么困难么？
那其他的VPN是怎么做到的呢?

希望开发者们能看到我这种iOS用户的强烈诉求。。。！！！

## 尽快发布iOS版吧~！！！

祝Lantern越来越好~

**Comment by fateblessme** [comment]
输入我的邀请码 YYXUZRV 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
