### ISSUE TITLE
SSR合租，

### ISSUE THREAD

**Issue by chooseworld** [getlantern/forum#9336]
YouTube 1080p, 2K 没压力，4K看你网络带宽，平时移动4G网速度能到 ~3m/s , 走的是cn2网络，自己是算法工程师，自己会维护，基本不会掉的，因为每个人的网络环境不一样，可以试用测试账号，给试用账号体验下，

# **wechat : x-lin0914**

## **这个ping值还是很低的，这样的速度可以代理韩服，美服的吃鸡了**

![ping](https://user-images.githubusercontent.com/38099363/38400101-f865a256-3980-11e8-81d5-e0bd86978483.png)

## **YouTube  4K 也是很轻松的**

![youtube_2](https://user-images.githubusercontent.com/38099363/38400156-30f18a4a-3981-11e8-95a5-801ac86ab968.png)

**Comment by 1793907272** [comment]
可以啊，大概多少钱
