### ISSUE TITLE
授权其他设备，收不到验证码，邮箱是国内的，申请更换备用邮箱

### ISSUE THREAD

**Issue by hfq-mayouzi** [getlantern/forum#9366]
请在发帖前先按照蓝灯无法使用的解决办法 https://github.com/getlantern/forum/issues/1902 自行解决。自行解决问题通常只需要几十分钟。管理员调查解决问题需要几天至几周。请立即访问https://github.com/getlantern/forum/issues/1902 瞬间解决98%的问题

为了能在最快的时间内解决大家使用蓝灯遇到的问题，请各位用户严格按照发帖格式提交问题。

## 发帖格式
遇到的问题：请详细描述遇到的问题。如果描述不仔细，将无法调查

蓝灯专业版账号Email:  请提供登陆蓝灯专业版的email，免费版不提供技术支持。

应用内报告问题的时间:  请根据 https://github.com/getlantern/forum/issues/1840 在应用内上报问题，请填写专业版的email。请在帖子里注明报告的时间。

截图: 请提供有关问题的截图。 请把图片拖拽到这里。

----
邀请码在本论坛请以签名形式发布或发到其他论坛。具体见 https://github.com/getlantern/forum/issues/3773

麻烦管理员审核一下，交易ID: w133738424  备用邮箱mayorderozan@gmail.com

**Comment by hfq-mayouzi** [comment]
另外，怎么设置一个账号的密码？方便登陆

**Comment by hfq-mayouzi** [comment]
@Ghostwithout

**Comment by Ghostwithout** [comment]
你好，已经更新邮箱。通常变成专业版后，就会一直保持登陆状态。但是如果因为重装等原因，变会免费版，可用如下方法授权设备登陆：
－在lantern界面左边菜单点击“授权设备使用专业版”，在里面输入购买时的邮箱，激活码就会发到你的邮箱，然后输入激活码即可； 
－在新设备选择“授权设备使用专业版”，该界面会收到验证码，然后请到专业版设备输入验证码。谢谢！ @hfq-mayouzi

**Comment by hfq-mayouzi** [comment]
@Ghostwithout 
谢谢，那就是说没法在官网通过账号密码登陆是吗？因为无法设置密码，另外邮箱变更后，我打开APP还是现实的之前的邮箱，这个是正常的吗？盼复

**Comment by hfq-mayouzi** [comment]
@Ghostwithout 
不好意思，刚我重启APP看了看，邮箱已经更换过来了，不知道能不能给邮箱发送一个登陆的密码啊？

**Comment by Ghostwithout** [comment]
可以啊，在lantern界面左边菜单点击“授权设备使用专业版”，在里面输入购买时的邮箱，激活码就会发到你的邮箱。
