### ISSUE TITLE
刚买了两年的专业版，结果一分钟都上不了，快退款！！！

### ISSUE THREAD

**Issue by jiarenyf** [getlantern/forum#9372]
刚买了两年的专业版，结果一分钟都上不了，快退款！！！
刚买了两年的专业版，结果一分钟都上不了，快退款！！！
刚买了两年的专业版，结果一分钟都上不了，快退款！！！

**Comment by zwtall** [comment]
能上这个网，就翻墙了，靴靴

**Comment by szw9536** [comment]
@zwtall 这个论坛不需要翻墙就能上，靴靴

**Comment by CrazySnailer** [comment]
我也是，连不上，刚买的一年的专业版，一点都没连上，快退款。

**Comment by CrazySnailer** [comment]
我的又可以了，删掉重新装的。

**Comment by zsqp447** [comment]
做梦啊
