### ISSUE TITLE
修改邮箱

### ISSUE THREAD

**Issue by spangrid** [getlantern/forum#940]
这个问题已经**2周**了，我注册的时候邮箱输入错误，**请**帮助我后台修改注册邮箱。
我没有处于登录状态的设备，即便你们以后添加了修改邮箱的功能，我也无法使用！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by p3rcya** [comment]
因为你输入邮箱错误，我们只能通过付款信息人为核对。这个工单系统我们以后会上线

**Comment by spangrid** [comment]
我这边输入错了是我的问题，但是你们注册机制上至少先提供个邮箱验证后付款。
还有能不能直接核对后后台帮我修改为正确的邮箱。

**Comment by p3rcya** [comment]
已经修改
