### ISSUE TITLE
刚买专业版就不能用了，无法根据以上信息识别账号

### ISSUE THREAD

**Issue by chriisella** [getlantern/forum#9418]
交易ID是w142079174。交易日期是2018-3-18 下午10:40 (GMT-5)。
购买邮箱是：ella_wenwen@outlook.com

**Comment by chriisella** [comment]
备用邮箱：qiaosilei1992@163.com

**Comment by chriisella** [comment]
那个帖子里的方法都用了 无效

**Comment by Ghostwithout** [comment]
你好，这个帐号对应邮箱是szguge@yahoo.com，请核实，谢谢！ @chriisella

**Comment by chriisella** [comment]
好的，谢谢

________________________________
发件人: Ghostwithout <notifications@github.com>
发送时间: 2018年4月16日 20:37:21
收件人: getlantern/forum
抄送: chriisella; Mention
主题: Re: [getlantern/forum] 刚买专业版就不能用了，无法根据以上信息识别账号 (#9418)


你好，这个帐号对应邮箱是szguge@yahoo.com<mailto:szguge@yahoo.com>，请核实，谢谢！ @chriisella<https://github.com/chriisella>

―
