### ISSUE TITLE
购买专业版写错邮箱，麻烦修改

### ISSUE THREAD

**Issue by damojiang** [getlantern/forum#9444]
不知为什么好多人给我发邮件 我修改一下  不显示邮件了

**Comment by damojiang** [comment]
@Ghostwithout  帮忙解决一下 谢谢

**Comment by damojiang** [comment]
@Ghostwithout  帮忙修改一下邮箱 谢谢

**Comment by Ghostwithout** [comment]
抱歉，没能及时回复，已更新为baijianchun0507@hotmail.com，谢谢！ @damojiang
