### ISSUE TITLE
输入我的邀请码 Y2FMCYN 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

### ISSUE THREAD

**Issue by Ablegang** [getlantern/forum#9447]
输入我的邀请码 Y2FMCYN 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by eagle0898** [comment]
如何使用邀请码？

**Comment by fangxu622** [comment]
输入我的邀请码 KWG5S6 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by cyu052** [comment]
6个月邀请码  YHV3NKC    ， 数量有限，尽快，立即下载 https://github.com/getlantern/forum
