### ISSUE TITLE
win10现在还是连接不上，4.6.0，大家都能用了吗

### ISSUE THREAD

**Issue by cyril666666** [getlantern/forum#9460]
请在发帖前先按照蓝灯无法使用的解决办法 https://github.com/getlantern/forum/issues/1902 自行解决。自行解决问题通常只需要几十分钟。管理员调查解决问题需要几天至几周。请立即访问https://github.com/getlantern/forum/issues/1902 瞬间解决98%的问题

为了能在最快的时间内解决大家使用蓝灯遇到的问题，请各位用户严格按照发帖格式提交问题。

## 发帖格式
遇到的问题：请详细描述遇到的问题。如果描述不仔细，将无法调查

蓝灯专业版账号Email:  请提供登陆蓝灯专业版的email，免费版不提供技术支持。

应用内报告问题的时间:  请根据 https://github.com/getlantern/forum/issues/1840 在应用内上报问题，请填写专业版的email。请在帖子里注明报告的时间。

截图: 请提供有关问题的截图。 请把图片拖拽到这里。

----
邀请码在本论坛请以签名形式发布或发到其他论坛。具体见 https://github.com/getlantern/forum/issues/3773

**Comment by cyril666666** [comment]
#1902里的方法都试了也没用

**Comment by marilyndean** [comment]
# **合租SSR**
1: 不限网速
2: pc 手机，ios ,mac 都能用
3: 可以代理游戏，可以代理游戏

# **wechat: x-lin0914**

**Comment by Ghostwithout** [comment]
你好，方便留下邮箱吗？有在lantern界面反馈问题吗，会自动上传日志，以便调查。谢谢！

**Comment by wjw513280** [comment]
WIN10一直很正常啊。除了开会那几天。

**Comment by yangjh1220** [comment]
我的蓝灯挂了很久，将近一个月不能用，按＃1902修改也是一样。Win10、Win8版本都失效。
