### ISSUE TITLE
Mac 新下载的lantern打开网页报错：‘很抱歉，蓝灯似乎未在运行。请重启蓝灯并重试。’

### ISSUE THREAD

**Issue by sunhaixin** [getlantern/forum#9475]
遇到的问题：macOS 10.12.3 新下载的lantern打开网页报错：‘很抱歉，蓝灯似乎未在运行。请重启蓝灯并重试。’

蓝灯专业版账号Email: 505872716@qq.com

应用内报告问题的时间: 2018/4/17 21:20

![error](https://user-images.githubusercontent.com/12843528/38872809-ba9d7e94-4286-11e8-816b-a79f788ee467.png)

[lantern.log.zip](https://github.com/getlantern/forum/files/1919882/lantern.log.zip)

**Comment by sunhaixin** [comment]
重启多次都是这样

**Comment by jessiesh** [comment]
me too

**Comment by JiateLi** [comment]
same, any solution?

**Comment by orbancanon** [comment]
@sunhaixin 你是不是用的Firefox Quantum？它有一个兼容性问题导致Lantern的界面不能工作。老版本的Firefox和其它浏览器可以用。

@jessiesh @JiateLi 你们是不是一样的情况？如果不是，请上传日志。

**Comment by jessiesh** [comment]
用Chrome

**Comment by sunhaixin** [comment]
@orbancanon 是这样的，已经解决了，非常感谢！@jessiesh @JiateLi 也可以试试

**Comment by sunhaixin** [comment]
@orbancanon 是这样的，已经解决了，非常感谢！@jessiesh @JiateLi 也可以试试
