### ISSUE TITLE
有的网站出现read tcp 192.168.1.100:52612->139.162.15.172:53541: i/o timeout

### ISSUE THREAD

**Issue by jy29104983** [getlantern/forum#948]
有的网站出现read tcp 192.168.1.100:52612->139.162.15.172:53541: i/o timeout，访问不了内容。

**Comment by ssy341** [comment]
我也出现过这个问题，一般我是多刷新几次就行了，这个情况出现在 国内的网站，比如csdn

**Comment by jy29104983** [comment]
刷新我试了，没有用，我刚开始以为不是专业版的问题，后来买了专业版也没用。以前这些网站是可以上的，现在用手机版的蓝灯也可以上，就是电脑上不去。

**Comment by junecwf** [comment]
设置全局代理

**Comment by johnwatsondev** [comment]
github 博客也会出现这个问题。例如：`http://chiuki.github.io/espresso/`

显示如下内容：

```
read tcp 10.0.0.31:52498->45.118.134.227:48613: i/o timeout
```

**Comment by jy29104983** [comment]
按照junecwf的提示解决了，谢谢
