### ISSUE TITLE
帮忙修改邮箱

### ISSUE THREAD

**Issue by willem405ever** [getlantern/forum#9522]
原注册邮箱owenwwj@yahoo.cn，由于邮箱已经作废，现改为owenwwj@126.com，支付宝凭证如图，不知道为什么商户账单是这个。。。
![2018-04-17 081031](https://user-images.githubusercontent.com/38412492/39024631-c21459fa-4474-11e8-91ec-ba520ace93b0.png)

----
邀请码在本论坛请以签名形式发布或发到其他论坛。具体见 https://github.com/getlantern/forum/issues/3773

**Comment by Ghostwithout** [comment]
你好，已更改，谢谢！ @willem405ever
