### ISSUE TITLE
买了蓝灯的专业版无法授权，请帮我核实谢谢。

### ISSUE THREAD

**Issue by u2383121** [getlantern/forum#9528]
直接填邮箱授权说没有这个账号，支付宝付款的。
邮箱：84984470@qq.com
付款信息：
2018-04-20 16:54
订单号
2018042021001003840552199637
商户订单号
AliPayFX_4315242143611813_6068

**Comment by u2383121** [comment]
请快速帮我核实谢谢

**Comment by Ghostwithout** [comment]
你好，麻烦提供w 开头的序列号才能查询，谢谢！ @u2383121

**Comment by u2383121** [comment]
我付款后没有那个序列号啊，我是用支付宝付的款

**Comment by u2383121** [comment]
怎么回事？出问题不给解决的吗？？？

**Comment by u2383121** [comment]
@Ghostwithout 我已经说了很多次了，邮件也给你们发了很多封，我安卓手机支付宝支付的，没有看到W开头的序列号。我购买的时候填写的邮箱是84984470@qq.com，而且好像不能上传截图把？你们给我个邮箱，我把截图给你传过去。

**Comment by u2383121** [comment]
@Ghostwithout 我已经说了很多次了，邮件也给你们发了很多封，我安卓手机支付宝支付的，没有看到W开头的序列号。我购买的时候填写的邮箱是84984470@qq.com，而且好像不能上传截图把？你们给我个邮箱，我把截图给你传过去。

**Comment by u2383121** [comment]
@Ghostwithout 
截图上的订单号是：2018042021001003840552199637
商户订单号是：AliPayFX_4315242143611813_6068
付款时间：2018-04-30 16：54
------------------------------------------------------------
如果这个不行的话，你们要告诉我没有W开头的订单号，而不是不停的重复要我拿出W开头的订单号。这样的效率我真的觉得无法接受

**Comment by orbancanon** [comment]
@u2383121 抱歉我们后台批量修复了这次出问题的几个帐号，但结果里面找不到你的帐号。你的支付宝记录里应该有16444970-4495-11e8-8f84-2fca2efdd745这样的商品说明，麻烦提供一下，以便后台查找并修复。前8位就可以了。

**Comment by u2383121** [comment]
fb00a2c0-4477-11e8-8f84-2fca2efdd745，这个是我的商品说明。
@orbancanon

**Comment by orbancanon** [comment]
@u2383121 你好，从支付服务商的后台查到，你的款似乎没能付过来。有可能是中间出了问题，不过我已经手工加了这笔付款，你现在已经是专业版了。如果没有的话，请用邮箱登录。
