### ISSUE TITLE
专业版无法授权，邮箱登录码获取不到

### ISSUE THREAD

**Issue by zizi520** [getlantern/forum#9536]
![qq 20180421105339](https://user-images.githubusercontent.com/38576248/39079663-4c26b9d4-4552-11e8-9c14-47039fb7fa5c.png)
麻烦核实一下 谢谢

**Comment by Ghostwithout** [comment]
你好，
这个购买凭证对应的邮箱是longluoqiao@vip.qq.com，但是qq邮箱屏蔽了部分登陆验证码，需要麻烦多试几次才能收到。
也可以在新设备选择“授权设备使用专业版”，该界面会收到验证码，然后请到专业版设备输入验证码。谢谢！ @zizi520

**Comment by zizi520** [comment]
试了很多次也不行。等邮箱验证码一等就是几个小时。 授权设备使用专业版也不得行，输入了验证码就没有后续反应。 这种情况怎么办？ 要不帮我修改一个登录邮箱，有网易的邮箱可以吗？
