### ISSUE TITLE
请管理员或者说客服帮忙修改一下蓝灯的邮箱

### ISSUE THREAD

**Issue by zzw19921212** [getlantern/forum#9545]
如题，请帮我修改邮箱为75278599@qq.com
原邮箱是：zzw19921212intl@gmail.com
订单号：w122357087
支付时间：2017.07.15 14：58

**Comment by Ghostwithout** [comment]
已更新，谢谢！ @zzw19921212

**Comment by zzw19921212** [comment]
@Ghostwithout ，还是显示原邮箱啊

**Comment by zzw19921212** [comment]
@Ghostwithout，那请改成sindey1982@gmail.com，谢谢
