### ISSUE TITLE
不能收到动态授权码

### ISSUE THREAD

**Issue by xiaozhengdong1999** [getlantern/forum#9570]
账号 1615449919@qq.com，即不能接收动态授权码，邮箱也收不到授权码
订单号 w129295494

**Comment by xiaozhengdong1999** [comment]
还是说服务器问题，或者是这个4.6.4的bug

**Comment by xiaozhengdong1999** [comment]
动态授权码一直显示验证错误提示框

**Comment by xiaozhengdong1999** [comment]
或者能不能帮我修改一下邮箱xiaozhengdong1999.gmail.com
管理员

**Comment by Ghostwithout** [comment]
你好，请参考https://github.com/getlantern/forum/issues/9280
提供购买凭证，核实后可更改，谢谢！ @xiaozhengdong1999

**Comment by xiaozhengdong1999** [comment]
原帐户 1615449919@qq.com
商户订单号 w129295494
支付时间 2017-10-09 01:48
备用邮箱 xiaozhengdong1999@gmail.com
@Ghostwithout

**Comment by Ghostwithout** [comment]
你好，已更新，谢谢！@xiaozhengdong1999
