### ISSUE TITLE
蓝灯邮箱注册错误

### ISSUE THREAD

**Issue by lp2004103121** [getlantern/forum#9575]
遇到的问题：蓝灯注册的时候本来想注册的邮箱为lp2004103121@hotmail.com，结果不小心填成了lp2004103121@hotmai.com。现在我这个账号由于没有邮箱支持，所以在家里的电脑上用不了。

蓝灯专业版账号Email: lp2004103121@hotmai.com

应用内报告问题的时间:  专业版账号为lp2004103121@hotmai.com。报告的时间为2018年4月24日10点30分左右。

截图: 这是我的账号和支付宝交易凭证，请允许我修改自己的邮箱，期盼你们的回信
![qq 20180424103421](https://user-images.githubusercontent.com/38676099/39163071-6033d19a-47ab-11e8-8e3f-a80f778790ae.jpg)
![_20180424103524](https://user-images.githubusercontent.com/38676099/39163074-61e6018e-47ab-11e8-9506-afa2fc375452.jpg)

----
邀请码在本论坛请以签名形式发布或发到其他论坛。具体见 https://github.com/getlantern/forum/issues/3773

**Comment by Ghostwithout** [comment]
你好，已更改，谢谢@lp2004103121

**Comment by zwtall** [comment]
互赠3个月，请输入：YGHVRD3

**Comment by lp2004103121** [comment]
@zwtall老哥已经用我同事的了。
