### ISSUE TITLE
专业版无法授权其他设备，并帮忙修改邮箱，还请帮忙尽快处理

### ISSUE THREAD

**Issue by CrzSeNrM** [getlantern/forum#9579]
请在发帖前先按照蓝灯无法使用的解决办法 https://github.com/getlantern/forum/issues/1902 自行解决。自行解决问题通常只需要几十分钟。管理员调查解决问题需要几天至几周。请立即访问https://github.com/getlantern/forum/issues/1902 瞬间解决98%的问题

为了能在最快的时间内解决大家使用蓝灯遇到的问题，请各位用户严格按照发帖格式提交问题。

## 发帖格式
遇到的问题：1.专业版动态码无法授权其他设备（显示授权后，其他设备长时间没有任何反应） 2.帮忙修改邮箱

蓝灯专业版账号Email:  582183684@qq.com
请帮忙将邮箱变更为：528183684@qq.com

因为这两天着急换设备，还请帮忙尽快处理

应用内报告问题的时间:  请根据 https://github.com/getlantern/forum/issues/1840 在应用内上报问题，请填写专业版的email。请在帖子里注明报告的时间。

截图: 
![tim 20180424150910](https://user-images.githubusercontent.com/38683227/39171470-7bee349a-47d1-11e8-8c50-8e6452523f41.jpg)

----
邀请码在本论坛请以签名形式发布或发到其他论坛。具体见 https://github.com/getlantern/forum/issues/3773

#

**Comment by Ghostwithout** [comment]
已更改，谢谢@CrzSeNrM

**Comment by CrzSeNrM** [comment]
感谢

**Comment by stevebanon** [comment]
输入邀请码 YFMF8MJ 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
