### ISSUE TITLE
如果再用什么最优算法忽悠我们,让我们选择不来服务器,我就去网络安监局投诉你们.

### ISSUE THREAD

**Issue by foxiexianmo** [getlantern/forum#9597]
HK服务器是猴子请来逗比的吧.坑爹呢这是,根本就访问不了外网.如果你们再不将默认选择HK这个服务器改成可手选.你们也别想挣钱了.等着被封吧!

**Comment by hub518123** [comment]
蓝灯本来就是GFW重点关注对象，再说了蓝灯本来就是美国的公司你投诉了也没用- -
