### ISSUE TITLE
付费后mac打开lantern一直转圈

### ISSUE THREAD

**Issue by gujiangfei1221** [getlantern/forum#960]
日志文件：
[lantern.log.zip](https://github.com/getlantern/forum/files/409217/lantern.log.zip)

**Comment by p3rcya** [comment]
为什么关闭了？解决了么？

**Comment by gujiangfei1221** [comment]
我电脑的环境是mac，之前安装的老版本（不收费版本），昨晚直接下载了最新版程序覆盖的，然后就出现了打开一直转圈的问题，后来我安装了mac版qq管家，然后用它的软件卸载功能把lantern卸载了，然后再安装最新版就可以了。麻烦你了。
