### ISSUE TITLE
连上蓝灯但是没有办法登陆外网，但是按方法关闭windows防火墙仍然不行，打开网页如以下状态，望教授设置方法 邮箱578046222@qq.com

### ISSUE THREAD

**Issue by guanzhixinn** [getlantern/forum#9609]
修改过一次邮箱地址 原来是578046222@qq.com
现在是posumshawn@163.com

回复请回复到邮箱578046222@qq.com
![-1](https://user-images.githubusercontent.com/38761190/39360451-ddb32d8a-4a50-11e8-93d7-d149a7ba4af6.jpg)
![999999](https://user-images.githubusercontent.com/38761190/39362463-12e4e2ac-4a59-11e8-9174-494b68069626.jpg)
![333333](https://user-images.githubusercontent.com/38761190/39362472-1445ad0c-4a59-11e8-8c93-901753fb4670.jpg)

个人认为是这一条有问题
(如果您的计算机或网络受到防火墙或者代理服务器的保护，请确认 Firefox 已被授权访问网络。)
我的支付数据号码是w146140053

但是不知道如何更改代理服务器或者是防火墙不限制，望及时解决谢谢！

**Comment by Ghostwithout** [comment]
你好，试下到firefox设置里把代理改为“使用系统代理”。谢谢！@guanzhixinn

**Comment by guanzhixinn** [comment]
@Ghostwithout 设置状态之前就按照你们给的那些自己解决的方法做了 是设置的使用系统代理 还是不行的 我觉得不是网页设置问题 因为使用其他网页也是不能连接外网 有没有可能是防火墙的问题啊 虽然我已经把防火墙关闭了 拜托 急

**Comment by guanzhixinn** [comment]
@Ghostwithout 急急急啊 可不可以解决一下啊

**Comment by Chien0719** [comment]
把注册表里的ie设置删了就好了

**Comment by guanzhixinn** [comment]
@Chien0719 可以问问注册表在哪里吗 我不知道 谢谢
