### ISSUE TITLE
蓝灯 国内推广优惠是不是真的 http://www.landengpro.vip/index.php

### ISSUE THREAD

**Issue by duhongle** [getlantern/forum#9628]
蓝灯 国内推广优惠是不是真的 http://www.landengpro.vip/index.php 是不是骗钱网站啊

**Comment by hub518123** [comment]
这个网站应该是蓝灯的代理商吧，从蓝灯哪里低价大批量购买激活码，然后再去卖

**Comment by duhongle** [comment]
推广活动 24月299 相比官网的27个月 336 也木啥优惠，关键是不知道真实度

**Comment by chenzi0103** [comment]
讲道理    大佬们 蓝灯可以打游戏嘛？
