### ISSUE TITLE
链接成功但是无法打开外网 已经关闭防火墙并且修改代理 仍然无法连接 请及时解决！

### ISSUE THREAD

**Issue by guanzhixinn** [getlantern/forum#9629]
修改过一次邮箱地址 原来是578046222@qq.com
现在是posumshawn@163.com

回复请回复到邮箱578046222@qq.com
![39360451-ddb32d8a-4a50-11e8-93d7-d149a7ba4af6](https://user-images.githubusercontent.com/38761190/39397662-c72ea63a-4b35-11e8-9292-7f47c1279199.jpg)
![39362463-12e4e2ac-4a59-11e8-9174-494b68069626](https://user-images.githubusercontent.com/38761190/39397664-c834af0c-4b35-11e8-9517-b91a344f1b2f.jpg)
![39362472-1445ad0c-4a59-11e8-8c93-901753fb4670](https://user-images.githubusercontent.com/38761190/39397667-cb51b694-4b35-11e8-9736-303f3c3ef70f.jpg)
个人认为是这一条有问题
(如果您的计算机或网络受到防火墙或者代理服务器的保护，请确认 Firefox 已被授权访问网络。)
我的支付数据号码是w146140053
是设置的使用系统代理 还是不行 我觉得不是网页设置问题 因为使用其他网页也是不能连接外网 有没有可能是防火墙的问题啊 虽然我已经把防火墙关闭了 拜托 急
![39366712-4afd9de2-4a67-11e8-8b00-235c57c55581](https://user-images.githubusercontent.com/38761190/39397679-f31e7b4e-4b35-11e8-96d3-4fffa8888748.jpg)
![39366713-4b3bcad6-4a67-11e8-8c3f-b2527e4ca588](https://user-images.githubusercontent.com/38761190/39397680-f45686a0-4b35-11e8-8554-131407b09eed.jpg)

但是不知道如何更改代理服务器或者是防火墙不限制，望及时解决谢谢！

**Comment by PJRay1123** [comment]
本人手机和电脑一样时断时续，根本就是蓝灯的问题，无法正常使用

**Comment by orbancanon** [comment]
@guanzhixinn 请问：
1. 其它被墙的网站能否访问？
1. 国内网站能否正常访问？
1. 试一下https://www.pinterest.com/（注意https）能否访问？

如果1和3都不行，请在Lantern界面上报告问题，并在这里@ 我，谢谢！
