### ISSUE TITLE
Mac os 10.13.4下Lantern闪退，无法使用

### ISSUE THREAD

**Issue by jeremy-wang** [getlantern/forum#9651]
## 遇到的问题：lantern持续闪退

> 系统Mac os 10.13.4版本

> lantern最新版本4.6.9

> 蓝灯专业版账号Email:  wj-reborn@qq.com

## 最近可疑的操作

* 在issue7235中尝试了一下使用电脑来给ios开热点的方式f。

报告时间：2018年5月2日

**Comment by orbancanon** [comment]
@jeremy-wang 你需要按那帖子的办法，重新修改settings.yaml，把addr=xxxx那一行删掉，然后再启动Lantern就可以了。原因是你的网卡地址失效了。

**Comment by jeremy-wang** [comment]
更新了最新版本之后没有闪退的问题了
