### ISSUE TITLE
账号注册时的Email被微软停用，需要重新修改邮箱地址。

### ISSUE THREAD

**Issue by cqr262934173** [getlantern/forum#9665]
遇到的问题：因为在注册蓝灯用户时，使用的邮箱地址cqr262934173@msn.cn被微软公司停用，强制将以前的邮箱地址变更为cqr262934173@outlook.com，导致邮箱变更之后没有办法登录蓝灯VPN，所以请官方把邮箱地址从cqr262934173@msn.cn更改到cqr262934173@outlook.com。

蓝灯专业版账号Email: cqr262934173@msn.cn

**Comment by Ghostwithout** [comment]
麻烦提供下购买凭证，核实后可更改。谢谢！ @cqr262934173

**Comment by cqr262934173** [comment]
@Ghostwithout  购买的订单号为w131065155
