### ISSUE TITLE
账号注册时的Email被微软停用，需要重新修改邮箱地址。

### ISSUE THREAD

**Issue by cqr262934173** [getlantern/forum#9672]
遇到的问题：因为在注册蓝灯用户时，使用的邮箱地址cqr262934173@msn.cn被微软公司停用，强制将以前的邮箱地址变更为cqr262934173@outlook.com，导致邮箱变更之后没有办法登录蓝灯VPN，所以请官方把邮箱地址从cqr262934173@msn.cn更改到cqr262934173@outlook.com。

蓝灯专业版账号Email: cqr262934173@msn.cn
购买的订单号：w131065155

![image](https://user-images.githubusercontent.com/33771066/39586914-df881024-4f2a-11e8-94c2-42ac644755bb.png)

**Comment by Ghostwithout** [comment]
你好，抱歉没能及时回复，已经更新为cqr262934173@outlook.com，请核实。谢谢！ @cqr262934173

**Comment by cqr262934173** [comment]
已经更改完成，谢谢。


________________________________
发件人: Ghostwithout <notifications@github.com>
发送时间: 2018年5月6日 20:35
收件人: getlantern/forum
抄送: cqr262934173; Mention
主题: Re: [getlantern/forum] 账号注册时的Email被微软停用，需要重新修改邮箱地址。 (#9672)


你好，抱歉没能及时回复，已经更新为cqr262934173@outlook.com<mailto:cqr262934173@outlook.com>，请核实。谢谢！ @cqr262934173<https://github.com/cqr262934173>

―
