### ISSUE TITLE
SSR, 30ms的延时，来合租

### ISSUE THREAD

**Issue by algernonsmith** [getlantern/forum#9683]
自己的服务器，网速稳定，基本没有出过问题，1080P的视频几乎秒开，平时的4g手机网大概2-3m/s 的网速，这基本就可以看任何视频了，可以试用账号，
另外还搭建了一个 延时30ms的服务器， 可以代理游戏，比如韩服吃鸡基本不延时，我试过，这个服务器就比较极端了，4K也秒开

# **wechat ： x-lin0914**

![ping](https://user-images.githubusercontent.com/38640620/39634135-8b1f8be4-4fec-11e8-9c7f-de89896ba8c6.png)

**Comment by LannYuu** [comment]
多少钱

**Comment by unco2** [comment]
多少钱

**Comment by algernonsmith** [comment]
加我微信
