### ISSUE TITLE
升级到3.0.10，不画圈了，没法输码xp sp3

### ISSUE THREAD

**Issue by zhrxx444** [getlantern/forum#970]
![1_](https://cloud.githubusercontent.com/assets/20348958/17575911/2635234e-5fa0-11e6-9f87-fe74dd8de824.jpg)

**Comment by p3rcya** [comment]
请按照此帖上传日志 https://github.com/getlantern/forum/issues/358 ，方便我们调查，谢谢

**Comment by zhrxx444** [comment]
不画圈了，可是没地方输入验证码

**Comment by zhrxx444** [comment]
![2](https://cloud.githubusercontent.com/assets/20348958/17576122/0fdbef54-5fa2-11e6-8631-f95d832b222e.JPG)

**Comment by unever** [comment]
我去，竟然。。。竟然是XP。

**Comment by zhrxx444** [comment]
xp咋了

**Comment by zhrxx444** [comment]
xp咋了

**Comment by p3rcya** [comment]
@zhrxx444 必须在已登陆专业版的设备上输入

**Comment by zhrxx444** [comment]
360自动清除LANTERN,怎么办

**Comment by p3rcya** [comment]
加白名单，或者卸载360

**Comment by zhrxx444** [comment]
安卓手机也没有输入动态授权码的地方啊，手机已登录

**Comment by p3rcya** [comment]
手机请升级到最新版

**Comment by Christophashjz** [comment]
什么叫已登录专业版的的设备呀？点击登陆专业版弹出的不就是授权码吗？

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
