### ISSUE TITLE
管理员你好。我的账号找不到了。不知是之前填错了还是代理商没登记

### ISSUE THREAD

**Issue by ccwxning1989** [getlantern/forum#9732]
请帮我改成19070766@qq.com的账号登录，备用为ccwxning1989@gmail.com.
Order w129720597

对方：Paymentwall Inc.

流水号：2017101521001003330252239669

订单金额： 32.83 USD

汇率： 1 USD = 6.60787000 人民币元

![b3d_cb c nevn 0vqd1 x9](https://user-images.githubusercontent.com/38188414/39811541-9448c974-53bb-11e8-86df-7697b26698b2.png)
![b3d_cb c nevn 0vqd1 x9](https://user-images.githubusercontent.com/38188414/39811566-a7b730a4-53bb-11e8-954f-7cbeaaf7dae0.png)

请在发帖前先按照蓝灯无法使用的解决办法 https://github.com/getlantern/forum/issues/1902 自行解决。自行解决问题通常只需要几十分钟。管理员调查解决问题需要几天至几周。请立即访问https://github.com/getlantern/forum/issues/1902 瞬间解决98%的问题

为了能在最快的时间内解决大家使用蓝灯遇到的问题，请各位用户严格按照发帖格式提交问题。

## 发帖格式
遇到的问题：请详细描述遇到的问题。如果描述不仔细，将无法调查

蓝灯专业版账号Email:  请提供登陆蓝灯专业版的email，免费版不提供技术支持。

应用内报告问题的时间:  请根据 https://github.com/getlantern/forum/issues/1840 在应用内上报问题，请填写专业版的email。请在帖子里注明报告的时间。

截图: 请提供有关问题的截图。 请把图片拖拽到这里。

----
邀请码在本论坛请以签名形式发布或发到其他论坛。具体见 https://github.com/getlantern/forum/issues/3773

**Comment by Ghostwithout** [comment]
@ccwxning1989 你好，注册的邮箱是2971186352@qq.com，由于qq邮箱会屏蔽部分验证邮件，为你改为ccwxning1989@gmail.com，谢谢！
