### ISSUE TITLE
🙏尊敬的蓝灯管理员，麻烦帮忙修改邮箱📮，谢谢你！

### ISSUE THREAD

**Issue by seingshinlee** [getlantern/forum#9740]
**尊敬的蓝灯管理员：
&emsp;&emsp;你好，因为原先的QQ邮箱无法接收验证码，且用于购买专业版账户的原邮箱`seungshinlee@qq.com`打错了一个字母，应该是要`i`而不是`u`，所以希望你帮我修改一下为新邮箱`seingshinlee@gmail.com`，谢谢你！**

---
**交易凭证**
![issue](https://user-images.githubusercontent.com/26791838/39867729-e1412794-5488-11e8-8abd-1ffb268d6473.jpg)
<img width="641" alt="lanternclients" src="https://user-images.githubusercontent.com/26791838/39867782-2fd4a912-5489-11e8-874a-e74f7b22323c.png">

**Comment by Ghostwithout** [comment]
你好，已经更改为seingshinlee@gmail.com，请核实。谢谢！ @seingshinlee
