### ISSUE TITLE
蓝灯管理员，您好，麻烦帮忙修改邮箱，谢谢你！

### ISSUE THREAD

**Issue by 875983103** [getlantern/forum#9749]
尊敬的蓝灯管理员：
  你好，因为原先的QQ邮箱无法接收验证码，且用于购买专业版账户的原邮箱875983103@q.com少打了一个字母，应该是@qq.com而不是@q.com，所以希望你帮我修改一下为新邮箱875983103@qq.com，谢谢你！

**Comment by Ghostwithout** [comment]
你好，已经更改为875983103@qq.com，但是QQ/Foxmail会屏蔽部分验证码邮件，如果是QQ邮件，建议多试几次。谢谢！ @875983103
