### ISSUE TITLE
已授权使用的专业设备，不能解除绑定？

### ISSUE THREAD

**Issue by wenyuanrui** [getlantern/forum#9777]
已授权使用的专业设备，不能解除绑定？点解绑，无效
![image](https://user-images.githubusercontent.com/37317321/39977591-9d5cc8ac-576d-11e8-8d65-7aac50e1db37.png)

**Comment by Ghostwithout** [comment]
你好，请在你要保留设备的lantern界面，选择账户管理，解绑需要解绑的设备。谢谢！ @wenyuanrui

**Comment by wenyuanrui** [comment]
可以了，是延迟造成的
