### ISSUE TITLE
出售蓝灯账号，2019/12/7过期，还有19个月，价钱预估150左右！

### ISSUE THREAD

**Issue by HonorKY** [getlantern/forum#9779]
因为不在需要使用蓝灯，还有19个月过期，出售价格可商量，预估150元左右，可闲鱼，需要的加QQ1131482955，请说明来意。

**Comment by zhumingzhe8888** [comment]
租账号 一个月10块 一季度20 有两个坑位可以租 方便大家试用一下再决定是否要买 wx 627909837
