### ISSUE TITLE
请问专业版有没有别的授权方式？

### ISSUE THREAD

**Issue by yueqianzhang** [getlantern/forum#978]
lantern的开发者们你们好,
用起来很方便，买了两年，
（吐槽一下：）
但是就是感觉账号管理机制太不科学了。。
一种没有保障的感觉，填写的邮箱没什么用，最开始填写的时候也没让验证邮箱。。
可能你们有自己的考虑。。

**Comment by p3rcya** [comment]
我也这么觉得。我觉得用户名和密码更好，但是其他开发人员认为用户密码不好。 如果你会英文的话，可以去 https://github.com/getlantern/lantern/issues/5146 留言

**Comment by p3rcya** [comment]
见这里 https://github.com/getlantern/forum/issues/980

**Comment by user-evan-chen** [comment]
@p3rcya 授权成功。请等待您的设备自动成为专业版。

然后就是 获取动态授权码错误！请稍候重试。输入错误：硬件ID应该是整数

我想说，付费之后真是各种不行。完全体现不出付费的优势在哪儿了？

**Comment by p3rcya** [comment]
[无法登陆的情况请报告到汇总贴, 说明详情](https://github.com/getlantern/lantern/issues/5146#issuecomment-239110555) 并发邮件到myles@getlantern.org 我们集中解决。

必须反馈到以上给美国的开发者，最好用英文（可以机器翻译），中文也可以。
我个人没有退款权限，没有退款权限，没有退款权限！只有美国的开发者能修改登陆方式，或者退款。

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
