### ISSUE TITLE
下载页面打不开

### ISSUE THREAD

**Issue by onlyatryyouknow** [getlantern/forum#979]
无论是蓝灯中国站还是蓝灯官方下载页面 桌面版点下载地址或备用地址一律白屏。。。

**Comment by p3rcya** [comment]
这里的地址你不行么？ https://github.com/getlantern/forum/issues/833

**Comment by onlyatryyouknow** [comment]
不行

**Comment by p3rcya** [comment]
备用地址也不行么？

**Comment by onlyatryyouknow** [comment]
但是移动版可以 我就先下了移动版 然后邮件发送试了一下 结果还是不行 点击就白屏……
另外手机端换了个新版本之后好像就得重新绑定……可是我电脑还是旧版本 根本没有手机上最新版本说的  “点击菜单中的 授权其它设备使用专业版”…………

**Comment by onlyatryyouknow** [comment]
不行 我一楼说的很清楚啦
……请问有谁能直接发个安装包吗？上网找了下也没有现成的

**Comment by onlyatryyouknow** [comment]
……杀了毒 重启了电脑 重启了路由器 翻墙下 不翻墙下 都白屏……工作人员有解决方法吗？暂时没有的话可不可以直接给我邮箱发安装包？music_miss@outlook.com 已经是专业版用户了

**Comment by onlyatryyouknow** [comment]
抱歉……总之问题解决了 但是不知怎么删帖 麻烦工作人员删帖了……

**Comment by GD-HBX** [comment]
@onlyatryyouknow 下方“close”
