### ISSUE TITLE
讲真 能不能让用户自行选择服务器？

### ISSUE THREAD

**Issue by AyaseCore** [getlantern/forum#9794]
我这线路老是切来切去的 玩游戏老掉线.
而且一旦切到jp基本连不上
说实话能不能走点心？
现在基本一换到jp就没法用了.我就只能换无码用。人家免费都比这好.虽然有广告但是能接受
但是你的这花钱的.
线路老切换 或者换到jp完全连不上叫什么事.
花钱还这么坑的吗？

**Comment by Pazuo** [comment]
我这个玩游戏好像不太行啊，上网看视频还好，是切换到JP的原因吗 ？

**# 输入我的邀请码   JTCU99   来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum**

**Comment by AyaseCore** [comment]
算了就这样吧. 😫 这售后服务态度也是一绝.
