### ISSUE TITLE
认为蓝灯专业版登陆方式很奇葩，动态授权码不会用，邮箱验证码收不到的请进

### ISSUE THREAD

**Issue by p3rcya** [getlantern/forum#980]
我个人认为3.1.0现在这个登陆方式比较奇葩，登陆过程见 https://github.com/getlantern/forum/issues/973
我认为用户名＋密码登陆直截了当，希望开发者更改。

但是国外的开发者不了解国情，认为用户名和密码不好，坚持使用其他的奇葩方式。 如果各位想要蓝灯支持用户名＋密码登陆，请去 https://github.com/getlantern/lantern/issues/5146 回帖和我们的开发者 @myleshorton 反馈，中英文都可以，强烈要求他们改为用户名＋密码登陆。

大家去 https://github.com/getlantern/lantern/issues/5146 回复的多了，蓝灯以后就会支持用户名＋密码了。 动态授权码不会用，邮箱验证码收不到的，统统去 https://github.com/getlantern/lantern/issues/5146 回帖。 这不是我的决定，你们要大量让其他开发者看到你们想要使用用户名＋密码，不想要其他登陆方式，他们才会改变这个决定

**Comment by EdwardAutumn** [comment]
这种东西去撕逼的确定不是闲得慌。谁没事总去改设备

**Comment by EdwardAutumn** [comment]
说实话我个人就喜欢这种方式，不然又让我创建一个账户密码不好管理，每次我都要想个随机密码，然后记在记事本里，基本上不会常用而且自己也记不住，很讨厌管理这些，统一一个账号对我来说是最好的。

**Comment by unever** [comment]
本来没觉得有什么问题，但是今天更新3.10后，我认为目前这样的方式体验非常差，如果在外面，临时要用，身边没有已授权的设备，是无法使用的，这样很不好，账户密码会更方便，安全是个问题，但在一定阶段，它不是问题。

@EdwardAutumn 账户密码一样是一个账号，也不用你管理。

**Comment by aaazz47** [comment]
3.1的授权方式感觉确实有点麻烦。比如我家里有台电脑购买了授权，但是公司电脑也要用，这样同时操作两台距离较远的设备就特别不方便。
我到是理解3.0的邮箱授权方式，大家可能会使用一些墙内的邮箱服务，导致收不到蓝灯的邮件，或者因为蓝灯服务器短时间发布了大量授权邮件导致白名单联盟自动封禁了发出的邮件信息。所以更换了授权方式。

但是这种用一个设备授权另外一个设备的方式确实很不方便。建议最好能保留两种授权方式。

另外，用户名+密码
感觉安全性差，完全可以黑掉几个账户来刺探付费服务器的IP，着违背官方收费的初衷。黑账号感觉难度还是小一点。不过这种形式用户体验最高。

**Comment by AmosStern** [comment]
同感，在一台电脑上用过之后不知道下一台设备应该怎么登陆了；

强烈建议开发者增加用户名+密码的登录方式

**Comment by zhcaa** [comment]
同感，在一台电脑上用过之后不知道下一台设备应该怎么登陆了；

强烈建议开发者增加用户名+密码的登录方式   



同一楼上的

**Comment by Jason-Lie** [comment]
需要账号密码登陆方式，请求改为通知在线最大允许3台设备！不然有时候外出的时候很不方便！！！！授权3台太坑了，完全不了解中国行情吗这是？

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)

**Comment by Frozensunshine** [comment]
是的，今天刚在电脑上升级到专业版，可是在android平板上无法获取动态验证码，也就无法升级到专业版。说好的可以在三台设备上使用，做不到啊！
