### ISSUE TITLE
授权成功。请等待您的设备自动成为专业版。然后，就没有然后了……

### ISSUE THREAD

**Issue by user-evan-chen** [getlantern/forum#981]
付费了之后真心累。我就说开发们没有把精力放在如何保证通畅性和服务质量的提升，天天变着花的在搞这种授权验证，结果还是不通的……

我想静静……

**Comment by crest0806** [comment]
没用过这么麻烦的代理，今天冲着口碑选择了lantern 一年的vip,速度奇慢无比，手机也无法授权，早知道这样，就是倒贴我200也不愿意尝试  @p3rcya

**Comment by unever** [comment]
手机同样无法授权。

@crest0806 我这边速度非常快，youtube 1080P都是没问题的。

**Comment by p3rcya** [comment]
[无法登陆的情况请报告到汇总贴, 说明详情](https://github.com/getlantern/lantern/issues/5146#issuecomment-239110555) 并发邮件到myles@getlantern.org 我们集中解决。

必须反馈到以上给美国的开发者，最好用英文（可以机器翻译），中文也可以。
我个人没有退款权限，没有退款权限，没有退款权限！只有美国的开发者能修改登陆方式，或者退款。

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
