### ISSUE TITLE
@p3rcya 【急】我已经买了专业版，手机版卸载后，重新安装后，怎么还让我买呢，怎么重新授权呀？

### ISSUE THREAD

**Issue by cunzai2016** [getlantern/forum#982]
我已经买了专业版，卸载后，重装后怎么还让我买呢，怎么重新授权呀？

**Comment by cunzai2016** [comment]
没人管吗？

**Comment by Boss198** [comment]
免费版已经从305开始，我这就用不了。希望了，太希望了

**Comment by Hwatu** [comment]
不敢升级...等你们先测试好了,我在升级

**Comment by p3rcya** [comment]
[无法登陆的情况请报告到汇总贴, 说明详情](https://github.com/getlantern/lantern/issues/5146#issuecomment-239110555) 并发邮件到myles@getlantern.org 我们集中解决。

必须反馈到以上给美国的开发者，最好用英文（可以机器翻译），中文也可以。
我个人没有退款权限，没有退款权限，没有退款权限！只有美国的开发者能修改登陆方式，或者退款。

**Comment by xyuanmu** [comment]
先下载旧版本登录再升级覆盖，我只有安卓的安装包。
[lantern-installer-3.0.12.zip](https://github.com/getlantern/forum/files/415098/lantern-installer-3.0.12.zip)

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
