### ISSUE TITLE
@p3rcya 【急】已买专业版后，但安卓版(Android)的重装后，专业版的标记就没有了，还让重新买,请解决一下

### ISSUE THREAD

**Issue by cunzai2016** [getlantern/forum#983]

**Comment by cunzai2016** [comment]
有个解决吗？难道都是骗子

**Comment by Hwatu** [comment]
是啊,我现在不敢升级

**Comment by onlyatryyouknow** [comment]
是的……同求

**Comment by p3rcya** [comment]
[无法登陆的情况请报告到汇总贴, 说明详情](https://github.com/getlantern/lantern/issues/5146#issuecomment-239110555) 并发邮件到myles@getlantern.org 我们集中解决。

必须反馈到以上给美国的开发者，最好用英文（可以机器翻译），中文也可以。
我个人没有退款权限，没有退款权限，没有退款权限！只有美国的开发者能修改登陆方式，或者退款。

**Comment by jiangchenxi** [comment]
已经购买专业版 重装了一下蓝灯后登录就让从其他已经授权的机子上授权当前的 可我没有其他已经授权的 
怎么办

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
