### ISSUE TITLE
是不是全退出了就永远也登不上了？？？

### ISSUE THREAD

**Issue by xxl594482971** [getlantern/forum#984]
已经全退出了。。。。。。。

**Comment by Hwatu** [comment]
哈哈...默哀!
@p3rcya  请解决一下吧.我现在也不敢升级到3.1.0 
怕怕

**Comment by junecwf** [comment]
我也很好奇是不是这样的，全退出去了，怎么接受动态码啊，邮箱还可以吗，哈哈

**Comment by junecwf** [comment]
@p3rcya

**Comment by p3rcya** [comment]
[无法登陆的情况请报告到汇总贴, 说明详情](https://github.com/getlantern/lantern/issues/5146#issuecomment-239110555) 并发邮件到myles@getlantern.org 我们集中解决。

必须反馈到以上给美国的开发者，最好用英文（可以机器翻译），中文也可以。
我个人没有退款权限，没有退款权限，没有退款权限！只有美国的开发者能修改登陆方式，或者退款。

**Comment by talvi117** [comment]
装回旧版，用邮箱验证完，不要卸载直接安装新版覆盖

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
