### ISSUE TITLE
付费用户无法登陆专业版 - 已解决

### ISSUE THREAD

**Issue by talvi117** [getlantern/forum#985]
rt，下午刚刚购买了专业版，但是无法上网，分别重装了lantern和浏览器之后，现在点授权就不停转圈圈。另外现在版本仅支持动态码验证吗？没有登陆过其他设备岂不是根本用不了(试着换了3.0.7用邮箱验证，在提交验证码那一步也是不停转圈)
[lantern.txt](https://github.com/getlantern/forum/files/412889/lantern.txt)

8/12 更新：
曲线救国的方法就是用之前的版本的邮箱验证码登陆，亲测用3.0.7今天解决了转圈问题能登陆了，之后再次安装3.1.1覆盖之后能正常使用专业版。希望后续版本给力吧。

**Comment by GeekerAndyLove** [comment]
同问
I have the same problem... Is there any way to solve it??

**Comment by p3rcya** [comment]
请去这里描述详细情况并报告 https://github.com/getlantern/lantern/issues/5146

**Comment by user-evan-chen** [comment]
Android 从来就没有成功过！

**Comment by p3rcya** [comment]
[无法登陆的情况请报告到汇总贴, 说明详情](https://github.com/getlantern/lantern/issues/5146#issuecomment-239110555) 并发邮件到myles@getlantern.org 我们集中解决。

必须反馈到以上给美国的开发者，最好用英文（可以机器翻译），中文也可以。
我个人没有退款权限，没有退款权限，没有退款权限！只有美国的开发者能修改登陆方式，或者退款。

**Comment by talvi117** [comment]
@p3rcya 曲线救国的方法就是用之前的版本的邮箱验证码登陆，亲测3.0.7今天能正常登陆了。希望后续版本给力吧。

**Comment by GD-HBX** [comment]
唔系挂，依家最新版只有授权码的方式？我以为是邮箱和授权码两种方式并存呢...

**Comment by GeekerAndyLove** [comment]
@talvi117 关掉杀毒软件，裸奔的话一定关掉windows defender, 我之前一直也是，虽然没关连上过，但这次转圈圈关掉立马就能连上最新版

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
