### ISSUE TITLE
手机端频繁掉线的问题不应该快点解决么

### ISSUE THREAD

**Issue by EdwardAutumn** [getlantern/forum#991]
被这个问题折磨很久了，用着用这就不能翻墙了，这个问题是自从上个月购买专业版一直存在，一直没解决，能给个技术人员的解答么？也省得我频繁的发送日志

**Comment by EdwardAutumn** [comment]
@p3rcya

**Comment by p3rcya** [comment]
他们都集中精力在修改登陆方式上面了，所以你这个得等等

**Comment by EdwardAutumn** [comment]
这不是给自己挖坑么，改之前早问一下不得了

**Comment by p3rcya** [comment]
对啊，我早就说了啊，国外开发者不相信

**Comment by p3rcya** [comment]
已经和美国的程序员撕逼很多次，警告他们这样很多用户绝对不会登陆，他们不相信，那我也没办法喽

**Comment by EdwardAutumn** [comment]
开发组人员还是没有做商业软件的经验，也不怪他们。现在只希望正式版快速上线，蓝灯现在速度还是比较快的，但是这个掉线真的有点不能忍

**Comment by joefei** [comment]
这个蓝灯项目的开发模式到底是咋样的？是志愿者的组织开发的，还是专门的公司团队开发的。

**Comment by p3rcya** [comment]
公司开发的，但是美国团队，开发者不懂中国环境

**Comment by xxl594482971** [comment]
@p3rcya 是不是登录问题马上能解决了？ 我现在全部退出了登不上啊！！！

**Comment by p3rcya** [comment]
@xxl594482971 [无法登陆的情况请报告到汇总贴, 说明详情](https://github.com/getlantern/lantern/issues/5146#issuecomment-239110555) 并发邮件到myles@getlantern.org 我们集中解决。

必须反馈到以上给美国的开发者，最好用英文（可以机器翻译），中文也可以。
我个人没有退款权限，没有退款权限，没有退款权限！只有美国的开发者能修改登陆方式，或者退款。

**Comment by zsqp447** [comment]
@p3rcya 最关键的速度问题不优先解决，真是令人捉急。
说实话看到管理员发公告让我们退款，我很寒心，我在海外小工作段时间，以我对老外做商业产品的理解，遇到问题不会轻易承诺退款，而是想办法解决问题，问题较大的则提供补偿，就像lantern现在做的一样，增加赠送时间是很合理的补偿。但lantern现在说可以退款了，那给我感觉就是放弃了，GFW兵不血刃获得大胜。真是越想越气，我特么对lantern还有信心结果lantern自己没信心了，如果退款通道正式打开，我将毫不犹豫退款。**退款也许是一种补偿方法，但这是走投无路时的下下策，是对责任的逃避，解决速度问题，提高补偿才是王道。**

**Comment by unever** [comment]
@zsqp447 管理员啥时候说让你们退款了，公告也不是这么说的啊。

**Comment by p3rcya** [comment]
我们会解决速度问题的，请放心

**Comment by ivanbirth851230** [comment]
楼主 你用的什么登陆 是电脑还是手机 发现速度快的呢

**Comment by EdwardAutumn** [comment]
手机电脑都快啊。

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
