### ISSUE TITLE
(已出) 出售坑位 90元=12个月， 30元=1季度，10元=1个月

### ISSUE THREAD

**Issue by RadditPig** [getlantern/forum#9912]
需要联系QQ: **NTczNjgyNTMy**

[QQ解码地址](http://tool.oschina.net/encrypt?type=3)

看到类似帖子,觉得闲置有点可惜,所以发个帖

**Comment by RadditPig** [comment]
s's's

**Comment by y976362357** [comment]
我这里也有坑位出租。90元=12个月， 30元=1季度，10元=1个月

**Comment by caizilisi** [comment]
我想要入坑位- -可是你的QQ是代码。。。联系我 wechat：louismakeup
