### ISSUE TITLE
动态码授权，怎么输入，没地方输入啊，还是用不了

### ISSUE THREAD

**Issue by Boss198** [getlantern/forum#998]
动态码授权，怎么输入，没地方输入啊，还是用不了
公司网络屏蔽也突破不了？以前304及以前的版本可以用，好得很，305开始就没几几用了，因为根本就用不了！...
是不是要购买后，才能输入？
我是繁体win7专业版系统：
![hyuj](https://cloud.githubusercontent.com/assets/19481181/17641682/faad10e2-615c-11e6-8a0e-1a8265820f84.jpg)
![uytr](https://cloud.githubusercontent.com/assets/19481181/17641939/87144ec0-6166-11e6-8aa7-827437e0ea93.jpg)

[lantern.log.zip](https://github.com/getlantern/forum/files/416455/lantern.log.zip)

**Comment by p3rcya** [comment]
无法登陆的情况请报告到汇总贴 https://github.com/getlantern/lantern/issues/5146 说明详情，并发邮件到myles@getlantern.org 我们集中解决。我们集中解决。

**Comment by cacaca222** [comment]
突然感觉有点后悔了。。。。。从开始各种收不到验证码,到后面卡的不行 在到后面 都不怎么卡了。。现在直接搞了个这个 本来这软件就是提供给网络封锁的国家的人的 必然使用的人肯定只占小部分 现在来个需要在专业版的基础上授权   难道还让我在大街上问谁买没买这个lantern 或者还是说是变相为了挣钱？ 本来之前就寻思买SS还是这个 后面觉得 这软件都免费用了1年左右了 感觉有必要支持下 现在这样搞有点不明白@p3rcya

**Comment by p3rcya** [comment]
[蓝灯专业版无法登陆的问题已经解决，无法登陆的请点这里](https://github.com/getlantern/forum/issues/1107)
