### ISSUE TITLE
之前添加的设备现在不用了，但是无法移除

### ISSUE THREAD

**Issue by ZhuLinYuWeng** [getlantern/forum#9982]
我的邮箱是qinweibob@icloud.com，希望能够帮忙移除设备

>

**Comment by Ghostwithout** [comment]
你好，
删除设备请参考如下两种方法“：
1. 请到需要删除的设备“账户管理”界面，选择退出
2.请到需要保留的设备“账户管理”界面， 删除要移除的设备 @ZhuLinYuWeng

**Comment by ZhuLinYuWeng** [comment]
已经解决了
