### ISSUE TITLE
付款2天了，还没收到登陆码，这可如何是好啊？急急急！！！

### ISSUE THREAD

**Issue by guymcheers** [getlantern/forum#9988]
付款2天了，还没收到登陆码，这可如何是好啊？急急急！！！2018.6.2 付款的，支付宝在网页版付款的，现在还没收到登陆码，系统说几个小时后会发送登陆码，我把收件箱和垃圾箱全部看了几遍，现在还没收到！

**Comment by guymcheers** [comment]
很着急，不知如何联系官方，我6.3给他们的support@getlantern.org发了邮件，也是没有任何回复。

**Comment by Ghostwithout** [comment]
@guymcheers 你好，请问你反馈的邮箱是多少，或者提供购买凭证以便查询。
正常情况下购买后会自动升级为专业版，你可以看下你的lantern界面是否显示有效期或帐号管理中显示你的注册邮箱，如果显示就已经是专业版了，如果要授权设备，可参照如下两种方法：
－在新设备lantern界面左边菜单点击“授权设备使用专业版”，在里面输入购买时的邮箱，验证码就会发到你的邮箱，然后输入验证码即可； 
－在新设备选择“授权设备使用专业版”，该界面会收到验证码，然后请到专业版设备输入验证码。谢谢！

**Comment by guymcheers** [comment]
@Ghostwithout 太感激了，按照您的方法，我已经找到码了，现在可以登录了。论坛真的神奇

**Comment by jasonguo203** [comment]
@Ghostwithout 您好 我的是显示找不到email对应的账号
